- Makefile
- frontend/device/android/device.lua
- frontend/device/android/powerd.lua
- frontend/device/cervantes/device.lua
- frontend/device/cervantes/powerd.lua
- frontend/device/generic/device.lua
- frontend/device/generic/powerd.lua
- frontend/device/input.lua
- frontend/device/kindle/device.lua
- frontend/device/kindle/powerd.lua
- frontend/device/kobo/device.lua
- frontend/device/kobo/powerd.lua
- frontend/device/pocketbook/device.lua
- frontend/device/pocketbook/powerd.lua
- frontend/device/remarkable/device.lua
- frontend/device/remarkable/powerd.lua
- frontend/device/sdl/device.lua
- frontend/device/sdl/powerd.lua
- frontend/device/sony-prstux/device.lua
- frontend/device/sony-prstux/powerd.lua
- frontend/ui/uimanager.lua
- spec/unit/device_spec.lua
Make sure we only send Suspend/Resume events when we *actually* suspend/resume. This is done via the Device `_beforeSuspend`/`_afterResume` methods, and those were called by the *input handlers*, not the PM logic; which means they would fire, while the PM logic could actually take a smarter decision and *not* do what the event just sent implied ;).
(i.e., sleep with a cover -> suspend + actual suspend, OK; but if you then resume with a button -> input assumes resume, but PM will actually suspend again!).
Existing design issue made more apparent by #9448 ;).
Also fixes/generalizes a few corner-cases related to screen_saver_lock handling (e.g., don't allow USBMS during a lock).
And deal with the fallout of the main change to the Kobo frontlight ramp behavior ;).
- - - …
> PM: Minor refactor to suspend/resume code flow

- frontend/ui/wikipedia.lua
See https://github.com/koreader/koreader/issues/10459#issuecomment-1554169852.
Closes #10459.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10462)
> Wikipedia EPUBs: strip out invalid-XHTML <link>

- frontend/apps/reader/modules/readerhighlight.lua
Regression after https://github.com/koreader/koreader/pull/10438.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10469)
> ReaderHighlight: fix translator auto lang for fragment

- frontend/ui/widget/container/inputcontainer.lua
- frontend/ui/widget/notification.lua
Notification is a toast, so it doesn't stop event propagation. If we don't disable those handlers inside Notification, we get spurious duplicate handlers being fired ;).
Fix #10461
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10471)
> Notification: NOP conflicting event handlers from our base class

- frontend/device/pocketbook/device.lua
Can't test as I don't have the device, but per #10444 should be fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10468)
> Add PB Inkpad 4

- frontend/device/pocketbook/device.lua
PocketBook InkPad 4 = Modell: PB743**g**, not PB743G
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10481)
> PB: Add Inkpad 4

- frontend/document/documentregistry.lua
`DocSettings:hasSidecarFile()` returns string (path to the sidecar file), not boolean.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10478)
> DocumentRegistry: fix getRandomFile()

- frontend/readcollection.lua
If a file has been deleted outside of KOReader, its entry remains in Collection list and in coverbrowser bookinfo sql.
So listmenu tries to build the full entry with the mandatory containing filesize (which is `false`).
After this fix the file entry will be displayed dimmed (as for deleted files), with metadata but without filesize.
Then a user should take care of this entry manually:
-remove it from the Collection, or
-refresh cached book info (after that listmenu will show the filename only with a hint (deleted))
Closes https://github.com/koreader/koreader/issues/10487.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10488)
> Collections: fix crash on showing deleted file entry

- frontend/dispatcher.lua
Fix showing action values:
-when an action has both a toggle and a spinwidget, and the value is not equal to any arg of the toggle
-when an action has a toggle and a unit, and the toggle is not a number
Before / after
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10495)
> Profiles: fix showing some bad values

- frontend/device/kindle/powerd.lua
sometimes my kindle fires the rtc alarm a tad too late so use a more generous timeout
the real fix would be to have validateWakeupAlarmByProximity return differently if the alarm is past or in the future, but i am too lazy
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10486)
> WakeupMgr: kinde: use a 90 sec proximity

- frontend/dispatcher.lua
The PR is discussible, maybe a user should take care of his profiles himself? @yparitcher
The same profile with mixed actions in:
FM
cre
pdf
Closes https://github.com/koreader/koreader/issues/10493.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10500)
> Profiles: disable inapplicable actions in QuickMenu

- frontend/dispatcher.lua
- frontend/ui/widget/buttondialog.lua
(1) In https://github.com/koreader/koreader/pull/10424 we've got a beautiful scrollable ButtonDialog.
Let's just add a title to it and replace ButtonDialogTitle with it (step by step, everywhere).
(2) Tall QuickMenues are now scrollable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10528)
> QuickMenu: scrollable

- frontend/apps/reader/modules/readerthumbnail.lua
- frontend/dispatcher.lua
- frontend/ui/widget/bookmapwidget.lua
- frontend/ui/widget/pagebrowserwidget.lua
Discussed all along #10433. Closes #10433.
Also fix possibly unbalanced left and right margins.
Align page numbers (the vertical ones, on the left of a BookMapRow) on the baseline of the BookMapRow, where page slots rise from.
Also tweak the page number spike below the baseline used in PageBrowser.
Enabled by default, to get the current behaviour.
Disabling it allows people with small fingers to jump directly to that page in Reader.
Allows hairy-boxes amateurs to get small markers (under the baseline) every 10 pages (with -/+ to get small or medium markers, with optionally smaller ones every 5 pages).
Add a restricted but convenient mode showing BookMap like in initial view, while still allowing chapter levels to be tweaked. This allows getting back to this view with another gesture to …
> BookMap: visual tweaks and enhancements

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagerutil.lua
- plugins/coverbrowser.koplugin/covermenu.lua
(1) New file popup dialog buttons:
-History: `Add/remove to/from favorites`
-History, Favorites: `Show folder`
(2) Favorites: new left titlebar menu with
`Add/remove current book to/from favorites`
`Add a book to favorites` - choose a book via PathChooser
`Sort favorites` - previously was in the file popup dialog
Closes https://github.com/koreader/koreader/issues/10343. @ichnilatis-gr
File browser
History
Favorites
Favorites (called from FM)
Favorites (called from Reader)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10537)
> File popup dialog buttons

- frontend/device/kobo/powerd.lua
- plugins/autowarmth.koplugin/main.lua
Fixes a regression introduced in #10426, when suspending during night and resuming during daylight.
see https://github.com/koreader/koreader/blob/fc7181419f4be581635295612d279d20381be699/frontend/device/kobo/powerd.lua#L450
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10557)
> [AutoWarmth] Fix resume and frontlight issue

- spec/unit/readerhighlight_spec.lua
The problem stems from <https://github.com/koreader/koreader/pull/10492> but we need the translations to go through.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10559)
> readerhighlight_spec: add #nocov to some highlight tests

- spec/unit/document_spec.lua
Otherwise the test fail in my environment because of some user fonts:
```
./spec/front/unit/document_spec.lua:88: Expected objects to be the same.
Passed in:
(table: 0x7f20c448b498) {
[1] = 'Droid Sans Mono'
*[2] = 'EB Garamond Absinthe'
[3] = 'Fira Code'
[4] = 'Fira Sans'
[5] = 'FiraCode Nerd Font'
[6] = 'FreeSans'
[7] = 'FreeSerif'
[8] = 'Noto Naskh Arabic'
[9] = 'Noto Sans'
[10] = 'Noto Sans Arabic UI'
[11] = 'Noto Sans Bengali UI'
[12] = 'Noto Sans CJK SC'
[13] = 'Noto Sans Devanagari UI'
[14] = 'Noto Serif' }
Expected:
(table: 0x7f20c448b3c0) {
[1] = 'Droid Sans Mono'
*[2] = 'FreeSans'
[3] = 'FreeSerif'
[4] = 'Noto Naskh Arabic'
[5] = 'Noto Sans'
[6] = 'Noto Sans Arabic UI'
[7] = 'Noto Sans Bengali UI'
[8] = 'Noto Sans CJK SC'
[9] = 'Noto Sans Devanagari UI'
[10] = 'Noto Serif' }
``` …
> tests: fix EPUB test

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/reader/modules/readerzooming.lua
- frontend/docsettings.lua
- frontend/document/documentregistry.lua
- frontend/ui/screensaver.lua
- frontend/ui/widget/imageviewer.lua
- frontend/ui/widget/imagewidget.lua
(1) Fix crash on opening an image with "Picture Document" provider.
(2) Add "Image viewer" one-time provider.
Benefits: no record in History, better scaling and rotation comparing to open as a book.
ImageViewer internal changes:
-do not show progress bar if number of images in list is 1
-do not cache local files
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10561)
> Open with: images

- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/readhistory.lua
To give more room for a title. Applicable in Classic and List display modes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10594)
> History: shorten date/time field

- frontend/device/android/powerd.lua
- frontend/device/generic/powerd.lua
- frontend/device/kobo/powerd.lua
Fix #10588
Regression since #10305
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10597)
> PowerD: Unbreak frontlight toggle notifications outside of Kobo

- frontend/device/sdl/device.lua
The emu might enforce window sizes via `EMULATE_READER_W` & `EMULATE_READER_H`, make sure we track those changes.
Requires https://github.com/koreader/koreader-base/pull/1627
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10619)
> SDL: Keep sdl_window state in sync on the emu

- frontend/apps/cloudstorage/webdavapi.lua
To avoid problems with 0 bytes files on upload from device to cloud I suggest to add 'Content-Length' header to upload function. Tested by manually changed `koreader/frontend/apps/cloudstorage/webdavapi.lua` file on Kobo Clara HD. Works fine.
https://github.com/koreader/koreader/issues/10564
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10567)
> Add 'Content-Length' header to WebDAV upload request

- frontend/device/input.lua
Drop the actual slot data storage, in addition to the active references (i.e., drop Input's state in addition to GestureManager's).
Re: #10571
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10612)
> Input: Be more thorough in resetState

- frontend/apps/reader/modules/readercoptlistener.lua
- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerwikipedia.lua
- frontend/device/gesturedetector.lua
- frontend/ui/data/onetime_migration.lua
- frontend/ui/network/manager.lua
- frontend/ui/widget/infomessage.lua
- plugins/kosync.koplugin/main.lua
Fix: #10539, and for context #6489, #6733, #6534
Reorganize and reword most of the settings to make it clear what actually ties into auto sync, and what doesn't. (Specifically, what happens when a pull attempts to sync forward or backward has nothing to do with auto sync, it applies in all cases; while the periodic sync *does* require auto sync).
The main point of contention, though, is that auto sync will now *always* attempt to setup network connectivity (i.e., on resume/suspend/close). Periodic sync will *not* though (the intent being that, if you use periodic sync, you're relying on the activity check to actually keep wifi on at all times)).
Since this may lead to a large amount of nagging about wifi toggles on devices w/ NetworkManager support, it is now *disabled* by default on …
> KOSync: Clarify settings, plus refactor & fixes to make "auto-sync" more reliable

- frontend/dispatcher.lua
- plugins/gestures.koplugin/main.lua
Disabled touch input has become a popular feature. Let's enhance a bit:
-added separate actions "Touch input on", "Touch input off"
-added an option to make a gesture "always active" (even when the touch input is disabled)
This will help in cases like https://github.com/koreader/koreader/issues/10273.
I saw the @NiLuJe 's warning:
https://github.com/koreader/koreader/blob/b8af326836374b82cccdadafef869d1d5decac69/frontend/ui/widget/container/inputcontainer.lua#L296-L306
but couldn't get any errors while testing, at least in a usecase "enable page turns with the bottom edge swipes with disabled touch input".  Maybe I've missed something...
- - - …
> Disabled touch input: always active gestures

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/ui/data/onetime_migration.lua
- frontend/ui/widget/filechooser.lua
As discussed, "access" and "change" dates are useless.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10627)
> FileChooser: Sort by date

- frontend/apps/reader/modules/readerpaging.lua
The `page_positions` array is saved to sdr. The purpose of it is:
https://github.com/koreader/koreader/blob/45428dda49aefdab68cc232e0798ce030c33d531/frontend/apps/reader/modules/readerpaging.lua#L220-L231
In my library I have found a pdf book of 300 pages with all page_positions equal to zero, and this array of 300 zero entries is saved to sdr.
Page_position value depends on the view mode parameters, but we can assume that zero is a frequent case.
So let do not store zeroes in sdr. Nils are handled well already (line 242):
https://github.com/koreader/koreader/blob/45428dda49aefdab68cc232e0798ce030c33d531/frontend/apps/reader/modules/readerpaging.lua#L233-L243
- - - …
> ReaderPaging: do not store zeroes in page_positions

- frontend/device/remarkable/device.lua
As discussed in https://github.com/koreader/koreader/issues/10012#issuecomment-1591810200 the mainline kernel doesn't use `/dev/input/event2`. Let's use the correct path instead.
Unfortunately I'm unable to test against the shipping kernel to know if this path works, but I suspect it doesn't.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10585)
> frontend: remarkable: Support the mainline touchscreen

- frontend/device/android/device.lua
- frontend/device/generic/device.lua
- frontend/ui/otamanager.lua
Poor man implementation since we cannot fullfit https://github.com/koreader/koreader/pull/10610#issuecomment-1608462530
>> EOL devices running the last supported version receive a "you're up to date" while checking updates.
>> EOL devices on previous versions receive an update to last supported version.
So instead, we merge something like this a few days/weeks *before* real deprecation and warn users with EOL devices that the source of trust is in https://github.com/koreader/koreader/wiki/deprecated-devices.
Other platforms can implement their own `isDeprecated` override on the future.
A better approach is very welcome. The same for a future proof client-server implementation.
This one is trivial and tries to prevent some tickets :)
No worries, at some point in 2024 somebody will try to …
> [ota]: deprecation check & notice

- plugins/kosync.koplugin/main.lua
Cf. https://github.com/koreader/koreader/pull/10605#discussion_r1252639047
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10648)
> [i18n]KOSync: use already translated "Not available" instead of "Unavailable"

- frontend/device/pocketbook/device.lua
Extended addition of PocketBook InkPad 4 with firmware later U743g.6.8.885 (PB743G) because its device ID was corrected from PB743g to PB743G by firmware U743g.6.8.1719.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10655)
> Extended addition of PocketBook InkPad 4 (PB743G)/(PB743g)

- frontend/device/gesturedetector.lua
- frontend/dispatcher.lua
In the process of looking over the "swipe reports the *contact* point (i.e., gesture *start*) as `pos` while pretty much everything else reports the *lift* point (i.e., gesture *end*)" for the QuickMenu anchoring thingy, I realized that the two-finger variants of the pans & swipes were doing things... differently (by always using the "swipe" semantics, which effectively means that two_finger_pan reports completely different things than pan).
So, I started looking into best to handle that, and I came up with an ugly mess.
Which leads me to a simple question: why? Wouldn't it be much, much simpler is swipes just behaved like everything else and reported the *lift* point as `pos`?
I don't think we actually care about it much... unless it's used for the tap/gesture zone hit detection, in …
> GestureDetector: Make two_finger pans & swipes report the same sort of data than their standard brethren

- Makefile
- kodev
- tools/mk7z.sh
Depends on: https://github.com/koreader/android-luajit-launcher/pull/419 and https://github.com/koreader/koreader-base/pull/1620
Additionally, speedup Android development cycle: don't recreate `assets.7z` from scratch every time, and also ensure it's reproducible to avoid busting gradle's cache.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10610)
> android: update to use NDK 23c

- frontend/apps/reader/modules/readerstyletweak.lua
Closes https://github.com/koreader/koreader/issues/10667.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10674)
> Style tweaks: notification on toggling style tweak with a gesture

- frontend/device/pocketbook/device.lua
Pocketbook's new InkPad Color 2 is not yet supported. I've added the configuration to make it work.
Besides the WiFi issues that seem to be present in all Pocketbook devices it works like a charm.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10685)
> Add support for InkPad Color 2

- frontend/apps/reader/modules/readerfont.lua
- frontend/ui/widget/touchmenu.lua
- Add a toggle in Font settings> allowing showing font ordered by most recently selected (long-press on it allows clearing this history).
- Keep in G_reader_settings a list of known fonts, so we can notice newly added user fonts, and put them at the start of the most recently selected. Show these new fonts with a symbol in the menu.
- TouchMenu: allows for a flag to trigger menu refresh when going up.
This is possibly a simpler alternative solution to #10613, so: Closes #10613.
@jonnyl2 : from https://github.com/koreader/koreader/issues/10613#issuecomment-1625468452
> Would this be an array of all fonts or just a defined number of recently selected ones? I would suggest that newly installed fonts also get in front of the line for easy selection after installation. But of course if the …
> Font list menu: allow sorting by more recently set

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/ui/widget/filechooser.lua
Partial un-do of #10627 : `access` is not the same as `modified`, so we want to keep the "last read date" file sort option in addition to the "date modified" option
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10682)
> Re-add file sort by "last date read"

- platform/mac/do_mac_bundle.sh
c.f., https://github.com/koreader/koreader/pull/10687#issuecomment-1633450159
----
I'm not actually sure why we were pulling webp itself, since we build it? Perhaps this predates that fact?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10690)
> macOS: We ship our own webp, don't pull brew's

- plugins/archiveviewer.koplugin/main.lua
View archived files content (without extraction to a file).
ImageViewer is used for supported image files, TextViewer for all other types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10683)
> ArchiveViewer: view files

- frontend/ui/network/manager.lua
Followup to #10669, fix #10694
While this one *should* technically be sound in and of itself, it failing would trip up the beforeWifiAction framework, so, just let whatever needs network connectivity fall on its face later; at worst, that'll provide more helpful logging than this failing would (because spoiler alert: it doesn't log anything :D).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10697)
> NetworkManager: Bypass isOnline on !hasWifiToggle platforms

- frontend/apps/reader/readerui.lua
- frontend/document/credocument.lua
Includes:
- bump LunaSVG: intermediate upstream bump, cleanup https://github.com/koreader/koreader-base/pull/1640
- bump LunaSVG: minor upstream tweaks
crengine https://github.com/koreader/crengine/pull/523 :
- DocX: add support for similar DocM format
- LVStyleSheet: fix LVCssDeclaration::getHash()
- CSS parsing: accept Unicode values for ID and classnames
- update for Harfbuzz 8, fix some compiler warning
Also fix input not restored when loading failed, and KOReader not able to exit (showing an InfoMessage "KOReader will exit not." and waiting for a dismiss tap - which did never happen as input was not restored :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10702 …
> bump LunaSVG, crengine: add support for .docm

- frontend/device/android/device.lua
before trying to read return status
like i had said in #10722 i dont really like this implementation, but i am not experienced enough to add a callback into the JNI
re #10722
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10726)
> Device:Android: wait until lights dialog is closed

- frontend/device/android/device.lua
re #10725
This PR is so that variable `is_fl_on` is also kept in-sync when `fl_intensity` is being set, this *could* maybe be de-duplicated by always calling it after the both `if`'s.
Why?
because thing that depend on `is_fl_on` do not work correctly after just `fl_intensity` being set, like `BasePowerD:isFrontlightOn` (by extension also `BasePowerD:isFrontlightOff`) and so in turn things like `BasePowerD:toggleFrontlight` call the wrong function.
Example:
(assuming #10726 is merged, makes it easier to explain)
initial state:
fl_intensity: 50
is_fl_on: true
then you go to the lights dialog, change `brightness` to `0` (fronlight being off) and then just `fl_intensity` is set to `0`, but `is_fl_on` stays `true` - which is wrong, and so if you then do something like event `ToggleFrontlight` …
> Device:Android: call "_decideFrontlightState" to keep "is_fl_on" in sync

- frontend/device/devicelistener.lua
add notification when the frontlight is unchanged (no callback is called)
because in `2023.04` a notification would be always be shown (like `Frontlight disabled`) and since `2023.05` no notification would be shown anymore if the frontlight did not change (no intensity change), see
https://github.com/koreader/koreader/blob/d350418367ddf39d752d05e0587e562d7d4af2c4/frontend/device/generic/powerd.lua#L149
re #10722
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10727)
> DeviceListener:onToggleFrontlight: add notification of "unchanged"

- plugins/autowarmth.koplugin/main.lua
At least for that case i think `Activate` and `Deactivate` are more appropriate (especially for translations)
for example currently in german they are translated to:
`Set` -> `Setzen` (literally `place` / `set`)
`Unset` -> `Löschen` (literally `delete`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10733)
> Autowarmth: Change strings "set" and "unset" to "turn on" / "turn off" where appropriate

- frontend/device/generic/device.lua
- frontend/device/kobo/device.lua
* OTA: Unbreak the first OTA on a fresh install (via https://github.com/koreader/koreader-base/pull/1643); Regression since #10162)
* NetworkInfo: Never show the token index next to the SSID
* Kobo: Apply the smooth ramp-off fix to all devices with an AW99703 PWM controller.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10728)
> Bundle of misc fixes

- frontend/apps/reader/modules/readerdictionary.lua
"Enable fuzzy search" checkbox is applicable to the current document only.
Do not show the checkbox when Dictionary Settings are called from the file browser.
Another way is to keep the checkbox and just change the item text, but in that case we'll lose the explanation dialog (it will remain on long-pressing only).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10721)
> Dictionary: fix Fuzzy search setting appearance

- frontend/document/credocument.lua
- frontend/ui/viewhtml.lua
- frontend/ui/wikipedia.lua
Includes https://github.com/koreader/crengine/pull/524:
- SVG: support embedded base64 images when no doc
- epub.css: hide `<nav hidden="">`
Closes #10703.
- Tables: fix possible specified width overflow
- Tables: fix caption and table width interactions
- CSS/Tables: add support for "caption-side: top/bottom"
- gatherNodeMatchingRulesets(): avoid messing document cache
- gatherStylesheetsMatchingRulesets(): add with_m_stylesheet param
On long-press on the "Show matched stylesheets rules" buttons, ignore those from our epub.css/html5.css and from styletweaks, which may make investigating a book style simpler without their noise.
I also changed the "markup" for element path, using Unicode solid black blocks, instead of the previous bland `/* ===== DocFragment > body > section > p */`.
The …
> bump crengine, fix images in Wikipedia results and EPUB, View matching CSS tweak

- plugins/wallabag.koplugin/main.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10715)
> Fix issue #9187 Handle wallabag server url with trailing slash(es)

- frontend/dispatcher.lua
- plugins/gestures.koplugin/main.lua
- plugins/profiles.koplugin/main.lua
Fixes https://github.com/koreader/koreader/issues/10668#issuecomment-1627806785.
Long-press on a profile entry in a QuickMenu calls a new QM with the content of the profile and "Execute all" button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10671)
> QuickMenu: add long-press on profile

- plugins/exporter.koplugin/clip.lua
(1) Fix (unreported) crash on exporting Kindle My Clippings.txt.
It expected datetime string
https://github.com/koreader/koreader/blob/9ceb07a4c667a275a3401fc202a0c5bd3b54f75d/plugins/exporter.koplugin/clip.lua#L44
but my Kindle produces the space after the day, not comma.
`- Your Highlight at location 12-12 | Added on Sunday, 30 July 2023 17:47:22`
Let's have both options.
(2) When parsing the library, let's get author/title from `doc_props`, not from `stats`.
(3) When parsing the current document, do not reopen it to get author/title, just read `doc_settings`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10765)
> Exporter: fixes

- frontend/apps/reader/modules/readerfooter.lua
Take a more tactful approach instead, should hopefully prevent issues like in https://github.com/koreader/koreader/pull/10114#issuecomment-1658913661
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10767)
> ReaderFooter: Don't reset the initial position marker like a cowboy

- frontend/device/kobo/device.lua
- platform/kobo/disable-wifi.sh
- platform/kobo/enable-wifi.sh
- platform/kobo/koreader.sh
- platform/kobo/nickel.sh
Depends on https://github.com/koreader/koreader-base/pull/1642, Fix #10408
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10719)
> Kobo: Initial Elipsa 2E support

- frontend/apps/reader/modules/readerrolling.lua
- frontend/device/kindle/powerd.lua
- frontend/device/kobo/device.lua
- frontend/device/sysfs_light.lua
- frontend/ui/data/onetime_migration.lua
- frontend/ui/widget/inputtext.lua
- frontend/ui/widget/notification.lua
- frontend/ui/widget/virtualkeyboard.lua
- frontend/util.lua
* Notification: Drop the fencing from #10083; it never actually helped, and had subtle side-effects we could do without.
* VirtualKeyBoard: Flash on close, otherwise, some of the fast refresh glitches may be burned into the working buffer until a flash. Making sure we flash ourselves prevent it from sticking around on the page ;).
* util: Move `writeToSysfs` to base (i.e., `ffi/util`), as we need it there (and it actually makes more sense there anyway ;p).
* Bump base for https://github.com/koreader/koreader-base/pull/1645, which is where the actual workaround (hopefully) lives.
Re #8414, #9806, #10558
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10771)
> Kobo: Yet another attempt at working around the hangs on the latest NXP boards

- frontend/ui/data/keyboardlayouts/el_keyboard.lua
- frontend/ui/data/keyboardlayouts/keypopup/el_popup.lua
Update the Greek keyboard to the new keyboard layout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10734)
> Update Greek keyboard

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/datetime.lua
- frontend/document/koptinterface.lua
- frontend/ui/bidi.lua
- frontend/ui/data/creoptions.lua
- frontend/ui/viewhtml.lua
- frontend/ui/widget/doublespinwidget.lua
- frontend/ui/widget/numberpickerwidget.lua
- frontend/ui/widget/spinwidget.lua
- frontend/ui/wikipedia.lua
- frontend/util.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
The ToC is no longer in the HTML we get from the Wikipedia API. So, add it ourselves.
Also, as we can't get anywhere the Wikipedia localized string for "Contents" (ie. "Sommaire" in French), use thick `<HR>` to mark the start and end of this ToC.
See https://github.com/koreader/koreader/pull/10746#issuecomment-1652134501 and followups.
Fix bug in replace_in_html() when consecutive matches, that could get parts of the content eaten and now shown.
Also ensure content after leading indentation is not wrapped on the next line.
ie with unprettified:
Before | After:
(But as it is all regex stuff, and not proper CSS tokenization, it may still do bad things in some cases...)
Because it is better if we inprint in our brain while reading code that a right single quotation mark is `U+2019`, rather …
> Re-add Wikipedia HTML ToC, View HTML & CSS tweaks

- frontend/ui/data/onetime_migration.lua
- plugins/statistics.koplugin/main.lua
This PR is an attempt to fix #10342 and #10656. According to https://github.com/koreader/koreader/issues/10656#issuecomment-1650991464, the bug could be `null id_books` in `page_stat_data`. I didn't really find out why that happened from the sync code but still added some "fail-proofs". 
Also it would be great if @libelle1995 and @xsdjt could try out this solution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10749)
> Statistics plugin sync: fix bloated null id_books

- reader.lua
First, don't require it so as not to pin it in package.loaded; just use dofile
And, second, do that in an explicitly scoped block because nothing in there should persist, when we named it "one time", we meant it ;p.
Followup to #10775
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10776)
> OTM: Don't keep it in scope forever.

- plugins/kosync.koplugin/main.lua
Fix #10784
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10785)
> KOSync: Only nag about "Action when Wi-Fi is off" when toggling auto-sync *on*

- frontend/device/input.lua
- frontend/ui/widget/inputtext.lua
we use it as text anyway and test if it is the empty string also.
this fixes a crash in viewhtml when holding a selector with an empty clipboard, we try to concatenate getClipboardText which is nil (on !SDL & !Android)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10780)
> do not allow clipboard to be nil

- frontend/ui/translator.lua
- frontend/ui/viewhtml.lua
- frontend/util.lua
`View HTML & CSS: fix minor spacing issues`
Fix one space indentation too much, and wrap after `}` when `h1 {...} h2 {...}` on a single line.
`Translator: explicite wording above each section`
Closes #10787.
@Frenzie : there are some translated strings - so up to you if this should go in v2023.08 or v2023.09.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10799)
> Translator: explicite wording above each section, fix minor View HTML/CSS issues

- frontend/apps/filemanager/filemanager.lua
- frontend/ui/widget/menu.lua
Truncate the path to view the filename in full. Closes https://github.com/koreader/koreader/issues/10760.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10783)
> FileManager: truncate left in selected files list

- frontend/device/input.lua
- frontend/device/kobo/device.lua
Apparently it mirrors on the Y axis. Or the panel vs. touch rotations are wonkier than expected or ...something.
Brain hurty >_<".
Followup to #10719
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10802)
> Kobo: Fix the input translation on the Elipsa 2E

- plugins/exporter.koplugin/target/readwise.lua
Exported highlights are good sorted by position, page numbers could be wrong.
Closes https://github.com/koreader/koreader/issues/10817.
For reference: https://readwise.io/api_deets
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10824)
> Exporter: fix order for Readwise

- frontend/ui/network/manager.lua
- frontend/ui/network/networklistener.lua
Fix #10823
(For reference, we *enable* wifi_was_on no matter *how* wifi is enabled, but we only toggle it off when it's killed by a *direct* user interaction, the intent being that if *something* non-interactive enabled wifi, you'll probably silently need it on resume too).
(Rebase me).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10825)
> NetworkManager: Always flip wifi_was_on when interactively tearing down Wi-Fi

- frontend/device/generic/device.lua
- frontend/device/pocketbook/device.lua
- frontend/ui/uimanager.lua
- reader.lua
Makes more sense this way.
Re: #10828
Also clarify the UIManager "no dialogs left" message, and drop the return value, as it's meaningless, we just want to break & return.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10830)
> PocketBook: Run Generic:exit *last*

- frontend/socketutil.lua
- plugins/kosync.koplugin/KOSyncClient.lua
- plugins/kosync.koplugin/main.lua
An attempt was made in the original code, but the whole thing was designed in the hope of actually switching to turbo, so it was super janky without it.
Anyway, we now actually have a sane way to set socket timeouts, so, use that, and set them very tight for now.
This is fairly critical right now, because the server is down, and the default timeouts are ~30s. That happens to be *above* the debounce threshold, so you can't even hope for that to help you. Meaning, right now, you get a 2 * 30s block on resume with auto sync. That's... Very Not Good(TM).
That becomes a single 2s one after this.
Exercised the timeouts thanks to the main server being down right now, and also tested successfully with a custom sync server (but, granted, one that's actually much closer to me than koreader.rocks), …
> KOSync: Set sane socket timeouts properly

- frontend/datetime.lua
Cf. <https://github.com/koreader/koreader/discussions/10774#discussioncomment-6618167>, reverts #10769 for direct use in translations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10845)
> [i18n] Revert Unicode escape sequence to utf-8 bytes for translation

- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/inputtext.lua
Fix issue introduced by 976aaf5f: with full screen text editor and hiding the keyboard, a tap in the text area would show a new keyboard hiding the button allowing to save/close the text editor, getting us stuck there.
See https://github.com/koreader/koreader/pull/10803#issuecomment-1694483616
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10850)
> InputText/InputDialog: fix keyboard issue

- frontend/ui/network/manager.lua
- frontend/ui/widget/networksetting.lua
- spec/unit/network_manager_spec.lua
> NetworkManager: Decode SSID to UTF-8

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/reader/modules/readertypography.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/apps/reader/readerui.lua
- frontend/docsettings.lua
- frontend/ui/screensaver.lua
- plugins/coverbrowser.koplugin/bookinfomanager.lua
Long-press on a property in the Book information window to customize it.
`custom_props` and original `doc_props` are saved to `custom_metadata.lua` in sdr folder.
Maybe it's better to reorder the items, to put non-prop "Pages" to the end, closer to other numbers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10861)
> Custom metadata

- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/inputtext.lua
- frontend/ui/widget/multiinputdialog.lua
- frontend/ui/widget/physicalkeyboard.lua
- frontend/ui/widget/virtualkeyboard.lua
- plugins/texteditor.koplugin/main.lua
Move as much of the state tracking as possible inside VirtualKeyboard itself.
InputDialog unfortunately needs an internal tracking of this state because it needs to know about it *before* the VK is shown, so we have to keep a bit of duplication in there, although we do try much harder to keep everything in sync (at least at function call edges), and to keep the damage contained to, essentially, the toggle button's handler.
(Followup to #10803 & #10850)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10852)
> VirtualKeyboard: Revamp visibility handling

- plugins/exporter.koplugin/clip.lua
New translatable strings: "Unknown Book", "Unknown Author".
They were untranslated in the exported file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10874)
> Exporter: custom metadata

- frontend/apps/filemanager/filemanagerutil.lua
- frontend/docsettings.lua
- frontend/document/documentregistry.lua
- frontend/ui/widget/filechooser.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10866)
> Reset settings/cover/metadata separately

- frontend/apps/reader/modules/readertypeset.lua
Main discussion in https://github.com/koreader/koreader/pull/10763.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10876)
> copt deduplicate: embedded_css, embedded_fonts

- frontend/apps/reader/modules/readerfont.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/readerui.lua
- frontend/document/credocument.lua
- plugins/docsettingtweak.koplugin/directory_defaults_template.lua
Main discussion in https://github.com/koreader/koreader/pull/10763.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10768)
> copt deduplicate: line_spacing

- frontend/apps/reader/modules/readercoptlistener.lua
- frontend/apps/reader/modules/readerfont.lua
- frontend/apps/reader/modules/readerlink.lua
- frontend/apps/reader/modules/readerrolling.lua
- plugins/docsettingtweak.koplugin/directory_defaults_template.lua
Main discussion in: https://github.com/koreader/koreader/pull/10763.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10882)
> copt deduplicate: font_size, visible_pages

- frontend/apps/filemanager/filemanagerbookinfo.lua
- plugins/coverbrowser.koplugin/covermenu.lua
Various fixes, including https://github.com/koreader/koreader/pull/10869#issuecomment-1710273563 and https://github.com/koreader/koreader/pull/10869#issuecomment-1712886536.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10889)
> Custom metadata: fixes

- plugins/statistics.koplugin/main.lua
Followup to #10861 and #10869 : update metadata in Reading Statistics DB when they change, so that the book can be found on the next opening and previous statistics are not lost - and so that the updated title/authors are reflected in the reading statistics (calendar view, today timeline & the others).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10894)
> Custom metadata: update Statistics db on metadata change

- doc/Building.md
libtool-bin is something everyone already has installed so it slipped by unnoticed for more than half a decade.
~~SDL 1.2 support was removed 4 years ago: https://github.com/koreader/koreader-base/pull/963~~
Fixes #10896.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10897)
> [doc] Building: minor updates to Debian/Ubuntu prerequisites

- frontend/ui/elements/font_ui_fallbacks.lua
After discussion with @NiLuJe in (on?) Gitter.
<details> 
<summary>Screenshot</summary>
</details>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10908)
> Check for Noto Emoji font in UI fallback fonts

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readertypography.lua
- frontend/ui/translator.lua
- frontend/ui/viewhtml.lua
- frontend/ui/widget/keyvaluepage.lua
- frontend/ui/widget/textviewer.lua
- plugins/opds.koplugin/opdsbrowser.lua
- plugins/patchmanagement.koplugin/main.lua
The DictQuickLookup and TextViewer windows are alike, let TextViewer use the same settings `dict_font_size` and `dict_justify`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10911)
> TextViewer: font size

- frontend/device/kobo/device.lua
This reverts commit e7e0d2edb6af95bced95ce88d90a9e08f49fcf7a.
Whatever's actually going on with nightmode, this isn't it. This was independently confirmed to behave as expected, and the issue that prompted this was *not* fixed by this commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10928)
> Revert "Kobo: Disable HW inversion on MTK (#10841)"

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/reader/modules/readertypography.lua
(1) Optimize getting custom prop if only one prop is needed.
(2) Pass plain text to the custom edit dialog.
(3) Remove unused `metadata_value_new` in the event arg.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10919)
> Custom metadata: fixes 2

- frontend/apps/reader/modules/readerrolling.lua
Fix #10932
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10934)
> ReaderRolling: Guard against races between scheduled tasks and CloseDocument

- plugins/timesync.koplugin/main.lua
And, on Kindle, make sure we update the native UI's time, too
Fix #10932
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10935)
> TimeSync: Probe for ntpd/ntpdate dynamically

- plugins/coverbrowser.koplugin/listmenu.lua
- handle possible height overflow
- now that labels don't overflow, increase the minimum font size
Example, before:
And after:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10942)
> coverbrowser: improve title & authors layout

- plugins/coverbrowser.koplugin/bookinfomanager.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/main.lua
Showing the page / progress info and the file size / type can now be disabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10941)
> coverbrowser: make showing some metadata fields optional

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/filemanager/filemanagerutil.lua
- plugins/coverbrowser.koplugin/main.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10956)
> Coverbrowser: event for cache refreshing

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/ui/widget/filechooser.lua
Fixes issue #7158
The default behavior is to display the finished books (no change on upgrade). For consistency with the two similar options, it represented by a checkbox "Show hidden books" that is checked by default.
The implementation is straightforward, meaning that, when the option is unchecked, each file will require a call to `filemanagerutil.getStatus` that checks its status.
For clarity, the code uses the "finished books" expression because the condition is relevant to the *book* metadata, while the other settings are about *file* attributes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10895)
> New menu option and filemanager filter to hide finished books #7158

- frontend/device/kobo/powerd.lua
Namely, skip ramping when going to/from <= 2% frontlight, otherwise we just eat the delay for no good reason (1%), or it just stutters and looks bad (2%).
Fix #10970
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10971)
> Kobo: Deal with some more frontlight edge cases on devices with the AW99703 PWM controller

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/datetime.lua
- frontend/readhistory.lua
- plugins/statistics.koplugin/main.lua
Separate settings for History and Statistics.
If enabled in History settings: after opening the finished book will not pop up in History, will not be saved as Last document, will not pop up in the file browser with Sort by last read date.
Doesn't depend on the way of opening (from FM, History, Collections, random book etc.).
Closes https://github.com/koreader/koreader/issues/10962.
EDIT: closes https://github.com/koreader/koreader/issues/10984.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10968)
> Finished books: freeze history timestamp and statistics

- plugins/statistics.koplugin/main.lua
Includes a LuaJIT update, and the 64bit ffi.load fix on Android; so, a lot of arm64 changes.
Oh, and the PB input translation overhaul. Still as broken as before, I'm just no longer triggered by the piece of code in question ;p.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10990)
> Bump base & android

- plugins/timesync.koplugin/main.lua
Kindle ships another implementation, with incompatible syntax...
Regression since #10935
Thanks to @yparitcher ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10992)
> TimeSync: Double-check that ntpd is busybox

- defaults.lua
- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/dispatcher.lua
- frontend/ui/widget/filechooser.lua
- frontend/ui/widget/pathchooser.lua
- plugins/coverbrowser.koplugin/covermenu.lua
All is cross-bound, hence the combined PR.
(1) **File search**
File search now is available in the file browser only.
Standard file dialog pop-up buttons added. Closes https://github.com/koreader/koreader/issues/10991.
(2) **File manager**
Unapplicable pop-up buttons in the file dialog are hidden (previously they were disabled).
Supported file
Unsupported file
(3) **FileChooser**
"Show" settings (finished books, hidden files, unsupported files) are centralized in FileChooser.
Optimization: do not init the settings every time when FM is launched.
(4) **Dispatcher**
"File search" is moved from General to File browser section.
"Fulltext search" is moved from General to Reader section.
Tidy: lines of code are ordered in accordance with the action menu order, comments fixed/added.
(5) …
> File search, FileChooser and others

- frontend/ui/otamanager.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10997)
> otamanager: fix OTA model name for Android x86_64

- doc/Building_targets.md
Deprecated or at least untested for years. Noticed due to <https://github.com/koreader/koreader/discussions/10972#discussion-5701647>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10974)
> [doc] Building targets: remove mentions of Ubuntu Touch

- frontend/device/pocketbook/device.lua
I now also own a PB-Basic Lux 4 (PB618) and KOReader runs excellently on it.
[crash.log](https://github.com/koreader/koreader/files/12840018/crash.log)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10987)
> Add new PocketBook devices PB-Basic Lux 4 (PB618)

- plugins/exporter.koplugin/main.lua
- plugins/exporter.koplugin/target/flomo.lua
- plugins/exporter.koplugin/target/memos.lua
Since memos removed open_api since v0.15, the existing memos export plugin doesn't work(https://github.com/koreader/koreader/discussions/10923), but since flomo still follows the previous model, the memos export is now fixed and the flomo export (i.e., the original memos export) has been added
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10988)
> Exporter: fix memos export, add flomo export

- frontend/device/android/device.lua
- frontend/device/android/powerd.lua
re https://github.com/koreader/koreader/pull/10731#discussion_r1271505121
This PR changes so that androids implementation of `setIntensityHW` always calls `_decideFrontlightState`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10737)
> Device:Android: always call "_decideFrontlightState" in "setIntensityHW"

- frontend/apps/filemanager/filemanager.lua
- frontend/readhistory.lua
Closes https://github.com/koreader/koreader/issues/10995.
(Doesn't update sdr with "dir" setting, but that's another story)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10999)
> History: update on renaming/moving a folder

- frontend/apps/reader/modules/readerhighlight.lua
Changes <kbd>Close</kbd> button to <kbd>Delete highlight</kbd> button.
(1) Other highlight dialogs do not have the Close button.
(2) It is easy to close the note view dialog by tapping outside of it.
(3) Speeds up some workflows:  https://www.mobileread.com/forums/showthread.php?t=356792.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11039)
> ReaderHighlight: delete highlight in view note dialog

- frontend/device/kindle/device.lua
Turns out it's not really specific to the Signature Edition
(Cosmetics only).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11051)
> Kindle: Amend #11049 comments

- frontend/device/kindle/device.lua
Fix #11050 (for real this time).
My first PoC unearthed an unfortunate bug in the input backend (https://github.com/koreader/koreader-base/pull/1685), but this one should behave.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11052)
> Kindle: Find the input device the hard way on the PW5

- frontend/ui/elements/menu_keyboard_layout.lua
- frontend/ui/widget/virtualkeyboard.lua
Default to enable. Fixes https://github.com/koreader/koreader/issues/10976.
Cleanup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11066)
> Virtual keyboard: add a setting to disable swipes

- frontend/device/generic/device.lua
- frontend/device/pocketbook/device.lua
- frontend/device/sdl/device.lua
Fix #11059
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11060)
> Device: Don't leave hasSeamlessWifiToggle enabled when hasWifiToggle is disabled

- frontend/device/pocketbook/device.lua
To add the new PocketBook InkPad Color 3 (743K3) with E Ink Kaleido™ 3 screen.
[crash.log(1).txt](https://github.com/koreader/koreader/files/13258960/crash.log.1.txt)
[crash.log(2).txt](https://github.com/koreader/koreader/files/13258962/crash.log.2.txt)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11079)
> Add new PocketBook InkPad Color 3 (743K3)

- frontend/apps/reader/modules/readerstyletweak.lua
- plugins/gestures.koplugin/main.lua
- plugins/profiles.koplugin/main.lua
Update gestures within Gestures module itself.
Fixes https://github.com/koreader/koreader/issues/11071.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11072)
> Profiles: fix updating gestures

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/dispatcher.lua
Search in history in filenames and books metadata (without opening files).
Available in the History
and by dispatcher in FM and Reader.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11084)
> History: search

- frontend/ui/network/manager.lua
- frontend/ui/network/wpa_supplicant.lua
- frontend/ui/widget/networksetting.lua
- spec/unit/network_manager_spec.lua
Connecting to non-ASCII SSIDs does not work, and I did not actually if #10864 fixed it. It turns out that it didn't, so here is a PR that actually fixes it.
The UTF-8 decoding of SSIDs is specific to wpa_supplicant. In this patch, we move all of this decoding logic to the wpa_supplicant module. We expose the raw bytes of the SSID to the NetworkMgr code, and make sure to always fix bad UTF-8 before we display the SSID to the user.
Within the wpa_supplicant module, we replace the call to the wpa_passphrase binary to get the PSK with a direct function call to OpenSSL. This allows us to calculate the PSK over any arbitrary bytes, including UTF-8. In the same vein, we use the hex-encoded SSID to communicate with wpa_supplicant when setting up the network to support arbitrary bytes in the SSID. …
> Fix connection bug with non-ASCII SSIDs in wpa_supplicant

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/readhistory.lua
Companion to https://github.com/koreader/koreader/pull/10999.
Minor optimization: avoid expensive `ReadHistory:reload()` and redundant `lfs.attributes`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11090)
> History: update on deleting a folder

- frontend/apps/reader/modules/readerthumbnail.lua
- frontend/ui/widget/imagewidget.lua
- frontend/ui/widget/pagebrowserwidget.lua
Just prevent page thumbnails ImageWidgets to be nightmode inverted, unlike all other ones which are expected to be double inverted to get their original colors shown.
The same thumbnail can be used and cached in both day and night modes, unless "nightmode_images" is enabled and have crengine itself invert images, making thumbnails different.
(Had a hard time writing that commit message :) was initially mentionning "triple inverting"... hard to put into words what's happening in nightmode and the simple tweaks there).
See https://github.com/koreader/koreader/issues/10811#issuecomment-1785943242
Pinging @NiLuJe for your OK the the ImageWidget `original_in_nightmode = true` idea/wording.
- - - …
> Page browser: show nightmode thumbnails when in nightmode

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/ui/widget/filechooser.lua
Minor fix: in sorting modes unapplicable to folders (size, type, percentage), folders remain sorted by name.
In that modes the reverse sorting should not affect folders.
Minor deduplicating.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11093)
> FileChooser: fix reverse sorting of folders

- frontend/apps/reader/modules/readerhandmade.lua
- frontend/ui/widget/buttondialog.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/textviewer.lua
Have tried and found useful. Closes https://github.com/koreader/koreader/issues/11092.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11094)
> InputDialog: tap outside to close dialog if keyboard is hidden

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/filemanager/filemanagershortcuts.lua
- frontend/ui/widget/filechooser.lua
(1) A marker in the mandatory to indicate the folder is added to Folder shortcuts.
(2) A marker in the TitleBar path to indicate the current folder is added to Folder shortcuts. 
(3) A button in the Plus menu to add/remove current folder to/from Folder shortcuts.
(4) A button in the folder popup dialog to add/remove the folder to/from Folder shortcuts.
(5) New wordings in the Folder shortcuts popup dialog buttons.
Classic
Mosaic
Detailed list
Plus menu
Popup dialog
Folder shortcuts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11108)
> Folder shortcuts: new markers, buttons

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/ui/widget/buttondialog.lua
Default to "center". Closes https://github.com/koreader/koreader/issues/11081.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11116)
> ReaderHighlight: adjustable highlight dialog position

- plugins/exporter.koplugin/target/xmnote.lua
Optimize #11087 :
1. In `isReadyToExport`, check if the ip is set. If not, then the user cannot enable xmnote export.
2. Add author field in highlights.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11134)
> Exporter: fix XMNote export, add author field

- frontend/ui/trapper.lua
- frontend/ui/widget/infomessage.lua
- frontend/ui/widget/notification.lua
- frontend/ui/widget/qrmessage.lua
Affects Notification, InfoMessage & QRMessage
Mostly harmless in practice, except for InfoMessage with a dismiss_callback, as it would have effectively ran twice.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11126)
> Widgets: Unschedule timeouts on early close

- frontend/device/devicelistener.lua
- frontend/dispatcher.lua
- frontend/ui/elements/mass_storage.lua
Fix #11106
It's right next to actual exit/restart actions, so it'll never ask for confirmation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11123)
> Dispatcher: Allow toggling USBMS

- defaults.lua
- frontend/device/android/powerd.lua
- frontend/device/devicelistener.lua
- frontend/device/generic/powerd.lua
- frontend/device/kindle/powerd.lua
- frontend/device/pocketbook/powerd.lua
- frontend/device/sdl/powerd.lua
- plugins/gestures.koplugin/main.lua
- spec/unit/frontlight_spec.lua
As "global defaults" (i.e., "advanced settings" in the UI).
These were the only zones not available there, for some reason (probably they were new and we try to avoid adding new defaults).
Fix #11142
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11158)
> Kindle: Frontlight fixes & Gestures: Make the edge swipe zones configurable

- frontend/dispatcher.lua
- plugins/gestures.koplugin/main.lua
(1) Closes https://github.com/koreader/koreader/issues/11131.
(2) Adjustable actions menu length to place settings in page 2.
Gestures
Profiles
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11135)
> QuickMenu: keep open on apply

- frontend/ui/data/dictionaries.lua
koreader can't download dictionary file if that have space in the url (it should change to `%20`)
and update links for persian dictionary too.
sorry for my mistake.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11165)
> fix dictionary link

- frontend/device/kindle/device.lua
Sorry, I renamed the branch and #11157 got nuked.
This PR adds gyro auto-rotation and basic support to use Kindle Scribe pen as touch input.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11159)
> Kindle scribe gyro and pen support

- frontend/device/kindle/device.lua
- frontend/ui/screensaver.lua
- frontend/ui/widget/screensaverlockwidget.lua
Because GH ate a commit during a rebase for some reason (it's fine locally, whatever).
Replaces #11170
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11174)
> ScreenSaverLock: Hide the popup on suspend ^2

- frontend/apps/reader/modules/readerstyletweak.lua
Includes:
- Avoid unnecessary string modifications https://github.com/koreader/crengine/pull/543
- remove unused lang_name https://github.com/koreader/crengine/pull/537
- extract SniffBOM()
- Optimize LVHTMLParser::CheckFormat()
- LVHTMLParser::CheckFormat() bugfixes
- Don't fillCharbuffer in Reset()
- lvfntman: fix stupid mistake https://github.com/koreader/crengine/pull/546
- css: mark const member functions https://github.com/koreader/crengine/pull/545
- css: clarify LVCssSelectorRule ownership
- css: speedup class matching
- fb2.css: empty paragraphs should have some line height https://github.com/koreader/crengine/pull/547
Closes #11173.
- CJK: fix bad ruby drawing on last paragraph line https://github.com/koreader/crengine/pull/548
Closes #11021.
Also includes:
ReaderStyleTweak: …
> bump crengine: various optimizations and fixes

- frontend/ui/widget/inputtext.lua
(1) A button to Delete all in the input box (sacrifice Cancel button) in the Clipboard dialog.
(2) Fix long-press in Select mode (thanks @stanxlc, supersedes https://github.com/koreader/koreader/pull/11169).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11182)
> InputText: Delete all and fix Select

- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/ui/widget/filechooser.lua
This PR extracts the collation related code from FileChooser and FileManager, to make it easier to add new sorting algorithms through user patches.
I also noticed a slight difference between which items got sorted depending on whether the `collate_mixed` option was set. Since the collation related code is now 'further away', I attempted to make it more consistent and predictable.
As an example, this is the user patch that I have been using: https://gist.github.com/wfdewith/978e4f8e09f481a480cb1bf645e8d518
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11150)
> Refactor FileManager collation for easier patching

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagershortcuts.lua
- frontend/apps/filemanager/filemanagerutil.lua
- frontend/readcollection.lua
- frontend/readhistory.lua
- spec/unit/filemanager_spec.lua
In file group actions (copy, move, delete files or folders) we maintain History and Collection.
With these changes flushing History and Collection is done not for every file but at the end of the action.
ReadCollection (rewritten) now does not ask the storage on each favorites status request.
(Opens the door for long awaiting favorites marker)
Currently one collection only is supported (Favorites) but the infrastructure is done ready for other collections, UI changes only needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11178)
> File browser, Collection: improve group actions

- frontend/apps/filemanager/filemanagershortcuts.lua
- frontend/ui/data/onetime_migration.lua
Since we show an indicator in the file browser, the check must be accelerated as much as possible, so - hash table.
https://github.com/koreader/koreader/blob/dbaef37b275a75bb7989b871f6a342af526394aa/frontend/apps/filemanager/filemanagershortcuts.lua#L32-L34
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11221)
> Folder shortcuts: speed up

- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/titlebar.lua
Increased height of the title bar in History and Collection pages, equal to FM title bar.
Item dimensions in Classic, Cover, List modes are equal in FM, Hist, Coll.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11243)
> History, Collection: title bar in FM style

- frontend/ui/widget/menu.lua
Wrong height of file manager content in classic mode.
Bug in https://github.com/koreader/koreader/pull/11243.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11251)
> File manager: fix height of menu widget

- frontend/apps/reader/modules/readerstatus.lua
- frontend/ui/widget/filechooser.lua
Finished books are always skipped while searching the next file.
Closes https://github.com/koreader/koreader/issues/11266. Closes https://github.com/koreader/koreader/issues/11267.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11272)
> Fix "Open next file"

- plugins/statistics.koplugin/main.lua
Followup to #11279
(ReaderFooter does it this way, and I don't have a testcase on hand anyway).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11284)
> Statistics: Also skip hidden flows stuff in continuous mode

- frontend/util.lua
- plugins/movetoarchive.koplugin/main.lua
First try.
Function is taken from: https://www.geeks3d.com/hacklab/20210901/how-to-check-if-a-directory-exists-in-lua-and-in-python/
Use case:
1) Open KOReader with MoveToArchive plugin enabled, setup folder for it.
2) While KOReader is open, rename that folder to something else.
3) Try to go to that folder from the plugin menu. Now instead of crashing, it should ask about setting a new folder for MoveToArchive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11262)
> Add folder check in move-to-archive

- frontend/device/kindle/device.lua
Closes #11199 , that reported about touch input unresponsiveness if KOReader was started very soon after a fresh Kindle reboot, both via KUAL and KOL.
Context: the old touch device was in fact a Wacom Digitizer (`event3`).
The new `touch` device is the true touch device, `event2`.
Why the old input device worked in all other cases (at all!) is still a lab126 mistery. My suspicion is that down the road of startup, Wacom Digitizer is then duplicated as a touch. However, this transition doesn't seem to have enough time to kick in, and probably gets murdered among other stuff that `koreader.sh` needs to murder during its startup.
Thank you @NiLuJe !
- - - …
> Kindle Scribe: fix touch input

- frontend/device/android/powerd.lua
Depends on https://github.com/koreader/android-luajit-launcher/pull/426
Fixing old issue on Onyx devices that also need warmth to be turned off.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11275)
> Properly toggle warmth on OnyxWarmthController devices as well

- frontend/device/pocketbook/device.lua
The bezel covers a couple of pixels of the screen, so adjust not to show content under the bezel.
This fixes #11301
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11302)
> Add viewport for PB743K3

- plugins/movetoarchive.koplugin/main.lua
updateItemByPath has recently been replaced with updateItem in both readhistory and readcollection.
Fixes: aabd6d7a2602 ("File browser, Collection: improve group actions (#11178)")
Fixes: https://github.com/koreader/koreader/issues/11320
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11321)
> Fix "Move current book to archive"

- frontend/device/kindle/device.lua
- frontend/ui/elements/screen_notification_menu_table.lua
- frontend/ui/widget/notification.lua
* Disable HW dithering on Scribe until we can merge https://github.com/koreader/koreader-base/pull/1718 & #11307 
* Completely random refactor of the Notification setting, because I had to look at it given a report on MR, and I nearly lost my mind trying to follow what the hell was happening in there ;p.
Now looks like this: ![notif_settings](https://github.com/koreader/koreader/assets/111974/ca7ed6f4-1820-4d55-a232-dc4d78313f19)
(Rebase me)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11308)
> Minor tweaks or stop-gaps before the release

- frontend/ui/elements/screen_notification_menu_table.lua
Something in the gettext/weblate pipeline doesn't like it...
These are real unicode codepoints, not custom nerdfont ones, so just render the actual glyph instead of escaping it.
Fix #11328
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11330)
> i18n: Don't use Lua unicode escapes

- plugins/exporter.koplugin/target/memos.lua
@fierceX (author of the plugin) FYI
Creating tags on memos looked like "#This is a book title" meaning only "#This" would become a Tag. Replacing spaces with underscore to be more usable so that the following tag would be created "#This_is_a_book_title"
and thanks a lot to @fierceX, very useful plugin!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11107)
> Exporter: memos, replace space with underscore for # tag creation

- frontend/ui/widget/filechooser.lua
(1) Bug from https://github.com/koreader/koreader/pull/11272: `show_unsupported` is set/used by PathChooser instances.
(2) Bug from https://github.com/koreader/koreader/pull/11150: incorrect args to `table.insert`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11300)
> FileChooser: fixes

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readerconfig.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/device/input.lua
- frontend/ui/widget/configdialog.lua
Optimize rotation when switching between the 2 variants upside-downside and left-right; quite similar to `G_reader_settings:isTrue("input_lock_gsensor")` in https://github.com/koreader/koreader/blob/63329569eb8afb00a29a723f215c6c5fcc9041aa/frontend/device/input.lua#L986
Tested on the emulator for now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11297)
> Reader: Do less work on same-orientation non-gyro rotations

- frontend/device/generic/device.lua
- frontend/device/kindle/device.lua
- frontend/ui/screensaver.lua
- frontend/ui/uimanager.lua
The API was unclear and the low-level functions had nil guards in place, but, in fact, our main caller, UIManager, ensures that can never happen.
A matching base PR (https://github.com/koreader/koreader-base/pull/1718) will drop those safety nets, so ensure we're safe.
Fix: #11303 (and re-enables HW dithering on the Kindle Scribe).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11307)
> Chore: Make sure we always pass a rect to `fb:refreshFull`

- frontend/apps/reader/modules/readerflipping.lua
- frontend/apps/reader/modules/readerhighlight.lua
Things discussed all along #11223. Closes #11223.
People using 2-steps text selection (via the Select button) may want to not be annoyed by this feature.
Also tweak a bit its behaviour, requiring now the text selection to come from outside a corder into a corner to activate it, which should allow starting text selection from a corner without triggering a scroll yet.
Some help_text and menu item text wording to be reviewed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11327)
> Text selection: option to disable corner scroll; show top left icon on very-long-press

- frontend/apps/filemanager/filemanagermenu.lua
Incorrect Classic mode `items_per_page` in the settings menu while in non-Classic mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11346)
> Fix Classic mode items per page setting

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerstatus.lua
- frontend/device/input.lua
- frontend/device/kindle/device.lua
- frontend/device/kindle/powerd.lua
- frontend/ui/widget/inputdialog.lua
We currently don't do anything with it, but this might help someone come up with fancier smartcover handling, like we do on Kobo...
Requires https://github.com/koreader/koreader-base/pull/1723
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11350)
> Kindle: Log the suspend/wakeup source (& a bunch of fixes)

- platform/remarkable/disable-wifi.sh
- platform/remarkable/enable-wifi.sh
Increase the robustness of the reMarkable enable/disable Wi-Fi scripts to support:
- Kernel module unloading not enabled in rM1: https://github.com/koreader/koreader/issues/11257#issuecomment-1868607390
- Future fixes in custom kernels: https://github.com/Etn40ff/linux-remarkable/pull/2
- Future fixes in the upstream kernel: https://github.com/toltec-dev/toltec/issues/803#issuecomment-1870634200
- Current workarounds and minimal setups: https://github.com/toltec-dev/toltec/issues/803#issue-2055903574
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11287)
> remarkable: Update Wi-Fi scripts

- frontend/ui/widget/container/framecontainer.lua
- frontend/ui/widget/container/inputcontainer.lua
- frontend/ui/widget/container/underlinecontainer.lua
- frontend/ui/widget/imagewidget.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/progresswidget.lua
- frontend/ui/widget/virtualkeyboard.lua
* Make the VirtualKey hitbox slightly larger, to encompass the padding between keys.
* Simplify `self.dimen` ref tracking in VirtualKeyboard, by fixing a few widgets `paintTo` methods to *not* break `self.dimen` references (namely, `FrameContainer` for VK, but there were a few other naughty pupils ;p).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11364)
> More VirtualKeyboard & dimen fixes

- frontend/ui/widget/frontlightwidget.lua
Fixes issue #8023
Related to issue #4029
The fix takes exactly the same approach as other PRs like #6195 to add some usability to devices with few hardware keys. The front-light widget can now be closed using the left key on the d-pad.
I was considering about experimenting with adding `"Left"` to `Device.input.group.Back` for devices with few keys, but that would be a much more bigger change and I think this quick fix just makes this widget operable on limited devices.
Tested on my PocketBook 616W
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11376)
> Fix Pocketbook 616 Frontlight Widget Inoperable

- frontend/apps/filemanager/filemanagerutil.lua
- plugins/coverbrowser.koplugin/covermenu.lua
- plugins/coverbrowser.koplugin/main.lua
Use events.
Fixes unreported bug: changing book status in History over file browser didn't change the displayed status in file browser.
Optimizes cache handling: do not trash the cache by Reset button when resetting the custom cover/metadata only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11360)
> CoverBrowser: doc_settings cache improvement

- frontend/apps/reader/modules/readersearch.lua
- frontend/apps/reader/modules/readerthumbnail.lua
- frontend/document/koptinterface.lua
- frontend/ui/rendertext.lua
- frontend/ui/widget/textboxwidget.lua
PageBrowser could have strange issues on devices with aggressive autostandby (ie. failure to read data
from subprocess).
Closes #11354.
Allow for embedding "tags" (invalid Unicode codepoints) in the text string to trigger some text formatting: for now only bolding some parts of text is possible.
Use it with fulltext search "all results" to highlight the matched word (instead of the previously used brackets).
See https://github.com/koreader/koreader/pull/11313#issuecomment-1880869671, https://github.com/koreader/koreader/pull/11313#issuecomment-1890457237.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11362)
> TextBoxWidget: allow showing bits of text in bold

- frontend/apps/reader/modules/readerfooter.lua
- frontend/dbg.lua
- frontend/device/kobo/device.lua
- frontend/ui/elements/common_info_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/geometry.lua
- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/confirmbox.lua
- frontend/ui/widget/container/framecontainer.lua
- frontend/ui/widget/container/underlinecontainer.lua
- frontend/ui/widget/container/widgetcontainer.lua
- frontend/ui/widget/imagewidget.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/keyvaluepage.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/notification.lua
- frontend/ui/widget/progresswidget.lua
- frontend/ui/widget/spinwidget.lua
- frontend/ui/widget/textboxwidget.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
- tools/wbuilder.lua
@hius07 mentioned something to that effect a few weeks back, I liked it ;p.
To make it slightly more user-friendly (and warrant the code duplication ;p), this always flips debug + verbose at once, and looks disabled if you only have debug w/o verbose enabled. It also requests a restart, for framebuffer's sake (it pulls a ref to logger.dbg on init, but Logger mutates its methods at runtime depending on the log level, so this doesn't track updates to the logging level).
(Also implement an actual `dbg.log` function that *will* keep track of the current status, in case something like that comes up again in the future).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11366) …
> UI: Add a verbose debug logging checkbox next to "Report a bug" 

- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/ui/screensaver.lua
- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/doublespinwidget.lua
- frontend/ui/widget/fixedtextwidget.lua
- frontend/ui/widget/touchmenu.lua
FrameContainer now behaves like other widgets, and no longer re-computes dimensions in paintTo *if you provide a dimen*.
Since we do here, for.... reasons I'm not entirely sure still make any sense, make sure we actually compute valid dimensions, instead of an empty rect from Geom:new ;).
Or, better yet, let FrameContainer do that itself, since the pre-computations were done as a workaround for a weird race with swipe handlers, and the Geom methods in question now have nil guards in place, so we don't need two layers of protection ;).
Fix #11389
Regression since d33bb0452cc696abd4c5d570555381b3405d2486
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11391)
> ConfigDialog: Don't enforce 0x0 dimensions on initial display

- plugins/coverbrowser.koplugin/main.lua
In Classic mode there is no `updateCache` method, caused warning in the log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11398)
> CoverBrowser: fix update cache

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagerutil.lua
- plugins/coverbrowser.koplugin/covermenu.lua
Getting bookinfo from the cache db is much faster than opening a book, let's use it in Classic mode too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11404)
> CoverBrowser: use bookinfo cache in Classic mode

- frontend/ui/widget/pathchooser.lua
To reproduce the bug:
-open Folder shortcuts
-press the Plus icon to add a shortcut
-in PathChooser long-press the Home icon
-press Folder shortcuts button
-close Folder shortcuts, close PathChooser
-press a shortcut
Folder shortcuts window remains open.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11367)
> PathChooser: fix calling Folder shortcuts

- frontend/device/generic/device.lua
- frontend/ui/widget/confirmbox.lua
- frontend/ui/widget/container/movablecontainer.lua
- frontend/ui/widget/infomessage.lua
- platform/kobo/koreader.sh
This is the logical continuation of #9114.
In #9114 the screen is cleared before downloading an update.
Then (unchanged by this PR) a ConfirmBox to ask for a confirmation of the new update is shown.
... no changes ...
After the successful download the user is asked to finally install the update.
Changes in this PR:
1.) Ask the user explicitly to update now or later. (No change in functionality,but only in texting, as later could have been selected by tapping outside the dialog before).
2.) Clear the screen before update, so that the user does only see whats happening (and not fragments of the book)..
Draft because: Does anybody know an easy solution to prevent the ConfirmBox to be movable (because moving it, shows some fragments of theold book's text)?
- - - …
> Clear UI leftovers before doing an OTA-install

- frontend/ui/widget/textviewer.lua
- frontend/util.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11427)
> TextViewer: make find result bold

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagerutil.lua
- frontend/apps/reader/readerui.lua
- frontend/document/documentregistry.lua
- frontend/readhistory.lua
- plugins/coverbrowser.koplugin/covermenu.lua
Recently added features (status buttons in file popup dialogs, aux providers support, frozen history for finished books) caused extra `DocSettings:open()` calls. Opening a book from the file browser gives 4 calls, popup file dialog gives 3 calls.
With this PR the number of calls is reduced: 2 calls while opening a book (that is the required minimum), 1 call for the popup dialog in FM, Hist, Coll.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11437)
> Minimize DocSettings:open() calls

- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
The entries built by filechooser/readhistory/readcollection already have all we need.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11449)
> CoverBrowser: do not call lfs on every item

- frontend/apps/reader/modules/readersearch.lua
Cf. https://github.com/koreader/koreader/pull/11313/files#r1439406753
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11352)
> [i18n] ReaderSearch: add translation context to "All" button

- frontend/ui/message/simpletcpserver.lua
- frontend/ui/message/streammessagequeueserver.lua
- frontend/ui/uimanager.lua
- plugins/httpinspector.koplugin/_meta.lua
- plugins/httpinspector.koplugin/main.lua
Can be used to inspect the state of the objects in a running KOReader.
It can also be used to execute actions (like the ones available to associate to a gesture) with HTTP requests from a remote computer/device/gadget.
The TCP server side is implemented with a new ZeroMQ StreamMessageQueueServer (thanks @bneo99). A small interesting writting about ZeroMQ and doing a small HTTP server that way at http://hintjens.com/blog:42.
Minor UIManager tweak to avoid uneeded inputevent when such a ZeroMQ module is running.
Based on (and supercedes) #10223 by @bneo99 , who did all the groundwork (I just had fun with building simple and pretty HTML and using Lua introspection ~~facilities~~ hacks to present all the objects we developpers are familiar with in a new light :)).
@bneo99: I did some small …
> HttpInspector: new plugin for developpers to inspect KOReader

- frontend/apps/reader/modules/readerlink.lua
- frontend/ui/data/css_tweaks.lua
- plugins/httpinspector.koplugin/main.lua
See https://github.com/koreader/koreader/pull/11457#issuecomment-1948237158
Includes https://github.com/koreader/koreader-base/pull/1737 and https://github.com/koreader/crengine/pull/554 : 
- `LvDocView`: allow setting custom title/authors/series
- `elementFromPoint()`: fix possible crash when float at end of document
Closes #11409.
- Non-linear fragments: fix generic handling on erm_final
Noticed around https://github.com/koreader/koreader/issues/10193#issuecomment-1915204376.
- `DrawBorder`: fix bottom border inset/outset drawing
- `getSegmentRects()`: allow segments to include images
Closes #11451.
- `getRangeText()`: allow gathering images
- Allow standalone image in link to trigger in-page footnotes
Closes #11451.
- `ldomDocument::render()`: avoid uneeded deserialization on each page …
> bump crengine: text selection and footnotes fixes and tweaks 

- frontend/ui/widget/filechooser.lua
This PR adds a new collate to sort `90% > 50% > 0% > unopened > 100%`, which is useful to directly have currently reading files / books at the front and finished books at the back instead of having to go through multiple pages (on long series'); and mostly benefits with #8472.
i would still like a better name for this sort than the current one
original (fork) PR: https://github.com/poire-z/koreader/pull/2
sorting example screenshot:
behavior:
- sort `90% > 50% > 0% > unopened > 100%` (non-reverse)
- sort using natsort (like `name (natural sorting)`) for same percentage
- smooth percentage to 2 decimal points instead of the numbers initial 16 decimal points (lua didnt provide a function for this to my knowledge)
- initialize un-opened files / books with `-1` to be distinct of opened but …
> Add sort: `90% > 50% > 0% > unopened > 100%`

- frontend/device/kindle/device.lua
I did not notice an ambient brightness sensor, nor adaptive brightness feature. (Ref: https://www.geekwire.com/2016/kindle-oasis-review-amazons-premium-e-reader-use-premium-features/)
Was it previously wrongly configured?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11456)
> Kindle oasis has no ambient brightness sensor

- frontend/apps/filemanager/filemanager.lua
- frontend/ui/widget/filechooser.lua
Fix my old bad code to avoid rescanning the storage and rebuilding the item table when selecting/deselecting files.
Just dim/undim the items instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11476)
> FileManager: less lfs calls when selecting files

- reader.lua
Fixes https://github.com/koreader/koreader/pull/11360#issuecomment-1960141453.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11485)
> Reader: use existing module instances on start

- plugins/wallabag.koplugin/main.lua
Previously unnoticed or changed Wallabag behavior can provide a mimetype of for example `text/html; utf-8`, which wouldn't be an exact match to `text/html`.
Fixes #11481.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11492)
> Wallabag: match `text/html` mimetype as starting with rather than exactly

- frontend/ui/widget/filechooser.lua
This PR adds onto the new filechooser sort `percent - unopened - finished last` to consider book status `complete` (Text: `Finished`) the same as 100%
re #11369
> `90% > 50% > 0% > unopened > 100% or finished`
https://github.com/koreader/koreader/pull/11369#issuecomment-1893897867
PS: it seems like the macos build is failing, but i do not see why
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11472)
> FileChooser: "percent - unopened - finished last" consider status "complete" as 100%

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/ui/elements/common_info_menu_table.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/widget/touchmenu.lua
If Menu Search is called from dispatcher, the upper menu goes opened, and remains opened on canceling the search results.
Fixing it: the menu will be shown when needed (for Open or Walk me there).
Also reordering code for some menu elements in accordance with the menus order (no any code changes).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11495)
> MenuSearch: open upper menu when needed only

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/ui/widget/touchmenu.lua
When `ShowMenu` is called via a keyboard event, the arg is not `nil`.
Bug from https://github.com/koreader/koreader/pull/11495. Closes https://github.com/koreader/koreader/issues/11509.
EDIT: **revert all changes to the upper menu made in** https://github.com/koreader/koreader/pull/11495.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11513)
> Upper menu: fix generating the menu

- frontend/device/input.lua
If there's only one contact, we won't get an ABS_MT_SLOT, so we need to make sure we fall back to the main finger slot once we've caught a tool switch.
Also, move the dedicated pen slot further away, so it has zero chance of being detected as a potential buddy contact to a finger contact.
Fix #11514
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11520)
> Input: Don't let wacom pens clobber the slot of the next contact

- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/textviewer.lua
- frontend/ui/widget/trapwidget.lua
We also need to catch it in TrapWidget so we can interrupt Wikipedia articles images loading.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11525)
> Menu, DictQuickLookup, TextViewer: allow mousewheel scrolling

- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
Closes https://github.com/koreader/koreader/issues/11521.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11523)
> CoverBrowser: show cached cover of deleted file in history

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/ui/widget/menu.lua
Available via 'Bookmark details' window (long-press on a bookmark in the Bookmark list).
'Reset text' button restores original selected text.
All bookmarks with edited highlighted text are shown on pressing the 'Filter by edited highligted text' button.
Closes https://github.com/koreader/koreader/issues/9900.
(The main method is `ReaderBookmark:setHighlightedText()`, it saves the edited text to hl and bm, and sets the `edited` flag.
Also minor bookmarks module optimizations, not been revisited for a while).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11484)
> Bookmarks: edit highlighted text

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readersearch.lua
(1) A setting to call Find All by default for highlighted text.
Applicable to Long-press on highlight default action, Search button in highlight popup dialog, Search button in dictionary dialog.
(2) Fix: search results - separate the search string with spaces when needed.
(3) Fix: save last search string when called from highlight dialog.
(4) Fix: reset "find all" cache on new forward/backward search.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11507)
> Fulltext search: default mode, fixes

- frontend/apps/reader/modules/readerfooter.lua
- frontend/dispatcher.lua
- frontend/ui/widget/progresswidget.lua
Toggles between the whole book progress bar and the chapter progress bar.
An option in the status bar settings, an action in the gestures manager.
Closes https://github.com/koreader/koreader/issues/11500.
------------------
Minor side effect: I had to move down @NiLuJe 's initial position marker because, when the progress bar is above the items, the marker is out of the footer container and is not updated properly:
and when the progress bar is below the items, the marker overlaps the items:
Now it is rather good I believe:
As mentioned in https://github.com/koreader/koreader/issues/10233, the marker is nearly invisible when there are many chapter ticks in the progress bar, I am afraid we cannot do anything for narrow progress bars.
The marker is perfectly visible in the chapter progress …
> ReaderFooter: chapter progress bar

- frontend/apps/reader/modules/readertypeset.lua
- frontend/document/credocument.lua
- frontend/ui/data/css_tweaks.lua
- frontend/ui/wikipedia.lua
- frontend/util.lua
Includes:
- Hyphenation: update French.pattern https://github.com/koreader/crengine/pull/553
- [CI] Add stylelint to help prevent typos in CSS https://github.com/koreader/crengine/pull/556
- https://github.com/koreader/crengine/pull/555 : 
- In-page footnotes: better handle duplicated ids 
- lvrend: handle in-page footnotes in table `<caption>`
- lvstsheet: fix compiler warnings
- LVString: ignore CJK chars in `lStr_findWordBounds()`
Closes #11478.
- lvtext: `AddLine()`: handle some CJK + space edge case
See https://github.com/koreader/koreader/issues/11478#issuecomment-1951424809.
- EPUB: look for EPUB3 cover even when EPUB2 cover advertized
See around https://github.com/koreader/koreader/pull/11491#issuecomment-1963021880.
- List items: proper per-specs positionning and sizing
Closed …
> bump crengine: better conformance to the HTML Standard rendering

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/ui/widget/menu.lua
`index` is generated and used by ToC. Fixes https://github.com/koreader/koreader/pull/11484#issuecomment-1988036886.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11534)
> Menu widget: fix item property name

- plugins/wallabag.koplugin/main.lua
A typo snuck in #11492, which should've read `not type(article.mimetype) == "string" or type(article.mimetype) == "string" and not article.mimetype:find("^text/html")`. But in most cases the behavior would've been identically broken because of the same underlying issue: Wallabag mimetype is actually HTTP content-type.
This PR shows two potential solutions while awaiting more concrete information about the actual problem observed in #11528.
Fixes #11528.
There would also be a new setting associated with the behavior in case people have different preferences. Hopefully inspiration will strike soon for the string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11532)
>  Wallabag: properly deal with mimetype actually being content-type

- frontend/ui/screensaver.lua
- frontend/ui/widget/filechooser.lua
percentages shown on the Lock Screen message will now truncate instead of round up. 
fixes #11516
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11541)
> LS msg percentages only reach 100% at final page

- frontend/apps/reader/modules/readercropping.lua
- frontend/apps/reader/modules/readerzooming.lua
- spec/unit/readerhighlight_spec.lua
Based on:
```
function ReaderCropping:setCropZoomMode(confirmed)
if confirmed then
-- if original zoom mode is "page???", set zoom mode to "content???"
local zoom_mode_type = self.orig_zoom_mode:match("page(.*)")
self:setZoomMode(zoom_mode_type
and "content"..zoom_mode_type
or self.orig_zoom_mode)
self.ui:handleEvent(Event:new("InitScrollPageStates"))
else
self:setZoomMode(self.orig_zoom_mode)
end
end
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11438)
> make auto crop default be page content

- frontend/apps/reader/modules/readerstyletweak.lua
As promised in https://github.com/koreader/koreader/pull/11353#issuecomment-1890929091.
Lots of text, may be I went too far... Dunno if we should bother translators with these bits of CSS tutorial...
Anyway, can be handy when needed, when you don't remember the syntax or a name, or just for exploring and getting ideas and experimenting.
I wasn't really inspired when organizing them into submenus... Thought about having them by topic (ie. Footnotes, DocFragments, Making pages), but most of these are not one-topic-centered, and can be used in varied contexts.
(This `noteref-ignore` is not yet available - it just happened this weekend I needed that; so I could write a bit about this fresh use-case. May be I'll complete the descriptions of others when I'll meet again some classic use-cases.) …
> Book style tweak: add more suggestions in "CSS ≡"

- frontend/apps/reader/modules/readerwikipedia.lua
- frontend/ui/wikipedia.lua
Allows setting a default answer to the "Include image" and "slightly higher quality images" questions when saving a Wikipedia article as EPUB.
Closes #10356.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11544)
> Wikipedia EPUBs: add settings for include/highres images

- frontend/apps/reader/modules/readerdictionary.lua
On a PocketBook device the WiFi connection is often not working (cf. #10183). When the connection drops after the initial online test.he current info message may show:
> "Dictionary filesize is %1 (nil bytes). Continue with download?" 
This PR tries to fail more gracefully by showing a custom error message.
(WiFi support on my PocketBook remains shaky though and probably needs more fundamental fixes that cannot be addressed in this PR..)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11548)
> Dictionary: Fix download message when connection fails

- platform/appimage/AppRun
Like in https://github.com/koreader/koreader/blob/master/platform/debian/koreader.sh
If **one and only one** argument is passed and the argument is a path that exists on the filesystem get its absolute path and pass it to lua, because assets dir != pwd and it is impossible to resolve relative paths from there.
Needs to be improved, here on in the future, to handle short options. The most effective way would be to pass `pwd` as a parameter and let the frontend to join `pwd` and `path`. So the frontend takes care of everything :)
Feedback welcome.
Closes #11518
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11552)
> appimage: get full path before changing to assets dir

- frontend/apps/reader/modules/readerview.lua
Fix gif and web files not opening: https://github.com/koreader/koreader/pull/11425#issuecomment-2002164851
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11557)
> Ensure that the pan zoom direction is not nil

- frontend/apps/reader/modules/readerstatus.lua
In the "End of the book" action.
Closes https://github.com/koreader/koreader/issues/11564 (No idea how we got a book without modification time but the time stamp must be updated in any case)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11568)
> ReaderStatus: update status modification time

- plugins/coverbrowser.koplugin/covermenu.lua
Fixes https://github.com/koreader/koreader/pull/11437#issuecomment-2008321927.
First discussion: https://github.com/koreader/koreader/pull/11404#discussion_r1465954851
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11576)
> CoverBrowser: fix file popup dialog

- frontend/apps/reader/modules/readertoc.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/widget/menu.lua
See https://github.com/koreader/koreader/issues/10261#issuecomment-1523993704
> If the lengths can be toggled on/off (so they won't bother anyone), then I think this would be more useful:
`Act V (15) .......   2804`
It is static and states the full chapter length (including the subchapters), it does not update in any way when expanding/collapsing.
(Not heavily tested in the bad ToCs jungle.)
Alternative wording suggestion welcome.
Pinging @jonnyl2, you can test it by just downloading and replacing this file:
https://raw.githubusercontent.com/poire-z/koreader/0b5f2375c02207f70b34f7813c761378c9d2583d/frontend/apps/reader/modules/readertoc.lua
(and if not replacing the other, you'll find the setting at the bottom or 2nd page of the first menu, marked "new").
You can experiment with the …
> ReaderToc: add option to show chapter lengths

- frontend/apps/reader/modules/readerpaging.lua
Fixes (my own) issue #11423.
The fully verbose thought process that led to these changes can be found in the issue.
This works as I'd expect when ran on my PW5, but may be a non-ideal implementation.
I did this by staring at the code for all of one hour; feedback would be welcome if there's a better way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11424)
> ReaderPaging: Enable page-turn animations

- frontend/ui/widget/filechooser.lua
- frontend/util.lua
Changes the sorting for `percent - unopened - finished last` to use a separate property from the percentage for display
re:
- https://github.com/koreader/koreader/pull/11524#issuecomment-1984110990 
- https://github.com/koreader/koreader/pull/11542#issuecomment-2018164346
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11592)
> FileChooser collates: use "item.sort_percent" for sorting + extra `on-hold` handling

- frontend/ui/elements/font_ui_fallbacks.lua
> [i18n] Font UI fallbacks: insert replacement characters with template for Weblate compatibility

- frontend/ui/data/css_tweaks.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11618)
> [minor] CSS tweaks: fix typo cellpading → celpadding

- frontend/apps/filemanager/filemanagerhistory.lua
This fixes ghosting for color Pocketbook devices
Needs https://github.com/koreader/koreader-base/pull/1755.
Fixes #11602.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11603)
> Do `flashui` refresh for first display of History page

- frontend/device/pocketbook/device.lua
- frontend/ui/network/manager.lua
On the PocketBook platform, for some reason, doing the `isOnline` check (`socket.dns.toip("dns.msftncsi.com")`) without having any network connection (`!isConnected`) results in the `isOnline` check never succeeding again even if connectivity is later acquired. Since `socket.dns.toip` is a simple wrapper around gethostbyname(3), we suspect the problem is somewhere deeper in PocketBook's libc, and thus we need to work around it somehow in KOReader.
This fix works around the problem by checking if we have a default route first before even attempting to check `isOnline`. If we don't, then `isOnline` is (almost) guaranteed to fail anyway.
We could alternatively check `isConnected` instead, but that only checks wireless connectivity on many platforms, and we could have internet access via …
> Fix PocketBook losing net access (#10183)

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/dispatcher.lua
- frontend/ui/data/onetime_migration.lua
- frontend/ui/elements/screensaver_menu.lua
- frontend/ui/screensaver.lua
- frontend/ui/widget/filechooser.lua
This PR brings a complete make over to the Lock Screen, currently know as 'screensaver' menu.
NO changes have been made to functionality, this is a strictly cosmetic but comprehensive update.
The following image, showcases the new arrangement of the menu: most names have been changed for ease of use but again no changes to back end code (you can see that though). 
[Book1.pdf](https://github.com/koreader/koreader/files/14595479/Book1.pdf)
Regarding "Hide reboot/poweroff Message", what the **ck does that do? I have never seen such a message and I don't have that selected. Anyway, I was not be able to place it correctly, so please let me know so it can be moved (if needed) to the appropriate place. 
Regarding the newly named "background fill" option, could someone please help me make it so …
> Sleep screen menu reworked

- frontend/gettext.lua
Concretely 1 second, %1 seconds since #11549 added `1 second` all by itself.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11643)
> GetText: fix crash if a value is used as unique value and as singular/plural

- frontend/ui/elements/screensaver_menu.lua
- frontend/ui/screensaver.lua
fixing minor issues with #11549
**Bug:** There appears to be a problem with the `edit sleep screen message` setting, as it shows the older version of the description (not the new and improved `Enter a custom message to be displayed on the sleep screen. The following escape sequences are available:`, see image attached
but I can't see why. it was working fine on my kindle 5 testing machine.
@Frenzie if you are not happy with **the** change, change it back, I promise I won't meddle anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11647)
> Sleep screen wording fixes

- frontend/gettext.lua
Reported in <https://github.com/koreader/koreader/pull/11647#issue-2233008767>.
Probably overlooked in #5807
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11648)
> [i18n] GetText: fix fuzzy detection for certain strings

- Makefile
Use the same code as in base (Cf. https://github.com/koreader/koreader-base/pull/1756).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11659)
> make: fix test rule on Arch Linux

- Makefile
Update sdnio library soversion to account for new docker image based on Ubuntu 20.04.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11662)
> make: fix `appimageupdate` rule

- Makefile
Instead of trying to detect if running under Docker, use a simpler wildcard check to detect if FUSE support is available. This as the advantage of supporting Docker, rootless Docker, and Podman.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11669)
> make: improve `appimageupdate` rule

- Makefile
The FUSE detection is false positive under Gitlab's pipeline, so just use the hidden `--appimage-extract-and-run` option to automatically and always "extract & run" the appimage tool.
Cf. https://github.com/koreader/koreader/pull/11669#discussion_r1561566031.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11671)
> make: improve `appimageupdate` rule, take 2

- plugins/autowarmth.koplugin/main.lua
This is a regression introduced in #10762
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11685)
> Stop touching night mode when control_nightmode == false

- frontend/apps/reader/modules/readerhandmade.lua
options to set 'custom hidden flows' and 'custom ToC' clutter the menus of non-touch devices. There is no available 'page browser' therefore these options cannot be used in them.
Technically you could set the ToC up, but it is SUCH a pain in the *rse you might as well just remove it altogether.
this PR looks scary but all it is really doing is 
```lua
if Device:isTouchDevice() then
EXISTING CODE 
end
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11690)
> hidden flows and custom toc removed from non-touch devices

- frontend/device/pocketbook/device.lua
To add the new PocketBook Era Color (PB700K3) with a 7-inch E Ink Kaleido™ 3 screen.
[crash.log](https://github.com/koreader/koreader/files/15031305/crash.log)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11695)
> Add PocketBook Era Color (PB700K3)

- frontend/device/kindle/device.lua
Fixes #11691 
It turned out there might another type of accelerometer declaration. 
I didn’t quite feel creating another edge case, so instead I shortened current searching keyword “accel” to “acc”. 
@NiLuJe @Frenzie 
Please wait before merge: I want to test this on my own Scribe first. 
Also, I don’t know what to do if there are multiple “acc” matches. (Is this even possible?)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11696)
> Kindle Scribe: fix gyro device detection (again)

- frontend/document/koptinterface.lua
closes #10854 #9272  #4481
Highlighting is still broken in kobo-clara emulator with reflow on. Problem is upstream in `k2pdfopt`
```cpp
void k2pdfopt_get_word_boxes(KOPTContext *kctx, WILLUSBITMAP *src,
int x, int y, int w, int h, int box_type) {
static K2PDFOPT_SETTINGS _k2settings, *k2settings;
PIX *pixs, *pixt, *pixb;
int words;
BOXA **pboxa;
NUMA **pnai;
k2settings = &_k2settings;
/* Initialize settings */
k2pdfopt_settings_init_from_koptcontext(k2settings, kctx);
k2pdfopt_settings_quick_sanity_check(k2settings);
/* Init for new source doc */
k2pdfopt_settings_new_source_document_init(k2settings);  
if (box_type == 0) {
pboxa = &kctx->rboxa;
pnai = &kctx->rnai;
} else if (box_type == 1) {
pboxa = &kctx->nboxa;
pnai = &kctx->nnai;
}
if (*pboxa == NULL && *pnai == NULL && src->bpp == 8) …
```
> Add relevant nil guards to prevent reflow crashes

- frontend/device/pocketbook/device.lua
To avoid avoid having to manually handle the multiple ways a model name reported by inkview can be formatted.
Close #11714.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11721)
> pocketbook: simplify device model detection

- .github/workflows/build.yml
Work around the fact that the lua@5.1 brew formula has been disabled.
Additionally, drop ragel (no necessary anymore).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11660)
> ci: fix macOS build

- frontend/apps/reader/modules/readerview.lua
- plugins/coverimage.koplugin/main.lua
If rotation changes, create a new cache entry and use that if necessary.
See #11713
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11752)
> [CoverImage] Honor rotation after opening of a book

- frontend/apps/reader/modules/readerannotation.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerview.lua
This is a cumulative PR for "annotations and around" fixes.
(1) Fix displayed Bookmark list item text after editing the highlighted text (unreported).
(2) Fix crash on showing anchored highlight dialog if finding text_box fails (https://github.com/koreader/koreader/issues/10854#issuecomment-2093716444).
(3) Lighter line for marking overlapped pages (https://github.com/koreader/koreader/issues/11734).
(4) Fix pdf page bookmarks conversion to annotations (https://github.com/koreader/koreader/issues/11762).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11761)
> Annotations: fixes

- spec/unit/document_spec.lua
The `droid sans fallback` test incorrectly assumes `Droid Sans Mono` will be the first font in the list of fallback fonts, but the list is alphabetically sorted.
Cf. https://github.com/koreader/koreader/pull/10566
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11776)
> tests: fix EPUB test, again

- frontend/device/kindle/device.lua
This fixes the problem on Kindle devices that after exiting out of KOReader **that was started with "--framework_stop" param** stock Amazon UI screensaver image would not be displayed because "screensaver" blanket module was unloaded by KOReader ( here in [in frameworkStopped()](https://github.com/koreader/koreader/blob/12c3c190b012e8c4b070d3e0b4e66b2878a89c7a/frontend/device/kindle/device.lua#L130) function ) and never (re)loaded on exit.
Tested on Kindle PW5 with firmware 5.16.2.1.1 and confirmed that it fixes the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11794)
> Kindle: Fix missing Amazon UI screensaver after exiting KOreader

- frontend/device/devicelistener.lua
- frontend/dispatcher.lua
- frontend/ui/elements/screen_rotation_menu_table.lua
This adds a gesture to toggle the existing "Lock auto rotation to current orientation" option. This is an option that I tended to change relatively often as I switch between reading in bed (and swapping hands) and reading while eating or doing other things that make it harder to hold my device.
I'm hoping I've done everything correctly (and I've tested and verified it works on my device) but if not, let me know and I'll do my best to fix it up.
There's perhaps other cleanups/changes that could be made here since it's a bit confusing that the rotation options are under "Screen" in the settings but under "Device" in the gestures but I just wanted to get this working for me :)
- - - …
> Gesture: Add toggle for orientation lock

- frontend/apps/reader/modules/readerhighlight.lua
closes #11747
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11750)
> [ReaderHighlight] Remove duplicated setting on NT devices

- tools/mk7z.sh
Close #11797.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11800)
> tools/mk7z: fixups

- frontend/ui/widget/dictquicklookup.lua
fix #11783
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11803)
> NT: add Hot swapping dictionaries button and edit button into FocusManager's layout

- plugins/calibre.koplugin/main.lua
I added actions to start/stop the wireless connection to Calibre. This way it's possible start the connection with a gesture / add it to a gesture quick menu.
This is my first PR here, so I hope I've done everything right.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11806)
> Register Calibre start/stop connection actions

- Makefile
- make/android.mk
If the Android NDK and/or SDK are not setup, `kodev` will try to invoke the `android-ndk` and/or `android-sdk` make targets.  This can't be done with `TARGET=android`, as `base/Makefile.defs` will error out trying to call the (missing) compiler to get the target machine. Those rules need to be available to all targets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11817)
> android: fix building with kodev

- frontend/device/generic/device.lua
- frontend/device/input.lua
- frontend/device/kindle/device.lua
- frontend/device/kobo/device.lua
- frontend/device/pocketbook/device.lua
- frontend/ui/uimanager.lua
- plugins/externalkeyboard.koplugin/main.lua
* Kobo: Drop a bunch of if ladder crap and switch to auto-detection of input devices via fbink_input
* Kindle: Drop an even larger bundle of crap to do the same ;p. (re: #11392)
* ExternalKeyboard: Switch to fbink_input to whitelist keyboards instead of the manual parsing of caps via its FindKeyboard class
* Input: Extended open/close wrappers to handle logging & tracking of dupe open/close calls.
Depends on https://github.com/koreader/koreader-base/pull/1782 & https://github.com/koreader/koreader-base/pull/1785
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11807)
> Support auto-detection of input devices via fbink_input

- frontend/device/kindle/device.lua
* Kindle: Don't forget to open INPU_DPAD devices for the fiveways. Somehow managed to skip my mind, they're often on a separate input device.
Regression since #11807
* Update FBInk to fix a few cases of input_scan misdetection (on misconfigured drivers (e.g., no DIRECT prop on supported kernels), or old kernels with no EVIOCGPROP support).
Fix #11824
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11827)
> Kindle: Don't forget about fiveways on legacy devices & fix a couple input-scan misdetections

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/readerui.lua
We do not like trailing slash in the path (except root).
Closes https://github.com/koreader/koreader/issues/11772.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11774)
> FileManager: safe initial path

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/ui/widget/dictquicklookup.lua
- plugins/vocabbuilder.koplugin/main.lua
There is nothing really wrong with the current approach, considering it was added for one specific reason, giving the vocabbuilder plugin access to the popup dictionary.
I created a custom plugin which also adds a button to the popup dictionary, and up until now I didn't care about it overwriting what the vocabbuilder one does.
However, I got a [request](https://github.com/Ajatt-Tools/anki.koplugin/issues/22) last week for it not to do that :slightly_smiling_face: 
I tried getting around making changes to koreader itself by wrapping the `tweak_buttons_func` so it still calls the original one, but also my own on top of it. This didn't work out quite right because each time the user switches between reader and filemanager all plugins get reloaded, meaning it forgets about the function …
> Replace tweak_buttons_func with an event instead

- frontend/apps/reader/modules/readerview.lua
- frontend/ui/elements/page_overlap.lua
Requested by our contributor in https://github.com/koreader/koreader/issues/11734#issuecomment-2104270288.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11804)
> Page overlap: add dashed line marker

- Makefile
- datastorage.lua
- frontend/device/sdl/device.lua
- make/appimage.mk
- make/linux.mk
- platform/appimage/koreader.appdata.xml
- platform/linux/do_debian_package.sh
Add a flavor to represent flatpak limitations (No OTA updates. Cannot restart, reboot, poweroff... )
Include appstream metadata in generic linux packages. Related to https://github.com/flathub/rocks.koreader.KOReader/issues/42
Add version and release data to appstream metadata at build time for appimage/linux flavors. 
Maybe @benoit-pierre could come up with a better `make` | `sed` foo? Thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11833)
> better flatpak support

- frontend/device/pocketbook/device.lua
Many PocketBook devices include a web browser, but when clicking a link in KOReader, there was no option to open the link in the browser, there was only an option to show a QR code (which can then be scanned by a smartphone).
This commit implements `canOpenLink`/`openLink` on PocketBook using the "browser.app", if available.
Tested on PB740 (InkPad 3).
Fixes: https://github.com/koreader/koreader/issues/11782
Related: https://github.com/koreader/koreader/issues/6597
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11787)
> PocketBook: Open links in the on-device web browser

- frontend/apps/reader/readerui.lua
The info messages for opening files always show the full path. By using `filemanagerutil.abbreviate`, the info messages now show the shortened home folder path (only if the setting "shorten home folder" is enabled).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11853)
> Shorten home folder path for info messages

- platform/linux/do_debian_package.sh
Slightly modified to avoid:
```E: koreader: description-starts-with-package-name```
The description looks messy on the script but looks ok when using a GUI to install it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11854)
> debian: update metadata

- frontend/device/input.lua
- frontend/device/kindle/device.lua
- frontend/device/kobo/device.lua
- plugins/externalkeyboard.koplugin/main.lua
Switch to a new `input.fdopen` API & wrapper so we can keep the fds opened by `fbink_input_scan` instead of closing them to re-open them right after that...
This should hopefully help on racy zForce devices that attempt to handle power management when opening/closing the device. We know this sometimes horribly fail to re-activate the IR grid (c.f., our manual activation on resume), but this apparently could also happen here (re: #11844) because of the quick succession of open->close->open.
Depends on https://github.com/koreader/koreader-base/pull/1788
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11855)
> Input: Some more followups to the input device auto-detection stuff

- frontend/device/input.lua
- frontend/ui/widget/screenshoter.lua
PR adds ability to capture screenshots on devices with keyboards and other non-touch kindles.
I've had to turn `ScreenKB` into a mod key, hoping that is not an illegal move..?
on devices (mostly kindles) with keyboards: `Alt` + `Shift` + `G`
on kindle 4: `ScreenKB` + `Menu`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11802)
> Screenshots on Non-Touch 

- frontend/document/credocument.lua
Includes https://github.com/koreader/crengine/pull/565, https://github.com/koreader/koreader-base/pull/1792 : 
- html5.css: really ensure ruby centering
Closes #11771.
- getRenderedWidths(): fix possible crash with 0-width images
Closes #11680.
- Page splitting: ignore empty non-linear flows
See https://github.com/koreader/koreader/issues/8623#issuecomment-2068168592.
- LvDocView header: allow overriding "page/total %"
CreDocument: add setPageInfoOverride() to allow tweaking top status bar display of page number/count/% (to be implemented in a later commit). Will help solving #11561 (and may be others).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11863)
> bump crengine: minor fixes (ruby, a crash, non-linear flows)

- frontend/apps/reader/modules/readercoptlistener.lua
- frontend/apps/reader/modules/readerfooter.lua
- spec/unit/readerfooter_spec.lua
As discussed in #11605 and #11533, here is my proposal for the new and improved `status bar` menu.
No changes were made to the logic besides, adding a few `if isTouch()` statements to a couple of settings that shouldn't be available to non-touch devices (`lock status bar` and `hold to skim`) and any necessary changes for the correct operation of the menu. Also a `checked function` was added to the battery complication on the alternative status bar.
Most of the settings were reworded and/or rewritten. Please don't take it personally if I changed yours.
In defence of "complications": The word is borrowed from horology (science of time and timekeeping) were it refers to features on mechanical watches (smart ones too) that convey information not related to hours, minutes or seconds.
In the …
> [Status bar] Major UI makeover

- frontend/ui/widget/focusmanager.lua
Also add ContextMenu for hold.
@comphilip I don't see much of a reason not to enable these, unless there's a specific reason not to?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11871)
> FocusManager: enable more keyboard shortcuts by default

- frontend/apps/reader/modules/readercoptlistener.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerpagemap.lua
- frontend/userpatch.lua
When using Reference page numbers, "Pages left" was showing the same info as "Current page", because Reference pages, being strings, couldn't be used for arithmetics. But we can just count the number of items left in the Reference pages array of strings.
Closes #11561 (I think I've seen this discussed elsewhere too.)
Also fix edge case with "page progress" with hidden flow when we are before the first chapter with a hidden flow before.
Noticed at https://github.com/koreader/koreader/issues/10193#issuecomment-2106274054.
We now build the "page/total %" string ourselves, with the same logic as used in the footer (including when hidden flows or reference page numbers are used) and give it to crengine to be displayed instead of its own way of doing it.
Uses bits previously added by …
> Footer and header tweaks and fixes

- frontend/ui/widget/menu.lua
- frontend/ui/widget/touchmenu.lua
Reverts koreader/koreader#11872
It'd go better in FocusManager, see https://github.com/koreader/koreader/issues/11880#issuecomment-2129592140
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11881)
> Revert "Global long press on K4, 'ScreenKB' + 'Press'"

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/device/kobo/device.lua
Being able to disable it can be interesting, because it *is* a somewhat destructive process.
Depends on https://github.com/koreader/koreader-base/pull/1794
Fix #11756
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11883)
> Kobo: Boost saturation for CFA refreshes (and add a dev setting to disable it)

- frontend/apps/reader/modules/readerlink.lua
Currently, links with a scheme other than http or https are rejected. But plugins may want to handle them. This allows them to, by registering the scheme with self.ui.link:registerScheme("example") during the plugin's init. (Motivation: I am writing a plugin for the gemini protocol.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11889)
> Add ReaderLink::registerScheme for plugins handling non-http(s) links

- frontend/apps/filemanager/filemanager.lua
Fixes https://github.com/koreader/koreader/pull/11476#issuecomment-2123550940.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11878)
> FileManager copy/move: do not paste to itself

- plugins/exporter.koplugin/clip.lua
- plugins/exporter.koplugin/target/readwise.lua
Recently Readwise started complaining about `note` being required to be filled when sending `"note": ""`, now `nil` is sent instead of `""`.
Not sure if this is koreader recently using different value for empty highlight's note, or Readwise Api changes, anyway exporting works again after this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11912)
> Don't send empty string as note in readwise export

- .github/workflows/build.yml
- platform/mac/do_mac_bundle.sh
The new build system should normally be free from "brew infections", and already have the proper runtime path and library names.
Cf. discussion in #11660.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11924)
> macos: fix bundle

- frontend/apps/reader/modules/readerlink.lua
Following RFC 3986.
The previous code failed on URIs like "about:foo", and on links containing upper case in the scheme.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11942)
> Fix scheme detection for external links

- frontend/device/kobo/device.lua
i.e., poke at the fb vinfo data to check the component offsets.
Fix #11952
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11953)
> Kobo: Check for RGBA vs BGRA the proper way

- frontend/document/pdfdocument.lua
New in 1.24.0. See <https://mupdf.com/releases/history>.
Possible due to <https://github.com/koreader/koreader/pull/11940>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11955)
> MuPDF: add txt, cfb,  docx, xslx, pptx filetypes

- plugins/opds.koplugin/opdsbrowser.lua
* Actually log failures, besides showing the completely unhelpful InfoMessage.
* Handle searches on Calibre.
* Fix content fill on pagination. I have no frickin' clue how the hell this ever worked, as it was using the wrong handler name.
Fix #11968
(Rebase me).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11972)
> OPDS: Fix browsing a Calibre content server

- frontend/apps/reader/modules/readercoptlistener.lua
Fix issue noticed at https://github.com/koreader/koreader/pull/11873#issuecomment-2144485909.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11965)
> AltStatusBar: fix page info when not all 3 items enabled

- plugins/gestures.koplugin/main.lua
It is overridden by the folder tree, so the Gesture manager setting doesn't work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11971)
> Gesture manager: make long-pressing on top left corner non adjustable in FM

- frontend/device/devicelistener.lua
- frontend/device/generic/device.lua
- frontend/ui/elements/physical_buttons.lua
As seen on this [picture](https://newatlas.com/4th-gen-kindle-review/20722/), K4 is ergonomically designed to be held with one hand (one's hand wrapped around the back and both thumb and middle finger on either `PgFwd` buttons).
This PR allows users to individually invert left and right page turners such that it can be operated just with one hand. It also closes #9350 
Not sure if there are any other devices with two sets of page turn buttons, so currently limited to kindle, excluding kindle Voyage, but could be added too, albeit with some gymnastics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11963)
> Individually Invert page turners on kindle

- plugins/autodim.koplugin/main.lua
Even if not from input.
Closes #11979.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11984)
> [plugin] AutoDim: reset counter on page turn

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerthumbnail.lua
- frontend/apps/reader/readerui.lua
- frontend/ui/widget/bookmapwidget.lua
- frontend/ui/widget/buttondialog.lua
as first discussed here #11908. This PR brings the book map to non-touch devices that `useDPadAsActionKeys()`.
Book map can be accessed from the menu or by using the following shortcut: `ScreenKB` + `Down` or `Shift` + `Down` depending on whether you use a K4 device or a kindle with keyboard respectively.
Inside the book map, a user can toggle the hamburger menu by pressing the `Menu` key and make any adjustment from there. `ScreenKB` (or `Shift`) + `Up/Down` allows it to scroll and Page turn buttons to move by whole full page turns. `Back` key allows user to exit the map.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11916)
> BookMap on devices with useDPadAsActionKeys()

- plugins/calibre.koplugin/main.lua
- plugins/calibre.koplugin/metadata.lua
- plugins/calibre.koplugin/parser.lua
Add a proper sax parser for "calibre.metadata" files, using lunajson.
Requires https://github.com/koreader/koreader-base/pull/1801
Fixes #11611
Fixes #11215
Fixes #9016
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11922)
> calibre sax json parser

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/reader/readerui.lua
File browser provides some actions over a group of files.
Let them be available in the file searcher.
To avoid code duplication, after the selection is done in the search results window
let switch to the file browser select mode, keeping the selected files list:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11980)
> File searcher: group operations

- plugins/calibre.koplugin/metadata.lua
- plugins/calibre.koplugin/parser.lua
The issue raised by @benoit-pierre revealed that we might have been mangling on-disk metadata files in the Wireless client, so, make sure this doesn't happen again, and update our parser to deal with it without crashing.
Depends on https://github.com/koreader/koreader-base/pull/1816
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11988)
> Calibre Metadata: Some fixes following up #11922

- frontend/apps/reader/modules/readercoptlistener.lua
With enabled battery percentage shown and some other (e.g. reading percentage) the alt status bar shows the expected line. But when disabling everything except battery percentage, then the reading percentage keeps being shown.
So when using this `self:page_info_override` caching trick, we have to restore the cre default again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12003)
> [AltStatusBar] Fix when showing (almost) empty

- frontend/apps/filemanager/filemanagercollection.lua
Since the collection mark is shown, refresh FM list after certain operations on collections.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11994)
> Collections: refresh list of files in FileManager

- frontend/apps/reader/modules/readerstyletweak.lua
Ignore files starting with "._" (metafiles by MacOS), that will otherwise show up in the Styletweaks menu. (These files are alrady ignored in the File manager, even when 'show hidden files' is enabled.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12022)
> Styletweaks menu: Ignore `._` files

- frontend/ui/screensaver.lua
- platform/kobo/koreader.sh
* On devices with a broken wait_for ioctl, the workaround could apparently lead to a weird race with the framebuffer state change done on exit, which could lead to strange results when displaying "slow" cover content as the sleep screen (#12009).
Stop touching the framebuffer state on poweroff/reboot to deal with this, as that was perfectly useless in these instances anyway ;).
* Consistently prefer the "event" i.e., (powered off/reboot...) message over the *default* message when show_message is enabled. Previously, it only applied when a custom message was *unset*, which hasn't been technically achievable through the UI for... quite a while now (maybe... ever? :D).
Fix #12009
- - - …
> ScreenSaver: Fix a bunch of weird corner-cases

- frontend/ui/network/manager.lua
- frontend/ui/widget/container/inputcontainer.lua
- frontend/ui/widget/keyvaluepage.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/sortwidget.lua
- plugins/kosync.koplugin/main.lua
- plugins/statistics.koplugin/calendarview.lua
- plugins/vocabbuilder.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/11990.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12012)
> InputContainer: consistent input type in onInput()

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/modules/readerhighlight.lua
fixes bug reported here https://github.com/koreader/koreader/pull/11916#issuecomment-2170605117 and unreported issue (... ?) where back button would not close widget in file manager.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12033)
> [ReaderHighlight] Bug fix

- frontend/apps/reader/modules/readerfooter.lua
- frontend/ui/data/onetime_migration.lua
Closes #7642
@hius07 
I just copied the logic from Book title item, so max item width is the same (30%), so users will need to adjust them themselves.
Please let me know if I missed anything.
I added onetime-migration as well and tested on my Kindle Scribe with `koreader-kindlepw2-v2024.04-154-gc8f4008e9_2024-06-08` build. All good! Sorting, enable/disable all work.
Open question: currently it takes all `authors` field, which might include one author, two, or as many as it contains. Should there be a limiting number of authors (configurable)? Say, 3 or 4. I presume this could be done by regex-cutting up to `n` number of commas in the string :D 
Here is a screenshot:
- - - …
> Footer: add book authors item

- frontend/apps/reader/modules/readerbookmark.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12020)
> Annotation list: sort by date

- .github/ISSUE_TEMPLATE/bug_report.md
Closes https://github.com/koreader/koreader/issues/11276
Rewording suggestions welcome!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12042)
> Update bug_report.md with new location of verbose logging toggle.

- platform/kobo/enable-wifi.sh
- platform/kobo/obtain-ip.sh
So it catches non-CLOEXEC sockets properly...
Fix #12043
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12045)
> Kobo: Overengineer the manual CLOEXEC logic in the Wi-Fi scripts

- frontend/ui/data/keyboardlayouts/ar_keyboard.lua
As reported in #12005: ث was duplicated; ظ was missing.
Fixed layout: 
Closes #12005.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12063)
> Fix Arabic keyboard layout (ظ key) 

- frontend/ui/translator.lua
Settings menu items override one another, so placing them in the overriding order.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12051)
> Translator: fix settings menu order

- frontend/ui/widget/screenshoter.lua
Screenshot dialog could not be interacted with in Text editor. Closes #12066.
Thanks to @hius07 for providing the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12067)
> Screenshot dialog fix

- frontend/apps/reader/modules/readergoto.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/widget/skimtowidget.lua
(1) Compact mode, taken from the userpatches in https://github.com/koreader/koreader/issues/11486.
(2) Full mode: long-press on the page number jumps to the start page.
(3) New boookmark symbols.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12046)
> SkimTo dialog: compact mode

- frontend/ui/widget/filechooser.lua
This is a minor annoyance of mine, since the introduction of "sort_percent" (#11592) `0%` and `on hold` marked books intermingle with one another, which was not the original intention (in my mind at least).
As a remainder, "sort_percent" is a local variable used exclusively to organise books in only _this_ sorting mode (percent – unopened – finished last), so should not affect anyone or anything else.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12037)
> [Filechooser] 0% > 'on hold'

- frontend/device/android/device.lua
- frontend/device/cervantes/device.lua
- frontend/device/generic/device.lua
- frontend/device/kindle/device.lua
- frontend/device/kobo/device.lua
- frontend/device/pocketbook/device.lua
- frontend/device/remarkable/device.lua
- frontend/device/sdl/device.lua
- frontend/ui/otamanager.lua
Devices with a single target might want to specify it in `Device.ota_model`
Devices with multiple targets want to override the function or to specify `ota_model` variants for each target.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12014)
> add Device:otaModel()

- doc/Building.md
Taking an interest in KOReader I noticed build notes were missing for my operating system.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12090)
> doc: add Arch Linux building instructions

- frontend/ui/widget/configdialog.lua
Fix unreported crash.
For example, "Word spacing". If we go to the Gesture manager before opening the bottom menu:
After opening the bottom menu:
Will crash on triggering action `⋮` with a gesture or a profile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12093)
> ConfigDialog: fix "toggle with more options"

- frontend/apps/reader/modules/readerbookmark.lua
Followup to https://github.com/koreader/koreader/pull/12053.
Fix crash with no bookmarks in the list.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12112)
> ReaderBookmark: fix sort by date 2

- frontend/ui/otamanager.lua
Fixes #12115
Kobos, Kindles, Remarkables, Cervantes and Pocketbooks that updated to latest (couple of?) nightlies need to perform a manual update.
Sorry :/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12120)
> Fix for OTA updates w/ zsync

- frontend/document/credocument.lua
Fix slowness when top status bar enabled on books with a large number of highlights.
Closes #12119.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12123)
> CRE call cache: don't reset on setPageInfoOverride

- frontend/apps/reader/modules/readerview.lua
Speedup drawing highlights in cre documents a little bit.
Annotations (highlights) are sorted by position.
Positions in a highlight are sorted (start position (pos1) is before end position (pos2)).
While drawing, the iteration over all highlights can be terminated once the start position of a highlight is bigger than the current page bottom position, it means that this and all next highlights are after the current page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12134)
> ReaderView: speedup highlights drawing

- frontend/ui/widget/footnotewidget.lua
- frontend/ui/widget/htmlboxwidget.lua
- frontend/ui/widget/scrollhtmlwidget.lua
Latest MuPDF update changed HTML parsing, and use a better HTML5 parser, which may cause some issues with the XHTML we get from crengine.
So, for footnote popups, be sure we use MuPDF's XHTML parser.
See https://github.com/koreader/koreader/issues/12144#issuecomment-2223853977.
Closes #12144.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12158)
> Footnote popup: fix XHTML handling

- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/ui/elements/physical_buttons.lua
Rewrite of `registerKeyEvents` in both reader paging and rolling. Now setting `useDPadAsActionKeys() = false` reverts to previous key mapping (c. 2024.04). See #11887, #11900 and https://github.com/koreader/koreader/issues/12168#issuecomment-2231692603
Adds <kbd>spacebar</kbd> as `PgFwd` and removes need to use modifiers for `panning` when in continuous mode. (#11749)
Adds option to turn pages with <kbd>Left</kbd> and <kbd>Right</kbd> keys on devices with `useDPadAsActionKeys() = true`. closes #12168
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12174)
> 'Use left and right keys for page turning' option added

- frontend/ui/widget/inputtext.lua
- frontend/ui/widget/scrolltextwidget.lua
- frontend/ui/widget/textboxwidget.lua
- frontend/ui/widget/virtualkeyboard.lua
(1) Speed up adding/deleting chars (by avoiding a call of expensive `splitToChars`), noticeable on big files.
(2) Indicate select mode: wider cursor.
(3) Minor code optimizations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12176)
> Text editor: enhancement

- frontend/apps/reader/modules/readerannotation.lua
(1) Allows annotations with equal `datetime` fields.
(2) Allows page bookmarks with equal page numbers.
Closes https://github.com/koreader/koreader/issues/12167.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12181)
> Annotations: more fixes

- .github/workflows/build.yml
No wonder the macOS builds take so long…
Cf. https://github.com/koreader/koreader-base/pull/1843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12188)
> ci/macos: fix fallback cache key

- frontend/document/credocument.lua
Avoid highlights' xpointers to be recomputed when switching between page and scroll mode, which could make using "Auto-scroll when selection reaches a corner" really slow when having a large number of highlights.
Closes #12156.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12194)
> CRE call cache: don't wrap setViewMode

- frontend/device/sdl/device.lua
...so as not to break the beforeWifiction shenanigans...
Which is most of them, only the Emulator subclass sets it, for... reasons.
(That Emulator quirk is also why we can't simply scrap the whole thing to use NetworkMgr's default imps).
Fix #12203 (thanks to @benoit-pierre for spotting that one).
This was clearly an oversight on my part when working on #10669
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12217)
> SDL: Return true in NetworkMgr:isConnected on !hasWifiToggle platforms

- .github/workflows/build.yml
Avoid breakage on runner image update, like the recent update to XCode 15.4 on arm64 which breaks our (ancient) glib build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12229)
> ci/macos: pin XCode version

- frontend/ui/network/manager.lua
- frontend/ui/network/wpa_supplicant.lua
Also, add a crapload of debug logging.
c.f., https://github.com/koreader/lj-wpaclient/pull/11 for all the gory details.
(PR is safe on its own, but stuff works better with everything merged, obviously ;p).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12236)
> NetworkMgr: Attempt to handle wpa_supplicant rescans better

- Makefile
This will avoid replacing data files in crengine with symlinks, when building the latest master without cleaning first.
Note: `build/x86_64-pc-linux-gnu-debug/data` will still be a symlink, so a clean is still needed to avoid creating build artifacts in crengine checkout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12259)
> make: handle old build data directory

- frontend/apps/reader/modules/readerannotation.lua
- plugins/exporter.koplugin/clip.lua
Restore `pageno` field for KOHighlights, add `pageref` field for Exporter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12261)
> Annotations: fix exporting

- frontend/device/generic/powerd.lua
- frontend/device/kobo/powerd.lua
Hopefully in the least intrusive way possible, because frontlight handling code is hell.
`self.fl_was_on` could go out of sync with the expected state when resume->suspend events happened in very quick succession, leading to it being set to false, preventing the frontlight from being turned back on on the next resume.
Fix #12246
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12256)
> Kobo: Track frontlight state more accurately on suspend/resume

- make/android.mk
I wanted to check https://github.com/koreader/koreader-base/pull/1886 on my old arm64 phone running Android 9, and could not get dictionary lookups to work…
The arm build, meanwhile, was still working fine until a reset of luajit-launcher to a pristine state. And the gradle build failed after fixing the update rule because apparently the change of type, symlink → file, is not handled. Yeah…
Close #12268.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12275)
> make: fix android update sdcv

- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/readhistory.lua
No need to look it up when we already provide it ;).
(Noticed because I had an item that refused to get removed on an old device. And because I'm an idiot, I fixed it without backing up the history.lua -_-".)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12253)
> ReadHistory: On remove, trust the index from FileManagerHistory if possible

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/document/credocument.lua
Getting text from xpointers to get the current selected word context would have crengine unhighlight that word. Allow to get it selected again when done getting context.
See https://github.com/koreader/koreader/issues/12250#issuecomment-2263754719.
Closes #12250.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12288)
> Fix early unhighlight after Add to vocab builder

- frontend/ui/network/manager.lua
Prevent crash:
```
./luajit: frontend/util.lua:1092: attempt to get length of local 'str' (a nil value)
frontend/util.lua:1092: in function 'fixUtf8'
frontend/ui/network/manager.lua:1109: in function 'requestToTurnOnWifi'
[…]
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12297)
> NetworkMgr: fix debug trace

- frontend/document/document.lua
When zooming to a small panel on a device with a large display, the resulting zoom factor often causes `renderPage()` to only render the panel itself instead of the whole page.  `getPagePart()` needs to account for that when extracting the panel from the rendered tile.
Fixes half of #7961 (namely the black/half-black rectangles)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12296)
> Panel zoom: Properly handle `renderPage()` not rendering the whole page

- frontend/device/devicelistener.lua
- frontend/device/generic/powerd.lua
- frontend/device/kobo/powerd.lua
- frontend/ui/widget/frontlightwidget.lua
While #12256 papered over the tracking of a *single* suspend -> (resume->suspend) series of events, things still go out of sync if you tack on *more* suspend/resume events after that.
The upside is that our *actual* tracking of suspend/resume is solid, so at least we're actually doing the right thing as far as PM is concerned.
The downside is that on Kobo, the frontlight handling code is full of delays, and the ramping down/up itself also takes some time, so things can quickly overrun into the wrong event.
This means a couple of things:
* We need to cancel any scheduled frontlight toggles and ramps on Kobo, to ensure that only the one from the *last* event received goes through, in an attempt to limit the amount of potential crossover.
* Tracking fl_was_on *cannot* reliably be done from …
> PowerD: Keep track of frontlight state change by interactive callers for suspend/resume purposes

- frontend/dispatcher.lua
- plugins/profiles.koplugin/main.lua
Mainly a difference without distinction, but in some edge cases like screenshots it keeps the menu on the screen. See <https://github.com/koreader/koreader/pull/12293#issuecomment-2269680044>.
The "Show as QuickMenu" is really just for balance; it makes little to no difference.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12299)
> Profiles: make sure to close menu/quickmenu before executing action

- frontend/ui/widget/textwidget.lua
Currently I get
```
08/07/24-20:48:39 DEBUG Found font: DroidSansMono.ttf in ./fonts/droid/DroidSansMono.ttf 
./luajit: frontend/ui/widget/textwidget.lua:181: Wrong text type (expected string)
[C]: in function 'assert'
frontend/ui/widget/textwidget.lua:181: in function 'pre_guard'
frontend/dbg.lua:46: in function 'updateSize'
frontend/ui/widget/textwidget.lua:303: in function 'getWidth'
frontend/ui/widget/menu.lua:199: in function 'init'
frontend/ui/widget/widget.lua:46: in function 'new'
frontend/ui/widget/menu.lua:1081: in function 'updateItems'
frontend/ui/widget/menu.lua:1000: in function 'init'
frontend/ui/widget/widget.lua:46: in function 'new'
frontend/apps/reader/modules/readertoc.lua:833: in function 'onShowToc'
frontend/apps/reader/modules/readertoc.lua:1019: in …
```
> Allow numbers in measure text: fixes a crash in table of contents when debugging on

- frontend/apps/reader/modules/readerfooter.lua
- frontend/device/devicelistener.lua
- frontend/dispatcher.lua
* Adds page-turn item to status bar to indicate inversion active. (somewhat proposed here https://github.com/koreader/koreader/pull/11963#issuecomment-2146336376)
</p>
* Show notification when inverting page-turn buttons from gestures. closes #12239
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12249)
> ReaderFooter: Add page-turn item

- Makefile
- kodev
- make/android.mk
It doesn't make sense to have base compile a version of luajit, use it to build all dependents, to run checks (`bincheck`), and then just chuck it away when generating the APK to rebuild another version.
With this PR, we keep the luajit library already built.
The luajit-launcher build is also now completely done out-of-tree (e.g. in `koreader-android-armv7a-unknown-linux-android18/luajit-launcher`), which means, except from some vestigial gradle output (an empty `platform/android/luajit-launcher/.gradle/kotlin/errors` directory), everything is cleaned on `make clean`.
Note:
- `make fetchthirdparty` will now fetch all submodules recursively (including luajit-launcher and its submodules)
- libraries are now stored in the application standard directory …
> luajit launcher: out of tree build + don't rebuild luajit

- make/android.mk
Missing `module/version.txt` would trigger a "new install" on every launch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12333)
> fix missing android APK asset

- frontend/ui/widget/imageviewer.lua
- frontend/ui/widget/imagewidget.lua
Input events from ImageViewer can be caught between it clearing an old ImageWidget & instantiating a new one, but before the new one has had a chance to actually render anything.
Fix #12327
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12331)
> ImageWidget: Don't attempt to pan if we haven't rendered the bb yet

- frontend/device/kobo/device.lua
- frontend/device/kobo/powerd.lua
I don't even remember how badly things broke (at least on old devices) without it, despite it making absolutely no sense at all (state-extended just flips a global that dictates whether some things get flagged as wakeup sources or not).
So, don't rock the boat too much: we don't remove it, but instead of using a sleep, we use a task deadline instead, which ensures we'll keep processing input events in the right order in the meantime. We'll already have neutered input by this point, so we'll only process power events anyway.
That means that the only iffy things are potentially *when* and *where* we have to potentially cancel that task. Resume makes sense, of course, and we log an info message to make the log flow clear; but we also do so in suspend... just in case. With a warning log …
> Kobo: Refactor suspend in order to be able to catch input events sent during the 2s window of ntx madness

- frontend/ui/widget/menu.lua
`mergeTitleBarIntoLayout()` was first introduced in #9041, but it's a solution that hasn't aged well. Kindle NT devices can now access all (bar one) of these "title bar" menus via key presses so, it makes little sense to keep this "solution" available there, particularly when it can in fact make the experience rather cumbersome. See #10301
* In FM, home (top left) can be accessed by pressing the <kbd>Home</kbd> key.
* In FM, plus menu can be accessed from the **TOP MENU**
* In widgets, hamburger menus (top left) can be accessed  by pressing <kbd>Menu</kbd> key. #11966
the only thing that would be unavailable is long-press (hold) on the top-left items (home on FM, hamburger menu elsewhere), but those are not essential so, fair game?
* fixes #10301
- - - …
> [Menu] Remove title bar buttons from layout on hasSymKey or hasScreenKB

- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readersearch.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/apps/reader/modules/readerwikipedia.lua
* Support <kbd>ctrl</kbd> keyboard shortcuts where appropriate  See https://github.com/koreader/koreader/pull/12162#issuecomment-2273884263 
Fix #10499 (Again)
*  Bring `ToC` and `Bookmark` shortcuts on par on all NT kindles.
-hey dwarves!- he yelled, -sometimes fighting the dragon isn't the only way, "eat one" I'm going back to The Shire-. -- Bilbo B. (The Hobbit, alternative ending)
Heroism isn't just about facing the beast, but if @ryanwwest has anything else to add after this is merged... I just might. -- somebody (probably).  ;)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12347)
> Support 'Ctrl' shortcuts on hasKeyboard

- frontend/apps/reader/modules/readerpanning.lua
- frontend/ui/elements/menu_keyboard_layout.lua
* Fix conflicting mapping on kindles with keyboards. see https://github.com/koreader/koreader/issues/12340#issuecomment-2284928923
* Add infoMessage to Kindle 4 with correct modifier (genuine overlook from #12162 )
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12341)
> Bug Fix: DPad conflict on Kindle Keyboard

- Makefile
- kodev
- make/android.mk
- make/emulator.mk
- tools/graph_memory.sh
Factorize (options handling, target setup, …), add explicit
Android targets (`android-arm`, `android-arm64`, etc…).
`build`:
- support `--no-build` / `-b`: only run setup phase
check: simplify implementation (re-use `.ci/check.sh`)
`cov` & `test`:
- forward to makefile rules (no need to guess install directory)
- support `--no-build` / `-b`: use existing build
`log`:
- drop the target argument (since only Android is supported anyway)
`prompt` & `wbuilder`:
- forward to makefile rules (no need to guess install directory)
- support `--no-build` / `-b`: use existing build
`release`:
- support `--no-build` / `-b`: use existing build
`run`:
- forward to makefile rules (no need to guess install directory)
- correctly support relative arguments, and whitespace in arguments
- drop support for …
> kodev rework

- frontend/ui/widget/textviewer.lua
* Add hamburger menu to FocusManager and <kbd>Menu</kbd> key
another stray widget that needs its menu mapped to Menu key. borrowing code from @NiLuJe to fix focusmanager shenanigans.
I might be pushing the functionality of `Device:useDPadAsActionKeys()` to mean, has a dedicated <kbd>Menu</kbd> button... await judgment there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12365)
> [TextViewer] Add hamburger menu to FocusManager and Menu key

- frontend/ui/screensaver.lua
- frontend/ui/widget/footnotewidget.lua
- frontend/ui/widget/sortwidget.lua
* Don't refresh the status bar over footnote "popups" (I originally got duped by the fact that it's not actually a popup *at all* unlike the setting implies, it's a BottomContainer on top of ReaderUI ;p) (re #12323).
* Fix SortWidget quirks on NT (fix #12342).
(Rebase me)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12359)
> A couple of tiny fixes

- make/android.mk
- silence unnecessary verbose update step
- tweak APK name: use `ANDROID_NAME` for last part so setting it as an environment variable to something like `dev` allows for a stable APK across different revisions
- remove old in-tree build artifacts that could conflict (`assets/libs` & `assets/module`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12370)
> android: tweak update rule

- frontend/apps/reader/modules/readerfont.lua
- frontend/ui/font.lua
In font selection menus, ask creengine for italic versions of fonts if there's no regular version to preview. Also prevents a crash when a font can't be previewed in the font family menu.
Bold-only fonts already work, so no need to cover that case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12351)
> Display menu preview of italic-only fonts

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/ui/widget/button.lua
- frontend/ui/widget/buttontable.lua
- frontend/ui/widget/skimtowidget.lua
(1) **Book info**: swap "Current page" - "Rating, review". https://github.com/koreader/koreader/pull/12313#issuecomment-2294960877
(2) **Bookmark settings**: "note if set, otherwise highlighted text" item text. https://github.com/koreader/koreader/issues/12362#issuecomment-2294996939
(3) **SkimTo**: increase buttons height in compact mode. https://github.com/koreader/koreader/issues/12362#issuecomment-2293007362
Before
After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12374)
> UX minor fixes

- plugins/terminal.koplugin/main.lua
This shall fix #12271 
Use `$SHELL` env-variable if available. (thanks to @Frenzie)
Use a read line wrapper (either rlfe or rlwrap) if available so that dash can be used as interactive shell.
(The usage of rlwrap with dash offers a new bug where some chars are displayes duplicated ...
Thats why rlfe is the primary choice. A bug fix will follow next week. Anyway this PR is fully functional.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12375)
> Fix terminal broken cursor and backspace

- frontend/ui/elements/screensaver_menu.lua
- frontend/ui/screensaver.lua
Checkbox in Wallpaper->Border fill to rotate images to fill as much of the screen as possible. It's basically what NiLuJe suggested in #11856 about checking the image's orientation. Passing a buffer directly avoids the ImageWidget cache trick that loads and stretches in one step.
A note about SVG: They're rendered here in their "native" resolution and so won't scale up correctly when rotated. Some math could fix that, but I doubt many people use SVG wallpapers.
I considered adding a rotate_to_fit setting to ImageWidget instead (ignoring orientation), but rotating *before* stretching a loaded file would require some refactoring, or at least an ugly-specific setting to disable the cache hack in _loadfile().
Test images if you like:
PNG
SVG
Fix #11856 
- - - …
> Screensaver: add option to rotate to fit screen

- frontend/apps/filemanager/filemanagercollection.lua
Consistent with the History context menu. Closes https://github.com/koreader/koreader/issues/12225.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12383)
> Collections: fix context menu

- frontend/apps/reader/modules/readerkoptlistener.lua
- frontend/apps/reader/modules/readerview.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12391)
> PDF: no "Contrast set to" notification on opening

- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/ui/widget/footnotewidget.lua
- frontend/ui/widget/htmlboxwidget.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/textboxwidget.lua
When a profile changes a few settings (ie. font), a few notifications may be stacked, before the single rerendering happens. If that rendering takes some time, the notifications' timeout may close them as soon as it is done, before they get a chance to be painted/refreshed.
So, delay a bit more that rerendering to be sure the notifications are shown.
(Fix 2nd item at https://github.com/koreader/koreader/pull/10083#issuecomment-1646985078.)
Avoid two identical stacked notifications "Book tweak not modified" after Close + Discard when text was modified.
(I may have been a bit too lazy to fix that at the time I made it...)
See https://github.com/koreader/koreader/pull/9586#issuecomment-2308894830.
MuPDF's own stylesheet is incomplete, and doesn't specify that a few common (and uncommon) …
> Various notification, text editor and footnote popup minor fixes

- kodev
- make/android.mk
- tools/logcat.py
- standalone: no other dependencies than Python (>= 3.7) and adb (Android >= 4.3 [Jelly Bean])
- filter KOReader's traces, and other processes chatter about KOReader (e.g. mentions of its application ID or PID)
- show time, PID, TID (when different), tag, priority, and message
- only parse the log (don't rely on `adb shell` commands)
- can be used as a filter, including on its own (uncolored) output
- we can simplify instructions to users when asking for detailed logs
Why not use pidcat?
- project is unmaintained
- does not support Python 3 (need at least one extra patch)
- mangle long lines by wrapping them, even when not outputting to a terminal, which is a big no-no, IMHO (as it break searching, copy pasting, etc…)
Vanity shot:
- - - …
> android: add custom `adb logcat` formatter

- kodev
Need to install the NDK / SDK when not configured.
Close #12404.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12407)
> kodev: fix `./kodev run android…`

- frontend/apps/reader/modules/readerfont.lua
Supersedes botched PR #12088. 
Changes:
1. If font menu is sorted by recently selected fonts, the current document's font will be listed first
2. When generating a font test document, if there are newly installed fonts in the current session, they will be listed first in the generated font test document, with "[NEW]" prepended.
3. Small wording changes (I decided to leave the "Would you like to..." as I see we use this phrasing in quite a few other places and there's no particular reason why it should be changed here.)
Thanks @poire-z for help and review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12410)
> Readerfont: Current font on top in menu; New fonts from current session on top in font test doc

- frontend/apps/filemanager/filemanager.lua
It's used on Android when we're murdered by the task switcher, and when doing an OTA update.
Fix #12124
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12425)
> FileManager: Handle the FlushSettings event

- frontend/ui/widget/pagebrowserwidget.lua
Bottom and right edges were not drawn since some recent FrameContainer tweak.
See https://github.com/koreader/koreader/pull/11364#issuecomment-2310107304.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12432)
> PageBrowser: fix drawing of thicker thumbnail frame on tap

- frontend/apps/filemanager/filemanagersetdefaults.lua
The actual defaults table is a hash, so we have no way of salvaging it from there without using a custom NULL type or another kind of sentinel value.
But since everything that actually *uses* the offending defaults expects a nil, don't rock the boat, and just fix the Advanced Settings widget to be able to deal with it.
Fix #11679
Regression since #9546
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12433)
> FileManagerSetDefaults: Handle strings that we default to nil

- frontend/device/input.lua
- frontend/device/kindle/device.lua
- frontend/device/kobo/device.lua
On Monza, the lift frame can report these for *multiple contacts* without an id or a slot, which is super-duper invalid -_-".
(And we have ABS_MT_POSITION_X & ABS_MT_POSITION_Y for the "saner" frames, plus these devices generally don't support pens, so we don't make use of pressure).
(Also, switched to a dedicated handler like for the phoenix quirks, to avoid bogging down the standard handler with hacks for broken drivers).
Fix #11910
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12427)
> Input: Ignore ABS_X, ABS_Y & ABS_PRESSURE for snow_protocol

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/document/pdfdocument.lua
- frontend/ui/widget/checkbutton.lua
- frontend/ui/widget/container/framecontainer.lua
- frontend/ui/widget/imagewidget.lua
- frontend/ui/widget/radiobuttontable.lua
- frontend/ui/widget/radiobuttonwidget.lua
- frontend/ui/widget/textboxwidget.lua
- plugins/terminal.koplugin/main.lua
Pass a configurable ColorRGB32 to bb:paintRect / bb:lightenRect.
If isColorEnabled is unset then original B&W Color8/uint8_t is passed in.
Requires corresponding Cbb patch.
https://github.com/koreader/koreader-base/pull/1680
Fix #9024 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11044)
> Add color highlight menu

- frontend/apps/reader/modules/readerhighlight.lua
- plugins/exporter.koplugin/clip.lua
- plugins/exporter.koplugin/main.lua
Cannot find the feature request, maybe it was on mobileread.
The use case was learning new words: highlighting them with a dedicated style (along with other usual highlights/notes), adding notes with translation, and then exporting only them for further repetitive learning.
(A lot of diffs in clip.lua are just wrapping into `if`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12431)
> Exporter: choose highlight styles to be exported

- frontend/apps/reader/modules/readerview.lua
- frontend/document/pdfdocument.lua
(They'll be drawn in gray, as before)
Regression since #11044
(https://github.com/koreader/koreader/pull/11044#issuecomment-2322820971)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12438)
> ReaderView: Don't crash on pre-#11044 highlights without a color field

- plugins/terminal.koplugin/main.lua
- plugins/terminal.koplugin/terminputtext.lua
Main effect is to make terminal usably fast with TUI programs which make extensive use of escape codes, which previously it wasn't (for me).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12369)
> Terminal fixes

- frontend/device/devicelistener.lua
- frontend/dispatcher.lua
Adds to Dispatcher the option to temporarily turn on the accelerometer for 5 seconds. This allows users who normally like to keep the accelerometer to OFF to call this feature, rotate their device, and then forget about it (no need to remember turning it back off).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12419)
> Dispatcher/DeviceListener: Temporarily turn on Accelerometer/GSensor for 5 sec

- plugins/exporter.koplugin/target/joplin.lua
This PR addresses the bug reported in #12180
The Joplin api endpoint koreader uses to send highlights expects a JSON object with a string field `body` ([joplin docs](https://joplinapp.org/help/api/references/rest_api/#post-notes)) but koreader currently sends an array.
Example trying to export a highlight:
```
> 2024/09/01 15:46:56.000272134  length=157 from=0 to=156
POST /notes?token=<token> HTTP/1.1\r
> 2024/09/01 15:46:56.000286062  length=423 from=157 to=579
User-Agent: KOReader/2024.07 (https://koreader.rocks/) LuaSocket/3.1.0\r
TE: trailers\r
Content-Type: application/json\r
Connection: close, TE\r
Host: 192.168.178.72:41190\r
Content-Length: 231\r
\r
{"title":"<book title>","body":["# <heading>","##### <author>\\n","## <chapter>","### <page  number & date/time>","<highlighted …
```
> fix bug preventing export to joplin;

- frontend/ui/widget/inputtext.lua
The drive-by fix for the original issue noticed late in #12361 turned out to be a bit heavy-handed ;).
Fix #12444
Regression since #12361
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12449)
> InputText: Unbreak onTapTextBox on an already in-focus field

- frontend/apps/reader/modules/readerview.lua
Namely, it trips a `recalculate` that snaps `visible_area` to `page_area` edges (depending on zoom/reading direction), while we do *NOT* actually want to move the view, just increase/decrease its height ;).
(This *might* happen more reliably than it used to since https://github.com/koreader/koreader/pull/11425 & https://github.com/koreader/koreader/pull/11557)
Also deal with scroll mode while I'm here, as recalculate doesn't affect scroll mode at all, since that uses an *array* of on-screen pages, each with their own visible_area, page_area & state.
Fix #12454
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12466)
> ReaderView: Fix a couple of edge-cases in onReaderFooterVisibilityChange

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/languagesupport.lua
- frontend/util.lua
Instead of duplicating it across ReaderHighlight, languagesupport, and potentially VocabBuilder.
Re: #12469
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12477)
> misc: Move cleanupSelectedText to util

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerview.lua
(Also minor fixes and UX standartization)
Closes https://github.com/koreader/koreader/issues/12439. Closes https://github.com/koreader/koreader/issues/11845.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12461)
> Highlights popup dialog: add "Color" and "Details" buttons

- frontend/apps/reader/modules/readerpaging.lua
Page buttons call `GotoViewRel` again (not `GotoPosRel`). Fixes https://github.com/koreader/koreader/issues/12380
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12495)
> [NT] Call GotoViewRel for page up/down on useDPadAsActionKeys devices

- defaults.lua
- frontend/apps/filemanager/filemanagersetdefaults.lua
- frontend/ui/data/onetime_migration.lua
It's no longer in use since #11977, dropping it ensures we stop showing it in the advanced settings UI.
(Rebase me)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12504)
> Defaults: Deprecate DKOPTREADER_CONFIG_DOC_LANGS_TEXT

- frontend/apps/reader/modules/readerannotation.lua
Supercedes https://github.com/koreader/koreader/pull/12493.
Closes https://github.com/koreader/koreader/issues/12492. Closes https://github.com/koreader/koreader/issues/12443.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12494)
> ReaderAnnotation: skip old highlights with invalid xpointers

- frontend/apps/cloudstorage/syncservice.lua
- plugins/statistics.koplugin/main.lua
- plugins/vocabbuilder.koplugin/main.lua
This pr removes the backup db (sync db) of the cloud syncing strategy when a different server location is used. This is to avoid the situation when later incoming db is not based on previously uploaded sync db.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12470)
> Cloud Sync: handles potentially incompatible backup and incoming dbs

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/apps/reader/readerui.lua
- frontend/device/devicelistener.lua
- frontend/ui/data/onetime_migration.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
Closes https://github.com/koreader/koreader/issues/12500.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12509)
> Write highlights into PDF: revisited

- frontend/apps/cloudstorage/syncservice.lua
Aligns with the CloudStorage behavior.
Fix #12518
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12520)
> SyncService: Only require online connectivity when using Dropbox

- frontend/apps/reader/modules/readertypeset.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/ui/data/creoptions.lua
- frontend/ui/data/koptoptions.lua
- frontend/ui/data/onetime_migration.lua
- frontend/ui/data/optionsutil.lua
- frontend/ui/elements/common_settings_menu_table.lua
Specifically, doc open runs the value through `scaleBySize`, as expected, but the event handler did not.
Switch the setting to a buttonprogress to allow using more_options in a less clunky fashion.
Also show the actual value in pixels in the long-press recap & notification.
This involved an extension of some helpers in optionsutil, and made me realize that I find showing these flex pixels as actual device pixels instead of mm/in much much much much more relevant, so, err, RFC to actually do something more involved on that front (expand the mm/in toggle to a mm/in/px tristate? Always show px in addition to mm/in?)
(Rebase me)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/korea …
> Fix page gap inconsistencies between doc open & config change

- plugins/vocabbuilder.koplugin/main.lua
Closes #12529.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12530)
> VocabBuilder.koplugin: save dict headword as entry

- frontend/device/pocketbook/device.lua
To add the new PocketBook Verse Pro Color (PB634K3) with a 6-inch E Ink Kaleido™ 3 screen.
[crash.log](https://github.com/user-attachments/files/16908777/crash.log)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12476)
> Add PocketBook Verse Pro Color (PB634K3)

- frontend/dispatcher.lua
- plugins/profiles.koplugin/main.lua
Reverts koreader/koreader#12299
See https://github.com/koreader/koreader/pull/12498#issuecomment-2339626911
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12534)
> Revert "Profiles: make sure to close menu/quickmenu before executing action"

- plugins/statistics.koplugin/main.lua
(1) Followup to https://github.com/koreader/koreader-base/pull/1921, https://github.com/koreader/koreader/pull/12503: when getting a pdf book id in the stats db, check for old records with null terminated authors and title.
Discussed in https://github.com/koreader/koreader/issues/11318. There are some other reasons for disappearing old stats for pdf (md5 changes when converting/writing to pdf or something else), hence not closing the issue.
(2) Add Dispatcher action for toggling statistics. Closes https://github.com/koreader/koreader/issues/11422.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12547)
> Statistics: fix null terminated strings, add toggle stats

- frontend/device.lua
- frontend/device/cervantes/device.lua
- frontend/device/generic/device.lua
- frontend/device/input.lua
- frontend/device/kindle/device.lua
- frontend/device/kobo/device.lua
- frontend/device/pocketbook/device.lua
- frontend/device/remarkable/device.lua
- frontend/device/sdl/device.lua
- frontend/device/sony-prstux/device.lua
- make/appimage.mk
- plugins/externalkeyboard.koplugin/main.lua
- spec/unit/device_spec.lua
In preparation of koreader/koreader-base/pull/1929.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12486)
> input: drop use of `ffi/input`

- .ci/test.sh
Use `BUSTED_OVERRIDES`, as `BUSTED_SPEC_FILE` was removed in 93c7ceccd9f3bab110dc230cfb07ba5ae16ced3c.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12551)
> ci/circle: fix tests parallelism

- frontend/device/kobo/device.lua
I missed converting one call of `Input.open` to a method call in #12486.
Cf. https://github.com/koreader/koreader/issues/12522#issuecomment-2374556131.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12553)
> input: fix kobo init

- frontend/apps/reader/modules/readerfooter.lua
- frontend/device/devicelistener.lua
- frontend/dispatcher.lua
- frontend/ui/elements/physical_buttons.lua
* currently, the page-turn item introduced in #12249 will not automatically update the status bar. This removes the need to make manual changes (i.e turn the page) before changes are reflected on screen.
* update `onSwapPageTurnButtons` event handler to deal with all turn-page inversions
* adds two dispatcher entries so they can be used through Profiles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12424)
> [ReaderFooter] update status bar in real time when inverting page turning

- frontend/device/kindle/device.lua
- frontend/device/kobo/device.lua
- plugins/externalkeyboard.koplugin/main.lua
The library is versioned.
Cf. https://github.com/koreader/koreader/issues/12558#issuecomment-2377658280.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12560)
> input: fix loading of `fbink_input` library

- frontend/ui/quickstart.lua
Spotted while updating a translation. FWIW [codespell](https://github.com/codespell-project/codespell) can be pretty handy in CI/CD.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12566)
> Fix typos in quickstart

- frontend/ui/widget/dictquicklookup.lua
* Adds key events to edit dictionary queries i.e., self.word
* ~~Adds Home event~~
* local dict-widget's type to search
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12539)
> [DictQuickLookup] shortcuts for editing searches

- frontend/apps/reader/readerui.lua
- frontend/ui/data/onetime_migration.lua
- plugins/profiles.koplugin/main.lua
Added opening and closing document so far.
Automation usage examples:
-show ToC on opening a document
-set different frontlight levels for FM and Reader
-disable touch input in Reader for devices with page-turn buttons and enable it in FM
Further possible development:
-add more events
-extend `ReaderReady` event to handle doc props, for example, execute different profiles depending on doc language.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12564)
> Profiles: auto-execute on events

- frontend/device/kobo/device.lua
- kodev
- make/kobo.mk
- make/kobov4.mk
- make/kobov5.mk
kobov4 exists solely because there's a dedicated TC for it, but we won't distribute binaries for it (it doesn't differ enough from kobo, and experience has taught us that this kind of split was not a great idea (e.g., kindle5 vs. kindlepw2)).
kobov5 targets a massively updated userland, and requires further changes, including to the delivery mechanism, so it very much warrants a dedicated package (re: #12401)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12568)
> Add kobov4 & kobov5 targets

- frontend/apps/reader/modules/readerdictionary.lua
- make/android.mk
We can get rid of the `libs` and `sdcv` symlink in application files.
Depend on https://github.com/koreader/koreader-base/pull/1920.
Close #12348.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12576)
> android: switch to monolibtic mode

- make/android.mk
- fix SDK location: our install has 2 different versions: under `tools/bin/apkanalyzer` and `cmdline-tools/latest/bin/apkanalyzer`, but only the later is functional (trying to use the former raise some classpath exceptions)
- always use the SDK location, don't try to detect it: it's better to fail with a more explanatory "apkanalyzer: command not found" error than having the shell try to run a command with the wrong executable (`manifest …` because `$(APKANALYZER)` is empty)
Close #12562.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12563)
> android: fix apkanalyzer location

- frontend/device/android/device.lua
- Disabling rotation map for Android devices mentioned in https://github.com/koreader/koreader/issues/9223 and https://github.com/koreader/koreader/issues/12423
- The implementation replaces necessity of using user patches
- The solution is similar to the one used for Pocketbook https://github.com/koreader/koreader/issues/10123
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12557)
> Disabled rotation map for Android devices where "hw media keys follow gravity"

- platform/android/llapp_main.lua
No need for dlopen machinery with monolibtic library.
Depend on https://github.com/koreader/android-luajit-launcher/pull/519.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12594)
> android: drop unnecessary code

- frontend/ui/widget/progresswidget.lua
I've observed a slight misalignment in the progress widget on the reading progress page on my Kobo Libra 2. 
Especially, the problem becomes particularly noticeable when I try to change fonts on the reading progress page.
The progress widget use paintRect and paintBorder to draw the background and the border sharing the same starting pos x and y. The misalignment is due to the different rounding method. [paintRect floors x and y](https://github.com/koreader/koreader-base/blob/0efd201bdfd948e2336ca83120335767c2a59cdd/ffi/blitbuffer.lua#L1174) but [paintBorder ceils x and y](https://github.com/koreader/koreader-base/blob/0efd201bdfd948e2336ca83120335767c2a59cdd/ffi/blitbuffer.lua#L2062).
This misalignment problem occurs when x or y is not integer.
I've made a minor adjustment to the …
> ProgressWidget: fix misalignment

- platform/cervantes/disable-wifi.sh
- platform/cervantes/enable-wifi.sh
This PR adds wifi support for the older Cervantes Touch Light device (PCB_ID==23) which uses a different wifi driver than the newer models. 
To enable wifi, the module to insert is "dhd" rather than 8189fs, and wpa_supplicant needs to use the "nl80211" driver.
Disabling wifi has also been changed to avoid removing the "dhd" module as it leaves the wifi subsystem completely frozen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12148)
> Add wifi support to Cervantes Touch Light devices

- frontend/ui/data/creoptions.lua
- frontend/ui/data/koptoptions.lua
- frontend/ui/data/optionsutil.lua
- frontend/ui/elements/screen_rotation_menu_table.lua
- plugins/profiles.koplugin/main.lua
For example, auto set 2-columns in landscape mode:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12612)
> Profiles: add "on rotation" auto-execute event

- frontend/device/kobo/device.lua
- plugins/kosync.koplugin/main.lua
Entering suspend with the Wi-Fi chip powered on famously makes a lot of NTX boards implode. To deal with this, we've been killing Wi-Fi before suspend since pretty much ever (in `Generic:onPowerEvent`).
KOSync, on the other hand, will request connectivity in its suspend handler to push reading progress.
The issue is that `Generic:onPowerEvent` kills Wi-Fi *before* sending the `Suspend` event (via `Powerd:beforeSuspend` into `Device:_beforeSuspend`), so that funky edge-case will happily implode kernels ;).
So, fix it on KOSync's side first by explicitly killing Wi-Fi (on platforms where we control it explicitly) in the suspend handler, because even on non-kablooey kernels, it may lead to bad power management issues.
And also fix it on Kobo's side (since most of the affected boards are from …
> KOSync/Kobo: Explicitly kill Wi-Fi on suspend

- frontend/device/kobo/device.lua
The only codepath that sets `pending_connection` to `true` in `NetworkManager` calls `turnOnWifi` right after, so we can't really ever see `pending_connection` w/o `isWifiOn` being also `true` ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12629)
> Kobo: Minor simplification after #12616

- frontend/ui/widget/filechooser.lua
- frontend/ui/widget/focusmanager.lua
- frontend/ui/widget/menu.lua
- plugins/coverbrowser.koplugin/covermenu.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
(1) Focus on the last opened book when closing Reader. Closes https://github.com/koreader/koreader/issues/12574.
(2) Focus on the folder when going up to the parent folder.
(3) Focus on a target item (like "Last bookmark" in bookmark list, or "Current page" in fulltext search results list etc.)
Since the Menu widget is affected, the focus may appear in some other (unexpected) places. If it is the case and annoying, the corresponding module to be fixed, after testing in the field.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12583)
> Menu widget: draw focus on focused item

- frontend/apps/reader/modules/readerfont.lua
New fonts were not rendering in their own font because the font names were modified directly in the `face_list` table, which is needed to style the HTML text. 
This ensures that only the written strings are changed with the 'NEW' modifier.
@poire-z please review. Thank you.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12646)
> ReaderFont test: Error correction -- new fonts were not rendering in own font

- tools/wbuilder.lua
Use `setupkoenv` to setup LUA paths and ensure `ffi.loadlib` is loaded.
Close #12664.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12665)
> wbuilder: fix environment

- frontend/ui/widget/focusmanager.lua
- frontend/ui/widget/menu.lua
- plugins/coverbrowser.koplugin/covermenu.lua
Tweak `mergeTitleBarIntoLayout` to keep the current selection (adjusted for the added rows) instead of resetting the focus.
It only actually called `moveFocusTo` on `hasDPad` devices, which explains why this was missed during testing.
Fix https://github.com/koreader/koreader/pull/12583#issuecomment-2423554770
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12657)
> Menu: Fix fallout from #12583 on hasDPad devices

- frontend/ui/widget/keyvaluepage.lua
- plugins/statistics.koplugin/calendarview.lua
Don't show initial focus in KVP & CalendarView
Fix https://github.com/koreader/koreader/pull/12583#issuecomment-2427403108
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12667)
> Misc: Some more FocusManager fallout

- frontend/pluginloader.lua
Keep translations around on deprecation.
Here's the whole picture, I will remove specific plugins from here and repurpose #12619 and #12620
Any better name or place to put those strings?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12636)
> plugin messages

- frontend/dispatcher.lua
- frontend/util.lua
- plugins/profiles.koplugin/main.lua
New "on wake-up", conditional "on book opening".
Ask to execute a profile (in auto-exec only), show notification on executing.
On book opening:
Closes https://github.com/koreader/koreader/issues/12491.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12651)
> Profiles: more auto-exec triggers

- frontend/device/devicelistener.lua
- frontend/device/generic/device.lua
It's relatively easy to miss-click the buttons, especially on devices with questionable touch panels...
And while doing so is perfectly fine, ~~you miss the InfoMessage telling you that the update will be applied on restart, which is potentially confusing.~~.
(Turns out it's only *mildly* confusing, I was just confused about my own half-remembered confusion ;p).
Re: #12674
(Rebase me)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12676)
> OTA: Make the final ConfirmBox undismissable

- Makefile
Cf. https://savannah.gnu.org/bugs/?func=detailitem&item_id=41273
This would result in release archives not including some data files (e.g. `ca-bundle.crt` and `KoboUSBMS.tar.gz`).
Close #12724.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12725)
> make: work around make < 4.4 wildcard bug

- frontend/document/koptinterface.lua
Previously unused by `libk2pdfopt`, the `ocr_type` argument passed to `k2pdfopt_tocr_single_word` and forwarded to `ocrtess_ocrwords_from_bmp8` now has a big impact for some languages (e.g. Arabic).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12726)
> kopt: fix OCR segmentation mode

- .circleci/config.yml
Can't look at `/sys/fs/cgroup/cpu/cpu.shares` anymore…
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12751)
> ci/circle: manually cap build jobs

- plugins/terminal.koplugin/main.lua
This pull request makes a minor adjustment to the terminal emulator's minimum font size in KOReader. It aims to prevent content from being truncated, allowing users to view more information on Kindle. 
Thank you for considering this update!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12752)
> Adjust Minimum Font Size in Terminal Emulator

- frontend/apps/reader/modules/readerhighlight.lua
- plugins/terminal.koplugin/main.lua
Closes #12754; as discussed there.
Other icons or text labels would also be okay, this is only to prevent user confusion of the easily mixed up Details/Delete buttons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12758)
>  ReaderHighlight: Highlight menu, change 'Delete' to Trash can icon 

- plugins/qrclipboard.koplugin/main.lua
This pull request introduces a new method to add the QR code generation option to the highlight dialogue, to allow users to generate a QR code from selected text. No longer do users need to make a selection, copy it and then go through menus with multiple taps or key presses to generate a QR code.
* [`plugins/qrclipboard.koplugin/main.lua`](diffhunk://#diff-be908c8cc0d929ec81f56dea5b9e12d85175edbae3541475de3071368c4a0d81R21-R41): Introduced `addToHighlightDialog` method to add the "Generate QR code" option to the highlight dialogue. This method copies selected text to the clipboard (automatically) and then displays the QR code.
</p>
* fix #11909
- - - …
> add faster option to export text selections via qr codes

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/ui/translator.lua
(After the release)
(1) Adjustable highlight line height. Discussed in https://github.com/koreader/koreader/issues/10416 and https://github.com/koreader/koreader/issues/11581.
(2) "Note" button in the Note window (on tapping a highlight with note). Closes https://github.com/koreader/koreader/issues/12234.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12721)
> Highlight: line height

- .github/workflows/build.yml
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/pkg-config
Target /opt/homebrew/bin/pkg-config
is a symlink belonging to pkg-config@0.29.2. You can unlink it:
brew unlink pkg-config@0.29.2
To force the link and overwrite all conflicting files:
brew link --overwrite pkgconf
To list all files that would be deleted:
brew link --overwrite pkgconf --dry-run
Possible conflicting files are:
/opt/homebrew/bin/pkg-config -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/bin/pkg-config
/opt/homebrew/share/aclocal/pkg.m4 -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/share/aclocal/pkg.m4
/opt/homebrew/share/man/man1/pkg-config.1 -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/share/man/man1/pkg-conf …
```
> ci/macos: fix possible issue during brew install

- spec/unit/readhistory_spec.lua
For example on my machine:
| test duration (ms) |  master  |             PR |
| :-                 | -:       | -:             |
| regular run        |  2645.94 | 106.83 (÷24.8) |
| coverage run       | 26133.27 | 641.59 (÷40.7) |
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12785)
> tests: speedup readhistory reduce test

- frontend/util.lua
- plugins/terminal.koplugin/main.lua
- plugins/timesync.koplugin/main.lua
Closes #12760 
Credits go to @benoit-pierre (Thank you!)
@NiLuJe 
Can you please give it a quick glance to make sure Kobo won't suffer from this?
I don't have any other devices to test, so please let me know if there are issues:
- newer Kindles?
- emulator
- Android
- Pocketbook
- Cervantes
- else?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12765)
> [Kindle NT] fix terminal and timesync

- frontend/dispatcher.lua
- frontend/ui/data/onetime_migration.lua
- frontend/ui/elements/screensaver_menu.lua
* Added a new local function `getUntilTapOrKeyPressText` to return appropriate text based on whether the device is a touch device or not.
* Refactored the return statement to use a local `menu_items` table.
* Conditionally added the `Until 'exit sleep screen' gesture` menu item only to touch devices.
issue was first documented here #12744
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12747)
> [screensaver menu] remove gesture based option from NT devices

- frontend/apps/cloudstorage/webdavapi.lua
Tested and confirmed to work even when the subfolder name appears multiple times in the current folder's full path.
Closes https://github.com/koreader/koreader/issues/12783
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12788)
> webdav: show folders with same name as current folder

- frontend/ui/screensaver.lua
I have enjoyed (possibly over) customizing my sleep screen message. However I kept getting confused between the book completed percentage and the battery percentage. At first I just tried adding the battery symbol, but when looking into it, it was simpler to just reference the function that returns the dynamic battery icon.
I added the battery symbol to the prompt as %B:
And examples of what it looks like (along with some other fun symbols I found along the way):
This was tested on a Kobo Clara 2E, but since it uses the same code that niluje wrote in `frontend/ui/widget/touchmenu.lua` for the touch menu icon, my guess is it will be device agnostic.
- - - …
> screensaver: Add dynamic battery symbol to sleep screen message

- plugins/autostandby.koplugin/main.lua
This PR attempts to fix #12814.
Following [this suggestion](https://github.com/koreader/koreader/discussions/12791#discussioncomment-11381336) and [that one](https://github.com/koreader/koreader/issues/12814#issuecomment-2506749839), I tested the fix vs. standard plugin settings and the plugin appears to work as expected, even with a never-opened-before complex EPUB. To be clear, this is not an attempt to fix the other issues reported for this plugin, c.f. #9493.
Based off of [this suggestion](https://github.com/koreader/koreader/discussions/12791#discussioncomment-11381336), schedule the next standby when the plugin is initialized, either:
1. When KOReader starts
- To prevent the device from instantly going into standby
2. During a view transition
- The standby scheduled by the input …
> Schedule next standby on AutoStandby plugin init

- plugins/autosuspend.koplugin/main.lua
This allows to set days to zero. As a security fall back setting days and hours both to zero will yield 5m autosuspend time. (to avoid shutdown loops).
fixes https://github.com/koreader/koreader/issues/12831
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12835)
> [AutoSuspend] Make day selector less restrictive

- frontend/document/credocument.lua
Reseting the default font each time we refresh metadata (ie. when refreshing a cover in History) could cause the rendering hash of the currently opened document to be messed up, with strange effects.
Hoping setting one in engineInit() is enough to avoid the crashes the removed comment talks about.
See https://github.com/koreader/koreader/pull/8613#issuecomment-2427326832 for the issue,
and https://github.com/koreader/koreader/pull/8613#issuecomment-2431194646 for the possible explanation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12846)
> CreDocument: tweak when the default font is set

- frontend/apps/filemanager/filemanager.lua
- plugins/coverbrowser.koplugin/covermenu.lua
- plugins/coverbrowser.koplugin/main.lua
The Plus dialog doesn't need an api, just fetch the button from the CoverBrowser.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12857)
> FileManager: Plus dialog button from CoverBrowser

- doc/Building.md
Add bash to the list of required Homebrew packages (macOS ship version 3, we need at least 4).
Closes #12868.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12886)
> doc: update macOS build instructions

- frontend/ui/widget/screenshoter.lua
Closes #12695.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12887)
> Screenshoter: add filename and page number

- plugins/profiles.koplugin/main.lua
New auto-exec condition "on book opening": for new books only.
Also fixes https://github.com/koreader/koreader/issues/12865.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12884)
> Profiles: auto-exec "on book opening" - new books

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/htmlboxwidget.lua
- frontend/ui/widget/scrollhtmlwidget.lua
Pass the directory that contains the dictionary's ifo file to Mupdf.openDocumentFromText to allow MuPDF to display images referenced by HTML dictionaries.
Depends on: https://github.com/koreader/koreader-base/pull/2002
Fixes: https://github.com/koreader/koreader/issues/12628
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12877)
> Dictionary: fix missing images

- doc/Building.md
One, the brew prefix differs on aarch64 hosts, two, this was completely nuts: the homebrew install process already handles that via an `eval $(brew shellenv)` in the shell profile.
Fix #12868
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12873)
> Update macOS PATH shenanigans

- frontend/apps/reader/modules/readersearch.lua
- plugins/hotkeys.koplugin/main.lua
This pull request introduces a new "type-to-search" feature to the `plugins/hotkeys.koplugin` module.
* Modified `HotKeys:overrideConflictingKeyEvents()` to handle the new type-to-search feature by adjusting key events and removing conflicting shortcuts.
* Reverts a previous addition of a now unnecessary return statement from the `ReaderSearch:onShowFulltextSearchInput(search_string)` function in `frontend/apps/reader/modules/readersearch.lua`.
</p>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12860)
> [HotKeys] adds 'type to search' setting to hasKeyboard devices

- frontend/dispatcher.lua
* [`frontend/dispatcher.lua`](diffhunk://#diff-73231974e9f228d37b8cd3abe7abf22d9d75e4d04e378c5c6de575e0fc8396bfL872-R872): Modified the `Dispatcher:_addItem` function to check if the device is a touch device before setting the option text for gesture distance.
<p align="center"> before/after  </p>
</p>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12889)
> [Dispatcher] remove gesture mentions from NT

- frontend/ui/uimanager.lua
- frontend/ui/widget/iconbutton.lua
- plugins/coverbrowser.koplugin/main.lua
`updateItemTable()` can get args.
`clearRenderStack()` is not used anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12895)
> CoverBrowser: minor fix and remove unused

- plugins/vocabbuilder.koplugin/db.lua
- plugins/vocabbuilder.koplugin/main.lua
closes #12506.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12885)
> VocabBuilder.koplugin: support option to overwrite word with new context

- frontend/pluginloader.lua
- frontend/provider.lua
- plugins/exporter.koplugin/main.lua
- setupkoenv.lua
- spec/unit/exporter_plugin_main_spec.lua
- spec/unit/provider_spec.lua
Some background in #7279
- Implements a `Provider` singleton that plugins can use to extend supported features
Thirdparty plugin developers can use:
```lua
local Provider = require("provider")
Provider:register("exporter", "my-service", my-implementation)
```
where `my-implementation` is a table that implements the interface for an exporter target.
- Makes the exporter plugin compatible with thirdparty providers
- Splits plugin loading into two steps: **discovery** and **load**. That way we get a list of all candidate plugins to load for the different paths and we sort those starting with "provider" to be load before the rest of them.
- - - …
> add provider module

- frontend/document/koptinterface.lua
Missed one line in #12917.
Fixes #12916 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12938)
> vocabbuilder.koplugin: fix selecting context bug

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/ui/widget/iconbutton.lua
- plugins/coverbrowser.koplugin/bookinfomanager.lua
- plugins/coverbrowser.koplugin/main.lua
When available, use CoverBrowser sql base to get (already customized) doc props.
Should be faster than `DocSettings:open()`.
(Also revert my erroneous change to IconButton)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12936)
> CoverBrowser BookInfoManager: lite getDocProps()

- frontend/apps/reader/modules/readersearch.lua
- frontend/ui/widget/menu.lua
Closes https://github.com/koreader/koreader/issues/12937.
Also adds "All results" button, see (1) in https://github.com/koreader/koreader/issues/12900.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12940)
> ReaderSearch results: search string always in bold

- frontend/ui/widget/pathchooser.lua
Regarding https://github.com/koreader/koreader/issues/12941.
Re-extraction of covers is triggered in the "choose file" dilalog, i.e. PathChooser.
I cannot reproduce on Kindle, assume the reason of the issue is different styles of the title bar in FM/Collections and PathChooser (small icons). Assume, on some screen resolutions (because of rounding in `scaleBySize`) this may cause different titlebar height and hence different cover thumbnail sizes:
https://github.com/koreader/koreader/blob/33af38096200033df618e4dc176daaf012050488/frontend/ui/widget/menu.lua#L707-L708
In any case, let the title bar be the same in all windows supported by CoverBrowser (FM, Coll, Hist, PathChooser), hoping it fixes the issue.
- - - …
> PathChooser: title bar fm_style

- frontend/ui/wikipedia.lua
For some time, we were no longer getting our added solid black symbols at the start of headings when "Save as EPUB".
Wikipedia has changed their HTML output from:
`<h2> <span class="mw-headline" id="stuff">Stuff</span></h2>`
to:
`<h2 id="stuff">Stuff</h2>`.
So, handle that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12961)
> Wikipedia EPUBs: fix missing symbols at start of headings

- plugins/newsdownloader.koplugin/feed_config.lua
- plugins/newsdownloader.koplugin/feed_view.lua
- plugins/newsdownloader.koplugin/main.lua
It's a saner default. Much of the time it won't just work but it'll work *significantly better* than `download_full_article=true`.
Additionally it should reduce the chance of being seen as abuse, cf. <https://github.com/koreader/koreader/issues/12953#issuecomment-2565973079>.
Also see #3172.
Since both the UI and the default config include the value, impact may be surprisingly limited.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12965)
> [plugin] NewsDownloader: switch default to download_full_article=false

- frontend/apps/reader/modules/readerannotation.lua
Closes https://github.com/koreader/koreader/issues/12957.
(1) `datetime_updated` is not exposed to UI.
(2) `datetime_updated` is not exported.
(3) There is no sorting by date modified.
(4) "Latest bookmark" still means the last **created** bookmark.
(5) @noembryo I do not add `datetime_updated` to new annotations.
Old annotations don't have this field, in any case you need to do something like
```Lua
local datetime = item.datetime_updated or item.datetime
```
so no difference whether it is `nil` or equals to `datetime`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12963)
> Annotations: add datetime_updated property

- frontend/document/koptinterface.lua
As pointed out at https://github.com/koreader/koreader/issues/12916#issuecomment-2564755827.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12975)
> Vocabbuiler.koplugin: Fix pdf context extraction with hyphenation

- plugins/newsdownloader.koplugin/main.lua
Fixes #9358.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12978)
> [plugin] NewsDownloader: fail gracefully when date can't be parsed

- frontend/socketutil.lua
Closes #10186, also see <https://github.com/koreader/koreader/issues/12953#issuecomment-2565973079>
Results in:
```
KOReader/2024.11-112 (Emulator; Linux; x64) LuaSocket/3.1.0
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12977)
> socketutil: remove URL from user agent, add device info

- plugins/newsdownloader.koplugin/main.lua
Noticed in https://github.com/koreader/koreader/pull/12969#discussion_r1900122593
This merely makes it a touch friendlier to future changes. Fixing it up as "proper" XHTML is likely to do more harm than good, since the content will typically be regular HTML encapsulated in `<![CDATA[`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12976)
> [plugin] NewsDownloader: reduce HTML idiosyncracies

- frontend/socketutil.lua
Device:info() is multiline on Android, see https://github.com/koreader/koreader/pull/12977#issuecomment-2568355984
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12992)
> socketutil: use Device.model directly

- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/inputtext.lua
- frontend/ui/widget/virtualkeyboard.lua
InputText:isKeyboardVisible could return nil when the keyboard was
already gone, which cleared the instance variable, meaning we end up
with the static class default instead, which is true...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12994)
> InputDialog: Make sure keyboard_visible is never nil'ed

- frontend/ui/widget/multiinputdialog.lua
* [`frontend/ui/widget/multiinputdialog.lua`](diffhunk://#diff-ec760af17116d6a9eb1ebd6cfcb2a3dd5ecf8d242af8cb2b061cdec5dbac583dR113-R119): Added initialization for the `keyboard_visible` property in the `MultiInputDialog:init()` function to determine if the keyboard should be visible based on device and reader settings.
* [`frontend/ui/widget/multiinputdialog.lua`](diffhunk://#diff-ec760af17116d6a9eb1ebd6cfcb2a3dd5ecf8d242af8cb2b061cdec5dbac583dR218-R222): Adjusted the height of the `CenterContainer` to account for the keyboard height only if the keyboard is visible.
* Removed pesky whitespaces
before/after
</p> 
</p>
* fix #12914
- - - …
> [MultiInputDialog] vertically centre multi input dialogue

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/readcollection.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/main.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
(1) Option to show/hide collection mark.
(Now I have **all** my books in one flat collection. "Collections search" allows to build a collection for, say, a certain author quickly.)
(2) Option to have fixed font size in List display mode, taken from https://github.com/koreader/koreader/issues/9094#issuecomment-2040834603.
(3) Radio buttons in the "Series" submenu. To avoid confusion comparing to adjacent "Progress" and "Display hints" menues.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12954)
> File list: new display options

- frontend/apps/filemanager/filemanagercollection.lua
"Filter by ..." buttons in the popup menu:
On pressing, say, "Filter by language" we get the list of unique "language" props in the collection, showing number of books for each value:
On pressing an item we get the list of books with the prop matching.
Filtered by one prop:
We can apply another filter to the filtered list. Filtered by two props:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12981)
> Collections: filter by metadata

- plugins/newsdownloader.koplugin/main.lua
Similar to the logic for Atom in #12959.
Reported in https://github.com/koreader/koreader/issues/12953#issuecomment-2580784621
Sample feed https://www.engadget.com/rss.xml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13032)
> [plugin] NewsDownloader: use first feed description if it's a table in RSS

- frontend/ui/wikipedia.lua
- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
This is the underlying reason that The Verge + download full article fails, see <https://github.com/koreader/koreader/issues/12953#issuecomment-2580784621>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13034)
> processImg: skip data URI

- frontend/apps/reader/modules/readerannotation.lua
Compare only datetime and start/end positions, it's enough.
Closes https://github.com/koreader/koreader/issues/13030.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13037)
> Annotations: fix matchFunc

- frontend/ui/screensaver.lua
- frontend/ui/widget/infomessage.lua
* Introduced the `force_one_line` property to the `InfoMessage` class to attempt to show text in a single line.
* Modified the `InfoMessage:init()` function to calculate the maximum height of the widget based on the `force_one_line` property, ensuring that the text fits within the specified constraints.
* Added the `force_one_line` property to the `Screensaver:show()` function to ensure the sleep screen message is displayed in a single line.
before/after
</p> 
</p>
fix #12109
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13026)
> Reduce sleep screen message's font size to fit one line

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readerwikipedia.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/footnotewidget.lua
- frontend/ui/widget/htmlboxwidget.lua
- frontend/ui/widget/scrollhtmlwidget.lua
- frontend/ui/widget/scrolltextwidget.lua
- frontend/ui/widget/textboxwidget.lua
When selecting text in the dictionary (including Wikipedia) or the pop-up footnotes highlight the selected text using an inverting rectangle. After closing the opened dictionary remove the highlight after a short delay just like in the reader.
Depends on https://github.com/koreader/koreader-base/pull/2013
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12948)
> Dictionary, footnotes: highlight the selected text

- frontend/ui/wikipedia.lua
- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
According to epubcheck.
```
Mimetype file should only contain the string "application/epub+zip" and should not be compressed.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13057)
> EPUB: mimetype file should not be compressed

- plugins/gestures.koplugin/main.lua
- plugins/hotkeys.koplugin/main.lua
See #13009 for details.
LuaSettings attempts to read a backup if the main doesn't work. If that doesn't work it returns an empty `data` table. But gestures expects there to be defaults inside.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13054)
> [plugin] Gestures, Hotkeys: attempt to work around corrupted gestures file

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
Other than the slightly different InfoMessage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13063)
> EPUB: unify include_images logic

- plugins/kosync.koplugin/main.lua
This should fix #13076 (if desired).
As said in the issue, one disadvantage is that existing (in my opinion incorrect) user names would become invalid.
(Another one is that since validate() is also used for passwords, it won't be possible to have whitespaces in passwords.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13077)
> kosync: Make sure there are no leading or trailing whitespaces.

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagerutil.lua
- frontend/apps/reader/readerui.lua
- frontend/ui/widget/booklist.lua
- frontend/ui/widget/bookstatuswidget.lua
- frontend/ui/widget/filechooser.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/pathchooser.lua
- plugins/calibre.koplugin/search.lua
- plugins/calibre.koplugin/wireless.lua
- plugins/coverbrowser.koplugin/covermenu.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/main.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
Less calls of `DocSettings:open()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13018)
> CoverBrowser info_cache: move to core

- frontend/ui/widget/screenshoter.lua
* [`frontend/ui/widget/screenshoter.lua`](diffhunk://#diff-ba47f4be979e53cfa280f177af83f1d52322ea41885213aa708392211b996a03L102-R103): Changed the saved settings from `image_file ` and `screensaver_image` to `document_cover` and `screensaver_document_cover` when setting a screenshot as a wallpaper.
this one slipped through the cracks when we removed `image_file` back in #11549
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13108)
> [screenshoter] Fix bug in ‘set as wallpaper’ setting.

- frontend/apps/filemanager/filemanagerutil.lua
- frontend/ui/elements/screensaver_menu.lua
- frontend/ui/screensaver.lua
* [`frontend/ui/elements/screensaver_menu.lua`](diffhunk://#diff-3982e81823bb1df13fdf234b0087be5bef2fb5f744be693b20fce2d8f833692cR162-R175): Added a new menu item to toggle the display of images in alphabetical order.
* [`frontend/ui/screensaver.lua`](diffhunk://#diff-ca0df032a2d2a54f0d1c18b7372a594335ef10c6fb9ecd1042b2a710cdc1f327R88-R101): Modified the `_getRandomImage` function to support the new alphabetical order option by sorting files and cycling through them. Wasn't sure whether to create a brand new one or just adapt this one, alas the latter was chosen. 
</p> 
* fix #11179
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13094)
> [screensaver] Add option to cycle through folder images

- frontend/persist.lua
- spec/unit/persist_spec.lua
I found the API a bit confusing.
Related to #13061.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13122)
> Persist: add support for zstd serialization/deserialization in memory

- plugins/bookshortcuts.koplugin/main.lua
For example, viewing crash.log in TextViewer can be assigned to a gesture or a profile.
Also menu prettify.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13106)
> BookShortcuts: open file with associated provider

- .github/workflows/build.yml
Ensure the cache does not get removed after being stale when not bumping base for more than 7 days.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13141)
> ci/macos: tweak ccache handling

- frontend/dispatcher.lua
- frontend/ui/widget/sortwidget.lua
- frontend/ui/widget/touchmenu.lua
- plugins/gestures.koplugin/main.lua
- plugins/profiles.koplugin/main.lua
**(1)** Actions menu: ask to remove several actions when choosing Default, Pass through or Nothing. Closes https://github.com/koreader/koreader/issues/10534.
**(2)** "Arrange actions" is available iff number of actions is greater than 1.
Actions are always ordered, in the order of adding until manual sorting, hence no checkbox in the menu.
**(3)** Remove "QuickMenu" header for gestures. Closes https://github.com/koreader/koreader/issues/12827.
**(4)** QuickMenu separators can be set in the Sorting widget (via SortWidget checkboxes). Closes https://github.com/koreader/koreader/issues/13056.
**(5)** Other minor fixes in actions menu appearance.
- - - …
> Gesture manager and Profiles: improve Dispatcher actions menu

- frontend/apps/reader/modules/readerstatus.lua
- frontend/ui/widget/bookstatuswidget.lua
"Book status and return to file browser".
Closes https://github.com/koreader/koreader/issues/13142.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13144)
> ReaderStatus: fix End of Document action

- frontend/apps/reader/modules/readerhighlight.lua
The changes focus on improving the logic for handling highlight interactions and enhancing the accuracy of text selection.
* **Highlight Interaction Logic:**
* Simplified the conditional checks and streamlined the logic for starting and stopping highlights.
* Added a return statement to handle cases where there is no current indicator position early in the function.
* **Text Selection Accuracy:**
* Introduced a heuristic approach to determine if a word is hyphenated due to line breaks, improving the accuracy of text selection.
* Created a helper function `updatePositions` to centralize the logic for updating hold and indicator positions.
**before** 
</p>
**after**
correct detection under extreme circumstances 
</p>
correct detection in two column mode …
> [ReaderHighlight] NT: Improve selection of hyphenated words

- frontend/ui/widget/booklist.lua
Old books may have nil or empty string status. Closes https://github.com/koreader/koreader/issues/13156.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13157)
> BookList: fix book status

- frontend/apps/reader/modules/readerview.lua
- frontend/dispatcher.lua
(1) Fix "Invert page turn taps and swipes" per document setting (it was impossible to set `false`).
(2) Add action to set the inverted direction on/off (in addition to toggle). See https://github.com/koreader/koreader/issues/13010.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13155)
> "Invert page turn taps and swipes" fix

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
May be relevant to #9363. In any case one of the most typical kind of failure wasn't treated properly, so a 404 would mess up everything instead of popping up a dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13165)
> NewsDownloader: deal with 404 and other error statuses better

- frontend/cache.lua
- frontend/cachesqlite.lua
- spec/unit/cachesqlite_spec.lua
Persist is intended for larger objects, which works best for things like cached tiles with some metadata.
For many small to medium entries that you nevertheless don't necessarily want to keep around in memory, that seems a bit inefficient.
SQLite then, is effectively a way of minimizing the amount of writes in this scenario.
Relates to #13061. Depends on #13122.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13131)
> Add CacheSQLite

- frontend/ui/widget/screenshoter.lua
* [`frontend/ui/widget/screenshoter.lua`](diffhunk://#diff-ba47f4be979e53cfa280f177af83f1d52322ea41885213aa708392211b996a03L99-R106): Modified the condition to display the "Set as wallpaper" option based on the device type and special offers status.
This only just crossed my mind, we don't show anything on sleep screen if a device has special offers (#13006) yet, this is still out there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13110)
> [screenshoter] remove 'set as wallpaper' from devices with special offers

- frontend/apps/reader/modules/readerannotation.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/readerui.lua
- frontend/ui/widget/booklist.lua
(1) Annotations: don't create annotation `datetime_modified` if it is equal to `datetime`.
(2) ReaderUI: set correct book status when opening old books
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13185)
> Couple of minor fixes

- frontend/apps/reader/modules/readerfooter.lua
* Added a `keep_menu_open` property to keep the menu open when arranging one's items. why was this not a thing?
* Introduced an `enabled_func` to ensure the "Arrange items in status bar" option is only enabled when there is more than one enabled item. (on par with dispatcher's)
</p>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13168)
> [ReaderFooter] keep menu open after arranging items in status bar

- frontend/ui/widget/sortwidget.lua
* Added a new function `onCloseNT` to handle the `CloseNT` key event, which checks if any items are marked and calls `onCancel` if so, or `onClose` otherwise.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13189)
> [SortWidget] add cancelOrClose method

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
Works around the issue in <https://github.com/koreader/koreader/issues/13173#issuecomment-2628027654>.
---
It's not a proper solution, since traditional HTML like the following would still cause issues, but it catches the low-hanging fruit of self-closing tags. Other than `<hr>` with its gray color I'm not sure if any of the other elements matter much in practice, but you might sometimes see some slightly curious indentation due to nesting.
```html
<p>Paragraph one
<p>Paragraph two
```
The simplest solution would be to revert to plain HTML files, but EPUB does offer some advantages. (And I don't know if I want to put in the work required for that. :-)
A better solution might be to leverage crengine or MuPDF's HTML parsing, to output normalized HTML. Or perhaps to put in the mimetype …
> NewsDownloader: process HTML with cre.getBalancedHTML() to ensure self-closing tags like <hr> are closed like <hr/>

- frontend/apps/reader/modules/readerannotation.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerview.lua
Update next annotations indexes in cached page boxes when adding or removing an annotation.
Closes https://github.com/koreader/koreader/issues/13198.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13200)
> Highlights: fix page boxes cache

- plugins/hotkeys.koplugin/main.lua
* Renamed `FFIUtil` to `ffiUtil` to maintain a consistent naming convention across the code base.
* Refactored the hotkeys list generation by defining a base keys table and iterating over it to create the hotkeys list dynamically. This change simplifies the code and makes it more maintainable.
* Added `no_refresh_on_check` property to menu items to prevent unnecessary refreshes when checking the items.
* Updated the `callback` functions in the hotkeys menu to include a `touchmenu_instance` parameter and handle the removal of actions more gracefully. This ensures the menu items are updated correctly after changes.
there is a problem with the callbacks introduced (in the gestures plugin) in #13078, I believe the solution is doing exactly what I am doing here (the if/else bit), but await …
> [Hotkeys] refactor hotkey list and update callbacks

- frontend/ui/elements/common_settings_menu_table.lua
#12293
* [`frontend/ui/elements/common_settings_menu_table.lua`](diffhunk://#diff-cb989447e34bc5b8a0e9f2f4c10ec368720cb0b7e6d99181a9c935371d057d60R753): Added a conditional check to include the `screenshot` setting only if the device meets certain criteria.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13221)
> [Common settings] remove screenshot setting from unsupported devices

- frontend/dispatcher.lua
- frontend/ui/data/onetime_migration.lua
- plugins/profiles.koplugin/main.lua
- plugins/statistics.koplugin/main.lua
(1) Remove unused kopt actions that are not shown in the bottom menu.
(2) Separate GoTo and Back actions for Reader and FileManager.
(3) Statistics:
-add "Time range" action
-group all actions together in the General section, except "Book statistics" in Reader section.
Closes https://github.com/koreader/koreader/issues/12690.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13167)
> Dispatcher: action list fixes

- frontend/device/android/device.lua
Added a new entry for OSS-Dict https://github.com/farfromrefug/OSS-Dict Not sure about the last value for the dict. Cant find where you use it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13224)
> fix: Added OSS-Dict support

- plugins/calibre.koplugin/main.lua
closes #13193
Using an InfoMessage instead of a notification because another infomessage will follow with success/error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13237)
> calibre.koplugin: show message when attempting to connect via dispatcher

- frontend/apps/reader/readerui.lua
Updating of `percent_finished` for `rolling` is triggered by the `CloseDocument` event, so refresh the cache after it.
Closes https://github.com/koreader/koreader/issues/13244.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13245)
> ReaderUI: fix BookList cache

- plugins/hotkeys.koplugin/main.lua
* Removed [now] unnecessary conditions when removing actions for hotkeys in the `HotKeys:genMenu` function. No longer needed as of #13227
* Added code to reset key events for the overlooked `font` UI component in the `HotKeys:overrideConflictingKeyEvents` function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13257)
> [Hotkeys] override self.ui.fonts key_events

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
`<script src="etc"></script>` is turned into `<script/>`, which can cause far too much to be stripped.
While that could be dealt with a bit better, for example by first stripping self-closing and then regular, it feels hacky to do so.
See <https://github.com/koreader/koreader/pull/13188#issuecomment-2660362639>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13260)
> [plugin] NewsDownloader: don't try to strip <script> tags

- doc/Building.md
- add `findutils`: we need the real deal (for `-printf`)
- add `nasm`: for building libjpeg-turbo' SIMD support
- drop `ninja-is-really-ninja` in favor of `ninja-build`: the former now conflicts with `samurai` (required by `meson`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13319)
> doc: fix / update build instructions for Alpine Linux

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerconverter.lua
- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagermenu.lua
- plugins/coverbrowser.koplugin/main.lua
Use CoverBrowser (following file manager display mode), standard file dialog on long-pressing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13298)
> FileSearcher: consistent results window

- frontend/ui/widget/doublespinwidget.lua
- frontend/ui/widget/numberpickerwidget.lua
- frontend/ui/widget/spinwidget.lua
This pull request includes changes to the `DoubleSpinWidget` and `SpinWidget` classes. The modifications enhance the functionality of these widgets by adding new key events to support value changing using the device's page-turn buttons.
* Added key events to support adjusting widget values. 
* Replaced local variables with instance variables for `left_widget` and `right_widget`. 
* Introduced the `onDoubleSpinButtonPressed` method to handle page-turn button presses for adjusting widget values.
* Added key events to support  adjusting widget values.
* Replaced local variables with instance variables for `value_widget`.
* Introduced the `onSpinButtonPressed` method to handle page-turn button presses for adjusting widget values. 
* Removed number of arguments needed to pass to `changeValue` …
> [DoubleSpinWidget, SpinWidget] change values with page-turn buttons

- frontend/ui/data/keyboardlayouts/pl_keyboard.lua
... in order to keep it consistent with other Polish characters. Looks like a copyedit bug to me.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13347)
> PL keyboard layout: move "ó" and "Ó" to east on keypopup

- frontend/apps/filemanager/filemanagercollection.lua
- frontend/readcollection.lua
Updates a collection when new books are added to a connected folder.
A collection is updated:
-on program start;
-on showing the collection;
-on connecting a folder;
-on including subfolders of a connected folder.
Collections with connected folders are marked with a "folder" icon.
Long-press a collection to connect folders.
List of connected folders.
Folders with connected subfolders are marked with a "folder" icon.
Long-press a folder to disconnect it or to include/exclude its subfolders.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13336)
> Collections: connect folders

- frontend/apps/reader/modules/readerhighlight.lua
* `frontend/apps/reader/modules/readerhighlight.lua`: Modified the logic to account for both the status bar and the alternative status bar, ensuring the highlight indicator does not overlap with these elements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13348)
> [ReaderHighlight] NT: account for status and alt-status bars in text selection

- frontend/ui/widget/infomessage.lua
* `frontend/ui/widget/infomessage.lua`: Added logic to store the original font and size when `force_one_line` is enabled, preventing excessive font size reduction.
* `frontend/ui/widget/infomessage.lua`: Implemented a condition to stop reducing the font size by more than 30 percent and reset to the original font and size if necessary.
related to #13107
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13337)
> [InfoMessage] stop force_one_line if font is too small

- frontend/ui/widget/imageviewer.lua
- plugins/opds.koplugin/opdsbrowser.lua
- plugins/opds.koplugin/opdspse.lua
**_Still pretty new to Lua & KOReader, so might’ve missed something. Open to any suggestions..._**
- Added [OPDS-PSE v1.2](https://github.com/anansi-project/opds-pse/blob/master/v1.2.md) [lastRead] support in the download dialog whenever pse:lastRead is present.
- Since the Page Stream option now has three buttons, I added a sub-dialog—clicking "Page Stream" now opens another dialog with all three options.
- Clicking "Resume From Page N" directs the ImageViewer to open that page image.
- Fix for serverFileName issues: If the endpoint doesn’t return proper headers on a HEAD request, the filename was set as empty, causing an error saying "Is a directory". Now, it falls back to the original/default filename, and if the filename is modified, it correctly retains that change. Relates to …
> Opds-pse v1.2 [LastRead]

- frontend/apps/reader/modules/readerhighlight.lua
Limitations comparing to cre documents:
-doesn't move by chars
-doesn't extend to next/previous page (works with multi-page highlights' end and start separately)
Closes https://github.com/koreader/koreader/issues/13058.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13364)
> Highlights: edit boundaries in pdf

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/ui/widget/keyvaluepage.lua
Closes https://github.com/koreader/koreader/issues/12640.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13377)
> KeyValuePage: lanscape and portrait items per page

- frontend/apps/reader/modules/readerannotation.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/dispatcher.lua
Exports annotations to a lua file in the assigned folder (default - book metadata folder):
-automatically on book closing, or
-manually from the Bookmark list, or with a gesture/profile.
Imports annotations on book opening.
Export filename is `<book-filename>.annotations.lua`.
The file should be moved to other device manually or by a syncing program.
Syncing logic:
Checks for correspondence between old and new annotations (by highlight start and end positions).
-if there is no old annotation, the new one is added;
-if new annotation is newer than the old one, the old one is replaced;
-if there is no new annotation corresponding to the old one, and the export datetime is newer than the old annotation datetime, the old one is removed.
- - - …
> Annotations: sync between devices

- plugins/profiles.koplugin/main.lua
- plugins/statistics.koplugin/main.lua
In addition to toggle.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13387)
> Statistics: actions to enable/disable

- frontend/apps/cloudstorage/cloudstorage.lua
- frontend/apps/cloudstorage/webdavapi.lua
This PR adds a 'file size' property  to the item dialog when selecting an item using Webdav Cloudstorage (see picture).
Default menu when file size is available:
Forcing the 'item.filesize' to be nil to display 'N/A':
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13371)
> feat(cloudstorage/webdav): Show 'file size' property in WebDAV

- plugins/newsdownloader.koplugin/main.lua
Hi, I couldn't find instructions on how to make PRs so I just pushed one. Feel free to tell me if the procedure isn't followed. I stumbled on KoReader 3 days ago and it is a real gem, thank you very much for your work!
I found this issue on nightly 2025-03-10, v2024.11-223-g154ec621d_2025-03-03, KindlePaperWhite5.
Some RSS feeds contain items that don't have a description (for instance [this one](https://fabiensanglard.net/rss.xml), which is valid as per https://validator.w3.org/feed/). In that case the processing for the feed just stop abruptly and we get "Could not process some feeds. Unsupported format in: XXX (Reason: Failed to download content)".
Probably because the call `feed.description[1]` raise an exception like in this code, and the code is run on another thread (? I am not too …
> [plugin/NEWS-RSS] Handle missing description gracefully in rss feed

- plugins/newsdownloader.koplugin/main.lua
Fix issue #13408
> In the news plugin, when you add 2 news feed in a row from the UI, for the second item the UI is populated with the exact same data that you entered on the first item, instead of showing the default "blank" values.
The `empty_feed` data structure is mutated every time the user adds a new feed item. This result in the UI showing the previously added feed as the "default" for new feeds.
This is confusing as it _looks_ as if they were editing the previously inserted feed.
This PR just create a new empty feed item every time, so that mutations to that feed items are not an issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13411)
> fix for Add new entry show the url from the last added entry in NoewDownloader

- plugins/newsdownloader.koplugin/main.lua
A small commit that helped me debug issues with weird RSS feeds, feel free to discard it if you don't think it would be useful.
The current implementation of the NewsDownloader will silently discard errors generated during the call to `processFeed`. This PR just store that error and log it as "err" to help with debugging. Given that it is a hard failure, I logged it at err instead of dbg.
(It's my last PR, I promise)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13413)
> Do not discard RSS/Atom feed processing errors

- plugins/newsdownloader.koplugin/feed_view.lua
In the News downloader, on the "Edit news feed" screen. Each field to display is stored in a table.
The current code will replace "empty" UI elements with a line (separator). However it is relying on the truthiness of the value of the field. If the value is False, for instance for the "download image" item, then the UI element for that field will be replaced with a line in the UI.
This PR just makes sure that we check for explicit "nil" value instead of truthiness.
We could also check `value` (and not `value[2]`) against a constant like `SEPARATOR="---"`, and use that constant elsewhere in the code, but that would require larger code change.
This PR
Master
- - - …
> [News Downloader UI] Fix missing elements in the Add feeds window

- frontend/document/koptinterface.lua
Leading space in the pattern: to search for words starting with the pattern.
Trailing space in the pattern: to search for words ending with the pattern.
Leading and trailing spaces in the pattern: to search for the exact word.
Closes https://github.com/koreader/koreader/issues/11029.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13414)
> PDF: single-word search with leading and trailing spaces

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/modules/readerstatus.lua
- frontend/dispatcher.lua
- frontend/ui/widget/filechooser.lua
Action, in addition to Open next file.
Available in Reader and FM.
Closes https://github.com/koreader/koreader/issues/12689. Closes https://github.com/koreader/koreader/issues/13017.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13424)
> Open previous file in last book folder

- plugins/opds.koplugin/opdsbrowser.lua
Fix crash when a book doesn't have a description.
Reported in https://github.com/koreader/koreader/pull/13338#issuecomment-2728212872
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13428)
> OPDS: fix group download

- frontend/ui/widget/menu.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
**Before**
Mirrored layout, the icon in the right
**After**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13429)
> CoverBrowser list mode: fix shortcut icon position

- plugins/opds.koplugin/opdsbrowser.lua
Recent bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13443)
> OPDS: fix calling "file downloaded" dialog

- frontend/ui/widget/container/underlinecontainer.lua
- frontend/ui/widget/touchmenu.lua
* fix touch menu's focus underline (non-touch) when using RTL languages
see #13362 generally and https://github.com/koreader/koreader/pull/13362#issuecomment-2749434009
@poire-z
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13454)
> [UnderlineContainer] "fix" focus underline for RTL UI

- frontend/dispatcher.lua
Currently new single-action gesture/profile doesn't have `order` setting.
Let's ignore order for old single-action gestures.
Fixes https://github.com/koreader/koreader/pull/11072#issuecomment-2746366874.
Doesn't fix rtl inverting of multi-actions gestures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13450)
> Dispatcher: ignore order for single-action gesture

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/ui/widget/touchmenu.lua
(1) Do not open the upper menu when Menu search dialog is called by a gesture/profile.
(2) In search results dialog mark disabled items with "medium shade".
(3) "Open/walk" doesn't highlight disabled items (text of disabled highlighted item is not visible).
(4) "Open/walk" stops on the first disabled menu item if it has subitems.
"Open/walk" will show:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13493)
> Menu search fixes

- frontend/apps/reader/modules/readerfont.lua
- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/dispatcher.lua
Font file or user style tweak can be deleted (outside of the program) after assigning an action with them as arg.
Fix displaying the action in Gesture manager / Profiles.
Check for font/tweak existence before executing.
Closes https://github.com/koreader/koreader/issues/13479.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13488)
> Dispatcher: fix action deleted arg

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/ui/data/onetime_migration.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/widget/filechooser.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13503)
> File browser: filter by status

- frontend/apps/reader/modules/readerlink.lua
- frontend/dispatcher.lua
* Consolidated the `enabled_func` for footnote popup settings into a single location to avoid redundancy in `frontend/apps/reader/modules/readerlink.lua`. 
* Added a new function `onToggleTapLinks` to toggle the tap-to-follow links setting and display a notification of the current status in `frontend/apps/reader/modules/readerlink.lua`.
* Included the new `toggle_tap_links` event in the settings list and dispatcher menu order in `frontend/dispatcher.lua`. 
</p>
closes #13381
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13469)
> [ReaderLink, Dispatcher] add toggle for tap-to-follow links

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerutil.lua
- plugins/coverbrowser.koplugin/main.lua
New multiple-files actions:
(1) reset settings. Closes https://github.com/koreader/koreader/issues/9553.
(2) refresh cached book info. Closes https://github.com/koreader/koreader/issues/11730.
(3) set book status. Closes https://github.com/koreader/koreader/issues/13125.
Repositioning popup dialog buttons for consistency of single- and multiple- file dialogs.
Single file
Selected files
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13510)
> Selected files: more actions

- frontend/util.lua
If not quoted, this function does not work with directories that include a space in their name.
I noticed this when using calibre wirelessly. It reports the disk space as 1GB as this is the default if util.diskUsage doesn't work. Adding quotes around the directory fixes it on my Kobo Libra Color.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13448)
> Quote directory in util.diskUsage

- frontend/ui/message/simpletcpserver.lua
The http inspector expects `http_socket:start()` to return `true` on success
https://github.com/koreader/koreader/blob/b58fc372abfb8545262330ee38553d6dc7872da9/plugins/httpinspector.koplugin/main.lua#L103-L107
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13541)
> [plugin] HttpInspector: fix crash when starting server

- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/ui/widget/focusmanager.lua
* `frontend/ui/widget/focusmanager.lua`: Added logic in the `onFocusMove` function to flip the horizontal direction when RTL mode is enabled.
* `frontend/apps/reader/modules/readerpaging.lua`: Introduced `nextKey` and `prevKey` variables that adjust key events based on the layout direction.
* `frontend/apps/reader/modules/readerrolling.lua`: Similar changes to `readerpaging.lua`, adjusting key events based on the layout direction using `nextKey` and `prevKey`.
reported https://github.com/koreader/koreader/pull/12579#issuecomment-2692262849
okay @poire-z, this should solve the cursor key problem. But there is still another one. The focus underline sticks to the left side of the screen (touchmenu)... when it should move along with the text to the right
- - - …
> [FocusManager] correct cursor keys in RTL

- plugins/statistics.koplugin/main.lua
Statistics is disabled for pic documents.
Thanks https://github.com/koreader/koreader-base/pull/2050#issuecomment-2795276910.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13561)
> Statistics: do not read settings for pic documents

- frontend/ui/widget/dictquicklookup.lua
* [`frontend/ui/widget/dictquicklookup.lua`](diffhunk://#diff-f250b2c70dbfef162af814861c9c2f8cc36c8c7c7f9628ce75286dee13a8e5edL221-R221): Modified the `width` assignment to be user-patchable in the `DictQuickLookup:init()` function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13497)
> [DictQuickLookup] make the widget's width user patchable

- frontend/ui/screensaver.lua
(1) Because of long description, the input dialog buttons were overlapped with the keyboard.
Move description to the info message.
(2) Allow multiline messages. Closes https://github.com/koreader/koreader/issues/13559.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13571)
> Screensaver: improve sleep screen message

- plugins/statistics.koplugin/main.lua
https://github.com/koreader/koreader/pull/13387#discussion_r1986246214
Closes https://github.com/koreader/koreader/issues/13579.
@mergen3107 unfortunately disabling statistics in a profile auto-exec on book opening doesn't work anymore until a workaround is found.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13592)
> Statistics: revert erroneous nextTick in onReaderReady()

- frontend/device/kindle/device.lua
Added kindle basic 5 hall file. Have been using the following patch: 
```
local Device = require("device")
Device.powerd.hall_file = "/sys/devices/platform/eink_hall/hall_enable"
Device.powerd:initWakeupMgr()
```
which has been working for me, but should be updated in the project.
This allows Basic 5 users to make use of toggling "cover events"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13603)
> add kindle basic 5 hall file

- .github/ISSUE_TEMPLATE/bug_report.yml
It wasn't in the old template, and I didn't think of it for https://github.com/koreader/koreader/pull/13633
See https://github.com/koreader/koreader/issues/13636
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13637)
> Issue template: ask for firmware version

- frontend/device/remarkable/device.lua
- frontend/device/remarkable/powerd.lua
- kodev
What works:
- Everything except restarting KOReader
What's janky:
- Shutdown: rmpp-qtfb-shim and qtfb dies before it can display shutdown screen, resulting in whatever was displayed before staying
- Refresh: controlled by xochitl, (reMarkable's proprietary UI/UX and controls screen) will change in future after qtfb and shim gets ability to control it.
What doesn't work:
- restart KOReader: it doesn't even try to lol
Dependencies required to run:
- [XOVI](https://github.com/asivery/rm-xovi-extensions)
- [QTFB](https://github.com/asivery/qtfb)
- [rmpp-qtfb-shim](https://github.com/asivery/rmpp-qtfb-shim)
You need to set a few environmental variables when launching, like this:
`LD_PRELOAD=(path to your qtfb-shim.so) QTFB_SHIM_INPUT=false QTFB_SHIM_MODEL=false QTFB_SHIM_MODE=RGB565 …
> reMarkable Paper Pro support

- make/remarkable-aarch64.mk
I overlooked this file so kodev release didn't work, sorry for the oversight
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13656)
> fix: missing remarkable-aarch64 make file

- frontend/device/android/event_map.lua
We included keys that are not aosp, for a few? onyx t68 clones
We don't need them and they might clash with other vendor definitions.
C.f https://github.com/koreader/koreader/issues/13649
Wiki updated: https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-keys
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13660)
> android: remove vendor hacks from event_map

- frontend/apps/reader/modules/readermenu.lua
Closes https://github.com/koreader/koreader/issues/13658.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13673)
> Style tweaks: fix saving document settings as default

- frontend/apps/reader/modules/readerfooter.lua
- frontend/ui/widget/sortwidget.lua
Also keep the status bar visible to view changes immediately on pressing the Apply button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13682)
> Status bar sort items: dim inactive items

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/device/gesturedetector.lua
- plugins/gestures.koplugin/main.lua
Adjustable corresponding min/max values with a 0.1 s gap to avoid overlapping.
Closes https://github.com/koreader/koreader/issues/13027. Closes https://github.com/koreader/koreader/issues/13645.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13690)
> Gesture intervals: adjust long- and very-long-press intervals

- frontend/apps/reader/modules/readerhandmade.lua
- frontend/apps/reader/modules/readerthumbnail.lua
- frontend/ui/widget/bookmapwidget.lua
- frontend/ui/widget/pagebrowserwidget.lua
Discussed [here](https://github.com/koreader/koreader/issues/10433#issuecomment-2439732594), and subsequent comments, with @poire-z. 
Summary of changes: 
1. In Page browser: long-press on <kbd>Start TOC chapter here</kbd> will create empty TOC item; no dialog (if existing TOC item, nothing happens)
2. Similarly in highlight menu: Long press will create the TOC entry without the edit dialog
3. Opening Book map (overview) via long press in top menu will close the menu on launch
4. Book map allows larger page slot width adjustment via long press on +/- buttons
5. Cursor will be placed at start of text when editing Custom TOC chapter titles (not discussed yet)
I found that cursor placement at the front is more convenient in most scenarios. When adding chapter titles from scanned PDFs, the …
> Minor changes to PageBrowser/BookMap/ReaderHandmade

- frontend/apps/reader/modules/readerfooter.lua
This PR seeks to enhance the status bar admin, recently I found myself in a situation where my usual status bar was simply inadequate for the content and was therefore forced to make some adjustments, but hey, I now need to remember what settings I had before and.. I ain't got time for that. So PRESETS yay!
Users will be able to save multiple presets and switch to them simply by selecting them, that's it. 
This allows for things like: having a status bar specifically for PDFs and another for ePUB, or another for when on Landscape mode, etc.
* Added a new menu item "Status bar presets" to the status bar menu, enabling users to manage named presets for status bar settings.
* Implemented `getNamedPresetMenuItems` to dynamically generate menu items for creating, loading, updating, and …
> [ReaderFooter] add status bar presets

- frontend/ui/elements/common_settings_menu_table.lua
- plugins/gestures.koplugin/main.lua
As discussed in #13578: adds notifications when toggling `Ignore long-press on corners` via Dispatcher.
(Skips notification when toggled via menu.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13605)
> Add notification when toggling 'Ignore long-press on corners' via Dispatcher

- frontend/ui/message/streammessagequeue.lua
- plugins/calibre.koplugin/main.lua
- plugins/calibre.koplugin/wireless.lua
Faster and with better UI:
- roughly halve a successful connection setup
- drop manual & temporary TCP connection before the real ZMQ one:
- it slows down the total connection time
- it's actually counted by calibre as a failed connection attempt: after 5 consecutive failures from the same IP, calibre ignore further connections, with no feedback to the user, except an error trace, until the wireless server is restarted
- avoid unconditional 1s delay before checking for authentication failure
- "searching" & "connecting" (cancellable) dialogs
- stop connection on quit / restart
NOTE: I actually kept the temporary TCP connection check, but after a failed connection attempt (timeout getting replies from the server), to get a better error message (failure in hostname resolution, connection …
> calibre: rework connection setup

- frontend/util.lua
The output of df wraps on to multiple lines on the rmpp due to the device mapped mount points. Enabling the posix -P option to df prevents this and allow the output to be parsed as normal.
Closes #13731
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13732)
> Fix file transfer from Calibre to Remarkable Paper Pro

- frontend/device/pocketbook/device.lua
Add new PocketBook Verse Lite (PB619)
before: [crash.log](https://github.com/user-attachments/files/20127316/crash.log)
after: [crash.log](https://github.com/user-attachments/files/20127324/crash_1.log)
Picture:
Technical Details:
Device: https://pocketbook.de/en/pocketbook-verse-lite
Model No.: PB619
Display Type: E-Ink Carta™
Display Resolution: 758 × 1024
Display Size: 6 inches (15.24 cm)
DPI: 212
Color Depth: 16 Grayscales
Touchscreen: Capacitive (Multi-Sensor)
Frontlight: Yes
SMARTlight: No
Processor: Dual-Core (2 × 1 GHz)
RAM: 512 MB
Internal Storage: 8 GB
Battery: Lithium-ion polymer battery, 1000 mAh
Position Sensor: Yes
Page Scrolling Buttons: No
Sleep Cover Function: Yes
Wi-Fi: Yes (2.4 GHz)
USB Port: Yes (USB-C)
Expandable Storage: No
USB OTG: No
Operating System: Linux 3.10.65 …
> Add PocketBook Verse Lite (PB619)

- frontend/device/sdl/device.lua
This change adds the property, `useDPadAsActionKeys`, to the  SDL `Device` object, allowing to emulate [more closely now] a non-touch kindle device with `./kodev run -t`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13769)
> [SDL] set useDPadAsActionKeys flag with DISABLE_TOUCH

- plugins/SSH.koplugin/main.lua
Adds the option to start the SSH server when KOReader is launched. Tested on Kindle 7th Generation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13772)
> Add option to start SSH server with KOReader

- frontend/apps/reader/modules/readerfooter.lua
(1) Set chapter markers on preset loading. Closes https://github.com/koreader/koreader/issues/13745.
(2) Fix loading unordered preset. https://github.com/koreader/koreader/pull/13774#issuecomment-2874411574
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13746)
> Status bar: fixes

- frontend/ui/screensaver.lua
* Added a new flag `is_document_cover` to track whether the screensaver is displaying a document cover (`frontend/ui/screensaver.lua`).
* Updated the logic to reset `lastfile` and disable `show_message` if the last opened file has been marked as unopened and the screensaver is not displaying a document cover (`frontend/ui/screensaver.lua`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13747)
> [ScreenSaver] handle case where a file is lastfile but has now been reset

- frontend/device/generic/powerd.lua
- frontend/device/remarkable/device.lua
- frontend/device/remarkable/event_map.lua
- frontend/device/remarkable/powerd.lua
- frontend/ui/elements/common_settings_menu_table.lua
For waking up w/o launcher, we now handle event code 143, properly fixing issue #8891.
For proper exit when KO_DONT_GRAB_INPUT is set, we use a workaround that relaunches xochitl.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13795)
> reMarkable: Make sleep/waking up w/o launcher work and properly exit when KO_DONT_GRAB_INPUT is set

- frontend/ui/widget/imageviewer.lua
Avoid decoding the first image twice (and decompressing it twice when used through ArchiveViewer).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13807)
> ImageViewer: small optimization

- plugins/wallabag.koplugin/main.lua
Added an ability to set network timeouts manually (for example, in case of slow wallabag server). 
Closes https://github.com/koreader/koreader/issues/9101
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13786)
> Network timeout settings for wallabug plugin

- frontend/apps/reader/modules/readerdictionary.lua
This pull request enhances the `ReaderDictionary` module by introducing functionality to manage dictionary preferences on a per-book basis. It allows users to prioritise dictionaries and disable specific dictionaries for individual books. 
* **Added a new `showPreferredDictsDialog` method**: This dialog allows users to prioritise active dictionaries and toggle their enabled/disabled state for the current book. Disabled dictionaries are visually marked and placed at the bottom of the list.
* **Updated `addToMainMenu` method**: Introduced a new menu item, "Set dictionary priority for this book," which opens the dictionary preferences dialog. This menu item is conditionally displayed based on the document state and the number of active dictionaries. 
* **Filtered dictionaries during …
> [ReaderDictionary] Enable dictionary prioritisation via new menu

- frontend/device/devicelistener.lua
- frontend/dispatcher.lua
ATM you can only toggle G sensor lock in dispatcher, this commit adds the ability to set the lock to on or off.
This can be useful in profiles that want to set an explicit mode instead of toggling the setting.
Change-Id: 5805932cf901fc05a4072b801847ae92
---
A quality of life improvement for https://github.com/koreader/koreader/pull/13675
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13835)
> feat: add set lock orientation in dispatcher

- frontend/apps/reader/modules/readersearch.lua
- frontend/dispatcher.lua
Easy jump to the page which the search started on.
Helps in https://github.com/koreader/koreader/discussions/13779, allowing to browse through all search results without jumping back every time.
Also an action, can be added to a profile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13798)
> Fulltext search: start page

- frontend/apps/reader/modules/readerannotation.lua
- frontend/apps/reader/modules/readerhighlight.lua
To extend an existing highlight: tap on it
Tap on three dots
Tap on Extend
You are now in select mode. Select ending fragment to combine the existing highlight with it.
As usual, tap on an icon or on the highlight to exit select mode without changes.
Style, color, note are preserved.
Edited highlight text is removed because we have a new highlighted text.
Closes https://github.com/koreader/koreader/issues/13776.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13815)
> Highlights: extend

- frontend/ui/widget/filechooser.lua
- frontend/ui/widget/menu.lua
- plugins/coverbrowser.koplugin/main.lua
Avoid re-reading the storage, avoid re-building the titlebar subtitle.
Fixes https://github.com/koreader/koreader/issues/13818#issuecomment-2889089691 (double auto-execution).
Also removed unused FileChooser method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13822)
> Coverbrowser: optimize display mode switching

- tools/mkrelease.sh
The manifest entry for `koreader/frontend/socketutil.lua` is wrong:
```
koreader/frontend/socketutil.lua/
```
That's because the CRC for that file (0E376639) compare as a false value when used conditionally with `if (0E376639)`. The correct way to check for an empty string is to use: `if (0E376639 != "")`.
NOTE: no impact that I could see on the actual generated archive, e.g.
for kindlepw2: the file is still included.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13847)
> tools/mkrelease: fix bug in AWK helpers

- frontend/ui/widget/buttondialog.lua
- frontend/ui/widget/container/movablecontainer.lua
- frontend/ui/widget/dictquicklookup.lua
* Added key event bindings in `MovableContainer:init()` to allow users to move the dialog up or down using keyboard modifiers (`Shift` or `ScreenKB`) combined with arrow keys (`Up` and `Down`). These events trigger the new `MovePosition` event.
* Added a property `is_movable_with_keys` to the MovableContainer class, that allows disabling it on widget where it is not necessary or not desirable, like dictionary widget.
* Introduced the `MovableContainer:onMovePosition(is_moving_to_top)` method to handle dialog repositioning. This method calculates the new vertical position based on the screen height, dialog height, and padding, updates the dialog's offset, and forces a screen redraw to reflect the changes.
<div align="center">
</div>
* closes #12596
- - - …
> [MovableContainer] allow widget repositioning on non-touch devices

- frontend/device/devicelistener.lua
- frontend/dispatcher.lua
Currently you can only toggle page turn buttons to inverted or not. This commit adds the ability to also have an option in dispatcher to set the value instead of just toggling.
This can be useful for profiles that want to set the value rather then toggle.
Change-Id: bde93e44794788fbc8b3c2ef6857d053
---
Quality of life improvement for  https://github.com/koreader/koreader/pull/13675
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13836)
> [feat] Dispatcher: Add 'Set page-turn button inversion'

- frontend/ui/widget/filechooser.lua
Discussed from [here](https://github.com/koreader/koreader/issues/4505#issuecomment-2887337723).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13829)
> FileChooser: Un-blacklist 'dict' and 'custom-dict' dirs in File browser

- make/appimage.mk
The more recent versions use ZSTD for compression, and net us a nice 2 MB reduction of the final AppImage' size.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13885)
> appimage: update appimagetool

- frontend/device/android/device.lua
With Onyx Boox Go 7. When the device is rotated (Left Hand to Right Hand) the button function does not rotate.
need to add Onyx Boox Go 7 to list of devices that need disableRotationMap() activated.
user patch works in the meantime. On current android nightly ( v2025.04-90-g58860f65d_2025-05-27 )
``` lua
local logger = require("logger")
local Device = require("device")
Device.input.rotation_map = {
[0] = {},
[1] = {},
[2] = {},
[3] = {},
}
logger.info("Hardware button rotation disabled by user patch")
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13872)
> Added Onyx Boox Go 7 to devices that follow gravity.

- plugins/hotkeys.koplugin/main.lua
* don't attempt to override readerfont's key events when opening pdf/djvu files. Reported https://github.com/koreader/koreader/issues/13895#issuecomment-2923450941
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13896)
> [Hotkeys] bug fix: don't override readerfont when reading pdf/djvu files

- frontend/document/djvudocument.lua
Crash reported in https://github.com/koreader/koreader/issues/13895.
Also crashed when changing highlight boundaries.
The first step only. Needs more testing on various systems with various djvu files, so keep the issue opened.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13897)
> DJVU: add getTextBoxes()

- frontend/ui/widget/buttondialog.lua
Will be used, for example, in multiple-choice dialogs:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13893)
> ButtonDialog: add widgets

- frontend/ui/widget/dictquicklookup.lua
we've all been there, you look up a word definition only to realise is long AF and you ponder, why isn't there an easy way to go full screen mode here? well worry not past me... here it is.
* **Static Variables and Properties**: Added a new static variable `temp_fullscreen_request` and a private property `_is_temporary_fullscreen_mode` to manage the temporary fullscreen state.
* **Gesture and Key Bindings**: Introduced a new gesture (`spread`) and a key binding (<kbd>screenkb/shift</kbd> + <kbd>home</kbd> ) to trigger the temporary fullscreen mode.
* **Initialisation Logic**: Updated the `init` method to check for `temp_fullscreen_request` and set the appropriate dictionary and fullscreen mode state during initialisation. 
* **Fullscreen Mode Implementation**: Added …
> [DictQuickLookup] enable full-screen mode for open dictionary window

- frontend/apps/reader/modules/readerfooter.lua
- frontend/ui/widget/touchmenu.lua
- plugins/bookshortcuts.koplugin/main.lua
- plugins/texteditor.koplugin/main.lua
Similar to the Menu widget, add `item.idx` to avoid rebuilding the whole menu or iterating over all items when removing an item.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13901)
> TouchMenu: optimize item removal

- frontend/apps/reader/modules/readerdictionary.lua
This pull request introduces a small enhancement to the `ReaderDictionary` module. The change improves the handling of word lookups by adding a lowercase version of a word to the search array if the word starts with a capital letter and fuzzy search is disabled.
it does seem quite silly, that a user might not get any results due to punctuation, in the following example all "Count", "Back", "Your", "Wait", "Have", "Tonight", "Tomorrow" and "There" yield no results at all, event though the dictionary has entries for them (in lowercase)
</p> 
</p> 
* fixes #13346
* fixes #10348
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13884)
> [ReaderDictionary] match words when they are Capitalised

- frontend/ui/widget/bookstatuswidget.lua
(1) allow to remove rating (consistent with BookInfo window). Closes https://github.com/koreader/koreader/issues/13938.
(2) do not show review input hint in sleep screen (https://github.com/koreader/koreader/issues/12373).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13943)
> BookStatus widget: minor fixes

- frontend/apps/cloudstorage/cloudstorage.lua
- frontend/apps/cloudstorage/dropbox.lua
- frontend/apps/cloudstorage/dropboxapi.lua
- frontend/apps/cloudstorage/ftp.lua
- frontend/apps/cloudstorage/webdav.lua
- frontend/apps/cloudstorage/webdavapi.lua
- frontend/socketutil.lua
- frontend/ui/widget/progressbardialog.lua
~~This is currently a **draft PR**.
I just wanted to get general feedback on the whole idea and implementation, as I'm quite new to this code base.~~
The goal of this PR is to provide a progress bar when downloading files via cloud storage e.g. Dropbox/WebDav/FTP.
In the current implementation this only works for Dropbox and WebDav, **for FTP the file size is not available when downloading**.
Depending on the use case it might be best to move this "progress bar window"-component into it's own widget, so it can be used for other things as well (e.g. #11217).
Here is a picture of the new download window:
Here is the current status with FTP. The filesize is 'N/A' and we don't show the progress bar in the dialog:
Stuff that needs more consideration:
Regarding FTP downloads, it might be …
> feat: Adds progress bar to cloud storage downloads

- frontend/apps/reader/modules/readerhighlight.lua
* [`frontend/apps/reader/modules/readerhighlight.lua`](diffhunk://#diff-db51db4b48e0314c642050876de6cd601d148eaaa00d4511523f811531d63ccfR78-R80): Updated `init()` to conditionally trigger `onStartHighlightIndicator()` for non-touch devices.
* [`frontend/apps/reader/modules/readerhighlight.lua`](diffhunk://#diff-db51db4b48e0314c642050876de6cd601d148eaaa00d4511523f811531d63ccfR2686-R2692): Enhanced `onHighlightPress()` to handle select mode, improving the user experience for extending highlights.
* [`frontend/apps/reader/modules/readerhighlight.lua`](diffhunk://#diff-db51db4b48e0314c642050876de6cd601d148eaaa00d4511523f811531d63ccfR2799-R2808): Updated `onStopHighlightIndicator()` to properly end selection mode when the user presses back. Temporary highlights are deleted, and UI regions are …
> [ReaderHighlight] NT: add better support for extending highlights

- Makefile
- frontend/gettext.lua
- make/gettext.mk
- spec/unit/gettext_spec.lua
Binary catalogs are more space efficient (total translations disk usage: 14MB instead of 35MB), and easier and faster (roughly 10 times) to load: no parsing, and less processing (no need to unescape strings).
Not much difference on the Android APK size (a ~600KB reduction), but other TAR.GZ / ZIP distributions see a reduction of ~3.5MB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13967)
> gettext: switch to binary catalogs

- .github/workflows/build.yml
Update ninjatracing to account for latest ninja log format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13992)
> ci/macos: fix "Dump build timings" step

- frontend/ui/widget/filechooser.lua
- frontend/ui/widget/pathchooser.lua
I'd like to have the `ui` parameter to the `item_func` of a collate always available, regardless of which collate is in use and whether the item is a file or directory. This allows user patches that add new collates to access all functionality for sorting.
@hius07 It's not entirely clear to me why the `self.ui` parameter was only set conditionally in `PathChooser` in #13437. Is there a specific reason for that choice?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13981)
> Pass `ui` parameter to all collate `item_func`

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/dispatcher.lua
- frontend/ui/elements/screen_rotation_menu_table.lua
- frontend/ui/widget/touchmenu.lua
- plugins/SSH.koplugin/main.lua
- plugins/autoturn.koplugin/main.lua
- plugins/autowarmth.koplugin/main.lua
- plugins/calibre.koplugin/main.lua
- plugins/coverimage.koplugin/main.lua
- plugins/gestures.koplugin/main.lua
- plugins/hotkeys.koplugin/main.lua
- plugins/profiles.koplugin/main.lua
By default, on tapping an item with a checkmark the Touchmenu:
(1) keeps the menu open
(2) highlights the item
(3) unhighlights the item
(4) fires the callback
(5) updates itself to show the changes.
If the callback updates the menu, (5) is not needed.
If the callback closes the menu, (3) and (5) are not needed.
This PR allows to avoid menu update duplicating and to avoid calling unneeded unhighlighting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13996)
> Touchmenu: fix menu refreshing on check

- frontend/ui/widget/htmlboxwidget.lua
When the contents of the HtmlBoxWidget changed the page boxes were not invalidated, this resulted the highlight to show up at a wrong coordinate.
Fixes #14013
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14028)
> Dictionary: fix invalid highlight when switching dictionary

- plugins/opds.koplugin/opdsbrowser.lua
As discussed in #13946 
Adds button in download list to do download all and remove all. Currently, both options remain when selecting individual books. I think it should be completely moved to the top left but I understand there being a reason for wanting to keep it where it is and duplicate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14024)
> Moving download all and remove all buttons in OPDS download menu

- frontend/apps/reader/modules/readerhighlight.lua
Fix a bug caused by https://github.com/koreader/koreader/pull/14004: after long-pressing on an image, taps don't work until long-pressing on text.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14048)
> ReaderHighlight: fix long-pressing on image

- plugins/wallabag.koplugin/main.lua
Adds a checkbox in the wallabag download settings, restricting the download of articles from wallabag to starred/favorite items
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14051)
> [plugin] wallabag - allow filtering download to starred articles

- frontend/util.lua
This change fixes an issue where a file/directory is not created when its name contains trailing spaces or dots. The issue has been observed on a Kobo device, but probably also applies to other systems using vFAT.
We also might want to consider handling other illegal vFAT filenames like `NUL` or `AUX`.
Please see the [official Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) for more details on the naming conventions of vFAT (this change addresses the last bullet point).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14043)
> [fix] Improve handling of illegal vFAT filenames.

- frontend/device/kindle/device.lua
- frontend/device/kindle/powerd.lua
Adds support for the Kindle Oasis (KOA) charging cover, codename "soda". 
Much of this code was taken from the Kobo implementation of an auxiliary battery. The biggest difference between the Kobo and Kindle implementation is that the status file for the charging cover is not present when the cover is detached, so the check for status there will result in the file failing to read.
Tested on two Kindles running koreader 2024.11.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13133)
> Support Kindle Oasis (KOA) charging cover "soda"

- plugins/terminal.koplugin/main.lua
- avoid potential out-of-bound read access + fix suboptimal code
- avoid blowing the stack with recursive calls (close #14084)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14090)
> terminal plugin fixes

- plugins/opds.koplugin/opdsbrowser.lua
- spec/unit/opds_spec.lua
This commit introduces support for OPDS 1.2 facets, enabling advanced filtering and sorting in compatible catalogs.
To maintain a clean and uncluttered book list, facet options are not mixed with catalog entries. Instead, they are presented in a dedicated context menu, providing a more intuitive user experience.
- When a catalog provides facets or a search link, the top-left button in the OPDS browser now functions as a menu trigger, displaying all available actions for the current feed.
- Facet links (`<link rel="http://opds-spec.org/facet">`) are parsed and grouped according to the `opds:facetGroup` attribute.
- The new context menu includes all facet groups, the catalog's search action, and the option to bookmark the current feed, unifying all feed-level operations.
- Support for …
> feat(opds): add support for facets via a context menu

- plugins/autowarmth.koplugin/main.lua
Resolves https://github.com/koreader/koreader/issues/13163 FR: Hide the AutoWarmth Plugin "Night Mode changed" popup forever. 
It adds 3 simple things:
1. New `G_reader_settings` called `"hide_nightmode_warning"`.
2. Adds a radio button to the popup in question to disable it permanently.
3. Adds a button in the plugin sub-menu to turn it back on (or turn it off from the menu if desired).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13253)
> Satisfy FR #13163: Option to hide the "night mode changed" warning

- frontend/device/input.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
Adds menu items (toggles) and functionality to turn a kobo back on with the page turn buttons.
Fix #13668
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13669)
> [Kobo] Enable wake on page turn buttons

- plugins/profiles.koplugin/main.lua
Profiles are auto-executed in a safe way: within `nextTick()` or even `tickAfterNext()`, to avoid interference with other operations/events.
But sometimes (e.g. on closing a document) a user needs to execute it promtly, provided there are no conflicts with other actions.
Closes https://github.com/koreader/koreader/issues/14126.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14133)
> Profiles: auto exec promptly

- frontend/apps/reader/modules/readerhighlight.lua
`datetime_updated` property should not be filled for new highlights.
Regression in https://github.com/koreader/koreader/pull/13815.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14155)
> Highlight: fix datetime_updated for new highlights

- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerrolling.lua
The footer does not use "document position".
No need to have separate code paths for "page" and "scroll" view modes.
Removed duplicated code and code execution when building and showing the footer.
Closes https://github.com/koreader/koreader/issues/14065.
Despite of the above optimization, the footer text generator is still executed 3 times when opening an epub book, but looks like this cannot be fixed with the current architecture.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14076)
> ReaderFooter: document position is not used

- .ci/after_success_docs_translation.sh
Since luarocks >= 3.12.0 is broken, and does not honor `wrap_bin_scripts = false` anymore, just call ldoc directly so it works even if a wrapper script is used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14207)
> ci: fix call to ldoc

- frontend/device/remarkable/device.lua
While looking at code, I found out that it's checking for both RM2FB AND QTFB not one of those. It should only be triggered when both aren't present, so replace `or` to `and`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14222)
> fix/remarkable: rM2 RM2FB check fix

- plugins/wallabag.koplugin/main.lua
Closes #14214.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14221)
> Wallabag: fix archive_finished initialization logic

- frontend/ui/data/keyboardlayouts/hu_keyboard.lua
- frontend/ui/widget/virtualkeyboard.lua
Hungarumlauts (double acute accents) were missing from O and U so I added them to a hungarian layout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14237)
> Add Hungarian keyboard layout

- frontend/device/input.lua
Should help with *some* #12787 reports, but not all, since that issue predates the PR that implemented the above feature (#13669)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14216)
> Kobo: Don't send `PowerPress` twice when fudging page turn button events for `pageturn_power`

- frontend/device/kindle/device.lua
* Improved error handling in `NetworkMgr:getCurrentNetwork()` to safely return an empty table if `kindleGetCurrentProfile()` is nil, preventing possible nil dereference issues.
@NiLuJe needs to bless this one.
fixes #14215
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14219)
> [Device, kindle] early return if kindleGetCurrentProfile() is nil

- plugins/wallabag.koplugin/main.lua
Downloading a PDF with a mimetype that includes `;...` failed. I then noticed that the original `article.mimetype` was used to lookup the file extension, instead of the cleaned up `local mimetype`. This fixes that.
I was also adding debug logging while trying to replicate #14147, and figured it might be useful to leave those in, but didn't think those are worth a separate PR, so left them here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14271)
> Fix downloading of PDFs with non-standard mimetype from wallabag

- plugins/calibre.koplugin/wireless.lua
Prompt the user again if the inbox folder has been configured but is missing (or not a directory).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14293)
> calibre: handle a missing inbox folder

- frontend/ui/widget/keyvaluepage.lua
* Added a new `onCloseWithKey()` method that checks for a return arrow and callback before invoking the appropriate close or return logic, providing clearer behavior when closing the page via a key event.
*  fix #14266
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14270)
> [KeyValuePage] back button returns to parent

- frontend/device/android/device.lua
Seems like #9223 , confirmed that disabling rotation via a userpatch resolved the issue.
At what point would this make sense to handle this in a different way, eg a list?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14317)
> Fix hibreak/bigme b7 buttons being inverted when the device is rotated

- .emmyrc.json
Also see <https://github.com/koreader/koreader/pull/10611>. There's some degree of compatibility with the LuaLS config `.luarc.json` but it didn't seem to work all that well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14319)
> Add a config file for EmmyLua Analyzer Rust LSP

- frontend/pluginloader.lua
Errors in plugins are logged but they are not actionable. As a plugin developer I expect some help from koreader.
This patch provides a way to get a lua stack trace when a plugin event  handler raises an error. This is achieved by wrapping each event handler with `xpcall` in place of `pcall`. This lua builint allows executing a error handler before the stack is unwound. The traceback we get is then from the execution in the plugin context.
The following is an example of where I am stuck. These are the last two errors I got. I am not sure if I have uncovered known errors or I am doing something wrong in the wrapping.
I made this patch by unpacking the appimage but I will transition to kodev soon to test more.
```bash
edoput@nibbler ~/r/koreader [SIGINT]> ./AppRun …
```
> plugin handlers traceback

- frontend/apps/reader/modules/readerkoptlistener.lua
- frontend/document/koptinterface.lua
- frontend/ui/data/koptoptions.lua
- frontend/ui/data/ocr.lua
- frontend/ui/widget/configdialog.lua
Messing about with advanced settings is kind of annoying, isn't it?
In reply to <https://github.com/koreader/koreader/issues/11147#issuecomment-2571602782>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13004)
> Autodetect OCR language support files

- frontend/ui/widget/sortwidget.lua
When using <kbd>shift</kbd>/<kbd>screenkb</kbd>  + <kbd>press</kbd>  on non-touch devices, hold events were always affecting the first item instead of the focused one. Added onHold() handler to SortWidget that directly targets the focused item, bypassing the coordinate-based gesture system that was causing the misdirection.
* Renamed the `onHold` method to `onHoldTouch` in `SortItemWidget`, ensuring the method does not clash with FocusManager's own Hold events.
* Updated the `registerKeyEvents()` method in `SortWidget` to add a new `HoldNonTouch` event for keyboard-based hold actions, and unified modifier handling for screen keyboard and physical keyboard inputs.
* Added a new `onHoldNonTouch` method in `SortWidget` to handle keyboard-triggered hold events by invoking the `onHoldTouch` …
> [SortWidget] bug fix: Fix keyboard hold events targeting wrong item

- tools/mkrelease.sh
7z shows an empty CRC for empty files when generating an archive manifest:
```
▸ mkdir dir
▸ touch dir/empty
▸ echo foobar >dir/foobar
▸ 7z a test.7z dir
[…]
▸ 7z -ba h dir
dir
B22C9747             7  dir/foobar
00000000             0  dir/empty
▸ 7z -ba -slt l test.7z
Path = dir
Size = 0
Packed Size = 0
Modified = 2025-09-27 22:55:25.7947183
Attributes = D drwxr-xr-x
CRC =
Encrypted = -
Method =
Block =
Path = dir/empty
Size = 0
Packed Size = 0
Modified = 2025-09-27 22:43:34.0722990
Attributes = A -rw-r--r--
CRC =
Encrypted = -
Method =
Block =
Path = dir/foobar
Size = 7
Packed Size = 11
Modified = 2025-09-27 22:55:25.7947183
Attributes = A -rw-r--r--
CRC = B22C9747
Encrypted = -
Method = LZMA2:12
Block = 0
```
- - - …
> tools/mkrelease: handle corner case

- frontend/apps/filemanager/filemanagerbookinfo.lua
(1) Show number of pages of reflowable documents in "Book information" called from the file browser.
(2) Show number of **reference** pages (if used) in "Book information" of the currently opened file.
(3) Show total/current **reference** pages (if used) in messages extended by patterns.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14373)
> BookInfo: minor fixes

- frontend/ui/data/onetime_migration.lua
- frontend/ui/elements/screensaver_menu.lua
- frontend/ui/screensaver.lua
- frontend/ui/widget/container/custompositioncontainer.lua
Have you ever found yourself in a situation where your book has a beautiful illustration, that sadly gets blocked by the sleep screen message? or the title happens to be dead centre and (because you prefer the infomessage) so, that spicy señorita at the coffee shop can't see how smart you are because the bloody title is now hidden? well fear not...
This pull request refactors how the screensaver message's position is configured and displayed. Instead of using the previous "top/middle/bottom" options, it introduces a more flexible system with "banner" and "box" containers and allows custom vertical positioning. 
* Migrated existing settings from `screensaver_message_position` ("top/middle/bottom") to new settings: `screensaver_message_container` ("banner"/"box") and …
> [ScreenSaver] allow sleep screen message to be placed anywhere on screen

- frontend/ui/screensaver.lua
* Changed the conditional in `Screensaver:show()` to check if `vertical_percentage > 80` (top of the screen) instead of `< 20` (bottom of the screen) before forwarding the message height to the overlay widget. 
Mistakes were made when swapping top/bottom values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14403)
> Bug fix: Change condition for message height calculation

- frontend/device/remarkable/device.lua
Use the modified event_map from above instead of reloading the event_map file, reverting unmapped event.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14415)
> fix/remarkable: event_map remapping fix

- plugins/opds.koplugin/opdsbrowser.lua
Follow-up to #14248.
The second result of `gsub` (total number of substitutions made) was passed as the second arg to
https://github.com/koreader/koreader/blob/7c677bf2ae391bf7f8a43b32ed9fecccb89f978a/plugins/opds.koplugin/opdsbrowser.lua#L714
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14425)
> OPDS: fix Search
