koreader/koreader

Makefile, frontend/apps/reader/modules/readeractivityindicator.lua, frontend/device/input.lua, frontend/device/pocketbook/device.lua, platform/pocketbook/koreader.app
More discussions can be found at #1387.
=> add PocketBook port of Koreader

frontend/device/kindle/device.lua
Depends on [koreader-base #297](/koreader/koreader-base/pull/297).
----
Fix #1403
=> Fix input on KT2 (re #1403)

frontend/device/generic/device.lua, frontend/device/generic/powerd.lua, frontend/device/kobo/device.lua, frontend/ui/networkmgr.lua, plugins/evernote.koplugin/main.lua
This should fix #1386, #1383 and #1401.
=> fix PocketBook screen configuration and Evernote login

frontend/apps/filemanager/filemanager.lua, frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readermenu.lua, frontend/apps/reader/modules/readersearch.lua, frontend/apps/reader/modules/readertoc.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/otamanager.lua, frontend/ui/widget/filechooser.lua, frontend/ui/widget/menu.lua, frontend/util.lua
The stable channel won't be usable until the next stable release though.
=> various fixes

frontend/device/kindle/device.lua
=> add page-button support for Kindle Voyage

.travis.yml, Makefile, README.md, frontend/httpclient.lua, frontend/ui/uimanager.lua, reader.lua, spec/unit/document_spec.lua, spec/unit/httpclient_spec.lua
it uses non-blocking turbo I/O looper to process http request
so that multiple http request can be handled simultaneously and http request
won't block user input, and most importantly, in Lua's way.
=> add async http client

frontend/ui/data/koptoptions.lua, frontend/ui/widget/configdialog.lua, frontend/ui/widget/container/framecontainer.lua, frontend/ui/widget/toggleswitch.lua, plugins/kosync.koplugin/main.lua
This allows disabling reflow options when reflow is not ON. 
This should also fix #1061 and when fine tuning font size the size indicator also changes.
=> Dynamic config panel

platform/kindle/koreader.sh, platform/kobo/koreader.sh
=> Load our own shared libraries if possible

frontend/ui/widget/button.lua, frontend/ui/widget/container/inputcontainer.lua, frontend/ui/widget/menu.lua, frontend/ui/widget/touchmenu.lua
by holding on the page info label at the buttom of the filemanager.
This should fix #1042.
=> Add 'input page number' function in filemanager

frontend/apps/reader/modules/readerdictionary.lua, platform/android/llapp_main.lua
Stardict dictionary files should be copied to
/sdcard/koreader/data/dict/ directory.
=> Dictionary on Android

platform/kobo/nickel.sh
I managed to be approximately 12 seconds too late for @chrox's merge ;p.
=> Very, very minor addendum to #1504

frontend/device/kindle/powerd.lua, platform/kindle/libkohelper.sh
The fL thing originally came from a crash report, but that turned out to be because the user wasn't root. Still, the change has merit on its own ;).
=> Minor Kindle tweaks

platform/kobo/nickel.sh
By killing the WiFi first, since apparently,
nickel really doesn't like that, and causes a deadlock.
re #1503, re #1504, fix #1520
=> Fix nickel restart with WiFi up.

frontend/device/input.lua, frontend/device/kobo/device.lua
See discussions in https://github.com/koreader/koreader/issues/1525
=> Kobo Glo HD support

defaults.lua, frontend/ui/uimanager.lua, spec/unit/commonrequire.lua, spec/unit/httpclient_spec.lua
This should fix #1535 and fix #1498.
=> disable turbo lib by default

frontend/apps/reader/modules/readerhighlight.lua
=> partial refresh after deleting highlights

.busted, .travis.yml, Makefile, platform/kobo/nickel.sh
The new Travis container-based format doesn't do sudo anymore, so there are some fairly extensive changes.
It does, however, allow cache.
I also took the opportunity to switch to a newer busted. The root element for that now needs to be a table.
=> Travis update

frontend/apps/reader/modules/readertypeset.lua
=> Fix clear external styles not persistent in document settings

frontend/device/kindle/device.lua
My bad, I only had a Kobo on hand yesterday, so a stupid mistake crept in at the last minute :/.
That basically broke startup on Kindles, which is, err, bad.
=> Unbreak on Kindles

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/ui/widget/touchmenu.lua
Addresses comments on MR.
Add a comment explaining the magic behind CRe's charging icon when using
CRE's full (top) status bar.
=> Prefix battery percentage w/ a + when charging.

.travis.yml, frontend/apps/reader/modules/readerconfig.lua, frontend/ui/font.lua, frontend/ui/widget/button.lua, frontend/ui/widget/buttontable.lua, frontend/ui/widget/container/centercontainer.lua, frontend/ui/widget/container/inputcontainer.lua, frontend/ui/widget/container/widgetcontainer.lua, frontend/ui/widget/focusmanager.lua, frontend/ui/widget/touchmenu.lua, frontend/ui/widget/widget.lua, spec/unit/font_spec.lua
=> keyboard support for confirmbox and buttontable

frontend/apps/opdscatalog/opdscatalog.lua, frontend/ui/widget/opdsbrowser.lua
and get rid of the ugly baseurl workaround for "Internet Archive",
actually the url building of all these catalogs is perfectly
handled with `url.absolute(base, relative)`.
=> fix #1593 cannot download from COPS OPDS server

frontend/ui/widget/menu.lua, frontend/ui/widget/opdsbrowser.lua
use coroutine to support ad-hoc callback in login button so that when
the username/password is incorrect it will retry automatically
currently tested with COPS on apache
This should fix #1001.
=> add Basic Authentication for OPDS catalog

frontend/ui/widget/container/inputcontainer.lua, plugins/kosync.koplugin/KOSyncClient.lua, plugins/kosync.koplugin/main.lua
=> add custom sync server option in Kosync plugin

frontend/device/android/device.lua, frontend/device/emulator/device.lua, frontend/device/generic/device.lua, frontend/device/kindle/device.lua, frontend/ui/widget/buttontable.lua
1. no need to do full screen refresh when out of screensaver on KV
2. don't show a highlighted button in confirm dialog on KV
=> fix some minor issues on Kindle Voyage

frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/textboxwidget.lua
=> hold to lookup word in dict window

frontend/ui/font.lua
these fonts can not be used by freetype and will cause hang up.
This will fix https://github.com/koreader/koreader/issues/1577
=> exclude those broken kindle system fonts

README.md, frontend/apps/reader/modules/readerfont.lua
=> fix hold-to-set font size not effective

plugins/statistics.koplugin/main.lua
Changed format to this:
```
["stats"] = {
["performance_in_pages"] = {
[1448307556] = 3,
[1448307575] = 7,
[1448307570] = 6,
[1448307564] = 5
},
["authors"] = "William Shakespeare",
["total_time_in_sec"] = 21,
["notes"] = 0,
["title"] = "Romeo and Juliet",
["highlights"] = 0,
["pages"] = 202,
["series"] = "",
["language"] = "en"
},
```
=> #1718 Save the statistics data into the history file

frontend/apps/reader/modules/readerfooter.lua, frontend/util.lua, plugins/statistics.koplugin/main.lua, plugins/statistics.koplugin/tableutil.lua
Add new statuses:
TB - book time to read
TC - chapter time to read
Fix backward compatible in statistics plugin
=> #1723 Add time to read into the status bar

frontend/apps/reader/modules/readerfooter.lua, plugins/statistics.koplugin/main.lua
Change time to read book formula to: ((total_read_time / read_pages) * (all_pages - current_page))
=> #1750 TB feature/statistics issue

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/readerui.lua
This fixes https://github.com/koreader/koreader/issues/1752
=> fix(ReaderFooter:getDataFromStatistics): return na if book has no stats history

frontend/apps/filemanager/filemanager.lua
=> fix: make screenshoter always active for filemanager

Makefile, README.md, frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerfilesearcher.lua, frontend/docsettings.lua, platform/kindle/extensions/koreader/README.txt, spec/unit/docsettings_spec.lua, spec/unit/filemanager_spec.lua
This RP fixes #1764 . 
Since it also bumps the base, can someone test this on Kindle before merge? I can only test the new koreader-base on Kobo. It's stable for me so far.
=> fix #1764 & bump koreader-base

.travis.yml, Makefile, kodev
according to https://github.com/travis-ci/travis-ci/issues/5548, we need to upgrade luarocks.
this PR relies on https://github.com/koreader/koreader-base/pull/376
=> fix travis build

frontend/ui/widget/menu.lua, plugins/statistics.koplugin/main.lua
=> #1807 FR: Add separator into menu

frontend/apps/reader/modules/readerstatus.lua, frontend/apps/reader/readerui.lua, frontend/document/pdfdocument.lua, frontend/ui/widget/statuswidget.lua, frontend/util.lua, plugins/statistics.koplugin/main.lua
Added into statistics plugin and into status too.
Used this document as example:
https://archive.org/download/TheCompleteWorksOfHPLovecraft_201412/The%20Complete%20Works%20of%20H.P.%20Lovecraft.pdf
=> #1710 FR: Add support of statistics plugin for pdf

frontend/device/kindle/device.lua
=> do full screen refresh on KV after waked up from screensaver

frontend/ui/widget/container/inputcontainer.lua
This should fix https://github.com/koreader/koreader/issues/1834
=> fix inputcontainer

frontend/apps/filemanager/filemanager.lua
This change uses newly pushed commit 74e57274ab8d21b99e614bcf4c050e32f407feee @ koreader-base to implement rename function in filemanager.
This new feature proposal is discussed @ https://github.com/koreader/koreader/issues/1838
=> Add rename function for filemanager

frontend/ui/widget/logindialog.lua, frontend/ui/widget/multiinputdialog.lua
eg. LoginDialog and MultiInputDialog
since the style refactoring in #1783.
=> fix broken extended InputDialog components

platform/kindle/koreader.sh
Mostly related to FW >= 5.6 and KUAL
=> Some Kindle fixes

.ci/common.sh, .ci/script.sh, frontend/apps/reader/modules/readergoto.lua
fix #1851 
Also simplified the goto dialog UI a bit
=> add current page to goto input hint

frontend/ui/widget/touchmenu.lua, kodev
This might be related to https://github.com/koreader/koreader/issues/1771
Fix #1850
This PR also relies on https://github.com/koreader/koreader-base/pull/384
=> bump base for android fix

frontend/apps/reader/modules/readerfrontlight.lua, frontend/device/generic/powerd.lua, frontend/device/kindle/powerd.lua, frontend/device/kobo/device.lua, frontend/device/kobo/nickel_conf.lua, frontend/device/kobo/powerd.lua, frontend/ui/uimanager.lua, kodev, platform/kobo/koreader.sh, platform/kobo/nickel_suspend_strace.txt, platform/kobo/suspend.sh, reader.lua, spec/unit/nickel_conf_spec.lua
* Depends on [base#387](/koreader/koreader-base/pull/387)
* Add some more logging & comments to the suspend script, because this shit is mystical.
* Unbreak shutting down the frontlight on suspend (broken in #1854). This possibly needs reviewing, because the new code didn't make any kind of sense to me (cf. my commit msg).
=> Minor Kobo tweaks

reader.lua
fix https://github.com/koreader/koreader/issues/1876
=> fix: delay showReader after UIManager:run is called

kodev
depends on https://github.com/koreader/koreader-base/pull/394
This PR also picks up the new optimization @frankyifei made in crengine. I am summarizing the discussion on gitter here so we can have a reference for the next stable release's changelog:
1. replace FNV1-a hash with xxhash for in caching module. For large epubs, about 50% speed up on page turns and 10-20% speed up on initial loading.
2. enable caching for books with count>20000 or text count>20000. books with all sizes should benefit from caching now.
3. remove LVDocView::updateBookMarksRanges() in goToPage call, which saved 3-4 seconds on page turn in large epubs.
=> bump bump bump

frontend/apps/reader/modules/readerfooter.lua, frontend/document/credocument.lua, frontend/ui/widget/progresswidget.lua, reader.lua, spec/unit/readerfooter_spec.lua
fix https://github.com/koreader/koreader/issues/1905
=> fix toc marks in footer progress bar

frontend/device/kobo/nickel_conf.lua
fix https://github.com/koreader/koreader/issues/1910 and https://github.com/koreader/koreader/issues/1902, relies on https://github.com/koreader/koreader-base/pull/395
=> fix(credocument): bump base to fix empty text search crash

.ci/script.sh, frontend/apps/reader/modules/readerbookmark.lua, frontend/device/android/device.lua, frontend/device/generic/device.lua, frontend/device/input.lua, frontend/device/kobo/device.lua, reader.lua, spec/unit/device_spec.lua, spec/unit/touch_probe_spec.lua, spec/unit/util_spec.lua, utils/kobo_touch_probe.lua, utils/wbuilder.lua
=> kobo: fix screen probe for touch

plugins/statistics.koplugin/main.lua
Thanks to https://github.com/koreader/koreader/commit/7a22282dbe63337fedad4d8d15adf0dc1e095bad#commitcomment-16954114
=> Fix statistics translation

frontend/ui/widget/bookstatuswidget.lua
This should fix the issue Ken mentioned in https://github.com/koreader/koreader/issues/1941#issuecomment-205792476
=> bookstatus(fix): reset self.stats on init

utils/kobo_touch_probe.lua
fix https://github.com/koreader/koreader/issues/1608
=> touch_probe(fix): do not filter probe touch event by range

frontend/device/kobo/device.lua
And bump base for the SSLv2 & misc build fixes.
Depends on base/402
=> Alays wake the H2O IR grid on wakeup

frontend/ui/widget/virtualkeyboard.lua
This issue has been discussed at #1945
=> Use Screen:scaleBySize to auto scale virtual keyboard size

platform/kindle/koreader.sh
=> Some Kindle startup script fixes

frontend/ui/widget/filechooser.lua
Bug #1966
This change merges logic in filechooser, and provides a list function to list, do the filtering, with same manner.
You can find a screenshot with this fix @ https://raw.githubusercontent.com/Hzj-jie/files/master/koreader/b1966/correct.png, and compare to existing behavior @ https://raw.githubusercontent.com/Hzj-jie/files/master/koreader/b1966/wrong.png
=> *.sdr folders are not excluded in folder item count

frontend/device/kindle/powerd.lua, reader.lua
AFAICT, no regression on Kobo, but I haven't tested it thoroughly...
=> Assorted FrontLight fixes ;)

.ci/after_success.sh, Makefile, frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/ui/widget/bookstatuswidget.lua, frontend/ui/widget/progresswidget.lua, spec/unit/readerrolling_spec.lua, spec/unit/widget_menu_spec.lua, spec/unit/widget_progresswidget_spec.lua, test/sample.txt
This should fix https://github.com/koreader/koreader/issues/1975
=> fix end of book detection for crengine

.editorconfig, .gitignore, Makefile, README.md, spec/unit/readersearch_spec.lua
Currently it can open cre-based docs and Djvu docs
It still has some problems with PDF docs and the touch input.
=> experimental port to Mac OSX

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerview.lua, kodev, spec/unit/readerfooter_spec.lua, spec/unit/readerlink_spec.lua, spec/unit/widget_progresswidget_spec.lua
=> progressbar(fix): persist progressbar visibility

frontend/ui/widget/scrolltextwidget.lua, spec/unit/device_spec.lua
=> Support page keys in dictionary window

platform/kobo/koreader.sh
Takes care of some potentially critical stuff ;p
=> Update Kobo startup script for KFMon

frontend/device/generic/device.lua, frontend/device/input.lua, frontend/device/kobo/device.lua, frontend/ui/uimanager.lua
Please don't merge. At the moment I'm looking for feedback.
The idea is to be able to power off the device directly from koreader. I'm adding this mostly because there's no other way to power off when running my okreader firmware (https://github.com/lgeek/okreader), but it also works on regular Kobo installations using Start Menu.
Between my relative unfamiliarity with koreader and my relative unfamiliarity with lua, I expect this to be less than optimal. And I guess it might be desirable only to enable this on Kobo devices.
Any feedback on how to improve this so it could eventually be merged?
=> RFC: Offer to power off if the power button is held for at least 3 seconds

README.md, frontend/apps/reader/modules/readercropping.lua, frontend/ui/data/creoptions.lua, frontend/ui/data/koptoptions.lua, frontend/ui/widget/configdialog.lua, frontend/ui/widget/toggleswitch.lua
This change was created for issue #1923, but we have these settings in menu already. So I removed duplicated settings, but leave only multi-line toggle switch and sdcv build error instruction changes.
=> Multi-line toggle switch & add instruction to resolve sdcv build error.

frontend/apps/reader/modules/readerhighlight.lua, frontend/ui/data/creoptions.lua
=> rename 'Highlight' to 'Highlight options' in menu

frontend/device/kobo/device.lua, platform/kobo/koreader.sh
Depends on base#422
(Hopefully) fix #2005
Bump base to fix base#421
And some Kobo startup script tweaks for #1996
=> Assorted tweaks

README.md, frontend/device/input.lua, frontend/device/kobo/device.lua, kodev, spec/unit/device_spec.lua
fix https://github.com/koreader/koreader/issues/630
=> automatically set proper ev timeval for kobo touch

.gitignore, frontend/apps/filemanager/filemanager.lua, frontend/ui/uimanager.lua, spec/unit/uimanager_spec.lua
Also fixes the bug that generates wrong filename for screenshots.
=> fix bug in UIManager:handleEvent

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerfilesearcher.lua, frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/filemanager/filemanagersearch.lua, frontend/apps/filemanager/filemanagersetdefaults.lua, frontend/apps/reader/modules/readerfrontlight.lua, frontend/apps/reader/modules/readergoto.lua, frontend/apps/reader/readerui.lua, frontend/dump.lua, frontend/ui/widget/bookstatuswidget.lua, frontend/ui/widget/buttontable.lua, frontend/ui/widget/container/inputcontainer.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/multiinputdialog.lua, spec/unit/defaults_spec.lua
changes:
* added screensaver folder setting dialog for kobo
* refactor defaults module, removed the hack to lookup defaults variables from global. Still have many more to clean up
* simplified the interface for inputDialog a little bit
=> defaults(refactor): remove global hack in filemanagersetdefaults

frontend/ui/uimanager.lua, kodev, spec/unit/nickel_conf_spec.lua, spec/unit/screenshoter_spec.lua
Not sure why it only breaks on 16.04.
=> Fix unit test on ubuntu 16.04

frontend/docsettings.lua
This change eventually resolves two issues,
1. When a file has been renamed, it's sidecar file won't be renamed.
2. We are still writing to legacy history folder.
To the first issue, I have updated sidecar folder from file-name-without-suffix.sdr to file-name-with-suffix.sdr, and sidecar file name from file-name-with-suffix.lua to .lua. So we won't need to rename the sidecar file anymore, simply renaming the sidecar folder is enough.
To the second issue, I disallow writing to legacy history folder if writing to sidecar file succeeded.
=> Refine docsettings, does not write history folder if it's not necessary

.ci/script.sh, frontend/apps/filemanager/filemanager.lua, frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/readerui.lua, frontend/dbg.lua, frontend/docsettings.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/textboxwidget.lua, frontend/util.lua, spec/unit/docsettings_spec.lua, spec/unit/filemanager_spec.lua, spec/unit/readerbookmark_spec.lua, spec/unit/readerui_spec.lua, spec/unit/textboxwidget_spec.lua, spec/unit/util_spec.lua
related to https://github.com/koreader/koreader/issues/2054
refactored filemanager a little bit and fixed the first issue reported in https://github.com/koreader/koreader/issues/2062.
=> readerfooter(fix): only populate footer info after document is loaded

frontend/ui/uimanager.lua, spec/unit/uimanager_spec.lua
=> uimanager(fix): handle edge case where second widget in stack is ignored

frontend/device/pocketbook/device.lua
=> handle auto shutdown in pocketbook

frontend/ui/widget/dictquicklookup.lua
=> restrict dictionary window inside of screen especially in landscape mode

frontend/apps/reader/modules/readerdictionary.lua, frontend/ui/uimanager.lua, spec/unit/uimanager_spec.lua
close https://github.com/koreader/koreader/issues/2062
=> uimanager(fix): handle stack change in close

frontend/device/input.lua, frontend/ui/uimanager.lua
So LOL, timeout_s is ignored in watiEvent...
fix https://github.com/koreader/koreader/issues/2050.
=> uimanager(fix): honor second when calling Input:waitEvent

frontend/apps/reader/modules/readerdictionary.lua, frontend/ui/widget/closebutton.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/textboxwidget.lua, frontend/util.lua, spec/unit/util_spec.lua
=> split accient greek words with spacing character

frontend/device/input.lua, frontend/device/kindle/device.lua
=> add inactive touch zones around buttons on Kindle Voyage

frontend/apps/filemanager/filemanager.lua, frontend/ui/widget/filechooser.lua
A tiny change to resolve issue #2012.
=> Add folder name in file manager

frontend/ui/widget/textwidget.lua
This change resolves the issue that path name in FileManager won't update in Kobo.
=> TextWidget should set dirty region in setText function

frontend/apps/reader/modules/readeractivityindicator.lua, frontend/device/kindle/device.lua, platform/kindle/libkohelper.sh
White PW3 is trivial.
I'm fairly confident in the various Oasis knobs (based on kernel/system logs, I don't have the device).
The KT3 (Basic 2) stuff is pure conjecture, though.
Depends on base#441
=> Support the White Kindle PaperWhite 3 & the Kindle Oasis

frontend/apps/reader/modules/readerview.lua
* setup autoSaveSettings callback on ReaderReady event
* delay calling autoSaveSettings with UIManager:nextTick
=> reader(fix): fix crash when DAUTO_SAVE_PAGING_COUNT is set to 0

frontend/device/kindle/device.lua
'Cause I got them wrong the first time ;).
=> Fix a few Kindle device codes

frontend/apps/reader/modules/readerstatus.lua, frontend/document/credocument.lua, frontend/document/djvudocument.lua, frontend/document/document.lua, plugins/statistics.koplugin/main.lua
=> book reading statistics for djvu documents

frontend/device/kindle/device.lua
Still unsure if the touchscreen input device is correct, though.
=> Fix KT3 battery sysfs entries

defaults.lua, frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/filemanager/filemanagersetdefaults.lua, frontend/apps/reader/modules/readerpaging.lua, spec/unit/defaults_spec.lua, spec/unit/readerhighlight_spec.lua, spec/unit/readerlink_spec.lua, spec/unit/readerpaging_spec.lua, spec/unit/readerview_spec.lua
close https://github.com/koreader/koreader/issues/2157
relies on https://github.com/koreader/koreader-base/pull/445
=> set scroll mode as default

frontend/ui/widget/scrolltextwidget.lua
fix https://github.com/koreader/koreader/issues/2166
=> scrolltextwidget(fix): add moveCursor method

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerview.lua, spec/unit/readerfooter_spec.lua
fix https://github.com/koreader/koreader/issues/2172.
=> footer(fix): avoid setting mini footer to invisible when full progress bar is on

frontend/device/kindle/device.lua
There's an extra controller in there screwing things up for us,
because reasons, I guess?
Fix #2181
=> Fix touch input on the 3G KOA

frontend/device/generic/device.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/network/manager.lua
Discussed in issue #2184. Feel free to reject this PR if you guys have a better solution.
=> Add a network info page

frontend/device/kindle/device.lua
It's a zforce2 IR grid...
Fix #2195
=> Fix KT3 input device

frontend/device/kobo/device.lua, platform/kobo/nickel.sh, platform/kobo/suspend.sh
Because it'd been a while :D.
This unfortunately doesn't fix the broken zforce resume I'm seeing, so that workaround is still in place.
=> Some more Kobo scripts tweaks

.gitignore, .luacheckrc, frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua, frontend/ui/screensaver.lua, frontend/ui/widget/touchmenu.lua
fix https://github.com/koreader/koreader/issues/2198
changes:
* bug fix in touchmenu widget
* move all screensaver related menu items into setting tab
* add menu item to enable screensaver folder
=> bring back toggle to enable screensaver folder

plugins/kosync.koplugin/main.lua
Also see https://www.transifex.com/houqp/koreader/translate/#nb_NO/koreader/64792760?issue=yes
=> kosync: improve a couple of strings

frontend/docsettings.lua, frontend/readhistory.lua, spec/unit/docsettings_spec.lua, spec/unit/readhistory_spec.lua
This change adds readhistory_spec and docsettings_spec, and fixed several bugs in readhistory / docsettings
=> Add readhistory_spec / docsettings_spec

frontend/device/kobo/device.lua
The viewport definition might not be 100% correct.
=> Aura One support

plugins/kosync.koplugin/KOSyncClient.lua, plugins/kosync.koplugin/main.lua, spec/unit/kosync_spec.lua
1. Two new settings, whisper sync to the latest record / whisper sync to a previous record
2. Use timestamp to decide the latest record instead of progress
3. Respect auto-saving setting
4. Sync timeout to 1s
=> This is the implementation of whisper sync

frontend/apps/reader/modules/readerfont.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/ui/widget/progresswidget.lua, spec/unit/readerlink_spec.lua, spec/unit/readerrolling_spec.lua
fix https://github.com/koreader/koreader/issues/2262
=> Fix readerrolling PageUpdate event

Makefile, kodev
depends on https://github.com/koreader/koreader-base/pull/459 and https://github.com/koreader/android-luajit-launcher/pull/45
=> kodev fixes and bump base/luajit-launcher

Makefile, kodev
depends on https://github.com/koreader/koreader-base/pull/460 and https://github.com/koreader/android-luajit-launcher/pull/46
=> build: fix android and pocketbook builds

.gitignore
=> Exclude *.un~ (vim undo file) from git

Makefile, kodev, platform/kindle/koreader.sh, platform/kobo/koreader.sh, platform/pocketbook/koreader.app, reader.lua
1. disable wifi on exit
2. fix crash.log rotation
3. change package name for legacy kindle build
4. update translations in kodev release comand
=> minor changes

frontend/apps/reader/modules/readerhighlight.lua
This is a quick fix to #2294. I also find this feature practically needed.
=> allow disable highlight by default

plugins/statistics.koplugin/main.lua
* Add reading statistics: https://github.com/koreader/koreader/issues/2299
* Statistics / All Books shows only currently opened book : https://github.com/koreader/koreader/issues/2170
* Fix incorrect time: https://github.com/koreader/koreader/issues/2298
=> Extend and fix statistics

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerhistory.lua
Issue: #578 and display document metadata in the history.
=> display document metadata

plugins/statistics.koplugin/main.lua
I added 3 new positions in "Current book" statistics:
- Current pages
- Today period
- Today pages
I also fixed calculation time for books.
=> Extend current book statistics and fix bugs

frontend/ui/widget/readerprogress.lua, plugins/statistics.koplugin/main.lua, plugins/statistics.koplugin/readerprogress.lua
I added reading progress page in statistics submenu.
Reading progress page shows last week progress in chart.
=> Create reading progress page

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerzooming.lua, kodev, spec/unit/readerfooter_spec.lua, spec/unit/readerlink_spec.lua
Various bug fixes and optimizations. The main change is to try do as much stuff as possible during the initial setting phase so that the main draw logic (hot path) is dead simple.
progress_bar setting has been removed since I don't really know what's the use-case for it.
fix https://github.com/koreader/koreader/issues/2303
=> footer refactoring

frontend/apps/reader/modules/readerview.lua
=> Make page gap configurable

frontend/ui/widget/listview.lua, frontend/ui/widget/networksetting.lua, platform/kobo/release-ip.sh, spec/unit/networksetting_spec.lua
depends on https://github.com/koreader/koreader-base/pull/463
fix https://github.com/koreader/koreader/issues/2293
=> network(fix): automaticallly obtain IP if network is already authenticated

frontend/apps/filemanager/filemanager.lua
Us humans can handle spaces in titles.
=> Properly spell the title of the file manager

Makefile, datastorage.lua, frontend/ui/widget/dictquicklookup.lua, kodev, reader.lua, setupkoenv.lua
Preparation for sqlite3 support
=> add setupkoenv.lua

frontend/ui/widget/opdsbrowser.lua
This commit fix problem with OPDS catalog for "Wolne Lektury" (http://wolnelektury.pl/opds).
"Wolne Lektury" is the biggest Polish catalog of free e-books (over 4,000).
=> OPDS - fix opds catalog for Wolne Lektury

frontend/apps/reader/modules/readerstatus.lua
=> Add new setting: auto_book_status

.ci/after_success.sh, frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readerpaging.lua, spec/unit/readerpaging_spec.lua, spec/unit/readhistory_spec.lua
fix with some minor optimizations
also fix https://github.com/koreader/koreader/issues/2367
=> readerpaging(fix): handle edge cases where paging pan will crash the reader

doc/Hacking.md, kodev, tools/wbuilder.lua
Continues the work of 9afad43a3ea781e98895fadbd85fac3fa42d2f45
=> Finish renaming `utils` to `tools`

frontend/ui/network/manager.lua, frontend/ui/otamanager.lua, plugins/evernote.koplugin/main.lua, plugins/kosync.koplugin/main.lua
fix https://github.com/koreader/koreader/issues/2355
=> fix: disable network info menu when device is not connected

frontend/ui/widget/textboxwidget.lua
Fix #2126 (hold on a word on the 2nd page of a definition was triggering lookup of the word at the same place in 1st page).
I'm new to git and github, so i'm practicing with a small one.
Dunno where to ask that, so i'm asking here :
I made a few enhancements for my own usage these last weeks, and feel like giving back. How should I proceed :
1) write somewhere (where? a generic issue ?) what i have, so you can tell me early if you want them ?
2) create an issue for each, describing why and what I did with screenshots, let people comment and decide, for eventually coding and make a PR with the agreed stuff ?
3) create a PR for each with my existing code (including questions in comments where I need feedback), and we'll have the discussion there ?
Also, I have more comments in my patches …
=> Fix selection in dictionary window (#2126)

frontend/apps/reader/modules/readerdictionary.lua, frontend/ui/elements/screen_dpi_menu_table.lua
These 2 simple changes helped me actually enjoy koreader on my high-dpi screen with my old age sight
=> Make koreader more useful on high-DPI screen (PW3 300dpi)

frontend/apps/reader/modules/frontlight.lua, frontend/apps/reader/modules/readerfrontlight.lua, frontend/ui/widget/frontlightwidget.lua
I prepared new frontlight widget. It should be easer to change frontlight in KO.
I'm not sure whether I put file frontlight.lua.
On generic devices:
On Kindle:
=> Frontlight progress bar

frontend/ui/widget/frontlightwidget.lua
Fix: https://github.com/koreader/koreader/pull/2385#issuecomment-264402071
Thanks @houqp
=> Fix: prog_button does not honor self.fl_min

frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/modules/readertoc.lua, frontend/device/generic/device.lua, frontend/ui/uimanager.lua, frontend/ui/widget/imagewidget.lua, frontend/ui/widget/networksetting.lua, platform/kobo/disable-wifi.sh
The Network info commit would have to be checked on other devices than Kobo (possible different output from linux commands, or even commands not available on some systems).
=> Various fixes (#2394)

frontend/apps/reader/modules/readerlink.lua
Allow swipe west to jump to current page's first link (easier than clicking on small links)
=> Added "Swipe to follow first link" option (#2392)

frontend/ui/widget/frontlightwidget.lua
Fix: https://github.com/koreader/koreader/pull/2396#issuecomment-264796894
=> Fix: prevent step_min lower than fl_min

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/scrolltextwidget.lua, frontend/ui/widget/textboxwidget.lua, frontend/ui/wikipedia.lua, frontend/util.lua, spec/unit/util_spec.lua
Feedback wanted on ReaderDictionary:cleanSelection():
It looks a bit heavy and redundant, but all that was needed to clean some french book selections (well, may be it could work with 1 or 2 gsub less, but i was tired testing :)
Dunno if there may be some side effects with other languages.
Selection of multiple words in TextBoxWidget:onHoldReleaseText() seems fine on western languanges, but needs to be checked on chinese or japanese texts (should be at least not worse on single word than the old Hold method).
=> Dictionary and wikipedia enhancements (#2393)

frontend/optmath.lua, frontend/ui/geometry.lua, frontend/ui/widget/container/inputcontainer.lua, frontend/ui/widget/listview.lua, frontend/util.lua
Fairly random as I was just browsing; nothing planned or coordinated.
=> Doc: miscellaneous improvements.

frontend/apps/reader/modules/readertypeset.lua, frontend/ui/otamanager.lua, frontend/ui/widget/menu.lua, plugins/calibrecompanion.koplugin/main.lua
Use uppercase for some menu entries that appear in lowercase in some menus.
OTA channel -- **S**table / **D**evelop
Set render style -- **C**lear all external styles
Tools -- **C**alibre wireless connection
Message error when opening bookmarks list when there is not any bookmarked pages in the book:
**N**o choices available
=> Some uppercase fixes

frontend/device/kobo/device.lua
Cf. https://github.com/koreader/koreader/issues/2418#issuecomment-267447810
=> Kobo: fix Kobo Aura second edition highlighting

frontend/util.lua
Followup from #2417 
> BTW, your CJK patches looks good to me, feel free to send a PR. I can help fix the unit tests. Today I learned that some of the characters in Japanese are not splitable :P
Implemented line breaking rules from :
https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages
including the few japanese "Characters that can't be separated".
Note : I couldn't cut & paste the 4th character from this wikipedia page:
Korean `Characters that are not allowed at the end of a line :$([\{£`...
which appears as a \ in my paste ... so i let it out.
The existing unit tests may not fail, but they are not checking for the new breaking rules. So, you may extend the existing one or add new ones.
=> textboxwidget: enhanced CJK text wrapping

plugins/goodreads.koplugin/doublekeyvaluepage.lua, plugins/goodreads.koplugin/main.lua
https://www.transifex.com/houqp/koreader/translate/#nb_NO/koreader/102219198
https://www.transifex.com/houqp/koreader/translate/#nb_NO/koreader/102219164
=> Language: fixed a couple of Transifex issues

frontend/ui/widget/textboxwidget.lua
fix #2434 and avoid strange things when holding from/to outside dimension.
Also fix crash when tap (move cursor) in an inputtext with no text at all.
@houqp : this fix should be best, but while looking at code, I first thought about giving the right textboxwidget region area to the hold range in dictquicklookup:
https://github.com/koreader/koreader/blob/master/frontend/ui/widget/dictquicklookup.lua#L116
so that onHold methods don't get called at all if outside.
But i found no real way to get to that textboxwidget object, and to get its drawn position (dynamically determined by all its containers at paint time). Did I miss some existing code/method for that ?
=> textboxwidget: added some sanity checks

frontend/apps/reader/modules/readerrolling.lua
potential fix for https://github.com/koreader/koreader/issues/2432 and https://github.com/koreader/koreader/issues/2425
=> fix: migrate readerrolling to touch zones

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readermenu.lua, frontend/ui/widget/container/inputcontainer.lua
fix https://github.com/koreader/koreader/issues/2432
=> override reader menu touch zone with reader footer

frontend/apps/cloudstorage/cloudstorage.lua, frontend/apps/cloudstorage/dropbox.lua, frontend/apps/cloudstorage/dropboxapi.lua, frontend/apps/cloudstorage/ftp.lua, frontend/apps/cloudstorage/ftpapi.lua, frontend/apps/filemanager/filemanagermenu.lua
I prepared KO integration with dropbox and ftp. After configuration we can list and download books from dropbox and ftp servers.
Similar FR #2165. 
In the future maybe I'll add googledrive and onedrive (now I don't know it is possible)
Here are a few screenshot:
=> Cloud storage - dropbox and ftp integration

frontend/apps/filemanager/filemanager.lua
=> Fix #2440 - Crash when selecting Book information on images

frontend/apps/cloudstorage/cloudstorage.lua, plugins/zsync.koplugin/main.lua
Unsubscribe from was suggested by Allan Nordhøy (kingu) on Transifex.
=> Minor language fixes

frontend/apps/filemanager/filemanagermenu.lua
Implements: #2415 
close #2415
=> Open last book in file manager

frontend/apps/reader/modules/readerfrontlight.lua, frontend/ui/widget/filechooser.lua, frontend/ui/widget/frontlightwidget.lua
fix https://github.com/koreader/koreader/issues/2439
=> feat: new setting to show opened book name in bold

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerview.lua, frontend/optmath.lua, frontend/ui/widget/widget.lua, plugins/statistics.koplugin/main.lua
Also optimize startup time by using `widget:extend` instead of `widget:new`.
=> Make readerview extensible by plugins

plugins/perceptionexpander.koplugin/main.lua
=> #2447 Perception expander plugin (Improve peripheral vision)

.ci/script.sh, frontend/apps/reader/modules/readermenu.lua, frontend/ui/opdsparser.lua, frontend/ui/widget/filechooser.lua, frontend/ui/widget/opdsbrowser.lua, plugins/keepalive.koplugin/main.lua, spec/unit/opds_spec.lua
also rename show_opened_doc_in_bold setting to show_file_in_bold
fix https://github.com/koreader/koreader/issues/2458
=> feat: support disable show file name in bold

plugins/statistics.koplugin/main.lua
With this change, we can also retrieve statistics of "All Books", or update settings of the plugin.
=> Update statistics plugin to support docless mode

plugins/storagestat.koplugin/main.lua, plugins/timesync.koplugin/main.lua
This change adds a plugin to display the storage usage of the device.
=> StorageStat plugin

plugins/evernote.koplugin/main.lua
This PR changes EvernoteExporter to support docless mode, i.e. it's now working in FileManager.
But unfortunately, this plugin has not be maintained for a while, it still uses very old history folder, which is deprecated. Another change will be sent out later to update the logic.
=> EvernoteExporter plugin can be docless

frontend/ui/widget/menu.lua
close #2326 
This commit should fix problem that file manager forgets the current page.
=> Fix #2326 (The file manager forgets the current page)

frontend/apps/reader/modules/readerwikipedia.lua
Issue: #2428 
When launching the Wikipedia from the tools menu or after selecting a word in the book, if the device is offline, you get the ask for connection like when a OTA update is requested while offline.
=> Ask for connection when clicking on Wikipedia

plugins/storagestat.koplugin/main.lua
Improves the output of StorageStat to make it more intuitive and user-friendly.
=> StorageStat: Improve Output (#2486)

plugins/perceptionexpander.koplugin/main.lua
Thanks to @kingu on Transifex. Fixes #2482.
=> Fix "line thick" typo to "line thickness" (#2482)

frontend/ui/elements/common_settings_menu_table.lua, plugins/keepalive.koplugin/main.lua, plugins/storagestat.koplugin/main.lua
Issue #2466 
I have also added a dummy implementation for SDL for debugging purpose.
=> Add checked tag for keepalive plugin

frontend/docsettings.lua
Get back "metadata." part forgotten while refactoring.
Fix #2509
=> Fix sidecar file name

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readermenu.lua, frontend/depgraph.lua, frontend/device/kobo/device.lua, frontend/ui/widget/container/inputcontainer.lua, spec/unit/commonrequire.lua, spec/unit/depgraph_spec.lua, spec/unit/eink_optimization_spec.lua, spec/unit/gesturerange_spec.lua, spec/unit/httpclient_spec.lua, spec/unit/kosync_spec.lua, spec/unit/opds_spec.lua, spec/unit/spore_spec.lua, spec/unit/widget_inputcontainer_spec.lua
fix https://github.com/koreader/koreader/issues/2479.
changes:
* touch zone dependency handling logic is rewritten from scratch for bug fixes
* change touch event handling behavior, now event won't stop propagation until one handler returns true
* move all unit test setup into setup function
* remove all echo shell out in kobo suspend function
=> fix footer hold touch handler

frontend/ui/screensaver.lua, frontend/ui/widget/bookstatuswidget.lua, frontend/ui/widget/iconbutton.lua, frontend/ui/widget/imageviewer.lua, frontend/ui/widget/imagewidget.lua, plugins/goodreads.koplugin/goodreadsbook.lua
Closes #2505.
Provides ability with gestures (no button added, so no space wasted) to zoom (pinch & spread, pageup/pagedown with keyboard) & pan (swipe, hold, pan) images.
The ImageWidget:_render() section has a bit too many if/then to account for incompatibilities in the options. As it is, it should be fully compatible with the existing options.
I let in some comments for discussion.
As of now, usage of ImageWidget in other parts of code is:
1) most uses: just a filename, no other option => returns a blitbuffer the size of the native image
2) iconbutton: filename + autoscale => returns a blitbuffer the size of the native image, or 2x this size for high DPI screen
3) screensaver images from files: screen width+height + autostretch => image scaled (aspect ratio kept) to fit width & height …
=> ImageViewer: added zoom & pan via gestures

frontend/apps/reader/modules/readerlink.lua
Discussion on https://www.transifex.com/houqp/koreader/translate/#nb_NO/koreader/106518021
@Frenzie Second option is I came to too. Very consistent and nice.
by kingu, 6 minutes ago
Let's see, I'm not entirely happy with the phrase. Here are a couple of brainstorms.
Would you like to read the full version of this Wikipedia EN article?
Would you like to read this Wikipedia EN article?
by Frenzie, an hour ago
@kingu It's the language code, such as EN, FR, etc.
http://imgur.com/u1q6tT4l.png
by Frenzie, an hour ago
ISSUE
What is %1 here?
by kingu, 3 days ago
=> Language: Would you like to read this Wikipedia %1 article?

frontend/apps/filemanager/filemanager.lua, frontend/ui/widget/filechooser.lua, frontend/util.lua
This change adds sorting by access time, modification time, change time, file type, file size functions in file manager. Though the times are impacted by OS, which may not so accurate, it's better than nothing.
=> More sorting orders in file manager

plugins/kobolight.koplugin/main.lua
=> fix overrides for plugin_kobolight_tap

frontend/apps/filemanager/filemanager.lua
Fixes #2550
Cf. b50204763542212ccd35c7b1903dfee62d4af16e
=> FileManager: rename hasSidecarDir to hasSidecarFile

frontend/ui/widget/filechooser.lua
More information regarding the file!
=> Use a smaller font to display the filename

reader.lua
=> Minor: don't turn off wifi on exit

frontend/ui/widget/filechooser.lua
#2568 introduced an up arrow but broke actually going up :blush:
=> FileManager: fix up arrow issue

plugins/timesync.koplugin/main.lua
=> Ask for connection when clicking on TimeSync while offline

frontend/ui/widget/bookstatuswidget.lua
=> Fix #2176 - Wrong book's review and rating stars are shown

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerhistory.lua, frontend/readhistory.lua
Fixes the problem introduced in 51327911f2fbea00258717d7b284e061ad31832e and turns it into a feature that should fix #2477
=> FileManagerHistory: remove harmful deletion code and turn it into a feature

README.md
Most people will be looking for the emulator info first, so put it on top. Fixes #2595
=> README.md: add automake and improve clarity

frontend/ui/widget/touchmenu.lua
Reverts koreader/koreader#2572
=> Revert "TouchMenu: keep file/exit button on the right"

reader.lua
=> Dialog when reopening book at start (#2259)

kodev
=> kodev: correct "luarocks path bin" to "luarocks path --bin" and miscellaneous ShellCheck code quality issues

Makefile, frontend/device/input.lua, frontend/device/kobo/device.lua, frontend/docsettings.lua, kodev, spec/unit/docsettings_spec.lua
Putting the code out here for early review. I am still testing this myself and please help test it too if you can :)
For https://github.com/koreader/koreader/issues/2520 and https://github.com/koreader/koreader/issues/2239
=> handle unexpected wakeup on kobo

plugins/kobolight.koplugin/main.lua
Which was increasing after each opening of a document.
Closes #2605
=> Fix KoboLight sensitivity

frontend/apps/reader/modules/readerfooter.lua
Helps following KOReader memory usage (and memory leaks).
As discussed in comments after 20170115 in #2239
=> Footer: added "memory usage" item

frontend/ui/widget/opdsbrowser.lua, frontend/util.lua
=> Fix crash when downloading books with unknown characters in title

frontend/ui/widget/opdsbrowser.lua
=> opds(fix): avoid infinite loop on paging

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerfooter.lua, frontend/ui/network/wpa_supplicant.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/wikipedia.lua
=> decouple reader footer from dictquicklookup widget & translation fix

frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/readerui.lua
close https://github.com/koreader/koreader/issues/2548
=> fix: adjust pan rate for eink and non-eink screens

frontend/apps/filemanager/filemanagerfilesearcher.lua
=> FileSearcher: filter .sdr directories

frontend/apps/reader/modules/readermenu.lua
=> ReaderMenu: fix MenuSorter-related typo

frontend/ui/widget/button.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/touchmenu.lua, plugins/kosync.koplugin/main.lua
Meanwhile, tap_input is not enough in both Button and TouchMenu, this change also adds tap_input_func.
=> InputDialog is broken by #2672

frontend/apps/reader/modules/readerfooter.lua
=> ReaderFooter: fix tapping footer to browse in flipping mode

frontend/gettext.lua
=> gettext: unescape quotation mark

frontend/ui/widget/infomessage.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/textboxwidget.lua, frontend/util.lua, spec/unit/util_spec.lua
* Fixed up all of util and added when absent
* Updated widget examples to new coding style
=> Developer documentation improvements 

frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/menusorter.lua, spec/unit/menusorter_spec.lua
What I thought was a problem in busted was actually a problem in the code. Apparently I never sufficiently tested the non-recursive function.
=> MenuSorter: fix findById

frontend/ui/uimanager.lua
I went in because "quiting" annoyed me but I ended up adding a bunch of docs.
=> UIManager docs & lang: add some docs and correct "quiting" to "quitting"

frontend/apps/reader/modules/readerdictionary.lua
crengine now does a much better job at finding word boundaries, so there's no more need for much cleanup.
I let in commented some code to remove some diacritical marks, see discussion in #1649 . But as i have no way to check if that works (no diacritical marks in the languages, texts and dictionaries i understand/read/have), I let people who can try that and tell us.
=> clean ReaderDictionary:cleanSelection

.ci/after_success.sh, .ci/helper_luarocks.sh, .ci/helper_shellchecks.sh, .ci/install.sh, .ci/script.sh, .gitignore, .travis.yml, platform/kindle/kotar_cpoint, platform/pocketbook/koreader.app
I can only check this stuff locally to a certain extent, so let's see what happens.
Edit: okay, we've got a regular "Ran for 14 min 1 sec" (not 15 mins 'cause I last-minute tacked on caching of luarocks compilation in #2712 which made me realize I wanted to do this PR right here).
Edit 2:  okay, success ("Ran for 10 min 12 sec").
Edit 3: no coverage on non-official master branch means "Ran for 7 min 11 sec"
Edit 4: cached .luarocks seems to make basically no difference because of the extra time spent packing and unpacking the cache. "Ran for 6 min 56 sec". But since I recall a lot of timeouts in that area it's probably not a bad idea to keep it in.
=> Travis: speed up by caching base and running luacheck earlier

frontend/apps/reader/modules/readerfooter.lua, frontend/ui/widget/container/framecontainer.lua, frontend/ui/widget/progresswidget.lua
fix https://github.com/koreader/koreader/issues/2361
=> bring back support for disabling progressbar in footer

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua, frontend/device/kindle/device.lua
for partially revert https://github.com/koreader/koreader/pull/2734
=> revert code that enables screensaver on kindle by default

.ci/after_success.sh, .ci/before_install.sh, .ci/common.sh, .ci/helper_luarocks.sh, .ci/helper_shellchecks.sh, .ci/install.sh, kodev, platform/kindle/extensions/koreader/bin/koreader-ext.sh, platform/kindle/koreader.sh, platform/kindle/kotar_cpoint, platform/kindle/libkohelper.sh, platform/kobo/disable-wifi.sh, platform/kobo/enable-wifi.sh, platform/kobo/koreader.sh, platform/kobo/nickel.sh, platform/pocketbook/koreader.app, platform/ubuntu-touch/koreader.sh
* enormous coding style update
* update luajit-launcher
All changes are formatting only except for:
* new more correct pushd/popd style
* keeps useful indentation
* prevents execution of commands when pushd failed (cf. https://github.com/koalaman/shellcheck/wiki/SC2164 and koalaman/shellcheck#863)
```bash
pushd some_dir && {
command1
command2
} || exit
popd
```
=> Travis: enforce shellscript coding style

platform/kobo/koreader.sh
Thanks to @a-kohout
Fixes #2752
=> Kobo (koreader.sh): install OTA update in working directory

doc/Collaborating with Git.md, doc/Events.md, doc/Hacking.md, doc/Porting.md, frontend/device/gesturedetector.lua, frontend/document/documentregistry.lua, frontend/ui/menusorter.lua, frontend/ui/translator.lua
* Content from wiki had some cosmetic leftover glitches
* Added/adapted some docs for other modules
=> Docs: cosmetic updates and additions

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerconverter.lua, frontend/apps/filemanager/lib/md.lua
Here's a little something I've been playing around with. It's actually the backend for the upcoming quickstart guide but I made a little GUI around it as well. The idea is to extend it to tap into Docverter via wifi to do a few more conversions (as opposed to actually bundling pandoc, although… we include freaking OCR so why not pandoc :-P).
=> FileConverter added with local Markdown to HTML conversion

frontend/apps/reader/modules/readerfooter.lua
=> Fix: Frontlight level in Status bar in Kobos without light

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua, frontend/device/generic/device.lua, frontend/device/kindle/device.lua, frontend/device/kobo/device.lua, frontend/ui/screensaver.lua
Similar to #2734 but screensaver is available only on devices without Special Ofers.
@NiLuJe Thanks for advice.
Tested on my Kindle PW2 without SO (screensaver works) and PW3 with SO (screensaver isn't available).
=> Screensaver on Kindle without Special Offers

frontend/apps/reader/modules/readerfont.lua
Increase and decrease font size with pinch and spread gesture.
Tested on my KPW3.
Reference: #2701
=> Pinch gesture for changing font size

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua, frontend/apps/reader/readerui.lua, frontend/pluginloader.lua, frontend/ui/uimanager.lua
for https://github.com/koreader/koreader/issues/2790
=> catch crash error in plugin

platform/kobo/koreader.sh
=> (chore) koreader.sh: remove 32-bit workaround

frontend/document/koptinterface.lua
Fixes #2805. Thanks to @poire-z, see https://github.com/koreader/koreader/issues/2805#issuecomment-296686695
=> Fix garbled ImageWidget cache issues

frontend/apps/reader/modules/readerdictionary.lua, frontend/util.lua
=> ReaderDictionary: add info message about installing dictionaries

frontend/apps/reader/modules/readerhyphenation.lua
It makes no sense to have both, so setting a default removes the fallback, and setting a fallback removes the default.
Also save hyph_alg to document settings only if it has been manually chosen, so that later changes to default or fallback can be used.
Discussion at https://github.com/koreader/koreader/issues/2476#issuecomment-297995328
=> Allow for setting a default or fallback hyph dictionary

plugins/goodreads.koplugin/goodreadsbook.lua
Thanks @poire-z for pointing this out. REF: https://github.com/koreader/koreader/pull/2870#discussion_r115196528
=> goodreads(fix): remove incorrect image_disposable setting

frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, plugins/newsdownloader.koplugin/feed_config.lua, plugins/newsdownloader.koplugin/main.lua
News downloader - support for Atom.
=> News downloader atom support

frontend/apps/reader/modules/readerdictionary.lua, frontend/ui/network/wpa_supplicant.lua
Fix https://github.com/koreader/koreader/issues/2864
=> wifi(fix): quote ssid and password for wpa_passphrase

frontend/apps/filemanager/filemanager.lua, frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/widget/dictquicklookup.lua
Closes #2883. Closes #2884.
Also allow taking screenshot when on dictionary window: Closes #2248.
=> Allow wikipedia lookup from filemanager

plugins/newsdownloader.koplugin/main.lua
Ability to select custom download folder
=> News Downloader: Select Custom download folder

frontend/apps/reader/modules/readerview.lua
=> ReaderView: add long-press to set default

frontend/ui/language.lua
fix https://github.com/koreader/koreader/issues/2918
=> language: remove out of date Russian translation

frontend/device/android/powerd.lua, frontend/device/kindle/powerd.lua, frontend/device/kobo/powerd.lua
Several changes of legacy codes were not included.
=> Crash errors

frontend/device/generic/powerd.lua, frontend/device/kobo/powerd.lua
This should fix https://github.com/koreader/koreader/issues/2974.
=> Fix frontlight nickel synchronizing issue caused by change #2941

spec/unit/readerlink_spec.lua
* crengine: return description and keywords metadata
Only available for EPUB documents for now. @poire-z
* crengine: css related improvements, fix crash, better handling of gif @frankyifei
=> Bump base: crengine update

frontend/apps/reader/modules/readerfont.lua
This patch allows increase or decrease font size (pinch gesture) by more than 1 at a time like in native kindle operating system (#2914). It is possible increase/decrease font size from 1 to 5.
=> Font zooming more than 1

frontend/device/kindle/device.lua
Should prevent crash liblipclua.
See: #3018 and https://github.com/koreader/koreader/pull/2757#discussion_r128628462
=> Prevent liblipclua crashes

plugins/goodreads.koplugin/goodreadsbook.lua
Enable text justification in GoodReads review.
Before:
After:
=> Text justification in GoodReads review

frontend/ui/widget/keyvaluepage.lua
Close: #2863 
Arrows at the bottom for turning pages:
=> KeyValuePage navigation buttons

plugins/readtimer.koplugin/main.lua
* no timeout on alarm
* autoclose menu when starting timer
* show time in menu when active
=> Read timer: various improvements

frontend/ui/wikipedia.lua
Fix download of some relative urls images.
(Llike hieroglyphs on https://fr.wikipedia.org/wiki/Horus, which have a relative url like `src="/w/extensions/wikihiero/img/hiero_G5.png?bcb90"`)
=> Wikipedia save as epub: fix some image download failures

frontend/device/kindle/device.lua, platform/kindle/libkohelper.sh
Model number either `0LK` or `0LL`
See discussion in https://www.mobileread.com/forums/showthread.php?p=3565878#post3565878
=> [Kindle] Add support for Kindle PW3 "manga" model

plugins/newsdownloader.koplugin/main.lua
* Fixes #3041 (HTTPS)
* Fixes unlimited (limit = 0) was broken
* Fixes titles and links with attributes
=> Newsdownloader: add HTTPS support and fixes

frontend/apps/reader/modules/readerconfig.lua
See comment: https://github.com/koreader/koreader/pull/3051#issuecomment-322044755
=> readerconfigmenu(fix): override pan gesture from scrolling

frontend/ui/widget/configdialog.lua
See comment: https://github.com/koreader/koreader/pull/3051#issuecomment-322058846
=> Swipe down to close config menu

frontend/device/generic/device.lua, frontend/device/kindle/device.lua, frontend/device/kobo/device.lua, frontend/device/pocketbook/device.lua, frontend/device/sdl/device.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, frontend/ui/widget/timewidget.lua
Reference: https://github.com/koreader/koreader/issues/2265
Now it's possible to setup clock in KO. Tested on Kindle. Should work on Pocketbook and Kobo.
=> Ability to setup clock

frontend/docsettings.lua, spec/unit/docsettings_spec.lua
In case of any failure when writing docsettings, this change reserves the last good docsettings file.
=> Reserve last good docsettings

frontend/apps/filemanager/filemanager.lua
Notified of destructive action without confirmation in https://www.mobileread.com/forums/showthread.php?p=3566978#post3566978
=> [UX] FileManager: add ConfirmBox for purge .sdr

frontend/ui/widget/checkmark.lua, frontend/ui/widget/horizontalgroup.lua, frontend/ui/widget/overlapgroup.lua, frontend/ui/widget/textwidget.lua, frontend/ui/widget/touchmenu.lua, frontend/ui/widget/verticalgroup.lua
=> [UX] Add CheckMark and use in TouchMenu checkable indicator

frontend/ui/widget/textboxwidget.lua, frontend/ui/widget/textwidget.lua, plugins/coverbrowser.koplugin/listmenu.lua, plugins/coverbrowser.koplugin/mosaicmenu.lua
2 small modifications to textwidget and textboxwidgets, and cleanup of workarounds in coverbrowser plugin
=> Small mods to core related to coverbrowser

frontend/ui/widget/checkbutton.lua, frontend/ui/widget/checkmark.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/inputtext.lua, tools/wbuilder.lua
#3040 made me realize a simple checkmark GUI widget is missing. However, I think I may have introduced some kind of gesture/input faux pas but I probably won't have time to look into that for a couple of days.
=> [UX] Add CheckButton and use it for show password

frontend/apps/reader/modules/readertypeset.lua
Because why not ? (and so that we can see which one is currently used)
=> Use checkmarks with Set render style items

README.md
includes git merge fun! (sorry for that ...)
=> fixes #3069 and #3116

frontend/ui/widget/imageviewer.lua
=> ImageViewer: fix rotation angle in landscape mode

plugins/statistics.koplugin/main.lua
https://github.com/koreader/koreader/pull/2893#issuecomment-325721541
=> database name change to statistics.sqlite3

frontend/apps/reader/modules/readerdictionary.lua
This adds a new dictionary settings menu, with each installed dictionary name, in the order they are used by sdcv, and allows for disabling some of them (this is done by renaming the .ifo file by appending `_Disabled_by_KOReader` to it).
(So I can disable the big greek and latin dictionaries that I don't need for most books: it speeds my fuzzy lookups from 10s to 2s).
=> Dict settings menu: list dictionaries, and allow disabling them

frontend/ui/plugin/background_task_plugin.lua, frontend/ui/plugin/switch_plugin.lua, plugins/autofrontlight.koplugin/main.lua, spec/unit/background_task_plugin_spec.lua, spec/unit/switch_plugin_spec.lua
Similar logic has been implemented for several plugins. It should be better to share the logic.
=> SwitchPlugin and BackgroundTaskPlugin with tests

frontend/apps/reader/modules/readerdictionary.lua
See https://github.com/koreader/koreader/pull/3144#discussion_r136590043
=> Fix "Info on dictionary order" string for translation

frontend/ui/widget/dictquicklookup.lua
=> Fix: Crash when highlight a word

frontend/device/kindle/device.lua
This may resolve this problem: #1934
It works on my KPW3 with SO. Screen is redrawn after exit from KO.
=> Refresh Kindle with SO on exit

frontend/ui/menusorter.lua, spec/unit/menusorter_spec.lua
See https://github.com/koreader/koreader/pull/3167#issuecomment-326805768
=> [fix] MenuSorter: take care of orphaned submenus

frontend/apps/reader/modules/readerdictionary.lua
=> [fix] Dict settings NaN in installed dicts submenu

frontend/ui/screensaver.lua, frontend/ui/uimanager.lua, spec/unit/uimanager_spec.lua
=> [fix, UX] Allow modal widget on top of modal widget

plugins/statistics.koplugin/main.lua
This should fix: https://github.com/koreader/koreader/issues/3185#issuecomment-327877844
=> Fix problem with import old .stat files

plugins/statistics.koplugin/main.lua
On monthly statistics now we can see the daily statistics from the whole month. Just tap on the month you want.
Statistics by month aren't limited to 10 years.
=> On monthly statistics we can see the daily stats

frontend/apps/reader/modules/readerhighlight.lua
This would allow holding a bit longer on a word to access directly the buttons table (the one we get when we select more than 1 word) and avoid a dict lookup.
Useful when we hold on a person/location name that we know is not in our dictionary, to access directly the Wikipedia link.
Could be useful too when we add more items to this highlight menu (we may not want to add them to the bottom of the dictquicklookup for clarity).
The 3 seconds delay is a bit too much for me, but it should prevent the other slow-holders out there being surprised not having their dict lookup result :)
=> Hold on a word for more than 3 seconds to access highlight menu and avoid the dict lookup

frontend/apps/reader/modules/readermenu.lua, frontend/device/input.lua, frontend/device/sdl/event_map_sdl2.lua
Depends on https://github.com/koreader/koreader-base/pull/506
=> [SDL] Add quit through regular window manager actions

plugins/statistics.koplugin/main.lua
See: https://github.com/koreader/koreader/pull/2893#issuecomment-328364416
=> Disable Current book when statistics are disabled

frontend/apps/reader/modules/readerfont.lua, frontend/apps/reader/modules/readerhighlight.lua
As suggested by @comradekingu in https://github.com/koreader/koreader/pull/3165#issuecomment-326795203
=> [UX] Document settings language simplification

frontend/apps/reader/modules/readerlink.lua
=> Fix wrong page when tap on link

frontend/ui/widget/bookstatuswidget.lua, plugins/statistics.koplugin/main.lua
Close: #3196 (Statistics at the end of book isn't synched with new statistics thus empty).
=> Synchronize new statistics with "Book status"

frontend/ui/widget/multiinputdialog.lua, plugins/statistics.koplugin/main.lua
Close: #3186 (Statistics settings get reset to default when you just save them)
=> Fix: #3186

frontend/device/kobo/powerd.lua
=> Fix crash on exit on Kobo devices with no frontlight

kodev
Also improve SDK installation for ease of setting up development system.
This also puts in place most of the missing pieces to finish the intent in #3064.
=> [Android] Update to NDK 15

frontend/ui/widget/numberpickerwidget.lua, frontend/ui/widget/spinnerwidget.lua, frontend/ui/widget/timewidget.lua
New widget - SpinnerWidget (I can't find better name :) )
Refactoring code for TimeWidget (I used SpinnerWidget).
=> Refactor TimeWidget and add SpinnerWidget

frontend/device/kindle/device.lua, frontend/device/kobo/device.lua, frontend/device/pocketbook/device.lua, frontend/device/sdl/device.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/widget/datewidget.lua, frontend/ui/widget/numberpickerwidget.lua
Close: #2265 
See: https://github.com/koreader/koreader/pull/3085#issuecomment-322291560
It's work in emulator and Kindle.
=> Add a date setting

frontend/ui/widget/dictquicklookup.lua
This boosts perceived performance of KOReader by a factor of 2 ! :)
=> Reduce unhighlight delay when closing dict

spec/unit/readerlink_spec.lua
crengine crashes, rendering and selection delay fix by @frankyifei, https://github.com/koreader/crengine/pull/86
Closes #3187. Closes #3192
=> Bump base for crengine bump

plugins/statistics.koplugin/main.lua
See comment: https://github.com/koreader/koreader/issues/3236#issuecomment-331632571
=> Book information for all books

plugins/statistics.koplugin/main.lua
Reported by [@jony08](https://www.transifex.com/user/profile/jony08/) on Transifex.
> It make take a few minutes. -> It may take a few minutes.?
=> [fix] statistics: typo

Makefile, frontend/device/android/device.lua, frontend/device/android/powerd.lua, frontend/device/generic/device.lua, frontend/gettext.lua, platform/android/llapp_main.lua
reflect changes in koreader/android-luajit-launcher#62 and hide navigation bar on start for Android.
=> reflect changes in koreader/android-luajit-launcher#62

plugins/newsdownloader.koplugin/feed_config.lua
Adapt ND to changes in code (bug/feature?) where 0 means no limit (instead of previous "no download") + reorganize config, improved comments
=> Adapt ND to changes in code (bug/feature?) where 0 means no limit

frontend/apps/filemanager/filemanager.lua, frontend/ui/widget/configdialog.lua, frontend/ui/widget/iconbutton.lua, frontend/ui/widget/touchmenu.lua
Tap to go HOME. Hold to set current folder as HOME. When no HOME is set yet tap also asks to set current folder as HOME.
See https://github.com/koreader/koreader/issues/2957#issuecomment-308513062
Closes #3200.
=> [UX] Add home button

plugins/coverbrowser.koplugin/main.lua, plugins/coverbrowser.koplugin/xutil.lua
I was reminded by @KenMaltby that this is disabled on Android.
https://www.mobileread.com/forums/showthread.php?p=3586162#post3586162
@poire-z Is there anything specific I should try to see if this is problematic? It seems to work just fine.
=> [Android] Enable CoverBrowser

frontend/apps/filemanager/filemanager.lua
Prevent crash when set HOME directory.
=> Avoid crash when set as home directory

frontend/apps/filemanager/filemanager.lua, frontend/ui/widget/iconbutton.lua
Also fix path display update.
Fixes #3270.
=> [fix] Add hold_callback to IconButton

plugins/coverbrowser.koplugin/bookinfomanager.lua
=> CoverBrowser: use MuPDF for down-scaling images

frontend/apps/reader/modules/readerbookmark.lua
Close: #3226
When hold bookmark we can now change it name.
=> Rename bookmarks name

plugins/readtimer.koplugin/main.lua
Oh, I completely forgot about it.
Now we have read timer like in #3032.
=> Time reader with normal time format v2

frontend/ui/elements/screen_color_menu_table.lua, reader.lua
See https://github.com/koreader/koreader/pull/3285#issuecomment-333464382 and following comments.
=> Inform once about color rendering on supported devices

frontend/device/pocketbook/device.lua, frontend/device/pocketbook/powerd.lua
Enable frontlight-support for Pocketbook840 via libinkview.
=> Pocketbook840 enable frontlight

frontend/apps/reader/modules/readerhighlight.lua
Closes #3305. Solution 1) in https://github.com/koreader/koreader/issues/3305#issuecomment-334732632
=> Fix crash on highlight in some situations

plugins/statistics.koplugin/main.lua
=> [statistics] Refresh footer

plugins/readtimer.koplugin/main.lua
See: https://github.com/koreader/koreader/pull/3279#issuecomment-334813582
=> [ReadTimer] Time from now

frontend/ui/widget/keyvaluepage.lua
Similar flash like tap on button or menu item.
I'm not sure that this is too expensive:
`UIManager:setDirty("all", 'ui')`
pinging @poire-z for help :)
=> Flash KeyValuePage item when callback

spec/unit/readerfooter_spec.lua
My bad, leftover from #3323 but not caught due to some Travis → CircleCI migration birth pains.
=> Fix readerfooter_spec

plugins/statistics.koplugin/main.lua
Too-quick fix in #3304, corrected. Thanks @robert00s !
=> Fix stats in cre scroll mode

.ci/after_success.sh
I wrote this whole complicated wofkflow-based config file, but except
in the case of a base rebuild it wouldn't really be any faster than
this simple tweak.
```yml
defaults: &defaults
docker:
- image: houqp/kobase:0.0.5
environment:
EMULATE_READER: 1
LC_ALL: en_US.UTF8
version: 2
jobs:
install-and-build:
<<: *defaults
steps:
- checkout
- restore_cache:
keys:
- deps-{{ arch }}-{{ checksum ".ci/install.sh" }}
- run: git submodule init base && git submodule update base && pushd base && git submodule init && git submodule update && popd
- run: pushd base && git_rev_base=$(git describe HEAD) && popd && echo $git_rev_base && echo $git_rev_base >git-rev-base
- restore_cache:
keys:
- build-{{ arch }}-{{ checksum "git-rev-base" }}
- run: echo 'export PATH=${HOME}/bin:${PATH}' >> $BASH_ENV
- run: …
```
=> CircleCI: run docs & coverage in first container only

.ci/after_success.sh, .ci/helper_luarocks.sh, .circleci/config.yml, README.md
The debug output from Coveralls was rubbish. `"Build processing error"`
Besides some basics like checking if we were actually sending
valid JSON that gives us absolutely nothing to work with.
=> [CI] Switch to Codecov

README.md
Improved some stylistic issues.
* Updated Travis CI reference to CircleCI.
* Switched to CircleCI "shield" style badge to fit in better with the other badges.
=> README: style updates

plugins/goodreads.koplugin/doublekeyvaluepage.lua, plugins/goodreads.koplugin/main.lua
+ add navigation button (next, prev) on the bottom of screen
+ flash item when selecting
+ small lookup improvements
+ fix refresh "Please wait..."
=> [Goodreads] lookup improvement

frontend/document/djvudocument.lua, frontend/document/document.lua
See https://github.com/koreader/koreader-base/pull/546#issuecomment-336674759 and around.
Needs base bump for https://github.com/koreader/koreader-base/pull/547
=> djvu: enable color rendering

frontend/device/kobo/device.lua
Cf. ongoing discussion in KSM8 thread: https://www.mobileread.com/forums/showthread.php?p=3596020#post3596020
=> [Kobo] Add preliminary Kobo Aura H2O2 definition

kodev
=> kodev: add debug flags

frontend/apps/filemanager/filemanagerbookinfo.lua, frontend/ui/widget/filechooser.lua, frontend/util.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua
See https://github.com/koreader/koreader/pull/3380#issuecomment-338217140
=> Added util.getFriendlySize()

frontend/device/android/device.lua, frontend/ui/network/manager.lua
https://github.com/koreader/android-luajit-launcher/pull/65 enables android wifi management.
This is Koreader implemention part that make use of above
Not tested. Testers welcome.
=> Android Wifi Manager

frontend/ui/elements/screen_fullscreen_menu_table.lua
@mwoz123 This is on me merging prematurely but I hope you understand that I'm not just trying to be obstructionist. :-)
=> [fix, Android] adjust touch location for #3392

plugins/newsdownloader.koplugin/main.lua
Handling wifi in NewsDownloader. 
Not tested. Testers welcome.
=> News downloader wifi handling

frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/skimtowidget.lua, frontend/ui/widget/button.lua
https://github.com/koreader/koreader/issues/2819#issuecomment-332261968
+ refactoring code in skimtowidget
+ add chapter markers
+ add next/prev chapter buttons
+ add next/prev bookmark buttons
=> New Skim to widget

frontend/ui/widget/dictquicklookup.lua
=> Fix dict title width to not go over CloseButton

plugins/readtimer.koplugin/main.lua
=> [readtimer] Separate strings for singular and plural

datastorage.lua
See https://github.com/koreader/koreader/pull/3424#discussion_r146994306
=> DataStorage: also create data/tessdata and minor string concat performance improvements

plugins/newsdownloader.koplugin/feed_config.lua, plugins/newsdownloader.koplugin/main.lua
=> News downloader: use feed.description as news context instead download full web page

datastorage.lua, plugins/newsdownloader.koplugin/main.lua
#3422 
TODO: fix line 319 :
`self.ui.document._document.filename` is always null.
@Frenzie can you help?
=> Remove news downloader files from Koreader history 

frontend/apps/reader/modules/readerfooter.lua, frontend/device/android/device.lua, frontend/ui/network/manager.lua
Display Wifi status (On/Off) in reader footer.
Not tested yet.
=> [w.i.p.] wifi status in footer

plugins/newsdownloader.koplugin/main.lua
Prompt to turn off wifi after download.
Extracted from #3388
=> News downloader: wifi off prompt after download

frontend/ui/widget/configdialog.lua
+ Fix height for ToggleWidget
+ Able ToggleWidget width more than half of width of screen
=> ConfigDialog improvements 2

frontend/ui/widget/dictquicklookup.lua
=> Disable Highlight button when text is not selected

frontend/ui/data/koptoptions.lua, frontend/ui/widget/buttonprogresswidget.lua, frontend/ui/widget/configdialog.lua
Close: #2133 
More info: #2133
=> More contrast settings

frontend/device/pocketbook/device.lua
Hopefully this PR fixes https://github.com/koreader/koreader/issues/3452. I am not quite sure about the DPI though.
=> Add PocketBook626

frontend/apps/reader/modules/readermenu.lua
* Add enabled_func on relevant settings
Fixes https://github.com/koreader/koreader/issues/3470
=> [UX] Always show screensaver menu in reader

frontend/device/kobo/device.lua
See https://www.mobileread.com/forums/showpost.php?p=3610605&postcount=24 for evtest output.
=> [Kobo] Update H2O2 to nearly working touch.

frontend/apps/reader/modules/readerhighlight.lua, frontend/device/generic/device.lua, frontend/device/sdl/device.lua
References https://github.com/koreader/koreader/issues/3441
Depends on https://github.com/koreader/koreader-base/pull/572 (not merged yet)
=> [feat] Add Device:hasClipboard()

frontend/ui/widget/configdialog.lua
See https://github.com/koreader/koreader/pull/3463#issuecomment-345076873
Also implement most conservative fix to wide toggleswitches from https://github.com/koreader/koreader/pull/3455#issuecomment-345075200 (which may be superceded by a more proper fix)
=>  Fix live refresh when changing pdf contrast 

frontend/apps/filemanager/filemanagerhistory.lua
=> Disable Purge .sdr and Delete for currently opened book

frontend/ui/widget/bookstatuswidget.lua
=> Fix bookstatuswidget window truncated at the bottom in landscape

kodev
Fixes https://github.com/koreader/koreader/issues/3504.
=> [fix] kodev: grep filter debug/no-debug dir

frontend/device/kobo/device.lua
See https://github.com/koreader/koreader/issues/2418#issuecomment-346287297
=> kobo/device: adjust KoboStar (Aura 2) viewport

frontend/device/pocketbook/device.lua
=> Added Pocketbook 624 alias Basic Touch

frontend/apps/filemanager/filemanager.lua
=> [Fix] actually use 'reverse_collate' saved setting

frontend/device/pocketbook/device.lua
Fix https://github.com/koreader/koreader/issues/3539
=> Add PB623 alias Touch Lux

frontend/apps/filemanager/filemanagerbookinfo.lua, frontend/ui/widget/keyvaluepage.lua, plugins/statistics.koplugin/main.lua
Close: #3515 
Now it looks like this:
=> Better keyvaluepage align in reading statistics

frontend/document/pdfdocument.lua
Needed for https://github.com/koreader/koreader-base/pull/577.
Closes #3519.
=> MuPDF 1.12

frontend/document/pdfdocument.lua
=> cbt support (#3533)

README.md
Was added in https://github.com/koreader/koreader/pull/3554
=> README: add CBT to list of supported formats

frontend/apps/filemanager/filemanager.lua
Close: #2637 (Can't delete Folder containing epub or pdf)
=> Remove not empty folder

frontend/apps/filemanager/filemanager.lua
Close: #1777
Details: https://github.com/koreader/koreader/issues/1777#issuecomment-282018013
=> copying file with .sdr

frontend/apps/filemanager/filemanager.lua
See:
https://github.com/koreader/koreader/pull/3571#issuecomment-355418296
https://github.com/koreader/koreader/pull/3575#issuecomment-355421170
https://github.com/koreader/koreader/pull/3555#issuecomment-355496118
=> Fix missing createFolder() function and fix File Browser is no more tapable

frontend/ui/widget/dictquicklookup.lua
See https://github.com/koreader/koreader/pull/3573#issuecomment-355903214
=> Fix: scale html dict result font size

frontend/ui/widget/dictquicklookup.lua
See https://github.com/koreader/koreader/pull/3573#issuecomment-355949796
=> Dict: make html and text results look similar

frontend/ui/widget/scrollhtmlwidget.lua
See https://github.com/koreader/koreader/pull/3585#issuecomment-356389498
=> Fix scroll with swipe in scrollhtmlwidget

plugins/goodreads.koplugin/doublekeyvaluepage.lua
=> DoubleKeyValuePage: make PgUp and PgDown key go to prev/next page (GoodReads)

frontend/apps/filemanager/filemanager.lua, frontend/util.lua
=> Fix folder path in filemanager

frontend/ui/widget/opdsbrowser.lua
See comment: https://github.com/koreader/koreader/pull/3571#issuecomment-354768385
=> OPDS - add confirm when file exist in local destination

frontend/apps/reader/modules/readerlink.lua, frontend/ui/elements/reader_menu_order.lua
=> [UX] Move "Go back to previous location" up one menu level

frontend/ui/widget/filechooser.lua
See: https://github.com/koreader/koreader/pull/3614#issuecomment-359071939
=> Sort documents - open sidecar file only in percent sort

frontend/luasettings.lua
Similar to what was done for docsettings in #3093 (will apply to settings.reader.lua, but also to plugins' own settings).
Had it since after my early MuPDF 1.12 kobo crashes, and it has recovered once when I had wrongly manually edited settings.reader.lua.
=> luasettings: backup previous file and auto-recover

frontend/ui/wikipedia.lua
https://fr.wikipedia.org/wiki/Figure_de_la_Terre saved as EPUB would give 46 pages like this:
<kbd>![math_bad](https://user-images.githubusercontent.com/24273478/35523487-44c29000-051f-11e8-9da2-ffd7d9322924.png)</kbd>
With this PR, it gives a more readable 26 pages epub with pages like these:
<kbd>![math_good](https://user-images.githubusercontent.com/24273478/35523518-53824770-051f-11e8-90d7-6ba01cae721c.png)</kbd><kbd>![math_good2](https://user-images.githubusercontent.com/24273478/35523523-55a0ad80-051f-11e8-945f-6f352d544bde.png)</kbd>
(I don't read maths, but I don't like  to read nearly blank pages either :)
Also fix some bad filenames and extensions in epub's `OEBPS/content.opf` (which didn't bother crengine, but let's have it right):
Before:
```
<item id="img00037" …
```
=> Wiki Save as EPUB: better handling of math formulas

plugins/newsdownloader.koplugin/internaldownloadbackend.lua
Fix http 301 handling Reuters full download bug #3596 
That was by misunderstanding removed from #3618 pr
=> News downloader : Fix http 301 handling Reuters full download bug. 

plugins/newsdownloader.koplugin/main.lua
Show Message with details when invalid configuration.
=> NewsDownloader: Message with details when invalid configuration.

frontend/ui/widget/container/inputcontainer.lua, frontend/ui/widget/filechooser.lua, frontend/ui/widget/menu.lua
Instead of the page number we go to the page with the name of the file/dir beginning with the character or string of characters in current folder.
More info: #3029.
Closes: #3029
=> Go to letter - File manager

frontend/apps/reader/modules/readerlink.lua
See https://github.com/koreader/koreader/pull/3669/files#r167394249
=> [fix, lang] ReaderLink: change location stack to location history

plugins/kobolight.koplugin/main.lua
* Variables must be inserted into strings with util.template (or in rare cases string.format)
* Sentences should be as complete as possible and not cleverly constructed through code.
=> [i18n, fix] KoboLight plugin: fix up text issues

plugins/kobolight.koplugin/main.lua
My bad, I meant to test #3665 (which I typed on GH) but forgot about it.
=> [fix] KoboLight: typo

frontend/apps/cloudstorage/dropboxapi.lua, frontend/apps/cloudstorage/ftpapi.lua, frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerfilesearcher.lua, frontend/apps/filemanager/filemanagersearch.lua, frontend/document/documentregistry.lua, spec/unit/document_registry_spec.lua
As suggested by @poire-z https://github.com/koreader/koreader/pull/3653#issuecomment-364663156
=> [fix] DocumentRegistry: don't create empty sdr and add hasProvider()

frontend/apps/reader/modules/readerfont.lua
Fixes #2686 
Depends on https://github.com/koreader/koreader-base/pull/600
=> [fix] larger max font size for crengine

frontend/document/documentregistry.lua, frontend/ui/widget/checkbutton.lua, frontend/ui/widget/openwithdialog.lua, frontend/ui/widget/radiobutton.lua, frontend/ui/widget/radiobuttontable.lua
=> [feat, UX] Add new OpenWithDialog based on RadioButton and RadioButtonTable

frontend/device/android/device.lua
Fixes https://github.com/koreader/koreader/issues/3441
In anticipation of the feature being added to luajit-launcher. Don't merge yet.
=> Add Android clipboard definition

frontend/ui/widget/inputtext.lua
See https://github.com/koreader/koreader/issues/3441
=> [UX] Paste on hold

frontend/device/kindle/device.lua, platform/kindle/libkohelper.sh
Screen refresh may still be broken.
References #3695.
=> [Kindle] Add preliminary support for Kindle Oasis 2

spec/unit/input_spec.lua
I'm not entirely sure what the best way to test this is, but here's a quick stab at something.
=> [spec] Input test stub

frontend/device/kobo/device.lua, frontend/device/kobo/powerd.lua, frontend/device/kobo/sysfs_light.lua
See https://www.mobileread.com/forums/showpost.php?p=3664352&postcount=66
Pinging @dengste for review.
=> [feat, Kobo] Add H2O2 natural light

plugins/coverbrowser.koplugin/bookinfomanager.lua
Forgot to do it in https://github.com/koreader/koreader/pull/3732
=> Set default 'cre_storage_size_factor' also in coverbrowser

plugins/coverbrowser.koplugin/bookinfomanager.lua
Correct https://github.com/koreader/koreader/pull/3750#pullrequestreview-104592546
=> coverbrowser: fix some texts

frontend/apps/reader/modules/readerhighlight.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua
in some InfoMessage and ConfirmBox, introduced willingly or not, that cause top or bottom padding
=> Remove some leading and trailing newlines

frontend/apps/reader/modules/readerwikipedia.lua
See https://github.com/koreader/koreader/pull/3762#pullrequestreview-104772416
=> Fix some texts

frontend/apps/filemanager/filemanagermenu.lua
As it was done for ReaderMenu in #3595.
=> FileManagerMenu: show tab from gesture position

frontend/ui/network/manager.lua
=> [fix] NetworkManager:isConnected() exit code check

plugins/coverbrowser.koplugin/xutil.lua, setupkoenv.lua
I have this problem where covermenu can't find z.
This commit fix it, and work on sdl, but I have no idea about other device.
What's the best way to go about this ?
=> Fix libz on kindle4

frontend/apps/reader/modules/readerback.lua, frontend/apps/reader/readerui.lua, frontend/util.lua, spec/unit/inputtext_spec.lua
This implements a reasonable facsimile of going back on Android.
The back button first goes back in a history of visited pages.
When there's no history left, it closes the app.
Fixes #3816.
=> [feat] Add ReaderBack

frontend/device/input.lua, frontend/device/sdl/device.lua, frontend/device/sdl/event_map_sdl2.lua
The specifics for other implementations are easy to change in the backend.
=> [feat, UX] SDL: add Gtk3 filechooser

frontend/device/pocketbook/device.lua
Fixes #3687
Thanks to @Maradar for testing, see https://github.com/koreader/koreader/issues/3687#issuecomment-378652074
=> [PocketBook] Add Inkpad 3 (PB740) definition

Makefile, datastorage.lua, frontend/ui/quickstart.lua, kodev, platform/appimage/AppRun, platform/appimage/koreader.appdata.xml, platform/appimage/koreader.desktop
=> [feat] Build AppImage

platform/appimage/koreader.desktop, platform/ubuntu-touch/koreader.desktop
As per https://standards.freedesktop.org/menu-spec/latest/apa.html
Reference:
https://github.com/AppImage/appimage.github.io/pull/510
=> Add Categories= key

setupkoenv.lua
That way it's always available.
Refrences #3853
=> [chore] setupkoenv: output some info about library loading

setupkoenv.lua
As per https://github.com/koreader/koreader/issues/3853#issuecomment-380521086
=> [chore] Always io.write ffi.load error message

frontend/apps/filemanager/filemanagersetdefaults.lua
Reported on the forum by roger64: https://www.mobileread.com/forums/showthread.php?t=296184
=> [fix] AppImage advanced settings location

platform/appimage/AppRun
Output is a bit verbose otherwise, see https://github.com/koreader/koreader/issues/3853#issuecomment-381098701
=> platform/appimage/AppRun: remove debug flag

README.md
=> README: add new logo and links from koreader.rocks homepage

platform/kobo/enable-wifi.sh, platform/kobo/nickel.sh
Regression after bdb82d09c176bcb46197d9286a193748c5ce3e2e
TL;DR: That thing is race-y as hell.
The more I play with Kobos, the more it feels like the whole thing's
held together by pieces of fraying strings...
~~Should fix #3888~~
=> Fix WiFi on Kobo

frontend/ui/otamanager.lua
Drop outdated mirror
Relocate mine, and give them actually accurate names given their location
=> Update OTA mirrors

plugins/goodreads.koplugin/goodreadsbook.lua
See comment: https://github.com/koreader/koreader/pull/3929#issuecomment-386680636
=> [GoodReads Plugin] Use RenderImage:renderImageData instead of Pic.openJPGDocumentFromMem

frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, frontend/ui/network/manager.lua, plugins/SSH.koplugin/main.lua
PR on base : https://github.com/koreader/koreader-base/pull/640
TODO: 
1. Go to [here](https://github.com/koreader/koreader-base/pull/640), download the right zip and run it.
2. Go to : Gear > Network > SSH server and try to start the ssh server.
3.  If no error, try to connect to the ssh server `root@<ip> -p 2222`
4. If it work, nice, please just post in this PR.
5. Else, post the log in this PR, thanks.
closing : https://github.com/koreader/koreader/issues/3810
=> [Done] Integrated SSH server

frontend/ui/data/creoptions.lua
See comment: https://github.com/koreader/koreader/pull/3952#issuecomment-390392139
=> Fix show current and default values in config dialog

plugins/readtimer.koplugin/main.lua
Close: #3959 
Add default to the last value used (or current left time) in ReadTimer -> Minutes from now.
=> Add default to the last value used in ReadTimer

frontend/device/kobo/device.lua
c.f. https://www.mobileread.com/forums/showpost.php?p=3702997&postcount=291
=> Kobo Clara HD support

frontend/apps/reader/modules/readerstatus.lua
=> Automatically exit to file browser after finishing reading quick start guide

frontend/ui/widget/notification.lua
Includes:
- Fix drawing position of bottom and right borders https://github.com/koreader/crengine/pull/211
Also let tap propagate when a Notification is displayed. See https://github.com/koreader/koreader/pull/3962#issuecomment-396997531 and follow-ups.
=> bump crengine: fix drawing position of bottom and right borders

frontend/device/kobo/device.lua, frontend/ui/screensaver.lua, platform/kobo/disable-wifi.sh, platform/kobo/enable-wifi.sh, platform/kobo/fmon/README.txt, platform/kobo/koreader.sh, platform/kobo/nickel.sh
Fairly minor stuff.
Fun fact: I get working WiFi immediately after restarting to Nickel now. Might be FW 4.8.whatever, though. Or might be gremlins, who knows.
=> Assorted bag of fixes

plugins/send2ebook.koplugin/main.lua
adapt to changes #3924 in ftp.lua
=> Send2ebook fix download after refactor from #3924 

frontend/device/kindle/device.lua, frontend/device/kobo/device.lua, frontend/document/credocument.lua, kodev, platform/kobo/disable-wifi.sh, platform/kobo/enable-wifi.sh, platform/kobo/nickel.sh
Hopefully :).
Plus a bunch of minor fixes (Clara FL, kodev)
Fix #3600 
Re #4021 
Re #4015
=> Fix KOA2 support

frontend/ui/data/css_tweaks.lua
I'm not sure if this is a good place :)
=> style tweaks - ignore publisher hyphenate

plugins/statistics.koplugin/readerprogress.lua
See comment: https://github.com/koreader/koreader/pull/4058#issuecomment-403118792
=> Fix display Reading progress in statistics plugin in landscape

plugins/SSH.koplugin/main.lua
Delayed hostkey gen, platfrom specific stuff.
=> Minor dropbear tweaks

frontend/apps/filemanager/filemanagerfilesearcher.lua, frontend/apps/filemanager/filemanagermenu.lua
Close: #2957 
First version. Detail: https://github.com/koreader/koreader/issues/2957#issuecomment-406281987
=> Add search in home folder

plugins/SSH.koplugin/main.lua
'Fix' #4104 (as well as we can).
=> Fix scp & sftp on Kobo/Kindle

platform/kindle/extensions/koreader/bin/koreader-ext.sh
The update option was broken
[skip ci]
=> Tweak KUAL extension

frontend/device/generic/device.lua
that's not full-screen (i.e., "message" ScreenSaver mode).
Fix #4098
=> Don't rotate on suspend for Kobo/PB when we're showing something new

platform/kobo/koreader.sh
Wild-ass experiment switching to conservative instead of userspace (because, well, there's no userspace anymore :D).
Note that my H2O seems to grandly ignore all of that crap and switch freq all on its own anyway, so this may be a giant NOP.
=> CPUFreq shenanigans on Kobo

frontend/apps/filemanager/filemanager.lua, frontend/document/documentregistry.lua
Open random book from current folder and from unreaded documents.
Close: #3543
=> Open random document

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerutil.lua
=> [fix] Don't crash when trying to go to deleted folders

frontend/ui/screensaver.lua
Details: https://github.com/koreader/koreader/issues/4117#issuecomment-408678266
=> Show hidden dirs and files in Choose screensaver image

frontend/pluginloader.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua
=> Remove Storage statistics from menu

plugins/texteditor.koplugin/main.lua
Fix review comments around https://github.com/koreader/koreader/pull/4135#issuecomment-410823170
=> TextEditor: fix some wording

frontend/apps/filemanager/filemanager.lua
Cf. https://github.com/koreader/koreader/pull/4140#issuecomment-412261195
=> FileManager typography: dashes to en-dashes

frontend/ui/widget/opdsbrowser.lua
=> Change title and button text in OPDS

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerbookmark.lua, frontend/apps/filemanager/filemanagershortcuts.lua
=> Folder favorites

frontend/ui/uimanager.lua
Original comment went poof in 229c5ad61cfa81b16ae1fd00d8f8823f3171b513
=> Reinstate the comment explaining the fiddling with regions in UIManager

frontend/apps/cloudstorage/cloudstorage.lua, plugins/zsync.koplugin/main.lua
=> Show hidden dirs in Choose Cloud and ZSync inbox

frontend/ui/widget/button.lua, frontend/ui/widget/buttonprogresswidget.lua
Similar to toggleswitch widget.
Close: #4218
=> Setting contrast on non-touch devices

frontend/apps/reader/modules/readergoto.lua, frontend/apps/reader/skimtowidget.lua
See: https://github.com/koreader/koreader/issues/3526#issuecomment-420940012
After changes:
=> Change skim mode dialog title

frontend/ui/widget/touchmenu.lua
=> Fix touchmenu unhilight optimization

frontend/ui/widget/opdsbrowser.lua
Close: #4076
Add new optional fields (username and password) to OPDS catalog and local calibre catalog.
=> Add OPDS authentication

frontend/ui/widget/opdsbrowser.lua
* Change url for Internet Archive from `http://bookserver.archive.org/catalog/` to `https://bookserver.archive.org`
* Fix logger problem in fetchFeed
=> OPDS - change url for Internet Archive

plugins/calibrecompanion.koplugin/main.lua
=> Custom server URL for calibre wireless connection

frontend/apps/reader/modules/readergesture.lua
* Fix name: Table of contents
* Extend full refresh
=> Minor changes of gesture manager

frontend/ui/widget/opdsbrowser.lua
Small change to display the author of books in OPDS catalogs. The author is shown under the title.
Fixes #4258
=> Display the author in OPDS catalogs.

README.md
=> README.md: add note about `--appimage-extract`

frontend/ui/widget/footnotewidget.lua
=> Fix footnote size after screen rotation or resize

frontend/device/kobo/device.lua
re #4291
c.f., https://www.mobileread.com/forums/showpost.php?p=3771404&postcount=2994
& https://www.mobileread.com/forums/showpost.php?p=3772378&postcount=2998
Big fat warning: something is *definitely* rotten in the state of
Denmark:
* FrontLight/NaturalLight might need some more testing/tweaks
* Rotation (initial or accelerometer-induced) is *NOT* handled.
This'll require someone with an actual Forma, shell access,
and a bit of courage, because rotation is hell.
Programming chops greatly appreciated!
=> Initial Kobo Forma support

frontend/device/kindle/device.lua, platform/kindle/koreader.sh
And generally avoids doing stupid things on FW >= 5.10.x, too.
=> Support the Kindle PW4

frontend/device/kindle/device.lua, platform/kindle/koreader.sh
For real, this time.... -_-".
re #2848
=> Fix Kindle FW detection

platform/kindle/koreader.sh
re #2848 
Should hopefully stop running from KUAL being intermittently broken depending on how much time KPVBooklet was used in that power cycle.
Note that I have no idea if that workaround is even still sane for KPV itself, or other KPV-specific quirks on newer FW.
=> Don't try to deal with KPVBooklet shenanigans when run from KUAL

frontend/ui/data/css_tweaks.lua
See https://github.com/koreader/koreader/pull/4307/files#r234400330
=> [fix, lang] Replace CSS jargon with natural English

frontend/ui/widget/configdialog.lua
The font size items (Aa Aa ... Aa) and the align & column items (for PDF) had a non-tapable spacing between them, which could make hitting an item difficult.
This replaces this spacing by padding on each side of the item, so a tap in between will always catch one item, for easier selection.
No change in look, but now the space between the old tap areas (shown with a border) is tapable:
<kbd>![image](https://user-images.githubusercontent.com/24273478/48798249-7eee5200-ed04-11e8-9e48-b8ea7fd4f859.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/48798278-8d3c6e00-ed04-11e8-931c-12659985b338.png)</kbd>
(no change in the vertical height of the tap area thus).
Sidenote: there seems to be an other issue (not fixed by this PR) with the column & align icons, which may …
=> ConfigDialog: larger tap area around font and icons

frontend/ui/data/css_tweaks.lua
Requested on the forum, and it makes a lot of sense.
https://www.mobileread.com/forums/showthread.php?p=3777972#post3777972
=> [UX] Add paragraph whitespace/indent style tweaks

frontend/device/kobo/device.lua
Related to #4291.
This is to fix the wrong key mapping.
=> fix wrong keymapping for Forma

frontend/device/kindle/device.lua, frontend/device/kindle/powerd.lua, spec/unit/device_spec.lua
* isWifiOn (fix #4380)
* FL state restore on resume (esp. when off) (fix #4392)
=> A few Kindle fixes

frontend/apps/reader/modules/readerdictionary.lua
As suggested by @poire-z in https://github.com/koreader/koreader/pull/4401#issuecomment-447629244
=> [UX] Download dictionary: keep menu open

frontend/device/pocketbook/device.lua
=> Add support for PocketBook Touch HD Plus

frontend/device/kindle/device.lua
For some reason, they weren't supported in the release FW, and I'd forgotten to add 'em here ;).
=> Handle the two newish Indian PW4 variants

frontend/ui/data/dictionaries.lua
=> [fix] Dictionary download: repackage lzip to gzip

frontend/device/pocketbook/device.lua
Might need to be repeated for the others?
Fixes #4473.
=> [fix] PocketBook 626 new firmware with new codename

Makefile
=> [fix] AppImage: include libsndio for SDL

kodev
This filters out useless messages using the "intended" way (without
grep).
=> [Android] Update logcat command for kodev run android

frontend/ui/language.lua
Thanks to @fofo444, see https://github.com/koreader/koreader/commit/5e557e22198cfdfdf4503e31fa57229124ac4b43#r32178173.
=> [i18n] Add Slovak to translations

Makefile
=> fix android release version

frontend/apps/reader/modules/readerdevicestatus.lua
=> Don't show low battery warning when charging

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerview.lua
Re #4575 & #4576 
(Not that I could actually exactly reproduce any of 'em, but at least #4575 made sense ;)).
=> Some more repaint/refresh tweaks

README.md
Pilfered from @NiLuJe's https://github.com/NiLuJe/kfmon
=> README: add a cute little version tag badge

frontend/apps/reader/modules/readergesture.lua
See https://github.com/koreader/koreader/issues/4333#issuecomment-464361133
=> [UX] ReaderGesture: add back to previous location as an option

frontend/apps/reader/modules/readergesture.lua
=> [UX] ReaderGesture: More gestures (suspend, history, rotation)

platform/kindle/koreader.sh
=> Fix fuse related shenanigans with tar on Kindle

frontend/device/gesturedetector.lua
Reported by @poire-z in <https://github.com/koreader/koreader/pull/4607#issuecomment-464622906>.
Also refactor slightly along the way to make the translations more straightforward.
=> [fix] GestureDetector: multiswipe rotation

frontend/document/picdocument.lua
=> Really disable HW dithering on Kindle ;)

spec/unit/gesturedetector_spec.lua
=> [spec] Add GestureDetector stub

Makefile
Fixes #4627.
Includes:
* [chore] Log SDL loading error https://github.com/koreader/koreader-base/pull/827
* [fix, AppImage] Add libXss.so.1 dummy https://github.com/koreader/koreader-base/pull/826
=> [fix, AppImage] Add libbsd.so.0 & libXss.so.1 dummy

Makefile, platform/android/llapp_main.lua
=> [chore] Deprecate Android OTA code

frontend/device/gesturedetector.lua
Unfortunately a mistake snuck into the final steps of refactoring <https://github.com/koreader/koreader/pull/4607>.
Thanks to @poire-z for pointing it out [here](https://github.com/koreader/koreader/pull/4607#issuecomment-464856789).
=> [fix] GestureDetector: fix multiswipe direction detection code

frontend/apps/reader/modules/readergesture.lua
Accidentally broken in https://github.com/koreader/koreader/pull/4623
Also see https://github.com/koreader/koreader/pull/4640#issuecomment-466443328
=> [fix] Gesture manager: actually register multiswipe

frontend/apps/reader/modules/readergesture.lua
Include a safety check to prevent rerecording an existing gesture.
Also extend the default set of gestures to include all of them, and add east south west north for refresh. (I've always thought small diagonal swipe to be rather awkward to trigger.)
See https://github.com/koreader/koreader/pull/4644#issuecomment-466743715 and https://github.com/koreader/koreader/issues/4651 regarding the menu update.
=> [UX] Gesture manager: delete custom gestures and update menu

frontend/apps/reader/modules/readergesture.lua
Accidentally broken by 1d6948ddf1ea67681fe9b8c71e1be06dc14e81c2
=> [fix] Gesture manager: default at the top

frontend/apps/reader/modules/readergesture.lua
Up, left is also the traditional Opera gesture for parent directory.
=> [UX] Gesture manager: add north west = folder up as file manager default

frontend/ui/otamanager.lua
See https://github.com/koreader/koreader/issues/4650#issuecomment-466965983
=> [UX] Alternative update message when ota_version < local_version

spec/unit/timeval_spec.lua
=> [spec] Add more TimeVal tests

frontend/apps/reader/modules/readergesture.lua
=> [UX] Gesture manager: add action - go to file browser

frontend/apps/reader/modules/readergesture.lua
See https://github.com/koreader/koreader/pull/4678#issuecomment-468378040
=> [fix] Gesture manager: more logical position for file browser

frontend/apps/reader/modules/readergesture.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua
Before multiswipes and the gesture manager this was impractical on touch-only devices, but no more!
=> [UX] Navigation settings for all devices

frontend/apps/reader/modules/readergesture.lua
Cf. https://github.com/koreader/koreader/issues/4687
=> [UX] Gesture manager: add action - toggle reflow

frontend/apps/reader/modules/readergesture.lua, frontend/ui/widget/keyvaluepage.lua, frontend/ui/widget/menu.lua
=> [UX] Gesture manager: add action - go to

frontend/apps/reader/modules/readergesture.lua, frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerrolling.lua
Also adds rudimentary support for these in ReaderPaging (might need more work in some zoom modes or in scroll mode).
paper.pdf includes a workable TOC.
cf https://github.com/koreader/koreader/issues/4333#issuecomment-468420820
=> [UX] Gesture manager: add actions - prev/next chapter

frontend/apps/reader/modules/readergesture.lua, frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerrolling.lua, spec/unit/readerlink_spec.lua, spec/unit/readerpaging_spec.lua
Also fix previous page action in gesture manager.
=> [chore] Deprecate TapForward/TapBackward

.codecov.yml
This should hopefully make it stop saying commits "fail" for not reaching 70 % coverage.
=> [CI] Add .codecov.yml

frontend/device/gesturedetector.lua
Multiswipes consisting of mixed straight and diagonal strokes are not dependable and too easy to mess up, but making them mutually exclusive seems to work out quite well.
=> [UX] GestureDetector: add diagonal multiswipes

frontend/apps/reader/modules/readergesture.lua
Start your gesture on the link to follow it.
Defaults to southeast, northeast.
References https://github.com/koreader/koreader/issues/4687
See https://github.com/koreader/koreader/issues/4687#issuecomment-468827385
=> [UX] Gesture manager: add action - follow nearest link

Makefile, frontend/device/android/device.lua, kodev
Requires https://github.com/koreader/android-luajit-launcher/pull/126
Related to #2040
=> Disable ota updates on certain android flavors

frontend/device/gesturedetector.lua, frontend/util.lua
=> [fix] GestureDetector: deep copies of events for multiswipes when rotated

frontend/device/generic/device.lua
=> [fix] Allow overriding low pan rate on E Ink device

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagershortcuts.lua, frontend/apps/reader/modules/readergesture.lua
=> [UX] Gesture manager: add action - folder shortcuts

frontend/device/generic/device.lua, frontend/device/gesturedetector.lua, reader.lua
Looks like my dpi refactoring also broke gesture detector :(
=> fix: update gesturedector constant for custom screen dpi

frontend/device/android/device.lua
=> [android - eink ]: do not refresh eink on activity changes

frontend/apps/reader/modules/readergesture.lua
Fixes #4743 (shallow submodule + GitHub bug). Updated FreeSans fixes #4707 todo (swapped arrows).
=> Bump fonts

frontend/apps/reader/modules/readerstatus.lua
Overlooked in #4746, see https://github.com/koreader/koreader/pull/4746#issuecomment-470569106
=> [fix] ReaderStatus showStatus to onShowBookStatus

frontend/device/sdl/device.lua
Avoids a crash otherwise caused by #4666.
=> [fix] Add delayed pan to SDL scroll

frontend/ui/widget/menu.lua
=> [fix] widget/menu: Don't propagate ShowGotoDialog to other widgets

frontend/device/generic/device.lua, frontend/ui/elements/screen_dpi_menu_table.lua
this addresses https://github.com/koreader/koreader/issues/4726#issuecomment-469585801.
=> fix: auto dpi menu checkbox display

frontend/apps/filemanager/filemanagershortcuts.lua, reader.lua
Regression caused by #4764. Fixes #4768.
=> [fix] Behave properly on start with shortcuts

frontend/apps/filemanager/filemanagerbookinfo.lua, frontend/apps/reader/modules/readergesture.lua
As requested by @ersi.
Cf. https://github.com/koreader/koreader/issues/4727#issuecomment-471766024
=> [UX] Gesture manager: add action - show book information

frontend/ui/data/creoptions.lua, frontend/ui/data/strings.lua
Sounds better. See https://github.com/koreader/koreader/pull/4782#issuecomment-472621160
=> cre 2-pages: rename toggle to "Dual Pages"

frontend/device/gesturedetector.lua
=> [fix] GestureDetector: fix typo in ges_coordinate_translation_90

frontend/device/android/device.lua
Fixes https://github.com/koreader/koreader/issues/4821
Same as https://github.com/koreader/koreader/pull/4822
Thanks to @pazos who implemented the Android backend, see https://github.com/koreader/android-luajit-launcher/pull/133
=> [Android, UX] Add Device:openLink() implementation

frontend/apps/reader/modules/readergesture.lua, frontend/device/kindle/powerd.lua, frontend/ui/uimanager.lua
fixes some stuff discussed in #4823
=> Kindle suspend using lipc

frontend/ui/menusorter.lua
=> [fix] MenuSorter: don't add empty menu item

plugins/wallabag.koplugin/main.lua
Currently unused, but a prerequisite for dynamically adding links to Wallabag.
=> [feat] plugins/wallabag: addArticle() method

frontend/apps/reader/modules/readergesture.lua
As requested by @poire-z here: https://github.com/koreader/koreader/pull/4820#issuecomment-478220239
=> [UX] Gesture manager: show selected two-finger swipe action

.gitignore, Makefile
This can be added to the build server as an artifact and used for automatic F-Droid updates. Cf. https://github.com/koreader/koreader/issues/2040#issuecomment-474925297 pointed out by @pazos.
=> [Android] Add F-Droid latest file

frontend/ui/widget/opdsbrowser.lua
Fixes #4873. Unfortunately this will introduce a slight delay but I don't see any other quick & reasonable solution.
=> [fix] OPDS last-modified check

frontend/ui/elements/multiswipes.lua, frontend/ui/widget/virtualkeyboard.lua
This makes the code a lot more complex, but it looks much better.
=> [UX] VirtualKeyPopup: variable size

frontend/ui/widget/virtualkeyboard.lua
See https://github.com/koreader/koreader/pull/4891#issuecomment-481866246
=> [fix] VirtualKeyPopup close refresh

frontend/device/cervantes/device.lua, frontend/device/generic/device.lua, frontend/device/kobo/device.lua, frontend/device/kobo/powerd.lua, frontend/ui/widget/frontlightwidget.lua
Regression since #4871
Fix #4895
=> Update AutoWarmth state on resume

frontend/ui/data/keyboardlayouts/en_keyboard.lua, frontend/ui/data/keyboardlayouts/keypopup/en_popup.lua
=> [UX] Keyboard popup: add Z diacritics

frontend/ui/data/keyboardlayouts/en_keyboard.lua, frontend/ui/data/keyboardlayouts/keypopup/en_popup.lua
=> [UX] Keyboard popup: add H and J

frontend/ui/data/keyboardlayouts/en_keyboard.lua, frontend/ui/data/keyboardlayouts/keypopup/en_popup.lua
=> [UX] Keyboard popup: add N and M diacritics

frontend/ui/data/keyboardlayouts/keypopup/en_popup.lua
Overlooked in https://github.com/koreader/koreader/pull/4938
=> [fix] Actually commit V popup data

Makefile
Accidentally broken in https://github.com/koreader/koreader/pull/2132.
=> [fix, Ubuntu Touch] Actually bundle libSDL2.so!

platform/ubuntu-touch/koreader.apparmor, platform/ubuntu-touch/koreader.apparmor.openstore, platform/ubuntu-touch/manifest.json
Cf. https://github.com/koreader/koreader/issues/4361#issuecomment-484959506 and https://github.com/koreader/koreader/pull/4946
=> [Ubuntu Touch] Minor updates

frontend/apps/reader/modules/readertypeset.lua
See https://www.mobileread.com/forums/showthread.php?t=316787
=> [i18n] Change user-facing floating punctuation text to hanging punctuation

Makefile, platform/ubuntu-touch/koreader.sh
It distracts the developers. ;-)
=> [Ubuntu Touch] Strip OTA update code

.ci/helper_luarocks.sh, .circleci/config.yml
Includes https://github.com/koreader/koreader-base/pull/906
Cf. https://github.com/koreader/koreader-base/issues/905
=> [CI] Bump busted to v2.0.rc13-0

Makefile, kodev, spec/unit/commonrequire.lua, spec/unit/readertoc_spec.lua
Some combination of Travis and/or older Busted necessitated insufficient insulation.
Follow-up to https://github.com/koreader/koreader/pull/4970
=> [spec] Better insulation

frontend/apps/filemanager/filemanagersearch.lua
Fixes https://github.com/koreader/koreader/issues/4225.
=> [fix] Close calibre search when opening document

plugins/newsdownloader.koplugin/main.lua
Wrap the whole of loadConfigAndProcessFeeds with Trapper:wrap so that feeds are downloaded sequentially, otherwise they become interleaved and the UI progress updates get confusing. Use Trapper:info in place of manually constructed InfoMessages.
Improves #4894 by fixing issues discussed in #4982
=> NewsDownloader: Fix UI when downloading multiple feeds

plugins/systemstat.koplugin/main.lua
I had some other mounts popping up
This seems like a good fix. (tested it)
=> Kobo only has mounts in /mnt/

frontend/ui/widget/button.lua, frontend/ui/widget/container/inputcontainer.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/inputtext.lua, frontend/ui/widget/virtualkeyboard.lua
=> [fix, UX] Ignore first hold release when keyboard opened with hold

plugins/newsdownloader.koplugin/epubdownloadbackend.lua, plugins/newsdownloader.koplugin/main.lua
Pass strings into functions, so that they can add their own info to the UI instead of overwriting the information shown by the calling function(s).
=> NewsDownloader: Improve info shown on UI during processing

frontend/util.lua, plugins/wallabag.koplugin/main.lua
Also pass path from Wallabag plugin.
Fixes #5025.
=> [fix] util.getSafeFilename() default to worst-case scenario

frontend/device/kindle/device.lua
Eerily similar to a PW4, except with a much lower density screen, and a raised bezel.
=> Kindle Basic 3 support

frontend/ui/data/keyboardlayouts/ko_KR_helper.lua, frontend/version.lua
=> [doc, fix] Some documentation issues

frontend/device/kindle/device.lua
Otherwise touch will be stuck in perpetual hold.
Fixes https://github.com/koreader/koreader/issues/5070
=> [fix] Kindle Basic 3: use Kobo snow protocol

frontend/device/android/device.lua, frontend/ui/elements/common_info_menu_table.lua
=> [wip]: more android device info in "Report a bug" infomessage

frontend/device/kindle/device.lua
Once again, LTE devices have an extra proximity sensor that shifts the
evdev path by one...
Fix #5110
=> Auto-detect the touchscreen input device on the PW4

frontend/device/generic/device.lua, frontend/device/kindle/device.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua, plugins/statistics.koplugin/main.lua
(i.e., truly ancient kernels and weird FS).
In which case, we use TRUNCATE, which might be a tad less terrible than
DELETE on said weird crap FS.
Re #5159
=> Don't use WAL on devices where it's not supported

frontend/apps/reader/modules/readerfrontlight.lua, frontend/apps/reader/modules/readergesture.lua
See: https://github.com/koreader/koreader/pull/5179#discussion_r310676845
=> Extend edge zones

frontend/apps/reader/modules/readerfrontlight.lua, frontend/apps/reader/modules/readergesture.lua
* Add double finger up and down swipe gesture
* Cleaning ReaderFrontLight
=> Add double finger up and down swipe gesture
