koreader/koreader

Makefile
since users may have mantained their own extensions.cfg file
The extensions.cfg file is still in the release package and users
could manually copy the `system` directory to the USB root if they
want Koreader to handle all their documents.
=> don't update extensions.cfg in OTA

frontend/ui/font.lua, platform/kindle/koreader.sh, platform/kobo/koreader.sh, platform/pocketbook/koreader.app
It turns out that one of our mupdf patch reads the FONTDIR env var
and uses it in a totally different way so we will use another env var
EXT_FONT_DIR to define external font directory for different platforms.
This is a hot fix.
=> fix mupdf rendering caused by FONTDIR env var

frontend/device/kobo/powerd.lua
I've tested this on a N905C. I assume this implementation never
worked (since charge_now is supposed to show state of charge), but
it would be useful to get a confirmation.
=> Fix charging detection for Kobo devices

.editorconfig, defaults.lua, frontend/apps/filemanager/filemanager.lua, frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readergoto.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/modules/readersearch.lua, frontend/apps/reader/modules/readerview.lua, frontend/apps/reader/readerui.lua, frontend/device/generic/device.lua, frontend/document/djvudocument.lua, frontend/httpclient.lua, frontend/ui/data/koptoptions.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/touchmenu.lua, plugins/kosync.koplugin/KOSyncClient.lua, plugins/kosync.koplugin/api.json, plugins/kosync.koplugin/main.lua, reader.lua, spec/unit/httpclient_spec.lua, spec/unit/kosync_spec.lua, spec/unit/spore_spec.lua
Synchronization should work like this:
=> add progress sync plugin and various fixes

frontend/httpclient.lua, frontend/ui/uimanager.lua, platform/android/llapp_main.lua, plugins/kosync.koplugin/KOSyncClient.lua
mcode force allocation on Android is now optional
Anyone who encounters random freeze of koreader for Android
is encouraged to enable this by adding a file at
"/sdcard/koreader/patch.lua" with the content of:
```
require("jit.opt").start("sizemcode=256","maxmcode=256")
for i=1,100 do end  -- Force allocation of one large segment
```
The sizemcode and maxmcode could be adjusted from 128 to 512 to
make koreader best fit on your Android device.
This is a workaround to fix #1456.
=> disable Turbo on Android

.travis.yml, README.md, frontend/apps/reader/modules/readerfooter.lua, frontend/device/android/device.lua, frontend/document/koptinterface.lua
This should also fix #1350 by temporarily dismissing minibar.
And now we are independent from system libstdc++ library, tested with all tool-chains currently available on my machine:
```
koreader $ readelf -d koreader-x86_64-linux-gnu/koreader/libs/*|grep stdc++|wc -l
0
koreader $ readelf -d koreader-x86_64-pc-linux-gnu/koreader/libs/*|grep stdc++|wc -l
0
koreader $ readelf -d koreader-arm-linux-gnueabi/koreader/libs/*|grep stdc++|wc -l
0
koreader $ readelf -d koreader-arm-obreey-linux-gnueabi/koreader/libs/*|grep stdc++|wc -l
0
koreader $ readelf -d koreader-arm-linux-androideabi/koreader/libs/*|grep stdc++|wc -l
0
```
This should fix #1469 and #480.
=> Popup goto dialog only when holding on visible status bar and various fixes

platform/kindle/koreader.sh, platform/kobo/koreader.sh
Thanks to @Markismus's questions, I realized that some of what I thought
was true, wasn't.
First, pkill is a terrible idea to check for interpreted scripts.
Second, pidof is also potentially not that great for interpreted
scripts, because it'll only work when said script is called via a shebang, and one that is
following the Linux syntax at that.
We don't have the full pidof version from procps with the -x flag to paper over that,
so use pgrep -f instead.
cf.
https://github.com/NiLuJe/koreader/commit/a736a571d221993c410da36bdcd8a1a2bde3f0fa#commitcomment-10948910
for the gory details.
=> Fix startup scripts.

defaults.lua, frontend/ui/font.lua
Now koreader on android can import fonts from "/system/fonts" and "/sdcard/koreader/fonts".
=> add external font dir option for Android

Makefile, datastorage.lua, frontend/apps/filemanager/filemanagersetdefaults.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/docsettings.lua, frontend/document/koptinterface.lua, platform/android/llapp_main.lua, reader.lua
On kindle, kobo and pocketbook the data directory is the current
running directory but on Android the app is installed in system
defined location and users may have no access to that location.
The same circumstances should be true for the upcoming Koreader for
Ubuntu touch, so the data directory (in which tessdata, dictionaries,
global settings, persistant defaults and probably history data are
stored) could be stored in another place.
This PR also fix #1537 and fix #1476.
=> add datastorage module to handle data directory on various platform

platform/kobo/koreader.sh
Should reboot less unnecessarily for older versions of KSM, and hopefully this would also be more forward-compatible.
=> Fix KOReader exit

README.md
The list of Linux build dependencies needs to include `luarocks`,
since the current master doesn't build without it:
/bin/bash: line 2: luarocks: command not found
make[1]: *** [build/x86_64-linux-gnu/rocks/lib/luarocks/rocks/lua-spore/0.3.1-1/lua-spore-0.3.1-1.rockspec] Error 127
make[1]: Leaving directory `~/koreader/base'
make: *** [base/build/x86_64-linux-gnu/luajit] Error 2
This PR fixes the docs (and removes a redundant mention
of `autoconf` from the list as well.)
=> Fix Linux build docs to mention luarocks

platform/kobo/nickel.sh
After exiting koreader, nickel will not recognize that sdcard is present.
This patch fixes that
=> Fix nickel doesn't recognize sdcard after exiting

frontend/ui/translator.lua, frontend/ui/wikipedia.lua
Rudimentary JSON validity check by seeing if the first character is {. The JSON decode function will crash in spite of pcall if it's not.
The Wikipedia issue was reported [on the forum](http://www.mobileread.com/forums/showthread.php?p=3155408#post3155408).
=> Fix Wikipedia (HTTP now redirect to HTTPS) and slightly more robust failsafes

Makefile
because ISP may cache gz files and confuse zsync protocol
When I wget the gz file it's redirected to a ISP cached file and zsync
will fail.
```
~ $ wget http://vislab.bjmu.edu.cn/apps/koreader/ota/koreader-kindle-arm-linux-gnueabi-v2014.11-348-gddc3619.tar.gz
--2015-09-26 10:55:54--
http://vislab.bjmu.edu.cn/apps/koreader/ota/koreader-kindle-arm-linux-gnueabi-v2014.11-348-gddc3619.tar.gz
Resolving vislab.bjmu.edu.cn (vislab.bjmu.edu.cn)... 202.112.180.24
Connecting to vislab.bjmu.edu.cn
(vislab.bjmu.edu.cn)|202.112.180.24|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location:
http://202.112.191.194/file/gz/2cd4eae05d961f8afe9ad99fb20288d4e735fbf4/vislab.bjmu.edu.cn/apps/koreader/ota/koreader-kindle-arm-linux-gnueabi-v2014.11-348-gddc3619.tar.gz
[following] …
```
=> don't use tar.gz file extension for OTA

frontend/device/kindle/device.lua, frontend/device/kindle/powerd.lua, frontend/ui/networkmgr.lua
... at least starting from the K3.
On older devices, we'd need to parse gasgauge-info's output.
=> Fix battery status on legacy Kindles

.travis.yml, Makefile, README.md, frontend/apps/reader/readerui.lua, frontend/document/koptinterface.lua, frontend/document/pdfdocument.lua, frontend/ui/widget/inputdialog.lua, platform/ubuntu-touch/koreader.apparmor.openstore, spec/unit/commonrequire.lua, spec/unit/document_spec.lua, spec/unit/httpclient_spec.lua, spec/unit/koptinterface_spec.lua, spec/unit/kosync_spec.lua, spec/unit/verbose_print.lua
this should fix #1547.
Note that Koreader assumes that all files in one zip archive use the same password to encrypt the file contents, even though ZIP file format has no such restriction.
This PR relies on a merge of koreader/koreader-base#345.
=> add support for password protected zip/cbz documents

frontend/device/generic/powerd.lua, frontend/ui/widget/touchmenu.lua, platform/kindle/koreader.sh
Fix the battery status polling cache invalidation. And use it to make sure the battery status shown in the top menu is always fresh (re #1656).
Update the startup script on Kindles to properly handle the status bar on FW 5.6.5 when starting via KUAL with the framework running. (Our previous method doesn't work properly anymore).
=> Minor fixes

frontend/ui/widget/opdsbrowser.lua
When downloading files from OPDS feeds, include author's name into the downloaded file name.
For example: "Mary W. Shelley - Frankenstein.epub" instead of just "Frankenstein.epub".
=> OPDS: include author's name into the file name

frontend/ui/widget/opdsbrowser.lua
The current code expects entry titles in OPDS feeds to be either plain text or XHTML nodes with a `type="text/xhtml"` atrribute. Some feeds may have titles with `type="xhtml"` or `type="html"` instead.
For example, the feed at http://manybooks.net/opds/titles.php contains:
```
<title type="xhtml">
<div xmlns="http://www.w3.org/1999/xhtml">Z</div>
</title>
```
Koreader does not know how to deal with this and displays "Unknown" instead.
This PR removes the type check altogether and just uses the contents of the `div` node as the entry title, if available.
=> OPDS: fix parsing entry titles on ManyBooks (and possible other sites)

defaults.lua, utils/kobo_touch_probe.lua
The KOBO_TOUCH_MIRRORED is only used when init input device,
after the initialization setting it will have no effect on the
event adjust hook.
=> fix kobo touch probe

platform/android/llapp_main.lua
This workaround makes a reservation of mmap slots that are hopefully
near the address of `mcode_alloc_at`. Then it unmaps those slots and
lets luajit allocate a large slot for mcode.
This PR relies on the merge of https://github.com/koreader/android-luajit-launcher/pull/33.
=> fix mcode allocation failure on Android

frontend/ui/widget/container/inputcontainer.lua, plugins/statistics.koplugin/main.lua
so that ReaderUI cannot receive that event and all devices
don't flush settings when going into suspend or background.
=> fix FlushSettings event consumed by statistics plugin

.gitignore, frontend/ui/uimanager.lua, spec/unit/readerfooter_spec.lua, spec/unit/uimanager_bench.lua, spec/unit/uimanager_spec.lua
There is a race condition between checkTasks and schedule/unschedule. It's surprising that no one has ran into this issue so far ;P
I changed the scheduler to an ordered queue to avoid the race condition. The new implementation will be way faster in checkTasks, but slower in schedule/unschedule. Given that it actually fixes a correctness issue, I think it's a reasonable tradeoff.
=> Fix scheduler in UIManager

frontend/apps/reader/modules/readerhyphenation.lua, frontend/apps/reader/readerui.lua
All EPUB and FB2 documents have a language specified in their metadata so we can choose the hyphenation dictionary automatically, without having to choose it manually for each document.
I've added a JSON index file to the crengine source tree (koreader/crengine#24). It is used for mapping language tags, like `en` or `ru-RU`, to hyphenation dictionaries, like `English_US_hyphen_(Alan).pdb`.
I've also had to add a new event, `ReadSettingsLate` alongside the usual `ReadSettings`. The reason for that is that `ReadSettings` is fired *before* the document is loaded and parsed, but the hyphenation manager needs to access the document metadata for choosing the right hyphenation dictionary when reading settings. The new `ReadSettingsLate` event is fired *after* the document has been read and …
=> Automatically choose the hyphenation dictionary based on the document language

defaults.lua, frontend/apps/reader/modules/readerfrontlight.lua, frontend/device/generic/powerd.lua, frontend/device/kobo/nickel_conf.lua, frontend/device/kobo/powerd.lua, frontend/ui/uimanager.lua, reader.lua
A few points about this patch:
* Because I consider nickel an optional external entity I tried to keep it away from core logic. For this reason I [load its value into `settings.reader.lua`](https://github.com/koreader/koreader/compare/master...dset0x:frontlight-sync?expand=1#diff-df44ce4f2932b4d7c52ce1bd4d511defR74) and let the rest of koreader's boot process read _that_ as it's always been doing.
* At the moment, KSM resets the brightness setting when switching from koreader to nickel and vice-versa. I have patches that fix that and once I've cleaned them up I will push them in KSM's way.
---
Issues that make this a WIP for now:
* Currently set to crash when `/mnt/onboard/.kobo/Kobo/Kobo eReader.conf` is missing, but I'll fix once I have the chance.
* The ini parser is very naive, but I …
=> WIP Synchronise frontlight level with nickel config

platform/kobo/koreader.sh
This change is to mount sd card as RW on kobo devices. Currently we are using sdr doc config, which needs write permission to the location where the original books store. But by default, sd card on kobo is mounted as RO, so the sdr doc config won't be written.
=> Mount SD card as RW on kobo, but ignore errors

frontend/device/generic/powerd.lua, frontend/device/kobo/nickel_conf.lua, frontend/device/kobo/powerd.lua, frontend/ui/uimanager.lua, reader.lua, spec/unit/nickel_conf_spec.lua
Currently koreader front light level is syncing with Nickle, but leaks front light state configuration. So this change is to,
1. Read / write FrontLightState in Nickle config.
2. Add a frontlight_state in G_reader_settings (for kobo only).
3. Add a flState (boolean) in kobo/powerd, to control the hardware toggle activity.
4. Change the fl_min of kobo from 0 to 1 (set front light level to 0 will confuse users, since the hardware toggle won't take any effect).
After this change, we can remove most of the functions and state variables (isOn, savedBrightness, etc) in koreader-base/ffi/kobolight.lua (only setBrightness is using)
Please kindly let me know if you think this PR needs to be squashed.
=> Add Nickle.frontLightState, save and restore frontlight toggle state when koreader starts

frontend/device/generic/device.lua, frontend/device/generic/powerd.lua, frontend/device/kobo/device.lua, frontend/device/kobo/powerd.lua
Logic to turn off Kobo front light when suspending device is too magic. So this change is a slight refector of device & powerd component. After this change, we can remove almost all variables in koreader-base/ffi/kobolight.lua.
Please refer to https://github.com/Hzj-jie/koreader-base for koreader-base change. Comparing is @ https://github.com/koreader/koreader-base/compare/master...Hzj-jie:master
=> Slightly refector device & powerd component, remove some magic code

frontend/device/generic/device.lua, frontend/ui/screen.lua, spec/unit/eink_optimization_spec.lua
frontend/ui/screen.lua is not required by any other components, so it's initializing function won't be called. Move its logic into frontend/device/generic/device.lua.
=> E-ink optimization setting should be correctly set after restart.

frontend/device/kobo/device.lua
=> Add a sleep after kobo resume to resolve partial blank screen issue

reader.lua
Issue discussed @ #1926 , I do not have a kobo mini, but at least this change won't smoke on my Aura HD.
=> Koreader won't start on Kobo without frontlight, powerd.fl may be nil.

.ci/script.sh, .luacheckrc, Makefile, frontend/apps/reader/modules/readerrolling.lua, frontend/dbg.lua, frontend/ui/uimanager.lua, spec/unit/commonrequire.lua, spec/unit/dbg_spec.lua, spec/unit/font_spec.lua, spec/unit/readerbookmark_spec.lua, spec/unit/uimanager_spec.lua
* fixed a bug in legacy reader config initialization
* added `dbg:guard()` function to disable critical asserts in non-debug mode
* refactor autospend a bit to make the code mostly self contained. that way it's easier for us to move it into its own module in the future if needed. also got rid of some if check at runtime.
=> fix(readerrolling): crash with legacy last_per config in page mode

frontend/cache.lua, frontend/ui/rendertext.lua, frontend/ui/widget/container/inputcontainer.lua, frontend/ui/widget/container/widgetcontainer.lua
to make koreader on Android  more stable
and with these opt params:
```
require("jit.opt").start("sizemcode=64","maxmcode=64", "hotloop=10000")
```
The strategy here is that we only use precious mcode memory (jitting)
on deep loops like the several blitting methods in blitbuffer.lua and
the pixel-copying methods in mupdf.lua. So that a small amount of mcode
memory (64KB) allocated when koreader is launched in the android.lua
is enough for the program and it won't need to jit other parts of lua
code and thus won't allocate mcode memory any more which by our
observation will be harder and harder as we run koreader and cause 
random freeze on some Android devices.
This PR relies on koreader/android-luajit-launcher#40.
=> disable jit on some modules on android

README.md
I have encountered the issue to build kobo version (kindle should also be impacted) on one of my newly installed amd64 ubuntu box recently. Error message is
/usr/include/features.h|374|fatal error: sys/cdefs.h: No such file or directory|
After google around, this seems like a very common issue for cross platform compiling. Installing libc6-dev-i386 should resolve the issue.
=> libc6-dev-i386 is required to build kobo / kindle version on amd64 system

frontend/docsettings.lua
This change resolves issue #1962, and also this is the first step to migrate old history folder to sdr docsettings.
=> Prefer sdr folder to history folder

defaults.lua, frontend/apps/filemanager/filemanager.lua, frontend/docsettings.lua, frontend/document/document.lua, frontend/ui/widget/opdsbrowser.lua, plugins/evernote.koplugin/main.lua, plugins/kosync.koplugin/main.lua, reader.lua, spec/unit/filemanager_spec.lua, spec/unit/util_spec.lua
If we're saying "successfully" is redundant as per #1972 we'd better be thorough.
I realized I should also check for deviant spellings of KOReader, but they don't really seem to occur. I changed a couple of comments to prevent false positives though.
Edit: oh yeah, if someone wants to double check, I searched with commands like
```
grep -R --include="*.lua" 'KoReader' .
```
=> Removed a bunch of "successfully" and replaced one ellipsis.

defaults.lua, frontend/device/kobo/device.lua, frontend/ui/screensaver.lua, frontend/ui/widget/imagewidget.lua, reader.lua
This issue has been discussed @ #1968 .
Also, current ImageWidget does not provide enough stretch strategies to better present a screen saver.
I have tried several combinations, and finally decide to use overflow + centering, considering users may use screensaver to hide what they are reading, so stretch the image to cover entire screen but respect original aspect ratio should be a good choice.
=> Update ImageWidget to support more stretch settings, and enable screensaver on kobo

frontend/ui/widget/imagewidget.lua
bring back the old behavior: when width and height are set and all the
zooming options are false, zoom the image to that size. The last commit
to Imagewidget.lua caused it ignores the set width and height and use
the image's original size instead when no zoom option is set. This
caused #1979. Although #1979 can be fixed by setting autostretch=true,
but I think it's good to fix here.
=> imagewidget fix

frontend/device/kobo/device.lua
This issue is discussing @ #1981, the change simply ignore Power_Sleepcover keycode if 'ignore_power_sleepcover' setting has been enabled.
=> Add an ignore_power_sleepcover setting to ignore Kobo power_sleepcover keycode

frontend/apps/filemanager/filemanagerhistory.lua, frontend/apps/reader/readerui.lua, frontend/docsettings.lua, frontend/readhistory.lua
This is the first step to migrate history into sdr, this issue has been discussed @ #1962 .
This change adds a new ReadHistory component to track and store read history. So components such as FileManagerHistory do not need to relay on history folder to build read history list.
=> Migrate history folder into sdr - A new history.lua file and ReadHistory component

frontend/readhistory.lua
This change fixes two small issues in ReadHistory class.
1. If a file has been removed, renamed, moved, etc, won't track it in ReadHistory anymore. Since we do not have binary search now, it's expensive to track a file moving, deleting or renaming. We can add this feature back once we have a binary search.
2. The table.sort is not stable, so we need to actively keep the last timestamp of a file.
=> Won't track missing files in history, and always keep latest timestamp

frontend/apps/reader/readerui.lua
by setting the timeout to 0.0 seconds so that when the screen
is turned to landscape the dialog is already closed.
Before this patch the 'Opening file' dialog could be this:
=> fix 'opening file' dialog not centered in landscape

frontend/apps/reader/readerui.lua, frontend/ui/uimanager.lua, kodev, spec/unit/readersearch_spec.lua
See commit message for more info. I remember someone reported this issue before, but I can't find the ticket anymore. I am able to reproduce the bug in my K3.
=> force paint open file info before loading document

frontend/apps/reader/modules/readerfooter.lua, reader.lua
This PR includes two minor changes,
1. File manager won't be able to start if settings.reader.lua contains partial fontmap. This issue is discussed in #2038.
2. Gesture range of page footer covers part of document area, so selecting text at the bottom of a page is impossible. i.e. the long press action will be sent to page footer instead of document. Considering we provide a defaults.persistent.lua to overwrite some default settings in defaults.lua, if the gesture range of page footer is zero, i.e. page footer is not touchable, a new menu item, 'Toggle' will be added to status bar menu to act as tapping on the page footer. Long press page footer would triggle 'go to page' function, which has been covered by the bookmark menu already.
Feel free to reject the second change if you really do …
=> Two minor changes

frontend/ui/widget/inputtext.lua, frontend/ui/widget/scrolltextwidget.lua, frontend/ui/widget/textboxwidget.lua, frontend/util.lua
This patch adds the cursor functionality for the inputtext widget on **KINDLE TOUCHABLE** device. Will add support for physical keyboard support for the cursor functionality in the future.
With this patch the user can navigate to the text where he wants to edit easily. Previously, if a user wants to insert some characters in some place in the original text, he has to delete all the tailing characters until he reaches the position to insert with, input the characters he wants to add and those deleted tailing characters.  Now the user can navigate to to the insert position simply by touching the screen, and a cursor in the widget appears indicating the current position to edit.
One of the application of this patch is for "Rename" on file manager window, where a user wants to edit the title …
=> Add cursor functionality for inputtext widget

frontend/docsettings.lua, spec/unit/docsettings_spec.lua
This change is to remove all legacy document settings after flushing.
=> Remove legacy document settings after flushing

defaults.lua, frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerzooming.lua, frontend/device/input.lua, frontend/document/djvudocument.lua, frontend/document/koptinterface.lua, frontend/document/pdfdocument.lua, frontend/ui/uimanager.lua, spec/unit/defaults_spec.lua
This should implement feature request of zoom mode for multi-columns page in #501.
This PR depends on koreader/koreader-base#435.
How to use?
1. 
Tap the top left corner of a PDF/Djvu page to get into the flipping
mode
1. 
Double-tap on text block will zoom in to that column
1. 
Double-tap on any area will zoom out to an overview of the page
1. 
repeat step 2 to focus to another page block
How does it work? 
1. 
We first find the mask of text blocks in the page.
1. 
Then we intersect page boxes with user tap to form a page block.
1. 
Finally we zoom the page to the page block and center current view to
that block.
=> PDF free zoom mode revisit

frontend/apps/reader/modules/readerzooming.lua
This issue has been discussed in issue #2072.
=> ReaderZooming should remove the size of page footer when calculating zoom value

frontend/device/android/device.lua, frontend/device/android/powerd.lua, frontend/device/generic/powerd.lua, platform/android/llapp_main.lua
and use standrad Android API to query battery level and charging status
This should fix #2025, fix #1759 and fix #1415.
And now Android adb log shall be filtered by `adb logcat | grep -i koreader`.
=> add support of screen brightness settings for Android

frontend/ui/uimanager.lua, frontend/ui/widget/inputtext.lua
1. fix crash when clearing inputbox (follow-up of #2092)
2. add larger margin top and bottom in reflowed page (#1714)
3. revert several commits in crengine that cause rendering problems (#2107)
=> various fixes and enhancements

frontend/ui/uimanager.lua
This should fix #2141 and fix #2130.
Previously the widget stack will enable double tap detection after closing readermenu.
=> diable double tap by default in the widget stack

frontend/apps/reader/readerui.lua, frontend/ui/elements/common_settings_menu_table.lua
This is a small change to add a hidden setting to disable save document feature.
I am considering whether we should add an individual 'control panel' like module.
=> Add a setting to disable save document

frontend/apps/filemanager/filemanagerhistory.lua, frontend/docsettings.lua, frontend/readhistory.lua
This change is to fix #2162.
This change adds item text in the button, and fixes several potential crashes. (A bad file name in history folder can crash DocSettings class.)
This change also fixes a wrong items deleted issue. i.e. index of ReadHistory.hist has not been updated after removing items.
=> Add removed item name in "Remove this item from history" and fix wrong items deleted issue.

frontend/document/document.lua, frontend/random.lua, plugins/kosync.koplugin/KOSyncClient.lua, plugins/kosync.koplugin/api.json, plugins/kosync.koplugin/main.lua, reader.lua, spec/unit/random_spec.lua
HouQP and I are discussing the details about whisper sync feature in issue https://github.com/koreader/koreader/issues/2179. Some of the changes to koreader client can be made in advance to the conclusion of discussion.
1. MD5 hash of a document should be calculated at the very first time a book has been opened. This change can avoid any document saving feature to impact this value. The MD5 hash is the only key to identity a file in kosync plugin.
2. Create a device id in kosync plugin to identity a device, and kosync plugin won't sync progress from a same device. I have considered to put the device id into a more common place, i.e. G_reader_settings. But I finally decide to leave it in kosync plugin, because of the complexity of the key. We always send the device_id in http requests, and …
=> Update kosync plugin

.ci/install.sh, plugins/kosync.koplugin/main.lua, reader.lua, spec/unit/device_spec.lua, spec/unit/readerrolling_spec.lua, spec/unit/screenshoter_spec.lua
1. It turns out that `device_id` is not defined in unit test environment
which makes the `assert(self.kosync_device_id)` fail and somehow makes `luajit` segmentation fault.
2. In the device spec, stubbing `io.open` will make subsquent `require`
all return boolean value and segmentation fault `luajit`.
This patch is a minimum viable change that makes CI work on both my
local box and Travis.
=> fix broken unit tests on Travis CI

.ci/install.sh, .ci/script.sh, Makefile, frontend/apps/reader/modules/readerlink.lua, frontend/apps/reader/modules/readerview.lua, frontend/apps/reader/readerui.lua, frontend/dbg.lua, frontend/document/document.lua, frontend/ui/uimanager.lua, frontend/ui/widget/eventlistener.lua, reader.lua, spec/unit/dbg_spec.lua, spec/unit/device_spec.lua, spec/unit/readerlink_spec.lua, spec/unit/readerpaging_spec.lua, spec/unit/readerview_spec.lua
and get more confidence with the unit testing framework.
Now `make testfront` won't retry on failure and testing files are
ordered in each run so that it's possible to reproduce testing failure.
And this patch also fix flush settings not working before suspend issue:
at some point the `FlushSettings` event is sent to `UIManager` instead
of `ReaderUI`, but `UIManager` only delegated events to active widgets
and `ReaderUI` is actually not an active widgets thus will miss the event.
=> fix unit test of readerlink and readerpaging

frontend/device/generic/device.lua, frontend/ui/uimanager.lua
which would make readerui handle swipe event twice.
And use broadcastEvent to emit `FlushSettings` event.
This should fix #2225 and fix #2226.
=> revert 9ab005a changes to UIManager:sendEvent

README.md
I've finally managed to build the release of KOreader for Android, but I've run into some issues.
I've updated the manual to reflect the solutions I've found.
The issues I've found are:
1. The version of the needed Android SDK platform isn't described anywhere;
2. `xutils-dev` is missing from the prerequisites, while it provides the `makedepend` utility used by the openssl build system;
3. Finally, for the Android build it is necessary to install JDK version 8.
=> Update documentation to clarify the process

frontend/ui/network/manager.lua, spec/unit/network_manager_spec.lua
Seems I forgot this function in last PR.
This change should ensure koreader can automatically enable WIFI and obtain IP when it starts.
=> Restore WIFI state when koreader starts

datastorage.lua
This change uses newly added android.externalStorage() to set the data folder instead of hard coded string.
android.externalStorage() change is @ https://github.com/koreader/android-luajit-launcher/pull/44, which must be merged before this one.
=> Use android.externalStorage instead of hardcoded string for android data path

platform/kobo/obtain-ip.sh
I recently found on Kobo, KOReader always gets a new IP each time it starts. Though this is not a serious issue, I would prefer to fix it in this simple way.
=> Always release ip before obtaining a new one

kodev
OSX's version of bash (3.x) does not support the new -v conditional operator. 
The problematic line in the script was modified to support bash 3.x.
=> fixed script to support OSX bash 3.x

frontend/apps/reader/modules/readerkobolight.lua, frontend/apps/reader/modules/readerview.lua
This only includes:
- the one finger gesture to adjust frontlight level on the left hand side of the screen.
- frontlight toggle on the bottom-left of the screen.
The default sensing area is not Global yet, let me know if it is ok like that.
I figure the "frontlight-info in the footer“ should belong to another PR if needed?
=> add kobo frontlight gesture

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerkobolight.lua
- This adds the frontlight information in the footer
- add an option to the menu
- if the frontlight is changed by gestures, the footer is updated as well.
Tested on a Kobo H2O.
=> add frontlight information in the footer

frontend/ui/network/manager.lua, frontend/ui/uimanager.lua, plugins/kosync.koplugin/main.lua
This change ensures KOSync plugin can automatically push and pull progress on related events.
onNetworkConnected / onNetworkDisconnected are two new events. But,
1. Since we do not block network restoring process when device resumes, the onNetworkConnected event cannot be raised on kobo correctly.
2. On android or kindle, we do not actively control the network. The onNetworkConnected event also cannot be raised correctly.
But this issue does not block KOSync plugin from listening to the event to get progress, which should be an expected behavior.
=> KOSync plugin should repect onNetworkConnected and onFlushSettings events

frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/wikipedia.lua
This patch fix https://github.com/koreader/koreader/issues/1844.
Language wikipedia search is set based on current document language or (if document language doesn't set) on Koreader settings.
Tested on KPW3 and emulator on Polish, English and German.
=> Patch for wikipedia language

Makefile, frontend/dbg.lua, frontend/device/generic/device.lua, frontend/device/kindle/device.lua, frontend/device/kobo/device.lua, frontend/ui/network/wpa_supplicant.lua, frontend/ui/uimanager.lua, reader.lua
This PR depends on https://github.com/koreader/koreader-base/pull/462.
Now plugging in/out usb cable should not corrupt the device suspend state anymore.
=> Support handling usb hotplug event in kobo

frontend/apps/filemanager/filemanagerhistory.lua, frontend/ui/rendertext.lua, frontend/ui/widget/keyvaluepage.lua
In history window when we long press on item we get menu. When filename is long the text go outside menu like that:
After this fix we have truncated text on long filename:
=> Fix long filename text in history textbox

platform/kobo/koreader.sh
This is a trivial change to return correct result from koreader.sh.
koreader on my kobo aura hd randomly crashes, so I prefer to have a while loop to ensure it can be restarted automatically. But I also do not want koreader to restart if I actively click on close button. So this change returns reader.lua result from koreader.sh, a wrapper script can use this value to decide whether restart or not.
=> Return correct result from koreader.sh

frontend/apps/filemanager/filemanager.lua
This mirrors the well known shell convention and release the user from a needlessly verbose description of the current path.
=> Replace the home dir by ~ in the FM's current path

frontend/apps/filemanager/filemanager.lua
- Don't do any substitution unless `home_dir_name` exists.
- Don't rely on `gsub` because it might interpret some characters in `home_dir` as magical (and might also replace a match not starting at the beginning of `path`).
=> Generalize and consolidate tildify

frontend/apps/filemanager/filemanager.lua
I'm not sure what the original intention was, but in practice, the user experience regarding the way this setting is saved is horrible: it seems to change randomly and once the orientation is changed from portrait to landscape, the only way to fix it is to edit `settings.reader.lua`.
=> Don't try to set the value of fm_screen_mode

frontend/device/generic/device.lua, frontend/ui/screensaver.lua, frontend/ui/uimanager.lua
This changes the behavior of the powered off transition phase for the Kobo devices: instead of displaying a confirmation dialog, a screensaver is used after a 2 seconds press delay.
Users can specify separate directories/files/messages for the powered off and sleeping states through the `path` and `message` attributes of the `{poweroff,suspend}_screensaver` settings.
Fixes #2327 and closes #2306.
=> Make the powered off state customizable

frontend/util.lua, spec/unit/util_spec.lua
In textboxwidget words with unicode characters are incorect hyphenation.
This patch fix it.
e.g.
Polish:
German:
=> Fix hyphenation words with unicode character in texboxwidget

frontend/util.lua, spec/unit/util_spec.lua
PR #2356 removes unicode from isSplitable character set, which breaks CJK.
=> PR #2356 breaks CJK character splitting

frontend/apps/opdscatalog/opdscatalog.lua, frontend/ui/widget/opdsbrowser.lua
I wonder that before opening the downloaded file close widget "opds catalog". Is it possible in function OPDSBrowser:openBook? What do you think? When you close the book and return to the "file manager" we see opds catalog widget.
=> Issue #1688 - FR: Would you like to read the downloaded book for OPDS

frontend/device/kobo/device.lua
Test image:
https://cloud.githubusercontent.com/assets/159419/20651651/5e344d1c-b4e9-11e6-8450-6fb165c792db.png
Fixes #2372.
=> Kobo Aura ONE: no viewport adjustments needed

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagermenu.lua
After exit from OPDS browser we should refresh filemanager. 
Without that we have not seen newly downloaded book in the current folder.
=> Refresh filemanager after exit from OPDS browser

frontend/device/kobo/device.lua
=> Kobo: initial support for Kobo Aura second edition (Kobo star)

frontend/apps/filemanager/filemanagermenu.lua, frontend/ui/widget/textboxwidget.lua, frontend/util.lua, platform/kobo/disable-wifi.sh, spec/unit/util_spec.lua
As discussed in some issues some days ago:
- `disable-wifi.sh `: reduced sleep time (1 second was noticable when exiting koreader) : 2x200ms is enough for my device to not crash, and should be less noticable to those who dont need it.
- clear reader's cache: also clear in-memory cache (I think it's quite simple, and less risky than exiting reader without flushing settings). I thought about adding `Cache.cached={} `in its `Cache:clear() `method, but this method is used by unit tests that expect `cached `to not be reset between calls to `clear()`. So, yes, i access some unexposed object attribute from outside, but we're in "developer options" :) If you prefer I add an other method for that, let me know.
About textboxwidget merged yesterday: I wasn't proud of my unit test results, and I …
=> Various fixes

frontend/apps/reader/modules/readergoto.lua, frontend/apps/reader/skimtowidget.lua, frontend/ui/widget/skimtowidget.lua
close #2444 
Discussion: #2444 
In sum:
- Add new menu item "Skim to"
- Left old widget "Go to"
- In the "old" widget has been added new button "Skim" to switch to new skim widget.
- From "skim widget" we can switch to "go to widget" clicking on the page number (button) between -10 and +10.
=> Skim to widget (New Go to page/location widget )

plugins/calibrecompanion.koplugin/main.lua
close #1909 
Should fix problem with missing Wi-Fi prompt in calibre wireless connection.
=> Fix: wifi prompt in calibre wireless connection

frontend/apps/reader/modules/readerhyphenation.lua, plugins/perceptionexpander.koplugin/main.lua
Most settings allow for choosing a default with Hold. Hyphenation didnt have that.
We could choose to make the hold item the default (overriding the document languages' one), instead of a fallback, but some people may not like that.
This fallback will help in that one doesnt have to select a non-english one each time for .txt and likes.
Also removed unnecessary PerceptionExpander:onSaveSettings().
=> Set hyphenation dict fallback with Hold

frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/rendertext.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/scrolltextwidget.lua, frontend/ui/widget/textboxwidget.lua
**Text justification of definitions:**
This is prettier (and helps distinguish paragraphs), but can be disabled for those who don't like it by adding `["dict_justify"] = false` to `settings.reader.lua`.
This could be used in any textboxwidget or scrolltextwidget with optional `justified=true` attribute.
The idea is just to add some pixels to spaces (or first chars if no space in line) to fill width.
I first did all the stuff in `RenderText:renderUtf8Text()`, before realizing i needed the padding info in `textboxwidget.lua` for hold position accuracy. So I ended up passing some optional `char_pads` table to `RenderText:renderUtf8Text()`.
I don't know what is the right syntax to mention it in the `RenderText:renderUtf8Text()` doc string.
I also increased `text_scroll_span` from 6 to 12 for …
=> dict/wiki text justification + language rotation fix

plugins/evernote.koplugin/main.lua
A trivial change to rename onSaveSettings to saveSettings in EvennoteExporter plugin.
=> Rename onSaveSettings to saveSettings

frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerlink.lua, frontend/document/credocument.lua, frontend/document/document.lua, frontend/ui/screensaver.lua, frontend/ui/widget/confirmbox.lua, frontend/ui/widget/container/alphacontainer.lua, frontend/ui/widget/imageviewer.lua, frontend/ui/widget/imagewidget.lua
Details in the commits' comments.
(All in one PR, cause they all depends on https://github.com/koreader/koreader-base/pull/470 - dunno about the base bumps needed for this to be linked to the cre.cpp mods, tell me if i need to do something more).
I did all these for a better experience with a wikipedia page "save as epub" feature, which produces a epub with thumbnail images and wikipedia links in the html. Here's one example, if one needs an epub with images (photos, maps) to check this PR: [Battle of Stalingrad.EN.zip](https://github.com/koreader/koreader/files/706922/Battle.of.Stalingrad.EN.zip)
(You'll tell me if there's some interest for that, or if it's a gadget.)
Btw, on the emulator, colored images (thumbnails in the wikipedia page) appears B&W for crengine, but with this …
=> ImageViewer widget, better handling of external links, fix some blitbuffer memory leaks

plugins/statistics.koplugin/main.lua
Makes percentage completed easily accessible through the statistics plugin. It has always been accessible through the status bar, but not through the statistics menu. I found myself wanting to know this information without using it on the status bar and figured others might feel the same way.
=> Statistics: Add percentage completed to Statistics plugin

frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/wikipedia.lua
... and TOC, and cover image. API and html from Wikipedia should be stable, so this should hopefully not need much maintenance. There are only a few tweaks to the HTML to work around some small crengine quirks.
Sample generated epub available in #2493
Included a zipwriter.lua that i put in frontend/ (did not find an existing other suitable place). It is based on some other works (but these can't be used as is), mentionned at top of file. Not sure that is enough to give credits, or if other things are needed.
Also for the current text-only wikipedia full page: replace the ==s in section titles with some unicode symbols for a better visual feeling of hierarchy. These same symbols are also used in the .epub.
Both can be disabled by adding ["wikipedia_prettify"] = false to settings.reader.lua …
=> Wikipedia: save full page as epub (html, with optional images)

frontend/apps/opdscatalog/opdscatalog.lua, frontend/ui/widget/opdsbrowser.lua
I removed the special nature of the default OPDS catalogs (Project Gutenberg, for example) where they could not be removed or edited and fixed a bug where non-calibre OPDS catalogs would not prompt the user to enable Wifi upon the failure of the device to connect to the internet. Instead, it threw a generic error message.
=> OPDS: Fixed Wifi prompt and enabled removing default catalogs.

plugins/statistics.koplugin/main.lua
close #2503 
Fix: #2503 (Statistics can't display the DOC name)
=> Can't display the doc name in Statistics page

frontend/ui/widget/imageviewer.lua
For devices without multi touch support, where pinch & spread don't work (see #2505).
=> ImageViewer: allow zoom with vertical swipe on sides

frontend/ui/widget/menu.lua, frontend/ui/widget/touchmenu.lua, frontend/util.lua
I think this may be a common issue in KOReader. For some unfamiliar features, I always need to try the menu items before actually understanding their meanings. A very basic issue is, I cannot quite tell whether the menu item is an action or contains sub items.
So this change adds a + before menu items with sub menu.
Indeed there are several options, say, preposing a +, as this solution; postposing a >, more like Microsoft style; postposing a +, the first design, etc. Feel free to vote or suggest your preference.
=> Add characters in menu items to indicate sub menus

frontend/apps/filemanager/filemanager.lua, frontend/docsettings.lua, frontend/ui/widget/filechooser.lua
.sdr folder is shared between kindle stock reader and kobo; it's also shared by files with only different suffixes, so we definitely should not purge it. Instead, removing metadata.{suffix}.lua is a safer choice.
Meanwhile, sidecar dir is generated by kindle stock reader automatically, even without opening the book, so DocSetting:hasSidecarDir() should be replace by DocSetting:hasSidecarFile() to decide the display style in file manager.
=> Removing metadata file instead of purging .sdr folder

frontend/apps/filemanager/filemanager.lua
Discussed in #2534, if a sidecar folder is empty, it can be removed by os.remove() function.
=> Remove empty sidecar folder

frontend/util.lua, plugins/statistics.koplugin/main.lua, plugins/statistics.koplugin/readerprogress.lua
In statistics plugin day of the week and months can now be translated.
Of course name of days and months must be translated in selected language with Transifex. 
e.g. in English
e.g. in Polish
=> Day of week and months can now be translated

platform/kobo/koreader.sh
ntx_hwconfig is a tool present in all kobo devices. It reads part of the firmware in the first MBs of the internal card. Variables stored in the "hwconfig" are used by uboot, the kernel itself, some kernel drivers and from userspace. The source code of both uboot and linux contains hooks to read some values and send them to the coproccesor.
Because of FW upgrades the binary: ntx_hwconfig is upgraded but the "hwconfig" storage area is not. So all those warnings "config too old, please upgrade" spammed by koreader came from here and there isn't any simple way to fix it" ( hexadecimal editor != simple way )
kobo_config.sh is a wrapper to ntx_hwconfig BTW
So, its SAFE to avoid those messages
=> Kobo: remove useless error messages from ntx_hwconfig

.gitignore
=> .gitignore: add linux-i686 emulator to excluded files

frontend/apps/filemanager/filemanager.lua, frontend/ui/widget/filechooser.lua
This should make it clearer to new users what's going on. Fixes #2529.
Before:
After:
=> File Manager: rename to "KOReader File Browser" and add up arrow to ".."

frontend/apps/filemanager/filemanagerfilesearcher.lua
=> FileSearcher: also show directory results

frontend/device/kindle/device.lua, frontend/device/kindle/powerd.lua, plugins/kobolight.koplugin/main.lua
The kobolight plugin is more useful on Kindle, which does not have a hardware front light toggle. So I changed frontend/device/kindle/powerd to support kobolight.
Meanwhile, this change modifies the steps in kobolight.koplugin, the original gesture level seems too small, and it should respect fl_min / fl_max. (Front light intensity on Kobo Aura HD has 100 levels, i.e. you need to swipe up 10 times to fully turn on the light.) If the behavior is expected, though I do not really think so, I am happy to remove it.
This change also modifies frontend/device/kindle/device, 0 is not a valid value for kindle front light intensity. Once the front light is fully turned off in KOReader, it turned back on again after resume. So we need to manually handle it in powerd:afterResume().
=> Update kobolight plugin to support kindle

frontend/dbg.lua, frontend/device/input.lua, frontend/ui/network/manager.lua, frontend/ui/network/wpa_supplicant.lua, platform/kobo/disable-wifi.sh, platform/kobo/enable-wifi.sh
Aura One uses 8189fs instead of dhd module. Depends on https://github.com/koreader/koreader-base/pull/476.
=> Fix wifi for Aura One

frontend/ui/widget/touchmenu.lua
References #2555.
Before:
After:
=> TouchMenu: keep file/exit button on the right

frontend/ui/widget/touchmenu.lua
The previous *approach* was distracting and unfounded.
Before:
```
TOC
╴╴╴╴╴╴╴╴╴
Bookmarks
╴╴╴╴╴╴╴╴╴
History
╴╴╴╴╴╴╴╴╴
Last Book
```
After:
```
TOC
─────────
Bookmarks
─────────
History
─────────
Last Book
```
=> Use a full line to separate menu items

frontend/ui/widget/opdsbrowser.lua
* Add action clarification to format download dialog
The format download dialog now has a title reflecting where a format will be downloaded with a prefix making it clear that choosing a format will download it.
=> OPDS catalog: improve download dialog (#2445)

frontend/apps/filemanager/filemanagermenu.lua
Minor fix -  if you've never opened a book before "Open last document" should be grayed out.
https://github.com/koreader/koreader/pull/2603#issuecomment-283920847
https://github.com/koreader/koreader/issues/2555#issuecomment-283997186
=> Grayed out Open last document

frontend/apps/cloudstorage/cloudstorage.lua, frontend/ui/widget/opdsbrowser.lua
https://github.com/koreader/koreader/issues/2555#issuecomment-283987684
> I think that there are at least two other cases where the gray out option or the asking for enabling WiFi option should be implemented: OPDS catalog and CLoud storage.
=> Prompt users to turn on Wifi in Cloud Storage and OPDS Browser

frontend/document/credocument.lua
When holding on an SVG image (unsupported by MuPDF,  but displayed as a small empty squere by crengine), KOReader would crash with:
`*** Error in ./luajit: double free or corruption (!prev): 0x0000000000e48a40 ***`
when freeing image data from LUA with `ffi.C.free(data)` .
It seems that for some errors, MuPDF does itself free() the data provided.
As I'm not sure if we can know from lua/ffi if a pointer has already been freed (the `data` cdata structure has the same pointer value before and after the error), the easiest fix is to catch that error message and not do the ffi.C.free(data) in that case.
Better a small memory leak if it's not really freed, than a crash.
=> Fix crash when holding on unsupported image

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/ui/widget/dictquicklookup.lua
And added diagonal swipe support (which was there in readerpaging) to readerrolling, as requested in #2655.
=> Update footer when refreshing screen with diagonal swipe

frontend/device/generic/device.lua, frontend/device/generic/powerd.lua, frontend/device/kindle/device.lua, frontend/ui/widget/touchmenu.lua
Battery capacity is now refreshed every 60 seconds, so we do not need to actively call refreshCapacity() anymore.
=> Remove powerd:refreshCapacity()

frontend/apps/reader/modules/readercoptlistener.lua, frontend/apps/reader/readerui.lua
Otherwise readerrolling will try to jump to a nil xpointer.
fix https://github.com/koreader/koreader/issues/2635.
=> readercopt(fix): set view mode after reader is ready

frontend/apps/reader/modules/readerfrontlight.lua
Close #1903 
- add refresh footer after two finger frontlight change
- change info when frontlight is off from `Frontlight intensity is set to 0` to `Frontlight is off` like in KoboLight plugin
- #1903 was resolved earlier
=> Minor: Reader Frontlight modification

frontend/ui/widget/networksetting.lua
Previously, the cached psk, which is derived from the password and
passed to wpa_supplicant, was not updated when changing the password.
=> WiFi manager bugfix: delete the cached psk when changing the password

frontend/ui/widget/touchmenu.lua
This time without obvious issues. Also see #2572.
=> TouchMenu: keep hamburger menu on the right

plugins/kobolight.koplugin/main.lua
Otherwise it will conflict with swipe to go back feature
=> kobolight(fix): do not consume swipe event if not matched

frontend/ui/widget/inputtext.lua
The last character of a password InputText is currently always shown, even if the `text` field had been set at init time.
=> Only show the last character of a password after typing it

frontend/ui/uimanager.lua
With the BatteryStats plugin, I found my Kobo Aura HD resumes unexpectedly.
Without this change, the device resumed randomly. Though I had not used it, it waked up for 4170 minutes.
With this change, the device had not resumed randomly anymore. (Technically speaking, it still randomly resumed, but got suspended immediately. I will add a system stats plugin later to track the issue.)
Day 1,
Day 2,
=> Force kobo to suspend

frontend/device/generic/device.lua
Noticeable latency between toggling the power switch and the device
showing the screensaver has been tracked down to the two network
manager calls. This change allows the screen to be updated first.
Note that unloading the open source brcmfmac driver used on okreader
is slower than unloading the proprietary driver shipped by Kobo,
making this delay even more noticeable.
self.suspend() is scheduled after the network manager calls to avoid
race conditions.
=> Disable the network asynchronously to avoid blocking the UI

frontend/apps/reader/modules/readertypeset.lua, frontend/document/credocument.lua
It does significantly more harm than good. It can be reenabled with a `txt_preformatted` setting. Fixes #1607.
(Screenshots made with the file from #2422.)
=> CreDocument: disable fancy formatting by default

frontend/ui/widget/opdsbrowser.lua, frontend/util.lua, spec/unit/util_spec.lua
Should fix #2627 and should better work than #2628 
I found this function http://notebook.kulchenko.com/programming/fixing-malformed-utf8-in-lua that should remove invalid UTF-8 chars.
=> Remove invalid UTF8 chars from OPDS

frontend/apps/cloudstorage/ftp.lua, frontend/apps/cloudstorage/ftpapi.lua
Sort order of requires in ftp.lua and ftpapi.lua.
=> Remove invalid UTF8 chars from FTP (cloud storage) and sort order of requires

plugins/terminal.koplugin/main.lua
* ... should be a proper ellipsis
* "written" is a bit more end-user friendly than "dumped"
=> Terminal plugin: minor language fixes

frontend/apps/filemanager/filemanager.lua, frontend/ui/network/manager.lua, frontend/ui/otamanager.lua, frontend/ui/widget/confirmbox.lua, frontend/ui/widget/inputdialog.lua
Generic "OK" buttons should be avoided. Thanks to @lightonflux for pointing this out https://github.com/koreader/koreader/issues/2555#issuecomment-291039945
=> Language: improve confirmboxes

reader.lua
=> Fix #2716 - "Cannot open last file" warning triggered with "Start with last opened file" option turned off

frontend/apps/reader/modules/readerfooter.lua
Device: Kindle Paperwhite with Special Offers (with ads)
Auto refresh time is enabled (Status bar -> Auto refresh time)
When device is going sleep ads is showing from Amazon. Up to 1 minute footer is showing:
This patch should fix it (remove footer from screen with ads).
=> Fix showing footer on Kindle with Special Offers screensaver

frontend/apps/cloudstorage/cloudstorage.lua, frontend/ui/otamanager.lua, plugins/keepalive.koplugin/main.lua
* lang: changed `...` in CloudStorage to real ellipses
* chore: reordered requires in CloudStorage per coding style
* UX: switched "Close" and "Stay alive" in KeepAlive per UX style
* lang: improved message in CloudStorage
* chore: reordered requires in OTAManager per coding style
* lang: removed "your" from "Your KOReader is up to date" in OTAManager
=> UX and language fixes

platform/kobo/koreader.sh
Waiting for #2502. Until now only KSM8 supports new firmware and this is because it uses its own version of koreader.sh.
This forces depth to 16bpp before running koreader.  It was suggested by baskerville on #2542
It also handles weird rotations that I've found on a Kobo Aura HD. AFAIK the same rotation bug happens on Kobo Aura H20 too.
Useful to run koreader from shell, fmon, kfmon...
=> Workaround to support new kobo firmwares (+4.0) without needing KSM8

frontend/apps/reader/modules/readerfooter.lua, spec/unit/readerfooter_spec.lua
I think it sounds more natural as chapter than as table of content, which is an implementation detail (i.e., the chapter markers are shown based on what's in the TOC).
Also removed redundant "this" from "Remaining pages in this chapter"
=> ReaderFooter (lang): "Show toc markers" to "Show chapter markers"

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readersearch.lua, frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/widget/configdialog.lua, frontend/ui/widget/container/inputcontainer.lua
Makes it easier to comply with UX style.
* Change "OK" to "Search dictionary" in Dictionary lookup to comply with UX style
* Change "OK" to "Search all text" in Fulltext search to comply with UX style
Tacked on but highly related:
* change "OK" to "Search Wikipedia" in Wikipedia lookup to comply with UX style
* change "OK" to "Set default" in ConfigDialog to comply with UX style
Chore:
* fixed up order of requires
=> InputContainer: add cancel_text and ok_text

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua, frontend/device/kindle/device.lua, frontend/ui/screensaver.lua
Add screensaver on Kindle devices.
Defaults screensaver is disabled. We can enable it by select Menu -> Screensaver -> Enable cover screensaver
Tested on KPW3 with special offers and KPW2.
=> Screensaver option on Kindle devices

plugins/systemstat.koplugin/main.lua
I add
`Last suspend time`
`Last resume time`
into System statistics
Sugestion https://github.com/koreader/koreader/pull/2669#issuecomment-288813651
=> Add Last suspend and resume time into System statistics

frontend/apps/reader/modules/readerhighlight.lua, plugins/statistics.koplugin/main.lua
* ReaderHighlight: underscore to underline. Although underscore means to
emphasize by underlining, the emphasis lies on the, ahem, emphasis. Besides
which, it's mostly AmE and less well understood worldwide (although in this
particular context it should probably cause no trouble).
* Statistics plugin: menu item text to "reading statistics" to make it clear
which statistics we're talking about. Fixes #2744.
=> Lang: two tiny strings

.ci/before_install.sh
Travis only makes a shallow clone of --depth=50. KOReader is small enough that we can just grab it all. This is necessary to generate the version number, without which some tests will fail.
I'm not entirely sure why something like `git fetch origin master tags/v2015.11` doesn't do the trick, but it doesn't matter much.
=> Travis: `git fetch --unshallow` for version number 

frontend/device/gesturedetector.lua, frontend/document/koptinterface.lua
See commit texts.
About the disable double tap stuff, I tried first to just not go thru the deadline/setTimeout stuff if disable_double_tap is true, but there are some strange side effects (in readerhighlight) i didnt fully understand, so it's just easier and safer to just not do the isDoubleTap check.
#1594 is not obvious to reproduce, i think it needs quick taping and some intensive processing for page display (kopt semi auto crop + dewatermark) so that the setTimeout has less chance to happen before next Tap processing.
=> Some small fixes related to pdf / kopt reading

platform/kobo/koreader.sh
tar fails to apply permissions on fat32 filesystem. thus mv doesn't get executed and consequently OTA package gets applied on every launch. Fixes #2791
=> Update koreader.sh; fixes #2791

frontend/document/credocument.lua, frontend/document/documentregistry.lua
CRE cache, hyphdict and fonts can be initialized only once when first credocument is opened. Previously, they were recreated for each document, and as previous instances were probably not free'd, this caused memory leaks.
Can be tested by opening some epub, and re-opening this same epub from History.
Before, mem usage went like: 14 > 30 > 38 > 48 > 57 > 66.
With this: 14 > 17 > 18 > 20 > 22 > 24.
The 2 collectgarbage() may not be necessary (the engineInit stuff is the one that has that effect), but I got the feeling of an sligthly better, and sometimes a memory decrease with them - but that may be placebo. I can remove them if they look too hacky.
=> Reduce memory leaks when switching credocuments

frontend/apps/reader/modules/readerlink.lua
`self.ui.document:getPageLinks()` (being not supported) returns nil for djvu (unlike pdf or cre where a possibly empty table is returned).
=> Fix crash on Swipe to follow links with DJVU documents

.ci/install.sh
Parsing and rasterisation provided by nanosvg (some svg tags like text, span and images are not supported).
Only svg images included as files in the .epub are supported (embedded svg tags in html are not).
Holding on svg image shows it 4x zoomed in ImageViewer.
Closes #2668 (with the above limitations)
=> Bump base/crengine for SVG images support

frontend/apps/reader/modules/readerrolling.lua
Close #2836 
Should fix problem: `onPageUpdate()` methods runs twice on book open.
=> Remove run twice onPageUpdate() when document is opening

frontend/device/generic/device.lua, frontend/device/kobo/device.lua, frontend/ui/elements/common_info_menu_table.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, frontend/ui/uimanager.lua
a new PR with suggestions from #2873. I close the old one
Not sure yet if those menu items should go in common_info_menu_table.lua or in another place. Feel free to give me your points. This is my first commit in lua code :+1: 
This should fix #2868 and #2588
=> [kobo]: add reboot and poweroff menu actions

frontend/apps/cloudstorage/cloudstorage.lua, frontend/ui/widget/opdsbrowser.lua, plugins/calibrecompanion.koplugin/main.lua, plugins/zsync.koplugin/main.lua
It's not necessarily clear that you need to long-press, see https://www.mobileread.com/forums/showpost.php?p=3520376&postcount=7
=> (minor, lang) improve text clarity for downloadmgr dialogs

plugins/newsdownloader.koplugin/main.lua
Now selecting new download folder doesn't require Koreader restart.
=> NewsDownloader: changing dir doesn't require Koreader restart

frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua
Fixes #2921. Leftover from #2764.
=> (chore) Remove storage statistics menu order leftovers

frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua
Reverts koreader/koreader#2922
Wrt #2926 I figure it's better to keep this where it was.
=> Revert "(chore) Remove storage statistics menu order leftovers"

plugins/batterystat.koplugin/main.lua
This function is not really needed: the state should always be updated by the events.
But we do have trouble that the events won't be fired on Kindle when sleeping, which makes the analysis inaccurate.
=> Remove BatteryStat:initCurrentState()

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua
as the tap gesture on the upper part (mostly) of the screen is
a conventional design to show menus in almost all ereaders as well as
some mobile phone apps. While users not farmilar with the Android world
have no experience with swipe down to show menus that's why we need a
quick start guide for this feature. And experienced Koreader users
probably will turn pages by mistake each time they want to popup the menus.
The solution here is adding back the tap gestures as they were and keep
the new swipe to show menu feature as a supplementary function when
link's tap area blocks menu's tap area.
=> [fix] revert removing tap gestures to show menus

frontend/apps/reader/modules/readermenu.lua, frontend/apps/reader/readerui.lua
This affects #2335, at least for documents covered by `validDjvuFile()` (see https://github.com/koreader/koreader/blob/76cef07c079e979de6aac6b540c9cc2b672b6f57/frontend/document/djvudocument.lua#L15-L23). However, that's only with regard to `touch invalid.djvu` and should not affect whatever happened in the OP.
=> ReaderUI: return to filemanager instead of quitting if no document

frontend/device/kindle/device.lua
Comparing to the existing sleep 1.5 / saveCurrentBB and restoreCurrentBB solution, this looks simple, fast and reliable.
I cannot tell whether this change works fine on devices without special offer, can anyone have a shot?
=> Force refresh when kindle is out of screensaver or usb is unpluged.

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readermenu.lua, frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/elements/reader_menu_order.lua
And also get rid of unnecessary screen refreshes on Kindle Voyage.
The "progress" window for dict lookup is also eliminated as most of the time dict lookup is an instant process, and the "progress" window is preserved for wikipedia lookup as it may take longer time to show the result window.
=> [fix] stop propagation of tap events when triggering reader menu

frontend/ui/widget/configdialog.lua
Close: #2879
Should remove illogical  "Set default Fine Tuning to increase" or "Set default Fine Tuning to decrease" when long pressing on "increase" or "decrease"
=> Remove "Set default Fine Tuning"

plugins/batterystat.koplugin/main.lua
I believe the battery of my Kobo may die soon or later, the capacity may suddenly change *after* I unplug the usb charger. But it's still reasonable for BatteryStats plugin to get hardware battery capacity instead of a cached version.
Indeed I cannot quite tell why getCapacity() needs to cache the result at all.
=> Use getCapacityHW() to ensure latest battery capacity can be retrieved

plugins/newsdownloader.koplugin/main.lua
After reinstallation Koreader I looked for "Settings" in NewsDownloader to change feed sources but there's no such menu entry.
I think it's not clear howto set own feed sources (especially for new users).
And should be explicitly shown.
To make it better visible I decided to add new menu entry with text info.
Maybe one day I'll try to add UI to handle that...
But for now I think this will do the work, better than "manual".
=> News downloader settings menu entry

frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua
Since "disable_fuzzy_search" is for dictionary search only, putting it into "search" menu should be more proper.
=> Put disable_fuzzy_search in search menu

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerbookinfo.lua, frontend/apps/filemanager/filemanagerhistory.lua, frontend/apps/filemanager/filemanagerutil.lua, frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/readerui.lua, frontend/document/pdfdocument.lua, frontend/ui/elements/reader_menu_order.lua, frontend/ui/widget/keyvaluepage.lua, frontend/ui/widget/textviewer.lua, frontend/util.lua, spec/unit/util_spec.lua
See discussion in #2986 and individual commit detailed messages:
- TextViewer widget, used when onHold on truncated item in KeyValuePage
- Store book metadata and nb of pages in new settings
- Book information: refactored and additional features
(not sure why github displays `\x`C2`\x`A0 in red, they work and I had added a lot in wikipedia.lua, where they are displayed in red too)
=> Book information: refactored and additional features

frontend/readhistory.lua, spec/unit/readhistory_spec.lua
I would like to KOReader to support loading history from metadata files. So first ReadHistory needs to be able to reload according to the modification timestamp of history.lua.
=> ReadHistory supports reload

frontend/apps/reader/modules/readerhighlight.lua
This fix should repair the problem with incorrect counting the number of highlight in Statistics plugin (reference  #2893).
=> Fix event AddHightlight and add event DelHighlight

frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/ui/widget/dictquicklookup.lua
Close: #2283
Close: #2609
This patch should fix:
#2283 - Unhighlight is not clickable in dictionary view
#2609 - Deleting highlights in bookmarks does not take effect
=> Fix: Unhighlight is not clickable in dictionary view and Deleting highlights in bookmarks does not take effect

frontend/ui/widget/textviewer.lua
Minor fix.
Wrap text in title TextViewer widget.
Before:
After:
=> Wrap text in TextViewer

frontend/apps/reader/modules/readerbookmark.lua, frontend/ui/widget/textviewer.lua
Close #1395
Now it's available to read bookmarks without having to view ebook page. 
When we long press on selected bookmark:
we get detailed window with all highlighted text. We can also remove selected bookmark.
=> Read bookmarks without having to view ebook page (#1395)

frontend/ui/widget/inputdialog.lua, frontend/ui/widget/networksetting.lua
Reference: #2882 
It's now possible to visible password when entering (connect to the wifi). After click in "Swich visible" you can show/hide password. 
I have no way of checking (on the emulator and the Kindle there is no option to add a wifi network), so ask to see if it works.
=> Option to make password visible when entering

frontend/ui/widget/virtualkeyboard.lua
Close: #2657 
This patch should fix hang up when four time click on AEβ on virtual keyboard. It should also speed up the input of chars.
Tested on Kindle Paperwhite 3.
=> Fix: KOReader dies after clicking AEB four times on keyboard

frontend/ui/widget/textboxwidget.lua
=> Fix: Backspace will delete the character before the one on the left 

frontend/apps/reader/modules/readerdogear.lua
Close: #2636 
This patch should fix problem: Can't long-press lookup word inside bookmark tap zone.
```
Can't long-press lookup word inside bookmark tap zone.
This happens with short words, small fonts and very narrow margins.
```
=> Fix: Can't long-press lookup word inside bookmark tap zone

defaults.lua, frontend/apps/reader/modules/readerconfig.lua, frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readermenu.lua
In some cases config menu is hidden by reader menu. 
Useful should be gesture to show only config menu. I implemented it
When we swipe from down to up in menu zone we get config menu.
=> Gesture to show only config menu

frontend/ui/widget/keyvaluepage.lua, frontend/ui/widget/menu.lua
Fix crash when input non number value (or empty) in "Input page number" (Filemanager or KeyValuePage -> long press on page 1 of xx -> input non number value eg. "aaaa")
=> Fix: crash when incorrect value in input page number

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readerconfig.lua, frontend/apps/reader/modules/readermenu.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/elements/menu_activate.lua
After this patch we can choose way to open reader menu and config menu.
Go to config > Screen > Activate menu :
+ Swipe and tap (default value) - activate of the menu by swipe and tap
+ Only swipe - activate of the menu by swipe (tap doesn't start menu)
+ Only tap - activate of the menu by tap (swipe doesn't start menu)
=> Option to choose gesture to open menu

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readertypeset.lua, spec/unit/readerfooter_spec.lua, spec/unit/readerhighlight_spec.lua
Close: #2257 
This patch should resolve issue #2257 (Footer hides text)
`Sometimes, depending on an epub style, some text is hidden by the progress bar (the mini one at the bottom).`
=> Fix: Footer hides text

frontend/apps/filemanager/filemanagersetdefaults.lua
Close: #2899
`When I use advance settings I mean when I try to open advance settings Koreader pretty much crashes `
Tested on my Android.
=> Fix: Advanced settings crashes

frontend/apps/cloudstorage/cloudstorage.lua, frontend/apps/cloudstorage/dropboxapi.lua, frontend/apps/filemanager/filemanagermenu.lua
Should fix: #3074 
Cloud storage opens in landscape mode when display is in portrait mode.
If return is pressed when in root, koreader crashes.
=> Fix: Cloud Storage not working on Kobo Aura ONE

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerhistory.lua, frontend/apps/filemanager/filemanagermenu.lua, frontend/ui/elements/filemanager_menu_order.lua, reader.lua
Fixes #2774
* make history view borderless
* add new menu for what to start with
I didn't bother to implement the "feature" that you couldn't toggle this setting unless you opened a document first. Comments welcome @ersi @KenMaltby
=> Support history as default view for filemanager

plugins/zsync.koplugin/main.lua
Close: #2638 
"Zsync" -> "Share this document" crashes koreader if not connected to wifi
After this fix when koreader is offline after "Zsync" -> "Share this document" we are asked to enable wifi.
=> Fix: Zsync -> Share this document crashes

frontend/util.lua, spec/unit/util_spec.lua
lfs.dir will crash rather than return nil if directory doesn't exist
Proper fix for 9f5e44670183d046054f87b4820bf5d1b35b3b12 which is nothing but a workaround. However, I do think creating more of those data dirs automatically is more user-friendly because otherwise Android users will have to look it up or guess.
=> [fix] util.isEmptyDir() crashes on non-existent dir

frontend/ui/elements/filemanager_menu_order.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua, plugins/coverbrowser.koplugin/covermenu.lua, plugins/coverbrowser.koplugin/listmenu.lua, plugins/coverbrowser.koplugin/main.lua, plugins/coverbrowser.koplugin/mosaicmenu.lua, plugins/coverbrowser.koplugin/xutil.lua
This plugin offers some alternative views of file lists as used by FileManager and History, using "as you browse" extracted metadata and cover images from files.
It exports one new sub-menu (Display mode) to File Browser menu and upon selected mode, replace a few display methods of the FileChooser and FileManagerHistory classes. While being a bit hacky, it has the effect that all the other code of these is still used as is and all features available (sorting, hidden files, select and hold actions...), so very few code duplicated.
As of now, it does not need any modification to core code, and is fully self-contained in its plugin directory.
<kbd>![1-menu-textcover](https://cloud.githubusercontent.com/assets/24273478/26780997/981c3344-49ec-11e7-8b52-c80fbb95319d.png) </kbd>
(If you choose …
=> CoverBrowser plugin: alt views for File Browser and History

frontend/apps/filemanager/filemanagerhistory.lua, frontend/ui/widget/menu.lua
due to a side effect with coverbrowser. CenterContainer is no more needed as History is now full screen.
See https://github.com/koreader/koreader/pull/3058#issuecomment-323178120
=> Fix "start with history" misalignment

frontend/ui/widget/button.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/textwidget.lua
Simple way to ensure overlong text is truncated. Used by dictquicklookup to truncate long titles.
Closes #3099.
See https://github.com/koreader/koreader/issues/3099#issuecomment-323515768
=> Button and TextWidget: added max_width attribute

frontend/device/input.lua
Avoid these warning on the emulator output:
```
08/19/17-14:42:22 WARN  got error waiting for events: ./ffi/SDL2_0.lua:110: Waiting for input failed: timeout
08/19/17-14:42:22 WARN  got error waiting for events: ./ffi/SDL2_0.lua:110: Waiting for input failed: timeout
08/19/17-14:42:25 WARN  got error waiting for events: ./ffi/SDL2_0.lua:110: Waiting for input failed: timeout
08/19/17-14:42:27 WARN  got error waiting for events: ./ffi/SDL2_0.lua:110: Waiting for input failed: timeout
```
They happen when something scheduled get us out of waitForInput (which may be useful to know on the emulator), but they ought to be ignored by the code - they were just not ignored because the error message with SDL had some prefix. So, we just replace equality check with some kind of _endswith_.
=> Avoid warning on input timeout on the emulator

frontend/apps/filemanager/filemanager.lua
Otherwise, this .old backup is used when re-opening the document, and we could never reset docsettings.
See https://github.com/koreader/koreader/pull/3093#issuecomment-323185347 and next ones.
=> Purge .sdr: also remove .old backup file

frontend/ui/widget/imageviewer.lua
Hold (= pan with 0 pixel move) was really hard to get (or I really have shaky fingers!). This makes it easier.
=> ImageViewer: make Hold (trigger full refresh) easier

.gitmodules
We should use https://github.com/koreader/... instead of git://github.com/koreader/... to prevent such problems: https://stackoverflow.com/questions/16298986/unable-to-connect-to-github-com-for-cloning
I have today similar problem.
=> Prevent problem with git clone

frontend/apps/filemanager/filemanagerbookinfo.lua, frontend/apps/reader/readerui.lua, frontend/document/picdocument.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua
So an image file can have a cover in coverbrowser's display.
It also allows for an alternative viewer (ImageViewer widget) when holding on file / View full size cover.
=> Added PicDocument:getCoverPageImage() and :getProps()

frontend/ui/menusorter.lua, spec/unit/menusorter_spec.lua
See https://github.com/koreader/koreader/pull/3107#issuecomment-323581851
=> [fix] MenuSorter: ignore separator as first item

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, frontend/ui/widget/dictquicklookup.lua
Added 2 submenus, and some settings menu items I was too lazy to add some months ago.
`Dictionary settings `: moved `Disable dictionary fuzzy search` in it, and added `Justify definitions' text` (we may add later some other items like list dictionary, dictionary management and ordering...)
`Wikipedia settings `: added `Set Wikipedia languages` (free input of language codes separated by space) and `Set Wikipedia 'Save as EPUB' directory`.
Should I remove `download_dir` (directory configured for OPDS downloads) from the candidates for `Save as EPUB`, so candidates starts with `home_dir` or `getDefaultDir()` ?
=> Dictionary settings and Wikipedia settings menu items

plugins/coverbrowser.koplugin/main.lua
Some _hidden_ file manager settings may have a place in menu, and they may fit in the newly added _Display mode/Other settings_ menu  (from coverbrowser plugin).
<kbd>![othersettings](https://user-images.githubusercontent.com/24273478/29665061-9217c074-88d2-11e7-8ce7-10a2886c012e.png)</kbd>
From https://github.com/koreader/koreader/issues/2589#issuecomment-323927682 :
**show_file_in_bold** filemanager items in bold : true/false/"opened" https://github.com/koreader/koreader/pull/2457
**home_dir_display_name** used by filemanagerutil.abbreviate(path) to shorten directory in title bar made as a toggle (true => "~", false => nil) (people who wants something other than ~ may set it manually as before
**autoremove_deleted_items_from_history** …
=> Add some settings to Display mode/Other settings menu

frontend/apps/reader/readerui.lua
See https://github.com/koreader/koreader/pull/3093#issuecomment-323595972
It allows keeping the original metadata.lua.old backup a little bit longer, instead of having them both be the same because of this double save when leaving reader.
I have this change for a few days, and I haven't noticed once I lost the page I was on, so it should be ok :)
=> Avoid settings double save when leaving Reader

frontend/ui/rendertext.lua, frontend/ui/widget/keyvaluepage.lua
It is not useful at this time, but it will be used by me in the future.
=> Fix: truncateTextByWidth() should respect kerning and bold

frontend/device/kobo/powerd.lua, frontend/ui/widget/frontlightwidget.lua
Been inclined to have a look at frontlightwidget after reading some issues, after i suggesting the fl_min=0 fix (https://github.com/koreader/koreader/issues/3103 https://github.com/koreader/koreader/issues/2970#issuecomment-324973222).
I don't use that widget, and I just fixed what was obvious to me, and for it to somehow behave like the 1st-time user I was would expect :) But maybe I changed some of the original expected behaviour. @robert00s , could you please review this and tell me if you're fine with it? And may be if it works as fine on Kindle (looks like most issues are reported on Kobo, but some should happen on Kindle too).
`fl_min=0` for all other devices, and I see no reason for it to be different on Kobo, and it solves the _1% acting as Off_ bug.
The assumption it should be 1 …
=> Fix kobo fl_min and frontlightwidget

frontend/ui/widget/buttontable.lua
This patch should prevent something like that:
=> max_width in buttontable - prevent overlong text

frontend/ui/network/manager.lua
Sometimes www.example.com doesn't resolve. Fixes #3142.
=> [fix] NetworkManager: check DNS from dns.msftncsi.com instead of www.example.com

plugins/statistics.koplugin/main.lua
Fix incorrect migration from v1 to v2.
Table page_stat only allowed one record per book.
=> Fix: Remove primary key from page_stat

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua, frontend/ui/elements/common_info_menu_table.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, frontend/ui/menusorter.lua
* fixes #2898 (prevents accidentally triggering reboot or poweroff)
* increases clarity by preventing second page
* add "sleep" menu entry
@a-kohout Do you think this is sufficient or should I still add confirmation boxes to the restart and shutdown actions seeing how they're more "destructive" than a mere accidental "sleep" or "exit".
=> [UX] Add exit menu

frontend/apps/reader/modules/readerrolling.lua
Fix that problem:
Open epub -> change to scroll mode -> exit than we have in crash log
```
./luajit: frontend/apps/reader/modules/readerrolling.lua:275: attempt to index field 'document' (a nil value)
frontend/apps/reader/modules/readerrolling.lua:275: in function 'getLastPercent'
frontend/apps/reader/modules/readerrolling.lua:147: in function 'handleEvent'
frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
frontend/apps/reader/readerui.lua:506: in function 'saveSettings'
frontend/apps/reader/readerui.lua:512: in function 'handleEvent'
frontend/ui/uimanager.lua:226: in function 'close'
frontend/apps/reader/readerui.lua:559: in function 'onClose' …
```
=> Prevent crash on exit in scroll mode

frontend/ui/widget/toggleswitch.lua
Taping on left or bottom borders of the toggles (bottom menu) was causing a crash (easier to reproduce with mouse clicks on the emulator :)
The crash was caused later, when we got for example 5 as position when the toggle has only 3 values.
=> Fix crash when taping on toggleswitch left or bottom borders

frontend/apps/reader/modules/readerrolling.lua
In scroll mode (epub) document was always reopen on first page. It should fix it.
=> Fix: Lost last document position in scroll mode

frontend/ui/uimanager.lua
Seen sometimes in the crash.log on my kobo:
09/08/17-15:45:03 WARN  no refresh got enqueued. Will do a partial full screen refresh, which might be inefficient
It's logged when, for example, closing a KeyValuePage widget, getting out of screensaver, may be a few others.
It used to be a debug, as it's just some info for developers that they may have forgotten to use a setDirty when widget is closed, and houpq made it a log.warn() when rewritting all the old debug code:
https://github.com/koreader/koreader/commit/f95ad00b9#diff-df44ce4f2932b4d7c52ce1bd4d511defL571
Just some info that KeyValuePage may need to have:
```
function KeyValuePage:onCloseWidget()
UIManager:setDirty(nil, "partial")
end
```
But it's exactly what uimanager does when a widget does not do it explicitely, so, it's fine …
=> Change a logger.warn() back to .dbg() as it used to be

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerlink.lua, frontend/ui/widget/dictquicklookup.lua
I realized I've got too many ideas just sitting around on my hard drive. The idea behind this one is that you can disable "follow links" on single tap yet still follow links.
Of course if you just hold on some regular text it's disabled.
It actually takes you to one page prior to where the chapter actually starts, but that's not caused by this change.
=> [UX] Allow following links though hold/highlight dialog

plugins/statistics.koplugin/main.lua
See comment: https://github.com/koreader/koreader/issues/3185#issuecomment-328300123
> Maybe if there's a wait for people to tap screen, maybe someone would like to know how many books were imported?
=> Change message after import

frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerlink.lua, frontend/ui/widget/dictquicklookup.lua
See https://github.com/koreader/koreader/pull/3190#issuecomment-328332771
@robert00s Does this also solve the other issue you noticed?
=> [fix] Add current location to location stack from follow link popup

frontend/apps/reader/modules/readerrolling.lua
When following an internal link (ie: to footnotes), this will show for 1 second a vertical marker where the link target is.
<kbd>![link_target_marker](https://user-images.githubusercontent.com/24273478/30252418-a8738d82-9672-11e7-9d7e-6da0327a369c.png)</kbd>
I think it helps a lot, your eyes just jump to where the footnore is, no need to remember and look for the footnote number.
Only works with readerrolling/crengine, as for pdf, we only get the target page, not the precise xpointer that allows us to get the vertical position.
I would also have liked to have that when back from link, to again see where we were before jumping to link, but that's more complicated.
Dunno if some people may dislike it and if it should be made an option in the Links submenu.
~~Also, for some reason i don't …
=> Show vertical marker at target position when following a link

frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/modules/readerlink.lua
Been using this `Swipe to follow nearest link` for some weeks, which is more usable than `Swipe to follow first page link` (that I added some months ago).
I feel like removing `Swipe to follow first page link` but I'm not sure, may be some people would prefer it, dunno.
(These 2 are mutually exclusive).
Also added another option: `Swipe to jump to latest bookmark`.
May be useful for non-avid bookmarkers like I am, to remember a page with some map, table, ... so I can quickly jump back to it from the following pages that talks about stuff referenced there.
Also useful for books with no real TOC / chapters: I bookmark the in-book TOC page, so I can easily swipe to it to see where i'm at/pages remaining till next chapter.
=> Added Swipe to follow nearest link/to jump to latest bookmark

frontend/ui/menusorter.lua
=> [fix] MenuSorter: don't ignore user order without counterpart in default menu

frontend/ui/widget/configdialog.lua
Should fix https://github.com/koreader/koreader/pull/3194#issuecomment-328828994:
> Noticed 2 things: icons move a few pixels left or right upon selection/unselection, and the selected icon looks to me a bit tight between its 2 vertical lines.
=> Fix moving icons in config panel

frontend/ui/widget/configdialog.lua, frontend/ui/widget/iconbutton.lua, frontend/ui/widget/touchmenu.lua
See https://github.com/koreader/koreader/pull/3194#issuecomment-328828994 and next comment.
Added padding to IconButton, so that icon image and this padding are tapable.
TouchMenu (top menu) and ConfigDialog (bottom menu) updated to make use of that. This provides a wider sensitivity to menu buttons.
Top menu looks unchanged. Noticed a thing that was already there: the line under icons does not go as far to the right screen border as it does on the left. Couldn't figure how to fix that (didn't really understand the `bar_sep` business there...)
For the bottom menu, we should choose how wide we want the icons (3 alternatives in the code: i let in something similar to top menu).
=> Add horizontal_padding to IconButton

frontend/apps/reader/modules/readertypeset.lua
As reported by https://www.transifex.com/user/profile/slow_mo/ :)
=> Set Rendering Style, and Comments

kodev
Usage:
`./kodev run --graph`
You get fun little graphs like this while running:
And a PNG for sharing afterward:
Edit: for reference (as the default plots aren't great looking), also see http://www.gnuplotting.org/attractive-plots/
=> kodev: add --graph option for rudimentary memory use tracking

frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/infomessage.lua, frontend/ui/wikipedia.lua
Been stuck lately downloading 149 images over a slow wifi, that I couldn't cancel: had to wait 10 minutes. Only thing I wanted was to see the location on a map of some old city.
So, with this, one can abort download in the sequence of "Fetchin image N/M..." by just taping while the InfoMessage is displayed. We can't abort in the middle of an individual download, but we can do something in between, with a bit of coroutine magic.
Also allows for saving the incomplete downloaded EPUB, so I could have seen the map which must have been among the first few images.
Awaiting rewording suggestions :)
I am tempted to try something similar for the sdcv lookup (i've often been stuck the last days when testing tap/hold on links on a lookup for "something[7]. Next". But this would need rewriting the …
=> Wikipedia save as EPUB: allow for aborting download

frontend/ui/wikipedia.lua
When first images don't have a height or width attribute
=> Fix Wiki save as epub crash on certain pages

plugins/readtimer.koplugin/main.lua
Fix: Reader Timer crash when we start timer in Filemanager mode.
=> Prevent crash Timer in Filemanager

frontend/apps/reader/modules/readerhighlight.lua, frontend/ui/widget/dictquicklookup.lua
Finally understood the occasional crashes I got (which are less likely to happen now that the delayed selection clear() when leaving dictionary has been decreased from 1 to 0.5 second, but well, better ensure that).
A delayed clear() could reset hold_pos while a onHold/onHoldPan/onHoldRelease is in progress, resulting in hold_pos becoming nil and a crash:
```
./luajit: frontend/apps/reader/modules/readerhighlight.lua:310: attempt to index field 'hold_pos' (a nil value)
frontend/apps/reader/modules/readerhighlight.lua:310: in function 'lookup'
```
Can easily be reproduced by increasing the 0.5 to 2.5, and doing a new Hold after closing a dict window.
=> Fix potential crash when clearing hold highlight

frontend/apps/reader/modules/readerdictionary.lua, frontend/ui/trapper.lua, frontend/ui/wikipedia.lua
Explanation in comments in the code (lots of comments about that coroutine stuff, as I previously used them in wikipedia Save as EPUB, but I had a hard time re-understanding how they work - so futur coroutiners gets some kind of primer - if I indeed get that business right :)
All in the single readerdictionary.lua for now, for easier review/tests.
If that is acceptable, it should be splitted into a PR to koreader-base, and some other lua file for the dismissable_popen() function.
=> Dict lookup: allow cancelling with tap

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerhistory.lua, frontend/apps/filemanager/filemanagerutil.lua, frontend/readhistory.lua, frontend/ui/widget/menu.lua, plugins/coverbrowser.koplugin/covermenu.lua, plugins/coverbrowser.koplugin/listmenu.lua, plugins/coverbrowser.koplugin/main.lua, plugins/coverbrowser.koplugin/mosaicmenu.lua
Seen https://www.mobileread.com/forums/showthread.php?t=290611 , and I'm not sure we need a "Purge all books in history" feature. But we should at least be able to purge or delete from History (currently, when I want to do that, i have to: open the book, switch to File browser to get in that book directory, browse the directory to find the book, delete it, go back to History, repeat for the next book).
So, I just wanted to add "Purge .sdr" and "Delete" to the onHold buttons of History... and it lead me to having to do much more:
- Made the onHold buttons table similar to the one of File browser (use ButtonDialogTitle with the full filename as title, instead of a truncated one), just cause it's prettier, and for consistency.
- Added "Purge .sdr" and "Delete" to these buttons.
- Moved the …
=> Some History fixes and enhancements

frontend/apps/reader/modules/readerbookmark.lua, frontend/ui/elements/reader_menu_order.lua
Close: #3184
Bookmark browsing mode is now available from menu
=> Add bookmark browsing mode to menu

frontend/ui/widget/iconbutton.lua, frontend/ui/widget/touchmenu.lua
This is to get discussion started but it does reflect my input.
Edited to add screenshots after @poire-z's comment.
=> [UX] Smaller menu icons

frontend/apps/filemanager/filemanagerhistory.lua
Prevent visibility of readers's footer edges.
=> Remove rounded corners from fullscren History

frontend/ui/widget/configdialog.lua, frontend/ui/widget/imagewidget.lua
And unrelated small optimisation in imagewidget.
Followup of https://github.com/koreader/koreader/pull/3253#issuecomment-331666370
=> [UX] Smaller bottom menu icons

frontend/ui/widget/imagewidget.lua
Will need a base bump for https://github.com/koreader/koreader-base/pull/519
ImageWidget can use `mupdf.scaleBlitBuffer()` instead of `BlitBuffer:scale()` for better quality images.
For easy comparisons, one can set `G_reader_settings:isTrue("legacy_image_scaling")` to revert to the old method (let's keep that for some time, we need to see how mupdf behaves on a long session, if it does not leak, get slower, etc...).
ImageViewer uses it, and zoomed images are indeed of better quality.
Performance wise, on small images, old method is probably a bit faster than mupdf (but both < 1ms on icon images). On large images (Wikipedia images), zooming can go from 1000ms (old method) to 250ms (mupdf).
~~Also, for our chevrons, that are just scaled_for_dpi, only the original is cached by ImageWidget, …
=> ImageWidget: use MuPDF for scaling images

frontend/ui/widget/keyvaluepage.lua, plugins/statistics.koplugin/main.lua
Closes: #3236 and #3235
Details:
> Also, when looking in days, we see info how many hours we read. It would be great if we could tap a day, it opens info on book(s) we read that day with info pertaining to that day, and if we tap on book, we receive book info for that book.
> Statistics plugin is really great, I started to look in my reading statistics now much more, but all the time I can go only in one way. And I need to exit at lowest level of info. It would be great if I can use statistics plugin like part of menu, to go up and down within statistics data and exit at my wish, not when I have to.
Also added:
+ new statistics book by week
+ new statistics book by month
+ last year by week now we can see days in selected week
Screenshots:
=> Add back button to statistics

frontend/ui/size.lua
For years they've been smaller on higher DPI devices and likely very few people realized it was technically a bug. These values round up on lower DPI and smaller screen devices.
References https://github.com/koreader/koreader/issues/3265
=> [UX] Smaller borders

plugins/coverbrowser.koplugin/bookinfomanager.lua, plugins/coverbrowser.koplugin/covermenu.lua
We previously disabled cache, but that may cause excessive memory usage with big books. We now use a temporary cache directory, that we clean when no more needed.
See https://github.com/koreader/koreader/issues/3261#issuecomment-333122611
=> CoverBrowser: use a cache for crengine books extraction

frontend/device/generic/device.lua, frontend/document/credocument.lua, frontend/document/djvudocument.lua, frontend/document/document.lua, frontend/document/pdfdocument.lua, frontend/document/picdocument.lua
Support for colored rendering is already there for most engines/formats (CRE, PDF, Images). It just needs a few fixes, and enabling it. (Only reflowed PDF and DJVU are still greyscale).
Needs to manually add setting: `"color_rendering" = true` (any better name for this setting?)
It will use 4 times more memory for blitbuffers (32bits RGB vs 8bits greyscale), so, even if a platform supports colors, it should be togglable thru a menu item.
Will need a base bump for https://github.com/koreader/koreader-base/pull/524.
Only observable for now with the emulator, but I guess some tweaks on the android side could make it colorful too.
edit:
- if this is going to be togglable thru menu, we'll need to clear tile cache (otherwise, cached grey pages would still be used once color is enabled).
- seems …
=> Allow for colored rendering

frontend/apps/opdscatalog/opdscatalog.lua
I noticed this dialog was undescriptive. I'm not entirely sure what to go for instead of Cancel/OK though.
<kbd>Don't read</kbd>/<kbd>Read</kbd>
or
<kbd>Read later</kbd>/<kbd>Read now</kbd>
=> [lang] OPDSCatalog ConfirmBox ok_text/cancel_text

kodev
See https://github.com/koreader/koreader/issues/2878#issuecomment-326796777
Also fix `./kodev run -h` as alias for `--help` as it's always overwritten by `-h` in the sense of the much more important `--screen-height`.
=> kodev: run with catchsegv by default

frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/device/android/device.lua, frontend/device/generic/device.lua, frontend/device/sdl/device.lua, frontend/document/credocument.lua, frontend/document/djvudocument.lua, frontend/document/document.lua, frontend/document/pdfdocument.lua, frontend/document/picdocument.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/elements/screen_color_menu_table.lua
New menu item in Screen submenu (and screen submenu a bit re-ordered).
hasColorScreen enabled for SDL device.
I could have either required a restart (and clear all caches, but I didn't want to bother with that), or deal with each document type so it supports toggling color rendering, which is what I did.
Follow-up of #3276
=> Allow for toggling color rendering

frontend/apps/reader/modules/readerdictionary.lua, frontend/ui/widget/imageviewer.lua
Show 'Follow Link' even when no dict installed: https://github.com/koreader/koreader/pull/3190#issuecomment-333406376 as suggested
Full refresh when showing ImageViewer: https://github.com/koreader/koreader/issues/3274#issue-261702634 (O/T:...)
=> Small fixes to dict Follow links and ImageViewer

frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/modules/readerview.lua, frontend/document/credocument.lua
Avoid unnecessary work in `ReaderView:onSetViewMode() `and `ReaderRolling:updatePos() `that would result in TOC being reset and rebuilt (which can take time on books with huge TOC) during reader setup.
See https://github.com/koreader/koreader/issues/3261#issuecomment-333560902.
(IT works fine in my tests and it looks simple enough, but given the heavy use of indirections in readerui/readerview setup - postSomethingCallback, events propagated to all widgets... - it's hard to foresee side effects...)
credocument.lua updated just to logically use `DCREREADER_VIEW_MODE `(and to mention the value must be the same as in readerview) , which defaults to `page`, even if we know that `scroll` mode currently crashes.
=> credocument reader optimisation (avoid multiple TOC builds)

plugins/coverbrowser.koplugin/bookinfomanager.lua
It wouldn't extract info from a book, but that book opened without problem for reading.
That book css contains a font-family applied to body (that doesn't look strange!):
```
@font-face {
font-family: "MinionPro-Regular";
font-style: normal;
font-weight: normal;
src: url(fonts/MinionPro-Regular.otf);
}
body {
margin-right: 20pt;
margin-left: 15pt;
font-family: "MinionPro-Regular";
font-style: normal;
font-weight: normal;
}
```
It looks like crengine is trying to reach parent->font, which may be wasn't defined and could be the default font the reader set.
Removing that body.font-family from the css, or adding a default font before loading document, avoid the crash. So let's do that.
=> CoverBrowser: avoid crash when indexing some cre documents

frontend/apps/reader/modules/readerrolling.lua
394be8a (#2855) and 2b3b310 (#3183) introduced side effects (scroll mode crashing and TOC being reset and rebuild). This reverts parts of them not yet reverted.
See https://github.com/koreader/koreader/issues/3282#issuecomment-333882828 and further discussion
(not a full revert, I kept the require re-ordering, and the 2nd chunk I reverted yesterday to fix TOC reset).
=> Revert 2 commits that caused side effects

plugins/goodreads.koplugin/goodreadsapi.lua, plugins/goodreads.koplugin/goodreadsbook.lua
See: https://www.goodreads.com/topic/show/18944471-announcement---migrating-all-api-endpoint-to-https
```
To better protect user privacy and security, we will be enabling HTTP to HTTPS redirection for all requests to goodreads.com on December 4th.
To prevent your applications from breaking, please do one of the following before December 4th:
Make sure your applications support HTTPS redirects
Update your applications to make only HTTPS requests
```
=> Migrate Goodreads to https

frontend/apps/reader/modules/readerrolling.lua
Was only noticable on Kindle (which uses REAGL as partial refresh) where a flash occurs (on kobo, the second refresh, with the same content, is not noticed).
On the emulator, we saw at end of opening with readerrolling 2 log lines like
```
10/04/17-21:54:08 DEBUG refresh on physical rectangle 0 0 600 610
10/04/17-21:54:08 DEBUG refresh on physical rectangle 0 0 600 610
```
We have only one with PDF/readerpaging.
Should resolves the 3rd item in #3230. @robert00s : can you confirm (and that you don't notice any side effects) ? (I verified it by enabling REAGL on kobo - Kindle is the real test).
=> Avoid multiple refreshes when opening credocuments

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/modules/readertoc.lua, plugins/statistics.koplugin/main.lua
This gives the page position to these modules even in scroll mode. Closes #3282
Also, in readerrolling: don't query battery/charging status when crengine does not need it (used only when it shows its top progress bar).
=> Fix footer, stats, TOC position with cre in scroll mode

frontend/ui/widget/buttontable.lua, frontend/ui/widget/focusmanager.lua
Using keyboard arrow keys on the emulator to select buttons in the OnHold button tables (in History or File Browser) crashes when encountering a separator or when the number of buttons in a row changes.
=> Fix crash with keyboard navigation of onHold buttontables

frontend/apps/reader/modules/readerconfig.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/infomessage.lua
"partial" refresh causes a full (without black flash) refresh on Kindle (which uses REAGL mode for partial refresh). This causes a full redraw of widgets, which is a bit distracting with some of them:
- dictquicklookup: when showing next definition
- infomessage: when displaying a new one (Wikipedia Save as epub)
Also fix bottom menu, that even when closed, would still register bottom area as dirty: this would cause top menu navigation to cause a full partial refresh, only noticable on Kindle.
See #3230 for details about these. Closes #3230
=> Avoid some full refreshes on Kindle

frontend/apps/reader/modules/readermenu.lua, frontend/ui/elements/menu_activate.lua
I added an option to disable show bottom menu every time when top menu (main) is opened.
Setting -> Screen -> Activate menu -> Show bottom menu
=> Option to disable show bottom menu on top menu activation

frontend/device/generic/powerd.lua, spec/unit/frontlight_spec.lua
I believe this should be `if isKobo()`, or better yet that the entire
block should be moved to `KoboPowerD:init()` because afaik that is the
only platform where the system doesn't provide trustworthy frontlight
information. But to be absolutely sure that I don't break anything (and I
don't want to spend any time on this atm) I'm temporarily excluding only
Android where this behavior is known to be problematic.
See discussion in https://github.com/koreader/koreader/issues/3118#issuecomment-334995879
References #3118 (using keyword "references" because phrases like "possibly fixes"
result in GH autoclose).
=> [fix, Android] Don't steal frontlight control on start

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/ui/widget/buttondialog.lua, frontend/ui/widget/buttondialogtitle.lua, frontend/ui/widget/buttontable.lua, frontend/ui/widget/confirmbox.lua, frontend/ui/widget/container/framecontainer.lua, frontend/ui/widget/datewidget.lua, frontend/ui/widget/frontlightwidget.lua, frontend/ui/widget/imageviewer.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/multiconfirmbox.lua, frontend/ui/widget/multiinputdialog.lua, frontend/ui/widget/textviewer.lua, frontend/ui/widget/textwidget.lua, frontend/ui/widget/timewidget.lua, frontend/ui/widget/toggleswitch.lua
Includes better centering of texts in their boxes, and additional widget fixes. See individual commit texts.
Solves items 3, 4, 5, 6 of #3265.
Added padding_top & co to framecontainer, as talked about in #3263 by @Frenzie.
All widget lines above the ButtonTable have been removed, to use the included `zero_sep` line of button table instead (which happen to be gray - I tried to change it to black, but it looks better when it is gray like all the others)
For reference, some doc and talks about vertical centering of text:
https://www.freetype.org/freetype2/docs/tutorial/step2.html
https://explodingpixels.wordpress.com/2009/01/29/drawing-text-about-its-visual-center/
https://stackoverflow.com/questions/1055851/how-do-you-draw-a-string-centered-vertically-in-java
For reference again, in case …
=> Fix appearance of widgets that uses ButtonTable

.ci/install.sh, .circleci/config.yml, .gitignore
* Update luarocks/shellcheck/shfmt check based on `deps-{{ arch }}-{{ checksum ".ci/install.sh" }}`
* We generate a git-rev-base to check whether we can trust the cache
with `build-{{ arch }}-{{ checksum "git-rev-base" }}`
Binary dependencies require `{{ arch }}` because there are different CPUs used on the servers.
More information here: https://discuss.circleci.com/t/use-the-arch-cache-template-key-if-you-rely-on-cached-compiled-binary-dependencies/16129
=> CircleCI cache fix

plugins/statistics.koplugin/main.lua
Previously we didn't write stats to DB on document exit :( 
Now should be fine.
=> [statistics] Fix onPosUpdate and save stats when closing document

frontend/apps/reader/modules/readerrolling.lua
This makes _Go to_, _Skim to_ and TOC page selection work in scroll mode, and page given to other module more accurate.
Previously, we were actually showing the page before the action was taken, like:
tap forward (actually on page 45, footer says: page 44)
tap forward (actually on page 46, footer says: page 45)
tap backward (actually on page 45, footer says: page 46)
(ref: https://github.com/koreader/koreader/pull/3304#issuecomment-335257133)
=> Fix cre scroll page update and allow jumping to page

frontend/ui/widget/menu.lua, frontend/ui/widget/multiconfirmbox.lua
Rationalize horizontal construction of Menu items (TOC, Bookmarks, Classic file views) for more even padding.
Align "x" close button diagonaly with top right border and title.
Also add forgotten scale_for_dpi to MultiConfirmBox
Solves items 1 & 2 of #3265.
The 'x' looks also a bit misaligned in TextViewer and KeyValuePage titles. I'll try to do the same to them if there is no negative feeback about this one (and when I see how it does on android).
=> Small visual fixes to Menu

frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/elements/flash_ui.lua, frontend/ui/widget/button.lua, frontend/ui/widget/checkbutton.lua, frontend/ui/widget/iconbutton.lua, frontend/ui/widget/keyvaluepage.lua, frontend/ui/widget/menu.lua, frontend/ui/widget/touchmenu.lua
May give a feeling of more responsiveness (real or just a feeling, I'm not sure).
Thought it would solve the "papercut glitches" (see #3130) when there's lots of refresh going on (like when changing fonts), but it does not (and may be accentuates them in some cases).
But it's nice to have I think (it also speeds up working with the emulator with X11 forwarded over slow ssh link).
Alternate wording for the menu checkboxed item ?
`Flash UI elements` ? `UI Feedback` ? `UI animations` ?
=> Allow for disabling flashing of menu, icons and buttons 

frontend/apps/filemanager/filemanagerbookinfo.lua, plugins/coverbrowser.koplugin/listmenu.lua, plugins/coverbrowser.koplugin/mosaicmenu.lua
Decode XML entities in series metadata and display decimal in series number if any.
See https://github.com/koreader/koreader/issues/3347#issuecomment-336268606. Closes #3347.
=> calibre 'series' metadata fixes

frontend/ui/widget/menu.lua
Would change this:
to this:
(so, with a little bit more chance for long items to be truncated)
=> Menu (TOC, bookmarks): add padding before right text

frontend/apps/filemanager/filemanager.lua, frontend/apps/reader/readerui.lua, frontend/ui/widget/filechooser.lua
When going from reader to filemanager, we are in the directory containing the last_file. With this, we will also be on the page showing this last_file.
When in filemanager and going up (".."), we will also be on the page containing the directory we came from (I think this was what the OP of https://www.mobileread.com/forums/showthread.php?t=290695 wanted).
Previously, we were either on page 1 (when we haven't yet browsed that directory in this koreader session), or on the page we were when we last visited this directory.
In most cases, this will be the same page, except in the following:
when "Start with: last file", and opening File browser for the first time: we were previously always on page 1
when opening files from History, and going to File browser: we were previously always on page …
=> FileBrowser: change page to show last file or previous subdir

frontend/document/document.lua, plugins/kosync.koplugin/main.lua
This is done by/for kosync plugin at each opening, because the docsettings was re-opened and saved for this, but later overwritten by the current koreader docsettings - so it was redone each time. This correctly adds this partial_md5_checksum to the current koreader docsettings, which will be saved on document closing - so it will not be redone next time.
Note: this partial_md5_checksum is not (yet) used by anything, but it will be there when kosync wants to use it.
Quick fix for #3132 (to avoid writting a metadata.lua at each opening, that will anyway be overwritten when closing document).
=> Avoid recalculation of partial_md5_checksum at each opening

kodev
You'll still have to call it with `ANDROID_ARCH=x86 ./kodev build/release/run android`.
Don't forget to `./mk-luajit.sh clean` in luajit-launcher when changing architectures.
* Bump android-luajit-launcher
This includes the fix for Android 8. Fixes #3126.
* Bump base
=> kodev: Add $ANDROID_ARCH to enable x86 build

frontend/ui/widget/touchmenu.lua
To make it more alike bottom menu:
- left and right border not displayed
- line below icons extends to screen borders
- same bottom border size as bottom menu top border
And make separator lines have same padding on both sides
Solves items 7 & 8 of #3265.
The absence of borders on bottom menu (ConfigDialog) is actually probably a bug, in the very complex computation of widgets, which in the end exceed the provided container width. BottomContainer actually do the centering, pushing left and right border off-screen.
We do it the same in TouchMenu (with the help of a CenterContainer, TopContainer, unlike BottomContainer, does not do any centering), but this time, it's not a bug but intentional :)
(Fixing ConfigDialog is not obvious, and I personally prefer not seeing left & right borders - …
=> Small visual fixes to top menu

frontend/apps/reader/skimtowidget.lua, frontend/ui/widget/closebutton.lua, frontend/ui/widget/datewidget.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/frontlightwidget.lua, frontend/ui/widget/keyvaluepage.lua, frontend/ui/widget/textviewer.lua, frontend/ui/widget/timewidget.lua
Normalize widgets' title heights, and vertical alignment of their CloseButton.
CloseButton mods similar to what I did in menu.lua to MenuCloseButton.
A bit more hacks for TextViewer as it uses a TextBoxWidget (as we don't know if the title provided will fit on one line) unlike all the others.
KeyValuePage: made the former `1/3 ---` page count an option, as we were no more using it since we added page navigation at bottom. Its presence (with some empty text) was adding some padding to left of line, and may overlap with the title text (if if contains chars that goes below baseline like p/g). I did like this way of showing page count, so I kept the code in with this new `use_top_page_count` that no widget is using for now.
@robert00s : i changed the Close button height, and it may have an …
=> Fix some widget title height and close button alignment

frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/modules/readerhighlight.lua
Followup of @robert00s 's work on #3034 and #3275: enable `edit` in the `delete|edit` menu we get when tapping on a highlight, by just using the Rename bookmark feature.
Also fix a few crash possibilities encountered when testing:
- when a bookmark has been renamed, we can't find the page number/slot from its text, so #3034 could crash after #3275 (nor can we use the current page, as for credocuments, page numbering can change with geometry): so we need to do a full scan of the highlights to find the page slot from which we can delete highlight
- comparing pos0 (a string for credocuments, but a table for pdfdocuments) works when in the same reading session (when the bookmarks and highlights tables contain the same reference to the same object), but after a restart, when read from the …
=> Enable Edit (rename bookmark) when tap on highlight

frontend/util.lua, spec/unit/util_spec.lua
util.secondsToClock(3599, true)) shows 0:60.
This commit fix it.
=> Fix util.secondsToClock

frontend/ui/widget/progresswidget.lua
Ticks (toc markers) in progressbar are displayed incorrectly.
=> Fix location of progress bar ticks

frontend/apps/filemanager/filemanagerbookinfo.lua, frontend/util.lua
https://github.com/koreader/koreader/pull/3381#issuecomment-338246490
(In french, we would use a space instead of a comma, and `octets` instead of `bytes`, but I'm perfectly fine with it as is.)
If there's a need for internationalisation:
https://ux.stackexchange.com/questions/23667/is-using-a-comma-as-a-number-separator-a-cultural-thing
=> Added util.getFormattedSize()

frontend/apps/filemanager/filemanager.lua, frontend/ui/widget/filechooser.lua, frontend/ui/widget/imagewidget.lua, frontend/ui/widget/menu.lua, plugins/coverbrowser.koplugin/covermenu.lua, plugins/coverbrowser.koplugin/listmenu.lua, plugins/coverbrowser.koplugin/main.lua, plugins/coverbrowser.koplugin/mosaicmenu.lua
I noticed since #3351 that it took 2 to 3 seconds to switch from Reader to FileBrowser.
Thought it would be some docsettings save or crecache stuff, but no: it was actually CoverBrowser doing many renderings, and in mosaic mode with 9 thumbnails, it was actually doing 3x9 = 27 renderings...
One additional time because of #3351 and its simple way of doing what it does.
One other unneeded time because I didnt thought much about the plugin initialization when I did it, and it could be optimized in a few ways.
See individual commit messages.
I haven't tested this as long as I did the first time :), but it seems ok, hope I haven't broken anything.
(The long diff in covermenu.lua is just indentation for wrap into `UIManager:nextTick(function()...` )
=> CoverBrowser: Speed up switch from Reader to FileBrowser

frontend/ui/elements/screen_fullscreen_menu_table.lua
As now vieport changing should work on Android (finished #3148, https://github.com/Frenzie/koreader-base/commit/ad47ca64d4941a7a2600d41eb86a3fc9f9b99e23)
It's time to use it in "Fullscreen" (https://github.com/koreader/koreader/issues/3148) Android toggle.
Not tested. Testers welcome.
=> Fullscreen android - resize window after toggle fulscreen

frontend/device/pocketbook/powerd.lua
This PR removes the need for hard-coded ``/sys/device/*``-paths in ``pocketbook/powerd.lua`` to get charging/battery-status information and uses libinkview instead.
=> PocketBook: Use libinkview for battery-percentage/charging status

frontend/apps/filemanager/filemanagerbookinfo.lua, frontend/ui/widget/keyvaluepage.lua
Question of taste (so it's ok if Before is preferred).
Before:
After:
=> KeyValuePage: align value to the right when half-overflow

frontend/ui/widget/dictquicklookup.lua
Probably since https://github.com/koreader/koreader/issues/3305#issuecomment-334732632, when saving some wikipedia page as Epub, and deciding to switch to this epub when done, the highlight menu (no more closed since above fix) would remain, even after switching to filemanager and other documents.
Later, when exiting koreader, this forgotten highlight menu would be shown (as the last widget managed by UIManager), yet easy to dismiss by taping anywhere, but well, let's fix this.
=> Wiki save as epub: close highlight menu when switching document

frontend/apps/reader/modules/readerdictionary.lua
Upstream uses `-e` rather than the `-f` that was first introduced in our fork.
References https://github.com/koreader/koreader/issues/3429#issuecomment-339749396
=> [fix] Dictionary no fuzzy search flag

kodev
=> kodev: add assert_ret_zero after make android-ndk

frontend/ui/widget/configdialog.lua, frontend/ui/widget/toggleswitch.lua
Close: #2538 
It truncates strings (item texts and buttons) if they are too wide. It's also possible to add hold_callback function when we hold name_text (not used yet).
Before:
After:
Before:
After:
Before:
After:
=> Improve ConfigDialog

plugins/newsdownloader.koplugin/feed_config.lua, plugins/newsdownloader.koplugin/main.lua
Compatibilty for existing NewsDownloader users. There would be no need to adapt their configuration files to changes in N.D.
+ fix sample feed configuration (pc world was not working for download_full_article)
As my `./kod run` doesn't work (after pull?) [neither clean nor build works] I wasn't able to test it:(
=> NewsDownloader: Compatibility for uses with previous configuration files

.ci/helper_luarocks.sh
Apply junit testcase time fix so CircleCI can actually do something useful
with the results. This can be removed once there is a busted 2.0.rc13 or final
See https://github.com/Olivine-Labs/busted/commit/830f175c57ca3f9e79f95b8c4eaacf58252453d7
=> [CI] apply patch for busted junit testcase time

plugins/newsdownloader.koplugin/main.lua
Displays number of currently processed item e.g :
"Processing 1/7" instead of "Processing"
=>  News downloader: Number items in processing

README.md
Tested on darwin-15.6, darwin-16.7 and darwin-17.2. This should fix #2651 and fix #3464.
=> [fix] add OSX build prerequisites cmake and makedepend

frontend/apps/reader/modules/readerdictionary.lua
When looking for .ifo to populate Dictionary settings menu, avoid walking sub-directories once we found a .ifo, as these sub-directories may contain a lot of images and other subdirs.
See https://github.com/koreader/koreader/pull/3144#issuecomment-344722499
=> Speedup dictionaries init

frontend/ui/data/creoptions.lua
Before: see https://github.com/koreader/koreader/pull/3194 https://github.com/koreader/koreader/pull/3356
After:
<kbd>![after](https://user-images.githubusercontent.com/24273478/32904741-633ce780-caf8-11e7-8469-8fb37722522b.png)</kbd>
I once tried that before @robert00s ' recent works on configdialog, and the texts were overflowing the toggles, so I guess that's the reason why it was not a toggle and stayed text. But now, as it fit, I see no reason not to upgrade it to ToggleSwitch and have them all look alike.
=> Use toggle for CRE Contrast in bottom menu

frontend/apps/reader/modules/readerdictionary.lua, frontend/ui/widget/dictquicklookup.lua
I prefer to see as much definitions as possible on the dictionary screen, it makes it easier to find what you are looking for without turning pages, so I would like to add this option.
I wasn't sure about the terminology to use in the options so currently it is simply "Full screen".  I think "Full screen pop-up" or "Full screen dialog" could work too.
I left the default behavior as it was, so it's turned off by default.
=> Option to show dictionary in full screen

frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerview.lua
drawXPointerSavedHighlight() and onTapXPointerSavedHighlight were looping thru all credocuments highlights, which was expensive.
Now, we first check with cheaper getPageFromXPointer() the highlights are on the current page before doing more expensive stuff.
Hope I got that right and that won't start ignoring some highlights...
Closes #3503.
=> Optimize cre highlights onTap and drawing

tools/wbuilder.lua
Full stack trace:
```
./luajit: ./ffi/blitbuffer.lua:173: attempt to index local 'color' (a number value)
./ffi/blitbuffer.lua:173: in function 'set'
./ffi/blitbuffer.lua:602: in function 'setter'
./ffi/blitbuffer.lua:944: in function 'paintRect'
./ffi/blitbuffer.lua:1135: in function 'paintRoundedRect'
frontend/ui/widget/container/framecontainer.lua:66: in function 'paintTo'
frontend/ui/widget/container/inputcontainer.lua:81: in function 'paintTo'
frontend/ui/uimanager.lua:616: in function '_repaint'
frontend/ui/uimanager.lua:683: in function 'handleInput'
frontend/ui/uimanager.lua:765: in function 'run'
./tools/wbuilder.lua:462: in main chunk
```
To reproduce:
1. Uncomment UIManager:show(Background:new()) in wbuilder.lua
2. Start wbuilder
Note: the new grey background …
=> Fixes ffi/blitbuffer.lua:173: attempt to index local 'color' (a number value)

frontend/ui/wikipedia.lua
Tests with mupdf 1.12 as epub rendering engine had it report this warning on wikipedia saved as epub:
`error: css syntax error: expected value (OEBPS/stylesheet.css:36)`
=> Fix typo in wikipedia epub stylesheet

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua
Just like Dictionary lookup history, with symbols to distinguish lookup queries from full page viewing, and language in brackets if different from current language (so users with one single language are not bothered by it). Taping on an item just relaunch the right query with appropriate language/full page or not.
<kbd>![wikipediahistory](https://user-images.githubusercontent.com/24273478/34078985-5fad9af8-e324-11e7-8d09-96ecd1d3985a.png)</kbd>
Also changed Disable to Enable in some menu items to be more positive.
=> Adds Wikipedia history

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua, frontend/device/generic/device.lua, frontend/device/kindle/device.lua, frontend/ui/elements/screensaver_menu.lua, frontend/ui/screensaver.lua, frontend/ui/widget/bookstatuswidget.lua, frontend/ui/widget/button.lua, frontend/ui/widget/infomessage.lua, frontend/ui/widget/inputtext.lua, frontend/ui/widget/screensaverwidget.lua, frontend/ui/widget/toggleswitch.lua, plugins/statistics.koplugin/main.lua, plugins/statistics.koplugin/readerprogress.lua
I prepared screensaver with new options. Tested on Kindle. Please check how it works on Kobo.
Closes: #1809 and #2904
Now we have that options:
+ cover image
+ book status 
+ random image (now we can choose folder with foldermanager)
+ reading progress
+ message (we can enter showing text) 
+ disable
I also added an option to define when the screensaver should be turned off. The default is after waking up the device, but also can be turned off after a few seconds or after tap screen. These options can be useful with sleeping covers.
Some screenshots:
=> Add new options to screensaver

frontend/ui/trapper.lua, frontend/ui/wikipedia.lua
- Fix links to wikipedia pages containing '?oldid=123', that wouldn't work when used back thru the API.
- Make external links to other wikipedias with a different langage work (it didnt work for non-ascii page titles)
- Speedup download of images by using a newly added 'fast_refresh' option to Trapper:info() to bypass UIManager.
Timing the images download part (which often takes 30s to a few minutes) shows that for smal images:
- http request would take 300ms
- updating the InfoMessage "Fetching image 3/47..." would take 700ms.
With this Trapper option,  the display of the InfoMessage is really faster (although a bit hacky, but I didn't find another way of getting speed than blitting to Screen and bypassing UIManager).
It's still slow, mainly because our http.lua/socket.lua code is doing, …
=> Wikipedia Save as EPUB: fix some wiki links and speedup download

frontend/apps/filemanager/filemanager.lua
When the path in file manager is too wide we truncate it at the beginning like that:
before
after
=> Truncate path in filemanager

frontend/ui/uimanager.lua, frontend/util.lua, plugins/calibrecompanion.koplugin/main.lua
Specifically:
- wake up periodically when ZMQs are active to process them, even if there are timed events pending
- create intermediate directories when receiving books to directories that don't exist yet.
This is enough for basic usage; koreader will connect to calibre and can receive books. Other features like the list of books on the device being displayed in calibre do not yet work, however.
=> Basic fixes to calibre-sync

frontend/apps/filemanager/filemanager.lua
Adding missing information after copying or cutting in FileManager.
Adding confirm when file exist in destination location.
=> Add info when copy or cut file

frontend/apps/filemanager/filemanagerbookinfo.lua, frontend/apps/reader/readerui.lua, frontend/document/credocument.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua
If cre:loadDocument() failed recognizing the document format (for example: a .epub in which /mimetype file is absent - crengine looks for this file in a zip to consider it a valid epub), koreader would still keep calling other methods on it, which would make crengine segfaults. With this, we can properly return an error
if document opening failed, so we never call other methods.
Will need a base bump for https://github.com/koreader/koreader-base/pull/582
=> credocument: deal with loadDocument() failures

kodev
- kodev-run: fix use of $args (see https://github.com/koreader/koreader/pull/3379#issuecomment-346462122)
- kodev-build: build the emulator in debug mode, for consistency with kodev-run (see https://github.com/koreader/koreader/pull/3439#issuecomment-354370470)
=> kodev: two small fixes

frontend/device/pocketbook/device.lua, frontend/ui/uimanager.lua
Partial fix for https://github.com/koreader/koreader/issues/3477
Partial, as it will safe the state when suspending the reader by pressing the power-button.
However, it will still **not** safe the state when Pocketbooks autoPowerOff-Feature kicks in, as this does not create an event (e.g. no EVT_BACKGROUND) of any kind. 
As it is possible to disable and re-enable the autoPowerOff-Feature altogether i'll somehow work around this second issue, but this will involve ``input-pocketbook.h`` in ``koreader-base`` again, so i'll prepare another PR for that.
=> Partial fix for 3477

frontend/ui/elements/screensaver_menu.lua, frontend/ui/screensaver.lua
Use "message" as the default for screensaver (instead of "disable") (https://github.com/koreader/koreader/pull/3535#issuecomment-353337143)
On Kobo 
Fix: display message on poweroff or reboot (https://github.com/koreader/koreader/pull/3535#issuecomment-352355865)
Allows for overwritting these default messages with the classic screensaver settings, by just prepending "poweroff_" or "reboot_" to them. (https://github.com/koreader/koreader/pull/3535#issuecomment-352498497)
So one can manually add to its settings.reader.lua:
```
"poweroff_screensaver_type" = "random_image" or "message", "cover", "bookstatus", "readingprogress", "disable",
"poweroff_screensaver_dir" = "path to same as screensaver_dir or alternate dir for poweroff image(s)",
"poweroff_screensaver_message" = "message to use …
```
=> screensaver: change default & show messages on reboot and poweroff

frontend/apps/reader/skimtowidget.lua
in relative page turning in skim, errors appear when page number is less than 10, and you press -10 in skim it gives warning and the page doesn't change, this happens in pdf. 
"update" method solves this if it comes first.
=> small skim problem

frontend/apps/reader/modules/readerdictionary.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/htmlboxwidget.lua, frontend/ui/widget/scrollhtmlwidget.lua, frontend/util.lua
This pull request adds a generic HTML widget modeled after the text widget, and HTML dictionary support. HTML dictionaries can have their own CSS (for X.ifo it must be X.css). The base CSS just resets the margin and sets the font.
Note that the widget doesn't handle links, that wasn't needed for the dictionary.
Closes #1776.
=> HTML dictionary support

frontend/apps/reader/modules/readerdictionary.lua
Happened (example in https://github.com/koreader/koreader/issues/3429#issuecomment-339589096) when some dictionaries files have been removed, while these were still referenced in the 'dicts_disabled' setting.
=> Fix negative nb of enabled dictionaries

frontend/apps/reader/modules/readerdictionary.lua, frontend/ui/widget/htmlboxwidget.lua
- Enable Mupdf color rendering in HtmlBoxWidget.
- Fix possibility of crash in HtmlBoxWidget:free() (I don't think a crash can happen with the current master code, but I have some work in progress that uses more free() to prevent memleaks and I had some crashes there, so let's fix it now).
- Allow for user's hooks for HTML dict to tweak/fix the bad HTML of some dicts, by allowing users to put a LUA function in some file named as the .ifo with a .lua extension (https://github.com/koreader/koreader/pull/3573#issuecomment-355848649)
With a painfully crafted [PetitRobert2007_1.1.lua](https://github.com/koreader/koreader/files/1615366/PetitRobert2007_1.1.lua.txt), I managed to turn this:
(the HTML returned is really really bad, full of errors and inconsistencies)
into:
Too bad I won't be using …
=> HTML dict: enable color rendering and per-dict user fix html func

frontend/ui/widget/scrollhtmlwidget.lua
Continuous scroll with tap (when you reach bottom of definition, tap leads you to the next definition) was working on text definitions, but not on html definitions
=> HTML dict: fix continuous scroll with tap

frontend/ui/widget/keyvaluepage.lua
The PgUp and PgDown keys work in reader, dict lookup results... but they didn't work in KeyValuePage.
Useful on the emulator when using Lookup history.
=> KeyValuePage: make PgUp and PgDown key go to prev/next page

frontend/apps/reader/modules/readerdictionary.lua
Revert 338d14edb78c94bc528baf0bf20c5af1493a9f43 (#3489), as it would prevent listing some dictionaries (and possibly knowing they are HTML dicts) that sdcv would use and return results from.
Now, we simply just don't walk into "res/" subdirectories, which is where resource files should be per startdict specs.
See https://github.com/koreader/koreader/pull/3573#issuecomment-356984670
=> Fix speedup of dictionaries init

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerfilesearcher.lua, frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/filemanager/filemanagersetdefaults.lua, frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/modules/readertoc.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/widget/filechooser.lua, frontend/ui/widget/menu.lua, frontend/ui/widget/spinwidget.lua
Close: #2013 and #3488
+ Allow filenames to wrap so that we can see the full name
+ Configure number of items per page (from 6 to 24) - default is 14
+ The font size is calculated depending on number of items
+ Used for File browser, History, Search Result, Table of contents (only single line), File chooser, OPDS catalog
=> Wrap names and configure number of items per page

frontend/apps/reader/modules/readerdictionary.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/htmlboxwidget.lua, frontend/ui/widget/scrollhtmlwidget.lua, frontend/util.lua
=> HTML dictionary link support

frontend/util.lua, plugins/backgroundrunner.koplugin/main.lua, spec/unit/background_runner_spec.lua
On kindle voyage, the background runner may still execute a while even device has been suspended. Because kindle stock software may wake up the device to update itself. The behavior of the stock software impacts KOReader. For example, the AutoFrontlight plugin may turn on the frontlight unexpectedly.
=> Do not execute background runner if device is suspended

frontend/apps/cloudstorage/cloudstorage.lua, frontend/ui/network/manager.lua, plugins/calibrecompanion.koplugin/main.lua
This enables connecting to calibre and FTP without Internet connectivity.
Pinging @robert00s @mk-f
=> [feat] Add NetworkManager:isConnected()

frontend/apps/filemanager/filemanager.lua, frontend/ui/widget/filechooser.lua
I added the option to sort books by reading percent. Two options to choose from:
+ sort books when book not yet open are first listed
+ sort books when book not yet open are last listed
I'm not sure that this will not affect the performance of the file browser. I tested on my Kindle and I didn't notice any decrease in performance.
=> Filemanager - sort by percent of book

frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/trapper.lua, frontend/ui/uimanager.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/imageviewer.lua, frontend/ui/widget/scrolltextwidget.lua, frontend/ui/widget/textboxwidget.lua, frontend/ui/widget/trapwidget.lua, frontend/ui/wikipedia.lua
Allows to (optionally) show images in wikipedia lookup results (one image) and on the full page (multiple images), so I don't need to Save as EPUB when I want to see a location on a map, a painting, a famous person's face. Have all that smooth and interruptible.
Details in the individual commit messages.
Summary of what this does in this 3Mb animated gif:
<kbd>![wikipedia_images_animation](https://user-images.githubusercontent.com/24273478/34988036-90df85e0-fabd-11e7-9ab9-464ba397c967.gif)</kbd>
I'm not sure why github displays my symbols correctly [here](https://github.com/koreader/koreader/commit/506d22eb7ccc265aaff18e18015208c8791f55ea#diff-31a2b803ff2483711a7238c8f085fb5fR391) but not [there](https://github.com/koreader/koreader/commit/549ffff67be117f13e6052d67693c0152469902f#diff-94a0 …
=> Show images in wikipedia lookup results

frontend/ui/widget/menu.lua
On devices with keyboard (also on emulator).
Last item on page + key down = next page and select first item 
First item on page + key up = prev page and select last item
=> Proper page changes using the up and down keys

frontend/apps/reader/modules/readermenu.lua, frontend/ui/elements/screensaver_menu.lua, frontend/ui/screensaver.lua, frontend/ui/widget/imagewidget.lua
Followup to #3572 to have a better default for poweroff/reboot instead of `message`: use the same settings as chosen in menu for Sleep/Suspend, and add to it a small overlay message, so the user can distinguish between suspend (no message) and poweroff (overlay message). (does not work when "Leave screen as is", as we took the shortcut of returning early and not displaying any widget at all).
See https://github.com/koreader/koreader/issues/3610#issuecomment-358059678 (and https://github.com/koreader/koreader/pull/3535#issuecomment-353461264 for the overlay idea,)
Closes #3591. Closes #3610.
Since I made these screenshots, I moved the message to the top right, so it does not hide the bottom widget parts:
<kbd>![screensaver1](https://user-images.githubusercontent.com/24273478/35147551-4cfefc …
=> Screensaver: for poweroff, use menu settings with added overlay message

frontend/ui/widget/bookstatuswidget.lua, frontend/ui/widget/keyvaluepage.lua, plugins/coverbrowser.koplugin/listmenu.lua, plugins/coverbrowser.koplugin/mosaicmenu.lua
crengine may now give us multiple authors (if multiple `<dc:creator>` in epub metadata) separated by `\n`.
Deal with that where needed. Limit the number of authors displayed in coverbrowser views.
See discussion in #3583. Closes #3583.
Will need a crengine bump for https://github.com/koreader/crengine/pull/93 to get these `\n`.
Should give us:
<kbd>![list_et_al](https://user-images.githubusercontent.com/24273478/35186018-b3da5ee6-fe0d-11e7-895a-5ba3a6cc269e.png)</kbd>
<kbd>![mosaic_et_al](https://user-images.githubusercontent.com/24273478/35186019-b6b6486e-fe0d-11e7-9cae-36baf7b4cd97.png)</kbd>
When Hold on book and using _Book information_:
<kbd>![bookinfo_kvpage](https://user-images.githubusercontent.com/24273478/35186021-b9b6d772-fe0d-11e7-95d3-e549e5ae972a.png)</kbd> …
=> metadata: support multiple authors

frontend/ui/wikipedia.lua
I added the wikipedia full page one year ago (and Save as epub a bit later), and I'm often a bit confused by the choice of symbols I made for prefixing H3 and H4 headings (there're not many usable symbols available in all fonts to choose from - and they should be the same in the epub that can be read with crengine with user fonts).
There's something in their density/alignment that, I think, is misleading in the feeling of hierarchy we get, and it feels better if we swap them:
before => after - What do you think ?
<kbd>![before](https://user-images.githubusercontent.com/24273478/35221591-fe9bd450-ff7a-11e7-939e-a3ebcf6e9779.png)</kbd> => <kbd>![after](https://user-images.githubusercontent.com/24273478/35221593-00ba702a-ff7b-11e7-8a59-a3de27bb9e9c.png)</kbd>
(headings start with h2 - many …
=> Wikipedia full & epub: swap symbols for H3 and H4

frontend/ui/widget/htmlboxwidget.lua
When selecting multiple words on the HtmlBoxWidget, and selecting backwards (ie: beginning the hold on the last word of the text we want to select - moving till the beginning of the text we want to select), we were getting the text from the first hold till end of page.
=> HtmlBoxWidget: fix selection when starting from end

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerwikipedia.lua
Avoids a standalone `:` as book title in histories.
=> Dict & wiki history: use filename when no book title

frontend/apps/reader/modules/readersearch.lua, frontend/apps/reader/skimtowidget.lua, frontend/ui/trapper.lua, frontend/ui/widget/buttondialog.lua, frontend/ui/widget/buttondialogtitle.lua, frontend/ui/widget/confirmbox.lua, frontend/ui/widget/container/movablecontainer.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/infomessage.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/textboxwidget.lua, frontend/ui/widget/textviewer.lua
I wanted to be able to move some InfoMessage: often, when reading and wanting to do a dict or wiki lookup, I have the habbit of remembering the word, continue reading till I pass the 2/3 of the screen, and then do the lookup - so the InfoMessage doesn't pop on where I am reading, and I can still read a few lines while the lookup is happening.
Anyway, this PR adds a MovableContainer, and plugs it into a few widgets:
- SkimToWidget (because in the middle of the screen is sometimes not the best place to see what's on the screen, and you can wish to move it to see some chapter title underneath it).
- ReaderSearch (buttondialog) widget with the `<< < > >>` buttons (for the same reason as SkimToWidget)
- ButtonDialog/ButtonDialogTitle: the highlight 2x4 menu, the Hold on file menu, that you may …
=> New MovableContainer: allow moving some widgets

frontend/apps/reader/modules/readerstatus.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua
See https://github.com/koreader/koreader/issues/3638#issuecomment-361369153 (and #2363, #2366).  Closes #3638.
Any suggestion for a better `"Save document (write highlights into PDF)"` ?
I understand the setting and menu title was made for a generic _save any stuff that make sense for this document format to the document itself_, but for now, it only works with PDF, and only for saving highlights into the PDF file. (The generic title `Save document` does not give any hint about what this could do, and got me perplexed since I first saw it :)
=> Add menu item for toggling auto_book_status

frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/scrollhtmlwidget.lua, frontend/ui/widget/scrolltextwidget.lua, frontend/ui/widget/textboxwidget.lua
When using Tap to scroll dict definitions for continuous reading, if one misses the bottom by taping too much and happen on the next definition, _Tap on left part of definition_ to go one page up would bring you to top of previous definition, and you would have to tap tap tap to reach again bottom.
This PR makes it jump to bottom of it, which feels more natural and expected.
One can still use swipe left to go to top of prev definition.
=> Dict: scroll back with tap: go to bottom of prev definition

frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/modules/readerlink.lua, frontend/apps/reader/modules/readersearch.lua, frontend/apps/reader/modules/readertoc.lua
When selecting an item in TOC and bookmarks list and going to its page, remember current page so we can go back to it. See #3645. Closes #3645.
When in Full text search: only add the initial page to the location stack - and not every search result's page - so we can easily go back to it. See #3616 Issue 1).
=> TOC, bookmarks: remember current page + Search: only remember initial page

frontend/document/credocument.lua, frontend/document/djvudocument.lua, frontend/document/documentregistry.lua, frontend/document/pdfdocument.lua, frontend/document/picdocument.lua, spec/unit/document_registry_spec.lua
This is step one toward "open with".
References https://github.com/koreader/koreader/issues/3345
* Fix up some mimetypes
* Add XHTML to supported filetypes
* Add a few image files to MuPDF
* ".bmp",
* ".gif",
* ".hdp",
* ".j2k",
* ".jp2",
* ".jpeg",
* ".jpg",
* ".jpx",
* ".jxr",
* ".pam",
* ".pbm",
* ".pgm",
* ".png",
* ".pnm",
* ".ppm",
* ".tif",
* ".tiff",
* ".wdp",
@poire-z Any thoughts on this before I start thinking about GUI and settings?
PS Regarding GUI, I was thinking maybe something like this:
=> [feat] DocumentRegistry: add getProviders() and preferred by weight

frontend/apps/filemanager/filemanager.lua, frontend/apps/reader/readerui.lua, frontend/document/credocument.lua, frontend/document/djvudocument.lua, frontend/document/documentregistry.lua, frontend/document/pdfdocument.lua, frontend/document/picdocument.lua, spec/unit/document_registry_spec.lua
=> [feat] Open with: choose which engine to use for file

frontend/apps/reader/modules/readerfont.lua, frontend/ui/widget/menu.lua
Should fix this problem: https://github.com/koreader/koreader/pull/3589#issuecomment-360986821 and #3655
=> Optimize menu

frontend/apps/reader/modules/readersearch.lua, spec/unit/readersearch_spec.lua
See technical details in https://github.com/koreader/koreader-base/pull/595 and https://github.com/koreader/crengine/pull/94. This will need cascading bumps for them.
Fix various inconsitencies: some occurences not highlighted on displayed page; different occurences highlighted on same page whether we went there searching backward or forward; pages with occurences simply just skipped when searching in one direction, and not in the other... See https://github.com/koreader/koreader/issues/2489#issuecomment-290906594
Closes #2489. Closes #3616 (item 3).
Some example "edge case" pages:
A table (grey border) ending on next page may cause a hit in it not being highlighted, If no other item on page, this page would be skipped when search backward : …
=> cre full text search: fix inconsistencies

frontend/ui/widget/menu.lua
First item would be underlined if the device is both Touch and Keys capable (emulator, android, pocketbook; kobo touch, some kindle...), which is not really pretty, and a bit confusing (is that line a header?) It happens since #3621. This PR delays that underlining on Touch devices until keys for focusing are really used.
<kbd>![toc_underlined](https://user-images.githubusercontent.com/24273478/35809203-4100856c-0a88-11e8-8195-6183f7988480.png)</kbd>
=> Menu: don't underline items on touch devices

frontend/apps/reader/modules/readerlink.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/modules/readersearch.lua
Followup to koreader/koreader#3202 so we see that marker too when back from link, so we know where we were before jumping to link. Only works with credocuments.
ReaderLink: make all links be a table (they were a table for PDF, but a string for CRE) for clearer code. Also have `location_stack` store them as tables, with additional properties.
Get original position of link source (and verify it is valid) thanks to https://github.com/koreader/koreader-base/pull/598 and https://github.com/koreader/crengine/pull/96 so we can show a marker there (but not if it was invalid, this can sometimes happen due to some bug in crengine).
Also (see https://github.com/koreader/koreader/issues/3645#issuecomment-361982342):
Hold on "Go back to previous location" to clear location stack.
_Resists_ "Swipe to …
=> Show vertical marker at original position when back from link

frontend/document/credocument.lua
With `["cre_compress_cached_data"] = false,` in `settings.reader.lua`.
Not using compression for cache files does indeed take more space, but it does speed up opening, rendering, page turns, and closing, with big documents.
Details in https://github.com/koreader/crengine/pull/97 and originally in https://github.com/koreader/koreader/issues/3261#issuecomment-348710821.
=> cre cache: allow for disabling compression

frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerzooming.lua
New zoom configuration available among the others
Allows to easily navigate in two-column documents
In order to  work properly, **scroll mode must be deactivated**
The best zoom is obtained with proper cropping around the two columns (should be the default one for content-width)
=> Two-column navigation

frontend/ui/widget/frontlightwidget.lua
frontlightwidget: Add widgets for changing 'warmth' where available
This is to further improve natural light support on the Kobo Aura One (see #2285).
=> Extend frontlight widget

frontend/apps/reader/modules/readerhighlight.lua
Closes #3696.
I guess I did not check how #3199 behave on PDF documents when I made it :|
Holding on a word for more than 3s should bring the highlight menu.
It crashed on readerpaging documents because `self.hold_pos` is no more a `Geom` object with readerpaging documents (while it stays a `Geom` object with readerrolling documents) after this:
https://github.com/koreader/koreader/blob/40ff96761548f3a713519e97a023cecb4f107578/frontend/apps/reader/modules/readerhighlight.lua#L263
Also inverted `selected_word` / `selected_text` logic, as with PDF, `selected_word` stays set when `selected_text` is available. Without that, with PDF, it keeps doing a dictionary lookup and never shows the menu.
Could you please test it works fine with PDF & DJVU and that this logic inversion is transparent? …
=> Fix long Hold on PDF documents

frontend/document/credocument.lua
This should considerably speed up the re-opening of big epub books from their cache.
Full technical details in https://github.com/koreader/crengine/pull/100 (and https://github.com/koreader/koreader-base/pull/601):
Bump crengine for cache re-use fix and warnings when cache sizes reached.
Allow for increasing some crengine cache sizes with a new setting: `"cre_storage_size_factor" = 1.5` (or `2`, or `4`...)
I don't know it we should already increase theses size with a default like:
```lua
+ G_reader_settings:readSetting("cre_storage_size_factor") or 2.0)
```
or wait a few nightlys for that.
Just mentionning bellow the new warnings that could be seen in crash.log here (so users searching issues would find this post).
KOReader and its epub rendering engine (crengine) may work very well in …
=> cre: cache re-use fix, warnings and allow cache sizes increase

plugins/coverbrowser.koplugin/bookinfomanager.lua, plugins/coverbrowser.koplugin/xutil.lua
Just some internal updates to coverbrowser plugin code:
- Remove the subprocess management functions from xutil.lua, as they are now available in base/ffi/util.lua, and use them from there.
- Also use the cre_storage_size_factor setting when processing credocuments, to avoid CRE WARNINGs while indexing too (so, a user like me don't go thinking "_why this setting that I just increased that seemed to work does not work anymore now, as I see these warnings again!_")
- Fix dealing with MuPDF document opening failures (previously, these were not noticed and indexing was retried each time).
=> coverbrowser: keep up to date with recent core changes

frontend/ui/widget/bookstatuswidget.lua, plugins/coverbrowser.koplugin/listmenu.lua
Replace reading percentage with 'Finished' or 'Abandoned' when book status is no more 'Reading' (can be changed back via Book Status widget). See https://github.com/koreader/koreader/pull/2940#issuecomment-369911064.
<kbd>![status2](https://user-images.githubusercontent.com/24273478/36904544-2f5e7a46-1e31-11e8-9c30-4c17771e8e8a.png)</kbd>
=> coverbrowser list view: show book status

frontend/document/pdfdocument.lua
It happens in base so we don't have to worry about it in front.
References https://github.com/koreader/koreader/issues/3705
=> [fix] Better error handling when MuPDF document has no pages

frontend/device/input.lua, frontend/device/kobo/device.lua
This makes touch work on my H2O2, including multitouch zoom gestures, but not including rotate. Hopefully, it doesn't break any other devices.
=> [feat] Make touch work on the H2O2

frontend/apps/reader/modules/readerhighlight.lua, frontend/document/koptinterface.lua
=> [UX] Add InfoMessage about OCR

frontend/ui/widget/container/movablecontainer.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/htmlboxwidget.lua, frontend/ui/widget/textboxwidget.lua
Some Hold and move (hold on title and move away from dict window) would not work (we need the HoldStart and HoldRelease gesture to have a range on the whole screen, so they can be ignored by TextBoxWidget and pop up to DictQuickLookup, which will forward the event to MovableContainer).
Pan (=swipe with hold at end) on the definition text would move the window (it now does nothing: proper text selection still needs Hold on word at start).
Also increase hold duration from 2s to 3s (for switching lookup between dict/wikipedia) to be consistent with the 3s duration in readerhighlight.
(See #3717 about these)
(It wasn't easy to get right, I hope I have not introduced other strange behaviour...)
=> Fix some issues with movable dict window

reader.lua
As suggested by @poire-z in https://github.com/koreader/koreader/pull/3723#issuecomment-370557018
```
---------------------------------------------
launching...
_  _____  ____                _
| |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
| ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
| . \ |_| |  _ <  __/ (_| | (_| |  __/ |
|_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|
It's a scroll... It's a codex... It's KOReader!
[*] Current time: 03/05/18-23:08:05
[*] Version: blablabla-21-g076bf406
```
=> reader.lua: add version to ascii art

frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/htmlboxwidget.lua, frontend/ui/widget/textboxwidget.lua
Clearer rework of #3722 : simpler, more explicite, no need for the additional callback. The Pan and PanRelease don't happen while Hold, so no need for checking if selection in progress.
Use https://github.com/koreader/koreader/compare/master~2...poire-z:fix_movable_dict_reworked?expand=1for review
(I had some afterthoughts after it was merged - so let this one sit for a few hours :)
=> Fix some issues with movable dict window (reworked)

Makefile
Adds an extra part at the end of the git-rev.
Before: `blablabla-21-g076bf406`
After: `blablabla-21-g076bf406_2018-03-05`
Fixes #2896
=> Add date to git-rev version

frontend/document/credocument.lua
Increase default crengine in-memory cache sizes to avoid pack/unpack of chunks that is known to be the cause of bugs (rendering, cache re-use...).
Details in https://github.com/koreader/koreader/pull/3700 and https://github.com/koreader/crengine/pull/100
=> Set default 'cre_storage_size_factor' to 20

frontend/document/credocument.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua
bump crengine:
Allow for quicker loading when interested in metadata only https://github.com/koreader/crengine/pull/123
Allow for more than 65535 different attribute values https://github.com/koreader/crengine/pull/124
Increase gamma values range https://github.com/koreader/crengine/pull/122
=> coverbrowser: quicker extraction of EPUB metadata

plugins/newsdownloader.koplugin/main.lua, plugins/send2ebook.koplugin/main.lua
Fix these errors seen in unit tests output (and when leaving emulator):
```
03/11/18-12:06:25 ERROR failed to call event handler onCloseDocument plugins/newsdownloader.koplugin/main.lua:370: bad argument #1 to 'len' (string expected, got nil)
03/11/18-12:06:25 ERROR failed to call event handler onCloseDocument plugins/send2ebook.koplugin/main.lua:216: bad argument #1 to 'len' (string expected, got nil)
```
=> Fix some minor plugin errors on exit

frontend/device/kobo/device.lua, frontend/device/kobo/powerd.lua, frontend/device/kobo/sysfs_light.lua, frontend/ui/widget/frontlightwidget.lua, frontend/ui/widget/naturallightwidget.lua
New widget to configure natural light on Kobo Aura One and H2O2.
=> Natural light configuration

frontend/gettext.lua
This is not fatal and can be mistaken by new users for the cause of all their problems, like I did in #2621.
=> turn missing translations into a warning

plugins/goodreads.koplugin/main.lua
=> [fix, i18n] plugins/goodreads.koplugin: make untranslated string translatable

frontend/device.lua
"hardware abstraction" didn't mean anything for me when I tried the emulator at first on Debian. In #2621, it was proposed to suggest installing SDL: do so here, although we do it for all platforms...
=> propose installing SDL on Linux

plugins/coverbrowser.koplugin/bookinfomanager.lua
As reported at https://github.com/koreader/koreader/pull/3750#pullrequestreview-104123218
=> converbrowser: fix some texts

frontend/document/credocument.lua
Interim solution for #3746.
For max disk space usable by crengine for storing book caches (value in MB).
Increased default from 32 MB to 64 MB (now that they are really re-used).
So one can adds to its settings.reader.lua:
```lua
["cre_disk_cache_max_size"] = 512,
```
if he has that space available and wants to keep more cache files so they are re-used, for quicker re-openings.
=> Adds 'cre_disk_cache_max_size' setting

frontend/apps/reader/modules/readerconfig.lua
Reading an epub file with Mupdf would show 6 items in bottom config panel. Reading it with crengine would show only 5.
A crash would happen if we were on the 6th when leaving MuPDF, and later opening config panel with crengine.
```
./luajit: frontend/ui/widget/configdialog.lua:473: attempt to index a nil value
frontend/ui/widget/configdialog.lua:473: in function 'init'
frontend/ui/widget/widget.lua:48: in function 'new'
frontend/ui/widget/configdialog.lua:668: in function 'update'
frontend/ui/widget/configdialog.lua:695: in function 'onShowConfigPanel'
frontend/apps/reader/modules/readerconfig.lua:75: in function 'handleEvent'
frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
frontend/ui/widget/container/widgetcontainer.lua:105: in function …
```
=> Fix possible crash with config panel when engine switched

frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/widget/dictquicklookup.lua
Use PathChooser (instead of InputDialog with keyboard to enter the directory path) to select a directory where to save Wikipedia EPUB to.
I didn't know PathChooser existed at the time I did it, so all this ugly directory path strings check stuff.
It's not perfect (because of PathChooser limitations: it does not display current dir path, it doesn't allow creating a directory), but it will do for this setting most people probably use only once.
=> Wiki save dir: use PathChooser for selecting directory

frontend/apps/filemanager/filemanagerbookinfo.lua, plugins/coverbrowser.koplugin/covermenu.lua
Use the recently added option to loadDocument() to load only metadata.
coverbrowser: also plug optimised callback to the right button ("Book information" was shifted when "Open with..." was added). It was for some weeks plugged to "Convert".
=> BookInformation: speedup getting EPUB metadata/cover

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerhistory.lua, frontend/apps/opdscatalog/opdscatalog.lua, frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/modules/readertoc.lua, frontend/apps/reader/readerui.lua, frontend/ui/screensaver.lua, frontend/ui/uimanager.lua, frontend/ui/widget/bookstatuswidget.lua, frontend/ui/widget/imageviewer.lua, frontend/ui/widget/keyvaluepage.lua
Navigating the TOC, viewing a full screen image, browsing reading stats... would call paintTo() on ReaderUI (so, asking the engine to render the page) or FileManager (so, rendering cover images) even though their content is hidden.
Widgets registering to UIManager have to explicitely state they cover the full screen with `covers_fullscreen = true`  (UIManager can't know, parts of their dimen may be transparent, e.g. if it is a CenterContainer, like an InfoMessage has dimension of the full screen).
This makes these things snappier.
(We can't do that for the top menu, as the book text is displayed below, and when changing menu items, the next one may be smaller, so book text has to be displayed - so, this still lags a bit by the same time taken by page turn).
I've been testing this only for …
=> UIManager: avoid painting widgets covered by a full screen widget

frontend/ui/widget/buttontable.lua, frontend/ui/widget/focusmanager.lua, frontend/ui/widget/menu.lua
Quick edit to be able to open the hold menu on non touch devices.
The naviguation in the hold menu need a bit of getting used to, but it's fully useable.
=> Create a keybinding to access the hold-item menu

frontend/device/sdl/device.lua
References #1417 
Bumps base for https://github.com/koreader/koreader-base/pull/614
Also includes:
* Speedup loading from cache EPUB with many files https://github.com/koreader/crengine/pull/133
* Avoid rewriting cache file when no change were made https://github.com/koreader/crengine/pull/134
A couple of screenshots:
=> [feat] SDL2: resize window

plugins/coverbrowser.koplugin/listmenu.lua, plugins/coverbrowser.koplugin/mosaicmenu.lua
Fix vertical wrong alignment of the _book opened_ hint, introduced by the recent correction to UnderlineContainer (https://github.com/koreader/koreader/pull/3745#issuecomment-373119098).
This was probably the right thing (top, no padding) I should have done at the time, and may be it worked fine enough just because of the bug in UnderLineContainer :)
<kbd>![uglyhint](https://user-images.githubusercontent.com/24273478/37668879-c5c5e0fe-2c65-11e8-9739-3debf9837774.png)</kbd>
I noticed this while testing file browser in full screen ~~desktop~~ emulator mode, so I guess it was good to have it:)
Don't merge yet, I'll verify tonight it displays as fine on my Kobo (where i didn't notice any problem recently).
=> coverbrowser: fix some vertical alignments

frontend/apps/reader/modules/readerfooter.lua
@poire-z Now this is a big one for Android. I wasn't sure if it was a problem in ReaderUI or in the Android framebuffer stuff. Thanks to resizing the problem was immediately obvious.
=> [UX] apps/reader/modules/readerfooter: also redraw progressbar on height change

frontend/ui/widget/focusmanager.lua, spec/unit/focusmanager_spec.lua
The focusmanager now find the closest widget on the right or left on
inner horizontal border.
See : https://github.com/koreader/koreader/pull/3765#issuecomment-373944897
It even make the touchmenu better by allowing to go down from every item of the top menu.
=> [FocusManager] More intuitive key naviguation

frontend/apps/reader/readerui.lua, frontend/ui/widget/filechooser.lua
This initial implementation only sets the title for FileManager and ReaderUI.
Fixes #3713.
Depends on https://github.com/koreader/koreader-base/pull/615
=> [UX] SDL2: set window title

frontend/device/sdl/device.lua
Depends on https://github.com/koreader/koreader-base/pull/622
Includes crengine: use cache files renamed as .cr3.keep koreader/crengine#137, which fixes #3746.
=> [feat, UX] SDL2: drop file to open

plugins/calibrecompanion.koplugin/main.lua
Fixes #3794. 
Upstream luasocket https://github.com/diegonehab/luasocket/commit/96965b179c7311f850f72a8629b9ba6d3a31d117 switched from just `socket.udp()` to `socket.udp4()` and `socket.udp6()`.
=> [fix] calibrecompanion.plugin

kodev
As in 16061370f48026eb18bdfa30e9ed2faf94e59387, leftover from #3723.
Also replaced a few non-standard `which` by `command -v` as per new shellcheck rule.
See https://github.com/koalaman/shellcheck/wiki/SC2230
=> [fix] kodev update $VERSION for `run android`

frontend/apps/filemanager/filemanagermenu.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/menusorter.lua, plugins/coverbrowser.koplugin/covermenu.lua
Add an element in the filemanager touchmenu to open the tapPlus menu on non touch device only.
=> Tapplus shortcut

frontend/apps/reader/modules/readersearch.lua
They were indeed removed, but no full screen refresh was requested, so the highlights stayed visible.
Only happen when search term was typed (via `Full text search` menu), does not happen when search started from a word selected with Hold (the refresh was done in that case).
Not noticable on the emulator, as on the emulator, all refreshes are full screen, so closing the search bar sets its small area as dirty, which is enough to refresh the full screen.
=> Remove search highlights when closing search bar

frontend/ui/widget/scrolltextwidget.lua
Found by using the InputText widget with scroll=true, and trying to enter text after tapping to move the cursor - wbuilder crashed with the error "./luajit: frontend/ui/widget/inputtext.lua:258: bad argument #2 to 'insert' (number expected, got nil)".
=> [Fix] Make ScrollTextWidget:moveCursor return the new charpos.

frontend/ui/uimanager.lua
As in https://github.com/koreader/koreader/issues/3706#issuecomment-370336452 Suspend kept being rescheduled on every touch while we should just ignore it.
Fixes #3706.
=> [fix] Kobo suspend when touching screen

Makefile
Fixes always reinstalling resource package.
See https://github.com/koreader/koreader/pull/3723#issuecomment-376508917
=> [Android] Makefile: only use VERSION, not REVISION

frontend/ui/widget/menu.lua, plugins/coverbrowser.koplugin/covermenu.lua
Also, maybe we should talk about code duplication between menu and covermenu
=> Fix the cursor not being reset in Coverbrowser

frontend/device/kobo/nickel_conf.lua, frontend/device/kobo/powerd.lua, frontend/ui/widget/frontlightwidget.lua, plugins/kobolight.koplugin/main.lua
Support for setting 'warmth' according to current time.
=> Automatic setting for 'warmth'

frontend/apps/filemanager/filemanagermenu.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/widget/touchmenu.lua
Closes #3802.
Looks easier than I thought - is that all that was needed?
<kbd>![image](https://user-images.githubusercontent.com/24273478/38413538-3ef1319e-398c-11e8-9a43-249a017eea31.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/38413552-4ad80b18-398c-11e8-952a-a0bf3b477961.png)</kbd>
=> FileManager menu: split Settings tab into 2 tabs

frontend/ui/widget/menu.lua, plugins/coverbrowser.koplugin/covermenu.lua
As suggested in #3817.
Also allows full refresh with short diagonal swipe of Menu instances (TOC, bookmarks).
=> CoverBrowser: avoid page info code duplication

plugins/coverbrowser.koplugin/main.lua
As requested in https://github.com/koreader/koreader/pull/3817#issuecomment-377668725 :
> I'd definitely prefer defaulting to one of the detailed list views these days. Probably either detailed list with cover images and metadata or detailed list with cover images and filenames.
I tried _cover images and filenames_, which would be the less intrusive for people used to classic mode, but the bigger filename in bold was a bit strong for me (when compared to Classic mode with small font size). Metadata with title and authors on 2 lines looked nicer.
@KenMaltby : I believe you use classic mode: with this, on your next update, you'll be switched to some other modes, and you'll have to manually reset them to classic mode (and delete Cache DB if you want to keep things tidy). Is that ok ?
=> CoverBrowser: set default display modes on first launch

frontend/apps/reader/modules/readerlink.lua, frontend/ui/widget/dictquicklookup.lua, frontend/ui/widget/multiconfirmbox.lua
As suggested in https://github.com/koreader/koreader/issues/3757#issuecomment-374201294 :
>> when I click on the same link (whose article is already downloaded) again then open the downloaded EPUB locally (instead of going online);
> This is a good idea: we could check at least, before going online do a lookup, if there is an EPUB of that link's article in the currently-being-read article EPUB directory (assuming you filled articles about the same topic in the same directory). 
Probably little chances I encounter this feature in my daily usage, but well...
<kbd>![image](https://user-images.githubusercontent.com/24273478/38429702-71ad1a3e-39bf-11e8-8903-c8c61354bd1a.png)</kbd>
Suggestion for alternate desription and (small) button texts ?
Also makes MultiConfirmBox movable, like ConfirmBox …
=> Wikipedia link: check if previously saved as EPUB

frontend/ui/widget/frontlightwidget.lua
Otherwise clock display will have a line break for low DPI (see issue
=> [fix, UX] frontlightwidget: More space for text and centering

frontend/ui/menusorter.lua
See : https://github.com/koreader/koreader/pull/3773#issuecomment-379181517
@Frenzie How do you feel about this ?
Now the layout look like this : 
```
{ { {...}, {...}, {...}, {...}, {...}, {...},
icon = "resources/icons/appbar.cabinet.files.png",
id = "filemanager_settings"
}, { {...}, {...}, {...}, {...}, {...}, {...}, {...},
icon = "resources/icons/appbar.settings.png",
id = "setting"
}, { {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...},
icon = "resources/icons/appbar.tools.png",
id = "tools"
}, { {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...},
icon = "resources/icons/appbar.magnify.browse.png",
id = "search"
}, { {...}, {...}, {...}, {...}, {...}, {...},
icon = "resources/icons/menu-icon.png",
id = "main"
},
id = "KOMenu:menu_buttons"
}
``` …
=> Fix Menusorter

frontend/cache.lua
If the most recently used global cache item refers to the same
page, it would be overwritten. This will happen when closing a
paged (PDF/DjVu) document on the same page you opened it, as well
as when opening and closing EPUBs with crengine because it uses
its own cache.
Fixes #3846.
=> [fix] Cache: don't overwrite same CacheItem

frontend/ui/wikipedia.lua, frontend/util.lua
- Fix display of `&` in article titles
- Fix display of `&`, `<`, `>` in TOC entries and in targeted anchors (the mismatch
with the target id made these TOC entries invalid and simply not displayed).
- Remove percent-encoded URLs tweaks for crengine now that crengine
correctly supports them (each percent encode handled as an UTF8 byte).
- Bump crengine for that.
- Don't include `<meta name="cover">` when no cover present.
- Fix util.htmlEntitiesToUtf8() to correctly do the substitution in order (`&amp; > &` should be the last)
See https://github.com/koreader/crengine/pull/143 for details.
Will need a crengine bump for https://github.com/koreader/crengine/pull/143 for the _Remove percent-encoded URLs tweaks_  to be included.
=> Wikipedia Save as EPUB: various encoding fixes

frontend/apps/reader/modules/readerback.lua
Mostly useful for developers for quick launch & quit of the emulator. See why _I_ want that in https://github.com/koreader/koreader/pull/3821#issuecomment-379239310 
This allows getting the old behaviour by adding to `settings.reader.lua`:
`["enable_back_history"] = false,`
ReaderBack has also moved the back action from the <kbd>Backspace</kbd> to the <kbd>Esc</kbd>. To replace <kbd>Esc</kbd> with the old <kbd>Backspace</kbd>, create `koreader-emulator-x86_64-linux-gnu-debug/koreader/settings/event_map.lua` with:
```
return {
[42] = "Back"
}
```
=> ReaderBack: allow for disabling back history

setupkoenv.lua
Not all failures to load are fatal. I still worry that this might be too noisy but it'd be useful to always have available.
=> [fix] setupkoenv: change "ERROR" to "(warning)"

platform/appimage/AppRun
Fall back to `pwd` otherwise.
Fixes #3861.
=> [fix] AppImage: use $XDG_DOCUMENTS_DIR if available

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerrolling.lua, spec/unit/readerfooter_spec.lua
Uses a setting `["copt_overlap_lines"] = N,` (default to `1`) for the number of text lines from previous page to show on next page (instead of a hardcoded and unscaled 20).
Takes footer height into account for overlap calculation and dim area.
Shows overlap only when changing pages (not when panning: it was changing at each pan step and it was real ugly).
It may help a bit with #3813 by just being more accurate, but there's still the misconfort of text lines being cut or dim'ed in the middle. But we can't do much more in scroll mode, when we have no knowledge of text rendering: we just cut slices of the whole document height.
(Doing overlap and dim in page mode would be a far more complex work!)
Also fix `ReaderFooter:getHeight()` which was returning a higher height than the real one …
=> Fix overlap in scroll mode for cre documents

tools/kobo_touch_probe.lua
Previously, it caused problems because it was overriding `G_reader_settings`,
which caused the `translator` test to fail on the second (but not first) run.
---
tl;dr: this is an example of one test affecting another negatively, and I tried other ways to fix it too, but at least this way seems to work. I tried to explain the underlying problem and my reasoning below.
This one took me a little while, not just to isolate where and figure out what was going on, but also to fix, as there's apparently some magic in there that was working against me. (It doesn't really help that I'm pretty much learning Lua as I go along here, as well as the Koreader codebase...)
The whole thing started with me being annoyed by and wanting to fix a failure I was seeing in the translator test, figuring that the …
=> [fix] Stop the kobo_touch_probe test from causing problems for other tests.

Makefile
On some systems only `/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0` exists. This is also relevant for the FFI but I've got different ideas about how to tackle that.
=> [fix] Build AppImage on more system configurations

frontend/ui/wikipedia.lua
Removes `width:80%` as it was never supported by crengine (the effect was achieved thanks to margins and paddings).
Wikipedia saved articles from now on won't be effected by a double effect if we later add full support for `width:` into crengine.
=> Wiki saved as EPUB: stylesheet fix

plugins/coverbrowser.koplugin/main.lua
Don't keep a handle on bookinfo_cache.sqlite3 when "Start with: last book".
It was and is closed/released when leaving filemanager and opening a book. It wasn't just when starting with opening a book (where we still go into plugins init()).
That didn't hurt, but it makes things cleaner when looking at luajit opened files.
=> coverbrowser: close sqlite db after init

frontend/apps/reader/modules/readerconfig.lua
For Kindle 4NT `hasKeyboard = no`, therefore cannot open config menu. I change the if condition to check `hasKeys`.
I've tested on my Kindle 4NT and it works.
=> Fix the bug where "Press" key does not open config menu on Kindle 4 NT

Makefile, frontend/device/kobo/device.lua
Otherwise, current tar versions abort
=> Fix order of tar args

frontend/ui/menusorter.lua
The plus_menu break the assumption of the menusorter about a tab beeing
always present.
See : https://github.com/koreader/koreader/pull/3844#issuecomment-383092219
=> [Menusorter] Ignore warning for the plus_menu.

frontend/ui/widget/menu.lua, frontend/ui/widget/textboxwidget.lua
By reducing the number of data structures, and avoiding nested tables, which seemed to impose a lot of work on the garbage collector.
When browsing full wikipedia page, we quickly end up with a few 100MB of memory used, that seem to never be released. I tried to track memory leaks, but found nothing obvious. There may be some thus.
But often, the same action of viewing the same page does not provoke the same increase of mem usage.
Also, it sometimes happens that koreader becomes very slow, even on simple actions, while still being in the 100-200 MB range, which may be the garbage collector at work.
This PR removes the huge (3 items for each letter in text) `self.char_width_list` table:
https://github.com/koreader/koreader/blob/3cc9313cc6acfbfe499c5f89597c8fc7449a5ede/frontend/ui/widget/tex …
=> TextBoxWidget: optimize memory usage

frontend/apps/reader/modules/readerhighlight.lua, frontend/document/credocument.lua, frontend/document/picdocument.lua, frontend/ui/renderimage.lua, frontend/ui/widget/imageviewer.lua, frontend/ui/widget/imagewidget.lua, frontend/ui/wikipedia.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua
RenderImage: factorize all image rendering and scaling code:
New module RenderImage (alongside existing RenderText) to provide image rendering and scaling facilities.
Uses MuPDF, but tries first giflib on GIF. Allows for getting all the frames from an animated GIF.
Needs a base bump for https://github.com/koreader/koreader-base/pull/657
PicDocument:getCoverPageImage(): use first page instead of MuPDF:
The dedicated image format library may often give better results than MuPDF (eg: for animated GIFs).
ImageViewer: allow viewing a list of images:
Mostly useful for browsing the frames of animated GIFs (but generic enough for other uses)
It adds a small progress bar under image, and allow switching frame with Tap on left/right of screen: …
=>  RenderImage: factorize all image rendering and scaling code 

frontend/apps/reader/modules/readerdictionary.lua
Seen that kind of results:
<kbd>![image](https://user-images.githubusercontent.com/24273478/39470881-72c73c3a-4d40-11e8-874a-e783c1c3c65f.png)</kbd>
We already remove html tags (after what this PR does, so this PR will convert twircely encoded html to tags, that will then be removed), so I hope it's fine and there's no non-html dictionary in the wild that uses litteral stuff that looks like these html entities or tags that have meaning in their definitions...
=> dict: convert htmlentities in non-html text results

plugins/goodreads.koplugin/goodreadsapi.lua, plugins/goodreads.koplugin/goodreadsbook.lua
After adding generic HTML widget in #3573 now we can show descriptions (review) in GoodReads as HTML.
Before:
After:
=> Add HTML widget in GoodReads review

frontend/apps/reader/modules/readerrolling.lua, frontend/document/credocument.lua, spec/unit/readerlink_spec.lua
Includes:
- [build] FreeType: bump to 2.9.1 https://github.com/koreader/koreader-base/pull/663
- [build] bump libjpeg-turbo to 1.5.3 https://github.com/koreader/koreader-base/pull/664
- bump crengine:
- Fix CSS selector specificity computation https://github.com/koreader/crengine/pull/171
- [fix] crengine/src/lvfntman.cpp: improve letter_spacing limit https://github.com/koreader/crengine/pull/173
- [fix] crengine/src/lvxml.cpp: add all empty HTML elements https://github.com/koreader/crengine/pull/175
- html head styles: fix styles not being applied https://github.com/koreader/crengine/pull/174
- Hyphenation: increase MAX_PATTERN_SIZE from 16 to 35
- html documents: proper handling of `<BR>` tags https://github.com/koreader/crengine/pull/172
- Allows requesting old (broken) XML/DOM …
=> bump base: crengine, freetype, libjpeg-turbo

frontend/apps/filemanager/filemanagermenu.lua
Close: #3310 
Similar to that: https://github.com/koreader/koreader/blob/e83a0c107843e6577fd308cdab5a7ee3ecaba5dc/frontend/apps/filemanager/filemanager.lua#L170-L171 after open last document (from menu) we should also close filemanager instance.
This change fix problem: #3310 (Menu with plugin isn't synchronized)
=> Close filemanger after open last document

frontend/device/generic/device.lua, frontend/device/kobo/device.lua, platform/kobo/disable-wifi.sh, platform/kobo/enable-wifi.sh, platform/kobo/koreader.sh, platform/kobo/nickel.sh, spec/unit/device_spec.lua
Fix hang on suspend when WiFi is on but we're not aware of it (c.f., #3936).
NOTE: It would probably be useful if we could actually simply trust `wifi_is_on`, but I guess that means some more checks on NetworkManager's init? (And accurate and network-agnostic device-specific ways to do that quickly and cheaply). OTOH, what I went with on Kobo should do the job, and I'm pretty sure we could get something useful out of lipc on Kindles.
A bit of script cleanup after #3920 & #3876 
Pave the way for properly handling #3925 by properly identifying Rev2 variants of the H2O² & Aura SE.
=> Another round of Kobo Fixes

frontend/apps/reader/modules/readerfont.lua, frontend/document/credocument.lua, frontend/ui/widget/touchmenu.lua
Adds symbols for default and fallback fonts.
Also allows for updating the fallback font and see results in real-time on the underlying document.
Also adds a menu item to generate a html document showing some sample text rendered with each available font.
<kbd>![image](https://user-images.githubusercontent.com/24273478/39866447-13600106-5451-11e8-9e7a-d2ed77e00133.png)</kbd>
(our default fallback font Noto Sans CJK has wrong glyphs for greek, so it's nice being able to see how others do - will need a base bump for https://github.com/koreader/crengine/pull/186 for real-time update).
I recently came across https://poliseuse.wordpress.com/ (in french) which has reviews for many fonts and their use on ereaders - and I like testing fonts :)
I used to manually make some html document with the …
=> Font menu: add symbols for default and fallback fonts

frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/modules/readerstatus.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/widget/bookstatuswidget.lua, frontend/ui/widget/filechooser.lua
Close: #3937 #3545, #3405 
Discussion: #3937
Screenshots:
Limitations: The "next file" option is not available when sorting: "sort by last read date".
=> End of document action

frontend/apps/reader/modules/readerrolling.lua
Footer item "pages left in chapter" (the `=> 3` in the screenshots below) was wrong just after changing font sizes or some other layout option (the footer was drown before this happen, and not after, until we later change page). So, just call it again (it's fast) when we have updated the TOC.
Seems to also fix possible wrong ticks position in that case (may be only when cache is used/re-used, for some not really obvious reason).
Before, when changing font sizes to really small or really huge, we could get:
After this, we get:
May be this fixes #3778 too?
=> ReaderRolling: update footer when TOC is updated

frontend/device/kindle/device.lua, platform/kindle/extensions/koreader/bin/koreader-ext.sh, platform/kindle/libkohelper.sh
Resync the model detection everywhere
Fix a bit of insanity in the screensavers handling.
Fix #2848 
Fix #3220 (this one's more of a 'cantfix', but, still).
=> A round of Kindle fixes

frontend/device/kindle/device.lua, platform/kindle/koreader.sh
re: #3955 
Looks safe enough.
Queued events that accumulate during the STOP properly get processed as bogus on resume.
And if the device is still plugged in on resume, you're thrown into the framework's USBMS handling, and it works.
Quickly tested on a PW2 on FW 5.8.1. YMMV on other setups.
=> Try to inhibit USBMS on Kindles

frontend/ui/data/creoptions.lua, frontend/ui/widget/configdialog.lua
After long press on name of options in config dialog we can see now current and default value. For now only for epub (cre) documents.
Long press on "View Mode"
Long press on "Line Spacing"
Long press on "Margin"
=> Show current and default values in config dialog (epub)

frontend/apps/reader/modules/readerfont.lua, frontend/apps/reader/modules/readerfrontlight.lua, frontend/apps/reader/modules/readerlink.lua, frontend/ui/widget/notification.lua
I think the notification messages are displayed too short (eg. `Line spacing set to...`, `Font size set to...`). I changed from 1 second to 2.
I also fixed the problem with blocking the UI when displaying the message. Now notification box is closed after taping anywhere (like InfoMessage).
=> Notification are displayed too short

frontend/apps/reader/readerui.lua
See comments:
https://github.com/koreader/koreader/pull/3933#issuecomment-386879892
https://github.com/koreader/koreader/pull/3933#issuecomment-386899058
=> Always close filemanger before open document

frontend/apps/reader/modules/readermenu.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/modules/readerstyletweak.lua, frontend/apps/reader/readerui.lua, frontend/document/credocument.lua, frontend/ui/data/css_tweaks.lua
See https://github.com/koreader/crengine/pull/188 for details about this _alternative rendering method for list items_.
~~Also reorganize Style tweaks (demote Workarounds by moving it into a new Enhancements menu - might look strange,  would it be better in Misc?, - I don't want to add another top level item for it).~~
<kbd>![image](https://user-images.githubusercontent.com/24273478/40278119-78455292-5c2b-11e8-8d6d-dab5aff12a09.png)</kbd>
Check the build DOM is still coherent with styles on stylesheet change, and propose to reload the document if not. Also invalidate cache in that case so a new DOM is built at next opening.
<kbd>![image](https://user-images.githubusercontent.com/24273478/40278101-28db056c-5c2b-11e8-99da-680579e3c728.png)</kbd>
One may get this message when using a Style …
=> Adds "Better rendering of list items" to Style tweaks

frontend/apps/reader/modules/readerstyletweak.lua, frontend/document/credocument.lua, frontend/ui/data/css_tweaks.lua, frontend/ui/wikipedia.lua
Books previously opened (that have a metadata.lua, whether with highlights or not, but because they all have a last_xpointer that points to the current page, that can be broken too by the changes)
will continue to have the old wrong behaviour, so they won't be impacted by the breaking changes.
Update cre_dom_version code to use the new functions from cre.cpp.
Remove these Workarounds from Style tweaks.
See https://github.com/koreader/koreader/issues/3940#issuecomment-391667791 and previous discussion for context.
Will need a base and crengine bump for:
- Adds cre.getLatestDomVersion() and cre.requestDomVersion() https://github.com/koreader/koreader-base/pull/679
- Use latest `<li>` and `<cite>` fixes as default https://github.com/koreader/crengine/pull/192
Users that would really want the …
=> bump crengine: LI and CITE fixes are now the defaults

frontend/apps/reader/modules/readerlink.lua, frontend/ui/widget/touchmenu.lua
When there is no hold callback attached to a menu item, a help_text attribute, when present, is shown in an InfoMessage.
This is one more step towards an _inline user manual_ as envisionned by @KenMaltby in https://github.com/koreader/koreader/pull/3952#issuecomment-390365232, after @robert00s recent works in #3952 and #3967.
I added just a few to the items in the `Links>` submenu (as I added some of these).
Dunno to which level of information we should go (facts, suggestions for different use cases...).
<kbd>![image](https://user-images.githubusercontent.com/24273478/40545037-a0e22254-602a-11e8-8296-f9b62c9563c0.png)</kbd>
Just curious how it works for translation, when we just correct a typo in some english message: do they see their previous entered translation, or it's lost as it's no …
=> TouchMenu: added hook to show help text on long-press

frontend/ui/data/css_tweaks.lua
Adds a few Text alignment tweaks, as suggested by @didierm in https://github.com/koreader/koreader/pull/3944#issuecomment-390411361.
`Justify most text` might be enough to re-enable justification if a publisher has disabled it.
`Justify all text` is radical (will remove centering of images and text in Wikipedia EPUB), but is available in case the previous one is not enough.
Did the same to enforce left alignment, as @Frenzie seems to like it and @cramoisi think KOReader should have that option. See https://github.com/koreader/crengine/pull/150#issuecomment-386855291.
<kbd>![image](https://user-images.githubusercontent.com/24273478/40542335-1a147a06-6020-11e8-82b6-cf862087991a.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/40542320-088054f4-6020-11e8-8792-89e091 …
=> Style tweaks: add a few text alignement tweaks

frontend/ui/data/creoptions.lua, frontend/ui/data/koptoptions.lua, frontend/ui/data/optionsutil.lua, frontend/ui/data/strings.lua, frontend/ui/widget/configdialog.lua
=> Show current and default values in config dialog (pdf)

frontend/apps/reader/modules/readertoc.lua, frontend/ui/elements/refresh_menu_table.lua
Close: #3984
Screen refresh between chapters option in KOReader
Screen -> E-ink full refresh rate
=> Screen refresh between chapters

frontend/readhistory.lua
Fixes koreader/koreader#3988. This just manually updates the atime when an ebook is read (in the history logging code) rather than relying on the kernel. I think this is better than reworking the last-read comparison code to reference the history data automatically; that would be a much larger change, and the history list is trimmed anyway.
This uses the existing luafilesystem touch() call, which calls utime(). Thus, it explicitly reads and preserves the file mtime so that the "by modification" sort view won't be messed up. Philosophically, it would be preferable to call something in the utimensat() family and pass UTIME_OMIT, but the busybox `/bin/touch` available on the Kobo doesn't expose the `-a` option that would make that easy, and in practice one-second granularity is sufficient …
=> Fix sort-by-last-read when partition is mounted noatime

frontend/ui/data/css_tweaks.lua, frontend/ui/wikipedia.lua
Includes:
- Fix getting xpointer to current page https://github.com/koreader/crengine/pull/195
- epub.css cleanup https://github.com/koreader/crengine/pull/194
- fb2def.h update https://github.com/koreader/crengine/pull/196
- Fix a few edge-case rendering issues https://github.com/koreader/crengine/pull/197
- Fix border being drawn in spite of 'border-width: 0' https://github.com/koreader/crengine/pull/198
Also update Wikipedia epub.css stylesheets regarding recent HTML fixes and enhancements.
Remove "Remove all borders" workaround tweak, as it's now fixed.
Some class name based styles have been removed from epub.css, mostly some stuff related to the FB2 format that was probably the first format supported by Cool Reader. For those nostalgic of these added styles, here's a file with them …
=> bump crengine: HTML and rendering fixes

frontend/apps/reader/modules/readertypeset.lua, frontend/document/credocument.lua, spec/unit/readerrolling_spec.lua
See https://github.com/koreader/crengine/pull/194#issuecomment-392834289 and https://github.com/koreader/crengine/pull/194#issuecomment-393293287 for the reasoning.
(TLDR: those other css are mostly duplicates, and epub.css should be better than any of them.)
Use epub.css as the main default style, with all file formats except FB2 (which needs fb2.css).
([epub.css has been cleaned recently](https://github.com/koreader/crengine/pull/194) to be more conforming to HTML specs and to not include class name based styles - with conditional compatiblity styles for previously opened documents. It should be usable on all HTML based documents, except FB2 which has some incompatible specs.)
Consider all shipped css files other than "epub.css" and "fb2.css" obsolete, and put them in a sub-menu (these …
=> Style menu cleanup

frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerhyphenation.lua, frontend/apps/reader/modules/readertoc.lua, frontend/document/credocument.lua, frontend/document/document.lua, frontend/ui/wikipedia.lua
Includes:
- Avoid page break between a node and its borders https://github.com/koreader/crengine/pull/207
- Allow building an alternative TOC from document headings https://github.com/koreader/crengine/pull/205
On CRE documents, allows toggling between original TOC and an alternative TOC with long-press on the "Table of content" menu item.
<kbd>![image](https://user-images.githubusercontent.com/24273478/41361664-e7728290-6f2f-11e8-9a2c-55cd757f3c04.png)</kbd>
It shows it's an alternative TOC in the menu with this small `*` (I tried to find other unicode symbols, but they were all too visible, and it felt strange with this simple menu often accessed - that small `*` feels discreet enough).
<kbd>![image](https://user-images.githubusercontent.com/24273478/41361691-f54900ce-6f2f-11e8-99cf-99eb …
=> bump crengine: alternative TOC, no page break on borders

frontend/document/credocument.lua
Default in crengine is 50%, and this may be too much for some users (words can look too much stuck to each other on some lines).
This manual setting may help testing if 70% or 80% is better, by adding to `settings.reader.lua`:
`"cre_min_space_condensing_percent" = 80`
(No real idea where to put that in menu or bottom config panel, and if that's really needed - should help testing if some other value is better then 50%.)
=> Add 'cre_min_space_condensing_percent' setting

frontend/apps/filemanager/filemanager.lua, frontend/apps/reader/modules/readerrolling.lua
Store the cache file path in book settings, so we can delete it too when deleting the book.
=> Remove cre cache file when deleting a book

frontend/ui/font.lua
Works around many of the CRe font errors on Kindle, as well as the really stupid ones (like trying to load macOS resource forks).
The actual check CRe does look dumb as hell, but I'm not familiar enough with the codebase to go at it with a machette, yet.
re #4021
=> Minor font sanity checking

Makefile, README.md, frontend/device/kindle/device.lua, frontend/ui/otamanager.lua, frontend/version.lua, platform/kindle/koreader.sh, platform/kindle/kotar_cpoint, platform/kindle/zsync_status.sh, platform/kobo/koreader.sh, platform/kobo/kotar_cpoint, spec/unit/readerlink_spec.lua, spec/unit/version_spec.lua
Requires a base bump to pickup FBInk, I'm waiting for #4040 to land first ;).
Minor fix to the version normalizer pattern so that it behaves properly with both older and current version strings (it was picking up the date suffix in the commit, and did not expect there to be >999 revisions since the last tag ^^).
=> Visual feedback around tar/zsync on Kobo during OTA updates

frontend/ui/data/creoptions.lua, frontend/ui/data/koptoptions.lua, frontend/ui/data/optionsutil.lua
So we can explain a bit what these do (and go a bit into technical detail, as these do not jump to the user face but he asked for it :)
<kbd>![image](https://user-images.githubusercontent.com/24273478/42229119-fd9d8cfc-7ee5-11e8-80dd-a206f10c179b.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/42229573-11170758-7ee7-11e8-8c38-8bffa5fecafb.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/42229188-2d8888b8-7ee6-11e8-838b-4acd9a2da008.png)</kbd>
When no help text:
<kbd>![image](https://user-images.githubusercontent.com/24273478/42229098-f17a1350-7ee5-11e8-9fef-8d97e4f44bb7.png)</kbd>
Hope someone can add some to the PDF/KOPT side of the bottom config :)
=> Add some help texts to long press popup on bottom config titles

frontend/ui/data/css_tweaks.lua
#4047 should be just below with the other Ignore publisher stuff (as we allow hyphenation by default, it's really a kind of Ignore publisher something).
<kbd>![image](https://user-images.githubusercontent.com/24273478/42271801-7fbafb40-7f84-11e8-8962-988f56b5e62e.png)</kbd>
=> Style tweaks: re-order Allow hyphenation on all text

frontend/ui/widget/touchmenu.lua
Should make things prettier in a few places (not many with English UI language, except dictionary names, but I guess there can be a lot in other UI languages).
Before:
<kbd>![image](https://user-images.githubusercontent.com/24273478/42212422-528c2852-7eb6-11e8-8fe5-7243f6ab1dd5.png)</kbd>
After:
<kbd>![image](https://user-images.githubusercontent.com/24273478/42272516-98cd99ec-7f86-11e8-8ac9-f0e3c7ed3199.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/42272505-906c49b0-7f86-11e8-838a-2af934bbab6b.png)</kbd>
=> TouchMenu: properly truncate item text when too long

frontend/pluginloader.lua
Plugins that a person doesn't need (or want shown in menus) can be disabled by manually adding into `settings.reader.lua` a setting like:
```lua
["plugins_disabled"] = {
["zsync"] = true,
["evernote"] = true,
["calibrecompanion"] = true
},
```
See https://github.com/koreader/koreader/pull/4043#issuecomment-402498354 and followups.
=> Allow disabling some plugins with manually added setting

frontend/ui/widget/buttontable.lua, frontend/ui/widget/textwidget.lua
=> Better display of text on buttons

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua, frontend/apps/reader/readerui.lua, frontend/ui/elements/reader_menu_order.lua, plugins/coverbrowser.koplugin/main.lua
Allows for quick switching between 2 documents (and keep symmetry with FileManager menu "Open last document", the last document being the one currently opened by reader, so... previous :).
Proposed at https://github.com/koreader/koreader/pull/4042#issuecomment-402389052
<kbd>![image](https://user-images.githubusercontent.com/24273478/42319824-70402ecc-8053-11e8-8cbe-6be4a1888412.png)</kbd>
With `Display mode > Other settings > Show filename in Open last/previous menu items` enabled:
<kbd>![image](https://user-images.githubusercontent.com/24273478/42319906-bc409d66-8053-11e8-80e6-3b8b72ae7854.png)</kbd>
=> Reader menu: adds "Open previous document"

Makefile, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, frontend/ui/network/manager.lua, frontend/ui/widget/networksetting.lua
Addressing part of [my own comment](https://github.com/koreader/koreader/issues/4034#issuecomment-402540116) in #4034 ;). (Also, re #3757).
Made it a toggle (enabled by default), because I'm not quite sure if that's always a helpful behavior (i.e., on my Kobo, it autoconnects to my usual network, so, yeah, I want it. But I only have *one* saved network. What happens when I have multiples, and it chooses the wrong one? Can this actually happen?).
Is the autoconnect behavior actually device-specific, too?
I can only test this on a Kobo, because Kindle shmingle, so, yeah, RFC ;).
=> Dismiss Wi-Fi scan popup after connection

frontend/apps/filemanager/filemanagersetdefaults.lua, frontend/ui/widget/multiinputdialog.lua
Close: #3680 
Fix: 
* size of window DCREREADER_CONFIG_FONT_SIZE in Advanced settings
* after leave inputtext (eg first on top to second one) we should set last one as unfocus - one inputtext should be focused in the same time.
Before:
After:
=> Fix size of DCREREADER_CONFIG_FONT_SIZE and fix focus/unfocus in MultiInputDialog

frontend/apps/reader/modules/readerfont.lua, frontend/apps/reader/modules/readerlink.lua, frontend/apps/reader/modules/readerstatus.lua, frontend/apps/reader/readerui.lua
Closes #3461.
Given that crengine is already reading buddy local files like linked images when rendering an HTML file, we can know navigate crawled/dumped web sites.
Also use the new ReaderUI:switchDocument(new_file) when already in ReaderUI in the other cases we switch document (so we have only one place to fix if need be).
I was a bit concerned while doing that about classic security issues when doing that, and wondered if we should add a checkbox to the `Links>` submenu: `Allow links to local files`.
But given we check it's a supported file (/etc/passwd is not), that our engine are quite dumb (no javascript engine to do malicious things), and that there is a ConfirmBox before following the link, we should be safe I think.
What do you think?
=> ReaderLink: allow following links to local files

frontend/ui/widget/checkbutton.lua, frontend/ui/widget/openwithdialog.lua, frontend/ui/widget/radiobutton.lua, frontend/ui/widget/radiobuttontable.lua
* add refresh after tap Cancel button,
* radiobutton and checkbutton with the same font size,
* truncates text outside window,
* better control font face and size in OpenWithDialog and RadioButtonTable widgets,
Before:
After:
=> Better display OpenWithDialog widget

frontend/apps/reader/modules/readerdogear.lua, frontend/ui/widget/imagewidget.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua, plugins/coverbrowser.koplugin/listmenu.lua, plugins/coverbrowser.koplugin/mosaicmenu.lua
The Dogear icon is 20x20 pixels and was never scaled where used. Now:
The bookmark icon (top right of screen) is scaled to 1/32th of the screen width (previously, it was 1/30th on a 600px wide emulator, 1/53th on a GloHD).
So, it should stay the same size on a small emulator, and become 2 times bigger on a 1000px device.
1/32 looks like this:
<kbd>![after_pdf_bookmark](https://user-images.githubusercontent.com/24273478/42754452-cc3d15ec-88f4-11e8-8fb3-257c0e404ae0.png)</kbd>
On CreDocument, furthermore decrease its size if needed depending on the selected margins so it never overwrite the text (as margins are scaled for DPI, this somehow scale the icon for dpi too).
Before => after
<kbd>![before_bookmark](https://user-images.githubusercontent.com/24273478/42754439-c765f64c-88f4-11e8-81c1-7 …
=> Bookmarks, CoverBrowser: scale dogear icon

frontend/apps/reader/modules/readerbookmark.lua, frontend/ui/gesturerange.lua, frontend/ui/size.lua, frontend/ui/widget/bookstatuswidget.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/inputtext.lua, frontend/ui/widget/logindialog.lua, frontend/ui/widget/menu.lua, frontend/ui/widget/pathchooser.lua, frontend/ui/widget/scrolltextwidget.lua, frontend/ui/widget/textboxwidget.lua
InputText, ScrollTextWidget, TextBoxWidget:
- proper line scrolling when moving cursor or inserting/deleting text to behave like most text editors do
- fix cursor navigation, optimize refreshes when moving only the cursor, don't recreate the textwidget when moving cursor up/down
- optimize refresh areas, stick to "ui" to avoid a "partial" black flash every 6 appended or deleted chars
InputText:
- fix issue when toggling Show password multiple times
- new option: InputText.cursor_at_end (default: true)
- as we are using "ui" refreshes while text editing, allows refreshing the InputText with a diagonal swipe on it (actually, refresh the whole screen, which allows refreshing the keyboard too if needed)
- if no InputText.height provided, measure the text widget height that we would start …
=> Text input fixes and enhancements

frontend/apps/filemanager/filemanagersearch.lua, frontend/device/kobo/device.lua, frontend/ui/widget/scrolltextwidget.lua
By setting SEARCH_LIBRARY_PATH when a Calibre tree is found, so that
book paths can properly be constructed.
Users should still very much set it themselves, but at least everything
works as intended when not, instead of mysteriously half-breaking later.
Drop the SetDefaults bits, it appeared to have been added to fix no-ops
detected by Luacheck, and it's actually non-functional, because
SetDefaults doesn't handle saving variables it did not itself assign.
So this was just causing the "Do you want to save new defaults" popup to
show up on exit, but it couldn't actually do anything useful (like, say,
save the new SEARCH_LIBRARY_PATH value).
fix #4082
=> Make findcalibre actually useful

frontend/apps/reader/modules/readermenu.lua, frontend/ui/elements/screensaver_menu.lua, frontend/ui/screensaver.lua
This PR adds support for setting single image as screensaver.
You can activate this function in `Screensaver -> Use image as screensaver`
You can select image to dispaly in `Screensaver -> Settings -> Screensaver image` 
default is /resources/koreader.png
You can choose a different file in `Choose screensaver image`
=> Allow select single image as screensaver

defaults.lua
Close: #4094 
Preventing overlap long tap for footer and last line of text.
=> Smaller default touch zone for footer (minibar)

frontend/apps/reader/modules/readerfooter.lua
See comment: https://github.com/koreader/koreader/issues/4094#issuecomment-406858743
> And launch the SkimTo widget instead of the Goto widget. The SkimTo widget is more pratical, and it looks more logical: you tap on the footer which usually displays the progress bar: launch a widget that display the same kind of progress bar that you can additionally tap on to go to that position.
=> Change default widget from GoTo to SkimTo after long press on footer

frontend/ui/elements/screensaver_menu.lua, frontend/ui/widget/screenshoter.lua
Close: #2115 
Option to save a screenshot as the current screensaver image. Defalut this option is disabled. You can activate it in `Screensaver -> Settings -> Screenshot as screensaver`
Than you can do it
=> Screenshot as screensaver image

frontend/apps/reader/modules/readerrolling.lua, platform/kobo/koreader.sh, plugins/coverbrowser.koplugin/bookinfomanager.lua, plugins/statistics.koplugin/main.lua
After a round of testing (and facepalming, and headdesking...).
Anyway, make it more conservative in general, which, hopefully, means it's now basically a giant NOP, and leaves us poor Mark5 fuckers in the mud, because there's no real solution.
At least I have something new to blame for the terrible battery life or performance on Mk5 now ;).
Re #4114 for the gory details in the middle of my ramblings ;).
----
Also, a couple unrelated fix:
* Minor ghosting tweak for the location swap markers.
* Switch SQLite DBs to WAL, it appears to mesh well with our workflow.
=> Tweak/unbreak my CPUFreq experiment

frontend/ui/rendertext.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/inputtext.lua, frontend/ui/widget/verticalscrollbar.lua, frontend/ui/widget/virtualkeyboard.lua, frontend/util.lua
InputText: checks whether provided content can be given back unaltered, which may not be the case after it is splitted to UTF8 chars if the text is binary content. Prevent editing text if that is the case.
See https://github.com/koreader/koreader/pull/4070#issuecomment-408671971
Added InputText and InputDialog :isEditable() and :isEdited()
Virtual keyboard: Hold on Backspace: delete from cursor to start of line instead of clearing all text content. Shouldn't feel like too much a change on the most common single line InputTexts (it now deletes from cursor, but as these starts with cursor at end, it will work as clear all if used at start), and it is more convenient and useful (quicker lines deletion) on the newly possible multi lines edits. Closes #4129.
Also ensure a minimal size of the …
=> Text input related fixes & enhancements

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerstyletweak.lua, frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/data/optionsutil.lua, frontend/ui/quickstart.lua, frontend/ui/widget/hyphenationlimits.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua, plugins/goodreads.koplugin/main.lua, plugins/statistics.koplugin/main.lua
Some problem somewhere with `[[...]]` strings starting with a leading newline. Should probably be allowed, but for now fix the few such cases to allow them being translated.
See #4085, and https://github.com/koreader/koreader/issues/4085#issuecomment-406059074 for proper and definitive solutions.
=> Fix untranslatable strings

frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/downloadmgr.lua, frontend/ui/widget/filechooser.lua, frontend/ui/widget/pathchooser.lua
Explicit new options: `select_directory`, `select_file`, `show_files`.
With `select_directory=true`, show an entry to select current directory (so, removed undocumented hack "hold on .. to select current directory"). This goes well with the newly displayed current path under the title.
With `select_directory=true` and `show_files=true` in the various display modes:
<kbd>![image](https://user-images.githubusercontent.com/24273478/43627309-12cac32e-96f6-11e8-9783-57c143fbd1b0.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/43627326-288f67e6-96f6-11e8-9351-d14e8741a307.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/43627413-9b18800e-96f6-11e8-8a54-d0bb3d43cd7b.png)</kbd>
With `select_directory=false` and `select_files=true` …
=> PathChooser: clearer usage and behaviour

frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, frontend/ui/widget/buttontable.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/inputtext.lua, frontend/ui/widget/logindialog.lua, frontend/ui/widget/multiinputdialog.lua, frontend/ui/widget/openwithdialog.lua, frontend/ui/widget/scrolltextwidget.lua, frontend/util.lua, plugins/texteditor.koplugin/main.lua
Followup of initial idea and implementation by @mwoz123 in #4070.
The nice thing is we will now be able to read crash.log and do small mods to style tweaks, lua code, font or element sizes, for testing, from koreader itself.
And obviously to read koreader own code in koreader, cause there is no reading more interesting than that :)
This plugin mostly sets up a `Text editor>` submenu, that allows browsing files, creating a new file, and managing a history of previously opened file for easier re-access.
<kbd>![image](https://user-images.githubusercontent.com/24273478/43675702-9e4ab6b8-97e4-11e8-827c-c00f72bc4bd9.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/43675833-d2fe6506-97e6-11e8-8c69-b6b945aa9321.png)</kbd> …
=> Text editor plugin, InputDialog enhancements

frontend/docsettings.lua
docsettings can be stored either as a sidecar file (prefered, when possible), or as a .lua file in the koreader/history/ folder (good, when book is in a read-only directory where we can't create the
.sdr/ directory).
They are managed correctly if for some reason, the book directory becomes writable: the docsettings in history/ is read, used, and removed when a docsetting in a .sdr/ can be saved.
These docsettings in koreader/history/ contribute to the History list build: they are put it in history.lua, and the duplicates on next history.lua builds are removed.
This fix a crash when a book is in a read-only directory. Closes #3869.
I verified that I can now open on Android books stored on the external SDCard, and the docsetting is saved in koreader/history/ . Closes #3365. Closes #3483. …
=> Fix crash and History with books in read-only directories

frontend/apps/reader/modules/readerhyphenation.lua, frontend/document/credocument.lua
The hyphenation algo setup was the only one using onPreRenderDocument, because it needed access to the document language to set accordingly the hyphenation algorithm.
Setting the hyph algo before loading the document may save crengine from re-doing some expensive work at render time (the hyph algo is accounted in the nodeStyleHash, and would cause a mismatch if it is different at render time from how it was at load time - "English US" by default - causing a full re-init of the nodes styles.)
We will only re-set it on pre-render (only then, after loading, we know the document language) if it's really needed: when no algo saved in book settings, no default algo, and book has some language defined.
Before, the hyphenation settings were only and always applied after loading. It was working …
=> Hyphenation: speed up book loading by setting hyph algo earlier

frontend/ui/widget/inputdialog.lua, frontend/ui/widget/inputtext.lua, frontend/ui/widget/scrolltextwidget.lua, frontend/ui/widget/textboxwidget.lua, plugins/texteditor.koplugin/main.lua
Feature of ScrollTextWidget, only used for now by TextEditor.
Pan is like Swipe, but wait a bit at end of gesture to release: the line on which Pan was started will be moved to where Pan is released.
May conflict with MovableContainer (so not enabled for DictQuickLookup, where it could have been nice - but it would work only with text dictionaries, not with HTML ones, as ScrollHtmlWidget can't really do that).
Useful to make a whole block of text contained into view, and not be limited by rigid page by page scrolling (eg: to move the `function Widget:name()` at top of screen and have a wider view  of it while you wonder wtf that function does :)
=> TextEditor: allow scrolling by lines with Pan

Makefile, frontend/device/kobo/device.lua
To avoid early blacklist of the blitbuffer code on alpha-blending
workloads.
Least terrible workaround we could come up with to "fix" #4137
=> Tweak JIT's loopunroll threshold on Kobo 16bpp

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua, frontend/pluginloader.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, plugins/SSH.koplugin/main.lua, plugins/autofrontlight.koplugin/main.lua, plugins/autosuspend.koplugin/main.lua, plugins/backgroundrunner.koplugin/main.lua, plugins/batterystat.koplugin/main.lua, plugins/calibrecompanion.koplugin/main.lua, plugins/coverbrowser.koplugin/main.lua, plugins/evernote.koplugin/main.lua, plugins/goodreads.koplugin/main.lua, plugins/hello.koplugin/main.lua, plugins/keepalive.koplugin/main.lua, plugins/kobolight.koplugin/main.lua, plugins/kosync.koplugin/main.lua, plugins/newsdownloader.koplugin/main.lua, plugins/perceptionexpander.koplugin/main.lua, plugins/readtimer.koplugin/main.lua, plugins/send2ebook.koplugin/main.lua, plugins/statistics.koplugin/main.lua, plugins/systemstat.koplugin/main.lua, plugins/terminal.koplugin/main.lua, plugins/texteditor.koplugin/main.lua, plugins/timesync.koplugin/main.lua, plugins/zsync.koplugin/main.lua
Reference: #2544 and #4054 
This PR gives you the option of enabling/disabling any plugin via the GUI. This is a continuation of the work @poire-z  in #4054.
Screenshots:
=> Plugin manager

README.md
As discussed with @Frenzie over email.
Hall-of-fame is a widget that automatically features new/trending/top contributors in a repo. It is designed to be very visual, and change frequently. Requires no maintenance, autoupdates every hour.
Side effects of merging this PR:
1. Frenzie GitHub token will be used to update the widget. This will take 10-15 requests out of 5,000 rate limit that GitHub enforces.
2. I will become a contributor to koreader, which means that my face will show in Hall-of-fame with the badge 'new' for 1 week.
=> Hall-of-fame to recognize contributors on README

frontend/ui/message/streammessagequeue.lua
(Actually should be size_t, but gcc-lua downgraded that to the
pointed-to type, for... reasons?).
Fix #4187
=> One more øMQ FFI fix that slipped through the cracks

Makefile
This should unbreak the AppImage build without having to update the Docker image.
Fixes https://github.com/koreader/koreader-base/issues/730
=> [build] Stick to AppImageTool 10

frontend/apps/filemanager/filemanager.lua, reader.lua
See comment: https://github.com/koreader/koreader/pull/4165#pullrequestreview-147292540
=> New startup option - Folder shortcuts

plugins/statistics.koplugin/main.lua
Two new statistics in `Current book`:
* Estimate end of read
* Average time per day
=> [Statistics] Add estimate end of read

frontend/device/generic/device.lua, frontend/device/pocketbook/device.lua
=> Add support for Pocketbook Color Lux

frontend/device/android/device.lua, frontend/device/generic/device.lua, frontend/device/kindle/device.lua, frontend/device/kobo/device.lua, frontend/device/pocketbook/device.lua, frontend/device/sony-prstux/device.lua, frontend/ui/elements/common_info_menu_table.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, frontend/ui/otamanager.lua
Remove Android since we cannot provide OTA updates other than upgrading the APK, which is done outside KOReader
Pinging @v01d about PRSTUX devices. Would they support over-the-air updates?
=> show OTA updates on supported devices

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerview.lua, frontend/document/credocument.lua, frontend/ui/data/css_tweaks.lua, frontend/ui/font.lua, frontend/ui/widget/textviewer.lua
Allow viewing selection HTML, for easier debugging of rendering issues.
We should now be able to see the HTML and CSS used by a book, and why it renders in such a way - and, thanks to the text editor, to create and test a Style tweak, all that directly on the device (before, you needed a computer to look at the EPUB and see what kind of tweak was needed). Requested in https://github.com/koreader/koreader/pull/3944#issuecomment-421562673.
Also fix highlighting of some multi-lines texts.
Details and screenshots in https://github.com/koreader/crengine/pull/236 and https://github.com/koreader/koreader-base/pull/740. Will need bumps for these.
Also adds 2 page-break related Style tweaks, and fix a typo in some help text.
=> Selection menu: allow viewing HTML

frontend/apps/filemanager/filemanager.lua, frontend/ui/elements/common_settings_menu_table.lua
The menu to select this behavior is under "Gear" > "Navigation"
It default to the current behavior named "default"
=> [Key navigation] The back key can be used to go to the parent folder.

frontend/apps/reader/modules/readerflipping.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerlink.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/document/credocument.lua, frontend/ui/widget/footnotewidget.lua, frontend/ui/widget/htmlboxwidget.lua, frontend/ui/widget/scrollhtmlwidget.lua
Adds new options to the `Links>` submenu, for now only available and used with CRE documents (*).
<kbd>![image](https://user-images.githubusercontent.com/24273478/46674602-d44f2380-cbdc-11e8-8c00-69d831846b71.png)</kbd>
The `Show footnotes in popup` is both in the Tap and the Swipe sub-sections, as one may want it for Tap but still follow with Swipe, and some others may have disabled Tap, but still want to see footnotes with Swipe.
The `Show more links as footnotes` is mostly for testing and loosening the footnote detection algorithm, and see how it would behave with glossary-like links and inter glossary terms links.
(Please have a look at the settings names, I'm not really satisfied with the `link_prefer_foonote` name, if we keep that item.)
Fixed distance computation from gesture …
=> EPUB links: show footnotes in popup, larger tap area

frontend/apps/reader/modules/readerrolling.lua
close #4263 
Look like the TODO from 6 years ago was actually relevant ! 
`@TODO disable panning in page view_mode?  22.12 2012 (houqp)`
=> Disable panning in page view_mode

frontend/apps/filemanager/filemanager.lua, frontend/document/documentregistry.lua, frontend/ui/widget/filechooser.lua, kodev
Not a good practice to have the core document code depend on UI elements ;)
=>  decouple UI from core document code

frontend/apps/reader/modules/readercoptlistener.lua, frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readerlink.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/document/credocument.lua, frontend/ui/widget/footnotewidget.lua, spec/unit/readerfooter_spec.lua
See individual commits messages.
Fix some issues reported at https://github.com/koreader/koreader/pull/4261#issuecomment-429265831
A few notes:
I moved the `self.ui.document:setStatusLineProp(status_line)` which is the call that enables the status bar in crengine from ReaderFooter to ReaderRolling, because it's more logical, and the `ReaderFooter:onSetStatusLine` is set to a no-op when footer is totally disabled.
I just discovered that Scroll mode and Full status bar don't work well together (no full status bar displayed when scroll mode is enabled). This looks like it's not supported by crengine itself (I have no intent to fix this combination of 2 rarely used options :)
I fixed: when switching Progress bar from 'full' to 'mini', show the mini bar again, with the side effect that the …
=> Fix some footnotes and full status bar issues

frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/reader_menu_order.lua, plugins/wallabag.koplugin/_meta.lua, plugins/wallabag.koplugin/main.lua
A plugin to download articles from a Wallabag server, an open source read-it-later service (https://wallabag.org).
Issues:
- (solved) The settings menu changes the menu item text for the download directory and the tag filter. It makes it easy to see the current configuration. But I have not found how to refresh the value after a change. I could remove the feature but I'd rather have a hint on how to fix it.
- To skip files that already exist locally, I want to check the dates of the local and remote versions. The only date parser is in the newsdownloader plugin. I have added an ugly hack to use it if available. Thoughts?
=> Wallabag plugin

frontend/apps/reader/modules/readerbookmark.lua, frontend/ui/elements/reader_menu_order.lua
=> [Non-touch] Add a menu item to toggle a bookmark on the current page

frontend/apps/cloudstorage/cloudstorage.lua, frontend/apps/cloudstorage/webdav.lua, frontend/apps/cloudstorage/webdavapi.lua
Addition of WebDav to the CloudStorage. The functionality is the same as with Dropbox and FTP, it is possible to browse the files on the server and download a copy.
Tested with:
- NextCloud
- HubZilla
=> WebDav CloudStorage

frontend/apps/cloudstorage/cloudstorage.lua, frontend/apps/cloudstorage/ftp.lua
The settings screen for the FTP cloud storage has a setting for a folder but that is then never used. Going back to edit the settings after saving, the folder is back to its default value. 
The fix is simply to change the field it is saved to.
=> Fix for FTP folder being saved to an unused setting.

plugins/wallabag.koplugin/main.lua
When the Wallabag plugin is not configured, there is an error loading the absent config file.
Setting a value of {} fixes it (thanks poire-z).
=> Wallabag: fix for un-configured plugin error

frontend/ui/opdsparser.lua, frontend/ui/widget/opdsbrowser.lua
Added supports the French catalog _Ebooks Libre et Gratuits_ at https://www.ebooksgratuits.com/opds/index.php
(Catalog not added to the default list; it needs to be entered manually by users)
- added Host header
- filtered CDATA section out
Fix for Internet Archive URL in the default servers
- trailing slash required for the links to work
Fixes #4279
=> OPDS fixes: support for www.ebooksgratuits.com catalog, fix for archive.org

frontend/device/kobo/device.lua, frontend/device/kobo/powerd.lua, frontend/device/sysfs_light.lua
syfs_light was written originally for Kobo Aura One but works fine on other devices w/ natural light (like other new kobos and Bq cervantes 4).
Some devices don't have a green led and /dev/null is used as the sysfs_path, causing log errors trying to write to /dev/null/bl_power and the like.
This PR moves sysfs_light outside kobo realm (because I'm going to use in cervantes) and removes the Kobo Aura One values hardcoded in the file. It doesn't try to write to nil dirs, so errors in log are also removed.
=> refactor sysfs_light

Makefile
It came out last week: https://github.com/AppImage/AppImageKit/releases/tag/11
I also fixed the `libcairo` issue from https://github.com/koreader/koreader-base/issues/730 in https://github.com/koreader/virdevenv/pull/21
=> [build, AppImage] Update to AppImageTool 11

frontend/version.lua
=> [hotfix] Version: empty pattern match is an empty string, not nil!

frontend/apps/reader/modules/readergesture.lua
Also put left first, which seems more logical.
Cf. https://github.com/koreader/koreader/issues/4300#issuecomment-435302101
=> [fix, lang] Bottom left/right adjective order

kodev
Use `-z` instead of `! -n`.
See https://github.com/koalaman/shellcheck/wiki/SC2236
=> [fix] Minor kodev shellscript issues

frontend/ui/data/css_tweaks.lua
bump crengine, which includes:
- Avoid uneeded re-rendering on load when with full status bar https://github.com/koreader/crengine/pull/238
- Update french hyphenation pattern https://github.com/koreader/crengine/pull/239
- https://github.com/koreader/crengine/pull/240 https://github.com/koreader/koreader-base/pull/751 :
- Fix border-collapse on table cells in some cases
- Fix line-height inheritance when no unit
- Fix: don't ignore space following an image
- Fix: ignore occasional space at start of line
- Fix possible segfault when viewing HTML
- Fix and extend support of vertical-align
Also includes:
- [build] Pull in thirdparty repos with --depth 50 https://github.com/koreader/koreader-base/pull/675.
Also add a style tweak to middle align images with text, which may make some text with …
=> bump crengine: fix vertical-align and others

frontend/version.lua, spec/unit/version_spec.lua
Also see #4303.
#4299 was an emergency patch. This should fix it up properly.
=> [fix] Version pattern: add two extra numbers for point release

frontend/document/djvudocument.lua
As of f71627cf, DjVu support for metadata is faked by setting the document tite to the file's basename. This is fixes that. It is the frontend companion to koreader/koreader-base#753, as such the continuous integration will inevitably fail until base integrates those changes.
If there's a better protocol for this kind of split pull request, please let me know.
This is my first foray into koreader's codebase as well as lua programming, so please forgive any boneheadeness. I tried to model the `DjvuDocument:getProps()` method after its namesake in `frontend/document/pdfdocument.lua`.
The silliness with capitalized keys versus lowercase, as mentioned in the code comment, comes from the covention mentioned in djvused(1). I considered `lower()`ing all `props` keys into a new table, but I …
=> [Feature] Support DjVu metadata

frontend/device/cervantes/device.lua
This was preventing the app from starting; with this tweak and https://github.com/koreader/koreader-base/pull/755 we're up and running on the Cervantes 3!
=> Old Cervantes devices don't hasNaturalLights

frontend/device/cervantes/device.lua, frontend/ui/network/manager.lua, frontend/ui/uimanager.lua, platform/cervantes/enable-wifi.sh, platform/cervantes/koreader-standalone.sh, platform/cervantes/koreader.sh
device: fix device names by removing spaces to match the base logic (https://github.com/koreader/koreader-base/pull/755)
wireless: read status from sysfs, disable auto_restore_wifi, improved compat w/ QBookApp.
power: suspend on power wake, like kobos
scripts: enable fbink visual feedback during OTA updates.
standalone: add support for https://github.com/pazos/cervantes-safemode, to start/stop usbnet & usb mass storage until #4306 is ready.
=> [Cervantes]: misc fixes & improvements

frontend/apps/reader/modules/readerconfig.lua, frontend/apps/reader/modules/readerfooter.lua, frontend/apps/reader/modules/readertoc.lua, frontend/ui/widget/menu.lua
- ReaderConfig does not need to call again self:initGesListener() on screen rotation/resize, as it uses the TouchZone infrastructure that deals itself with rotation. So, it was adding new same gestures that were overriding tap on footer and preventing it from working. See https://github.com/koreader/koreader/issues/4332#issuecomment-437768464. Closes #4332.
- ReaderFooter: fix refresh area (which was too small when toggling from hidden to visible)
- ReaderToc: fix crash when showing TOC in scroll mode after rotation. See https://github.com/koreader/koreader/issues/4328#issuecomment-437700619
- Menu: fix crash when no onReturn defined (could happen when tap on bottom left corner when showing an empty TOC). Closes #4330.
=> Fix a few edge cases crashes and issues

frontend/apps/reader/modules/readerrolling.lua
Follow-up of #4162. Closes #4338
(It seems double tap is only implemented for credocuments in readerolling - so no fix needed on the readerpaging side)
=> Double-tap chapter nav: add origin page to location stack

plugins/wallabag.koplugin/main.lua
- Tag not included in request if not set. Fixes #4337
- Skip failed download rather than stop everything. Fixes #4340
- Delete leftover file after failed download (ie HTML file with error description in it).
- Display number of failed files.
- Check number of articles before proceeding.
- Skip remote deletion process if disabled.
=> Wallabag fixes and improvements

frontend/device/kindle/device.lua
Fix toggling the FL on/off (as that's the only instance we're not using
lipc)
=> Fix frontlight sysfs path on the PW4

frontend/apps/filemanager/filemanagersearch.lua, frontend/apps/reader/readerui.lua, frontend/document/credocument.lua, frontend/ui/screensaver.lua
When a main document is opened for displaying, some other document openings (for getting metadata or cover image) could affect the main document.
Split some code from CreDocument:init() into another new method CreDocument:setupDefaultView(), that will only be called by ReaderUI when opening the main document (and not by these other openings like Book inforation, View cover...)
Details in https://github.com/koreader/koreader/issues/4346#issuecomment-440036496. Closes #4346.
Will need a base bump for https://github.com/koreader/koreader-base/pull/766.
Also speed up some of these other openings (Search, Screensaver) by using doc:loadDocument(false) to load only metadata and avoid parsing the HTML.
=> CreDocument: fix document loading interferences

frontend/device/pocketbook/device.lua
Fix: unrecognized PocketBook model PocketBook 630
=> Add support for PocketBook 630

frontend/apps/filemanager/filemanager.lua, frontend/apps/filemanager/filemanagerhistory.lua, frontend/apps/filemanager/filemanagerutil.lua, frontend/apps/reader/modules/readermenu.lua
In reader, after having opened doc1.html and doc2.html, being in doc2.html, going to History (where Delete on current book doc2.html is forbidden) and deleting doc1.html, we would still see in the top right menu: `Previous: doc1.html`, and taping on it would show the Opening dialog, an error, and KOReader would exit (UIManager: no widget left to show).
This fixes this by ensuring we alway refresh the previous document in that menu item to the previous still existing document.
I also ensured it globally for any Delete from FileManager or History invoked from FileManager, to fix: Reading doc1.html > File browser > delete doc1.html > Exiting Koreader > Opening Koreader > `Cannot open last file. This could be because it was deleted or because external storage is still being mounted. Do you …
=> Ensure "Open last/previous" point to existing files

frontend/ui/widget/networksetting.lua
When Wifi is connected, the message "Connected." stays on the screen
waiting for the user feedback. The change sets reasonable timeout
for info message to disappear
=> Set timeout for wifi result info message

frontend/document/pdfdocument.lua
Makes an attempt at a reasonable default. References #4368.
=> [fix] MuPDF: set default DPI-based EPUB fontsize

platform/kindle/extensions/koreader/menu.json
It's generally broken, and useless there.
The main intended use-case is the DX/DXg, because of its larger screen &
low RAM leading to more severe memory constraints.
=> Hide "no framework" buttons on FW 5.x

frontend/ui/data/css_tweaks.lua
It just occured to me that we don't need yhe first-level menu to be short if it contains no tweak itself (only the submenus with toggable tweaks need to be kept shorter to let room below to see the tweak effects).
For now with this PR (just moved Tables and Images out from `Miscellaneous>`)
<kbd>![image](https://user-images.githubusercontent.com/24273478/49668017-2eddf200-fa5d-11e8-9f2c-39d76ab85730.png)</kbd>
We have room for 8 submenus containers of tweaks (10 minus the top info item minus the bottom user style tweaks) if we want them all on a single page.
The only submenu that contains itself submenus is `Text>`:
<kbd>![image](https://user-images.githubusercontent.com/24273478/49668124-7cf2f580-fa5d-11e8-87ae-6a23ecf2a315.png)</kbd>
So, we have room for the 3 submenus from `Text>` (but …
=> Style tweaks: move some sub-menus to first-level menu

frontend/ui/elements/screen_dpi_menu_table.lua
* It was unclear that you needed to hold to set DPI, see https://github.com/koreader/koreader/issues/2589#issuecomment-445471384
* Up the DPI limit to 900 as several Android devices have already breached 800. This will increase the possibility of crashes due to a higher setting even on relatively high-DPI devices, but that was always already an issue.
* Also brings the custom DPI dialog box in line with the UX guidelines as per <http://koreader.rocks/doc/modules/ui.widget.confirmbox.html>.
=> [UX] Inform about hold to set custom DPI, up DPI limit to 900

frontend/ui/elements/screen_dpi_menu_table.lua
Follow-up of #4388.
Implements the suggestion by @turkeyphant from <https://github.com/koreader/koreader/issues/2589#issuecomment-445474155>.
Also adds a little explanatory message when holding on the Auto DPI option.
=> [UX] DPI: show concrete numbers and add more custom DPI presets

frontend/apps/reader/modules/readerlink.lua
Fix crash with `attempt to index field 'xpointer'` when taping on an external link in a PDF document.
=> Fix crash when tap on external link in non-EPUB documents

frontend/ui/elements/screen_eink_opt_menu_table.lua
Fixes confusion caused by its appearance such as in #4396.
=> [UX, Android] Hide E Ink full refresh setting on Android

frontend/ui/menusorter.lua, plugins/hello.koplugin/main.lua, spec/unit/menusorter_spec.lua
By adding a `sorting_hint` to a menu item, the program will put orphaned items in the relevant (sub)menu instead of in the first menu with a NEW prefix.
Fixes #4393.
=> [feat] MenuSorter: add sorting_hint support

Makefile, README.md
Requires ~~https://github.com/koreader/koreader-base/pull/774~~ && ~~https://github.com/koreader/koreader-base/pull/778~~ && bump base
=> Fix for #4375

plugins/SSH.koplugin/main.lua
I tried to actually use this feature and five seconds isn't enough time to register the relevant IP:port to connect.
I'd add a menu item to call up the info (without a timeout) but this is just a web interface quickie.
=> [UX] SSH: double info dialog timeout

frontend/ui/widget/opdsbrowser.lua
I've encountered an issue where an `OPDS` catalog was redirecting the client to a different host, but since the `Host` header is set  in `frontend/ui/widget/opdsbrowser.lua`, the client retries, until it fails.
I've noticed, that before creating the request, `socket/http` automatically creates the `Authorization` (if `username` and `password` are provided) and `Host` headers, which is why i split the `http` and `https` request generation.
There's probably a better way to handle this (preferably by using a library that can do `http`/`https` seamlessly).
Please feel free to disregard this PR if does not conform to the code quality of the project.
=> Fix http redirects, where the target host differs

frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/modules/readerview.lua, frontend/device/cervantes/powerd.lua, frontend/device/input.lua, frontend/device/kobo/device.lua, frontend/device/kobo/nickel_conf.lua, frontend/device/kobo/powerd.lua, frontend/device/sysfs_light.lua, frontend/ui/data/koptoptions.lua, frontend/ui/widget/frontlightwidget.lua, platform/kobo/koreader.sh, platform/kobo/nickel.sh, plugins/kobolight.koplugin/main.lua
* Enforce Portrait on startup, to avoid getting touch coordinates wrong if we were started from Nickel in inverted Portrait.
* Fix button mapping, and made it behave properly in landscape. I may have massively ruined non-Portrait mappings for everyone else, but, hey, this made sense, and it works here ;p.
* Fix NaturalLight handling, thanks to @cairnsh & @pazos in #4291 ;)
=> Better Forma handling (fix #4291)

frontend/ui/otamanager.lua, platform/common/spinning_zsync
Fix #4429 (and by "fix", I mean "workaround' ;p).
Basically gives the user another choice on failure, one that'll download the full OTA package.
Prevents leaving users in the lurch in case zsync goes wonky again, like in #4429 ;).
=> If zsync eats dirt during an OTA update, allow to fallback to a full download

frontend/apps/reader/modules/readerrolling.lua, frontend/readhistory.lua, plugins/coverbrowser.koplugin/listmenu.lua, plugins/coverbrowser.koplugin/main.lua
Fix some conflict on Android where a swipe north from the bottom to show system buttons (to exit or swith apps) would cause a page change. These gestures have never been available in ReaderPaging, so it shouldn't be a big loss. https://github.com/koreader/koreader/issues/4326#issuecomment-437668418. Closes #4326.
See https://github.com/koreader/koreader/issues/4266#issuecomment-428994659. Closes #4266.
See https://github.com/koreader/koreader/issues/4436#issuecomment-450652619. Closes #4436.
2 independant options, that can make sense independantly (and easier to do than a `Show progress as >` menu with a subitem for each combination of % / pages read / pages left):
<kbd>![image](https://user-images.githubusercontent.com/24273478/50571452-a1679680-0dab-11e9-9a67-4c8fb0160fc8.png)</kbd> …
=> Various ui fixes: file sizes in History, pages read/left in CoverBrowser

frontend/apps/reader/modules/readerstyletweak.lua, frontend/ui/data/css_tweaks.lua
Adds 2 tweaks to allow displaying footnotes at the bottom of pages, like it's done in some printed books. This will work only with books with correctly specified footnotes with the adequate EPUB attributes, and with Wikipedia EPUBs. But users may be able to activate them for other books with some user style tweaks.
Details and some sample pages screenshots in https://github.com/koreader/crengine/pull/249
<kbd>![image](https://user-images.githubusercontent.com/24273478/50574984-b1a36400-0df3-11e9-8d2d-1291d539e48b.png)</kbd>
Not sure if we should keep the `.footnote, .note, .note1` extra, it might be wrong with some books, but it adds a bit of documentation on how one could do that in his user style tweaks.
Adds a few tweaks to control the build of the alternative TOC, and a bit of …
=> cre: adds in-page footnotes and alternative TOC hints tweaks

frontend/dbg.lua, frontend/logger.lua, platform/android/llapp_main.lua
So we can filter messages in logcat.
For example: 
`adb logcat KOReader:V luajit-launcher:I *:S` will print verbose messages for KOReader and info or higher for luajit-launcher.
`adb logcat KOReader:V *:S` will print verbose messages for KOReader (this is the same as `adb logcat | grep KOReader`)
`adb logcat KOReader:I *:S` will print info or higher messages for KOReader.
######
<details>
<summary>Here is a sneak peak of logging info messages:</summary>
```
--------- beginning of system
--------- beginning of main
12-27 20:11:43.799 31577 31622 I KOReader: try to load module libs/libkoreader-lfs.so
12-27 20:11:43.799 31577 31622 I KOReader: dl.lua - dl.dlopen - library lname detected /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
12-27 20:11:43.800 31577 31622 I …
```
=> [Android]: use proper log levels

.gitignore, Makefile, datastorage.lua, frontend/device/generic/device.lua, frontend/device/sdl/device.lua, kodev, platform/debian/do_debian_package.sh, platform/debian/koreader.desktop, platform/debian/koreader.sh
Fixes #3108 and **maybe** #4398 
Requires https://github.com/koreader/koreader-base/pull/785
=> add support for debian packages

frontend/ui/elements/common_settings_menu_table.lua
For a hidden setting already present (added in #3862) and used in [frontend/apps/reader/modules/readerback.lua](https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerback.lua)
Only shown, as the whole Navigation> submenu, on devices with keys.
See https://github.com/koreader/koreader/issues/4421#issuecomment-451175347
=> Adds "Enable back history" menu item

frontend/device/pocketbook/device.lua
Add support for Pocketbook 641 aka Aqua 2.
Tested on a real device, works well.
=> PB641: add support

frontend/ui/data/css_tweaks.lua, frontend/ui/wikipedia.lua
Will include a bump for crengine, which includes https://github.com/koreader/crengine/pull/250
- CSS: avoid publisher's !important from overriding ours (see https://github.com/koreader/koreader/issues/4196#issuecomment-451016032)
- In-page footnotes: fix vertical position when full status bar (closes #4444)
- In-page footnotes: avoid duplicated footnotes on same page
- In-page footnotes: fix ignored link in nested tags
- In-page footnotes: gather links in table cells
- In-page footnotes: fix page splitting edge cases
Split the In-page footnotes tweak into 3 distinct ones, mainly because I want the 3rd one with classic class names to be disabled'able, while keeping the others, in case these classic class names are not used for footnotes. …
=> Style tweaks: split in-page footnotes tweaks

frontend/apps/reader/modules/readergesture.lua, frontend/device/generic/device.lua, frontend/device/input.lua, frontend/device/kobo/device.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/elements/screen_eink_opt_menu_table.lua, frontend/ui/elements/screen_toggle_gsensor.lua, spec/unit/device_spec.lua
* Fix the Touch input probe on Trilogy devices that depend on the touch_probe_ev_epoch_time quirk (fix #630)
* Expose a "PageTurn button inversion" feature in the Navigation menu (for all devices with keys) (fix #4446)
* Allow ignoring the accelerometer on the Forma (Screen > Ignore accelerometer rotation events) (fix #4451)
* Fix SleepCover handling on the Forma (fix #4457)
* Make isWifiOn a tiny bit more accurate (check the actual WiFi module instead of sdio_wifi_pwr)
=> A few Kobo input tweaks

frontend/device/cervantes/device.lua, frontend/ui/network/manager.lua
Iterate over available networks ordered by signal power, and check if we
can connect to saved SSIDs. If we can, then skip network list dialog.
=> wifi: try to connect to known network before listing

frontend/device/cervantes/device.lua, frontend/ui/network/manager.lua, platform/cervantes/restore-wifi-async.sh
Fixes #4422 
The patch runs shell script and pipes known networks from `settings/network.lua` to `wpa_cli` executable.
=> [cervantes] automatically restore wifi connection

frontend/device/pocketbook/device.lua, frontend/ui/network/manager.lua
* Detect the PocketBook Basic Touch 2 (fix #4366)
* Workaround a few WiFi corner-cases on some Kobo devices (i.e., make the 'Wi-Fi connection' menu less stupid) (fix #4387)
=> Random bug triage!

frontend/device/android/device.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/elements/screen_keep_on_menu_table.lua
continuation of #4409 , which I managed to close somehow, sorry :p 
Fixes #2748
Fixes #4364
Related to #4430 #3567 #3517 
In *some* phones *some* runtime configuration changes will force a surfaceDestroyed (followed by surfaceCreate) without losing/regain focus, so we need to refresh the screen on APP_CMD_INIT_WINDOW too. This will help on further "black screen issues"
More info: https://developer.nvidia.com/fixing-common-android-lifecycle-issues-games
=> [Android] add Keep screen awake toggle

frontend/device/android/device.lua, platform/android/llapp_main.lua
Related to https://github.com/koreader/koreader/issues/4441
Requires https://github.com/koreader/android-luajit-launcher/pull/89
Fix open files from intent once KOReader is running (android 2.3 to 7.1). Check if file exists before open it.
=> [Android]: Open files from intent

frontend/apps/reader/modules/readerlink.lua
Duplicate with the tap to show footnotes text, reported on https://www.mobileread.com/forums/showthread.php?p=3798627
=> [fix, lang] Swipe to show footnotes in popup setting text

frontend/device/kobo/device.lua, frontend/device/pocketbook/device.lua
Not that we ever use it anywhere on PB, it basically just makes logs prettier ;).
=> Set actual model names on PB devices

frontend/apps/reader/modules/readerhighlight.lua, frontend/ui/elements/common_settings_menu_table.lua
This resolves #4480. Adds `Action on highlight` subsection in `Document>` menu, that allows for using default action when user highlights multiple words.
=> Added choice of default action when highlighting

frontend/ui/data/css_tweaks.lua
More details in the main discussion about widows & orphans in #4484.
Includes https://github.com/koreader/crengine/pull/253 :
- (Upstream) Harfbuzz light: fix rendering of fallback font
- CSS: adds support for 'orphans:' and 'widows:' properties
Adds some Style tweaks related to Widows and orphans.
(Rewording suggestions welcomed)
<kbd><img src="https://user-images.githubusercontent.com/24273478/51347555-b416e680-1aa0-11e9-8e8f-fa1b2e15114f.png" width=400></kbd>
<kbd><img src="https://user-images.githubusercontent.com/24273478/51347723-2ab3e400-1aa1-11e9-862e-ffcd85740008.png" width=400></kbd>
<kbd><img src="https://user-images.githubusercontent.com/24273478/51347617-ed4f5680-1aa0-11e9-9051-3cb3bea0ac98.png" width=400></kbd>
<kbd><img …
=> bump crengine: adds support for 'orphans:' and 'widows:'

frontend/device/input.lua, frontend/device/kindle/device.lua, frontend/ui/otamanager.lua, frontend/ui/widget/container/inputcontainer.lua
* WiFi handling on Kindle (fix #4472)
* Crappy attempt at handling key repeat for the Forma pageturn buttons
* Fix long-standing OTA inconsistencies on Kindle so that OTAManager picks the right binaries (Massive oversight on my part there -_-") (re #4497).
* Use the proper binaries (kindle5 -> kindle) on the K4
* Use the proper binaries (kindlepw2) on every Kindle since the PW2.
=> Assorted minor tweaks

plugins/wallabag.koplugin/main.lua
The Wallabag plugin's callAPI() method was attempting to parse the user supplied
URL for the Wallabag API. Unfortunately, the parse was silently failing since
the variable apiurl did not contain a complete URL. The scheme of the parsed
URL (always nil) was then used to select either http or https (default). The
result being https was always selected, regardless of the user supplied setting.
The parsed URL was switched to the variable server_url instead of apiurl but the
behavior resulting in the default selection of https when parsing fails was left
unchanged.
=> Fixed Wallabag plugin's parsing of wrong API url.

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerlink.lua, frontend/apps/reader/modules/readerstyletweak.lua, frontend/apps/reader/modules/readerwikipedia.lua, frontend/ui/data/css_tweaks.lua, frontend/ui/data/optionsutil.lua, frontend/ui/quickstart.lua, frontend/ui/widget/hyphenationlimits.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua, plugins/goodreads.koplugin/main.lua, plugins/statistics.koplugin/main.lua, plugins/texteditor.koplugin/main.lua, plugins/wallabag.koplugin/main.lua
Thanks to https://github.com/koreader/koreader-misc/pull/24, revert #4132
Adds "Generic web browser paragraph style" style tweak:
<kbd><img src="https://user-images.githubusercontent.com/24273478/51846050-209faa00-2319-11e9-84be-4cb5ad4c301f.png" width=400></kbd>
=> Cleanup multiline translatable strings, adds one paragraph tweak

frontend/device/kobo/device.lua
Move Clara HD to same interface used in the Forma.
Fixes #4523 
The same should apply to other devices without green leds, but needs testing.
=> move Clara HD to frontlight mixer

.ci/check.sh
Follow-up to https://github.com/koreader/koreader/pull/4524
The regex in the Python wasn't actually picking up on that style of writing it at all, because it's not only ugly, but also so counter-intuitive that I overlooked to test for and add support for it.
```
_(
[[
```
It'd be easy to fix up the Python regex a little, and perhaps I will,
but either way it makes more sense to automatically enforce this as a coding standard.
=> [chore, CI] Ensure no whitespace between gettext() call and string

frontend/device/android/device.lua, frontend/device/generic/device.lua, frontend/device/sdl/device.lua, frontend/ui/elements/screen_eink_opt_menu_table.lua
Supported devices:
- Boyue T61 and *some* clones
- Boyue T62 and *some* clones
- Onyx C67
- Energy Sistem (which are in fact Boyue T62 clones). Was tested on a energy pro 4.
Others may work with the same controller too, but are disabled by default.
Requires https://github.com/koreader/koreader-base/pull/798
Requires https://github.com/koreader/android-luajit-launcher/pull/96
Fixes #4373 
Fixes #1613 (supported devices will show the "full refresh rate" option under eink settings. Others won't)
Related #4228 (need to add support for this specific device to work)
=> add basic support for android eink refreshes on some rockchip devices

frontend/ui/elements/screen_dpi_menu_table.lua
Simply don't mention any values when the device DPI isn't known.
A more robust auto-DPI info function could be added to Screen
but I'm not sure if it's worth the trouble.
Fixes https://github.com/koreader/koreader/pull/4389#issuecomment-454552446
=> [fix, lang] More accurate auto-DPI text

frontend/ui/otamanager.lua
Some variants have a space before the number, others don't :/.
=> [Kindle] Fix i.MX 6/7 detection pattern

frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/modules/readerview.lua
Make the existing setting (introduced in #3870) tunable with a menu item.
Also make the Page overlap and Highlight menus (with pdf or cre) items grayed out when disabled, and use a checkbox instead of the strange Enable/Disable.
<kbd>![image](https://user-images.githubusercontent.com/24273478/52126934-f3ad0900-2630-11e9-9368-acefe064985a.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/52126957-032c5200-2631-11e9-976b-b1089cbb5cb5.png)</kbd>
=> Page overlap menu (cre): set nb of overlap lines

Makefile
Includes "set android versionCode and android versionName at buildtime" (<https://github.com/koreader/android-luajit-launcher/pull/106>)
* versionCode uses the number of Git commits, because Google doesn't like values larger than `2100000000`
* versionName uses our existing version string
References #2040.
=> [Android, feat] Set APK version to a sane automated value

frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerlink.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/document/credocument.lua
Follow up on an initial idea and experimentations by @Galunid in https://github.com/koreader/koreader/issues/4496#issuecomment-455821393)
Panning to the bottom right corner (or top left corner) switches to scroll mode and scroll the page forward (resp. backward) 1/3rd of the screen.
One has to pan out of the corner to continue selection.
Panning again to that corner scrolls another 1/3rd of screen.
Page mode and initial page are restored when highlighting or dismissing the highlight dialog, and a little marker is shown at where selection was started so one does not get lost after all that scrolling and restoring.
Closes #4496. Closes #1575. Closes #2071. Related #4533.
=> cre: allow text selection/highlighting across pages

frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/ui/widget/button.lua, frontend/ui/widget/buttontable.lua, frontend/ui/widget/configdialog.lua, frontend/ui/widget/focusmanager.lua, frontend/ui/widget/inputdialog.lua, frontend/ui/widget/inputtext.lua, frontend/ui/widget/menu.lua, frontend/ui/widget/multiinputdialog.lua, frontend/ui/widget/scrollhtmlwidget.lua, frontend/ui/widget/scrolltextwidget.lua, frontend/ui/widget/virtualkeyboard.lua
* Various FocusManager related tweaks to limit its usage to devices with a DPad, and prevent initial button highlights in Dialogs on devices where it makes no sense (i.e., those without a DPad. And even on DPad devices, I'm not even sure how we'd go about making one of those pop up anyway, because no Touch ;)!).
* One mysterious fix to text-only Buttons so that the flash_ui highlight always works, and always honors `FrameContainer`'s pill shape. (Before that, an unhighlight on a text button with a callback that didn't repaint anything [say, the find first/find last buttons in the Reader's search bar when you're already on the first/last match] would do a square black highlight, and a white pill-shaped unhighlight (leaving the black corners visible)).
The workaround makes *absolutely* no …
=> A few graphics fixes after #4541

frontend/ui/elements/screen_eink_opt_menu_table.lua
Follow-up to #4557. Ten-second fixes are never a good idea.
This hides the E Ink settings menu properly again.
=> [fix, Android] hasEinkScreen function in eink_opt_menu_table

Makefile
This greatly speeds up package creation and somewhat speeds up resource bundle extraction.
=> [build, Android] Use faster lzma2 compression

frontend/apps/reader/modules/readerview.lua, frontend/device/kobo/device.lua, frontend/ui/widget/screensaverwidget.lua
* Enforce Dithering in PicDocument
* Flash when closing ScreenSaver
* Mention that Forma rotation events won't work when launched via KSM, because apparently Nickel requests them somehow during boot.
Thanks to @ptrm for quickly noticing all those in #4541 ;).
=> A few minor fixes after #4541

frontend/device/generic/device.lua, frontend/ui/network/manager.lua, spec/unit/network_manager_spec.lua
* On Kobo, try to avoid booting in an inconsistent state ("Wi-Fi connection" checked, because the modules are loaded, but no actual network connection, for whatever reason).
* Don't enable auto_restore_wifi by default.
=> Some Wi-Fi tweaks

kodev
It will introduce some minor noise, but too much stuff is simply not seen otherwise, for example:
*:E
```
02-09 12:45:53.359  2580  2609 E IconLoader: Unexpected null component name or activity info: ComponentInfo{org.koreader.launcher/org.koreader.launcher.MainActivity}, null
```
*:F
```
--------- beginning of system
--------- beginning of main
--------- beginning of crash
02-09 12:47:31.275  4985  5003 F libc    : /home/frans/src/kobo/koreader/base/thirdparty/filemq/build/i686-linux-android-debug/filemq-prefix/src/filemq/src/fmq_client.c:170: fmq_client_set_resync: assertion "self" failed
02-09 12:47:31.275  4985  5003 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 5003 (Thread-37), pid 4985 (reader.launcher)
02-09 12:47:31.512  5085  5085 F DEBUG   : *** *** *** *** …
```
=> [Android] kodev run android: show all errors

frontend/apps/reader/modules/readergesture.lua
c.f., https://www.mobileread.com/forums/showthread.php?t=315023
=> Add Prev/Next page actions to GestureManager

plugins/zsync.koplugin/main.lua
It's more sensible to stick it in the designated data dir on any platform, but the AppImage (and Debian package) can't write in the program's own folders by design.
=> [fix, AppImage] writable zsync outbox location

frontend/device/generic/device.lua
By flashing to a white screen first.
Depends on https://github.com/koreader/koreader-base/pull/814
=> Eliminate ghosting on eInk when showing an image ScreenSaver

frontend/apps/reader/modules/readerbookmark.lua, frontend/apps/reader/modules/readerhighlight.lua, frontend/document/credocument.lua, frontend/ui/widget/button.lua, frontend/ui/widget/buttontable.lua
This allows user to move highlight end/beginning using buttons that appear after pressing on the highlight.
**Screenshot:**
This should be merged after https://github.com/koreader/koreader-base/pull/808
Close #4555. Close #975. Provides a solution for #4134 and https://github.com/koreader/koreader/pull/4267#issuecomment-429926765
=> Add highlight editing buttons

frontend/device/cervantes/device.lua, frontend/device/generic/device.lua, frontend/ui/elements/common_settings_menu_table.lua, frontend/ui/elements/filemanager_menu_order.lua, frontend/ui/elements/mass_storage.lua, frontend/ui/elements/reader_menu_order.lua, platform/cervantes/koreader.sh, platform/common/spinning_zsync
* Move Cervantes 4 to frontlight mixer, like Kobo Forma and Kobo Clara HD.
* Fix waiting spinner (fallback to sleep in devices where usleep is not present)
* USB storage support for KOReader, using a thirdparty tool.
* Allow installation of dicts from the external partition.
I  don't want to spend time building safemode as part of koreader so I made a runtime check. USB storage settings and actions are only displayed on devices if 3rd party tools are recent enough to work with KO.
Once this PR is merged I will update the tool and write specific instructions to enable mass storage on mobileread :+1: 
pinging @avsej for feedback (specially about frontlight/natural light changes),
=> Cervantes tweaks

frontend/apps/reader/modules/readerhighlight.lua, frontend/document/credocument.lua
Includes: https://github.com/koreader/crengine/pull/263 (Closes #4577)
- Footnotes, text selection: don't clip on left and right margins
- Fix underline overflowing last word
- Fix ldomXPointer::getRectEx(), cleanup getSegmentRects() workaround
- Update remaining font metrics from Int8 to Int16
- [CI] Add .codacy.yml https://github.com/koreader/crengine/pull/262
cre.cpp: adds compareXPointers()
Highlight adjusting (#4582): avoid start and end of highlight from crossing each other
=> bump crengine: font, text and highlights fixes

frontend/device/gesturedetector.lua
This morning I finished my thought from about a year ago that I mentioned in passing last night https://github.com/koreader/koreader/pull/4601#issuecomment-464386779
I haven't quite got the GestureDetector end of it sorted out. I'll probably write it up GUI-less for now, other than an on/off switch and a first time use confirmation dialog.
<hr>
The basic idea is that you gain an infinite amount of extra gestures,
although in practice you're probably mostly limited to your 16 basic
two swipe combinations and maybe a few three swipe ones.
=> [feat] GestureDetector: add multiswipes

frontend/apps/reader/modules/readergesture.lua
Follow-up to #4606. This one's a little more hackish and unfinished, but it's got a basic demo configuration interface that works. My point in already opening this PR is to provide context for the other one.
The main problem here lies in the configuration aspect. For the first 16 I could add them manually, and I could procedurally generate a whole lot more, but that doesn't seem terribly user friendly. My thought is to include a set of defaults (e.g., I was thinking something like `down left` for back to previous location), but at the same time a user should also be able to add a gesture like `up down up down` or `up right down left`.
Unimplemented: the first time the user makes a multiswipe gesture they'll be presented with a popup asking if they want to enable multiswipes.
=> [feat] Gesture manager multiswipes

frontend/device/generic/device.lua, frontend/ui/screensaver.lua
When we rotate to show a screensaver, restore original rotation *before* closing the ScreenSaver window.
And ensure closing the ScreenSaver *always* triggers a full update, no matter the settings.
Fix #4621
=> Fix partial refresh when coming out of ScreenSaver in landscape

frontend/apps/reader/modules/readergesture.lua
Pointed out by @poire-z
Also add default previous location action for left, down.
=> [fix] Gesture manager: check multiswipe defaults

frontend/apps/reader/modules/readergesture.lua, frontend/apps/reader/modules/readerzooming.lua
=> [UX] Gesture manager: add paged zoom gestures

frontend/ui/network/manager.lua
Double-checks that the connection was successful, and forcefully kills WiFi if it didn't, to avoid leaving stuff in an inconsistent state.
Should fix #2183
=> Stricter WiFi callback

frontend/device/android/device.lua, frontend/device/sdl/device.lua, frontend/ui/otamanager.lua
The concept is quite simple: stick a file on the OTA server named
something like `koreader-appimage-latest-stable` (by analogy with
`koreader-cervantes-latest-stable.zsync`), which contains nothing
but a filename.
The difference with the zsync update is that the link is then launched
in the user's browser (AppImage) or DownloadManager (Android, not yet
implemented).
=> [feat] Update check

frontend/document/picdocument.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua
Avoids a use-after-free in mupdf.scaleBlitBuffer
Fix koreader/koreader-base#821
Thanks for the hint, @poire-z ;).
=> PicDocument: Pass a copy of image_bb in getCoverPageImage()

frontend/ui/message/streammessagequeue.lua
Depends on https://github.com/koreader/koreader-base/pull/825
=> Leave size_t alone in FFI stuff

frontend/apps/reader/modules/readerzooming.lua
Zooms out until a page can fit in the cache. It's a bit ugly, but better than being stuck. Fixes #3491.
=> [fix] ReaderZooming: work around tiles that are too large

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readergesture.lua, frontend/apps/reader/modules/readermenu.lua, frontend/apps/reader/readerui.lua
=> [feat, UX] Gesture manager: add option - open previous document

frontend/apps/reader/modules/readergesture.lua
=> [feat, UX] Add multiswipe recorder

frontend/apps/reader/modules/readergesture.lua
Silly oversight in https://github.com/koreader/koreader/pull/4644.
=> [fix] ReaderGesture: don't crash without custom gestures

frontend/device/android/device.lua, frontend/ui/otamanager.lua
Requires https://github.com/koreader/android-luajit-launcher/pull/122
- make hasOTAUpdate false for Fdroid.
~~- better name for "koreader-latest.apk".~~
- opening the apk when downloaded, it is a hell, requires special permissions, a file provider on Nougat+, probably breaks our target api, requiring api24+, forcing us to request permissions at runtime instead of install time...
- display a notification when the file is downloaded, because it can't be translated.
=> [wip]: android: (re)enable downloads using full apks

frontend/device/gesturedetector.lua
Reported by @poire-z, cf. https://github.com/koreader/koreader/pull/4640#issuecomment-466544922
<hr>
Apparently it's natural for me to make the second swipe slightly longer than the first, so I never noticed a logic issue. I did notice that it seemed slightly harder to make 4-swipe multiswipes than I expected it to be, but those are not necessarily easy gestures to make.
The problem was that I needed to prevent obviously silly gestures like `west west west east`. In ignoring such duplication, what I accidentally did can be illustrated in the following `west east` multiswipe:
So what you see there is that at point X, the first direction in the multiswipe is detected. Every further movement west was ignored, meaning that the following swipe east could still end up as a relatively western …
=> [fix, UX] GestureDetector: fix multiswipe length detection

frontend/apps/reader/modules/readergesture.lua
Also move multiswipes_enabled setting reading into init(),
to avoid it taking effect only after next restart.
@poire-z I'll apply my changes on top. I hadn't gotten around to that part yet anyway. (Here, you can probably see where I'm going with this.)
```diff
diff --git a/frontend/apps/reader/modules/readergesture.lua b/frontend/apps/reader/modules/readergesture.lua
index b5b47450..8580e908 100644
--- a/frontend/apps/reader/modules/readergesture.lua
+++ b/frontend/apps/reader/modules/readergesture.lua
@@ -23,6 +23,40 @@ local default_gesture = {
multiswipe_east_south_west_north = "full_refresh",
}
+local action_strings = {
+    nothing = _("Nothing"),
+
+    page_jmp_back_10 = _("Back 10 pages"),
+    page_jmp_back_1 = _("Previous page"),
+    page_jmp_fwd_10 = _("Forward 10 pages"),
+ …
```
=> Gesture manager: re-order actions, add Skim option

frontend/apps/reader/modules/readergesture.lua
As suggested by @poire-z (thanks for testing!)
PS Since #4652 it's feature complete as far as what I'd planned at the outset, other than coming up with the defaults.
=> [UX] Gesture manager: show selected action in menu

frontend/apps/reader/modules/readergesture.lua
Otherwise you can get rather unexpected results in paged media and scroll mode.
Workaround suggested by @NiLuJe here: https://github.com/koreader/koreader/pull/4570#discussion_r258693835
=> [fix] Gesture manager: send TapForward event for page forward

frontend/apps/reader/modules/readergesture.lua
Rationale for the default `down, left` gesture: it's pointing at the location for the frontlight toggle.
=> [UX] Gesture manager: add action - show frontlight dialog

frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/modules/readerview.lua, frontend/document/credocument.lua
Includes https://github.com/koreader/crengine/pull/264:
- Fix text selection in some tables
- Add known HTML attributes to avoid cache issues
- Make existing context.AddLine() and pb_flag clearer
cre.cpp https://github.com/koreader/koreader-base/pull/834:
- gotoPos(): allow scrolling after end of document (to avoid not seeing the last line of a document that would be hidden by the footer bar). Will help fixing https://github.com/koreader/koreader/issues/4650
cre scroll mode: fix highlights not shown when small pages
cre scroll mode: fix last line of book hidden by footer (closes #4650) and some other issues related to new document height (when switching font size or layout) never being updated until book reload. Might fix #4328.
=> bump crengine, fix a few cre scroll mode issues

frontend/device/gesturedetector.lua, frontend/ui/timeval.lua, spec/unit/timeval_spec.lua
In principle, any negative subtraction result should be caused by a logical error. Cf. https://github.com/koreader/koreader/pull/4666#discussion_r260772668
@poire-z @NiLuJe Of course it could also be made into a more forgiving logger.warn, or nothing at all if there are legitimate cases where the result could be negative.
=> [fix] TimeVal: add dbg:guard against incorrect subtraction order

frontend/apps/reader/modules/readerpaging.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/device/gesturedetector.lua
This properly fixes the long-standing complaint that swiping to open
the menu could unintentionally trigger some light panning. With the
introduction of multiswipes, this problem has become more noticeable.
=> [fix] GestureDetector: add PANINTERVAL

spec/unit/readerrolling_spec.lua
See https://github.com/koreader/koreader/pull/4692#issuecomment-468689490
=> [fix, spec] readerrolling_spec: rename onDoubleTapForward/Backward to GotoNextChapter/PrevChapter

frontend/device/gesturedetector.lua
Accidentally lost while refactoring. See <https://github.com/koreader/koreader/pull/4640#issuecomment-468788986>.
=> [fix] GestureDetector: only initiate multiswipe with clear N/S/E/W direction

frontend/ui/data/optionsutil.lua
See https://github.com/koreader/koreader/pull/4691#issuecomment-468905263
=> [fix] ConfigMenu cre margins hold action

frontend/ui/widget/buttonprogresswidget.lua, frontend/ui/widget/configdialog.lua
May help with ghosting when closing bottom dialog, and fit better with the other grey toggles.
See https://github.com/koreader/koreader/pull/4691#issuecomment-468646394 and follow ups.
(To be merged or tried before/after release.)
It's actually far better in grey on my GloHD (because of the HW auto-flash, which leaves no ghosting at all):
<kbd>![image](https://user-images.githubusercontent.com/24273478/53664436-c754ce80-3c68-11e9-9251-fcaa5431c721.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/53664448-d045a000-3c68-11e9-98b9-fc776c6d19ac.png)</kbd>
=> ButtonProgressWidget: grey buttons instead of black

frontend/apps/reader/modules/readerdictionary.lua, frontend/apps/reader/modules/readergesture.lua, frontend/apps/reader/modules/readerwikipedia.lua
=> [UX] Gesture manager: add action - show dictionary/Wikipedia

frontend/apps/reader/modules/readergesture.lua
NB The north east and north west arrows are swapped, see https://github.com/koreader/koreader/issues/4707
=> [feat, UX] Gesture manager: add support for diagonal swipes

frontend/apps/reader/modules/readerfooter.lua, spec/unit/readerfooter_spec.lua
=> [fix, UX] ReaderFooter: Don't hide progressbar if it's the only ticked option

frontend/ui/uimanager.lua
When double tap is not disabled (only ensured in ReaderRolling), repeated key hits were slowed down by it. This ensures Input widgets that temporarily overrides it to be disabled are satisfied.
See https://github.com/koreader/koreader/pull/4699#issuecomment-468910319
=> Fix slow keyboard when double tap not disabled

frontend/apps/reader/modules/readergesture.lua, frontend/apps/reader/modules/readersearch.lua
=> [UX] Gesture manager: add action - fulltext search

frontend/apps/filemanager/filemanagermenu.lua, frontend/apps/reader/modules/readermenu.lua
Require is kept in memory, including the modifications made to it by MenuSorter. This can cause trouble when switching between the FileManager and Reader.
Fixes #4703.
=> [fix, UX] Common menu & info menu: switch to dofile

frontend/apps/reader/modules/readergesture.lua, frontend/apps/reader/modules/readerlink.lua
Also show notification when `previous_location` can't go back because the location stack is empty.
Ref https://github.com/koreader/koreader/issues/4687#issuecomment-468956892
(I've put it in the menu, not just after `Back to previous location`, but after all the others that put stuff into this location stack, as some kind of self documentation.)
=> [UX] Gesture manager: add action - clear location history

frontend/apps/reader/modules/readerfont.lua
This little hidden feature (introduced in #3941) needed some update after we made htm.css obsolete and
use epub.css instead.
=> Fix "fonts test HTML document" styles

frontend/device/android/device.lua, frontend/device/generic/device.lua
in Android, where we support both e-ink/normal screens, hasColorScreen depends on hasEinkScreen.
Fixes #4667
=> set panning rate default based on hasEinkScreen

frontend/apps/reader/modules/readergesture.lua
Reference https://github.com/koreader/koreader/issues/4687#issuecomment-469054113
Also:
- add and show some separators in the gestures list
- fix gesture removal, and also remove it from settings
- add missing east west east
- add 6 remaining of the 8 knob 3/4 rotations
- add 3 easy knob full rotation (down + east + west)
These 3/4 or full knob rotations are really practical for stuff you don't want to do by error, but still easy to do when needed. Some may appeal more to left-handed persons.
<kbd>![image](https://user-images.githubusercontent.com/24273478/53731935-93ea8d80-3e7c-11e9-84cc-a71a560eeeda.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/53731941-9c42c880-3e7c-11e9-8f60-c0c165f536f9.png)</kbd>
(I let the "Zoom to fit" ones consecutive)
I did not let …
=> [UX] Gesture manager: add Exit and Restart action and a few gestures

frontend/apps/reader/modules/readergesture.lua
By using the same events used by the bottom menu toggles.
Reference https://github.com/koreader/koreader/issues/4724#issuecomment-469739274. Close #4738.
=> [UX] Gesture manager: fix "Toggle rotation" action

frontend/device/android/device.lua
Including an ugly hack to provide feedback when we open a new file from an intent and the activity is currently stopped (and we cannot blit to window yet).
bumping base to avoid eink updates on framebuffer init.
bumping luajit-launcher to avoid action.VIEW for schemes other than file
=> [android]: misc stuff

frontend/apps/reader/modules/readergesture.lua
As suggested by @poire-z.
https://github.com/koreader/koreader/issues/4727#issuecomment-469668338
I wanted to make the gesture a `W`, but that's a bit too unwieldy. Instead there's the suggestion of a (backward) `W`.
=> [UX] Gesture manager: add action - toggle wifi

frontend/apps/reader/modules/readergesture.lua, frontend/apps/reader/modules/readerstatus.lua
Marking a document as "finished" is important for Wallabag (see, among others, #4737, #4271). Also it's an obvious missing action.
Default to left, up. That keeps with the fullscreen dialog gestures generally go up. Also it was still unassigned.
=> [UX] Gesture manager: add action - book status

frontend/apps/reader/readerui.lua
I added a call to self in ReaderUI:showFileManager() in #4720, breaking this singular reference that wasn't passing self.
Reported on Gitter by @ptrm, see https://gitter.im/koreader/koreader?at=5c81465725e4e24c072f1a00
=> [fix] ReaderUI Pass self in open with cancel callback

frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerview.lua
Also check for boxes in the 2nd page when in 2 page modes. Fix https://github.com/koreader/koreader/issues/772#issuecomment-470106759
(And fix onTapXPointerSavedHighlight(), too quickly cut and pasted from drawXPointerSavedHighlight() recently in #4663).
Bump crengine and cre.cpp to correctly returns rect for the first line of the 2nd page. See https://github.com/koreader/koreader-base/pull/844. Fix https://github.com/koreader/koreader/issues/772#issuecomment-470107420
=> cre: fix highlights in 2-pages mode

frontend/apps/filemanager/filemanagershortcuts.lua, frontend/apps/reader/modules/readergesture.lua, frontend/apps/reader/readerui.lua
Note that `self.ui:onClose()` properly closes open documents. There might be similar pieces of code around that don't do that.
Fixes #4755.
=> Gesture manager: allow folder shortcuts as action in Reader

frontend/apps/filemanager/filemanagershortcuts.lua
The widget system doesn't really do multi-inheritance as well as it should at the moment. Instead of diving into the internals with release upcoming, this commit rewrites the shortcuts to behave better.
Also fixes an older bug in that changing the friendly name didn't actually do anything on first adding a shortcut.
Fixes #4763.
=> [fix] FileManagerShortcuts: prevent interference with general Menu class

frontend/apps/reader/modules/readerrolling.lua
Just copied the code from the next function ReaderRolling:onChangeScreenMode into ReaderRolling:onSetDimensions with some conditionals to not have it before init() is done.
Seems to fix position, footer, toc...
Not super sure about the whole events chain and order, but it seems to work without issue, even on my Kobo when just rotating.
Pinging @NiLuJe - might be there's just a few lines to add around there to fix https://github.com/koreader/koreader/issues/4752#issuecomment-470708895
=> cre: fix position and page number after window resize

frontend/device/pocketbook/device.lua, frontend/ui/network/manager.lua
Partially resolves #4747. Will enable switching Wi-Fi on/off in the menu and getting the network status. However, a new Wi-Fi session lasts ~100 seconds and then terminates automatically, apparently, to save the energy. I believe it can be prolonged by some networking activity. Also it is not shut down if the auto suspension is disabled.
=> PocketBook: implement Wi-Fi connection toggling

frontend/ui/widget/container/framecontainer.lua, frontend/ui/widget/virtualkeyboard.lua
Square keys with a thin border, and changed the flash from an invert to a temporary thick inner border, as discussed on Gitter (àla Kindle).
Depends on https://github.com/koreader/koreader-base/pull/846
=> Slightly prettier virtual keyboard

frontend/apps/reader/modules/readerhighlight.lua
Reuses already existing highlight editing functionality, to enable "AddNote" in highlight menu. This basically does what was asked in #4115 #1095
=> Enable addNote button, by letting it edit highlight

platform/kobo/koreader.sh
KSM is currently emulating a legacy pickel rotation (UR, 0), instead of what both pickel & Nickel do (CCW, 3) on the Forma.
Besides the bad interaction with FBInk described in #4752, I found out that the eInk driver was doing very weird things with A2 updates when UR @ 8bpp...
=> Fix fb rotation on the Forma w/ KSM

frontend/apps/reader/modules/readerhighlight.lua, frontend/apps/reader/modules/readerlink.lua, frontend/apps/reader/modules/readerrolling.lua, frontend/apps/reader/modules/readerview.lua, frontend/document/credocument.lua, frontend/ui/data/creoptions.lua, frontend/ui/data/strings.lua, plugins/coverbrowser.koplugin/bookinfomanager.lua, plugins/coverbrowser.koplugin/covermenu.lua
Fix a few small issues, and introduce a new toggle in the Orientation bottom config menu:
<kbd>![2pagesb](https://user-images.githubusercontent.com/24273478/54278808-bf176000-4593-11e9-8aa0-d09cfb8ce48c.png)</kbd>
Note: 2-pages view was the default for landscape for some users depending on their device resolution and selected dpi, and was not toggable. So I guess a few people will discover this existing nice feature of crengine, that I find really cute.
See individual commit messages for details.
Added fixes for CoverBrowser issues detailed in #4778. Closes #4778.
Also:
bump crengine https://github.com/koreader/crengine/pull/270
- docToWindowPoint(): adds fitToPage parameter
- 2-pages mode: add and fix some functions
- 2-pages mode: tweak middle margin sizing
- Text rendering: fix words …
=> cre landscape view: adds 1 page / 2 pages toggable 
