- frontend/device/kobo/device.lua
It's now generic, and handled in ffi/blitbuffer.lua directly.
Depends on https://github.com/koreader/koreader-base/pull/852
Re: https://github.com/koreader/koreader/pull/4782
> Remove the Kobo-specific 16bpp JIT loopunroll tweak

- frontend/apps/reader/modules/readergesture.lua
- frontend/apps/reader/modules/readerhighlight.lua
It should do what I discussed here: #4727 (comment)
@Frenzie Thanks for the instruction in the other PR ;-)
@poire-z Could you take a look?
> [Gesture manager] Add toggle default highlight action

- frontend/ui/widget/buttonprogresswidget.lua
- frontend/ui/widget/configdialog.lua
Fix small issue in #4789 gray refactoring. See https://github.com/koreader/koreader/pull/4789#issuecomment-473034847
> ConfigDialog: remove gray underline on text items

- frontend/apps/reader/modules/readerrolling.lua
- frontend/ui/data/koptoptions.lua
- frontend/ui/widget/configdialog.lua
This internal ButtonProgressWidget widget was behaving differently from all others (OptionTextItem, OptionIconItem and ToggleSwitch) by duplicating some code from ConfigDialog:onConfigChoose() instead of calling it directly. So, similar to:
https://github.com/koreader/koreader/blob/f637555d93a16d77b78140f3c18a16a2bcdb6d13/frontend/ui/widget/toggleswitch.lua#L191-L208
While making it similar to others, I noticed that onConfigChoose() did a full repaint, which was necessary for some settings to be applied (ie: Contrast) - or may be not, see below, but I don't know what did that then...
On CreDocument, this full repaint may cause some double drawing on config changes (ie: Margins, since #4691, drawing once after margin changes,and then re-positionning to previous xpointer).
So, make the need …
> ConfigDialog: fix ButtonProgressWidget and some refreshes

- frontend/apps/reader/modules/readergesture.lua
- frontend/document/credocument.lua
- plugins/coverbrowser.koplugin/bookinfomanager.lua
- plugins/coverbrowser.koplugin/covermenu.lua
It was doing a full document load to get the cover. It now does the faster "only metadata" load.
Also move the trick of setting a default font in CreDocument, so that all callers of `document:loadDocument(false)` benefit from it.
Prevent crash when no cover image is available (even if the cache says it has one, the file may have been updated and doesn't have it anymore).
Also:
Gesture manager: add actions: Book cover, Book description - as requested in https://github.com/koreader/koreader/issues/4727#issuecomment-472739389
> CoverBrowser: speedup "View full size cover"

- frontend/ui/screensaver.lua
Just switched to use the friendly PathChooser (#4133) instead of FileChooser (which is more like a superclass and shouldn't be used directly).
This screensaver.lua was the only remaining file using FileChooser directly, apart from filemanager.lua, pathchooser.lua and coverbrowser.plugin - where it's ok to use it directly.
Closes #4798 
(Just tested that the file path is saved in settings.reader.lua - not tested that the whole use of that setting value to display that image as screensaver works - no device at hand.)
> Screensaver: fix crash when "Choose screensaver image"

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/reader/modules/readergesture.lua
Code removed from ReaderGesture and put into BookInfo where it belongs, so we can just use Events - I added that a bit too quickly as part of #4792.
Also convert description to plain text to not show HTML tags. Reported at https://github.com/koreader/koreader/issues/4727#issuecomment-473274913
> Gesture manager: fix actions: Book cover, Book description

- frontend/ui/widget/buttonprogresswidget.lua
- frontend/ui/widget/configdialog.lua
Make the default (user set, or KOReader's default) item among the button progress squares shown with a black border. Details in https://github.com/koreader/koreader/pull/4700#issuecomment-473351859 and followups.
<kbd>![image](https://user-images.githubusercontent.com/24273478/54460449-dd36b900-4769-11e9-8074-8f06e3570c47.png)</kbd>
> ConfigDialog ButtonProgress: black border on default item

- .circleci/config.yml
The difference for builds from scratch is negligible, but for rebuilds (i.e., for us hackers & the CI here in front) it should bring a speed improvement.
Automatic fallback to Make when Ninja is not available, or override with `USE_MAKE=1`.
You can (theoretically) choose your own generator with a sensible combination of `CMAKE_FLAGS` and `CMAKE_MAKE_PROGRAM`.
I also added `MAKE_FLAGS` and `NINJA_FLAGS`. That way you can easily pass `MAKE_FLAGS=-n` or `NINJA_FLAGS=-n` for a dry run, for example.
To switch you might have to run something like `make dist-clean USE_MAKE=1`.
Cf. https://github.com/koreader/koreader-base/pull/861, https://github.com/koreader/koreader-base/pull/862 and https://github.com/koreader/virdevenv/pull/34/files
> [build] Bump base to make ninja the default CMake generator when available

- frontend/apps/reader/modules/readergesture.lua
I overlooked this until I noticed it on Transifex today.
See https://github.com/koreader/koreader/pull/4791#discussion_r265546245
Also changing the internal name because for something that's only been in one or two nightlies there's no point in prematurely introducing legacy settings.
> [fix, lang] ReaderGesture: toggle highlight action to cycle

- frontend/ui/widget/imagewidget.lua
- frontend/ui/widget/textboxwidget.lua
Note that in every current call site, alphablitFrom was used with pixmap data straight from MuPDF ;).
(Which means that, technically, alphablitFrom is now dead code).
Depends on https://github.com/koreader/koreader-base/pull/863
re: https://github.com/koreader/koreader/pull/4789#discussion_r266173207
> Properly account for MuPDF feeding us premultiplied alpha

- Makefile
It's generally working as expected at the moment because you're unlikely to have a file named `clean`. But if you were to create a file named `all` or `clean` you could have a pretty difficult time figuring out why nothing's happening anymore.
Pointed out by https://github.com/mrtazz/checkmake which I ran out of sheer curiosity.
> [fix] Makefile: declare all phonies

- frontend/apps/reader/modules/readerlink.lua
- frontend/device/generic/device.lua
- frontend/device/sdl/device.lua
- frontend/ui/otamanager.lua
> [UX] Add Device:openLink() stub for Linux SDL

- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/ui/elements/screen_color_menu_table.lua
Fix #4832, indeed broken by some late change in #4580.
Also refresh screen when toggling (which was no more happening probably since we have more localized refreshes for menu).
> Fix Color rendering toggle not toggable

- frontend/ui/widget/configdialog.lua
Fix possible crash introduced by #4805, when one has set a default for toggles that don't have 'values' in their definitions (possibly only Orientation).
Noticed by @NiLuJe, details in https://github.com/koreader/koreader-base/pull/878#issuecomment-476076439.
> ConfigDialog: fix possible crash

- frontend/apps/reader/modules/readerlink.lua
- frontend/apps/reader/modules/readerrolling.lua
Fix crash when dismissing the popup when the link was detected as "not coherent". See https://github.com/koreader/koreader/issues/4840#issuecomment-476603558. Close #4840.
Also includes:
ReaderRolling: proper refresh when toggling scroll/page mode 
When toggling between scroll and page modes multiple times, _gotoXPointer() could find the xpointer to be already positionned and avoid calling setDirty() (so not enqueuing a whole screen refresh). But the page will be slightly moved to account for the top margin disappearing. We need that whole screen refresh in such cases, so ensure one is enqueued.
Issue probably introduced by the refresh optimisations from #4793.
> Footnote popups: fix crash when used on some links

- frontend/apps/reader/modules/readerfont.lua
- frontend/device/kobo/device.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/rendertext.lua
- frontend/ui/uimanager.lua
- plugins/autosuspend.koplugin/main.lua
* Ignore the accelerometer when sleeping on Kobo (avoids spurious refreshes).
* Allow setting the autosuspend timeout from the UI (Gear > Device)
* Allow toggling the sleepcover from the UI (Gear > Device)
* Enable full granularity in most common font sizes in CRe (depends on https://github.com/koreader/koreader-base/pull/881 for actual effect).
* Don't crash when sizeUtf8Text is called on a nil (#4845)
* Remove viewport on the H2O², as there isn't actually one in effect (#4834)
* Remove viewport on the Aura SE (I'm going to chalk 1-2px on the side to personal preference).
> A few assorted tweaks

- frontend/apps/reader/modules/readergesture.lua
Follow-up to #4815. Pointed out as an easy target [here](https://github.com/koreader/koreader/pull/4815#issuecomment-473990141) by @poire-z. Diagonal two-finger swipes are currently unused.
@ersi Do you have any suggestions for defaults?
PS Migrating up/down isn't self-evident because it does some fancy stuff with gesture length.
https://github.com/koreader/koreader/blob/728bb187fa0758fc9fbe6804a307638a37405fe1/frontend/apps/reader/modules/readerfrontlight.lua#L40-L65
> [UX] Gesture manager: add diagonal two-finger swipes

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/ui/widget/fixedtextwidget.lua
- frontend/ui/widget/textwidget.lua
- platform/android/llapp_main.lua
- platform/kobo/nickel.sh
- reader.lua
- setupkoenv.lua
* Add a toggle to disable the C blitter in the Dev menu (depends on https://github.com/koreader/koreader-base/pull/882) (never shown if the JIT is disabled, grayed out if the C blitter is not installed)
* Fix a few sizeUtf8Text call sites that were doing a nil check in order to account for the new return type.
* Tweak statusbar handling to avoid spurious sizeUtf8Text warnings when it's hidden, and unify its behavior between being hidden via toggle, and hidden on book open (at least when all-at-once is not enabled).
> A few minor fixes after #4847

- frontend/document/credocument.lua
- frontend/ui/widget/footnotewidget.lua
- frontend/ui/widget/imagewidget.lua
Have the code pre-invert some images when in night mode, so they get inverted back to normal by night mode.
This will allow images to be displayed normally in the following contexts:
- images in credocument pages
- images long-pressed in credocument and viewed in ImageViewer
- cover thumbnails in File browser and History
- full size covers when viewed in ImageViewer
- images in Wikipedia lookup results
There is still some issues when the lua blitter is used (Kobo, Kindle), where some images may be wrongly or not inverted, or messed up. No issue seen when the C blitter is used (Android, emulator). Discussed in #2571. Closes #2571.
Includes https://github.com/koreader/crengine/pull/276:
- DrawBuf: allow drawing images inverted (to be used in night mode)
- ldomXPointer::getRect(): adds …
> Night mode: keep some images non-inverted

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readerconfig.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readergesture.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readermenu.lua
- plugins/kobolight.koplugin/main.lua
It was missing some ordering hints to have it always precede taps to change page.
(Somehow noticed only when we reached > 32 gestures registered, which may have introduced some shuffling, while previously the addition order was somehow preserved...)
Details and observations in #4856. Closes #4856.
> Fix tap for top menu occasionally not working

- frontend/apps/reader/modules/readerlink.lua
- frontend/device/android/device.lua
- frontend/device/generic/device.lua
- frontend/device/sdl/device.lua
- plugins/wallabag.koplugin/main.lua
Offers a choice when Wallabag is available.
> [feat, UX] Add external link to Wallabag

- Makefile
- frontend/device/android/device.lua
- platform/android/llapp_main.lua
get android logger tag from application name ("KOReader")
~~debug logging can be enabled using developer options like in other platforms.~~
requires https://github.com/koreader/android-luajit-launcher/pull/136 & bumping that module
> [Android] use the same tag for all logs

- frontend/apps/reader/modules/readergesture.lua
- frontend/apps/reader/modules/readerlink.lua
- frontend/document/koptinterface.lua
- frontend/ui/widget/buttondialogtitle.lua
Follow up to #4863, see discussion there (so, I removed the External link action menu, and as a compensation, I allowed external links on swipe :).
- Removed "Swipe to follow first link on page" menu item and handling code, as it feels not really as practical as "Swipe to follow nearest link".
- Removed recently added "External link action", as we can just always present a popup with the url and the available actions.
- Generic handling of these actions in onGoToExternalLink(), so they are proposed on the Wikipedia lookup popup too.
- Allow external link on PDF documents (previously, only internal links were handled).
- Have "Ignore external links on tap" available on all document types.
- Added "Ignore external links on swipe" (default to true, the current behaviour).
- Added multiswipe …
> Links menu and handling tweaks

- frontend/ui/widget/virtualkeyboard.lua
Other than positioning, this is a feature-complete proof of concept. For the moment this PR is mainly to gather potential feedback before/while tidying it all up.
> [UX] Keyboard character selection popup

- frontend/ui/widget/virtualkeyboard.lua
As suggested by @poire-z in https://github.com/koreader/koreader/pull/4886#discussion_r273569802
This is actually much better than before.
It subtly changes the behavior of every key this way, but I don't think that's a bad thing.
> [UX] VirtualKeyPopup: respond to hold & pan release

- frontend/ui/widget/virtualkeyboard.lua
> [UX] VirtualKeyPopup: close on hold release

- frontend/ui/widget/virtualkeyboard.lua
> [fix] VirtualKeyboard: always fall back to en (like it used to)

- frontend/apps/filemanager/filemanager.lua
- plugins/coverbrowser.koplugin/covermenu.lua
Going with partial ends up being problematic on REAGL devices in a
number of different ways.
On Kindle (at least pre EPDCv2), it's slightly flickery because of the
whitespace and the boldface (I assume), probably combined with the need to make it FULL.
On Kobo, it's slow when anything else tries to queue an update (i.e.,
flashing the chevrons).
Which is a non-issue on the Forma because then it's fast when using
pageturns to navigate, but, still :D.
The obvious downside is we lose the automatic flash after n refresh,
which is potentially annoying on older, non-reagl devices.
It's not really an issue on REAGL devices, especially on EPDCv2.
> Go back to "UI" refreshes in the FM

- frontend/ui/data/keyboardlayouts/keypopup/en_popup.lua
Danish/Norse and IPA close-mid front rounded vowel.
Requested by @gerhaher over in https://github.com/koreader/koreader/pull/4907#issuecomment-482784459
> [UX] Keyboard O popup: add Ø

- frontend/ui/data/keyboardlayouts/en_keyboard.lua
- frontend/ui/data/keyboardlayouts/keypopup/en_popup.lua
Mainly for easy swipe access to `[]{}`.
> [UX] Keyboard popup: add Q and W

- frontend/ui/data/keyboardlayouts/keypopup/en_popup.lua
Split sigma into upper and lowercase to make room for esh.
> [UX] Keyboard popup: minor changes to S

- frontend/device/generic/powerd.lua
- frontend/device/kobo/powerd.lua
> Some more FL fixes

- frontend/apps/reader/readerui.lua
Same as https://github.com/koreader/koreader/pull/2956.
Fixes https://github.com/koreader/koreader/issues/4928.
> [chore] Show FileManager in case of showReaderCoroutine failure

- .gitignore
This is extremely minor, bu the following build/test products end up spamming git status:
- foo.sdr and foofoo.sdr
- koreader-kindle-arm-kindle5-linux-gnueabi*
- koreader-emulator-x86_64-unknown-linux-gnu*,
so I'm adding these to `.gitignore`.
> Add more build products to gitignore list

- frontend/device/android/device.lua
- platform/android/llapp_main.lua
Keep debug builds as they are (verbose logging everything from start, ignoring settings.lua)
As an example (using `adb logcat KOReader:V *:S`)
[debug.log](https://github.com/koreader/koreader/files/3090832/debug.log)
[release.log](https://github.com/koreader/koreader/files/3090833/release.log)
> [Android]: don't log verbose messages on release builds, unless specified in settings.lua.

- frontend/apps/reader/modules/readergesture.lua
- frontend/apps/reader/modules/readerhighlight.lua
This allows user to switch between "invert", "lighten", "underline" highlight styles using gestures, discussed https://github.com/koreader/koreader/issues/1095#issuecomment-481834569
closes #4896
> [GestureManager] Implement action to change highlight style using gesture manager

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readertypeset.lua
- frontend/document/credocument.lua
- frontend/ui/data/creoptions.lua
- frontend/ui/data/strings.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/imagewidget.lua
- frontend/util.lua
- reader.lua
Requires https://github.com/koreader/koreader-base/pull/888
Fix https://github.com/koreader/koreader/issues/1833
> Allow toggling CRe's new dithering & scaling

- plugins/send2ebook.koplugin/main.lua
Also fix weird indentation.
Reported on the forum: https://www.mobileread.com/forums/showthread.php?p=3833021#post3833021
> [fix] plugins/send2ebook: crash on setting download dir

- frontend/device/kobo/powerd.lua
on if it's off.
Because, on the KA1, since setting the warmth *has* to set the
brightness, it could ;).
Patch only actually needed on Kobo, as all Cervantes devices with warmth
support have a mixer, which mean they *can* set the warmth without
affecting the brightness ;).
> Make sure the AutoWarmth feature will never try to turn the light back

- README.md
The Ubuntu Touch build has been broken for three years and since I have no way to test I can't fix it.
References #4904.
> README: remove Ubuntu Touch and add screenshot

- spec/unit/readerview_spec.lua
It's not clear to me where the value is set as expected when running all tests linearly because it doesn't seem to be ReaderFooter.
> [fix, spec] enable ReaderView tests

- .circleci/config.yml
It should be a path to a directory, not a file.
https://circleci.com/docs/2.0/configuration-reference/#store_test_results
> Path (absolute, or relative to your working_directory) to directory containing subdirectories of JUnit XML or Cucumber JSON test metadata files
Perhaps the file needs to be named results.xml. We'll see.
> [CI] CircleCI: save test results

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
- plugins/newsdownloader.koplugin/feed_config.lua
- plugins/newsdownloader.koplugin/main.lua
> NewsDownloader: epub with images

- frontend/apps/reader/modules/readertypeset.lua
- frontend/ui/data/creoptions.lua
- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/container/inputcontainer.lua
- frontend/ui/widget/toggleswitch.lua
So we can immediately see how's the bottom margin:
<kbd>![margins_tap_dismiss](https://user-images.githubusercontent.com/24273478/57060154-aa646800-6cb8-11e9-8922-6a107d68b324.gif)</kbd>
(As proposed in https://github.com/koreader/koreader/pull/4945#issuecomment-488571117)
> CRe margins: hide bottom menu on change

- frontend/device/kobo/powerd.lua
Possibly helps with some more edge cases related to interaction with
autowarmth & the KA1...
re: #4925
> [Kobo] Sync powerd.fl brightness with powerd when toggling the FL

- plugins/coverbrowser.koplugin/bookinfomanager.lua
"succesfully" => "successfully"
> Info message typo fix

- plugins/newsdownloader.koplugin/main.lua
Fixes #5005
Results from re-running "Download news" should be as before, except when the
article content has changed between runs, but the title has not and an updated
date has not been given in the feed. User can force it to re-download an
article by manually deleting the file then running "Download news".
> NewsDownloader: Skip re-downloading files which already exist

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
The server might redirect to only path, in this case the scheme and host
should be taken from original URL
> newsdownloader: rebuild URL on redirect to bare path

- frontend/apps/reader/modules/readerrolling.lua
- spec/unit/readertoc_spec.lua
Bump crengine:
- Ensure text decoration (underline) is continued over word gaps https://github.com/koreader/crengine/pull/286
- Invalidate TOC page numbers on rendering change (details in #4972)
- Ensure reproducible cache files when same rendering settings (details in #4972)
- Use utf8proc for string uppercase/lowercase/capitalize https://github.com/koreader/crengine/pull/287
- LVBlockWriteStream: workaround to exclude fatal error
Bump base https://github.com/koreader/koreader-base/pull/915
Thirdparty: adds utf8proc 2.3.0 (libutf8proc.so.2)
For use by crengine, for now mostly for more complete and accurate text-transform: uppercase/lowercase/capitalize.
Also revert test tweak (in #4972 / 27ddd6f) to workaround an issue with cre cache that should be solved by this crengine bump.
Also: …
> Bump crengine: cache and text fixes, use utf8proc

- frontend/document/pdfdocument.lua
Fixes <https://github.com/koreader/koreader/issues/5024>.
Highlighting will still work with the .sdr metadata.
> [fix] Don't try to save highlight into non-PDF document

- frontend/apps/reader/modules/readerlink.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/opdsbrowser.lua
- frontend/util.lua
- plugins/newsdownloader.koplugin/main.lua
- plugins/wallabag.koplugin/main.lua
Fixes https://github.com/koreader/koreader/issues/5025
The OPDS browser was doing some fancier stuff in a way that should be abstracted away in util (because it applies anywhere files will be saved):
https://github.com/koreader/koreader/blob/eace8d25c1cbf9bd13e98220098494e8fb63c18f/frontend/ui/widget/opdsbrowser.lua#L482-L491
> [fix, chore] Abstract filename logic in util.getSafeFilename()

- frontend/ui/data/css_tweaks.lua
- frontend/ui/widget/footnotewidget.lua
- Popup footnotes: workaround strange behaviour of MuPDF which is adding some unwanted margin above elements with an `id=` attribute. See https://github.com/koreader/koreader/issues/5015#issuecomment-492221431
- In-page footnotes: also remove any left and right margin, to keep footnotes aligned with the main text. See https://github.com/koreader/koreader/issues/5015#issuecomment-492184113
Also add 2 classnames (witnessed in quite a few recent french books) to the list of classic classnames.
Also bump crengine for:
- CSS: fix parsing of multi classnames and attributes selectors https://github.com/koreader/crengine/pull/288
> cre: fix 2 footnotes issues

- frontend/device/kobo/device.lua
Officially, the bezel should only cover the bottom 10 pixels ;).
(The Aura was officially advertised as having a 758x1014 screen).
> Tweak the Aura viewport

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
- plugins/newsdownloader.koplugin/main.lua
Split the html page download out of createEpub, so that createFromDescription
can pass in its own html for epub packaging (with optional image download).
Still pass in a url, so that relative urls can be made absolute.
Related to #3172.
> NewsDownloader: Allow including images when using text from feed

- plugins/newsdownloader.koplugin/main.lua
Atom feed content is found under the xml tag, 'content', not 'context'.
The content field is a actually a table, with the text/html at [1].
With this, I can finally get a decent changelog from https://github.com/koreader/koreader/releases.atom :-)
> NewsDownloader: Fix createFromDescription for atom feeds

- spec/unit/readerrolling_spec.lua
Includes:
- Freetype kerning: fix possible unstable rendering https://github.com/koreader/crengine/pull/291
- Hyphenation: fix one-letter patterns, update French.pattern https://github.com/koreader/crengine/pull/290 Thanks @cramoisi 
- Hyphenation: update French.pattern https://github.com/koreader/crengine/pull/292
- epub.css: add style for empty-line (used on text files) https://github.com/koreader/crengine/pull/293
Closes #5042
> bump crengine: hyphenation, kerning and epub.css fixes

- frontend/ui/widget/inputtext.lua
Dear KOReader developers,
I want to ask you to consider below pull request about improving `InputText` widget behavior.
Because `addChars()` function did not consider if hint text is displayed or not, it could ignore the character input if the carat is not at the beginning of the hint text. If an user uses touchscreen device, he or she can place a carat at the middle of a text.
-- Before change
As in the example above, if I placed the carat in the middle of a hint text and clicked a key, that key was just ignored and the carat is moved to the beginning of text. Subsequent key click was processed because the carat is at the beginning of text.
I think that there are at least two solutions:
❌ Make the widget tap handler function just moves the carat to the beginning of text if the widget is …
> Fix inconvenient InputText behavior with hint text and devices having touchscreen

- plugins/perceptionexpander.koplugin/main.lua
Dear KOReader developers,
I want to ask you to pull changes for fixing "Perception expander" plugin behaviors:
* Landscape status not detected when reloading document
It seems that when the `(Plugin):onInit()` function is being called, 'landscape' state of a screen seems not applied. Hence, the lines drawn by plugin are placed for the portrait state. 
-- Before fix
To fix this, I added a hack that checks if screen rotation was changed but not yet handled in the plugin from `onUpdate` function.
-- After fix
* Settings are mostly not applied immediately; have to flip page to see effects
After clicking `[Apply]` button of the plugin settings, configs are updated but actual dimensions of lines drawn by this plugin were not updated immediately in most time. To see if settings changed are …
> Change perception expander plugin behaviors

- frontend/ui/data/keyboardlayouts/ko_KR_helper.lua
- frontend/ui/data/keyboardlayouts/ko_KR_keyboard.lua
- frontend/ui/widget/virtualkeyboard.lua
Dear KOReader developers,
I want to add Korean keyboard (in 2-beolsik; most popular and somewhat simple to implement) that I implemented, regarding many references on the web, to the KOReader.
Here is the screenshot of the keyboard:
and here is some working example:
Because Korean characters, called `Hangul`, have to be typed with combinations of some `consonnants` and `vowels`, hence Korean keyboard requires some automata code to do those combinations. It seems that keyboards implemented in KOReader did not required automata things, I did not found handler functions required for processing events with automata code.
Therefore, I made those changes that are not matching your code quality standard:
* I don't know adequete location, so I placed automata code in the same directory of …
> Add Korean keyboard (2-beolsik)

- frontend/device/kobo/device.lua
Bypass init, like Nickel does.
Otherwise, some devices either deadlock or panic.
> Fix shutdown action on Kobo

- frontend/device/generic/device.lua
- frontend/device/kindle/device.lua
- frontend/device/kindle/powerd.lua
- frontend/ui/network/manager.lua
By having viable fallbacks when we can't open a Lua lipc handle, and by dealing with really really old busybox builds.
Fix #5058
> Minor networking fixes on legacy Kindles

- frontend/apps/reader/modules/readerstatus.lua
Fixes #5060.
Cf. https://github.com/koreader/koreader/blob/89e002f2367079cefd445e1719c1715dccedd65b/frontend/apps/reader/modules/readermenu.lua#L42-L50 and https://github.com/koreader/koreader/blob/89e002f2367079cefd445e1719c1715dccedd65b/frontend/apps/reader/readerui.lua#L711-L718
> [fix] End of document - go to file browser: swap openFileBrowser() close/open order

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagershortcuts.lua
Adds a new paste action to folder shortcuts.
Fixes #5046.
> Paste to shortcuts

- plugins/wallabag.koplugin/main.lua
See https://github.com/koreader/koreader/issues/5060#issuecomment-499416617
> [fix, plugins] Wallabag: close document on go to folder

- plugins/newsdownloader.koplugin/main.lua
Same as https://github.com/koreader/koreader/pull/5063. Also see https://github.com/koreader/koreader/issues/5060#issuecomment-499416617.
> [fix, plugins] NewsDownloader: close document on go to folder

- frontend/ui/widget/opdsbrowser.lua
Regression introduced in <https://github.com/koreader/koreader/pull/4249>.
Fixes <https://github.com/koreader/koreader/issues/5091>.
> [fix] OPDS crash with fewer than 4 servers

- frontend/ui/widget/container/movablecontainer.lua
The MovableContainer's contained widget may not have integer position/dimen (which should probably be fixed in those that don't ensure that), and our maths could eventually make them even more shifted by fractional parts.
In the end, when closing the widget, the refresh code may miss painting/cleaning 1px and leave a border of the widget on the screen.
Eg, on a sufficiently large resolution, moving this InfoMessage to the screen right border, then back:
<kbd>![image](https://user-images.githubusercontent.com/24273478/60129617-b7bc4100-9795-11e9-8d24-f2218b0e2803.png)</kbd>
On tap elsewhere to close it:
<kbd>![image](https://user-images.githubusercontent.com/24273478/60129722-f05c1a80-9795-11e9-93f6-8b9bf0f1fc11.png)</kbd>
So, @NiLuJe , don't remove the following as long as we haven't make …
> MovableContainer: avoid refresh glitches on close

- frontend/ui/widget/bookstatuswidget.lua
- frontend/ui/widget/button.lua
- frontend/ui/widget/buttontable.lua
- frontend/util.lua
- plugins/coverbrowser.koplugin/covermenu.lua
* Make the cover thumbnail respect the cover's AR in the widget
* Add a "Mark as read/unread" button in the FM's longpress menu.
> Some BookStatus QoL tweaks

- frontend/device/generic/device.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/network/manager.lua
- frontend/ui/uimanager.lua
- plugins/coverbrowser.koplugin/covermenu.lua
For some mysterious reason, I have a duplicate default gateway on my
Forma, one with no metrics, and a proper one.
This ensures we pick the proper one.
I'm fairly sure this is temporary insanity on the part of my device,
but, still, it can't hurt.
`route -n`:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG    0      0        0 eth0
0.0.0.0         192.168.0.1     0.0.0.0         UG    208    0        0 eth0
192.168.0.0     0.0.0.0         255.255.255.0   U     208    0        0 eth0
```
`ip r`:
```
default via 192.168.0.1 dev eth0
default via 192.168.0.1 dev eth0  metric 208
192.168.0.0/24 dev eth0  src 192.168.0.49  metric 208
```
> Make sure we only pass a single IP to ping

- .ci/helper_shellchecks.sh
Requires https://github.com/koreader/android-luajit-launcher/pull/149 and https://github.com/koreader/koreader-base/pull/927
In order to build we need to add the valid sdk and ndk paths into platform/android/luajit-launcher/local.properties
I'm using:
```
ndk.dir=/home/pazos/Escritorio/koreader/base/toolchain/android-ndk-r15c
sdk.dir=/home/pazos/Escritorio/koreader/base/toolchain/android-sdk-linux
```
> [android]: bump sdk, switch to gradle, add support for runtime permissions, fix some memleaks.

- kodev
bump base, bump luajit-launcher and adapt kodev to use the new ANDROID_NDK_HOME path.
Related to https://github.com/koreader/koreader/pull/5096
> update ndk/sdk paths on demand, bump sdk tools..

- frontend/apps/reader/modules/readergesture.lua
- frontend/device/generic/device.lua
- frontend/device/input.lua
- frontend/device/kobo/device.lua
- frontend/ui/elements/screen_toggle_gsensor.lua
- frontend/ui/uimanager.lua
Make sure it's off when we want it off, and on when we want it on.
The older racy behavior could lead to unexpected results after a quick succession of suspend/resume events.
> More robust Gyro toggle

- frontend/apps/reader/modules/readerstatus.lua
- frontend/ui/elements/common_settings_menu_table.lua
Close #5050 
Add option to "delete" just read book to "End of document action".
Before:
After:
> Delete book after reading

- frontend/device/android/device.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/screen_android.lua
- platform/android/llapp_main.lua
Work in progress: 
Things work but the new viewport is not changed without reloading current app (I mean the reader or the file manager). 
Move the old toggleFullscreen for apis 14-16 to device/android/device.lua?
requires https://github.com/koreader/android-luajit-launcher/pull/148
fixes #4794
> fullscreen toggle for Jelly Bean devices

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/device/android/device.lua
- frontend/device/android/dictionaries.lua
- frontend/device/generic/device.lua
Added support for Aard2, Alpus, Colordict, Fora, Goldendict, Kiwix, Mdict and Quickdic.
Goldendict Pro is untested. The Free version works fine.
All credits to @poire-z, who did most of the job in https://github.com/koreader/koreader/issues/2333#issuecomment-502010311
**how to add support for new dictionary apps ?**
1. find a target dict app (already installed, configured and ready to work)
2. find its package name (using an app like "Package Names Viewer")
3. try generic actions in this order: picker-share -> picker-send -> picker-text.
4. hopefully the application is available as an option to open the query.
5. try again removing the "picker-", It should open your dictionary without questions.
You might need to look at the app AndroidManifest.xml and find the kind of intents that the …
> android: add support for 3rd party dictionary apps

- Makefile
- platform/kindle/extensions/koreader/bin/koreader-ext.sh
- platform/kindle/libkohelper.sh
Otherwise, using the KUAL extension can get a bit tricky if KOReader has
been removed.
(Same logic as in libkh5, except we prefer our own build, and there's a
shitty eips fallback in case all hell broke loose and even libkh is
gone).
That said, if libkh is gone on a FW 5.x, you're in serious trouble :D.
Re #5110
> Try harder to find an FBInk binary on Kindle

- .luacheckrc
- plugins/statistics.koplugin/main.lua
After fresh KOReader installation we don't need information "Conversion complited." like that:
>  [statistics] Remove conversion message on new installations 

- frontend/ui/screensaver.lua
This is one feature I miss from the stock Kobo firmware, the ability to see the percentage read on the screen while the device is asleep. I know I can see the book status but it's not quite the same.
I thought a good way to do it would be to create escape sequences that the user can put in their screensaver text. I've modified screensaver.lua to use %p for percentage read. While I was at it I added %c and %t for current and total pages respectively, and %dt for document title.
Attached is a picture of the screen of my Kobo Aura One sleeping...
> Add percentage read (and other book information) to sleep message

- frontend/apps/reader/modules/readertoc.lua
- frontend/ui/data/css_tweaks.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/textwidget.lua
In the TOC, baseline align chapter name and page number, which makes it a bit prettier.
Before:
<kbd>![toc_before](https://user-images.githubusercontent.com/24273478/61561380-2330c000-aa6f-11e9-9bdd-b10f91b4622c.png)</kbd>
After:
<kbd>![toc_after](https://user-images.githubusercontent.com/24273478/61561389-275cdd80-aa6f-11e9-96b4-c85939fee581.png)</kbd>
Add a few style tweaks to ignore all horizontal margins _only_ or all vertical margins _only_ instead of _all_ margins - and the same for paddings for books that wrongly use paddings for that effect.
> TOC: baseline align chapter name and page number, adds some style tweaks

- frontend/device/kindle/device.lua
- spec/unit/device_spec.lua
We were (currently) unaffected because we don't support the K1.
Still, this should be slightly more robust.
(c.f., https://github.com/NiLuJe/FBInk/commit/8a1161734b3f5b4461247af461d26987f6f1632e)
> Fix Kindle model detection in some corner-cases

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/readerui.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/widget/filechooser.lua
New option to show all files (also not supported by KOReader) in file manager. Default this option is disabled.
Close: #3578 
Screenshots:
> File manager - adding option to view unsupported files

- frontend/ui/data/css_tweaks.lua
Pluralizing paddings like this is a bit unidiomatic, and that "all" seems a bit redundant.
Cf. <https://github.com/koreader/koreader/pull/5127>.
> [lang] Minor CSS tweaks stylistic improvements

- frontend/apps/cloudstorage/dropbox.lua
- frontend/apps/cloudstorage/dropboxapi.lua
- frontend/apps/cloudstorage/ftp.lua
- frontend/apps/cloudstorage/ftpapi.lua
- frontend/apps/cloudstorage/webdav.lua
- frontend/apps/cloudstorage/webdavapi.lua
Option to show all files in cloudstorage also not supported by KOReader. We can also download any file.
To show all files in CS we need to enable option `Show unsupported files` in file manager (introducing in #5129)
Close: #5006
> Cloudstorage - Adding option to view unsupported files

- frontend/apps/reader/modules/readergesture.lua
- frontend/device/gesturedetector.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/widget/spinwidget.lua
Discussion: #4842 
Close: #4842 
Screenshots:
> Gesture intervals configurable

- frontend/apps/reader/modules/readergesture.lua
Follow-up to https://github.com/koreader/koreader/pull/5138
> [fix] Typo miliseconds → milliseconds

- frontend/device/android/device.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/elements/screen_android.lua
requires https://github.com/koreader/android-luajit-launcher/pull/160
fixes #4604
> android: add support for different screen timeout setups

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/widget/menu.lua
Ref: #4757
This PR add option to changing the font size of items in menu widget (filemanger in classic mode, TOC) in single line mode.
Close: #4757
> Set font size for menu items

- plugins/wallabag.koplugin/main.lua
Adds a new client setting representing the number of articles that will be fetched from the Wallabag server for each synchronization.
Previously, Wallabag only returns 30 articles at a time by default. With this setting, koreader will be able to download a custom number of articles from the Wallabag server for each synchronization.
If the setting was not present in the user settings, the default value (30) will be used.
> feat: customizable articles count per sync

- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/device/sdl/device.lua
Close: #4997 
This PR add support arrow key and mouse scroll wheel for next/previous page.
- Document in page mode:
PageDown, Arrow down, Arrow right - go to next page
PageUp, Arrow up, arrow left - go to prev page
Mouse scroll wheel down - go to next page
Mouse scroll wheel up - go to prev page
- Document in scroll mode:
PageDown, Arrow right - go to next page
PageUp, Arrow, arrow left - go to prev page
Arrow down - scroll document down
Arrow up - scroll document up
Mouse scroll wheel down - scroll document down
Mouse scroll wheel up - scroll document up
> [sdl] Add support arrow key for next/prev page

- plugins/wallabag.koplugin/main.lua
Adds the option to remotely archive finished Wallabag articles instead of permanently deleting them.
Previous versions permanently deleted the remote finished articles. This behavior is preserved by default. If the archiving setting is used, then the finished articles won't be deleted but remotely archived.
The setting is available in the `Settings` menu as `Archive instead of delete articles`.
Perhaps it would be better (if possible) to regroup all the deletion options in a settings dialog? Also, all the options regarding deletion and archiving might get confusing to the user. I thought about rewriting the labels but how would that impact translation?
> feat(wallabag): archiving instead of deleting articles

- frontend/ui/otamanager.lua
Adding the option to restart KOReader after update.
Close: #5144
Before:
After:
> Restart KOReader after update

- frontend/device/generic/device.lua
- frontend/device/kobo/device.lua
- frontend/ui/network/manager.lua
- platform/kobo/nickel.sh
- platform/kobo/restore-wifi-async.sh
* Attempt to make it send a NetworkConnected event, eventually (may help w/ #5109)
* Made sure it wouldn't interfere with nickel startup in case it's still running when we exit (which reliably happens if we crash on startup)
* Tweaked the Kobo variant to check if wpa_supplicant managed to connect before attempting to acquire an IP, and to tear down the modules if it didn't ("inspired" from @shermp's https://github.com/shermp/Kobo-UNCaGED/pull/21 ;)).
> Minor auto_restore_wifi tweaks

- .gitmodules
https://github.com/Sturmflut/ubuntu-touch-sdl-template/ disappeared so I uploaded my copy to https://github.com/koreader/ubuntu-touch-sdl-template
> [fix] Switch ubuntu-touch-sdl-template to our own mirror

- frontend/device/android/device.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
Related to #5136 
Requires https://github.com/koreader/koreader-base/pull/938
Requires https://github.com/koreader/android-luajit-launcher/pull/162
Fixes #1760 
Fixes #3374
> android: add an option to ignore volume keys or use them to turn pages

- frontend/apps/filemanager/filemanager.lua
Make the Home button fallback to sane values in case no custom home directory is set (re #5154 ).
And if we're already home, make it jump to the first page.
(The QuickStart Guide properly introduces the long-press as the way to set defaults, so I'm not too torn up about mostly getting rid of that bit of QoL cuteness that may actually mean people wouldn't remember that long-presses are awesome in KOReader).
> Go Big or Go Home!

- frontend/device/android/event_map.lua
- frontend/device/input.lua
Requires https://github.com/koreader/koreader-base/pull/939
Requires https://github.com/koreader/android-luajit-launcher/pull/163
Fixes #3978 
Right now the behaviour is hardcoded to AKEYCODE_CAMERA but can be changed easily by generating a new event_map.
To test the behaviour, since both the emulator and my phone lack the proper hardware key, I'm using `adb shell input keyevent 27`
A toast will be shown to give feedback to the user about the new touchscreen state (enabled/disabled).
@Frenzie @NiLuJe @poire-z @robert00s Please feel free to suggest better ways of doing this (including base and luajit-launcher stuff), because my brain is starting to melt-down.
> Android: ignore touchscreen by user request (using a hardware key)

- frontend/apps/cloudstorage/webdavapi.lua
Using the cloud storage feature to connect to a NextCloud server (using WebDAV protocol) results in "/" for every folder name in the list, and "Empty Folder" messages when trying to access any folder.
The cause is a trailing slash in the response from the NextCloud server that needs to be handled if present.
> fix "empty folder" when accessing nextcloud webdav

- frontend/ui/elements/screen_dpi_menu_table.lua
- frontend/ui/widget/touchmenu.lua
Settings -> Screen -> Screen DPI
When custom DPI is not set we see ugly information with %1:
This PR should fix it and replace input widget with spin widget.
Before:
After:
> Fix: set custom screen DPI

- frontend/ui/widget/touchmenu.lua
See: #5155 
Close: #5155 
I chose option 1 (red rectangle is touch zone).
Before:
After:
> Extend the touch zone for up button in touch menu.

- frontend/ui/widget/button.lua
Close: #5174 
Hold gesture was eaten by a hidden `return button`.
https://github.com/koreader/koreader/blob/2dd29f6ab14f30c0ccdefa63d18fbf0281dd909a/frontend/ui/widget/menu.lua#L719-L727
> Fix: hold left corner doesn't work properly

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/ui/trapper.lua
- frontend/ui/widget/trapwidget.lua
- frontend/ui/wikipedia.lua
They should be now interruptible when fuzzy search is disabled, and on Android.
See https://github.com/koreader/koreader/issues/5151 and https://github.com/koreader/koreader/issues/3588#issuecomment-357467866.
Closes #5151. 
(Tested on my Android 6 phone, hope they work as well on other android versions, with hopefully correct shells.)
Also increase the timeout when downloading Wikipedia HTML, needed when making an EPUB out of https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD).
> Dict lookups: have them always interruptible

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/modules/readergesture.lua
- frontend/ui/widget/menu.lua
Add top/bottom edge swipe gesture like in #5156
> Add horizontal edge gestures

- frontend/apps/reader/modules/readerview.lua
- frontend/apps/reader/modules/readerzooming.lua
- spec/unit/readerlink_spec.lua
- spec/unit/readerview_spec.lua
The alternative is to disable scroll mode by default, but the default combination of fit page + scroll is a bit odd.
Fixes #5166.
> Change default zoom mode & add warning message for fit page + scroll

- plugins/zsync.koplugin/main.lua
Patch similar to PR #3086.
Same problem #2638 when tap Subscribe to book share.
"Zsync" -> "Subscribe to book share" crashes koreader if not connected to wifi
After this fix when koreader is offline after "Zsync" -> "Subscribe to book share" we are asked to enable wifi.
> Fix: Zsync -> Subscribe to book share crashes

- frontend/apps/reader/modules/readerfont.lua
- frontend/apps/reader/modules/readergesture.lua
* Add spread/pinch gesture to gesture manager
ability to disable: 
https://www.mobileread.com/forums/showthread.php?t=321818
https://github.com/koreader/koreader/pull/4815#issuecomment-478462416
* Add increase/decrease font size action gesture
https://github.com/koreader/koreader/issues/4727#issuecomment-475950484
> Gesture spread pinch

- frontend/apps/reader/modules/readergesture.lua
- frontend/apps/reader/modules/readerlink.lua
See: #5186 
> Horizontal left edge gesture gets in conflict with the other left swipe. I have 'Swipe to follow nearest link' enabled, so every time there is a link on the page my bottom/top left edge swipe follows that link instead.
> Fix: conflict horizontal edge gesture with link swipe

- frontend/apps/reader/modules/readerfooter.lua
Close #5044 
Option to align status bar without progress bar.
> Status bar alignment

- kodev
- platform/debian/koreader.sh
Although the current hard-coded paths work on debian, they may fail on many other distros. Other distros may pack koreader based on the released deb file. I personally have problem using current script on nixos, as it does not use the paths `/bin/bash` and `/usr/lib/`.
> avoid hard-coded path

- frontend/device/kobo/device.lua
Prevents a crash when the WIFI_MODULE environment variable is not
defined.
> Add missing parentheses

- frontend/ui/elements/common_info_menu_table.lua
- frontend/ui/widget/infomessage.lua
It ends up with a black background otherwise.
(Old regression that dates back to my alpha shenanigans a few months
ago)
> Honor the alpha channel in our icon for the About popup

- frontend/device/kobo/device.lua
Don't fork for lsmod + grep, we can perfectly well parse /proc/modules
ourselves ;).
c.f., https://github.com/koreader/koreader/pull/5203#issuecomment-521277628
> Simplify isWifiOn on Kobo

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readergesture.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/device/android/device.lua
- frontend/device/cervantes/device.lua
- frontend/device/generic/device.lua
- frontend/device/kobo/device.lua
- frontend/device/sony-prstux/device.lua
- frontend/ui/elements/common_info_menu_table.lua
Ref: #5021 
Two new gesture:
+ Power off
+ Reboot the device
> Add gesture - poweroff and restart device

- frontend/device/android/device.lua
- do not request write settings permission at launch
- do not uncompress assets if we don't have read and write permissions on external storage.
- do not propagate mute key events to the frontend
Requires https://github.com/koreader/android-luajit-launcher/pull/169
Related to #5205
Fixes #5206
> android: some runtime permissions / keys fixes.

- frontend/device/pocketbook/device.lua
Similar to #4474
PocketBook Touch Lux 3 (626) seems to have a new codename with the latest firmware (mine is FR626.5.14.1228 released on 20170718_143341)
> PocketBook 626 new codename

- frontend/apps/reader/modules/readerfooter.lua
- frontend/util.lua
- spec/unit/readerfooter_spec.lua
- spec/unit/util_spec.lua
Base on #4594
Close: #4854 
Changes include:
+ adding unicode characters to menu and footer
+ move alignment to settings submenu
+ new text footer separator
+ progress percentage format (#4854)
+ date in 12/24 format
+ time format in 1h30' as option
Edit - new screenshots
> Some footer tweaks

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/document/credocument.lua
Bump crengine https://github.com/koreader/crengine/pull/305 :
- View HTML: option to show text unicode codepoints
- Fix attribute parsing: decode &-encoded chars
- Text: allow wrap after more unicode spaces and hyphen (Closes #5191)
- Fix: no left hanging when hanging punctuation disabled
- lvtextfm.cpp: more comments, some formatting cleanup
- Optimize background image drawing
- CSS: fix background-image file path resolution
Bump harfbuzz to 2.6.0 https://github.com/koreader/koreader-base/pull/917
Bump luasec to 0.8.1 https://github.com/koreader/koreader-base/pull/949
cre.cpp: https://github.com/koreader/koreader-base/pull/950
Adds `setBackgroundImage()` proxy function to crengine facility to set background textures (this is unrelated to the background-image CSS fixes).
No frontend code …
> bump crengine and others, adds HTML extended debug view

- frontend/apps/reader/modules/readerfooter.lua
https://github.com/koreader/koreader/pull/5203#issuecomment-522156268
https://github.com/koreader/koreader/pull/5203#pullrequestreview-276228925
> Fix after #5203

- frontend/ui/elements/refresh_menu_table.lua
+ add `Never refresh` in `Settings -> Screen -> E-ink settings -> Full refresh rate`.
+ spinnerWidget insteed of inputWidget after long press Cutom x
+ After changing the value, the menu label is now updated see: https://github.com/koreader/koreader/issues/5190#issuecomment-522528644
> Never full refresh

- frontend/gettext.lua
References https://github.com/koreader/koreader/issues/5232
Given an entry in the PO file like the following:
```
msgctxt "systemstat"
msgid "    Total"
msgstr "Totaal"
```
It can be addressed using:
```lua
_("systemstat", "    Total")
```
This allows to distinguish between separate instances of the same string, for example "Pages" meaning "Number of pages" and "Pages" meaning "Display of pages".
Extraction of this code pattern is not yet implemented by nightswatcher. xgettext didn't yet support Lua back in 2013 when all this was first added to the program, but now it does. Therefore it might make the most sense to replace the current Python extraction script with xgettext itself.
By default it only understands gettext.dgettext(), but that can be addressed by passing some extra command …
> [i18n, feat] Add basic context (msgctxt) support

- Makefile
- frontend/ui/data/css_tweaks.lua
This introduces context to our strings to differentiate them when necessary.
The syntax chosen is `C_()`, following [glib](https://developer.gnome.org/glib/2.28/glib-I18N.html#C-:CAPS).
```lua
local _ = require("gettext")
local C_ = _.pgettext
C_("Menu|StyleTweaks|", "Pages")
```
Closes #5232.
> [i18n] Switch `make pot` to xgettext

- frontend/ui/widget/opdsbrowser.lua
this will fix #5240 and provide some more feedback to users trying to use OPDS
catalogs
- handle moved permanently HTTP 301
- handle authentication required HTTP 401
- handle authentication errors HTTP 403
- handle catalog not found HTTP 404
> handle OPDS catalog responses accordingly

- .gitignore
They're created by Dolphin by default to store per-directory view settings.
> Git ignore .directory files

- Makefile
- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/filemanager/filemanagersearch.lua
- frontend/apps/reader/modules/readerfont.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerfrontlight.lua
- frontend/apps/reader/modules/readerhyphenation.lua
- frontend/apps/reader/modules/readertypeset.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/ui/data/strings.lua
- frontend/ui/network/manager.lua
- frontend/ui/translator.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/filechooser.lua
- frontend/ui/widget/touchmenu.lua
- frontend/util.lua
- plugins/coverbrowser.koplugin/bookinfomanager.lua
- plugins/evernote.koplugin/main.lua
- plugins/kosync.koplugin/main.lua
- plugins/systemstat.koplugin/main.lua
Thanks to <https://github.com/koreader/koreader/pull/5237> we can now  extract the knowledge currently embedded in Transifex and put it directly in our source. This positively affects <https://github.com/koreader/koreader/issues/3754>.
Translation instructions and knowledge that comes out of localization-related questions should be preserved in the source, because Transifex is too ephemeral. For example, the links from <https://github.com/koreader/koreader/pull/2290> are no longer accessible. Even when they are, it's quite useful to have this information around while dealing with the code as well, and I also hope it'll be informative to contributors who seldom visit Transifex.
This commit also makes a few minor changes to obviate the need for comments where possible.
> [i18n] Add translator notes

- Makefile
- frontend/gettext.lua
- frontend/ui/widget/filechooser.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/evernote.koplugin/main.lua
- spec/unit/gettext_spec.lua
Fixes <https://github.com/koreader/koreader/issues/5249>.
Looks a little something like this:
> [feat, i18n] Implement ngettext

- frontend/gettext.lua
A simple `string.gmatch()` should do the trick here, which avoids the need for refactoring.
Fixes <https://github.com/koreader/koreader/issues/5269>.
> [fix] Remove gettext util dependency

- .gitignore
- Makefile
Changes Cervantes, Kindle, Kobo, Pocketbook, and Sony to the following format:
```
koreader-kobo-v2018.11.1.zip
koreader-kobo-debug-v2018.11.1.zip
```
Changes Android to the following format:
```
koreader-android-arm-v2019.09.apk
koreader-android-arm-debug-v2019.09.apk
koreader-android-x86-v2019.09.apk
koreader-android-x86-debug-v2019.09.apk
```
Fixes <https://github.com/koreader/koreader/issues/4297>.
> [feat] Friendly filename

- Makefile
I overlooked the Kindle cleanup line in https://github.com/koreader/koreader/pull/5268, but that kind of thing is what variables are made for.
> [chore] Makefile cleanups

- plugins/kosync.koplugin/main.lua
As a side effect of <https://github.com/koreader/koreader/pull/4189> some menus have to manually trigger updates.
I'm not overly enthused with this solution but I couldn't think of anything better right now.
Fixes <https://github.com/koreader/koreader/issues/5224>.
> [fix, UX] Update kosync login/logout text

- frontend/device/input.lua
- frontend/ui/uimanager.lua
This allows to shutdown straight from suspend just like Nickel.
Fixes <https://github.com/koreader/koreader/issues/2431>.
> [feat, Kobo] Implement shutdown from suspend

- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/ui/elements/reader_menu_order.lua
This is supported by ReaderPaging and ReaderRolling, but the menu entry was only shown in ReaderPaging.
Hold now sets the global default.
Fixes <https://github.com/koreader/koreader/issues/4983>.
Fixes <https://github.com/koreader/koreader/issues/4089>.
> [UX] Treat inverse_reading_order as a proper setting

- frontend/apps/reader/modules/readerconfig.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/apps/reader/modules/readerzooming.lua
- frontend/apps/reader/readerui.lua
- frontend/document/document.lua
- frontend/document/pdfdocument.lua
- frontend/ui/data/koptoptions.lua
- frontend/ui/widget/configdialog.lua
Closes #4368.
<del>I might leave it like this for now (after some minor cleanup), meaning the full document will have to be reloaded, because `layoutDocument()` has to be called again. Ideally I'd give it that bit of polish too.</del> <ins>Rerendered on the fly.</ins>
> [feat] Add MuPDF EPUB/FB2 dynamic font size

- Makefile
- kodev
- platform/android/llapp_main.lua
Requires https://github.com/koreader/android-luajit-launcher/pull/174 ~~and https://github.com/koreader/android-luajit-launcher/pull/175~~
The main benefit of having the libraries outside the zip file is that they will be installed when installing the application instead of copying them on the first run (it could save a few seconds)
**Edit:** I'm leaving the libs thingy for the future.
> migrate from lzma to zip file.

- Makefile
- frontend/fontlist.lua
- frontend/ui/elements/font_settings.lua
- frontend/ui/font.lua
This is preinstalled on every Android device. It's only 105.6 KiB, but every space reduction is a good one.
Cf. <https://github.com/koreader/koreader/pull/5200#issuecomment-524501845>.
> [Android] Don't package Droid Sans

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/ui/widget/dictquicklookup.lua
Internal links carry more baggage than external ones.
See <https://github.com/koreader/koreader/pull/5282#issuecomment-526813719>.
> [fix] Pass plain link to link:onGotoLink

- tools/wbuilder.lua
The widget builder was broken by <https://github.com/koreader/koreader/pull/4580>.
> [fix] Add CanvasContext to wbuilder

- frontend/apps/reader/modules/readergesture.lua
Reorganize submenu tap corner like other submenus
Settings -> Tap and gestures -> Gesture manager -> Tap corner
Before:
After:
> Reorganize tap corner menu in Gesture Manager

- reader.lua
This patch only handles part of  file URI scheme defined in [rfc 8089](https://tools.ietf.org/html/rfc8089), i.e., it currently only handles `file://ABSOLUTE_PATH`.
> handle file:// protocol URI scheme

- frontend/gettext.lua
- spec/unit/gettext_spec.lua
Fixes <https://github.com/koreader/koreader/issues/5293>.
> [fix] GetText: guard against empty strings in translation

- frontend/device/kobo/powerd.lua
Fixes <https://github.com/koreader/koreader/issues/5292>.
> [fix, Kobo] Save frontlight state on shutdown after suspend

- frontend/ui/data/creoptions.lua
- frontend/ui/widget/configdialog.lua
Similar to top and bottom margins I add fine tune buttons to L/R margins.
Before: 
After:
> Add fine tune buttons to horizontal margins

- frontend/ui/uimanager.lua
See <https://github.com/koreader/koreader/issues/2431#issuecomment-526925910>.
Supersedes <https://github.com/koreader/koreader/pull/5302>.
> [fix] Let UIManager handle suspend logic

- frontend/document/koptinterface.lua
Can occur with invalid page numbers, for example by changing the font size in a reflowable MuPDF document.
Discussion in <https://github.com/koreader/koreader/pull/5282#issuecomment-526842921>.
> [fix] Prevent crash when no page boxes

- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/toggleswitch.lua
And a couple bugfix this unearthed:
* Always set the default as the *current* value, no matter what (by chance, this was not an issue for margins).
* Don't crash on the hold gesture in the -/+ buttons for the horizontal margins (regression since #5303).
> Allow setting a fine-tuned font size as default

- Makefile
- frontend/fontlist.lua
- frontend/ui/font.lua
Follow-up to <https://github.com/koreader/koreader/pull/5252>. This greatly reduces the Android package size.
See discussion in <https://github.com/koreader/koreader/pull/5264#issuecomment-525517001>.
> [Android] Don't ship Noto

- frontend/apps/reader/modules/readergesture.lua
Sorry, I couldn't resist the stupid *Arrow* reference, since this PR is entirely concerned with... arrows ;p.
* Switch the one finger edge swipe descriptions to harpoon arrows
* Switch the two-finger swipe arrows to double arrows, instead of a single large, filled arrow, to emphasis the fact that it's a gesture that requires, well, two fingers.
> You have failed this city!

- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/menu_keyboard_layout.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/language.lua
- frontend/ui/widget/virtualkeyboard.lua
Fixes <https://github.com/koreader/koreader/issues/3998>.
This is an unpolished quickie but I've been letting this slip for too
long due to fancier keyboard interaction concepts.
> [UX] Allow keyboard layout selection

- frontend/apps/reader/modules/readergesture.lua
Otherwise ffi/util.template crashes on a table.
> [fix] ReaderGesture: Use getCurrentNetwork().ssid

- frontend/apps/filemanager/filemanagermenu.lua
- platform/kobo/koreader.sh
Because getting booted back to Nickel is mildly annoying ;).
(Keeps track of crashes to avoid getting stuck in boot loops).
> [Kobo] Restart KOReader after a crash

- frontend/document/pdfdocument.lua
A typo introduced in <https://github.com/koreader/koreader/pull/5282>.
This might resolve <https://github.com/koreader/koreader/issues/5323>, fixes <https://github.com/koreader/koreader/issues/5327>.
> [fix] PdfDocument: Hash collision

- frontend/ui/elements/filemanager_menu_order.lua
Overlooked in <https://github.com/koreader/koreader/pull/5318>.
> [fix] Add keyboard layout to filemanager menu

- platform/android/llapp_main.lua
Partially reverts d2536d8b7e9474bd7748b199d1f01a53f332942a.
Fixes <https://github.com/koreader/koreader/issues/5347>.
> [fix, Android] Set executable bit

- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerrolling.lua
`self.inverse_reading_order == nil and G_reader_settings:has("inverse_reading_order")` could easily be false, which would then incorrectly turn the setting off.
Fixes <https://github.com/koreader/koreader/issues/5346>.
> [fix] ReadSettings Inverse reading order

- frontend/apps/filemanager/filemanagerfilesearcher.lua
Fixes <https://github.com/koreader/koreader/issues/5343>.
> [fix] Filesearcher crash on empty file attributes

- frontend/apps/reader/modules/readerfooter.lua
> Disable show chapter markers when progress bar is hidden in footer

- frontend/device/kobo/nickel_conf.lua
- frontend/device/kobo/powerd.lua
- spec/unit/nickel_conf_spec.lua
When reasonably possible, the program should only crash in debug mode.
Adds a couple of extra unit tests to prevent regressions and adds docs.
Fixes <https://github.com/koreader/koreader/issues/5356>.
> [fix, Kobo] Don't crash trying to sync frontlight with Nickel.

- frontend/ui/data/creoptions.lua
- frontend/ui/widget/buttonprogresswidget.lua
- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/spinwidget.lua
See: https://github.com/koreader/koreader/issues/5312#issuecomment-528506421
Progress widget has a new extra button `⋮` that triggers SpinWidget.
> Add fine tune in line spacing

- frontend/document/pdfdocument.lua
Fix issue 2) at #5383. Closes #5383.
> Fix: don't create sidecar file when indexing pdf documents

- frontend/apps/reader/modules/readerrolling.lua
- frontend/document/credocument.lua
Includes https://github.com/koreader/crengine/pull/310
- Adds tinyNodeCollection::getStatistics()
- epubfmt.cpp: cleanup indentation and small optimisation
- Add more progress callback events
- Optimisation: avoid re-init for EPUBs with embedded fonts
- Fix: don't draw border when border-color: transparent
- CSS: ignore 'inherit' inside font-family
Show a small progress meter at top left of screen when crengine is loading, re-rendering, and saving cache file (after a 2 second delay to not be bothered on small books):
<kbd>![image](https://user-images.githubusercontent.com/24273478/65353632-e9ef0a80-dbed-11e9-8fad-7a23d17de332.png)</kbd>
Also add a wrapper for the last remaining bit of code that was accessing _document directly (`:getPageOffsetX()`).
> bump crengine, show progress meter on load/re-rendering

- frontend/device/cervantes/powerd.lua
- frontend/device/kobo/powerd.lua
- frontend/device/sysfs_light.lua
It's much lower latency (re #5373).
We can do so on NL devices with a mixer.
> [Kobo/Cervantes] Prefer using the ioctl over sysfs when setting the FL.

- frontend/device/kobo/device.lua
It's actually UR, not CCW like on the Forma.
> Hotfix the startup orientation on the Kobo Libra

- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerrolling.lua
Close: #3778 
We have to set chapter markers in footer every time when screen geometry is changed.
Thanks @poire-z for: https://github.com/koreader/koreader/issues/3778#issuecomment-389967175
> Fix: incorrect chapter markers

- frontend/ui/widget/toggleswitch.lua
See: https://github.com/koreader/koreader/pull/5375#issuecomment-533561559
Before (align `View mode` `Render mode` `Zoom`):
After (align `View mode` `Render mode` `Zoom`):
> Better align toggleswitch in configdialog

- frontend/apps/reader/modules/readergesture.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerrolling.lua
before you merge, i am not very familiar with lua so a few points;
i was not sure what to put here just followed the flow.
```lua
{"toggle_inverse_reading_order", not self.is_docless, true},
```
is there a way to abstract the code from `readerrolling` and `readerpaging` to avoid duplication?
---
when testing this i came across a very weird related bug that i can not figure out.
on startup of the reader i can change the page turn direction using any gesture.
once the page turn direction was changed in the current session (of crengine) i cannot change it via the corresponding corner gesture.
i can't go from RTL -> LTR using the right corners,
nor from LTR -> RTL using the top left corner,
nor either way using the bottom left corner.
(all once the page turn direction was changed in the …
> [UX] add inverse reading order to gesture manager

- frontend/ui/size.lua
- frontend/ui/widget/buttonprogresswidget.lua
Similar to #5420 
Before:
After:
Before:
After:
> Better align buttonprogress in configdialog

- frontend/device/cervantes/powerd.lua
- frontend/device/kobo/powerd.lua
sysfs_light handles every case sanely already, no need to be cute ;).
This prevents always setting the warmth when setting the FL on NL
devices with a mixer, because, besides being useless, it's also slow
(lua does mmap'ed io, so every handle requires an fstat + mmap).
It was subtly affecting the fluidity of the toggle ramp, and much less
subtly wreaking havoc on #5373 ;).
KA1 owners might want to investigate keeping the fds around one way or
another, like we do for the fl ioctl, to alleviate the overhead of doing
that for not one but three or four fds...
I won't be doing that, since I lack the hardware to test it, and FL+NL
stuff is pain.
> [Kobo/Cervantes] Always use setBrightness to set the brightness

- frontend/ui/data/css_tweaks.lua
- frontend/ui/wikipedia.lua
bump crengine: enhanced RTL block rendering. Includes:
- Re-enable: Use the same FT load flags in HB as in FT https://github.com/koreader/crengine/pull/311
- Avoid redundant calls to getStyle() https://github.com/koreader/crengine/pull/312
- CSS: parse and store "direction:"
- Enhanced block rendering: handle RTL direction
- Enhanced block rendering: handle RTL tables
- Pagesplitting: account for lines' text direction
- CSS: add support for more pseudo-classes
- epub.css: a few updates for RTL documents
- Fix LVDocView::getBookmark() which could be slow or wrong https://github.com/koreader/crengine/pull/313
Add a few style tweaks useful to RTL readers.
Wikipedia Save as EPUB: build proper RTL documents from persian, arabic, hebrew (and others) Wikipedia articles.
Screenshots in …
> EPUB: more support for RTL documents

- plugins/evernote.koplugin/JoplinClient.lua
- plugins/evernote.koplugin/main.lua
adds joplin support https://github.com/koreader/koreader/issues/5086
Changes
-adds a submenu to evernote menu 
- -Joplin
|-Set IP and port
|-Set authorization token
|-Export to Joplin
|-Help
-adds EvernoteExporter:exportBooknotesToJoplin()
-adds JoplinClient.lua
-modifies html_export, txt_export and joplin_export flags to work with each other. (eg if user selects one others deactivated)
Because joplin only listens on localhost, [see diccussion on joplin forums, ](https://discourse.joplinapp.org/t/clipper-api-listens-only-localhost-requesting-to-include-local-addresses/3560)  user needs to port forward on computer. To do that :
on linux `$socat tcp-listen:41185,reuseaddr,fork tcp:localhost:41184`
on windows `netsh interface portproxy add listeningaddress:0.0.0.0 listeningport:41185 …
> Joplin support

- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/toggleswitch.lua
> Fix: Crash toggleswitch when args are empty

- frontend/ui/uimanager.lua
see https://github.com/koreader/koreader/issues/5415 https://github.com/koreader/koreader/issues/4034
> Fix frozen confirmbox when keyboard shown

- frontend/apps/reader/modules/readermenu.lua
Regression inadvertently caused by #5369.
With the way this is constructed, this is almost guaranteed to happen.
Fixes #5459.
> [fix] Try to make screensaver settings slightly less error-prone

- frontend/ui/widget/imageviewer.lua
As proposed in #5444, when open an image, it is shown using the whole screen. User can toggle the buttons by tapping the bottom quarter. Tapping other area will close the image.
If it is a list of image (e.g. animated gifs), then the above does not applied.
> Image viewer use the whole screen

- Makefile
Reverts a small part of #5310.
I don't really have the time to investigate doing font fallback better and the Android landscape is a tad far from uniform.
Fixes #5381.
> [Android] Ship Noto

- frontend/device/android/device.lua
- frontend/ui/elements/screen_android.lua
Visible changes:
- KOReader icon on start & friendly e-ink spinner, authored by @ColinKinloch
- Safer and more verbose WRITE_SETTINGS permissions: 
Under the hood: 
- Migration to Kotlin (everything except the test activity and the e-ink methods to refresh the screen):
+ Safety against null pointer exceptions (It can still be triggered from JNI)
+ Less boilerplate code.
+ Usually easier to read and more expresive.
- More responsive garbage collector:
+ avoid leaking activity context
+ slightly more memory usage on average (~1MB) but with the hability to free some memory on-demand (2-3MB)
- Removed wakelock permissions.
Fixes #5374 
Requires https://github.com/koreader/android-luajit-launcher/pull/193
> android bump - kotlin/haptic/timeout

- frontend/device/kobo/powerd.lua
It might be possible to instead only set the white led, but I don't
have the hardware to test that theory, so, eh.
Fix #5465 (probably.)
> [Kobo] Always set the warmth on the KA1

- plugins/evernote.koplugin/clip.lua
see https://github.com/koreader/koreader/issues/5408
parseHighlight now must be called with both highlight and bookmarks fields of sidecar file. If bookmarks field have edited text field on it, it removes page and time info from text, saves edited version as clipping.text. 
I tried to making it work only with bookmarks or highlight but both fields lacks necessary data (pboxes, page info for example) and didn't want to fill them with duplicate info.
Also when a highlights borders are changed bookmarks.text field gets rewritten. I think there will also be issues with that later.
> Support for exporting annotations/bookmark renames 

- platform/pocketbook/koreader.app
In Pocketbook Koreader should also use system fonts. 
Tested by Cyfranek from forum.eksiazki.org
> Use system font in Pocketbook

- plugins/wallabag.koplugin/main.lua
A new setting has been adding allowing to set a comma separated list of
tags to ignore.
Entries with either of these tags will be skipped by the client when
fetching the list of articles to download. Extra articles will be
fetched from the server to make up for the skipped articles, ensuring to
meet the target number of articles.
This can be used to ignore some articles that are known to not be readable in koreader: videos, binaries,.. As long as they are correctly tagged on the server. 
Another use case could be, once the ability to tag an entry in the client has been added, to ignore some entries and not download them again.
Most of the code (for the UI) was copied from the existing `filter_tag` setting.
> [feat] plugins/Wallabag: add ability to set a list of tags to ignore

- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readertypeset.lua
I found several problems with proper showing footer (or margins) when enable/disable progress bar (or mode with empty items) after KO start.
> Fix footer with no_mode and disabled progress bar

- frontend/apps/reader/modules/readermenu.lua
With some particular document switching workflows, the screensaver menu could lose its last item, and shrink to having zero item, and eventually cause a crash.
Details at https://github.com/koreader/koreader/pull/5460#issuecomment-543139751.
Fix first crash mentionned in #5469.
> Fix screensaver menu stability

- frontend/document/credocument.lua
Includes:
- (Upstream) Unified cache for chars and glyph's indexes https://github.com/koreader/crengine/pull/314
- (Upstream) Glyph caching: optional use of hash table instead of a linked list
- (Upstream) Adds docx and fb3 support
- Update hardcoded elements list and stylesheets
- DocX: build a HTML DOM instead of a FB2 DOM
- Text: allow wrap after '/' and '-' https://github.com/koreader/crengine/pull/316
- Text: with Harfbuzz, split measurement on text node change
- Clear fonts on load and re-rendering
> bump crengine: adds DOCX and FB3 support

- frontend/document/pdfdocument.lua
- frontend/ui/screensaver.lua
When just reading settings, no need to close and write the file to disk - as it's just a table that disappear when out of scope, and no ressource attached.
> Remove uneeded doc_settings:close()

- Makefile
- kodev
Translations live in a submodule since <https://github.com/koreader/koreader/pull/5506>,
and without initialized submodules `kodev release` will therefore fail.
The specifics need a fair bit more attention once Weblate has been set up, but this should
suffice for the nightly/stable build to succeed.
> [fix] kodev: Allow nightly build to succeed

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerutil.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/widget/keyvaluepage.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/touchmenu.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/main.lua
- plugins/goodreads.koplugin/doublekeyvaluepage.lua
Have made several changes to the UI to improve the experience and make it less "clunky" and more polished/refined, please let me know what you think
> UI Changes

- frontend/apps/filemanager/filemanager.lua
- frontend/ui/rendertext.lua
- frontend/ui/screensaver.lua
- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/fixedtextwidget.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/keyvaluepage.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/numberpickerwidget.lua
- frontend/ui/widget/sortwidget.lua
- frontend/ui/widget/spinwidget.lua
- frontend/ui/widget/textwidget.lua
- frontend/ui/widget/toggleswitch.lua
- frontend/ui/widget/touchmenu.lua
- frontend/ui/widget/trapwidget.lua
- plugins/coverbrowser.koplugin/covermenu.lua
- plugins/goodreads.koplugin/doublekeyvaluepage.lua
Lots of code was doing some renderText calls to get the size of some text string, and truncate it to some width if needed, with or without an added ellipsis, before instantiating a TextWidget with that tweaked text string.
This PR fixes/adds some properties and methods to TextWidget so all that can be done by it. It makes the caller codes simpler, as they don't need to use RenderText directly.
(Additionally, if we ever go at using Harfbuzz for text rendering, we'll just have to update or replace textwidget.lua without the need to update any higher level code.)
RenderText: removed the space added by truncateTextByWidth after the ellipsis, as it doesn't feel needed, and break right alignment of the ellipsis with other texts.
KeyValuePage: fix some subtle size and alignment issues. …
> TextWidget: small refactoring, better handle max_width

- frontend/ui/widget/menu.lua
See: #5388 
New algorithm:
When text is too long or too height:
- first: we try to decrease number of lines (eg from 3 to 2 and from 2 to 1 line)
- second: when 1 line is too height we try to decrease font size (-1)
And at the end we try to add or remove at least one letter to better fit text.
Needs to be tested. Shouldn't be merge before 2019.10.
Close: #5388
> New algorithm to show items in menu widget

- plugins/coverbrowser.koplugin/listmenu.lua
- Use a hardcoded default value of 10 files per page. https://github.com/koreader/koreader/pull/5435#issuecomment-545335940
- Save cover sizetag as `s<nb of items per page>` instead of `s<item height>` so they are stable (and not re-fetched) when switching between FileBrowser and History, which have some small geometry differences. Closes #5523.
- When showing History in landscape mode, decrease perpage from the set value, so items looks the same, instead of smaller.
- In list mode, use a step (larger with big items) when iterating and decreasing font sizes to make text fit, to speed up the process a bit. (This was already happening in mosaic mode.) On devices, instead of always -1, it will be -2 at around 8-12 items per page, -3 at around 4-6, possibly -4 on large devices.
There are …
> CoverBrowser: some fixes after #5435

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/readerui.lua
- frontend/document/documentregistry.lua
- frontend/ui/widget/filechooser.lua
This ~~is a working POC / hack to~~ allow opening unsupported files as txt, for example .lua files.
this can be very helpful when having oddly named files. 
it might be a good idea to allow all providers on this list?
this only triggers via the open with menu, not by directly clicking the item, unless setting the provider as a default.
this probably needs proper integration but i am not 100% sure exactly how the `DocumentRegistry` works and don't want to mess things up.
~~once this works i would like to add a way to clear already set providers from settings.~~
> open unsupported documents as text

- plugins/statistics.koplugin/main.lua
There is no need to generate a md5 sum for documents that were already opened.
> [statistic plugin] Don't generate md5 sum on open document

- frontend/apps/reader/modules/readerfooter.lua
- frontend/ui/font.lua
- frontend/ui/widget/touchmenu.lua
- spec/unit/document_spec.lua
- spec/unit/readerfooter_spec.lua
We unfortunately lack a battery glyph, so we'll make do with the power
glyph instead.
A vertical lignting bolt suffix now always means charging.
Fix #5535
> Unify battery meters look'n feel

- frontend/ui/elements/common_settings_menu_table.lua
This was glossed over in #5508 ;).
> Allow access to the topmenu clock format even if !Device:setDateTime()

- frontend/apps/filemanager/filemanagerutil.lua
By calling the function instead of returning it. Fixes #5547.
> [fix, Android] Crash on startup when no homedir is set

- doc/Building.md
- plugins/docsettingtweak.koplugin/main.lua
Might be emulator only. Can be easily replicated by deleting `settings.reader.lua*`, `settings/*` & `help/*` (recursively).
Opening the newly generated quickstart guide will deadlock in docsettingtweak:main:97 by busy-looping forever, because `directory == next_directory == base` (`== .`).
> Fix a deadlock with empty settings

- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/main.lua
Don't use a hardcoded default value of 10 files per page, but compute it from available height, as previously (this reverts a bit from #5525). See https://github.com/koreader/koreader/issues/5547#issuecomment-547525726
> CoverBrowser: list mode: better default for files_per_page

- frontend/ui/size.lua
- frontend/ui/widget/button.lua
- frontend/ui/widget/buttontable.lua
See https://github.com/koreader/koreader/issues/5449#issuecomment-548363585. I went with `Screen:scaleBySize(4),`, which is between the 2nd (2) and the 3rd (5) options among the screenshots there.
Went with 4 so I have no regret not aiming high - we'll decrease it to 3 (or 2 if really needed) if people find that too big.
Closes #5449.
> ButtonTable: taller buttons for easier tap

- plugins/coverbrowser.koplugin/listmenu.lua
Avoid saving/getting "12.0" (as the lua-ljsqlite3 driver does), and save/get "12" instead by properly converting it to a string and back, as the config.value table column is of type TEXT.
See https://github.com/koreader/koreader/pull/5551#issuecomment-548698110
> CoverBrowser: fix files_per_page setting type

- frontend/ui/wikipedia.lua
Tapping to turn pages while some image is loading was interrupting the image loading, but not turning the page, since #5173 where using `trap_widget=false` is to be used to not resend the event (while `=nil` does resend it).
> Wikipedia lookup results: fix page turning when image loading

- frontend/apps/reader/readerui.lua
Avoid double flash when switching documents (via gesture or Open previous document menu) or reloading document (switch from alt TOC to normal TOC, or when "styles have changes in such a way that fully reloading the document might be needed").
That's just the 2 place I had noticed that, so no big change.
Pinging @NiLuJe in case I missed something where these 2 flashes could make some sense.
> Avoid double flash when switching or reloading document

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/reader/readerui.lua
- frontend/readcollection.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/widget/sortwidget.lua
- plugins/coverbrowser.koplugin/bookinfomanager.lua
- plugins/coverbrowser.koplugin/covermenu.lua
- plugins/coverbrowser.koplugin/main.lua
New function that support organize books to favorites.
We can:
- add files to favorites
- remove files from favorites
- view list of favorites books
- sort list of favorites books
- open books from favorites
- change view mode (like in history)
Now we support only one collection (named favorites) but code is preparted to extend to more collections.
Some screenshots:
Close: #5099
> Add book to favorites

- frontend/device/input.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
Using camera button.
Fixes #5558
> android: touchscreen toggle

- frontend/ui/uimanager.lua
Reverts koreader/koreader#5452 because it breaks the way modal dialogs are supposed to work, which isn't the correct solution to #5415.
Also see #5573.
> Revert "Fix frozen confirmbox when keyboard shown"

- frontend/ui/widget/virtualkeyboard.lua
Added some forgotten `return true` on hold release event handlers: the event would otherwise trigger
a tap (as we generate a tap normally only at release time) and cause duplicate key strokes.
Details in https://github.com/koreader/koreader/issues/5555#issuecomment-550423347. Closes #5555.
(I included your suggested fix for the keyboard popup, as it's more related to my other fixes. You might want to remove it from #5569).
> Keyboard: avoid additional key stroke on hold release

- frontend/ui/opdsparser.lua
- frontend/ui/widget/opdsbrowser.lua
Close: #5476 
- Prevent segmentation fault when we enter incorrect address of calibre opds server (eg http://192.168.1.1:8080/ instead of proper http://192.168.1.1:8080/opds
- prevent unnecessary infos in Gutenberg OPDS like
> Prevent crash on local calibre OPDS server

- frontend/apps/reader/modules/readerrolling.lua
- frontend/ui/size.lua
the current thickness for the loading bar when opening a document is to thin to really see on my KT4,
i don't have screenshots as they only trigger once koreader finishes loading.
i would like to make it a little thicker, it still does not fully cover the top menu bar.
let me know if this is the wrong place to change the number, and if it has negative effects on other devices. (my emulator loads books too fast to get the bar)
> loading bar thicker

- frontend/apps/reader/modules/readerstatus.lua
- frontend/ui/elements/common_settings_menu_table.lua
> Add Mark as read to end of document action

- .luacheckrc
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/document/picdocument.lua
- frontend/ui/font.lua
- frontend/ui/rendertext.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/textboxwidget.lua
- frontend/ui/widget/textwidget.lua
- spec/unit/readerfooter_spec.lua
- spec/unit/textboxwidget_spec.lua
Have TextWdiget and TextBoxWidget use the new Lua C module (added in https://github.com/koreader/koreader-base/pull/1010) as an alternative text layout method, using Harfbuzz, FriBiDi and libunibreak.
This is needed to correctly shape Arabic scripts (cursive glyphs), propertly draw RTL text (Hebrew,
Arabic) and bidi text (arabic/hebrew filenames in english UI).
Screenshots and discussion in koreader/koreader#5359.
With this PR, we globally switch to use Harfbuzz for text shaping. It will feel like a change (text more condensed, I didn't like it initially, but switching back to the previous Freetype-only rendering, that old rendering really feels ugly :)
This should be enough to render Arabic text correctly. It still needs more work on the UI widgets and the language bootstrap code, and …
> TextWidget/TextBoxWidget: enhanced text shaping

- frontend/document/credocument.lua
- frontend/ui/widget/configdialog.lua
-  ConfigDialog: allow larger toggle title text : avoid a few truncated text, as some fit when allowed
to bite a bit on the (large) left padding.
Allows `Embedded fonts`, `Sync T/B Margins`, and `Render Mode` (truncated since we added the finetuning button) to no more be truncated.
- cre fonts list: ignore nerdfonts/symbol.ttf : it's rejected anyway by crengine, this just avoids
an error from being logged.
> ConfigDialog: allow larger toggle title text

- kodev
As per @NiLuJe's suggestions from <https://github.com/koreader/koreader/pull/5598#issuecomment-554767891>.
I'm not super happy with this but being able to easily run the emulator is the most important thing.
> [fix] Prevent double library loads

- frontend/apps/cloudstorage/cloudstorage.lua
- frontend/apps/cloudstorage/dropbox.lua
- frontend/apps/cloudstorage/dropboxapi.lua
- frontend/ui/cloudmgr.lua
Option to synchronize files in local koreader folder with folder on Dropbox. All files that aren't on the local disk will be downloaded. Files with different sizes will also be downloaded and overwritten.
The download process can be paused or stopped at any time (similar to downloading images in Wikipedia).
Synchronize and settings are available after long press in dropbox account in Cloud storage. 
Limitations: Only one folder (without subfolders) can be synchronize with one folder on local storage.
Close: #4971
> Synchronize local folder with dropbox

- frontend/apps/cloudstorage/cloudstorage.lua
- frontend/apps/cloudstorage/dropbox.lua
- frontend/apps/cloudstorage/ftp.lua
- frontend/apps/cloudstorage/webdav.lua
Two cloudstorage UX improvements:
+ Show confirmbox `File already exists. Would you like to overwrite it?` after tap on `Download file` not before tap in situation when file exist in local storage.
+ Show confirmbox `File saved to: (...). Would you like to read the downloaded book now?` instead of `File saved to:...` when file is supported and when we have choosen `Show unsupported files` .
> Cloud storage UX improvements

- frontend/ui/widget/radiobutton.lua
Fixes <https://github.com/koreader/koreader/issues/5614>.
> [fix] Prevent xtext crash by not freeing TextWidget prematurely

- frontend/apps/filemanager/filemanagerutil.lua
- frontend/apps/reader/skimtowidget.lua
- frontend/ui/widget/bookstatuswidget.lua
- plugins/statistics.koplugin/readerprogress.lua
PR fix prevent empty path in filemanager.
Step to reproduce:
1. Create two folders:
+ /home/koreader/test
+ /home/koreader/test1
2. Set folder `/home/koreader/test` as home folder in KO
3. Set option `Shorten home directory` (Other settings -> Shorten home directory)
4. Go to folder in fm to `/home/koreader/test1`
> [fix] Empty directory path and crash on TextWidget

- frontend/ui/screensaver.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
Small fixes:
- Screensaver: avoid crash when no lastfile. Closes #5633. 
- CoverBrowser: Mosaic: fix alignment on non-fully filled rows. Closes #5634.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5638)
> Screensaver: avoid crash / CoverBrowser Mosaic: fix alignment

- frontend/util.lua
- spec/unit/util_spec.lua
`util.secondsToHClock(xx, true, true)` should show _xx_**m** instead _xx_**'** when xx<3600.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5640)
> fix util.secondsToHClock when hmsFormat is true

- plugins/batterystat.koplugin/main.lua
- spec/unit/batterystat_spec.lua
Close: #3031, #2937
What was done:
- fix incorrectly show awake and sleeping,
- fix incorrectly show charging and discharging,
- remove unneeded debug mode,
- remove logging to external file,
- another method to show indentation text for better translate,
- prevent showing values like inf, -inf, nan in estimate time (we show now n/a),
- prevent showing values below zero,
- show extra confirm box when we want to reset data,
- show time in format xx**h**xx**m** (hours, minutes) instead only pure minutes,
- check at initialization that the device was charging when it was turned off (the battery is larger than at the time of the KO exit),
ToDo: 
- more tests
- show time in format xx**d**xx**h**xx**m** (days, hours, minutes)
Before:
After:
--- …
> Fix and improvements of battery stats plugin

- frontend/ui/elements/font_settings.lua
- plugins/systemstat.koplugin/main.lua
Fixes #5631 
Fixes #5621 
Fonts can be placed in the following directories (under the primary storage partition): `fonts/` and `koreader/fonts`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5643)
> Android fixes

- frontend/ui/data/keyboardlayouts/ko_KR_keyboard.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/inputtext.lua
- frontend/ui/widget/virtualkeyboard.lua
- plugins/coverbrowser.koplugin/main.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
Avoid some of the issues noticed in #5632:
- Korean keyboard: unwrap InputText on layout change:
The korean keyboard wraps InputText and overrides some of its methods to process input in some specific way (details in #5053). When switching to another keyboard layout, the original methods need to be restored.
- Keyboard: properly handle keyboard layout height change
The japanese keyboard being taller than the others, when switching to/from it from/to another layout:
Re-init InputDialog for proper sizing and positionning
Refresh the whole screen, to remove any trace of a previous taller keyboard
Also add calls to :free() here and there to free keyboard keys' TextWidgets' XText C objects without waiting for GC.
(The `width = icon_height * 100` change is just because I was seeing some huge …
> Keyboard layout change and Coverbrowser Mosaic tweaks

- frontend/apps/reader/modules/readerdictionary.lua
See: https://github.com/koreader/koreader/pull/5647#issuecomment-559376164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5650)
> [fix] Crash dictionary font size in reader mode

- frontend/ui/data/keyboardlayouts/keypopup/en_popup.lua
- frontend/ui/data/keyboardlayouts/keypopup/ru_popup.lua
- frontend/ui/data/keyboardlayouts/ru_keyboard.lua
This commit contains the following changes:
~~- Added Șș diacritics - I added those instead of $ symbol which was already duplicate on the main en layout popup.~~
~~- Added Ĭĭ, Ŭŭ, Ăă (on the en layout popup)~~
~~- Added comments for all Romanian characters with diacritics - also rearranges some of them for consistency.~~
- Added Ӂӂ on the Russian layout popup for Moldavian.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5652)
> Add Moldavian diacritics to ru_keyboard

- frontend/apps/reader/modules/readergesture.lua
- frontend/depgraph.lua
- spec/unit/depgraph_spec.lua
Happens with "Inverse reading order", which re-registers the Reader tap forward/backward zones and would prevent tap menu and bookmark from working.
Before this PR, when removing them, we would lose all the `override=` set on them by other touch zones (tap menu, bookmarks...), and so they were no more ensured after re-adding the zone.
So, make sure we don't lose that info. (Pinging @houqp for info, as DepGraph comes from you.)
This must be the proper fix for #5354, and revert a bit from #5423 (which made only the gestures set by ReaderGesture re-work - but not all others not managed by ReaderGesture like ReaderMenu Tap on top of screen). Pinging @yparitcher for info.
--- …
> Touch zones: fix loss of overrides when re-registering a zone

- frontend/ui/widget/inputtext.lua
- frontend/ui/widget/textboxwidget.lua
- plugins/coverbrowser.koplugin/listmenu.lua
Includes https://github.com/koreader/crengine/pull/321:
- CSS: remove invalid and unused item in selector enum
- Fix possible crash with backward search
Also:
- xtext.cpp: adds `XText.getParaDirection()` to help with cursor positionning in empty lines in RTL/bidi https://github.com/koreader/koreader-base/pull/1019 
- xtext: fix occasionally wrong measured width https://github.com/koreader/koreader-base/pull/1020
Also includes some TextBoxWidget tweaks:
- have the XText object freed early when no more needed.
- slightly better cursor positionning in RTL text (not really visible for now, will need proper UI RTL language support in a followup PR - but this change needs the xtext.cpp base bump, which is unrelated to RTL UI mirrorring)
And a CoverBrowser list view mode fix for: …
> bump crengine: fix possible crash, some TextBoxWidget tweaks

- Makefile
There's some delay on the Weblate end. Partially reverts #5507. Fixes #5673.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5674)
> Transifex pull on release build

- frontend/device/android/dictionaries.lua
After a conversation with @Norbi24 in https://www.mobileread.com/forums/showthread.php?t=325088 I finally implemented [his original suggestion](https://www.mobileread.com/forums/showpost.php?p=3922401&postcount=4)
Requires https://github.com/koreader/android-luajit-launcher/pull/200 for being able to launch an action with no specific package
I tested it placing the file "dictionaries.lua" inside the koreader folder with
```lua
return {
{ "Generic", "App picker", true, nil, "send" },
{ "ColorDict", "ColorDict", false, "com.socialnmobile.colordict", "colordict" },
}
```
If no package is specified the item must be true to avoid checking if the package is available.
--- …
> android: allow overrides on 3rd party dictionary list

- Makefile
- frontend/apps/reader/modules/readerfont.lua
- frontend/fontlist.lua
- frontend/ui/elements/font_settings.lua
- frontend/ui/font.lua
like on desktop linux, but without the menu entry to open fonts dir.
Wip: works fine on fresh installation (without the koreader folder or with the folder without further modifications) but crashes on my main device, which is actually is/was heavily modified.
I'll update the crash logs when I have a bit of time.
**Edit:** the main reason for this PR is to avoid *15* pages of noto fonts on my huawei tablet. Others will find this useful too, specially on generic, modern, phones/tablets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5670)
> android: make system fonts toggable

- frontend/apps/reader/modules/readerpaging.lua
closes  #5654
like #5620 but for continuous mode.
~~may fail CI because the page sizes change.~~
needs testing for side effects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5657)
> fix continuous scroll & footer overlap

- frontend/ui/font.lua
- frontend/ui/rendertext.lua
- frontend/ui/widget/textboxwidget.lua
- frontend/ui/widget/textwidget.lua
Follow up to #5598 _"we might need to work on our bold font use and handling..."_
A few fixes and enhancement related to bold text:
- When using `bold=true` with a regular font, use its bold variant if one exists.
- When using a bold font without `bold=true`, promote `bold` to `true`, so fallback fonts are drawn bold too.
- Whether using a bold font, or using `bold=true`, ensure fallback fonts are drawn bold, with their available bold variant if one exists, or with synthetized bold.
- When using a bold variant of a fallback font, keep using the regular variant as another fallback (as bold fonts may contain less glyphs than their regular counterpart).
- Allow providing `bold=Font.FORCE_SYNTHETIZED_BOLD` to get fake bold even when a bold font exists (might be interesting to get text in bold …
> UI font rendering: use available bold fonts for bold

- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/docsettings.lua
- frontend/luadata.lua
- frontend/luasettings.lua
- frontend/readhistory.lua
- spec/unit/docsettings_spec.lua
Bump base for util.fsyncOpenedFile() and util.fsyncDirectory() https://github.com/koreader/koreader-base/pull/1021
Use these to force flush to storage device when saving luasetting, docsetting, and history.lua.
Also dont rotate them to .old until they are at least 60 seconds old.
Discussion in #3625.
(Unrelated, but I also updated Luadata so it does not output stuff when there is no file - I used to see a few lines as I got not custom multiswiple.lua defined.)
Also bump crengine: open (as text) small or empty files https://github.com/koreader/crengine/pull/322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5678)
> Settings: use fsync() for more robust setting files saving

- frontend/apps/reader/modules/readerhyphenation.lua
- frontend/ui/widget/doublespinwidget.lua
More generic HyphenationLimits widget is now known as DoubleSpinWidget. TextBoxWidget was changed to TextWidget to prevent multiline in title above NumberPickerWidgets.
This is first step to create `more_option ⋮` for `Word Spacing` in ConfigDialog.
See: https://github.com/koreader/koreader/pull/5655#issue-346842175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5679)
> New widget DoubleSpinWidget based on HyphenationLimits

- datastorage.lua
- frontend/device/android/device.lua
Requires https://github.com/koreader/android-luajit-launcher/pull/201
Tested against the Android 10 - emulator
Build with targetApi 28: normal storage, RW path retrieved: `/storage/emulated/0`
Build with targetApi 29: scoped storage, RW path retrieved: `/storage/emulated/0/Android/data/org.koreader.launcher/files`
This isn't intended as a long term solution but as a workaround. Lets see what other reading software do to avoid scoped storage limitations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5680)
> android: unbreak KO on scoped storage devices

- frontend/ui/data/keyboardlayouts/en_keyboard.lua
Here's a quick concept for consideration. Use 1/2 and 2/2 instead of Shift.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5659)
> [UX] Simple symbol keyboard layer paging

- frontend/ui/widget/textboxwidget.lua
Fix crash (witnessed when swiping quickly to change dict/wiki results and a swipe registers as hold and does text selection):
```
./luajit: frontend/ui/widget/textboxwidget.lua:1751: bad argument #1 to 'getSelectedWords' (index out of range)
[C]: in function 'getSelectedWords'
frontend/ui/widget/textboxwidget.lua:1751: in function 'handleEvent'
frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent' …
```
> TextBoxWidget: fix crash on hold after end of text

- frontend/ui/widget/textboxwidget.lua
When `text = "Stuff\n"` and `alignment="center"` or `="right"`, TextBoxWidget would crash with:
```
./luajit: frontend/ui/widget/textboxwidget.lua:494: attempt to perform arithmetic on field 'targeted_width' (a nil value)
frontend/ui/widget/textboxwidget.lua:494: in function '_shapeLine'
frontend/ui/widget/textboxwidget.lua:676: in function '_renderText'
frontend/ui/widget/textboxwidget.lua:166: in function 'init'
frontend/ui/widget/widget.lua:48: in function 'new'
frontend/ui/widget/buttondialogtitle.lua:65: in function 'init'
frontend/ui/widget/widget.lua:48: in function 'new'
frontend/apps/reader/modules/readerlink.lua:668: in function 'onGoToExternalLink'
```
(I had added aligmnent="center" in my own patch, I guess we don't have any occurence of these circonstances in …
> TextBoxWidget: fix crash when empty last line and alignment center/right

- frontend/ui/widget/textboxwidget.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
- bump crengine: (Upstream) DocX: fix paragraphs with single hyperlink https://github.com/koreader/crengine/pull/323
- bump fribidi to 1.0.8 (for nested isolates fix, https://github.com/koreader/koreader/issues/5359#issuecomment-565001148)
- xtext.makeLine(): return `no_allowed_break_met=true` when that happens, so we know the line breaks inside a word. https://github.com/koreader/koreader-base/pull/1022 https://github.com/koreader/koreader/pull/5598#issuecomment-565836669
Also CoverBrowser: Mosaic: better words wrap in text covers
- Update words wrapping tweaks for use_xtext: add zero-width spaces around dots and underscores to allow more wraps.
- Fix overlap of directory name and nbitems for long directory names.
Before:
<kbd>![image](https://user-images.githubusercontent.com/24273478/70 …
> bump crengine, fribidi, xtext - some CoverBrowser Mosaic tweaks

- platform/cervantes/koreader.sh
- platform/kindle/koreader.sh
- platform/kobo/koreader.sh
Will stall for longer, but with a visible message (vs. less stalling on
a white screen during the startup and a laggy FM for a while).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5685)
> Ensure we flush everything to disk after an update.

- frontend/gettext.lua
- frontend/ui/bidi.lua
- frontend/ui/widget/menu.lua
- frontend/util.lua
- spec/unit/util_spec.lua
Some followup tweaks to #5667:
- Alias everything to `Bidi.nowrap()` when in LTR UI, as using LTR isolates seems uneeded when already LTR. This might avoid unforeseen side effects for LTR languages (safer for the coming up release, but we might then notice general wrapping issues only in RTL UI, so less quickly :)
- Better wrapping of RTL filename by using auto direction and LTR-isolating only the suffix so it's always on a side. That's option C in https://github.com/koreader/koreader/issues/5359#issuecomment-564767926, used in the screenshot below.
- menu.lua: handle `bidi_wrap_func` outside `getMenuText()`, which may be used in other contexts. See https://github.com/koreader/koreader/pull/5693#issuecomment-566240993.
- GetText/Bidi: wrap untranslated strings in LTR. See …
> [RTL UI] Bidi wrapping tweaks

- frontend/apps/filemanager/filemanager.lua
- frontend/device/android/device.lua
- frontend/device/generic/device.lua
Add an option to the filemanager "plus" menu to import files in current path using Android storage access framework.
The new menu entry will be displayed on Android 4.4+. Once the user select one or more files in the dialog these files will be imported on the specified folder.
Only supported mimetypes can be imported.
On folders *outside* the file sandbox the "import files here" entry will be disabled.
**Edit**: updated description and sample
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5686)
> android: import from Storage Access Framework

- frontend/ui/data/css_tweaks.lua
- frontend/ui/widget/confirmbox.lua
- reader.lua
- reader.lua: re-order touchScreenProbe() after CanvasContext. Should close #5717.
- ConfirmBox: prevent lower widgets from responding to tap: could happen when toggling Render Mode in the bottom menu, when we get the "Styles have changed in such a way... do you want to reload the document": taping on that text instead of the buttons would activate some other buttons in the bottom config menu hidden by that ConfirmBox :)
- Style tweaks: In-page footnotes: add some classic classnames: just adds `note2` and `note3`. Closes #5707.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5727)
> Various fixes (reader.lua, ConfirmBox, In-page footnotes style tweaks)

- frontend/apps/reader/modules/readerview.lua
- frontend/ui/data/koptoptions.lua
- frontend/ui/data/strings.lua
for request see https://github.com/koreader/koreader/issues/5656
Adds an option to select page gap in continuous mode. Option only shows up on documents that have numbered pages (.pdf, .cbz) because i think there is not much use to this option when reading arbitrarily paged documents. If seen necessary same logic can be duplicated for .epub files.
koptoptions.lua handles user selection and saving that selection
ReaderView:readSettings() handles reading previously selected option when opening book
ReaderVİew:onPageGapUpdate() renders changes when selection made
Page gap is same in both landscape and portrait modes, I think adding different settings for both is little unnecessary. 
The options for gap is 0, 8, 16 and 32, default one before was 8.
commit log
> 
> page_gap setting on opening …
> Option to change page gap in continuous mode

- .ci/after_success.sh
If only 1 line changed, it's just the timestamp. Otherwise every commit in the main repo will result in a useless one in koreader/koreader-translations, such as <https://github.com/koreader/koreader-translations/commit/eadc9f133a850361d2f532099aad248ac106f14c>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5734)
> [chore] Prevent useless POT updates

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/device/android/device.lua
Most users can call it from the developers menu:
On some devices, where KOReader doesn't work at all, it can be called using adb with:
`adb shell am start -n org.koreader.launcher/.EPDTestActivity`
Fixes #5730 too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5737)
> android: call EPD test from within KOReader

- frontend/ui/otamanager.lua
Requires https://github.com/koreader/android-luajit-launcher/pull/215
Fixes #5731 
If the device is borked and fails to download using DownloadManager show a confirmBox to retry using the browser.
See how it works/looks (simulated because I don't have any borked device)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5738)
> android: OTA fallback using the browser

- plugins/evernote.koplugin/main.lua
The edited `netsh` command line had errors:
1- missing v4tov4 (or v6 variant)
2- should have `=` instead of `:`
3- typo in listen(ing)address and listen(ing)port
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5744)
> [plugin] fix netsh command

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/device/android/device.lua
- frontend/device/generic/device.lua
I'm an user of [Markor](https://github.com/gsantner/markor), an awesome markdown/text tool for android.
It has a Quicknote feature which is greeeat. Works with ACTION_SEND, so it is compatible with a lot of applications, including all web browsers. When a user shares text with markor and press "quicknote" he/she will return to the previous activity and the note will be stored in Quicknote.md.
See how it works with a browser:
It is extremely useful to do initial researching about a topic, at least for me. So I did the same with KO
It works exactly the same, but in my case I setup markor as my preferred app to send text from KO, so no application picker is shown.
This is kind of a one-user feature, but the share text can be repurposed for other uses: twitter?, whatsapp? I don't know.
--- …
> [android]: share text with other apps

- frontend/apps/filemanager/filemanagerconverter.lua
As pointed out by @comradekingu on <https://hosted.weblate.org/translate/koreader/koreader/en/?q=has:comment#comments> it looks like some translators have mistakenly interpreted this as a reduction in price.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5752)
> [i18n] Add translators comment about Markdown

- Makefile
- platform/kindle/koreader.sh
- platform/kindle/libkohelper.sh
Regression since #5715 (because I forgot to test with tarballs, and links be weird).
Also, pile on yet another stupid Kindle workaround to make sure an OTA update won't break the launcher script itself because of truncation, which would break the exit sequence, leaving the user with an apparently hung device, simply because the WM was never unpaused...
Yay Kindle. -_-"
Fix #5721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5758)
> Unbreak OTA on Kindle

- frontend/apps/reader/modules/readerfooter.lua
This patch fix problem with overwriting text in footer in `Show all at once` mode and when we select many items to show. When text is to wide we truncate it and end with ellipsis(...).
Now we can also set minimal width of progress bar (from 20% to 50% of screen size) in all at once mode.
Before:
After: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5757)
> Prevent overwriting text in footer

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerlink.lua
- frontend/apps/reader/modules/readertypeset.lua
Includes https://github.com/koreader/crengine/pull/325 :
- lvtinydom.cpp: fix Use-after-free
- lvtextfm: fix/cleanup lastnonspace code bits
- lvtextfm: fix vertical-align: top & bottom
- renderBlockElementEnhanced: minor fixes related to floats
- renderBlockElementEnhanced: compute baseline of block
- Add support for display: inline-block/inline-table
- Better selection highlighting by using getSegmentRects(). Closes #5735
- getHtml(): add flag to get text soft-hyphenated
cre.cpp: toggable text selection highlighting method, default to the new one using segments. https://github.com/koreader/koreader-base/pull/1030
Update various cre flags to use the new features (and to conform with some flags re-ordering):
- support display: inline-block in flat, book and web render modes. Screenshots in …
> bump crengine: support inline-block, better text selection

- plugins/evernote.koplugin/main.lua
When multiple bookmarks exported Koreader shows following message/error:
This PR removes `all_count == 1` check (holds `false` with multiple books). 
I guess it was added to decide which message to display but string template already does that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5765)
> fix, confusing info/error message when exporting bookmarks

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/document/credocument.lua
- frontend/ui/widget/opdsbrowser.lua
Optimise usage of some of CreDocument methods by caching their results, either globally, or per page/pos for those whose result may depend on current page number or y-pos.
This helps a lot on cre books with a lot of highlights. More info in https://github.com/koreader/koreader/issues/5766#issuecomment-574410890.
Currently off by default, can be enabled via File browser > Developer options. Please do so to help testing it. We'll see how it does before enabling it by default.
Also adds OPDS for https://gallica.bnf.fr (not super interesting, but I was testing it, found some possible bug in their output, and added some "fix" to workaround it, so, might as well add it to the list to justify the fix :)
--- …
> cre: add toggable crengine call cache

- frontend/apps/filemanager/filemanagershortcuts.lua
Close: #5759 
Chooser in folder shortcut should show or hide hidden dirs based on current settings in FM (`show hidden files`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5785)
> Show or hide hidden folders in folder shortcut chooser

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/ui/widget/bookstatuswidget.lua
- frontend/ui/widget/footnotewidget.lua
- frontend/ui/widget/keyvaluepage.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
Gives the book language to Text*Widget (and XText) when drawing title, authors and other metadata text (mentionned at https://github.com/koreader/koreader/pull/5696#issuecomment-570739039).
Might be needed to properly display a Japanese book title when the UI language is Chinese when the glyphs are different.
The following 2 books have the same UTF8 text in their metadata title and authors, but a different language - our CJK font would default to the chinese glyphs (but it does contain the japanese glyphs, and Harfbuzz will use them when we tell it to):
<kbd>![image](https://user-images.githubusercontent.com/24273478/73005438-42871c00-3e09-11ea-95a4-3acb1cc87291.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/73005533-664a6200-3e09-11ea-9825-2f2f1f718000.png)</k …
> Render metadata text with book language

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/device/generic/device.lua
Mainly by ensuring we actually *always* remember it properly in a book sidecar, and that we support it in ScreenSaver mode, as well as in the FM.
This basically makes the whole "lefty" workflow consistent, without any spurious rotations back to Portrait.
Landscape is another kettle of fish, because the FM doesn't support it (and neither do image ScreenSaver modes).
Fix #5772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5783)
> Make Inverted Portrait a first-class citizen

- frontend/apps/reader/modules/readerfooter.lua
Close: #5778 
Minimal progress bar in footer can be now from 5% to 50%. Before 20%-50%.
Settings: `Status bar -> progress bar -> Minimal width`
Regression from #5757
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5788)
> Extend minimal progress bar width to 5%

- frontend/ui/data/keyboardlayouts/ar_AA_keyboard.lua
Fixes #5792
change Del/Backspace & Enter from icons to glyphs
this was done for all other keyboards between when #5569 was opened and merged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5793)
> fix arabic keyboard to conform to #5639

- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readergesture.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerlink.lua
- frontend/apps/reader/readerui.lua
- frontend/ui/widget/container/inputcontainer.lua
The lack of proper "overrides" could make their order/precedence/priority non-deterministic.
Issued described at https://github.com/koreader/koreader/pull/4878#issuecomment-577371343 - but this PR does not exactly set them as I proposed there :)
I had quite a hard time following the flow, having it not working at all with circular override, having to decide where to break it :) and hopefully, making it consistent.
So, not describing right now what's the ordering/priorities: I put in some comments, please have a look and see if the way you read it and understand it make sense :)
(I let in some `print()` because it's not the first time I had to use that - and so probably not the last time :)
--- …
> Reader: strict ordering of tap & hold gestures

- plugins/evernote.koplugin/main.lua
- spec/unit/evernote_plugin_main_spec.lua
When using txt export with multiple books koreader produces an output like this: [bugged_exports.txt](https://github.com/koreader/koreader/files/4073633/bugged_exports.txt) Only first entry has clippings. fixes https://github.com/koreader/koreader/issues/3690
On every `booknotes` `:exportToTXT()` compares `booknotes.time` with file modification time. After first run this modification time is updated to current time, then comparison returns false. 
I think idea behind it was a .txt file for every book without using flag like `exported_stamp`. Or an artifact from here: https://github.com/koreader/koreader/blob/b111ccc2b803fc78425d9791fcc8bb7a9a704e6e/frontend/apps/reader/modules/readerhighlight.lua#L1134-L1136
Solution
I think best solution here is rewriting .txt file everytime. To append …
> [fix, plugin] Evernote exporter only writes one documents clippings when txt export used, rest is ignored

- frontend/ui/data/keyboardlayouts/tr_keyboard.lua
- frontend/ui/widget/virtualkeyboard.lua
Pretty much self explanatory. I tried to imitate layouts used by mobile phones. 5th and 6th levels of added keys feature Kurdish and Azeri characters. Also added a commented part to make top row 10 key rather than standart 11 key row.
Since keyboard layouts gets their name from language locale names, it shows up as "Türkçe" which commonly refers to F layout. Just writing here to be safe in case anybody complains in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5795)
> Add turkish q keyboard layout

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/document/credocument.lua
- frontend/ui/data/css_tweaks.lua
- frontend/ui/wikipedia.lua
See https://github.com/koreader/crengine/pull/326 for details and screenshots (including some about the added style tweak purpose, and galleries in wikipedia EPUBs).
The wikipedia gallery CSS solution is a bit hacky :) but I had a hard time getting them as I wanted, and this trick seems quite fine, and survives render mode change without the need for reloading the book.
(A bit saddened after I had cleaned up the HTML tweaking code and removed these `:gsub()`, as they were kinda my syntax reference when I needed to write a complex one :) I'll have now to dig them out from git history.)
Also includes:
MuPDF: switch fallback font from FreeSans to FreeSerif.  https://github.com/koreader/koreader-base/pull/1033
Bump LodePNG to 2020/01/20. https://github.com/koreader/koreader-base/pull/1032 …
> Bump crengine, "Enforce steady line heights" style tweak, Wikipedia EPUB tweaks

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/filemanager/filemanagersearch.lua
- frontend/ui/widget/opdsbrowser.lua
It's extremely confusing, as it has nothing to do with calibre catalogs,
which are actual things the user can generate manually.
What it's using instead is actually a metadata cache in a flatfile db
that's always present, as long as "Send To Device" was used to upload
the content to the device.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5813)
> Stop using the "calibre catalog" wording

- frontend/apps/reader/modules/readergoto.lua
- frontend/apps/reader/modules/readerstatus.lua
- frontend/ui/elements/common_settings_menu_table.lua
Allow `go to beginning` in end actions.
I Use this quite often
If anyone has any opinions where in the menu it belongs i am all ears, i put it at the end by default.
I would like to add `go to beginning` and `go to end` to the goto UI,
but i am not sure if to put it in the `goto` or `skim` menu.
please advise, as i am sure everyone has their own preferred UI look :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5814)
> end of document: add go to beginning

- frontend/ui/widget/filechooser.lua
An awful lot of effort was wasted getting attributes just for getting a count of the number of files/directories in subdirectories. Getting the count is pretty fast. Getting all the attributes is not, and in this context we don't even use the attributes.
See <https://www.mobileread.com/forums/showthread.php?t=327085> and <https://gitter.im/koreader/koreader?at=5e3ac3b9e8a838355918ba13> for discussion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5819)
> [fix] Don't waste time on dir/file attributes in subdirs

- frontend/ui/widget/opdsbrowser.lua
OPDS catalogs may have search query capabilities. It is very usefull to find a
book in huge catalog, even when they are organized as directories. This commit
provides the possibility to add a %s mark in an OPS catalog URL, that would
trigger a search box when browsing the OPDS in koreader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5823)
> Add “searchable” capabilities to OPDS catalogs

- frontend/ui/widget/filechooser.lua
Apparently there's less overhead this way.
See https://github.com/koreader/koreader/pull/5819 for context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5827)
> [chore] FileChooser: use "traditional" for loop for ~20% better performance

- frontend/device/remarkable/device.lua
- platform/remarkable/koreader.sh
First change just removes some unnecessary code as pointed out by @NiLuJe in the original remarkable support pull request.
Second change is quite important but I don't quite understand the reasoning for the code in `reader.lua` which requires it. If you look at the if statement in `reader.lua` starting at line 239, you can see that if no argument is passed, *and* no `lastfile` setting is set then koreader will just exit with the usage help output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5834)
> A couple of minor remarkable port fixes

- frontend/ui/otamanager.lua
- platform/common/spinning_zsync
Instead of the blind spinner we used to have.
This is a bit of a hack (on both sides), and it currently extends towards the middle of the screen, which means the tail end of it will probably get overwritten by the "Success/Failure" popup.
Can easily be tweaked later, I'd like to get it in as-is to try it for real first ;).
Requires https://github.com/koreader/koreader-base/pull/1038
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5824)
> Print zsync2's output on screen

- frontend/ui/uimanager.lua
c.f., https://github.com/koreader/koreader-base/pull/1039#issuecomment-583494496
Generally affects `setDirty(nil, "full")`, the vast majority of which are indeed diagonal swipes. There are a few stray other uses where this still does make sense ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5836)
> Honor dithering on diagnoal swipe refreshes

- frontend/ui/wikipedia.lua
Includes https://github.com/koreader/crengine/pull/327 :
- (Upstream) Fix potential segfault
- lvtextfm: avoid spurious spaces when hyphenating (bis)
- View HTML: cosmetic fixes for floats and inline blocks
- Text: avoid clipping of overflowing inline-block content
- Fix images with "display: inline-block" not shown
- elementFromPoint(): skip moved-down block floats
- Rend methods init: fix inconsistency when floats disabled
- getRectEx(): don't crash in case of rend method bug
- getRenderedWidths(): slightly better estimate table width
- Tables cells: handle vertical-align: baseline
- Page splitting: add missing 'discard at start' handling
- Page splitting: split single column tables by lines instead of row
- Hardcoded elements list: add `<legend>`
- Drawing: fix some y/y+h vs page …
> bump crengine: various table and other fixes

- platform/kobo/koreader.sh
- platform/remarkable/koreader.sh
Not quite sure how this happened on @Frenzie's device, but in any case, skipping fbdepth in this case was nonsensical ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5841)
> Don't bypass fbdepth when starting KOReader @ 8bpp

- frontend/ui/widget/opdsbrowser.lua
The "author:" prefix looks like some kind of special search syntax, but it doesn't seem to be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5851)
> [chore] Add translator comment for Alexandre Dumas

- doc/Porting.md
I found this was a big stumbling block for me when porting to remarkable. I couldn't see any documentation on how these FFI Lua files were generated, so I added some where I expected to find in. Maybe there is some somewhere else which I missed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5808)
> Add some basic info on using ffi-cdecl

- frontend/ui/widget/container/inputcontainer.lua
- frontend/ui/widget/overlapgroup.lua
- plugins/statistics.koplugin/calendarview.lua
- plugins/statistics.koplugin/main.lua
Because KOReader knows what you read last summer 😬
and when you get old, you don't anymore. So, this should help us remembering, and give us an interesting view of our reading activity.
<kbd>![image](https://user-images.githubusercontent.com/24273478/74336103-f0993c80-4d9d-11ea-90cc-528babfc8289.png)</kbd>
Books are vertically ordered by reading duration in that day (but continuations from previous days override that), and when there are more than 3, there's a little `+2` above, and tap/hold on that day open the classic Statistics book per day list view.
The bottom of each day shows some histogram of reading duration per hour, so one can know when a book kept it awake at night, or when he had a day off work.
No setting, but if needed, stuff is already there to specify starting day of week …
> Statistics: new Calendar view

- frontend/ui/widget/filechooser.lua
as per https://github.com/koreader/koreader/issues/5843#issuecomment-585531475
better implementation of #5846 
never count `.sdr` directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5858)
> file count: Fixes #5843

- frontend/ui/widget/dictquicklookup.lua
The default left margin on blockquote and dd is `40px`. There are two potential problems with this:
1. 40px is a lot on a small font and perhaps rather little on a large font. Conversely, *if* blockquote font size were variable you'd get strange differences in indentation. `rem` should be a better choice.
2. <del>We don't interact with MuPDF quite as I believe we should (cf., the way I implemented this stuff with layoutDocument for opening EPUB/FB2 with MuPDF). While effectively the same problem, the distinction is that point (1) is real but nevertheless largely academic, while this point constitutes a very real problem both on DPIs over ~300 and under ~200.</del><ins>Actually there may be some MuPDF issue involved.</ins>
For problem (2) this may be a bit of a quick & lazy fix, but …
> Make dictionary margin depend on font size

- frontend/apps/reader/modules/readerfont.lua
- frontend/ui/data/css_tweaks.lua
- frontend/ui/widget/footnotewidget.lua
- frontend/ui/widget/touchmenu.lua
Show only 5 fonts by menu page to get more room below to see how the text looks with the selected font. Not sure everybody will like that (needs to extend your thumb more to browse menu pages), but the net effect is that you see the font and don't need to close the menu as previously to appreciate how it looks, and go back re-opening that menu to test another font.
<kbd>![fontmenu](https://user-images.githubusercontent.com/24273478/74511846-31609500-4f07-11ea-94b4-2b515a91adf4.png)</kbd>
Re-organize style tweaks into more submenus to also get more room below.
Add a few styletweaks: "No indentation on first/following paragraphs" https://github.com/koreader/koreader/pull/4358#issuecomment-585591943, "Paragraphs margins and paddings", and Links underlining.
Popup footnotes: some CSS fixes …
> Fonts, Style tweaks: smaller menus to see more of the book

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/modules/readerdictionary.lua
- plugins/statistics.koplugin/main.lua
So that Statistics settings modified while in FileManager are saved.
Also allows resetting statistics when in FileManager (where there is no current book id to exclude).
Issue reported at https://github.com/koreader/koreader/pull/5867#issuecomment-586911339.
I decided to have FM do a `self:handleEvent(Event:new("SaveSettings"))` - as that seems logical to have - even if currently, the only imported stuff in FM that has it is the Statistics plugin - and ReaderDictionnary that I had to fix to not fail when no document.
So, a bit risky, but we'll see if side effects.
The alternative would have been to just have StatisticsManager call its own saveSettings() on each UI setting widget action (which is what it did before with the old single setting) - which would have been less risky.
---
This …
> FileManager: tell plugins to save settings on close

- plugins/coverbrowser.koplugin/bookinfomanager.lua
Fix little util/ffiutil misuse in the last addition in #5816.
(Too many `util.` expecting it to be `ffi/util.lua` to change them all to `ffiutil`. or `BaseUtil.`.)
Closes #5873.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5874)
> CoverBrowser: fix "Extract and cache" crash

- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/screen_color_menu_table.lua
- reader.lua
Can happen if a user imports settings from a color device (see today's discussion with @ptrm on gitter ;)).
Also, make sure the "Color rendering" checkbox is actually available in these instances ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5871)
> Warn if color rendering is enabled on a grayscale device.

- frontend/ui/widget/textboxwidget.lua
Don't display a tofu glyph when meeting a tab (none of our fonts have a glyph for it).
New parameter: TextBoxWidget.tabstop_nb_space_width, that defaults to 8, to ensure tabstops in the usual left aligmnent.
Needs a bump for base/xtext.cpp https://github.com/koreader/koreader-base/pull/1049.
Closes #5837,
Defaulted to 8 spaces, because our spaces are really small and 4 was really tiny.
Also, only for TextBoxWidget - makes no real sense in TextWidget that hopefully only gets our own text or filenames.
I initially thought: why bother? as all our input is mostly tab-free (most dictionaries, Wikipedia, Google translate results, our own Lua code), except, as seen, some dict - and possibly some text files edited with TextEditor.
So, well, let's have a go: if it's not handled correctly, or the …
> TextBoxWidget: handle tabs and tabstops

- frontend/apps/reader/modules/readerview.lua
- spec/unit/readerlink_spec.lua
- spec/unit/readerview_spec.lua
in scroll_mode allow visible area to be larger than one page
allows proper scrolling on tall aspect ratios. Fixes #5876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5885)
> continuous: do not limit visible area to page area

- frontend/ui/elements/screensaver_menu.lua
- frontend/ui/screensaver.lua
Adds a screensaver mode which is just a line of text at the top of the screen. Purpose is to be minimally obstructive while still displaying something to indicate the device is asleep.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5739)
> add "message at top of screen" screensaver

- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readertypeset.lua
- frontend/docsettings.lua
- frontend/document/credocument.lua
- frontend/ui/data/css_tweaks.lua
- frontend/ui/widget/confirmbox.lua
Will need a base bump for https://github.com/koreader/koreader-base/pull/1054:
Includes https://github.com/koreader/crengine/pull/328 :
- Fix shifted native selection/internal bookmarks in legacy mode
- Fix drawing of inline-block taller than page height
- (Upstream) createXPointer/toString: normalized xpointers
- toStringUsingNames(): rename to toStringV2()
- DOM_VERSION_WITH_NORMALIZED_XPOINTERS 20200223
- CSS/List items: skip boxing elements when walking
- CSS: parse pseudoclass nth_child(3n+2)
- toStringV2(): output [1] when first but not single
- Tables: complete incomplete tables
- Store gDOMVersionRequested in cache file header
- Cache: increase Rects cache size
cre.cpp: adds `getDomVersionWithNormalizedXPointers()` and `getNormalizedXPointer(xpv1)`
When opening a book previously …
> bump crengine, migrate books to normalized xpointers

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/document/pdfdocument.lua
Fixes #5881
Poor atempt to fix issues with read-only pdfs, when auto or manual save settings is triggered. I don't like it because it adds UI stuff to a document. Probably there are better ways of doing this without messing with InfoMessages in pdfdocument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5889)
> avoid writting to read-only pdfs

- frontend/apps/reader/modules/readerlink.lua
- frontend/document/credocument.lua
- frontend/ui/data/css_tweaks.lua
- frontend/ui/widget/footnotewidget.lua
Will need a base bump for https://github.com/koreader/koreader-base/pull/1055.
Includes https://github.com/koreader/crengine/pull/329 :
- toStringV2(): fix when target node is a boxing node
- CSS font-family parsing: set usual default of sans-serif
- FB2 footnotes: fix spurious newline ("display: run-in")
- FB2 footnotes: disable hardcoded handling as in-page
cre.cpp: accepts classic FB2 footnotes in footnote popup detection
Make FB2 footnotes behaviour consistent with what we have for footnotes in EPUB:
- FB2 footnotes are no more rendered in-page by default
- In-page rendering can be enabled by the added Style tweak
- FB2 footnotes can also show in footnote popup (with some added not-so-nice CSS so MuPDF can render them as crengine)
`cre: setFontFace(): increase bias given to the main …
> bump crengine: normalized xpointers fix, FB2 footnotes tweaks

- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/ui/data/css_tweaks.lua
Set these 2 tweaks as default global tweaks for new users (and existing users that have not set any global defaults).
One can disable them by long-press on each of them.
Only per-specs EPUB and FB2 footnotes (other in-page footnotes tweaks may trigger on non-footnote content on some books, so let enabling them be a user decision).
Discussed at https://github.com/koreader/koreader/issues/5015#issuecomment-592609337
So, (mostly) everybody will get:
<kbd>![image](https://user-images.githubusercontent.com/24273478/75568621-e93b8980-5a53-11ea-8c21-5a430f24b244.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/75568590-da54d700-5a53-11ea-9f2d-2f293f77ab2b.png)</kbd>
--- …
> Style tweaks: enable EPUB/FB2 in-page footnotes by default

- frontend/apps/filemanager/filemanagershortcuts.lua
- frontend/ui/widget/pathchooser.lua
Rework #5785: `show_hidden` was fetched from G_reader_settings in new/extend(), so it kept the value it got on its first use/require. This just makes PathChooser pick it from G_reader_settings in PathChooser:init(), so on each instantiation - so we always get the current up to date value (https://github.com/koreader/koreader/issues/5919#issuecomment-595885460).
Closes #5919: fix crash when FileManagerShortcuts is called from outside File browser, e.g. from Reader via a gesture.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5923)
> PathChooser: fetch 'show_hidden' setting on each use

- frontend/apps/reader/modules/readerrolling.lua
Because dismissing it by tapping outside would have "not for this book" selected, which is the least welcome action...
Details at https://github.com/koreader/koreader/pull/5897#issuecomment-596209498.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5931)
> Make xpointers migration ConfirmBox non-dismissable

- frontend/apps/reader/modules/readerlink.lua
Only borked ones were supported. The new behavior mimics Firefox.
The following incorrect varieties will be treated the same as the correct `file:///tmp/test.txt`.
* file:/tmp/test.txt
* file://tmp/test.txt
Fixes <https://github.com/koreader/koreader/issues/5941>.
See <https://github.com/koreader/koreader/issues/5941#issuecomment-598633973> for discussion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5945)
> [fix] Support proper local links

- frontend/apps/reader/modules/readerdictionary.lua
#5955 
So I just combined the first two titles on the first page. This saves space and allows three complete dictionary entries to fit one page. This works on Kindle PW3, I don't know about other screens.
Please have a look:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5960)
> More compact dictionary download window

- frontend/ui/data/css_tweaks.lua
- frontend/ui/widget/footnotewidget.lua
Includes https://github.com/koreader/crengine/pull/330
- FB2 footnotes: disable hardcoded handling as in-page 2
- CSS: also support gray colors spelled "grey"
- Text: move past floats when wide image or inlineBox does not fit
- Fix list item marker clipping check
- Ensure nodeDisplayStyleHash change when boxing prevented by cache
- Text: adds LFormattedText.is_reusable
- Handle block elements inside inline element
- Fix getBookmark() on multi-pages embedded block
- (Upstream) Support raw picture in RTF
- (Upstream) Fixed integer overflow in cache size calculations
- Add libCURL's CA bundle to the ignore list https://github.com/koreader/crengine/pull/332
- FB2 footnotes: fix setBoxingWishedButPreventedByCache() https://github.com/koreader/crengine/pull/333
- fb2.css: handle …
> bump crengine: handle block elements inside inline element

- frontend/device/cervantes/device.lua
- frontend/device/kobo/device.lua
Regression after https://github.com/koreader/koreader-base/pull/1047 (I
thought it was already implemented).
Fix #5963
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5966)
> Unbreak nightmode on Cervantes

- plugins/statistics.koplugin/main.lua
when enabling statistics while reading a new book.
if you then click on `current book` koreader crashes as `avg_time` is nill
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5971)
> fix current book on statistics enable

- frontend/apps/reader/modules/readerhighlight.lua
More generally: switch to the page that contains the highlight edge that we are currently moving.
Closes #5973.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5984)
> Highlights: turn page when start or end crosses pages

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readergoto.lua
- frontend/apps/reader/modules/readerpagemap.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/apps/reader/modules/readertypeset.lua
- frontend/apps/reader/readerui.lua
- frontend/apps/reader/skimtowidget.lua
- frontend/document/credocument.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/widget/textboxwidget.lua
bump crengine: support for EPUB3 nav toc and page maps
Includes https://github.com/koreader/crengine/pull/336
- Fix lvRect:isRectInside(rc) with 0-width or 0-height rect - closes #5991
- TOC: parse EPUB3 nav toc, fallback to spine when no toc - closes #4915
- Parse and cache various hardcopy page list maps
- epub.css: hide EPUB3 <span epub:type="pagebreak"> content
cre.cpp: add a few PageMap helper functions.
Adds ReaderPageMap which will add a new menu (under TOC and Bookmarks) that will allow:
- to list source page numbers (like a TOC)
- to show visible page labels in the right margin
- to use these source page numbers in the footer, the TOC, the GoTo and SkimTo widgets, and to use the source page number in the standard bookmark and highlight initial text.
- (and to unwontfix and close …
> Adds ReaderPageMap, to optionally show source pages numbers

- frontend/device/kindle/device.lua
Because apparently stuff blows up in weird and interesting ways for...
reasons.
Might be relevant on older PB devices, too?
Re #5780
Closes #6024
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6025)
> Workaround more weird XText/HB issues on Kindle armv6

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/modules/readergesture.lua
- plugins/statistics.koplugin/main.lua
Add a gesture action to show Statistics calendar view - because I realised I was hitting that menu too often :)
Also flush statistics to DB when showing it, so we see the last minutes/hours reading in the hourly histogram.
Also: File browser: sane fallback when home_dir invalid or missing - see https://github.com/koreader/koreader/issues/6026#issuecomment-610856059
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6035)
> Gestures: add action "Statistics calendar view"

- frontend/apps/reader/modules/readerfont.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/device/sdl/device.lua
- frontend/document/canvascontext.lua
- frontend/fontlist.lua
- frontend/ui/elements/font_settings.lua
- frontend/ui/widget/touchmenu.lua
The emulator will still show the battery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6040)
> desktop: disable battery on touch menu and reader footer

- plugins/statistics.koplugin/main.lua
Which could cause a same book appearing multiple times as different entries in statistics.
More details in https://github.com/koreader/koreader-base/pull/1077#issuecomment-613353913
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6052)
> Statistics: fix md5 leaking between newly opened books

- frontend/apps/reader/modules/readerhyphenation.lua
- spec/unit/readerlink_spec.lua
Includes https://github.com/koreader/crengine/pull/337 :
- Fix a few clang-tidy warnings
- Add support for <img src="data:image/png;base64,...> - Closes #5529.
- XML parsing: add more HTML5 named entities, optimize search
- Text: fix standalone BR not making an empty line
- Fix BR with "display: block" not making an empty line
- Fix hyphens from soft-hyphens not part of highlighted segments
- Use libunibreak for line breaking
- Adds TextLangMan for text typography by language
- Force BR to always be display:inline https://github.com/koreader/crengine/pull/338
Tweak ReaderHyphenation to work with the new TextLangMan (even if it will be replaced soon by ReaderTypography).
(Removed uneeded onUpdateToc() which were useless as they were done before the new rendering - another one was done …
> bump crengine: text typography by language

- frontend/apps/reader/modules/readerfont.lua
- frontend/document/credocument.lua
Includes https://github.com/koreader/crengine/pull/339 :
- Simplify libunibreak includes
- Text: fix read/write outside array bounds
- lvtextfm: dont adjust space after initial quotation mark/dash (rework)
- Fonts: allow providing and using multiple fallback fonts
Users can set their prefered fallback font, which will be completed with a few of our shipped fonts for maximum coverage.
Ref https://github.com/koreader/koreader/issues/5277#issuecomment-525847129. Closes #5277.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6090)
> bump crengine: multiple fallback fonts

- frontend/ui/widget/textboxwidget.lua
- frontend/ui/widget/textwidget.lua
bump crengine: fix wrong usage of Harfbuzz y_offset https://github.com/koreader/crengine/pull/340
Same in TextWidget and TextBoxWidget.
Noticable with nastaliq arabic fonts, see https://github.com/koreader/koreader/pull/6090#issuecomment-619418198 :
<kbd>![image](https://user-images.githubusercontent.com/24273478/80290807-45671500-8748-11ea-8009-bd5ed5fd2364.png)</kbd> => <kbd>![image](https://user-images.githubusercontent.com/24273478/80290812-52840400-8748-11ea-8494-118698664fca.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6093)
> Text widgets, crengine: fix wrong vertical positionning

- frontend/apps/reader/modules/readerfooter.lua
See: #5969 
New option in Status bar -> Settings
`Lock tap status bar` (mayby better name?)
When we enable it - tap on status bar is disabled (locked)
Close: #5969
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6083)
> Option to prevent tap on status bar

- plugins/evernote.koplugin/main.lua
Tested in a Boox Max Carta.
The purpose (for me) of having JSON formatted clippings is that they are easy to parse, and then convert to org mode format, which is the format I am interested in.
I tried exporting html and converting to org with pandoc, but the result didn't please me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6067)
> Add export to JSON option in Evernote plugin. Sort requires in Evernote plugin sources.

- frontend/apps/reader/modules/readerfont.lua
- frontend/document/credocument.lua
- frontend/ui/elements/font-test-sample-default.html
- frontend/ui/elements/font_settings.lua
Allow toggling the use of multiple fallback fonts (#6090).
Might be handly when testing new fonts or choosing the first fallback font - when you really want to see what a font supports.
I've put it at the bottom of the font menu (if will be alone, the last one is optionnal):
<kbd>![image](https://user-images.githubusercontent.com/24273478/80306994-c1a03d80-87c6-11ea-8176-915580c11384.png)</kbd>
Dunno if it's better if it was at start (with the Font settings that is not shown on most devices - or inside it, which would made this menu shown on all devices, so with a single item on most devices):
<kbd>![image](https://user-images.githubusercontent.com/24273478/80307050-10e66e00-87c7-11ea-8932-c1c511a5401e.png)</kbd>
InfoMessage shown on long-press (for rewording suggestions): …
> Allow toggling use of additional fallback fonts

- plugins/movetoarchive.koplugin/_meta.lua
- plugins/movetoarchive.koplugin/main.lua
Mismatches in these names prevent this plugin from being disabled'able. https://github.com/koreader/koreader/pull/6101#issuecomment-623131390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6113)
> [Plugin] Fix move to archive plugin names

- platform/kindle/koreader.sh
Because everything is terrible, and the fuse proxy can apparently still
manage to screw us over.
(Re: #6117)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6120)
> Tweak the post-OTA warning on Kindle

- frontend/apps/reader/modules/readerstatus.lua
don't rewrite the freshly deleted .sdr, when calling from the endaction popup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6108)
> close file before deleting

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/ui/elements/common_settings_menu_table.lua
Also add "Fulltext search" as an option for highlight action.
See https://github.com/koreader/koreader/issues/6111#issuecomment-623088751. Closes #6111.
@protist, in this [highlight_search_singleword.zip](https://github.com/koreader/koreader/files/4571118/highlight_search_singleword.zip) are the 2 modified files, if you want to confirm this works for you.
<kbd>![image](https://user-images.githubusercontent.com/24273478/80921250-84631f00-8d75-11ea-86fb-8d4dc0f1a6dc.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6114)
> Enable Highlight action on single word selection

- frontend/device/android/dictionaries.lua
There is no `mobi.goldendict.android.pro` app:
https://play.google.com/store/apps/details?id=mobi.goldendict.android.pro
It's `mobi.goldendict.android`:
https://play.google.com/store/apps/details?id=mobi.goldendict.android
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6127)
> Fix name for GoldenDict Pro dictionary

- Makefile
- platform/debian/changelog
- platform/debian/copyright
- platform/debian/do_debian_package.sh
- platform/debian/koreader.1
Follow-up to https://github.com/koreader/koreader/pull/4434#issuecomment-451219568
Fixed some errors and warnings. ~~I didn't care of warnings (there are soooo many)~~.
The mail address is a dummy address, feel free to suggest a change :p 
~~I didn't fix the `no-copyright-file` and `debian-changelog-file-missing` as I don't know how to fix them on non source debian packages.~~
The rest of errors left are:
`binary-or-shlib-defines-rpath` -> fixable during build
~~`unstripped-binary-or-object`-> fixable during build. I don't know why these are yet unstripped.~~
`embedded-library` -> not easily fixable without dismiss our own versions of libpng, libturbojpeg, libfreetype...
The whole list of remaining issues can be obtained running `lintian --no-tag-display-limit` against a debian package. …
> Debian - fix some lintian errors

- platform/kobo/koreader.sh
This works purely because busybox (GNU grep wouldn't stand for this ;p).
(c.f., http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/Kindle/Misc/zshenv#L39 for an explanation).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6147)
> Some more Kobo startup script tweaks

- frontend/device/sdl/device.lua
fix an issue caused by our LD_LIBRARY_PATH on some linux distros. The issue does look like:
```
/usr/bin/google-chrome-stable: symbol lookup error: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: hb_glib_script_to_script
/usr/bin/x-www-browser: symbol lookup error: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: hb_glib_script_to_script
XPCOMGlueLoad error for file /usr/lib/firefox/libmozgtk.so:
/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: hb_glib_script_to_script
Couldn't load XPCOM.
/usr/bin/xdg-open: 869: iceweasel: not found
/usr/bin/xdg-open: 869: seamonkey: not found
/usr/bin/xdg-open: 869: mozilla: not found
/usr/bin/xdg-open: 869: epiphany: not found
/usr/bin/xdg-open: 869: konqueror: not found
/usr/bin/xdg-open: 869: chromium: not found …
```
> fix openLink on linux

- frontend/apps/reader/modules/readerbookmark.lua
- plugins/statistics.koplugin/main.lua
Fixes issue noticed at https://github.com/koreader/koreader/pull/6052#issuecomment-629610275: no error log message anymore, and the number of highlights will be updated (and corrected if previously wrong because leaked from another book) to the number of highlights in the settings on each book opening. 
Note that the number of "Notes" shown does not mean much.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6173)
> Statistics: fix number of highlights

- frontend/device/sdl/device.lua
- frontend/device/sdl/dictionaries.lua
Like #5108 but for desktop.
* Add support for goldendict in Linux and Mac
* Add support for apple dictionary on Mac.
Users can also add other dictionaries, which will be appended in the list. Both commands and urls work.
```lua
return {
{ "MerriamWebster", "Merriam-Webster", false, "https://www.merriam-webster.com/dictionary/" },
{ "Wolfram", "WolframAlpha", false, "https://www.wolframalpha.com/input/?i=" },
{ "Qstardict", "QStardict", false, "qstardict" },
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6167)
> desktop: add support for 3rd party dictionary apps

- platform/kobo/koreader.sh
It's a big pile 'o RAM we could use.
Plus, it might be causing bad interactions with DRM on Nickel restart if we keep it around.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6179)
> Kill the RMSDK, too.

- frontend/apps/reader/modules/readerrolling.lua
- frontend/document/credocument.lua
Includes https://github.com/koreader/crengine/pull/344 :
- Don't reset invisible BR to display: inline https://github.com/koreader/koreader/issues/6152#issuecomment-629241554
- ldomTextCollector: handle inline-block/table as inline
- Avoid re-rendering on font hinting mode change
- List markers: fix positionning when floats involved
- GIF decoding: avoid uneeded abort on LZW table overflow
- Adds getUnknownEntities(), can help with debugging
- Don't check stylesheet hashes when loading from cache
- Hardcoded elements and attributes list: cleanup
- Full rendering: 2 small optimisations
- Strut confinning: deal with images earlier
- lvtextfm: some cleanup and reordering
Also includes:
- cre.cpp : fix getPageFromXPointer() and getPosFromXPointer() to not fail on invisible nodes and work on …
> bump crengine: various fixes, tweaks and cleanups

- frontend/ui/widget/keyvaluepage.lua
- plugins/statistics.koplugin/main.lua
Fix wrong values for books opened (or first opened) from April 14th to May 20th: highlights and notes
possibly being NULL was preventing nb of pages and last_open from being fetched.
Details in https://github.com/koreader/koreader/issues/6190#issuecomment-633693940. Closes #6190.
Also fix paren issue noticed at https://github.com/koreader/koreader/issues/6181#issuecomment-633696209. Closes #6181.
Also re-order current book and all books stat items to some hopefully more sensible order.
That's quite subjective, so opinions welcome.
I let you look at the current order on your device.
Proposed new order (and some renames):
`Statistics > Current book`:
<kbd>![image](https://user-images.githubusercontent.com/24273478/82950996-b21f3a80-9fa6-11ea-9ad1-d5b4484fc68f.png)</kbd>
`Statistics > Time …
> Statistics: some fixes, reorder book stats fields

- frontend/readhistory.lua
- frontend/ui/wikipedia.lua
Internal `self.hist` being an array, iterating it with `pairs` could have some strange effects. Best to use `ipairs`. See https://github.com/koreader/koreader/issues/6201#issuecomment-635291450 . Closes #6201
Also includes: Wikipedia EPUBs: keep links in bold text bold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6209)
> History: fix possible issues when saving and loading

- frontend/apps/reader/modules/readerfooter.lua
Iterating a k/v table as an array would have us stopped on the first disabled MODE (frontlight, battery... on some devices). Details at https://github.com/koreader/koreader/issues/6210#issuecomment-636132193. Closes #6210.
Rework that initial setup, and make it correctly handle added or removed MODEs when using the ordered items saved in the user settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6212)
> Footer: fix items possibly missing

- frontend/device/kobo/device.lua
Depends on https://github.com/koreader/koreader-base/pull/1106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6211)
> Disable the RTC alarm on shutdown

- frontend/apps/reader/skimtowidget.lua
Next/prev bookmark was not updating the widget (progress bar and current page number did not change when jumping bookmarks). Probably since #5968.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6216)
> SkimToWidget: fix next/prev bookmark not updating it

- frontend/apps/reader/modules/readermenu.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/ui/widget/buttondialog.lua
- frontend/ui/widget/buttondialogtitle.lua
- frontend/ui/widget/focusmanager.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/touchmenu.lua
This is a quick exploration into how the new Device:hasFewKeys() method could work to make things more usable on very limited devices.
In the reader, the right is repurposed to open the menu. Left in turn closes it.
The same principle is applied to ButtonDialog. This means you can select anything in principle, but once you go right you can't go back.
References <https://github.com/koreader/koreader/issues/4029>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6195)
> [UX] Implement hasFewKeys prototype

- doc/config.ld
Otherwise it'll choke on the comments in that file.
See <https://github.com/koreader/koreader/pull/6195#issuecomment-638801075>.
Accidentally introduced in <https://github.com/koreader/koreader-base/pull/1105>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6229)
> [fix] Ignore sha2.lua in doc generation

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
- plugins/newsdownloader.koplugin/feed_config.lua
- plugins/newsdownloader.koplugin/main.lua
Works exactly as expected, requires [htmlparser luarock](https://msva.github.io/lua-htmlparser/) which I do not know now how to include.
I am open to any corrections/edits. This is my first Lua code so please be wary.
Solves #6185 . I have tested it on Kindle PW3 now, and it works surprisingly quickly with convoluted HTML of Reuters (by just throwing my local .luarocks to rocks directory 🤣 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6228)
> [NewsDownloader] Added an HTML filter through a CSS selector

- platform/kindle/extensions/koreader/menu.json
This should allow WhisperTouch support to stay enabled, allowing
consistent button behavior.
c.f., https://github.com/koreader/koreader/issues/6038#issuecomment-612564693
Fix #6038
(Requires today's KUAL build, Booklet only).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6233)
> Don't exit KUAL on the Voyage

- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/document/credocument.lua
- frontend/ui/data/css_tweaks.lua
Includes https://github.com/koreader/crengine/pull/345 :
- GIF decoding: avoid crash on some images - Closes #6215 
- Top progress bar: avoid re-computing when not needed - Closes #6191 
- Top progress bar: allow external filling of marks
- CSS/Text: properly inherit and handle text-align-last
- getRenderedWidths(): fix handling of text-indent
- Reorder some flags to make the sets clearer
- CSS: support more white-space named values
- Text: fix standalone BR not making an empty line (rework)
- CSS: support for pseudo elements ::before & ::after
- CSS: content: open-quote support via TextLangMan
- CSS/Text selection: adds a few "-cr-hint:" tweaks - (Can help with https://github.com/koreader/koreader/issues/6223#issuecomment-638834510 )
Also:
- cre.cpp: adds setHeaderProgressMarks() …
> bump crengine: support for pseudo elements ::before/after

- frontend/device/kindle/device.lua
We were missing the fancy extra white flash and landscape handling that
most every other eInk device gets ;).
(On non-SO devices, of course).
Fix #5724
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6240)
> Ensure feature-parity in ScreenSaver handling on Kindle

- frontend/apps/reader/modules/readerrolling.lua
It was causing a double-refresh on orientation change via ConfigDialog
I could only reproduce it on Kindle, for some strange reason (slower?).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6241)
> Remove a dodgy scheduleIn

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/ui/widget/inputdialog.lua
- frontend/util.lua
Allows editing a CSS snippet to be applied to this book only, without the need to create and edit a User style tweak.
Allows copying any other tweak CSS by just taping on it (and pasting into this with Hold).
Limit User style tweaks nb of items per menu page to 6 (like we try to do for other tweaks menus).
(Dunno if there's a better wording than "Book specific tweak" to make that clearer... "Book own tweak" ?)
<kbd>![image](https://user-images.githubusercontent.com/24273478/83997185-1e624c80-a95e-11ea-82e4-c5ff8feb672a.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/83997216-2e7a2c00-a95e-11ea-9dcd-6695e282d346.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/83997235-3a65ee00-a95e-11ea-8deb-13013922d975.png)</kbd> …
> Style tweaks: adds "Book specific tweak" menu item

- frontend/apps/reader/readerui.lua
- frontend/ui/data/keyboardlayouts/es_keyboard.lua
- frontend/ui/data/keyboardlayouts/fr_keyboard.lua
- frontend/ui/data/keyboardlayouts/tr_keyboard.lua
- frontend/ui/widget/virtualkeyboard.lua
`ReaderUI:setLastDirForFileBrowser(): remove trailing /`
Closes #6243 (untested though)
`Keyboard: better isolation of FR/ES/TR from EN base`
Fix some issue really noticable only with the FR keyboard, noticed at the bottom of https://github.com/koreader/koreader/pull/6244#issuecomment-640395594 :
`dofile()` wasn't enough to copy en_keyboard, as the references to key popups would still be shared, and hacks to them (as done by the FR keyboard) would be active on the EN keyboard.
Also, for the FR Keyboard:
- bring <kbd>M</kbd> key popup too when moving it to 2nd row.
- keep original <kbd>,</kbd> and <kbd>.</kbd> as on EN keyboard (as this is more useful and intuitive, even if not really AZERTY, but we didn't really have the 4 AZERTY bottom puncts in a row …
> Keyboard: better isolation of FR/ES/TR from EN base

- frontend/apps/reader/modules/readerstatus.lua
- frontend/ui/elements/common_settings_menu_table.lua
Keep showing the "mark as" option/button, though, because that one is a
toggle, it doesn't enforce the "read" status.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6256)
> Allow automatically marking the book as read on end of doc

- frontend/apps/reader/modules/readerfooter.lua
* Refresh the footer instantly when changing the prefix, separator, or formatting.
(Either that never worked, or it's an old-ish regression).
* Allow setting the container height (formerly DMINIBAR_CONTAINER_HEIGHT)
* Allow setting the container bottom padding (formerly 1 flex pixel)
* Refactor ReaderFooter:applyFooterMode
Handle toggling the genFooterText function even in all at once mode
Make sure the layout is properly reset when changing visibility state, to avoid inconsistencies with complex layouts.
* Allow taller progress bars in the footer (max = default * 4)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6257)
> A few footer tweaks

- plugins/wallabag.koplugin/main.lua
The MultiConfirmBox indicates which settings are still missing and offers you a quick way to get to them.
Cf. <https://github.com/koreader/koreader/issues/6129>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6262)
> [plugin, UX] Wallabag: aid with setting up missing information

- frontend/apps/reader/modules/readercropping.lua
- frontend/apps/reader/modules/readerfont.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/apps/reader/modules/readertypography.lua
- frontend/ui/translator.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/confirmbox.lua
- frontend/ui/widget/infomessage.lua
- frontend/ui/widget/multiconfirmbox.lua
- frontend/ui/widget/notification.lua
- frontend/ui/widget/textboxwidget.lua
My best guess is it's an artifact caused by the PxP alignment constraints...
The EPDC should *already* be taking care of this (c.f., epdc_process_update @ drivers/video/fbdev/mxc/mxc_epdc_v2_fb.c), but, apparently, something's still not *quite* right  ;).
TL;DR: If we request a HW dithered refresh, grow the rectangle ourselves until the alignment constraints are met.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6267)
> Fix partial HW dithered refreshes sometimes appearing to shift refreshed content

- frontend/device/android/device.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
Requires https://github.com/koreader/android-luajit-launcher/pull/233
Requires https://github.com/koreader/koreader-base/pull/1117
It is a workaround for #6263 but can be useful on some devices with erratic back key behaviour too (yep, Onyx)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6269)
> android: add a toggle to ignore back button events

- frontend/ui/widget/configdialog.lua
Revert bit from #6267 , see https://github.com/koreader/koreader/pull/6267#issuecomment-644903608.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6273)
> Fix bottom menu item titles truncation

- frontend/ui/elements/common_info_menu_table.lua
More tools is a submenu in the tools menu, not in the plugins menu. That everything in there happens to be plugins is merely a technical detail and not considered part of the unifying menu vision. Plugin management should be last as it is because it's only used once in a blue moon, if it should be in the tools menu at all. The same applies to settings more broadly. Putting plugin management in the tools menu is traditional, however.
Plugins should not and are not supposed to be most at home in the tools menu. Those plugins that happen to be in the tools menu are by and large there because that's where they fit best. Those that don't are new and I didn't have the heart or energy to make much of a fuzz about it provided they had a reasonable claim to the tools menu. That includes plugins …
> [chore] Rename 'More plugins' to 'More tools'

- Makefile
- afterupdate.marker
- platform/android/llapp_main.lua
Add the possibility to run *.sh scripts:
After an update of koreader all *.sh scripts in /sdcard/koreader/scripts.afterupdate are executed.
On every start of koreader run all *.sh scripts in /sdcard/koreader/scripts.always
This is a further development of the proposal of the pull request: #6253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6275)
> Startup Scripts

- platform/kobo/koreader.sh
Should take care of all the weird and interesting ways people manage to
find to break it...
NOTE: "$(dirname $(realpath "${0}"))" works, too, but I'm not sure if
really old devices ship with the realpath applet...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6283)
> More robust way to detect our own path on Kobo

- platform/android/llapp_main.lua
I've played a bit with #6275, to make the iterator available for non-power users too.
this PR automate user data migration (which happens once per update). If the folder `koreader/scripts.afterupdate` contains a file `migrate` then files will be copied to internal dir preserving their relative path. Thus user data **needs** to have the same hierarchy as internal directories.
Shell scripts will be find and run if the folder `koreader/scripts.afterupdate` exists and has no `migrate file`.
In the case of `koreader/scripts.always` there's no migration available, just shell scripts.
Digging a bit seems not possible to create new directories on app internal storage (it just crashes on the emulator since API25). So very fancy extensions are not supported, but it is ok to override files and …
> migrate user directories after update

- frontend/device/generic/device.lua
- frontend/device/kindle/device.lua
They're full-screen, and they work fine in Landscape.
re: #5724
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6286)
> Don't rotate BookStatus & ReadingProgress in screensavers.

- plugins/evernote.koplugin/main.lua
This makes the menu structure slightly clearer.
See <https://github.com/koreader/koreader/issues/2778#issuecomment-647324742>.
Pinging @Galunid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6294)
> [plugin] Add menu separators to Evernote menu

- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/ui/data/css_tweaks.lua
Includes https://github.com/koreader/crengine/pull/347 :
- Fix some non-recursive subtree walkers
- Text: skip formatting optimisations when inlineBoxes
- CSS parsing: parse selectors starting with [attrib]
- Use T="" for internal elements attributes
- CSS: re-order css_d_* (display) enum for easier checking
- Rendering methods: remove erm_table_cell
- Rendering methods: remove erm_table_caption
- Rendering methods: remove erm_list_item
- getRenderedWidths(): better estimate table width
- styleToTextFmtFlags(): adds is_block parameter
- Adds support for "display: ruby" and `<ruby>` elements
- Fix prev/next-VisibleWord-Start/End() with CJK text
Also:
- bump HarfBuzz to 2.6.8 https://github.com/koreader/koreader-base/pull/1122
- bump evernote-lua-sdk …
> bump crengine: add support for <ruby> elements

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/apps/reader/skimtowidget.lua
Was correctly done when jumping bookmarks via the Bookmarks menu and the SkimTo widget, but not from gestures. Details in https://github.com/koreader/koreader/pull/6259#issuecomment-642677750.  Supersede #6259.
Also prevent fillToc() on each page turn when book has no TOC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6306)
> Bookmarks prev/next via gestures: add location to stack

- frontend/device/pocketbook/device.lua
Cf. <#6311>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6312)
> Add PocketBook 614W (Basic 3) definition

- frontend/device/sdl/device.lua
- frontend/ui/network/manager.lua
Useful to test things that rely on network state changes, like #6299 
Probably useful to fix #6080
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6314)
> emulator: add fake network manager

- frontend/ui/widget/focusmanager.lua
There doesn't seem to be a reason not to, but it could be limited to `Device:hasFewKeys()` if desired.
Cf. <https://github.com/koreader/koreader/pull/6312#issuecomment-650207697>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6315)
> [feat] FocusManager: wrap around horizontally

- frontend/ui/widget/configdialog.lua
Follow-up to <https://github.com/koreader/koreader/pull/6195>.
Part of <https://github.com/koreader/koreader/issues/4029>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6318)
> [UX] Add left to close to ConfigDialog for hasFewKeys

- plugins/evernote.koplugin/main.lua
This sets default EvernoteOAuth logger introduced in https://github.com/koreader/evernote-sdk-lua/pull/4 to `DEBUG`, instead of default `print`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6308)
> EvernoteOAuth set logger

- spec/unit/document_registry_spec.lua
calling `docsettings:flush()` was causing the sidecar file to be recreated leaving garbage folders in the KOreader folder after running the tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6323)
> Tests: make sure files are deleted

- plugins/wallabag.koplugin/main.lua
Finished is a specific status distinct from 100% read.
Also reorganize the menus slightly.
Closes <#6316>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6320)
> [plugin] Wallabag: Make remove from history consistent with deletion

- frontend/dispatcher.lua
accessing the table via reference rather than copying the values was breaking the configdialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6324)
> Dispatcher: fix table

- frontend/apps/filemanager/filemanager.lua
- reader.lua
fixes issue discovered in #6347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6348)
> allow default FM rotation on init when `Keep FM rotation` is disabled

- frontend/device/android/device.lua
Native surface rotation is used on Kitkat+ devices. On devices with older versions and android Tv/ChromeOS blitbuffer rotation is still used.
Also bumps curl, fribidi and LuaJIT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6359)
> android: support for native surface rotation

- frontend/apps/reader/modules/readertoc.lua
- frontend/device/devicelistener.lua
- frontend/dispatcher.lua
- frontend/ui/elements/refresh_menu_table.lua
- frontend/ui/uimanager.lua
idea from #5079
allows setting night mode directly not only toggling it.
If the user has not set a separate refresh rate for night mode
the default one will be used, as was the previous behavior
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6386)
> SetNightMode event & Night Mode refresh rate

- frontend/device/devicelistener.lua
this is what happens when i do things too quickly :)
they both are essentially a XOR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6388)
> better logic for #6386

- frontend/apps/filemanager/filemanager.lua
- frontend/ui/widget/filechooser.lua
Allows users to detect numbers in text when sorting filenames. We get:
```
AAA 1
AAA 2
AAA 10
```
instead of 
```
AAA 1
AAA 10
AAA 2
```
Most of the code was adapted from http://notebook.kulchenko.com/algorithms/alphanumeric-natural-sorting-for-humans-in-lua.
closes #6374
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6378)
> Implement numeric collator in file manager

- platform/remarkable/README_remarkable.txt
This adds a little more detail about how to use koreader with a different launcher on reMarkable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6397)
> remarkable: add more detail to README about launcher

- frontend/ui/menusorter.lua
Skipped in <https://github.com/koreader/koreader/pull/6371>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6403)
> [fix] MenuSorter: use orderedPairs for orphans

- frontend/ui/widget/menu.lua
- spec/unit/widget_menu_spec.lua
Cf. <https://github.com/koreader/koreader/pull/6403> and <https://github.com/koreader/koreader/pull/6371>.
I'm not completely sure if this would be correct/expected behavior, hence why I put it in a separate PR. See https://github.com/koreader/koreader/commit/394c847e2b276e07b9a639d53d29b59ac6eb4609 for some context. On the flip side, I don't see much in the way of alternatives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6404)
> [fix] Use orderedPairs in touch menu item table

- frontend/ui/data/css_tweaks.lua
- frontend/ui/widget/footnotewidget.lua
Includes:
- New German hyphenation patterns https://github.com/koreader/crengine/pull/356
- CSS: adds `text-align-last: -cr-right-if-not-first` private keywords https://github.com/koreader/crengine/pull/357
- CSS: adds `-cr-only-if: fb2-document`
- fb2.css: fix verses, minor cleanup
- FB2 footnotes: fix spacing between number and text
- ldomTextCollector: guess block boundaries better
- Text: fix read/write outside array bounds
- Text: fix read outside array bounds https://github.com/koreader/crengine/pull/358
- Fix crash when more than 64 nested elements - Closes #6391 
- Fix possible crash on book with embedded fonts load - Closes #6394 
- (Upstream) lvstsheet: avoid compilation warnings https://github.com/koreader/crengine/pull/359
- Strut confining: don't when there is no strut
- CSS: …
> bump crengine: various fixes and FB2 tweaks

- frontend/apps/filemanager/filemanagermenu.lua
- reader.lua
* Allow switching to SW dithering on a HW-capable device without that being lost on boot (and, worse, left in an undithered state).
* Make sure the automagic toggles between HW/SW in the Dev menu are properly saved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6419)
> Fix a few logic holes in dithering mode selection

- frontend/device/sdl/powerd.lua
- spec/unit/readerfooter_spec.lua
Cf. <https://github.com/koreader/koreader/pull/6370#issuecomment-662382487>.
@pazos No spies/stubs necessary here. ^_^
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6417)
> Fake battery status in readerfooter_spec to succeed on devices with batteries

- frontend/apps/reader/modules/readerview.lua
It doesn't do so for the FM, so the inconsistency is confusing.
Plus, if you're actively using sticky rotation, saved rotations are
ignored anyway.
Re #6420
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6423)
> Don't store document-specific rotation when sticky rotation is enabled

- frontend/ui/widget/configdialog.lua
Witnessed with "L/R Margins": tapping on a button sets the value to the preset table by reference.
Tapping the -/+ fine tuning buttons would update these tables in-place, in effect modifying the presets. This avoids that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6433)
> Fix ConfigDialog's ButtonProgress Fine tune updating presets

- frontend/apps/cloudstorage/cloudstorage.lua
- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readerwikipedia.lua
- frontend/device/kindle/device.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/network/manager.lua
- frontend/ui/network/networklistener.lua
- frontend/ui/otamanager.lua
- frontend/ui/translator.lua
- frontend/ui/widget/networksetting.lua
- frontend/ui/widget/opdsbrowser.lua
- platform/kobo/disable-wifi.sh
- platform/kobo/enable-wifi.sh
- platform/kobo/koreader.sh
- platform/kobo/nickel.sh
- platform/kobo/obtain-ip.sh
- platform/kobo/release-ip.sh
- platform/kobo/restore-wifi-async.sh
- platform/remarkable/koreader.sh
- plugins/calibre.koplugin/wireless.lua
- plugins/evernote.koplugin/main.lua
- plugins/goodreads.koplugin/main.lua
- plugins/kosync.koplugin/main.lua
- plugins/newsdownloader.koplugin/main.lua
- plugins/send2ebook.koplugin/main.lua
- plugins/timesync.koplugin/main.lua
- plugins/wallabag.koplugin/main.lua
- plugins/zsync.koplugin/main.lua
- spec/unit/networksetting_spec.lua
* Revamped most actions that require an internet connection to a new/fixed backend that allows forwarding the initial action and running it automatically once connected. (i.e., it'll allow you to set "Action when Wi-Fi is off" to "turn_on", and whatch stuff connect and do what you wanted automatically without having to re-click anywhere instead of showing you a Wi-Fi prompt and then not doing anything without any other feedback).
* Speaking of, fixed the "turn_on" beforeWifi action to, well, actually work. It's no longer marked as experimental.
* Consistently use "Wi-Fi" everywhere.
* On Kobo/Cervantes/Sony, implemented a "Kill Wi-Fi connection when inactive" system that will automatically disconnect from Wi-Fi after sustained *network* inactivity (i.e., you can keep reading, it'll …
> Various Wi-Fi QoL improvements

- frontend/ui/widget/opdsbrowser.lua
The media types for CBZ and CBR (added in #5940) are deprecated, and replaced by `vnd.comicbook+zip` and `vnd.comicbook+rar`. In addition, many OPDS servers will use the actual media type of the file, ie `application/zip` and `application/x-rar-compressed`.
See here about the new `vnd` types:
- https://www.iana.org/assignments/media-types/application/vnd.comicbook+zip
- https://www.iana.org/assignments/media-types/application/vnd.comicbook-rar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6443)
> Add additional media types to OPDS Browser

- .ci/install.sh
Otherwise it fails when it doesn't hit cache.
Also update to 0.7.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6445)
> [CI] Update shellcheck URL

- frontend/ui/widget/opdsbrowser.lua
following #6443 i thought i would check the other types
application/x-mobi8-ebook is replaced by application/vnd.amazon.mobi8-ebook (see https://www.iana.org/assignments/media-types/application/vnd.amazon.mobi8-ebook)
application/djvu doesn't seem to be an official one. image/x-djvu was the previous one, and is replaced by image/vnd.djvu (https://www.iana.org/assignments/media-types/image/vnd.djvu)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6450)
> add more media types to OPDS browser

- frontend/device/devicelistener.lua
- frontend/dispatcher.lua
Currently dispatcher has ability to change frontlight/warmth by a given number, this PR aims to allow user to change FL intensity/warmth to a new value. This is pretty useful, as it allows users to make profiles for day reading/night reading. I\m not sure if I should check all the conditions in events, since dispatcher already handles that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6440)
> Add Set Frontlight/Set Frontlight Warmth to dispatcher

- plugins/coverbrowser.koplugin/covermenu.lua
Slow browsing and exiting (ex: closing History) could be noticed when the memory usage is already high (as the GC has a lot of memory to visit).
Delaying it to after the new screen is shown limits the feeling of slowness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6453)
> CoverBrowser: delay GC for quicker browsing/exiting

- platform/kobo/koreader.sh
This passes shellcheck, for some reason, but it really doesn't work in busybox...
(I *probably* tested this in ZSH and didn't think twice about it at the time).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6466)
> Oops, too much Python/Lua ^^.

- plugins/gestures.koplugin/migration.lua
issue found by @poire-z https://github.com/koreader/koreader/pull/6441#issuecomment-666466047
when a user never set any custom multiswipes there is no file `multiswipes.lua` leading to `custom_multiswipes_table` being nil and pairs fails.
since it happens after the rest of the migration, the migration is successful and when the user reloads gestures (via restart or switching FR/reader) it works fine.
@poire-z 
To confirm this is what you issue was you should have a line in you crash.log from when you migrated:
```lua
ERROR Failed to initialize gestures plugin:  plugins/gestures.koplugin/migration.lua:189: bad argument #1 to 'pairs' (table expected, got nil)
```
--- …
> Fix gesture migration when user never had custom multiswipes

- frontend/ui/widget/sortwidget.lua
For now, close on any keypress.
Cf. https://github.com/koreader/koreader/issues/6463
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6464)
> [fix] Allow closing SortWidget

- frontend/dispatcher.lua
- plugins/gestures.koplugin/main.lua
- plugins/profiles.koplugin/main.lua
Should work, did not fully test every corner case.
one side effect, this invalidates a profile named `_updated`. it will fail to be created. (if a user had such a profile they will see very weird behavior)
based on @poire-z idea in https://github.com/koreader/koreader/pull/6441#issuecomment-668220743
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6471)
> Dispatcher Gestures Profiles: only flush settings when changed

- frontend/apps/reader/modules/readerhighlight.lua
- plugins/gestures.koplugin/main.lua
This PR adds new menu entry called `Hold pan rate` to `Taps and Gestures -> Gesture intervals`. This allows users to increase speed at which highlighting is refreshed, instead of the default 2 refreshes per second. Discussed partially in #6381.
closes #6381
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6449)
> Allow user to set higher hold pan rate

- plugins/coverbrowser.koplugin/bookinfomanager.lua
As reported by @lescheck on Weblate
> I think this should be in plural form (because of second line)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6483)
> [chore] Proper plurals in CoverBrowser processing

- plugins/gestures.koplugin/main.lua
* Better description in spinwidget
* Rename SpinWidget title from "Hold pan rate" -> "Text selection rate"
Mentioned in https://github.com/koreader/koreader/pull/6449#discussion_r466160878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6484)
> Cleanup after #6449

- frontend/device/pocketbook/device.lua
Proposed changes:
Notes:
1. PocketBook Basic 611 runs on the v16 firmware that predates the current OS, so compatibility needs to be tested.
2. Codenames were created based on similarity. To get the true codenames, I'd need users with said devices to check a file available in all PocketBooks that lists the proper codename. Not sure how to otherwise find the proper codenames.
3. Several of the previously added devices actually cover more than 1 device that shares the same firmware, but their codenames might differ. This should be further explored.
4. None of these definitions were tested, as I don't have the devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6481)
> PocketBook: Improve existing and add new device definitions

- plugins/kosync.koplugin/main.lua
Currently you can toggle it, but it doesn't persist after restart. This should fix this and prevent any more "lags"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6488)
> KOSync doesn't save "Auto sync now and future"

- frontend/device/sdl/device.lua
Requires https://github.com/koreader/koreader-base/pull/1157
Applies to all sdl targets that are not fullscreen. Environment overrides still take precedence over saved settings.
It can be tested on the emulator by removing `EMULATE_READER_W` and `EMULATE_READER_H` from [kodev](https://github.com/koreader/koreader/blob/master/kodev#L707)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6495)
> sdl window position and size

- frontend/apps/reader/modules/readerrolling.lua
Before it only worked in scroll mode not page mode & it used 10000 instead of 100%
thanks @poire-z 
Fixes: #6501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6503)
> ReaderRolling: fix gotoPercent

- frontend/device/android/powerd.lua
- frontend/device/devicelistener.lua
deduplicate code on warmth/brightness swipes
If device has a small scale (e.g. warmth is going from 0..10)
* adjust warmth message,
* use a smaller gesture sensitivity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6468)
> gesture: messages and sensitivity changes for small (warmth) scales; devicelistener dedup

- frontend/apps/cloudstorage/webdavapi.lua
This change to the parser in `cloudstorage.lua` adds support for the [Apache WebDAV module][1]
It was manually tested using the [bytemark/webdav][2] docker container.
I developed this in Windows, with a docker container that hosted an extracted AppImage and a VNC server that I viewed using a VNC client.
I will write up my work flow at a later point.
Changes have not been tested against other webdav servers (what was this originally tested against?). Please could someone test against other webdav servers?
I also noticed a logic inversion error where we were looking for a slash at the end of the URL and if it exists, then we explicitly set `has_trailing_slash=false` - so I fixed it to set to `true`. I had to do this so that we weren't visiting the URL without a trailing slash - apache sends …
> Support for Apache WebDAV module

- plugins/perceptionexpander.koplugin/main.lua
Perception expander doesn't check if the field is empty and overwrites the current value, resulting in using defaults.
fixes #6517
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6518)
> Fix perception expander overwriting settings with defaults

- frontend/ui/data/css_tweaks.lua
Includes:
- (Upstream) LVBase64NodeStream: fix possible segfault https://github.com/koreader/crengine/pull/366
- (Upstream) Fix getting encoding from HTML META tags (solves the characters encoding issue of #6482)
- FB2: also look for cover in `<src-title-info>` (closes #6493)
- FB2: fix cover image colors (see https://github.com/koreader/koreader/issues/6490#issuecomment-671768171)
- FB2: don't draw cover in scroll mode (shamelessly closes #6490)
- TextLang: better linebreaks at em-dash (EN/ES/FR) https://github.com/koreader/crengine/pull/365
- TextLang: increase _lb_props static array size https://github.com/koreader/crengine/pull/368
FB2 footnotes style tweaks: avoid gap above first footnote, caused by the title bottom margin collapsing into it. Solves …
> bump crengine: better linebreaks at em-dash, fb2 fixes

- frontend/device/pocketbook/device.lua
**Changes:**
**Reasons:**
- It seems like the 615 Plus is a CIS-only device, there's a [manual](http://support.pocketbook-int.com/fw/615-2/u/5.17.999/manual/cis/User_manual_PocketBook_615_Plus_RU.pdf).
- 616 is a CIS-only device ([manual](http://support.pocketbook-int.com/fw/616/u/0/manual/cis/User_Manual_PocketBook_616_RU.pdf)), while the Basic Lux 2 is a worldwide device that goes under 616W ([manual](http://support.pocketbook-int.com/fw/616/u/0/manual/ww/User_Manual_Basic_Lux_2_BG.pdf)).
**Other:**
- @NiLuJe @Frenzie Should I get rid of the hasColorScreen and has3BytesWideFrameBuffer lines for the Color (633)?
- #6505 fixes might be included in this, if there's an answer.
Besides that, this is ready for review, can't test as always.
--- …
> Update PocketBook device definitions

- frontend/device/pocketbook/device.lua
Adds cap to the device so it plays nice with the portrait touchscreen, see https://github.com/koreader/koreader/issues/6479#issuecomment-676336876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6529)
> Update PB633 device definition

- frontend/apps/filemanager/filemanager.lua
when rotation was caused by a gesture the gesture settings were not flushed leading to weird state when the FM reinit reloaded the gestures plugin
discovered in #6530
caused by #6309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6532)
> FM: rotation flush setting before reinit

- frontend/device/pocketbook/device.lua
**Changes:**
Can't test as usual, but should be good to go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6533)
> Fixes and changes to PocketBook definitions

- plugins/kosync.koplugin/KOSyncClient.lua
Reverts koreader/koreader#6489 since it introduced problems for people having `[*]Auto sync now and in the furture` & `Action when wifi off: prompt`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6535)
> Revert "Kosync network callback"

- frontend/readhistory.lua
- spec/unit/readhistory_spec.lua
The current code was only clearing the live table, it was forgotten
after a restart.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6557)
> Make sure "Clear history of deleted files" actually persists.

- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/readerui.lua
- frontend/document/credocument.lua
Includes https://github.com/koreader/crengine/pull/370 https://github.com/koreader/koreader-base/pull/1166 : 
- Revert "FB2: don't draw cover in scroll mode"
- (Upstream) FB2: fix coverpage drawing in scroll mode (properly fix #6490)
- FB2 footnotes: only merge run-in when next is erm_final
- fb2.css: use OTF tabular-nums for footnote numbers
- Text: ignore ascii and unicode control chars
- Fix HR positionning when floats involved
- writeNodeEx(): minor tweaks
- OnTagClose(): add self_closing_tag parameter
- HTML format detection: accept HTML5 doctype
- HTML parser: rework Lib.ru specific handling
- HTML parser: new more conforming implementation
- HTML parser: ensure foster parenting inside tables
This new HTML parser should close #6482 - and with #6521, might have solved a few other CHM …
> bump crengine: new HTML parser, libRu and FB2 tweaks

- frontend/apps/reader/modules/readerfooter.lua
It's only used by `all_at_once`, but it needs to actually reflect the settings at all times, so as to actually track them, and avoid issues with no or a single mode enabled.
Fix #6561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6563)
> Always update the table of footer text generators

- frontend/dispatcher.lua
have a user set number override a gesture (gestures will still work when set to 0), this allows incremental FL changes with a tap gesture
Fixes: #6564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6565)
> Dispatcher: incremental gesture fix

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/ui/widget/scrollhtmlwidget.lua
- frontend/ui/widget/scrolltextwidget.lua
- frontend/ui/widget/textboxwidget.lua
- frontend/ui/widget/verticalscrollbar.lua
- reader.lua
- Bookmarks: avoid possible crash. See https://github.com/koreader/koreader/issues/5387#issuecomment-675551293. Closes #5387 
- Start with: adds Favorites. Closes #6487 
- Text/HTML widgets: allows scrolling with the scrollbar. Closes #5308 
Little difference from what we are used to on computers: tapping jumps to where we tap, instead of paging just one page in that direction as on computers - as we can already page one page by tapping in the text or via other buttons (and it makes it a little easier to use).
Not super easy with dictionaries and Wikipedia (I made the touch area 3 times the width of the scrollbar, to not make the scrollbar larger and ugly, so I hope people were not tapping that near the scrollbar for browsing down current result or going to next...)
But quite fine with …
> Text/HTML widgets: allow scrolling with the scrollbar

- frontend/apps/reader/modules/readerfont.lua
- frontend/document/canvascontext.lua
- frontend/fontlist.lua
- frontend/ui/elements/font_settings.lua
- platform/pocketbook/koreader.app
They're not encrypted, so we can use them.
By default "use system fonts" is disabled, like in other platforms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6567)
> [Pocketbook]: enable usage of system fonts

- Makefile
This gives about 1Meg smaller apk.
Compression time on a quad-core is about twice as `zip -r9`, when using `mx=7` its about the same time (of course then the compression is not as good, but saves 800k)
Decompression memory usage does not seem to be bigger: Tested with grep `grep VmPeak /proc/$PID/status` and `grep VmHWM /proc/$PID/status` showed almost identical values.
I have used this compression the last weeks on Tolino and phone without strange effects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6587)
> Better zipping

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/docsettings.lua
- frontend/readhistory.lua
- frontend/ui/widget/checkbutton.lua
- frontend/ui/widget/filechooser.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/openwithdialog.lua
- frontend/ui/widget/radiobuttontable.lua
- frontend/ui/widget/touchmenu.lua
- frontend/util.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/texteditor.koplugin/main.lua
`FileChooser: allow traversing unreadable directories`
See https://github.com/koreader/koreader/issues/6508#issuecomment-681991683. Closes #6508. Ref https://github.com/koreader/koreader/issues/6379#issuecomment-659344319 https://github.com/koreader/koreader/issues/4885#issuecomment-494314073
`CoverBrowser: list mode: show fake cover when no cover`
See https://github.com/koreader/koreader/issues/6058#issuecomment-682117096. Closes #6058.
Also bump base for lua-ljsqlite3 to use sqlite3_close_v2() https://github.com/koreader/koreader-base/pull/1174 and avoid possible crashes https://github.com/koreader/koreader/issues/5563#issuecomment-682980942 
`util: adds util.secondsToHour(), util.secondsToDate()`
`History: show last read date instead of file size`
See …
> History: show last read date, adds Text editor to "Open with" dialog

- frontend/device/generic/device.lua
- frontend/ui/trapper.lua
- frontend/ui/uimanager.lua
- plugins/backgroundrunner.koplugin/commandrunner.lua
- plugins/coverbrowser.koplugin/bookinfomanager.lua
Conversely, Trapper and plugins report standby interruptability.
Ground work for #6545, effectively no-op now. To test it, run in debug mode and see if the usual places trigger standby bans as they should, fe for covers:
```
$ strings crash.log |egrep 'standby|BG'
08/25/20-01:31:51 DEBUG prevent standby
08/25/20-01:31:51 DEBUG   BG extraction started
08/25/20-01:31:51 DEBUG   BG extracting: ...
08/25/20-01:31:51 DEBUG   BG extracting: ...
08/25/20-01:31:56 DEBUG   BG extraction done
08/25/20-01:32:01 DEBUG allow standby
```
~Of special note is Trapper:info() - while not background process stuff like the rest, it is used for "tap me to abort this" of unattended loops, so we need to prevent standby in there as well.~ Trapper now nukes standby wholesale. This is coarse, but simple and …
> Make UIManager track prevent/allowStandby state.

- .luacheckrc
- frontend/device/cervantes/powerd.lua
- frontend/device/kobo/powerd.lua
- frontend/ui/plugin/background_task_plugin.lua
- plugins/autofrontlight.koplugin/main.lua
- plugins/backgroundrunner.koplugin/main.lua
- spec/unit/autofrontlight_spec.lua
- spec/unit/background_runner_spec.lua
- spec/unit/background_task_plugin_spec.lua
- spec/unit/commonrequire.lua
(I really don't like this plugin, and for a few years I've been having bad sleep, knowing that it _is_ running for nothing on thousands of devices and that users don't even know it - and it _is_ surely responsible for climate change and global warming :/ So, may be it's not too late... :)
A BackgroundRunner plugin instance will stop running (rescheduling a check every 2 seconds) when there is no (or no more) job to run.
Clients of this service now have to emit an event after adding a job into PluginShare.backgroundJobs, so an already loaded but stopped BackgroundRunner can notice it and start running again.
Ref https://github.com/koreader/koreader/pull/3608#issuecomment-357929349
Not tested on devices where it is really used: some kindle for autofrontlight, some kobo and cervantes for …
> Tame BackgroundRunner: stop running when no more job

- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- plugins/autostandby.koplugin/_meta.lua
- plugins/autostandby.koplugin/main.lua
Adaptively pins the auto-standby UI lock. When frequent input from user is observed, we'll prevent auto-standby for increasingly longer periods of time, and revert back to more aggressive standby with infrequent input (ie when reading a book). Auto-standby is set aggressive (not adaptive) if battery is below certain threshold. Can also configure standby to be always prevented for lower input lag, shorter battery charge.
Depends on #6558
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6602)
> Auto-standby plugin

- plugins/autostandby.koplugin/main.lua
Since circleci decided to ignore everything I spam around until it's too late for some reason, I'll run luacheck manually from now on, pinky promise.
(./kodev is unfortunately badly broken on archlinux, so have to go a little blind wrt testing)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6612)
> Autostandby: Fix variable ref.

- frontend/apps/reader/modules/readertypography.lua
- plugins/coverbrowser.koplugin/listmenu.lua
Includes https://github.com/koreader/crengine/pull/372 : TextLang, hyphenation: add Serbian
Follow up to #6596.
Also fix CoverBrowser list mode with History, to show the last read date of deleted files. See https://github.com/koreader/koreader/issues/6041#issuecomment-684762928
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6618)
> bump crengine: TextLang, hyphenation: add Serbian

- frontend/device/pocketbook/device.lua
- platform/pocketbook/koreader.app
- reader.lua
* Bring in restart koreader & shutdown device exit options
* Selecting books in stock explorer reuses running instance
ref #6597
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6620)
> Pocketbook: Launcher OS integration

- frontend/dispatcher.lua
- plugins/terminal.koplugin/main.lua
To be able to quickly repeat often used terminal commands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6609)
> Terminal: add shortcuts for re-useable commands

- frontend/device/pocketbook/device.lua
We used to put koreader alone in there, but apparently other
handlers can be left in as optional - see #6415 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6624)
> Pocketbook: Add file associations into "Open with" menu

- frontend/device/android/powerd.lua
Each JNI call has a little overhead, so don't use them when it is not needed.
The syntactic sugar is not needed to use android module's functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6641)
> AndroidPowerD: remove unneded syntactic sugar & JNI calls

- frontend/ui/uimanager.lua
Also, fix a typo that broke (PC) plug out detection on Cervantes ;).
Depends on https://github.com/koreader/koreader-base/pull/1183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6645)
> Only ask to start an USBMS session when plugged into a USB host on Kobo

- platform/remarkable/koreader.sh
The reMarkable version of fbdepth doesn't support the -1 rotation so
this was actually not setting the rotation at all. I didn't notice this
as I was always launching koreader from xochitl so the rotation was
already set correctly.
This means that if koreader is started up as the default UI then the
display actually gets set up correctly!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6658)
> remarkable: fix fbdepth use in startup script

- frontend/device/android/powerd.lua
getWarmth must not be called before warm_diff is initialized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6665)
> correct bug introduced with #6641

- frontend/apps/reader/modules/readerfooter.lua
- frontend/device/generic/powerd.lua
- frontend/device/kobo/powerd.lua
This made the ReaderFooter refresh go super-wonky...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6667)
> [Kobo] Don't send a flood a FrontlightStateChanged events during the FL ramps

- frontend/apps/reader/modules/readerlink.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/footnotewidget.lua
Since 8815cbe0 and getSafeFilename() taking additional parameters, and :gsub() returning multiple values, filesystem type wasn't really checked and replacements were not ensured, so saving articles like "Portal:Stuff" failed on VFAT devices as ':' wasn't replaced.
Add styles for some more non-HTML FB2 tags, so MuPDF can render them as expected.
According to https://github.com/koreader/koreader/issues/6622#issuecomment-686328228. Closes #6622. 
In the "Set footnote popup font size", allow toggling between setting a relative (to the document) font size and setting an absolute font size (that won't change with the document font size).
Closes #6642.
--- …
> Footnote popups: allow setting an absolute font size

- frontend/apps/reader/modules/readertypography.lua
- frontend/document/credocument.lua
- frontend/ui/data/css_tweaks.lua
Includes:
- Update German hyphenation patterns https://github.com/koreader/crengine/pull/375
- (Upstream) Adds ODT (ODF) format support https://github.com/koreader/crengine/pull/377
- TextLang, hyphenation: add Basque, Croatian, Esperanto, Estonian, Georgian, Latvian, Lithuanian, Macedonian, Occitan, Welsh; update Bulgarian, Irish, Portuguese, Slovak, Dutch, Norwegian, Spanish; update hyphen min for Czech, English, Greek; fix Romanian and Ukrainian pattern file names https://github.com/koreader/crengine/pull/378 Thanks to @roshavagarga and @cramoisi.
- HyphMan: adds HyphMethod::getLeft/RightHyphenMin()
- epub.css: update HR default style https://github.com/koreader/crengine/pull/379 - Closes #6632 
- fb2.css: keep `<date>` in main text left-aligned …
> bump crengine: ODT support, more typography languages

- frontend/device/generic/powerd.lua
- frontend/device/kindle/powerd.lua
- frontend/device/kobo/powerd.lua
- frontend/device/sdl/powerd.lua
`isFrontlightOnHW()` was returning a value from powerd not from hardware before powerd was updated, therefore `_decideFrontlightState()` would have the old state.
The `FrontlightStateChanged` event used by `ReaderFooter` was called by `_setIntensity` before `powerd.is_fl_on` was toggled by `_decideFrontlightState()`
Also add `isFrontlightOnHW()` for the emulator (it was broken)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6664)
> ReaderFooter: update FL on toggle

- frontend/version.lua
Turns out match returns an empty string instead of nil for unmatched groups?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6693)
> Fix point release and revision detection in Version:getShortVersion

- platform/remarkable/koreader.sh
related to https://github.com/Eeems/oxide/issues/69, this diff adds an env variable to remarkable platform's koreader.sh to allow someone to tell koreader to not set the bpp to 8 from outside koreader.sh. the env variable is called `KO_DONT_SET_DEPTH`
we don't use the dev setting because someone might change the dev setting without realizing what it does
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6685)
> reMarkable: add environment variable to tell koreader.sh to not set bpp

- frontend/device/generic/device.lua
- frontend/device/gesturedetector.lua
- frontend/device/pocketbook/device.lua
- frontend/ui/uimanager.lua
- spec/unit/gesturedetector_spec.lua
Needs https://github.com/koreader/koreader-base/pull/1194
* Uses bunch of new plumbing in base to configure screen rotations in hardware (koreader normally does this via blit buffer rotations, except for android).
* Some PB specific kludges that used to pollute core/framebuffer_linux are brought into PBs frontend driver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6684)
> Pocketbook: Implement HW screen rotation, bring in PB specific kludges from linuxfb

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/device/cervantes/device.lua
- frontend/device/generic/device.lua
- frontend/device/kindle/device.lua
- frontend/device/kobo/device.lua
- frontend/device/pocketbook/device.lua
- reader.lua
Needs https://github.com/koreader/koreader-base/pull/1195
CBB now handles nightmode correctly (by deferring to Lua), so we no longer
need to do monkey dances about disabling it when hw invert is missing.
canUseCBB cap is resolved by generic device re-configuring blitbuffer
on the go, so as to avoid repeating the same thing in every device driver.
The dev setting can now flip cbb on the go, so one can gloat at the near
meaningless perf difference - 2Mp draw is 15ms Lua / 10ms C on 1GHz Cortex A7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6696)
> Clean up C blitbuffer kludges.

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/dispatcher.lua
- frontend/document/djvudocument.lua
- frontend/document/document.lua
- frontend/document/koptinterface.lua
- frontend/document/pdfdocument.lua
- frontend/ui/elements/reader_menu_order.lua
This pull requests aims to provide convenient way to zoom in comics. The idea is when user holds/double taps (not decided yet) on a manga/comic panel, it gets cut out from the rest of the image and zoomed. More details in https://github.com/koreader/koreader-base/issues/1148. Depends on https://github.com/koreader/koreader-base/pull/1159
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6511)
> Comics: zoom to panel

- frontend/device/cervantes/device.lua
- frontend/device/kobo/device.lua
- frontend/device/sdl/device.lua
This is because fb driver should not be inspecting self.device for low level
caps anymore.
Fixes #6711
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6712)
> linuxfb: frontends need to pass is_always_portrait

- frontend/ui/elements/mass_storage.lua
As things were, when I activated USBMS, any bookmarks recently added and not yet stored in the sidecar file would be lost after returning to the reader. These changes fix that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6713)
> Save document settings before activating USBMS

- frontend/apps/filemanager/filemanagershortcuts.lua
In the current KOReader version the folder shortcuts are sorted by date of addition. When a user has many folder shortcuts (like I do 😊 ) they are easier to find again when sorted alphabetically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6707)
> Sort folder shortcuts

- frontend/document/document.lua
Implementing what @Frenzie mentioned in https://github.com/koreader/koreader/pull/6511#issuecomment-698584844
It should improve resolution of output "panel" (https://github.com/koreader/koreader/pull/6511#issuecomment-698346603)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6709)
> Panel zoom - improve output image resolution

- frontend/device/generic/device.lua
- frontend/device/pocketbook/device.lua
The differences between Allwinner/MXC matter surprisingly little in practice (https://github.com/koreader/koreader-base/issues/1202), it's not even worth it to bother the base mxc driver with it. Instead, frontend can make some informed choice by probing for the hardware and tweaking requested device caps accordingly.
On Allwinner B288, we disable both hwrot (done in software in kernel and terribly, ie not worth it) and hwinverse (no support whatsoever). On NXT we'll keep both on, as the kernel driver seems to be [using the hardware properly](https://github.com/pocketbook/Platform_MX6/blob/master/Kernel_631/drivers/video/mxc/mxc_epdc_fb.c#L2218)
--- …
> Pocketbook: Try to auto-detect HW feature caps more precisely

- frontend/apps/reader/modules/readerfooter.lua
- frontend/device/android/device.lua
- frontend/device/cervantes/device.lua
- frontend/device/generic/device.lua
- frontend/device/kobo/device.lua
And also allow enabling said icon on Kobo & Cervantes.
(Supersedes #6656, see discussions over there ;)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6725)
> Fancier Wi-Fi status icons in ReaderFooter

- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/device/generic/device.lua
- frontend/util.lua
- plugins/statistics.koplugin/main.lua
- spec/unit/util_spec.lua
Fix #6728
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6729)
> Show full ToC entry on hold

- frontend/device/pocketbook/device.lua
Ditto as PB740
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6735)
> Pocketbook: Fix silly rotation bug on PB1040

- plugins/kosync.koplugin/main.lua
If user manually triggered update, allow for automatically enabling WiFi, add new menu entry "Sync every # pages", so users don't have to rely on modifying `defaults.lua.persistent` and set global variable `DAUTO_SAVE_PAGING_COUNT`. It won't break like #6489, because we check if user triggered the update. Some discussion in https://github.com/koreader/koreader/issues/6726#issuecomment-700679676. It should be alright, but I'll go over it once again after I get some sleep ;P
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6733)
> KOSync improvements

- frontend/ui/font.lua
- frontend/ui/widget/imageviewer.lua
`Font: fix possible messy font sizes when geometry/dpi change`
Fix issue noticed at https://github.com/koreader/koreader/pull/6729#issuecomment-700822079
`ImageViewer: allow saving current view as an image`
And to make it the screensaver image.  Done on two-finger large diagonal tap on multitouch devices (like regular ScreenShoter) as long-diagonal swipe is reserved for panning.
Fallback to tap in the bottom left corner on non-multitouch devices.
(Might not be super obvious, but I don't want anything more intrusive in the ImageViewer.)
See https://github.com/koreader/koreader/issues/1914#issuecomment-702927965 and https://github.com/koreader/koreader/issues/3637#issuecomment-362107711.
Closes #1914. Closes #6699.
--- …
> ImageViewer: allow saving current view as an image

- frontend/apps/reader/modules/readerfooter.lua
I'm half of a mind to drop that behavior from the Bookmarks generator, because I feel like the generator itself deciding to go into hiding breaks some implicit contract with the user that explicitly asked to display it...
But, it's been implemented that way from the start, so, for the sake of backward compatibility, eh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6752)
> ReaderFooter: Don't generate separators for empty generators

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/ui/widget/sortwidget.lua
Previously you on had move files in and out of the dictionary directory to change the order in which dictionaries are queried.
With the changes in this pull request, the dictionary order can instead be configured via a SortWidget based menu.
Since I thought it would be impractical to have two menus for managing dictionaries, one for switching between enable/disable and one for the sorting order, I decided to add checkbox support to SortWidget. The check mark is toggled with a long press.
New dictionaries, i.e. those that were not present when the sort menu was last called, are placed at the end of the dictionary list.
The previous implementation relied on file order provided the filesystem implementation. Opposing to that the new implementation sorts the dictionaries by their name.
Users …
> Make dictionary lookup order configurable via SortWidget

- frontend/apps/reader/modules/readerfont.lua
- frontend/ui/font.lua
- frontend/ui/widget/textwidget.lua
- frontend/ui/widget/touchmenu.lua
Includes https://github.com/koreader/crengine/pull/385 :
- TextLang: German: loosen quotation marks handling - Closes #6717.
- Fonts: add LVFontManager::getFontFileNameAndFaceIndex()
- fb2.css: avoid break before footnote links - Closes #6718.
- FlowState: fix possible wrong baseline with nested inline-table
- Tables: fix possible layout issues with rowspan
- Table cells: minor refactoring of baseline handling
- getRenderedWidths(): better estimate table width
- lvstyles: allow for more than 64 styles
Font menu: show font names with their own font
See https://github.com/koreader/koreader/issues/6739#issuecomment-703131167. Closes #6739.
Any rewording suggestions for the following and the setting name `font_menu_use_font_face` ?
<kbd>![image](https://user-images.githubusercontent.com/242734 …
> Font menu: show font names with their own font. Bump crengine

- plugins/statistics.koplugin/main.lua
I have found a new bug in statistics plugin. The remaining time to read (both for a book & for a chapter) is decreasing a way too fast when navigating betweeg the same set of pages (for example going forward and backward a few times), especially on newly opened books, so it becomes useless very quickly.
**The reason:**
The `mem_read_pages` is calculated wrongly in `ReaderStatistics:onPageUpdate(pageno)` method for two reasons:
- it counts duplicated page numbers (every visit of the same page as it was a "new page")
- it counts pages even if you spent less time on them than `self.page_min_read_sec`
This fix solves the bug.
---
_P.S. This is my first contribution to KOReader. It's currently my favorite reader app. I'm really excited that it was so easy to fix something myself that was …
> Statistics plugin: fix in-memory statistics.

- frontend/ui/widget/infomessage.lua
as suggested by @poire-z in https://github.com/koreader/koreader/pull/6729#issuecomment-700765094
I need it for a custom plugin https://github.com/yparitcher/chitas.koplugin that displays a InfoMessage in Hebrew (RTL)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6766)
> enable RTL InfoMessage

- .circleci/config.yml
This will be required by November 1.
See <https://docs.docker.com/docker-hub/download-rate-limit/> and <https://discuss.circleci.com/t/authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567?mkt_tok=eyJpIjoiT1dVNE9EWmhNRFJtWTJObSIsInQiOiJOd1lnZHJidWpyU2ZqMG1JM21cL1Yxc1BsK1M1cWYwWnljeE43WlQ2K2tcL0ZKNnpXUElISjl6djlIM2FucTl4ekY3bjFBUVRxbXJ5XC93YTlZYlF2Z0pWeU1OM2FQR2RFNWFWOFBURk80RElsK3JabHZqT09qc3FYOE1aS0VUdFo4MiJ9> for more information.
<hr>
The only problem is I'm not sure if it's actually working or not based on the CirlceCI output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6764)
> [chore] Add authentication to Docker image

- frontend/apps/filemanager/filemanager.lua
Somehow I placed it at the bottom of the menu by accident, it should've been 2nd, with other "Sort by filename" entry
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6777)
> Move numeric sort up, so it looks better

- frontend/device/remarkable/device.lua
Turns out it's being weird like on Mk. 7 Kobos with a crapload of PxP
processing flags.
Except without the "crapload of flags", part :D.
Re: #6772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6779)
> Disable HW inversion on rM

- frontend/device/pocketbook/device.lua
- frontend/device/pocketbook/powerd.lua
- frontend/ui/uimanager.lua
- platform/pocketbook/koreader.app
- plugins/autosuspend.koplugin/main.lua
This allows for better energy efficiency (no more 50Hz tick poll),
as well as lower input lag / higher precision - touch events are
native linux ones.
In addition, auto off/suspend plugin is used in this mode, as we need
to trigger (timed) sleep / poweroff on our own, since the OS ones
will no longer work whenever koreader has focus.
This is for rooted devices only, and possibly somewhat FW
specific, so enabled only on PB740-2 where it's reasonably tested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6791)
> Pocketbook: use raw input I/O

- frontend/device/cervantes/device.lua
- frontend/device/gesturedetector.lua
- frontend/device/kobo/device.lua
- frontend/device/sony-prstux/device.lua
- plugins/gestures.koplugin/main.lua
- spec/unit/device_spec.lua
See https://github.com/koreader/koreader/pull/5138#issuecomment-707733771 and above.
And https://www.mobileread.com/forums/showthread.php?t=333958 for the original issue.
Also fixed info_text not displayed, and added more descriptive ones.
Rewording suggestions welcomed (for this one and the 6 other info_text I tweaked).
<kbd>![image](https://user-images.githubusercontent.com/24273478/96302515-42fbbe80-0ff9-11eb-8d9d-031d3df5c525.png)</kbd>
Works for me instead of my previous handling of that described at https://github.com/koreader/koreader/pull/5138#issuecomment-707384339.
Quickly tested with double tap enabled on the emulator, seems OK.
(There might be already some issues when intervals overlaps, or when we go above 1 second - but not really caring much. I.e. with this one, if …
> GestureDetector: add Tap interval setting, to avoid bounces

- frontend/apps/reader/modules/readerview.lua
- frontend/device/generic/powerd.lua
- frontend/ui/uimanager.lua
- plugins/autosuspend.koplugin/main.lua
- plugins/autoturn.koplugin/main.lua
- plugins/statistics.koplugin/calendarview.lua
- plugins/statistics.koplugin/main.lua
* Avoid spurious Screen:afterPaint calls
* Cache os.time() calls where it makes sense to do so
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6801)
> Random nano optimizations

- frontend/apps/reader/modules/readerfont.lua
- frontend/fontlist.lua
- frontend/util.lua
Info about each face (l10n, name, family, style etc) is
now cached offline, so fonts can be queried ahead of time.
Fixes https://github.com/koreader/koreader/issues/6763
needs https://github.com/koreader/koreader-base/pull/1215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6786)
> fontlist: Cache categorized font info (for mupdf)

- doc/config.ld
- frontend/dispatcher.lua
- plugins/calibre.koplugin/main.lua
- plugins/calibre.koplugin/metadata.lua
- plugins/hello.koplugin/main.lua
- plugins/kosync.koplugin/main.lua
- plugins/terminal.koplugin/main.lua
- plugins/texteditor.koplugin/main.lua
- plugins/wallabag.koplugin/main.lua
as discussed in #6768 and elsewhere.
Dispatcher was updated as not to crash on not existent entries.
I extended the Hello World Plugin to serve as an example.
the important parts.
the plugin must define a `DispatcherRegisterActions` event like so, and call it on init in case the plugin is loaded after Dispatcher:
```lua
function Hello:onDispatcherRegisterActions()
Dispatcher:RegisterAction("helloworld_action", {category="none", event="HelloWorld", title=_("Hello World"), filemanager=true,})
end
```
If there is a non registered item attached to a gesture/profile (someone enabled a gesture and then disabled the appropriate plugin). then the menu will keep that item, but it will not show in any of the sections as there is no corresponding entry. However the `None` box will **not** be checked …
> Dispatcher: allow registering actions at runtime

- plugins/statistics.koplugin/calendarview.lua
- plugins/statistics.koplugin/main.lua
Just by tweaking the SQL queries.
Also, in the hourly histogram, show at least a 1px bar when there was any reading this hour.
I always thought the slowness of showing and browsing the calendar views was caused by the many little widgets to size and draw, but no, it was really the SQL queries (and it was as slow before the recent refactoring).
On my Kobo, each of the 2 SQL queries used to take 500ms (and the UI drawing around 20ms)- and it was quite noticable.
With these tweaks, each SQL query take around 100ms.
(By adding an index `CREATE INDEX zzz ON page_stat_data(start_time)`, we'd get even better results, 50ms + 30ms - but well, it makes the DB file size grow by 30%, and it's not worth again upgrading the schema.)
--- …
> Statistics: speed up Calendar view

- frontend/device/pocketbook/device.lua
- frontend/ui/elements/screen_eink_opt_menu_table.lua
- frontend/ui/elements/waveform_level.lua
cf https://github.com/koreader/koreader-base/issues/1202
On pocketbook, update modes are not as clear cut due to overall
chipset and kernel version mess. Inkview solves this by always
using the slowest (and safe) GC16 waveform. We now do that too
by default.
Slow updates suck though, so there's now a menu entry to configure
it for speed (with mild artifacts at best, kernel panic at worst).
This is a generic interface (any eink Screen can announce support).
The driver may interpret the slow/fast range however they want.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6794)
> Pocketbook: waveform presets

- plugins/statistics.koplugin/main.lua
By chunking DB migration steps per schema revision, as discussed in #6807
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6812)
> Statistics: Handle DB migration to 20201022

- frontend/device/android/device.lua
We need it to exit the lua state and return from android_main. This avoid a *zombie state** on the following scenarios:
- App is killed by the activity manager  (ie: battery optimizations or OOM)
- We call finish() from Kotlin
**zombie state**: app is running, does nothing, won't easily trigger ANRs and needs to be killed manually by the user
In the real world the only related bug I found was on android10+, when running KO ocassionally and leaving the activity in the background for a week. The app is then destroyed by the system to "save battery".
As android has a way to "upgrade" or "downgrade" app battery optimization based on usage, YMMV.
Requires https://github.com/koreader/koreader-base/pull/1224
--- …
> android: handle onDestroy

- frontend/document/koptinterface.lua
Fixes #6825
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6827)
> KoptInterface:getWordFromBoxes: guard against nil boxes

- plugins/statistics.koplugin/main.lua
Re #6825
Re #6827
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6829)
> Statistics: Don't blow up when annotating/highlighting stuff with the plugin loaded, but disabled

- frontend/ui/uimanager.lua
`_repaint` already ensures that widgets below a full-screen one never get painted.
`close` wasn't doing that, which meant that it was sending `setDirty` calls on behalf of stuff that `_repaint` would later skip.
This was causing the refresh region to get needlessly inflated.
In the same vein, prevent being infected by the dither flag if said dithered widget is covered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6828)
> UIManager: Handle covers_fullscreen properly in close

- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerpagemap.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/apps/reader/modules/readerzooming.lua
(Some of this is related to the last one, #6540)
* When auto_refresh_time is enabled, don't actually refresh anything when the footer is hidden.
* Fix a bunch of state tracking related to height computations, meaning `getHeight()` is now actually accurate, always, and we don't need shitty workarounds anymore.
* `footer_container.dimen.h` *includes* the progress bar, so, never reset it to 0 unless the progress bar is disabled (some `settings.progress_bar_position` codepaths were mistakenly doing just that).
* More aggressively set/reset `footer_text.height` (not sure this one makes much of a difference, and/or if it's actually useful at all, but, the tracking was already there, but hella inconsistent, so, just fix it).
* Honor `settings.reclaim_height` in other bits of code that were only …
> Another round of ReaderFooter fixes

- frontend/device/gesturedetector.lua
- frontend/device/input.lua
- frontend/ui/data/css_tweaks.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/virtualkeyboard.lua
- plugins/gestures.koplugin/main.lua
`Style tweaks: fix some wording`
See https://github.com/koreader/koreader/issues/6836#issuecomment-717910988. Closes #6836. 
`GestureDetector: add Tap interval on keyboard setting`
Follow up to #6798: allow specifying an other value for tap interval when the keyboard is shown
(a good value for tap interval on reader and UI elements might be too long on the keyboard, and prevent typing fast). (And may be some other people will want a bigger one on the keyboard and 0 in the UI/Reader.)
See https://github.com/koreader/koreader/pull/6798#issuecomment-716852598
<kbd>![image](https://user-images.githubusercontent.com/24273478/97500845-9b737a00-1970-11eb-8550-d09a584029ae.png)</kbd>
(same description text as on the other one)
--- …
> GestureDetector: add Tap interval on keyboard setting

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/modules/readerback.lua
- frontend/apps/reader/modules/readerlink.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- plugins/gestures.koplugin/main.lua
Have ReaderBack be the sole handler of onBack.
Add 4 mutually exclusive options for the Back key, to avoid ReaderLink and ReaderBack location stacks from interfering (ReaderBack's stack being always a superset of ReaderLink's stack).
So, remove "Enable back history", which is replaced by Back option "Go to previous read page".
Fix a few possible crashes and inconsistencies (when zoom, scroll or reflow have changed) with ReaderPaging and ReaderView when restoring previous context (page/view).
<kbd>![image](https://user-images.githubusercontent.com/24273478/97781596-dc47da80-1b8c-11eb-8c31-3d7115b0d12c.png)</kbd> <kbd>![image](https://user-images.githubusercontent.com/24273478/97781600-e4a01580-1b8c-11eb-8b1e-3030fabcad69.png)</kbd>
Some details about the issues in …
> Reader: rationalize "Back" key/action handling

- frontend/device/android/device.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/elements/screen_android.lua
- Lcd devices won't use the SurfaceView, just the good old native content/window (except AndroidTv and ChromeOS)
- All android dialogs will be presented with Material Design on recent devices.
- Added an option to device settings to manage application battery optimization.
- Permissions that require the user to go to a settings page will be presented with a native android dialog.
Requires https://github.com/koreader/android-luajit-launcher/pull/257 (please go there to read the changes under the hood)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6821)
> android changes

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readertypeset.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/device/devicelistener.lua
- frontend/document/credocument.lua
- frontend/ui/uimanager.lua
Instead of relying on `Screen.night_mode` at the actual call site, rely on an internal flag, toggled via a set* function, which ensures the cache framework will reset the cache, allowing the page to be re-rendered (and the image counter-inverted properly, and, more importantly, reliably ^^).
Fix #6845 (at least as far as I'm concerned, as I couldn't find anything else going awry on Kobo either with HW or SW invert ^^).
Now also includes minor ReaderHighlight tweaks to avoid spurious cache invalidations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6854)
> [CRe] Ensure toggling nightmode invalidates the drawCurrentView cache

- datastorage.lua
Partially reverts https://github.com/koreader/koreader/pull/6849
Needed for new installs, mainly in https://github.com/koreader/koreader/blob/master/frontend/ui/otamanager.lua#L173.
Fix https://github.com/koreader/koreader/pull/6849#issuecomment-723491945
Hopefully the issue won't affect many users as it needs an empty data_dir to begin with. It is easily fixable with `mkdir koreader/ota`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6857)
> create ota dir

- frontend/ui/data/css_tweaks.lua
This is for ebooks that have `<span>` inside of `<a>`.
I've come across ebooks with hyperlinks like this: `<a href="fn.html#fn-1"><span class="a">1</span></span></a>`. The span has CSS that changes the color and overrides the “a_black” CSS fix. With this PR, the CSS for the span gets overridden too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6856)
> Apply CSS tweaks for links to all elements below a elements.

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/readerui.lua
- frontend/dispatcher.lua
Fixes #6592
I needed to add `Screenshoter` to `self` as until now it was just listed as a `active_widget` and would only receive `sendEvent` but not regular `handleEvent` like other widget children. this shouldn't cause too much overhead as they should point to the same table. If there is a better way to fix this please let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6858)
> add Screenshot to Dispatcher

- frontend/apps/reader/modules/readertypeset.lua
- frontend/device/devicelistener.lua
- frontend/document/credocument.lua
I think this should be a simpler fix for #6854 allowing us not to track nightmode in 2 places.
unless there is a specific reason not to export `_callCacheReset()`?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6859)
> allow clearing CreDocument's callcache from frontend

- frontend/apps/reader/modules/readerfooter.lua
Rationale: 
Today I learned that there are system-wide gestures on Onyx devices, and while performing those, skim widget kept popping up and there is no way to disable it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6852)
> Add menu item allowing users to disable "hold on footer to show Skim Widget"

- frontend/apps/reader/modules/readerfooter.lua
It was supposed to be without parentheses
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6862)
> Cleanup after #6852

- frontend/device/android/device.lua
- frontend/device/generic/device.lua
- plugins/coverimage.koplugin/_meta.lua
- plugins/coverimage.koplugin/main.lua
If the plugin is enabled the following actions can be selected:
1. On opening of a document, the cover is saved to a file (format png). 
If the filename exists, a backup of the original is created.
2. On closing of the document this file can be deleted and the original file can be restored.
3. Certain documents can be excluded from image generation.
This plugin can be used to change the sleep-screen on Tolinos (filename: /sdcard/suspend_others.jpg) as long KOReader has an opened document. On close of KOReader the original sleep screen is restored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6813)
> Plugin for saving the cover image to file

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerfooter.lua
When toggling a bookmark, the status line should be updated, so that the actual bookmark count (if enabled) is shown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6872)
> update Stausline immediately when toggling a bookmark

- frontend/gettext.lua
In case of no environment language. I suppose that doesn't tend to happen much in the wild since I added the offending code early in 2020. ;-)
Fixes <https://github.com/koreader/koreader/issues/6873>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6874)
> [fix] Always initiate empty context table

- frontend/device/sdl/device.lua
Required after https://github.com/koreader/koreader/pull/6309.
Uses the same logic as in android (I cannot locate the PR right now). Tested on a mac.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6882)
> sdl: resize FM

- frontend/ui/uimanager.lua
- platform/kobo/koreader.sh
I'm not quite sure why I never actually noticed this brainfart before, but it's been stupid like this since basically ever.
(It was made obvious by the inittab changes in FW 4.25, which does a few more things on halt, which gave more time for the on-animator call from our nickel restart script to pop up...).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6880)
> [Kobo] Don't attempt to restart Nickel when asking for a reboot/shutdown

- frontend/apps/reader/modules/readerpagemap.lua
- frontend/ui/widget/dictquicklookup.lua
`Reference page numbers list: highlight current page` like it happens with the TOC
`Dict/Wiki: update footer on full refresh` so we can update the time (it currently isn't updated, although I think it used to work in the past) when reading a long definition or long Wikipedia lookup result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6888)
> Reference page numbers list: highlight current page

- frontend/apps/reader/modules/readerfooter.lua
- frontend/ui/widget/progresswidget.lua
With some screen sizes, the footer progress bar (in thick style) may be empty, because margins and borders take the full height. This should ensure that does not happen, by reserving at least 1 pixel for the actual progress bar.
Left: before the PR. Right: after
with `./kodev run -h=720 -w=1024`, for sizes 5 to 9 (which get scaled to 6 to 10, and the default border and margin are scaled to 2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6878)
> Ensure minimum height for the in-fill in progress bar

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readergoto.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/apps/reader/skimtowidget.lua
- frontend/document/credocument.lua
- frontend/document/document.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/widget/imagewidget.lua
- frontend/ui/widget/progresswidget.lua
- frontend/ui/widget/textboxwidget.lua
- frontend/ui/widget/textwidget.lua
This is the frontend implementation of https://github.com/koreader/koreader/issues/6809, to be merged after https://github.com/koreader/koreader-base/pull/1228 (see https://github.com/koreader/crengine/pull/391/ too)
The core of the implementation is pretty basic: just create `Document:getPrevPage` and `Document:getNextPage`, which return the prev/next page number. By default they are `page-1` and `page+1`, but if a document contains non-linear flows, they can be skipped. If already inside a non-linear flow, paging works normally, until the boundary is reached, where it continues on the main (linear) flow, skipping other non-linear flows that may be in-between. The non-linear pages are still accessible through links, goto, skim, bookmarks... it's only page back/forward that are affected …
> Support for hiding (skipping) non-linear EPUB fragments

- frontend/apps/reader/modules/readerrolling.lua
As an aside, it should be "ToC," not "Toc." ;-)
Cf. <https://github.com/koreader/koreader/pull/6847>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6895)
> [lang] Minor touch-up to non-linear info text

- plugins/coverimage.koplugin/main.lua
Remove leftover help_text and correct not to show an info message, when fallback is empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6897)
> Remove leftover and correct info message on empty fallback

- frontend/apps/reader/modules/readercropping.lua
Also remove the grey gap between the page and the buttons that would appear only when the footer is visible.
Suggested at https://github.com/koreader/koreader/pull/6885#issuecomment-731015316. It would look now like:
I switched OK and Cancel because we usually have OK on the right (although OK is somehow the most destructive - of the current crop settings - and I like destructive things on the left, less acccessible, but well, OK like all OKs.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6900)
> ReaderCropping: prettier bottom buttons

- frontend/luxl.lua
- frontend/ui/opdsparser.lua
- frontend/ui/widget/opdsbrowser.lua
By essentially dropping the whole XHTML block, instead of trying to salvage each and every tag one by one as we did before.
Also, as that's usually the result after broken parsing, handle nil URLs slightly better in the frontend, so that they get caught/reported properly instead of doing nothing and/or crashing half the time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6902)
> OPDS*: Mangle Calibre feeds some more so that they don't confuse luxl/us

- frontend/apps/reader/modules/readerfooter.lua
- frontend/ui/widget/progresswidget.lua
Some stuff was still hacked on manually instead of trusting the widget system to do things right, which it does, if you update the right stuff at the right time the right way ;). *This Is The Way*.
Fix #6893 (and address https://github.com/koreader/koreader/pull/6878#discussion_r523411883, because it was indeed redundant ^^).
Includes a bonus fix for a number of settings not being applied immediately in PDFs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6898)
> ReaderFooter: Cleanup some more messy dimensions handling

- frontend/apps/reader/modules/readertypography.lua
This PR is also an issue: some months ago (I don't record exactly when), it was possible to choose hyphenation from a big list, an latin hyphenation thanks to [this file](https://jperon.github.io/latin/Latin.pattern), generated from [this project](https://github.com/gregorio-project/hyphen-la) was possible.
Since the only option depends on "typographical rules":
- I tried to add the modification proposed in this PR;
- I edited `data/hyph/languages.json`, adding following lines:
```json
{
"name": "Latin",
"filename": "Latin.pattern",
"language": "la",
"left_hyphen_min": 2,
"right_hyphen_min": 2,
"aliases": ["lat"]
},
```
- I added [Latin.pattern](https://jperon.github.io/latin/Latin.pattern) into `data/hyph`.
I'd have expected `Latin.pattern` to be used as hyphen dictionary; but the only …
> Add Latin hyphenation

- plugins/coverimage.koplugin/main.lua
This PR requires https://github.com/koreader/koreader-base/pull/1233.
It allows to store the image depending on its extension, as PNG or as BMP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6904)
> Add functionality to write BMP-Images in Cover-Image

- .github/ISSUE_TEMPLATE/bug_report.md
So we can get the whole picture since the beginning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6920)
> bug template: [android] log native crashes too

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/device/generic/device.lua
- frontend/device/kobo/device.lua
- platform/kobo/koreader.sh
Should help prevent potentially puzzling issues whenever significant changes are made that require startup script tweaks (e.g., USBMS).
Also print a warning right after the update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6916)
> Kobo: Warn on restart if the startup script is outdated

- frontend/apps/reader/modules/readerview.lua
- plugins/statistics.koplugin/main.lua
`nextTick` was too early ;).
Prevents small hitches when turning the page for the page where this
triggers.
Apply the same trickery to the Stats DB insert, even if that one probably
had a much smaller impact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6917)
> AutoSave: Delay I/O until after the pageturn

- frontend/apps/filemanager/filemanager.lua
- frontend/device/android/device.lua
- frontend/device/generic/device.lua
Android nonsense nº 1458349
Switch between two storage volumes that cannot be accesed directly using the filemanager.
Fixes #6912 
Requires some changes in luajit-launcher. I will push them once I get a confirmation of https://github.com/koreader/koreader/issues/6912#issuecomment-734943107
Please review naming while we're waiting :smile:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6919)
> android: switch between internal and external sdcard

- frontend/ui/data/koptoptions.lua
Except potentially the likes of 0.7 vs. 0,7 but I'm not convinced that should be done by bothering translators.
Cross-ref to <https://github.com/koreader/koreader/pull/6885>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6928)
> [chore] Don't translate numbers

- frontend/ui/widget/buttonprogresswidget.lua
Change the text in the button from a hypen (-) to a
Unicode minus size (−, U+2212). This is the same width
as the + sign.
The NaturalLightWidget and FrontLightWidget controls
already use minus signs in this way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6939)
> Use Unicode minus in ButtonProgressWidget

- kodev
It was blowing up when find found multiple matches (c.f., gitter).
Warning: requires bash 4.4. It's not in Ubuntu 16.04, it is in 18.04. Is that good enough?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6935)
> kodev: Make the directory finding code work as intended (probably?)

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/infomessage.lua
Provided said InfoMessage exists, and is not taller than the Dict/Wiki popup itself.
Re #6932
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6934)
> ReaderDictionary: Avoid an irritating refresh when dismissing the InfoMessage

- Makefile
requires https://github.com/koreader/android-luajit-launcher/pull/264
I will upload slightly modified versions of 2020.11 with LZMA/ZIP that show a toast with the milliseconds spent uncompressing, for users to benchmark.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6881)
> android: switch compression to lzma2

- frontend/device/devicelistener.lua
That seems like an obvious mistake?
xref https://www.mobileread.com/forums/showthread.php?t=335341
(ping @zwim)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6946)
> Fix the frontlight gesture range scaling

- Makefile
Should be done regardless, not sure why it was in base but not in front, but also somewhat related to #6354 and #6947. Otherwise a value like `c/Program Files (x86)` causes a syntax error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6948)
> Quote PATH

- plugins/coverimage.koplugin/main.lua
This add JPG-support to CoverImage. It depends on https://github.com/koreader/koreader-base/pull/1241.
Changes: Switched to jpg as default as it is faster and produces smaller images than png. On slow devices the time is like roughly like PNG:JPG:BMP=2s:0.3s:0.2s. The size of jpg is much, much smaller than bmp.
It is also more sane to use jpg on a Tolino (which uses suspend_other.jpg) as screensaver image to make the image-format match the filename.
To discuss: I have selected a quality of 75 for jpg. The images look clear. A lower quality doesn't give much space savings.
This can be changed by the advanced user in `settings.reader.lua`  with `["cover_image_quality"] = xx,` if desired.
--- …
> Add JPG-support in CoverImage

- frontend/ui/renderimage.lua
- frontend/ui/widget/imagewidget.lua
Adds `RenderImage:renderSVGImageFile()` with 2 implementations:
- one using MuPDF (our current MuPDF 1.13 is not really good at it)
- the other using NanoSVG, via https://github.com/koreader/koreader-base/pull/1250, which is quite good (not really with our current SVG icons, but fine with those from #6937)
ImageWidget: allow picking SVG versions of provided PNG icons if available. To use, just drops SVG versions with the same name of the PNG we use in another directory, and set this variable in `frontend/ui/widget/imagewidget.lua`:
```lua
local ICONS_ALT_SVG_DIR
-- Uncomment to use SVG icons from one of these directories
-- ICONS_ALT_SVG_DIR = "resources/icons/src/"
-- ICONS_ALT_SVG_DIR = "resources/icons/svg/"
```
See #6937.
This should be a no-op if we keep `ICONS_ALT_SVG_DIR` blank. …
> RenderImage: add renderSVGImageFile()

- frontend/apps/filemanager/filemanager.lua
`FileManager:init` is called by `FileManager:reinit`, which caused duplicate
loads. Those can't be useful (for example to re-load a modified plugin
on runtime), as `PluginLoader:loadPlugins` memoizes loaded plugins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6958)
> FileManager: don't load already loaded plugins

- frontend/apps/filemanager/filemanager.lua
- plugins/gestures.koplugin/defaults.lua
- plugins/gestures.koplugin/main.lua
manage it in FM not in gestures, as  #6918 made the menu tap zone the entire width so the tap is not passed through to the gesture plugin
also do not allow changing the top right corner gesture in FM, as it does not do anything any more.
This is also in line with the home button handling.
regression caused by  #6918, touching the tap zones always manages to break something :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6957)
> FileManager: fix Plus menu override

- frontend/ui/data/koptoptions.lua
- frontend/ui/widget/configdialog.lua
Fix crash with RTL UI (little RTL UI specific layout bit not updated after #6885).
Also don't check show_func when sizing the names on the bottom menu, to avoid icons moving or resizing when toggling options. See https://github.com/koreader/koreader/pull/6885#issuecomment-735443154 and above:
> E minor aesthetically annyoing thing: when toggling Zoom to because of the different name_text show on the left, and their possibly different text size (Horizontal overlap is long :), the zoom for these names vs the room available for the widget may change: so, you have the widget images moving a bit, possibly changeing sizes to fit. I guess this will vary with language translation :)
May be we should take into account all the not enabled options' name_text into account to compute the left width? …
> Fix crash with RTL UI

- plugins/texteditor.koplugin/main.lua
Strange I didn't notice that before...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6979)
> TextEditor: fix some settings not sticking

- frontend/apps/reader/modules/readerview.lua
- frontend/apps/reader/modules/readerzooming.lua
This means it will warn when changing to continuous mode while
zoom to columns is active.
----
This doesn't fix #6822 but it's related to a fix since probably all members of `paged_modes` probably should also warn/autofix in reverse (i.e. when changing the zoom mode)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6970)
> Add columns to ReaderZooming paged_modes

- frontend/device/generic/device.lua
- frontend/ui/elements/screen_dpi_menu_table.lua
This was... not quite the case before.
Requires https://github.com/koreader/koreader-base/pull/1258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6984)
> Make sure getting rid of a DPI override actually restores default behavior

- README.md
The images stopped working, so they no longer look nice like they used to. Here's an excerpt from an e-mail they sent me on November 18, 2020.
> We’ve made the very difficult decision to shut down Sourcerer and have sold our intellectual property rights and trademarks to another organization. We are not disclosing the acquiring organization at this time, but, have discussed extensively how they may be used in the future and couldn’t be more impressed with how thoughtfully they’ve communicated with us their vision for the future.
>
> Sourcerer profiles will be live until March 31, 2021. We will not be updating the platform, fixing bugs, or accepting new signups effective immediately.
--- …
> Remove sourceror.io

- frontend/readhistory.lua
- spec/unit/readerfooter_spec.lua
- spec/unit/readhistory_spec.lua
* ReaderFooter: Account for the trimmed hour in the morning (re #6973)
* ReadHistory: Use fake timestamps to ensure reproducible results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6991)
> Tests: Make a few things more deterministic

- .github/workflows/build.yml
- doc/Building.md
- kodev
- tools/valgrind_amd.supp
* This means that stuff like passing a custom gdb frontend or custom valgrind args is now actually usable ;).
* Fixed the stock GDB invocation (passing args to the debuggee is... not straightforward).
* Only pass LD_LIBRARY_PATH to LuaJIT, not the script's env, because some GDB frontends (hi, nemiver) may have dependencies on libraries we ship, causing ABI breakages (e.g., happened for glib).
* Made the valgrind defaults slightly more aggressive
* Added a --callgrind shortcut for... callgrind
* Documented how to use a valgrind suppression file to tame mesa/drm on distros that don't build it w/ valgrind markings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6980)
> kodev: Use getopt instead of a hand-rolled hack

- frontend/apps/reader/modules/readeractivityindicator.lua
- frontend/apps/reader/readerui.lua
- platform/kindle/koreader.sh
And only actually flesh it out and register it in the very few cases
where it can actually do something (i.e., old FW 5.x with KPV).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7002)
> Kindle: Make ReaderActivityIndicator a stub

- frontend/ui/widget/iconwidget.lua
- frontend/ui/widget/imagewidget.lua
Also, instead of doing that every time, cache a pre-composited version
that matches the screen's BB type.
This is faster, and also has the advantage of making icon highlights
behave.
Jot down a few notes about corner-cases or future improvements, e.g.,
dimming icons on non-white backgrounds, and nightmode with color icons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7011)
> Implement proper alpha-blending of SVG icons

- defaults.lua
Forgot to update it during the revamps in #6918, meaning it starts much
higher than expected.
(Which also leads to a weird tiny gap between the classic & extended tapzone -_-").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7015)
> Fix y origin of the configmenu extended tapzone

- frontend/ui/widget/iconwidget.lua
Should be `DataStorage:getDataDir()` instead of `DataStorage:getSettingsDir()`.
(`koreader/icons/` instead of `koreader/settings/icons/`) https://github.com/koreader/koreader/pull/6977#discussion_r546375434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7019)
> IconWidget: fix user icons directory path

- frontend/ui/widget/buttonprogresswidget.lua
- frontend/ui/widget/frontlightwidget.lua
- frontend/ui/widget/naturallightwidget.lua
U+FF0B vs. U+002B
Because otherwise it is not, in fact, the same width as the minus, which looks weird in buttons ;).
Re #3840 & #6939
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7018)
> Use a full-width plus for buttons paired with a unicode minus

- frontend/ui/widget/networksetting.lua
Depends on https://github.com/koreader/lj-wpaclient/pull/6
Fix #7008
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7020)
> NetworkManager: Slightly more accurate wifi strength icons

- frontend/ui/widget/menu.lua
- frontend/ui/widget/opdsbrowser.lua
At a quick glance, it's only used by CloudStorage & OPDSBrowser
Which explains the weird potential for mixups in #7025
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7028)
> Menu: Clear path history on close

- platform/remarkable/koreader.sh
The seven billion different input devices on an rM make this trickier in
practice.
Plus, rM1 vs. rM2 platform differences...
Re #7033
Re #6992
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7038)
> rM: Switch to plain dumb sleep during the crash screen

- frontend/ui/data/creoptions.lua
- frontend/ui/widget/configdialog.lua
fixes #5978
We may want to get rid of fine_tune on them and just use the spinwidget for finer control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7021)
> Margins: allow direct input (more_options)

- frontend/apps/reader/modules/readerstatus.lua
if scrolling past the end of a document the EndOfBook event get fired once per scroll (a lot).
This can cause humorous results, ie. if the end action is set to `next book` a long enough scroll will go through a few books.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7035)
> Show only 1 End Document Dialog at a time

- frontend/apps/reader/modules/readeractivityindicator.lua
it was being overridden by the EventListener:new
caused by #7002
c.f. https://www.mobileread.com/forums/showthread.php?t=335886
@NiLuJe 
I didn't test this (don't have a KPV device) but it makes sense to me, please test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7041)
> ReaderActivityIndicator: fix isStub()

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/luasettings.lua
Attempts to do what was discussed in https://github.com/koreader/koreader/pull/6511#issuecomment-739545598 - should allow zooming images in PDFs.
TODO:
Make the defaults per extension and simplify extension handling (avoid duplicated code)
@poire-z any comments?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6960)
> Add fallback text selection to panel zoom

- frontend/device/android/device.lua
Depends on https://github.com/koreader/koreader-base/pull/1268
(The magic happens in base & android-luajit-launcher)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7042)
> Android: Avoid the Lua blitter

- frontend/device/input.lua
- frontend/ui/uimanager.lua
Cf. <https://github.com/koreader/koreader/pull/7044>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7050)
> Close Lua state on all os.exit() calls

- frontend/apps/reader/modules/readerdictionary.lua
That way images can be made to work in a more generic, portable manner, such as:
```lua
return function(html, dict_path)
html = html:gsub('<rref[^>]*>([^<]*%.jpg)</rref>', '<img src="'..dict_path..'res/%1">')
return html
end
```
Cf. <https://github.com/koreader/koreader/issues/6056>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7057)
> Pass dict_path to dictionary fix_html_func

- frontend/ui/size.lua
An utterly trivial thing but I think it looks a bit nicer if the button radius matches the windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7054)
> UI: Button radius matches default window radius

- frontend/device/remarkable/device.lua
Preserves the ghosting fix without the suspend crash from https://github.com/koreader/koreader/pull/7043
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7051)
> remarkable: poweroff.png ghosting fix

- frontend/device/remarkable/device.lua
Long explanation for a one-line change :)
Still a n00b, so my analysis might be off, but the end result works on my reMarkable 2.
High-level problem is that *sometimes* after starting koreader, "touchscreen" events (i.e. finger inputs, not stylus) are always interpreted as long-hold presses, no matter how brief the tap.
I think it comes down to the `_has_real_clock_time_ev_time` flag that only gets set *once* in `frontend/device/gesturedetector.lua`.
The timestamps on raw event data for the reMarkable 2 are definitely NOT real clock time.
If I got the log message "event times are real clock time: no adjustment needed" then touchscreen taps all got misinterpreted as holds.
If I got the log message "event times are not real clock time: some adjustments will be made" then everything worked …
> Time-adjust all reMarkable 2 events, not just EV_ABS

- frontend/device/remarkable/device.lua
While reMarkable 2 is suspended, pressing the power button wakes up the device but does NOT send an input event. So KOReader does not know the device has exited its suspend mode. Currently, the user has to press the power button twice: once to physically wake the device, and once to send the input event to KOReader.
This PR schedules a manual `UIManager:resume` call, which will trigger after the device wakes up from suspension.
Notes:
- I don't know if the reMarkable 1 has the same behavior quirk. If so, then it's simple enough to apply this same fix to both device types.
- I don't know if there's a cleaner way to guarantee a post-wakeup call.
- A zero-second wait in `scheduleIn` does *not* work; it triggers the `resume` call *before* the device actually suspends, i.e. before the …
> Fix reMarkable 2 "double-press power button required to wake up"

- frontend/util.lua
Rework #7027, with a tabulation instead of multiple `&nbsp;` to ensure a constant indentation when text
is justified. See https://github.com/koreader/koreader/pull/7027#issuecomment-752764752.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7095)
> htmlToPlainText(): tweak format paragraphs with indentation

- frontend/apps/reader/modules/readerfooter.lua
A trivial implementation of adding pages remaining to the status bar, for those times when you want to know how many pages remain and aren't up to doing the subtraction.
This is added to the Status bar settings:
This is how things look in the status bar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7047)
> Add pages remaining option to status bar

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/device/android/device.lua
- kodev
Requires https://github.com/koreader/android-luajit-launcher/pull/283 & https://github.com/koreader/koreader-base/pull/1279
Make it a real boy, i.e.:
* No longer flag it as `should_restrict_JIT`
* Allow disabling the C blitter
Tweak kodev to add a -d, --debug flag to log to catch the extra logging added in debug builds for LuaJIT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7094)
> LuaJIT on Android fixes

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerlink.lua
- frontend/apps/reader/modules/readerwikipedia.lua
- frontend/ui/trapper.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/confirmbox.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/infomessage.lua
More dictionary tweaks, following #7029: 
Don't cleanup input text as much when entered manually (or when it's sane) than when coming from book text selection.
This may allow looking up words like "-suffix", or do more precise Wikipedia queries.
I haven't have much need for this, but it was thought of as a possible solution to https://github.com/koreader/koreader/issues/6877#issuecomment-727192483 . Possible caveats: people who cut & paste crappy input may need to clean that input manually in the InputText widget.
Closes #6877.
Because sometimes I hit <kbd>></kbd> a few times to see what kind of results I got, and then want to quickly get back to the first result to start reading them.
Add `UIManager:discardEvents()`, to allow dropping events for a period of time.
Default duration of …
> More dictionary tweaks

- frontend/ui/data/creoptions.lua
- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/doublespinwidget.lua
By having the same DoubleSpinWidget launched when hitting <kbd>...</kbd> on any of Top margin or Bottom margin progress bars.
DoubleSpinWidget: remove blank space when no info_text.
Follow up to @yparitcher #7021, solving https://github.com/koreader/koreader/pull/7021#issuecomment-749389043:
>> We already have a 2-values picker for L/R Margin.
As when tweaking top or bottom, we may want to adjust the other, could it be the same 2-values picker allowing tweaking both top and bottom margin, when launched from either ... ?
(Probably less simple as the current tweaks so far :)
> not easy,
L/R are done with one event hence one picker with 2 values, T/B are 2 separate events and configdialog does not provide a way to tie them together.
so out of scope for now.
--- …
> CRE: allow both Top/Bottom margins fine tuning

- frontend/device/kindle/device.lua
- platform/kindle/koreader.sh
* Flag the K2/K2i & DX/DXg as `supportsScreensaver`, since these cannot be SO.
* On the K3 & the K4, where we can't detect SO properly, which means they are forcibly flagged as NOT `supportsScreensaver`, unbreak native screensaver handling by doing the SIGSTOP/SIGCONT dance with cvm. I'm fairly sure this used to be implemented, and/or I thought it was and never actually checked. In any case, it's probably been broken for ages.
Fix #7108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7112)
> Legacy Kindle: Unbreak screensavers

- plugins/coverbrowser.koplugin/main.lua
I was getting this:  (the lighter one is invisible on E-ink)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7106)
> add noop callback to cache size to prevent artifacts

- frontend/device/sdl/device.lua
- frontend/device/sony-prstux/device.lua
- kodev
- platform/android/llapp_main.lua
- platform/appimage/AppRun
- platform/cervantes/koreader.sh
- platform/debian/koreader.sh
- platform/kindle/extensions/koreader/menu.json
- platform/kobo/koreader.sh
- platform/mac/do_mac_bundle.sh
- platform/pocketbook/koreader.app
- platform/remarkable/koreader.sh
- platform/ubuntu-touch/koreader.sh
- reader.lua
it was sometimes crashing when opened with no args
Fixes: #7049
The behavior is now (in order of precedence).
1. open **file** passed on command line
2. show the Quickstart if not shown before.
3. if `start_with` is `last document` try to open the last document (confirming that it exists).
4. else if a directory was passed on the command line or `start_with` is defined with a FM based action start the correct action.
5. else show usage.
The reason I didn't prioritize a directory passed on the command line over `start_with` is that many of the launchers start koreader with the directory to start from by default so `start_with` would end up doing nothing.
--- …
> reader.lua: open the correct item / rework args handling

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/dictquicklookup.lua
- plugins/statistics.koplugin/main.lua
First Reset current book, then Reset other books by name, then Reset other books by duration - feels more logical than Reset current book sandwitched between the 2 others.
Regression (typo from cut and paste) from #6851. See https://github.com/koreader/koreader/pull/6851#issuecomment-754672318
Restore feature removed in #7029: tap on title to set dict of current result as a preferred dictionary for this document.
Changes from former implementation:
- trust sdcv for ordering, instead of doing it ourselves while looking at the results (which didn't always work)
- allow setting multiple preferred dicts
- order of preference is shown with a number as a prefix to the dictionary name in the title
- taping again allows removing it from preferred dicts, and taping again allows setting it back as …
> DictQuickLookup: re-add "tap on title" to set as preferred dict

- frontend/apps/filemanager/filemanager.lua
- reader.lua
Fixes: #7093 
~~Based on #7053 as they change the same file.~~
~~only the last commit is related.~~
we now do not have to reset the FM rotation at start when rotation is locked.
This only affects locked rotation (never change rotation), we will ignore defaults and use the way we left off last time.
If rotation is not locked the FM or book will override.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7096)
>  save rotation across restarts.

- frontend/apps/reader/modules/readercoptlistener.lua
This will allow to immediately see the results when changing the font size of the alternate status bar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7119)
> show AltStatusBar when changing the font size

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readertypeset.lua
- frontend/apps/reader/modules/readerwikipedia.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/scrollhtmlwidget.lua
- frontend/ui/widget/scrolltextwidget.lua
- plugins/statistics.koplugin/main.lua
We could scroll a definition with keys. Now, when reaching top or bottom, switch to prev/next result - like it happens when tap on left/right of definition. Requested in #7126.
Also includes a few fixes:
Closes #7123 
Also reword some "...canceled" to "...interrupted" for consistency, like done previously for dictionary lookup.
Optimisation for CRE from #7029 dd74194 made it not work with KOpt-based documents. Closes #7126.
See https://github.com/koreader/koreader/pull/6778#discussion_r553957794
As we can now tweak them independantly. See https://github.com/koreader/koreader/pull/7104#issuecomment-757338930
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7128)
> DictQuickLookup: allow continuous reading with key - and other fixes

- frontend/apps/reader/skimtowidget.lua
- frontend/ui/data/koptoptions.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/button.lua
- frontend/ui/widget/checkbutton.lua
- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/iconbutton.lua
- frontend/ui/widget/imagewidget.lua
- frontend/ui/widget/infomessage.lua
- frontend/ui/widget/keyvaluepage.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/radiobutton.lua
- frontend/ui/widget/touchmenu.lua
- frontend/util.lua
- plugins/statistics.koplugin/readerprogress.lua
So, err, this started as a simple investigation into why the SkimTo widget was so weirdly slow on Mk. 7 (spoiler: https://github.com/koreader/koreader-base/pull/1283/commits/926c294d87e90080fb68265c30a64a8f7069bfa9), and it turned into a weird revamp of how flash_ui highlights are handled ;p.
In short:
* Wherever possible, do an actual dumb invert on the Screen BB instead of repainting the widget, *then* inverting it (which is what the "invert" flag does).
* Instead of playing with nextTick/tickAfterNext delays, explicitly fence stuff with forceRePaint
* And, in the few cases where said Mk. 7 quirk kicks in, make the fences more marked by using a well-placed WAIT_FOR_UPDATE_COMPLETE
This revealed a fun amount of bugs and weird quirks, from widgets being completely reinstanciated on each …
> Revamp "flash_ui" handling

- frontend/ui/screensaver.lua
Regression since f67296942f9c28e76c9c45b27c3b8ad0c1dc7860
That's a bit of legacy/backward compat mess, because we now have an explicit "no background" setting, but the "disable" mode predates it (*and* the white bg option, for that matter), and as such, just assumes the the default magically morphs from black to nil in this mode.
I mistakenly reverted that bit of the hack in f67296942f9c28e76c9c45b27c3b8ad0c1dc7860 by "fixing" the check to actually honor settings ^^.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7124)
> ScreenSaver: Unbreak "disable" mode

- frontend/fontlist.lua
- frontend/persist.lua
- frontend/util.lua
- plugins/calibre.koplugin/main.lua
- plugins/calibre.koplugin/search.lua
- spec/unit/persist_spec.lua
- table dumps is what we're using now to get table persistence. It is pretty printed, uncompressed.
- binary dumps using bitser is needed for tables where human readibility doesn't matter. It is faster encoding, decoding and produces smaller cache files.
A test to show the difference in encoding/decoding speed and the result cache size
```
encoding table 1: bitser: 1161KB [84ms]| dump: 9118KB [429ms](7.85x size)
encoding table 2: bitser: 2332KB [179ms]| dump: 18259KB [975ms](7.83x size)
encoding table 3: bitser: 3524KB [291ms]| dump: 27439KB [1442ms](7.79x size)
encoding table 4: bitser: 4735KB [377ms]| dump: 36658KB [2092ms](7.74x size)
encoding table 5: bitser: 5946KB [503ms]| dump: 45876KB [2531ms](7.72x size)
encoding table 6: bitser: 7157KB [592ms]| dump: 55095KB [3163ms](7.70x size) …
```
> Table persistence

- frontend/document/credocument.lua
- frontend/ui/data/creoptions.lua
Includes:
- EPUB: fix truncated HEAD>STYLE stylesheet https://github.com/koreader/crengine/pull/405
- XML parsing: slightly better parsing of `<script>`
- Update German hyphenation patterns https://github.com/koreader/crengine/pull/406
- (chore) Silence some clang warnings https://github.com/koreader/crengine/pull/407
- (Upstream) CSS content: fix regression with open-quote/close-quote
- (Upstream) HTML lists: support the 'reversed' attribute
- (Upstream) Tweak list items disc/circle/square symbols
- 2-pages mode: option to skip geometry checks
CRE bottom menu: allow toggling Dual Pages in portrait mode. Closes #7129 
(I let in commented out the previous checks, just in case we need to tweak it after feedback, and because there are not many examples on how to use this current_func …
> bump crengine: parsing, lists, 2-pages fixes & tweaks

- frontend/device/android/device.lua
Mainly for HW rotation on notched devices. Depends on https://github.com/koreader/android-luajit-launcher/pull/288
Includes an untested fix/breakage to viewport handling on the small API range where we do that ^^.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7137)
> Bump android-luajit-launcher

- frontend/pluginloader.lua
To prevent name clashes on menus, when OTA updated. See https://www.mobileread.com/forums/showpost.php?p=4082337&postcount=4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7147)
> Mark calibrecompanion plugin as obsolete

- frontend/apps/reader/modules/readerfooter.lua
For battery level, show icon only
Reduce separator between items to " " from "  "
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7153)
> Make status bar prefix compact items a bit more compact

- frontend/ui/network/manager.lua
If we're in range of multiple known WiFi Access Points (including multiple instances of the same SSID), we don't need to keep trying to connect after the first successful connection.
Minimal change would have been replacing the `return` inside the `foreach` function with `return [a non-nil value]`.
But foreach is deprecated, and since I was touching the code anyhow, I figured I'd do that tiny update as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7121)
> Don't need to keep attempting WiFi connection after success

- frontend/apps/reader/skimtowidget.lua
Fixes #6866 
Replace InputContainer with FocusManager for easier DPad Handling.
Add ProgressBar jump via key Q to P, corresponds with 0% to 100%.
Tested on K3 and SDL. Should be safe for devices with touch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7163)
> Add skimming support for Non-Touch devices

- frontend/apps/reader/modules/readersearch.lua
- frontend/ui/widget/button.lua
- frontend/ui/widget/buttontable.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/touchmenu.lua
- frontend/ui/widget/virtualkeyboard.lua
- plugins/texteditor.koplugin/main.lua
* I'd failed to notice that ButtonTable *also* instantiates seven billion Buttons on each update. Unfortunately, that one is way trickier to fix properly, so, work around its behavior in Button. (This fixes multiple issues with stuff using ButtonTable, which is basically anything with a persistent set of buttons. A good and easy test-case is the dictionary popup, e.g., the Highlight button changes text, and the next/prev dic buttons change state. All that, and more, was broken ;p).
* Handle corner-cases related to VirtualKeyboard (e.g., Terminal & Text Editor), which screwed with both TouchMenu & Button heuristics because it's weird.
--- …
> Assorted fixes after #7118

- frontend/apps/reader/modules/readerfooter.lua
(crash, attempting to set compact items …in status bar [PB631]
Put wrappers around book_time_to_read nil value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7172)
> Fix bug raised in issue 7168

- plugins/calibre.koplugin/metadata.lua
- plugins/calibre.koplugin/parser.lua
- plugins/calibre.koplugin/search.lua
Repurposes parts of @WS64 manual parser to read huge json files.
~~Likely broken for json right now, for whatever reason I need to debug. It works fine with the manual parser.~~
rapidjson is 10x faster than manually parsing but manually parsing avoids OOM.
~~Do not review for the moment, as it is broken. Testing  is welcome but there's a 99'9% chance you'll lose faith in humanity.~~
Pinging @NiLuJe, as our chief calibre user: I hardcoded the max JSON file to 30MB. Files bigger than that are going to be parsed manually. I have no idea how many books can be fit in 30MB on calibre metadata. The two files I've tested are mine (200 books, 200kb) and @WS64 (50000 books, 186MB)
--- …
> calibre plugin: handle huge metadata files

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readercoptlistener.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/document/credocument.lua
- frontend/ui/data/creoptions.lua
- frontend/ui/elements/common_settings_menu_table.lua
Like we do when following links. Helps a bit on pages crowded with multiple chapters or highlights.
Closes #5961.
<kbd>![image](https://user-images.githubusercontent.com/24273478/105974134-df6c3d00-608d-11eb-8dd0-af56207f8dea.png)</kbd>
Fixes issue B from https://github.com/koreader/koreader/issues/7129#issuecomment-763602579
https://github.com/koreader/koreader-base/pull/1295
Includes:
- EPUB ncx TOC: allow items with an empty title https://github.com/koreader/crengine/pull/409
- resizeImage(): restore original scaling options code
- CSS: parse and store min/max-width/height
- Add getStyledImageSize() ensuring min/max-width/height
- renderBlockElementEnhanced(): ensure min/max-width/height
- 2-pages mode: add option twoVisiblePagesAsOnePageNumber …
> bump crengine, various dual-page and other tweaks

- frontend/apps/reader/modules/readercoptlistener.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/document/credocument.lua
- frontend/ui/data/creoptions.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/textwidget.lua
- frontend/ui/widget/touchmenu.lua
- spec/unit/readerfooter_spec.lua
Close #7201 (even if that's a shitty discussion and can't be closed...)
See #7176. Seems people prefer having both bars - and auto-removing the footer when toggling it is a bit bothering when you have footer's "Lock status bar" enabled.
People who really want only the top one can just disable the footer - so they can hide the top without havig the footer auto-shown back.
Feels more prectical to have them independant.
I'll rebase these 2 commits: the first is @zwim latest work on #7179 - the second my continuation.
(Haven't tested resume/suspend.)
@NiLuJe : what do you think about handling auto refresh in the footer the same way: a function called from all involved menu items and events to cancel/reschedule the refresh, with everything ready for auto refresh. The current footer bits that …
> Refresh AltStatusBar once a minute (continued)

- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/htmlboxwidget.lua
- frontend/ui/widget/imageviewer.lua
- frontend/ui/widget/keyvaluepage.lua
- frontend/ui/widget/scrollhtmlwidget.lua
- frontend/ui/widget/scrolltextwidget.lua
- frontend/ui/widget/sortwidget.lua
* Switching between HTML/text dicts (Fix #7209)
* Updating the scrollbar and scroll state properly when switching dicts
* Highlights in SortWidget
* Highlights in the Dictionary Download page
* Minor simplification of the tail end of the update process in ImageViewer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7212)
> Fix a few things after #7166

- frontend/apps/reader/modules/readercoptlistener.lua
- frontend/apps/reader/modules/readerfooter.lua
- spec/unit/readerfooter_spec.lua
Similar to how it's been done recently for CRe top status bar in #7211.
Continued from #7182. See https://github.com/koreader/koreader/pull/7211#issuecomment-770003153.
@NiLuJe : please have a look if that looks fine (at least, not worse than before)
It's a bit nightmarish with the self.mode vs self.view.footer_visible possibly getting out of sync when toggle from other modules...
So, there are probably some cases badly handled - but hopefully, it's not worse than before :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7213)
> Tweak footer auto refresh

- frontend/ui/data/keyboardlayouts/ka_keyboard.lua
- frontend/ui/widget/notification.lua
(Emptying my list of fun-things-todo list.)
From https://github.com/koreader/koreader/pull/7135#issuecomment-758292956 : 
> Some other idea about Notification: knowing with :onShow()/onCloseWidget() how many are shown, the Notification class could store the list of active/shown instances, so a new one could have another y - so they don't override each other, but are stacked above each others.
(Not that I care much about Notification, but seeing 3 of them hiding each other with Dispatcher is a bit ugly :)
<kbd>![stacked_notifs](https://user-images.githubusercontent.com/24273478/106473479-1a161100-64a4-11eb-9a07-870c143480e6.gif)</kbd>
--- …
> Notifications: stack them instead of overdrawing them

- frontend/apps/reader/skimtowidget.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/button.lua
- frontend/ui/widget/buttondialog.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/doublespinwidget.lua
- frontend/ui/widget/numberpickerwidget.lua
- frontend/ui/widget/scrollhtmlwidget.lua
- frontend/ui/widget/scrolltextwidget.lua
- frontend/ui/widget/spinwidget.lua
* By actually being aware of that fact, and delaying a single full repaint post-callback and post-unhighlight, in order to avoid flickering glitches (especially when flash_ui is enabled).
* Scroll*Widget: handle belonging to a translucent dialog properly on scroll.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7223)
> Button: Better handling of translucent MovableContainer

- frontend/ui/elements/reader_menu_order.lua
Reported by @pazos in <https://github.com/koreader/koreader/pull/7237#discussion_r570395126>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7239)
> [chore] Properly set CoverImage menu order

- frontend/ui/widget/textviewer.lua
It's used that way in a few contexts (e.g., View HTML).
Fix #7249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7255)
> TextViewer: Flag as a modal

- frontend/document/credocument.lua
- frontend/document/djvudocument.lua
- frontend/document/pdfdocument.lua
Doesn't include application/zip as CBZ, but it will be downloaded (as ZIP).
Doesn't include CBR since that's not supported.
Closes <https://github.com/koreader/koreader/issues/7218>, closes #5997.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7258)
> Add a few more mimetypes for OPDS

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/ui/elements/filemanager_menu_order.lua
- plugins/coverbrowser.koplugin/main.lua
Move classic file browser settings from CoverBrowser plugin into FileManagerMenu, so they are available when this plugin is disabled (as they also apply to everything based on Menu).
Disccused at https://github.com/koreader/koreader/issues/7141#issuecomment-774727373.
Updated screenshots:
<kbd>![image](https://user-images.githubusercontent.com/24273478/107204568-1a129580-69fd-11eb-8aac-83b03f34027a.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/107204582-20a10d00-69fd-11eb-98d0-910725c53cae.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/107204654-36aecd80-69fd-11eb-845d-5b4dad0c1fa4.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/107204463-fcddc700-69fc-11eb-80c9-25bae63e943c.png)</kbd> …
> File browser settings: reorganize into Settings submenu

- doc/Building.md
Add instructions for installing homebrew grep on MacOS since the macos version of grep fails with an error about the -z flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7266)
> Update macos instructions in Building.md to include homebrew grep

- frontend/device/cervantes/powerd.lua
- frontend/device/kobo/powerd.lua
This change is to improve the ramp-down of the warm-light.  Currently the warm light stays at 100% for 3 hours, and then drops to 50% and then 0%, meaning that you get a suddend and major change if you're still up reading at that hour.  If you set your max-warmth to 20:00 (8:00pm), then it'll be at max warmth at 8, 9, 10, then 50% at 11, and back to 0% at midnight.  
Ideally there would be a way to adjust these factors or to set the time at which it starts to return to 0% and calculate from there, which I might implement later if it doesn't look too hard, but for now this is still much better as it drops by 15% per hour giving you:
100,100,100,85,70,55,40,25,10,0 -- if you start at 8:00pm (as above) it'll be back to 0 at 5am.  If you start at 11:00pm, then it'll be back to the coolest …
> Improved ramp-down of warm-light after max hour

- frontend/device/cervantes/powerd.lua
- frontend/device/kobo/powerd.lua
Somewhat urgent PR, please merge before the next stable build -- the changes I made somehow made the warm light hours even worse, so I'm reverting them.
Even though I've plotted the output of the algorithm multiple times in both a spreadsheet, and copied the algorithm into Python and made the minimal changes necessary to make it work in Python and plotted the output using numpy and the algorithm is absolutely correct -- there's something VERY weird about the warm-light code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7296)
> Reversing commit 2348cd, changes to warmth values

- frontend/ui/widget/button.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/textboxwidget.lua
Some results fields were forgotten by the "smarter update" from #7212.
See https://github.com/koreader/koreader/pull/7166#issuecomment-779654246.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7300)
> Wikipedia results: fix images not updated across results

- frontend/ui/screensaver.lua
I still have that enabled on my test device from the last round of fixes, and I randomly noticed that with @poire-z's various test-cases, as HTML files don't really have metadata besides a title ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7314)
> ScreenSaver: Don't expand special tokens with an empty string

- frontend/apps/reader/modules/readertoc.lua
- frontend/readhistory.lua
- frontend/ui/widget/menu.lua
Add 2 convenience settings, allowing ToC ignored depths settings to apply further than just the progress bars.
See https://github.com/koreader/koreader/pull/7238#issuecomment-774729725 and followups.
<kbd>![image](https://user-images.githubusercontent.com/24273478/107854503-82f27700-6e1c-11eb-8f5c-c03145a5373e.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/107854495-73732e00-6e1c-11eb-9b3a-eff6a8894c43.png)</kbd>
Also includes:
~~#### Button: don't handle long-press when not enabled~~
~~It was only not handled when hold_callback. Do that also when hold_input/hold_input_func.
Menu: prevent long-press on "No choice available", as there's then no page to navigate to.
Closes #7276.~~
^ Updated commit included in hotfix #7300.
Mostly just so we don't get the …
> TOC settings: add bind chapter navigation/titles to ticks

- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/menu.lua
- frontend/util.lua
Fix #7316, #7317, #7318
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7322)
> A few UI fixes

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readertypography.lua
- frontend/apps/reader/modules/readerwikipedia.lua
- frontend/ui/widget/keyvaluepage.lua
- plugins/batterystat.koplugin/main.lua
- plugins/statistics.koplugin/main.lua
- plugins/systemstat.koplugin/main.lua
See https://github.com/koreader/koreader/issues/3620#issuecomment-777775675. Closes #3620.
Tweak building to start from items per page instead of a fixed item height.
Guess the best font size that fit.
Update separator specification from using a `"----"` to the now generic `separator=true` (this allows not wasting a slot for each separator in the page and not have only 12 items and 2 small lines in a 14 items page).
<kbd>![image](https://user-images.githubusercontent.com/24273478/107848564-a86b8a80-6df4-11eb-8468-64b0343ddea2.png)</kbd>
Before | After:
<kbd>![image](https://user-images.githubusercontent.com/24273478/107854793-a9191680-6e1e-11eb-8ee8-eafc98e37171.png)</kbd>
And when switched from the default of 12 (on my emulator with Screen DPI: small) to a custom value of 16: …
> KeyValuePage: configurable items per page

- plugins/coverimage.koplugin/_meta.lua
- plugins/coverimage.koplugin/main.lua
Standardizes case on `_meta.lua` and improves readability of the plugin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7309)
> Adjust wording of coverimage plugin

- frontend/ui/uimanager.lua
- frontend/ui/widget/button.lua
- frontend/ui/widget/checkbutton.lua
- frontend/ui/widget/iconbutton.lua
- frontend/ui/widget/keyvaluepage.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/radiobutton.lua
- frontend/ui/widget/skimtowidget.lua
- frontend/ui/widget/touchmenu.lua
- spec/unit/uimanager_spec.lua
Followup to https://github.com/koreader/koreader/pull/7325
----
* flash_ui: Yield to the kernel between the HL and the UNHL/CB to let the EPDC do its thing in peace.
* UIManager: Handle nils in task scheduling arguments.
* SkimTo: Use the same, thicker chapter nav icons as ReaderSearch (fix #7326).
* SkimTo: The bookmark toggle button doesn't require a vsync flag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7332)
> flash_ui: Workaround potential EPDC races

- frontend/apps/reader/modules/readertoc.lua
When showing TOC, expand/show TOC entries for all items on current page.
I.e.: when on this page:
<kbd>![image](https://user-images.githubusercontent.com/24273478/108775535-7a5b1880-7561-11eb-8676-04a8488b2bd2.png)</kbd>
ToC currently opens like this (possibly more accentuated since a482baac5 #7204, but a similar situation could have happened before):
<kbd>![image](https://user-images.githubusercontent.com/24273478/108775642-aaa2b700-7561-11eb-82ff-baaa36dc3716.png)</kbd>
It will now show:
<kbd>![image](https://user-images.githubusercontent.com/24273478/108775582-8d6de880-7561-11eb-8688-c43e9da4adcf.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7339)
> TOC: expand to show all chapter on current page

- frontend/ui/data/css_tweaks.lua
Includes:
- LVString: Fix a c/p issue in lString8::atoi64 https://github.com/koreader/crengine/pull/421
- LVTextFm: Simplify and fix resizeImage logic
- LVXMLParser::ReadText(): fix parsing at buffer boundaries https://github.com/koreader/crengine/pull/423
- TextLang: fix lang_tag first part comparison
- CSS font-family: fix parsing of 'inherit' and '!important' - Closes #6886.
- CSS: support a few -epub-* and -webkit-* properties
- Text fragment flags: add LTEXT_HAS_EXTRA
- CSS: add support for 'line-break' and 'word-break'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7342)
> bump crengine: CSS line-break/word-break, various fixes

- frontend/ui/widget/menu.lua
- frontend/ui/widget/sortwidget.lua
- plugins/coverbrowser.koplugin/covermenu.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
* Unify SortWidget's pagination button (it was using a tap_input, which is why I'd missed it ;)). (https://github.com/koreader/koreader/pull/7335#issuecomment-785628495)
* Menu*: Remove redundant screen-layout updates from `_recalculateDimen`, as it should only be concerned with item layout (https://github.com/koreader/koreader/pull/7335#discussion_r582072032)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7347)
> Minor followup to #7335
