koreader/koreader

frontend/apps/reader/modules/readergesture.lua

Hopefully pass through is clearer than ignore. Terms like capture and propagate are too jargon; almost no one without the specific domain knowledge would understand what that means.
Cf. https://github.com/koreader/koreader/issues/5204#issuecomment-521278649

[lang] Change 'ignore' to 'pass through'

---

frontend/apps/reader/modules/readergesture.lua

Ref: https://github.com/koreader/koreader/issues/5021#issuecomment-522308285
Close: #5021 
Before:
After:

Move tap x y corner to tap corner submenu

---

frontend/device/android/device.lua

Fixes  #5228  (by fixing my own stupidity on #5207)
Hopefully fixes #5221  on any problematic device (aside from Tolinos on fw10).

android bugfixes

---

doc/config.ld

[fix] Update LDoc config

---

.ci/check.sh
.circleci/config.yml
frontend/apps/reader/modules/readerdictionary.lua
frontend/apps/reader/modules/readergesture.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerlink.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/apps/reader/modules/readerstyletweak.lua
frontend/apps/reader/modules/readertypeset.lua
frontend/apps/reader/modules/readerview.lua
frontend/apps/reader/modules/readerwikipedia.lua
frontend/apps/reader/modules/readerzooming.lua
frontend/ui/data/creoptions.lua
frontend/ui/data/css_tweaks.lua
frontend/ui/data/optionsutil.lua
frontend/ui/quickstart.lua
frontend/ui/widget/configdialog.lua
frontend/ui/widget/hyphenationlimits.lua
frontend/util.lua
plugins/coverbrowser.koplugin/bookinfomanager.lua
plugins/goodreads.koplugin/main.lua
plugins/statistics.koplugin/main.lua
plugins/texteditor.koplugin/main.lua
plugins/wallabag.koplugin/main.lua

Because let's face it, it just looks much better this way.
Docker image update in https://github.com/koreader/virdevenv/pull/43
Discussion in https://github.com/koreader/koreader/pull/5238#issuecomment-523675211 and https://github.com/koreader/koreader/pull/4524

[CI] Switch to custom xgettext build to extract multiline strings

---

frontend/ui/data/optionsutil.lua

Somehow this one slipped through the cracks for years.

[chore, i18n] Translate "not set"

---

frontend/apps/filemanager/filemanager.lua
frontend/ui/widget/iconbutton.lua

Fix: Unable to hold top right corner in FileManager

---

frontend/apps/reader/modules/readerhighlight.lua
plugins/statistics.koplugin/main.lua

Fixes <https://github.com/koreader/koreader/issues/5255>.

[fix, i18n] Make two strings translatable

---

spec/unit/gettext_spec.lua

[fix, CI] Forgot to run luacheck

---

frontend/apps/reader/modules/readertypeset.lua
plugins/statistics.koplugin/main.lua

See https://github.com/koreader/koreader/pull/5000#discussion_r317392259
Btw @NiLuJe is that code path I reference in the second commit even still used?

[i18n, chore] Some translation stuff

---

plugins/calibrecompanion.koplugin/main.lua
plugins/coverbrowser.koplugin/bookinfomanager.lua

Some grammar/style, some fixes.

[lang] Miscellaneous improvements

---

.ci/check.sh
frontend/apps/reader/modules/readerrolling.lua
frontend/device/gesturedetector.lua
frontend/device/kindle/device.lua
frontend/document/pdfdocument.lua
frontend/ui/widget/container/framecontainer.lua
frontend/ui/widget/linewidget.lua
frontend/ui/widget/menu.lua
frontend/ui/widget/textwidget.lua
plugins/send2ebook.koplugin/main.lua

Cf. <https://github.com/koreader/koreader/pull/5244>.
Also update check.

[chore] Convert a couple more todos

---

Makefile

Forgotten line from https://github.com/koreader/koreader/pull/5268.

[fix] Cervantes package generation

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerpaging.lua

Fixes <https://github.com/koreader/koreader/issues/5265>.

[fix] Distinguish bookmark/page flipping in menu

---

Makefile

https://github.com/AppImage/AppImageKit/releases/tag/12

[AppImage] AppImageTool 12

---

frontend/apps/reader/modules/readerpaging.lua

See https://github.com/koreader/koreader/issues/5265#issuecomment-525626930

[UX] Ignore page flipping toggle while bookmark flipping

---

frontend/apps/reader/modules/readersearch.lua

Closes <https://github.com/koreader/koreader/issues/5054>.

[feat] Implement fulltext search direction

---

doc/Events.md
frontend/ui/event.lua

Also some minor grammatical fixes.

[doc] Add internal documentation references

---

frontend/apps/reader/modules/readerfooter.lua

See: https://github.com/koreader/koreader/pull/5203#issuecomment-525849264
Old memory icon: ⌨
New: ≡

[minor] New memory icon for footer

---

plugins/readtimer.koplugin/main.lua

See: https://github.com/koreader/koreader/pull/3420#pullrequestreview-71776459

[i18n, plugins] ReadTimer - better plural forms

---

frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua
platform/cervantes/koreader.sh

Supersedes #5081 
It was tested by @ZapperDJ in https://github.com/koreader/koreader/pull/5081#issuecomment-527653617

[Cervantes]: launch QBookApp from KOReader

---

frontend/device/cervantes/device.lua
platform/cervantes/koreader.sh

disable wifi before returning to QT, improved sysfs read

---

frontend/ui/widget/numberpickerwidget.lua

Messages in numberpicker widget

---

frontend/device/kobo/device.lua
frontend/device/wakeupmgr.lua
plugins/autosuspend.koplugin/main.lua

Enables logging just a few more things by default (cf. #5376) and fixes a few relatively minor issues. See individual commits for details.

A few autoshutdown tweaks

---

frontend/ui/elements/screensaver_menu.lua
frontend/ui/screensaver.lua

Cf. suggestion by @KenMaltby in <https://github.com/koreader/koreader/issues/3033#issuecomment-526657352>.

[feat] Allow setting any document cover as screensaver

---

frontend/apps/reader/modules/readerfooter.lua
frontend/ui/size.lua
frontend/ui/widget/button.lua
frontend/ui/widget/sortwidget.lua

Close: #5329 
- new option for footer - `Sort items`
- new widget `SortWidget`
Screenshots:

Sort footer elements

---

frontend/apps/reader/modules/readerfooter.lua

Fix: footer offset when orientation is changes

---

frontend/apps/reader/modules/readerfooter.lua

Fix: Incorrect width of separator line

---

frontend/ui/widget/spinwidget.lua

fix: Truncate text in spinwidget

---

frontend/apps/reader/modules/readergesture.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua

Closes <https://github.com/koreader/koreader/issues/5401>.

[feat, UX] Ignore hold corners

---

frontend/apps/reader/modules/readerfooter.lua

Close: #1933
New option that moves progress bar to separate line in footer.

Two lines footer

---

frontend/ui/data/keyboardlayouts/he_keyboard.lua
frontend/ui/data/keyboardlayouts/keypopup/he_popup.lua
frontend/ui/language.lua
frontend/ui/widget/virtualkeyboard.lua

english - hebrew keyboard first draft, without diacritics, will add them soon.
please review and let me know if i am doing it right, before i spend more time finishing it off.
also how can i change the menu title from en_HE ?
it looks like the hebrew variable name are failing circleci, how can i fix this?
thanks

Add Hebrew keyboard

---

frontend/device/kobo/device.lua

Doesn't seem to actually help, though?
Which doesn't make much sense to me, as the kernel hasn't changed on
that front...

Use the proper LED driver on the Libra

---

frontend/device/kobo/powerd.lua

I got my wires crossed.
It's fast on Mk. 5, slow on Mk. 7.
So, slow it down on Mk. 5 so we actually get a ramp and not a jump.

[Kobo] Unbreak the FL ramp-up/down.

---

frontend/apps/reader/modules/readerstatus.lua
frontend/device/generic/device.lua
frontend/device/sdl/device.lua
frontend/ui/widget/virtualkeyboard.lua

References <https://github.com/koreader/koreader/issues/5374>.
<hr>
@pazos This reflects my basic thought process on how to implement this. Most actions wouldn't do anything of course, basically just keyboard & hold. In using [performHapticFeedback](https://developer.android.com/reference/android/view/View.html#performHapticFeedback(int)) it would be up to the system whether it wants to do anything with it.

[feat] Add haptic feedback

---

frontend/apps/reader/modules/readerfooter.lua

See: https://github.com/koreader/koreader/pull/5403#issuecomment-536568163

Fix: Footer overflow screen after resize emulator window

---

plugins/wallabag.koplugin/main.lua

Currently, all the articles were converted to .epub by default. When
handling an article that linked to a .pdf file, it resulted in an
unreadable file.
This patch skips the conversion for a pdf file, and download it directly
instead.
I'm using the mimetype attribute of wallabag's articles to determine if they are pdf or not. Unfortunately this doesn't seem to cover every link correctly for some reason (e.g. https://www.usenix.org/system/files/sec19-sathaye.pdf is not recognized as a pdf by wallabag). Maybe looking at the extension of the link is better?
Since some pdfs were a little bit large, I had to extend the timeout, but I still got some errors reported at the end of the sync sometimes. How could I access the errors reporter to the logger?
Finally I reused the callApi function, …

[wallabag] fetch pdf files directly instead of converting them

---

frontend/apps/reader/modules/readerrolling.lua

When following or back from link, that marker is shown (here in dual pages mode):
<kbd>![image](https://user-images.githubusercontent.com/24273478/66158019-4fe38500-e625-11e9-882d-cfaa0000e942.png)</kbd>
This PR avoids this from happening when it is removed a second later:
<kbd>![image](https://user-images.githubusercontent.com/24273478/66158052-62f65500-e625-11e9-8f4c-c056b5c45d3b.png)</kbd>
or this when some background texture is used:
<kbd>![image](https://user-images.githubusercontent.com/24273478/66208144-b663b400-e6b4-11e9-9109-7a79f21c5f14.png)</kbd>

cre: properly unmark link position markers

---

frontend/ui/widget/toggleswitch.lua

Fix: Crash after change book status page

---

spec/unit/toggleswitch_spec.lua

To protect against issues like #5448.

[spec] Add ToggleSwitch spec stub

---

frontend/apps/reader/modules/readerhighlight.lua

Shows regular highlight dialog. Fixes #5455.
<hr>
<del>Perhaps slightly hackish.</del> <ins>Plus a couple of complementary crashes. ;-)</ins>
Anyway, just playing around.

WIP [UX] Add … button to highlight edit

---

frontend/ui/font.lua

Follow-up to #5458. Cf. https://github.com/koreader/koreader/issues/5381#issuecomment-539873843.

[Android, fix] Revert slightly more of the Noto business

---

platform/kobo/koreader.sh

(Because it gets tedious asking for it in every bug report ;p).

[Kobo] Log the FW/kernel version on crash

---

platform/kobo/koreader.sh

Cf. https://github.com/koreader/koreader/pull/5477#discussion_r334234063

[chore] Make ShellCheck happy

---

defaults.lua
frontend/apps/filemanager/filemanager.lua
frontend/apps/filemanager/filemanagerutil.lua
frontend/device/android/device.lua
frontend/fontlist.lua
frontend/ui/elements/font_settings.lua
platform/android/llapp_main.lua
spec/unit/defaults_spec.lua

Requires https://github.com/koreader/android-luajit-launcher/pull/195
Fixes #5487
~~to-do:~~
Removed: 
https://github.com/koreader/koreader/blob/5209493ba881f25e94cb4682d92416d515b2fb7c/defaults.lua#L238

android: fix ko paths when primary storage is a SD card

---

plugins/autosuspend.koplugin/main.lua

Should fix #5495.
Hat tip to @NiLuJe for saving my time by telling me where to look.

[fix, plugin] Remove wakeup task on resume

---

frontend/ui/widget/inputdialog.lua

Make it work out of the box, add some cross-references, and update a few minor things.
In response to @dontcrash.
Cf. <https://gitter.im/koreader/koreader?at=5dac431978e4974ace8c4213>.

[doc] Update InputDialog example

---

frontend/gettext.lua
spec/unit/gettext_spec.lua

Fixes <https://github.com/koreader/koreader/issues/5516>.
Cf. <https://github.com/koreader/koreader/pull/5515>.

[fix] GetText: Support Arabic plurals

---

doc/Building.md
doc/Porting.md

* Made Porting not so hilariously outdated.
* Minor tweaks to the macOS build instructions and the various quirks involved in getting it to behave.

Minor dev documentatioon tweaks

---

frontend/apps/reader/modules/readertypeset.lua

[fix] typo in #5522

---

frontend/ui/widget/timewidget.lua

Set max_width like in #5503 
Before:
After:

Handle max_width in time widget

---

plugins/evernote.koplugin/main.lua
plugins/kosync.koplugin/main.lua

Fixes https://github.com/koreader/koreader/issues/5415
Cf. https://github.com/koreader/koreader/pull/5452 https://github.com/koreader/koreader/pull/5573 https://github.com/koreader/koreader/pull/5574

[fix, plugin] Don't show full widget together with isOnline()

---

frontend/ui/widget/sortwidget.lua

Enable rewind button in sort widget

---

frontend/apps/reader/modules/readerdictionary.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerpaging.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/apps/reader/modules/readertypeset.lua

as per https://github.com/koreader/koreader/pull/5522#issuecomment-548006595 do not grey out the current default

default setting option always enabled

---

frontend/ui/widget/buttontable.lua

Same as the menu.
See <https://github.com/koreader/koreader/pull/5584>.

[UX] Switch ButtonTable to COLOR_GRAY

---

frontend/ui/widget/virtualkeyboard.lua

Required for <https://github.com/koreader/koreader/pull/5583>.

[feat] Support callback function in VirtualKeyPopup

---

frontend/apps/reader/modules/readergesture.lua

Close: #5576 
+ default multigesture east - west - east -> open `Favorites`,
+ ability to add new gesture to open `Favorites`

Gesture to open Favorites

---

frontend/apps/reader/modules/readerfooter.lua
frontend/ui/widget/touchmenu.lua
spec/unit/readerfooter_spec.lua

Update nerdfonts symbol codepoints for the updated version with no PUA

---

frontend/gettext.lua

[fix] Tailor plurals match

---

doc/Building.md

See https://github.com/Frenzie/koreader/commit/75d02a90380a813b14bb39dac028c894dc4d589a#commitcomment-36008019

[doc] Add coreutils to Mac brew dependencies

---

frontend/util.lua

Avoids costly divs & modulos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5625)

Rewrite unicodeCodepointToUtf8 w/ bitopt

---

frontend/util.lua

Close #5649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5651)

Translate file size unit

---

plugins/evernote.koplugin/clip.lua

fixes https://github.com/koreader/koreader/issues/5609
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5677)

fix, crash when exporting notes

---

frontend/apps/reader/modules/readerstatus.lua

Close: #5682
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5684)

fix: Crash FM after delete file from end of document action

---

.github/ISSUE_TEMPLATE.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5701)

crash.log for cervantes and android

---

.ci/after_success.sh
Makefile
README.md

Closes #3754.
Adds an automated source file push to the koreader/koreader-translations repo and a cute little badge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5713)

Finish Weblate migration

---

Makefile
platform/kindle/extensions/koreader/bin/koreader-ext.sh
platform/kindle/extensions/koreader/config.xml
platform/kindle/extensions/koreader/menu.json
platform/kindle/libkohelper.sh

Nasty symlink shenanigans meant we weren't actually shipping a required script...
Also, unclutter it while I'm here ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5715)

Unbreak the KUAL extension

---

Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5716)

[i18n] Use sort to keep POT order more stable

---

frontend/apps/filemanager/filemanagersearch.lua
plugins/SSH.koplugin/main.lua
plugins/coverbrowser.koplugin/main.lua

Fixes <https://github.com/koreader/koreader/issues/5712>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5719)

[fix] Various minor string issues

---

frontend/ui/uimanager.lua

Thanks to Weblate, see https://github.com/koreader/koreader/issues/3754
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5720)

[chore] Ellipsis instead of dots

---

frontend/gettext.lua

Fixes #5661.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5718)

[fix] Update hardcoded gettext workaround for Romanian

---

doc/Building.md
kodev

fixes connected to the migration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5722)

transifex -> weblate fixes

---

.gitmodules

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5726)

add metadata, to be used by fdroid

---

frontend/ui/elements/common_settings_menu_table.lua

See https://github.com/koreader/koreader/pull/5687#issuecomment-570226614 and followups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5729)

[fix, i18n] Auto-save book metadata: fix interval string

---

frontend/document/document.lua

See https://github.com/koreader/koreader/issues/5740#issuecomment-570767685. Closes #5740.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5742)

PicDocuments: fix crash on hold + pan

---

frontend/apps/reader/modules/readerhighlight.lua

Fix things after https://github.com/koreader/koreader/pull/5745
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5747)

[android]: share text with other apps - 2

---

frontend/ui/widget/logindialog.lua

See https://github.com/koreader/koreader/issues/5748#issuecomment-570945633. Closes #5748.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5749)

LoginDialog: fix crash on focus switch

---

doc/Building.md

See discussion in https://github.com/koreader/koreader-base/pull/1025#issuecomment-570556188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5743)

[doc] Add ragel to build prerequisites

---

.circleci/config.yml

See https://github.com/koreader/virdevenv/pull/46
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5753)

[CI] Docker koreader/koappimage:0.1.7 for ragel

---

frontend/apps/reader/modules/readerhighlight.lua

Swap left/right corners when inverse_reading_order. Closes #5750.
(Changed the variable names to be readable whatever the setting/UI direction is :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5751)

CRE multipage text selection: mirror corners when inverse_reading_order

---

.github/FUNDING.yml

@poire-z @NiLuJe @pazos @robert00s Come join the team. ;-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5770)

Add Liberapay link

---

frontend/ui/widget/textwidget.lua

Needs a base bump for https://github.com/koreader/koreader-base/pull/1031.
Needed for #5775.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5776)

TextWidget: adds getFittedText()

---

frontend/apps/reader/modules/readerfooter.lua

See: https://github.com/koreader/koreader/pull/5736#discussion_r371753606
Ref: https://www.mobileread.com/forums/showthread.php?p=3946432#post3946432
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5796)

Footer: extend min and max values for font size

---

frontend/ui/font.lua
spec/unit/document_spec.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5803)

Update fonts & add Devanagari

---

.ci/after_success.sh
.ci/before_install.sh
.ci/check.sh
.ci/common.sh
.ci/helper_luarocks.sh
.ci/helper_shellchecks.sh
.ci/install.sh
.shellcheckrc
kodev
platform/appimage/AppRun
platform/cervantes/disable-usbms.sh
platform/cervantes/enable-usbms.sh
platform/cervantes/koreader-standalone.sh
platform/debian/do_debian_package.sh
platform/debian/koreader.sh
platform/kindle/extensions/koreader/bin/koreader-ext.sh
platform/kobo/enable-wifi.sh
platform/kobo/koreader.sh
platform/pocketbook/koreader.app
platform/ubuntu-touch/koreader.sh
plugins/backgroundrunner.koplugin/luawrapper.sh
plugins/backgroundrunner.koplugin/wrapper.sh

Update shellcheck and shfmt to the latest version.
Fixes <#5152>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5809)

[CI] Add curly braces check

---

frontend/ui/otamanager.lua
platform/android/llapp_main.lua
platform/common/spinning_zsync
platform/kobo/koreader.sh

It's as easy as that ;p.
Requires https://github.com/koreader/koreader-base/pull/1036
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5810)

Switch to zsync2

---

README.md

As pointed out by @pazos in https://github.com/koreader/koreader/issues/4235#issuecomment-581489630
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5811)

[doc] Update donation info

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/filemanager/filemanagercollection.lua

Follow-up to <https://github.com/koreader/koreader/pull/5804>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5815)

[chore] Replace ... with … (ellipsis)

---

frontend/apps/filemanager/filemanagerfilesearcher.lua
frontend/ui/widget/filechooser.lua
plugins/coverbrowser.koplugin/bookinfomanager.lua

Re https://www.mobileread.com/forums/showpost.php?p=3949194&postcount=21
Makes it much faster if you happen to have a lot of crap in dot folders, like I do ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5816)

File search: Don't traverse hidden folders if we're not showing them

---

frontend/ui/widget/opdsbrowser.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5826)

Add searchable version of flibusta OPDS catalog

---

frontend/device/android/device.lua
frontend/ui/network/manager.lua

Fixes #5787
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5801)

[android]: nuke wifiManager

---

frontend/device/remarkable/device.lua

See https://github.com/koreader/koreader/pull/5828#issuecomment-583677718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5829)

[CI] Ignore unscaled size check on mt_width/height

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/skimtowidget.lua

hold the prev chapter button goes to beginning.
hold next chapter goes to the end.
add functionality without messing with the UI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5820)

skimto: add beginning and end as hold callback

---

frontend/ui/widget/filechooser.lua

Fixes <https://github.com/koreader/koreader/issues/5843>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5846)

[fix] More accurate count in FileChooser

---

platform/common/spinning_zsync

Thanks to our good friend tee ;).
As suggested by @Frenzie on gitter ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5842)

Log zsync2's output, too.

---

Makefile
frontend/ui/otamanager.lua
platform/cervantes/spinning_zsync
platform/common/spinning_zsync

Because everything is terrible.
Fix #5844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5850)

Unbreak OTA on crappy shell

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5839)

Add Remarkable to README.md

---

Makefile

Followup to #5850 ;).
Ooops. Thanks @avsej ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5853)

Actually ship the Cervantes version of spinning_zsync

---

frontend/apps/reader/modules/readerfooter.lua

cf. https://www.mobileread.com/forums/showpost.php?p=3946581&postcount=5 and https://www.mobileread.com/forums/showpost.php?p=3938492&postcount=5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5849)

Footer: bold font option

---

frontend/apps/cloudstorage/webdav.lua

As per https://en.wiktionary.org/wiki/e.g.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5855)

Spelling: e.g

---

frontend/apps/reader/modules/readergesture.lua

Cherry-picked changes from #5746 (not the comments).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5856)

Spelling: Wi-Fi, turn on/off, on/off

---

frontend/device/sony-prstux/device.lua
frontend/ui/uimanager.lua
platform/sony-prstux/set-wifi.sh
platform/sony-prstux/suspend.sh

Cherry-picked changes from #4567
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5857)

Prstux fixes

---

Makefile
kodev

c.f. https://github.com/koreader/koreader-base/pull/1048 & https://github.com/koreader/koxtoolchain/pull/22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5860)

Get rid of the old PB TC

---

frontend/device/pocketbook/device.lua

Closes #5887.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5890)

Add support for PocketBook InkPad X.

---

doc/Building.md

Following https://github.com/koreader/koreader-base/pull/1052
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5891)

macOS build info tweaks

---

plugins/kosync.koplugin/main.lua

Fixes #5832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5894)

kosync: validate username and password against empty/blank strings

---

frontend/apps/reader/modules/readerfooter.lua
frontend/ui/widget/touchmenu.lua

Discussion around https://github.com/koreader/koreader/issues/5359#issuecomment-590593945
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5898)

[i18n] allow translation of time (12/24-hours formats)

---

frontend/apps/reader/modules/readertoc.lua

Our code expects (rightfully) the TOC items to be ordered and to have increasing page numbers, but we may occasionally not get that from the engines (usually, because of bugs or duplicated IDs in the document).
Check for that and fix page numbers (possibly making them wrong) to have a working TOC.
Some details in https://github.com/koreader/koreader/issues/3062#issuecomment-402746843
Closes #3062. Issue also met in #5194.
That China.EN.epub fixed TOC would then appear as:
<kbd>![image](https://user-images.githubusercontent.com/24273478/75569878-40425e00-5a56-11ea-8171-9298bfeee6a1.png)</kbd>
(which is not super right, the real page number of that History entry is 14 - but I'm just attempting to have the TOC working, not to make tha page right, which is impossible, just less bogus enough …

TOC: validate and fix misordered page numbers

---

frontend/document/documentregistry.lua

Fixes <https://github.com/koreader/koreader/issues/5946>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5947)

[fix] DocumentRegistry: only add provider once

---

frontend/fontlist.lua

Fix #5950
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5951)

Blacklist a few Amazon Ember styles to get the main ones to behave.

---

frontend/luxl.lua
frontend/ui/opdsparser.lua

Apply the same crappy workaround than for BR.
Fix #5948
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5949)

Don't break OPDS parsing on HR tags.

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerfooter.lua
frontend/apps/reader/modules/readergesture.lua
frontend/apps/reader/readerui.lua
frontend/apps/reader/skimtowidget.lua
plugins/statistics.koplugin/main.lua

Fixes #5965
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5968)

Next/Previous Bookmark Gestures

---

frontend/ui/widget/opdsbrowser.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5982)

Add DJVU MIME type to OPDS browser

---

plugins/terminal.koplugin/main.lua

- Show output in a TextViewer with a monospace font.
- Include stderr, so errors are shown
- Use Trapper to allow interrupting command (and to fix some refresh issues)
Closes #5979.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5985)

Terminal plugin: a few tweaks

---

frontend/device/generic/powerd.lua
frontend/device/kindle/device.lua
frontend/device/kindle/powerd.lua
platform/kindle/koreader.sh
spec/unit/device_spec.lua

Fix #5986 
Probably breaks a bunch of random and weird corner-cases (Auto FrontLight plugin?). Meh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5989)

[Kindle] More accurate on/off FL detection/toggle

---

plugins/newsdownloader.koplugin/main.lua

Solves: #5924
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6003)

5924 nd force skip imasges dl

---

platform/kindle/koreader.sh

Should *hopefully* fix #5990 ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6009)

[Kindle] Try harder when restoring the title bar

---

frontend/device/remarkable/device.lua

This fixes issue #6030 and allows the ReMarkable pen to work as a touch input device.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6031)

Fix remarkable pen input

---

frontend/device/kindle/device.lua

Fix #6019
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6039)

[Kindle] Be more thorough when toggling WiFi

---

frontend/ui/widget/configdialog.lua

Fix issues reported at https://www.mobileread.com/forums/showthread.php?t=328880
See https://github.com/koreader/koreader/pull/3785#issuecomment-613063955
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6047)

Non-Touch: fix hang on bottom config menu navigation

---

.luacheckrc
defaults.lua
frontend/apps/reader/modules/readerdictionary.lua

Fixes #5995
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/5999)

stardict path override

---

frontend/optmath.lua
plugins/kosync.koplugin/main.lua
plugins/wallabag.koplugin/main.lua

Solves: #5045
Default is (as previous) off
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6048)

Wallabag remove from history setting

---

frontend/optmath.lua
plugins/kosync.koplugin/main.lua
plugins/wallabag.koplugin/main.lua

Fixes https://github.com/koreader/koreader/pull/6048#issuecomment-613978657:
```
Luacheck results
Checking plugins/kosync.koplugin/main.lua         1 warning
plugins/kosync.koplugin/main.lua:561:31: accessing undefined variable 'roundPercent'
Checking plugins/wallabag.koplugin/main.lua       1 warning
plugins/wallabag.koplugin/main.lua:1046:36: line contains trailing whitespace
Total: 2 warnings / 0 errors in 425 files
```
Was it unmerged? cause I'm getting all of my changes here?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6059)

fix errors on master

---

frontend/ui/widget/screenshoter.lua

Fixes #6055.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6062)

Screenshot: use month number instead of name

---

frontend/apps/reader/modules/readercropping.lua
frontend/ui/widget/bboxwidget.lua

See: #2003
In page crop:
physical press button = OK
physical back button = Cancel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6091)

Add support for physical button for page crop

---

plugins/kosync.koplugin/main.lua

See: https://github.com/koreader/koreader/issues/6022#issuecomment-618369408
Close: #6022
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6089)

kosync - new string methods

---

.gitignore
platform/kobo/koreader.sh
platform/kobo/nickel.sh

And a bit of future-proofing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6102)

Minor Kobo startup script cleanups

---

plugins/send2ebook.koplugin/main.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6118)

Send2Ebook - memory optimalization

---

frontend/apps/reader/modules/readergesture.lua

See: #6036
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6096)

[Gesture] Add go to first and last page

---

frontend/apps/reader/modules/readergesture.lua
plugins/kosync.koplugin/main.lua

New gesture:
- Push progress from this device
- Pull progress from other devices
Close: #5938
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6103)

[Gesture] Add progress sync gesture

---

frontend/device/android/device.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6123)

android: add a toggle to force haptic feedback in spite of system settings

---

frontend/device/android/dictionaries.lua

Fixes #6150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6154)

add eudic dictionary support

---

frontend/device/pocketbook/device.lua

It got worse with every new device added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6169)

clean PB device definition

---

plugins/wallabag.koplugin/main.lua

idea:
https://github.com/koreader/koreader/issues/6119#issuecomment-624329183
not tested yet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6170)

init wallabag queue

---

frontend/device/pocketbook/device.lua

Might need further tweaks. References <https://github.com/koreader/koreader/issues/6168>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6182)

[PocketBook] Add 515 and PB616W definition stubs

---

frontend/device/pocketbook/device.lua

References <#6168>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6183)

[PocketBook] Map d-pad key events

---

frontend/device/pocketbook/device.lua

References <#6168>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6184)

[PocketBook] Refine 515 model attributes

---

frontend/device/gesturedetector.lua

Prevent the Tap>Hold setTimeout'ed function to trigger on another later Tap.
Fix a Tap quickly following a Swipe (which triggers this Tap>Hold timer) from becoming a Hold.
I would often get that behaviour on my Kobo...
It's a bit harder to trigger on the emulator with the default gesture interval settings, but it become easier if you set Hold interval to 1000ms:
- do a few long-press on a word to get a feeling of how long this takes
- do a diagonal swipe (to full screen refresh) and then quickly a tap/short long-press : the hold will trigger quicker than previous feeling
I had hope that somehow this could magically fix the issue I have once a week of touch becoming unresponsive (https://github.com/koreader/koreader/issues/4431#issuecomment-455847181) - where my next tap after power button …

[fix] GestureDetector: prevent hold timers overlap

---

frontend/device/pocketbook/device.lua

Cf. <#4029>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6192)

[PocketBook] Add PocketBook 613 Basic definition

---

frontend/device/generic/device.lua
frontend/device/pocketbook/device.lua

This will allow to behave subtly different in certain instances.
Cf. <https://github.com/koreader/koreader/issues/4029>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6193)

[feat] Add Device:hasFewKeys()

---

platform/kindle/koreader.sh

This apparently fatally upsets the WM on FW >= 5.12.4
I don't have the HW to test it, and I've been saying FW 5.12.x is evil
from the get go, so, eh.
Re #6117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6204)

[Kindle] Don't resize the titlebar on FW >= 5.12.4

---

frontend/apps/reader/modules/readerfooter.lua
platform/debian/do_debian_package.sh

Also disable battery completely from defaults/option in desktop linux as it always return 0%
Background in #6210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6218)

fix missing glyphs by packaging freefonts again.

---

frontend/apps/reader/modules/readerfooter.lua

7d139263 / #6083 was preventing some features to work when lock status bar is enabled, so skip it in some cases:
- When toggling between top & bottom status bar (a tap is simulated to show the bottom bar).
- When in flipping mode (jumps to page at tap position).
- When toggling via menu (shown only when zero tap zone).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6225)

Footer: skip tap lock when needed

---

.gitignore
frontend/ui/elements/screensaver_menu.lua
frontend/ui/screensaver.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6238)

Allow message to be overlaid on other screensavers

---

frontend/document/credocument.lua
spec/unit/document_spec.lua

* Minor FreeFont update
* Noto Sans CJK downgrade to fix a number of issues w/ the git version
* Initial import of Noto Naskh Arabic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6242)

Update bundled fonts

---

frontend/document/koptinterface.lua

Fixes #6045 
Implemented @sr1920 suggestion at https://github.com/koreader/koreader/issues/6045#issuecomment-633215253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6247)

handle newlines in exported pdf highlights

---

frontend/device/sdl/device.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6248)

desktop: don't show `which` results on console

---

frontend/apps/reader/modules/readerfooter.lua

That's it: replace "static 10px" margins by a value that takes device DPI into account and works with rounded corner devices.
Fixes #6157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6260)

android: replace default footer margins.

---

frontend/optmath.lua

See <https://github.com/koreader/koreader/pull/6255#discussion_r438648691>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6258)

[doc] Add documentation to optmath

---

frontend/device/android/device.lua
frontend/device/generic/device.lua
plugins/kosync.koplugin/main.lua

Fixes #6237
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6266)

fix ANRs in Kosync plugin login/register

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readertoc.lua
plugins/evernote.koplugin/clip.lua
plugins/evernote.koplugin/note.tpl

closes #4566
closes #6138 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6146)

Add chapter title when exporting notes in Evernote(JSON/HTML, remote)

---

frontend/ui/translator.lua

This gives us result when doing same language -> same language translation
closes #6293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6295)

Translator: Add definition of the word to the translation

---

.github/ISSUE_TEMPLATE/feature_request.md

Follow-up to <https://github.com/koreader/koreader/pull/6291>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6296)

Add FR template

---

platform/android/llapp_main.lua
plugins/backgroundrunner.koplugin/main.lua

Also disables background runner plugin on android. It isn't unused by any plugin and somewhat breaks what an activity is on android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6300)

Fdroid: prevent runtime modification

---

doc/Collaborating_with_Git.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6289)

[doc] Add some tips about GitHub PR refs

---

plugins/wallabag.koplugin/main.lua

See <https://github.com/koreader/koreader-base/issues/594#issuecomment-484233915>.
LuaSocket takes care of everything now, so all similar code can be simplified.
Edit: To be clear, LuaSocket automatically calls LuaSec when appropriate. That way it also provides redirect support to LuaSec. LuaSec itself is still very much required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6307)

[chore, plugin] Simplify Wallabag http.request handling

---

frontend/ui/widget/opdsbrowser.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6335)

[feat] Add text/html to OPDSBrowser

---

frontend/ui/widget/opdsbrowser.lua

Cf. <https://github.com/koreader/koreader/pull/6307>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6334)

[chore] Simplify OPDSBrowser http.request handling

---

kodev

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6341)

[fix] Bring kodev cov command in line with kodev test

---

Makefile

closes koreader/koreader#6357
thanks @Frenzie
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6358)

do not link cache dir as it may already exist

---

frontend/apps/filemanager/filemanagercollection.lua
frontend/document/credocument.lua
frontend/util.lua

Fixes #6365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6366)

remove isAllowedScript leftovers

---

frontend/device/sdl/device.lua
frontend/ui/elements/font_settings.lua

The basic abstraction to be used in #6331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6360)

add mac ttf paths & simplify user fonts using Device.home_dir

---

doc/Building.md

Fixes https://github.com/koreader/koreader/issues/6354
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6368)

WSL extra bits

---

frontend/apps/reader/modules/readerfont.lua
frontend/device/devicelistener.lua
frontend/dispatcher.lua
frontend/ui/elements/filemanager_menu_order.lua
plugins/profiles.koplugin/main.lua

use `Device` and `Crengine` and soon `Mupdf` sections to organize the dispatcher menu and allow the user to know when the action will apply
add a few device settings/events to dispatcher and by extension profiles.
depends on koreader/koreader#6292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6364)

 Dispatcher: use sections

---

plugins/perceptionexpander.koplugin/main.lua

Closes #6376
as per @NiLuJe suggestion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6377)

Perception expander: disable margin increase when set to 0

---

frontend/device/kobo/device.lua

Obviously untested ;p
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6380)

Initial handling of the upcoming Kobo Nia

---

frontend/dispatcher.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6387)

[fix, lang] Filemanager → file browser consistency

---

frontend/apps/reader/modules/readerfooter.lua

thanks @poire-z
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6392)

Fix footer update on `UpdatePos` event. regression from #6292

---

frontend/apps/cloudstorage/ftpapi.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6363)

Fix issues #6362 - ftp corruption of binary files

---

frontend/cache.lua
frontend/document/document.lua
plugins/evernote.koplugin/clip.lua
plugins/kosync.koplugin/main.lua
plugins/statistics.koplugin/main.lua

Depends on <https://github.com/koreader/koreader-base/pull/1149>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6411)

[chore] Update MD5 calls with new sha2 library

---

frontend/apps/reader/modules/readerhighlight.lua

crengine returns the original source text from the HTML, which may include leading/trailing/consecutive spaces that would be collapsed when rendered on the page.
This removes them so the selected text is usually much nicer (but only when it's to be provided to some other stuff or saved - we keep working in here with the original).
Dunno really if it helps with PDF (looks like we don't get any `\n` with pdf; dunno if we can get spurious spaces, or trim valuable spaces) - and if people might prefer to have the raw data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6410)

Text selection: cleanup text obtained from engines

---

Makefile
frontend/apps/reader/modules/readerfooter.lua
frontend/device/generic/device.lua
frontend/device/input.lua
frontend/device/sdl/device.lua
frontend/device/sdl/powerd.lua
frontend/ui/widget/touchmenu.lua
platform/mac/do_mac_bundle.sh
platform/mac/koreader.sh

Follow up:  #6361
Fixes a nasty bug in catalina by preventing multiple app instances. More info in https://github.com/koreader/koreader/pull/6361#issuecomment-657123046
Pinging @JasonInOttawa for a review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6370)

some mac app fixes

---

frontend/apps/cloudstorage/ftp.lua
frontend/apps/reader/modules/readerbookmark.lua
frontend/ui/elements/common_settings_menu_table.lua

reported by sarigabor on mobileread https://www.mobileread.com/forums/showthread.php?t=331787
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6428)

allow text to be translated

---

plugins/coverbrowser.koplugin/bookinfomanager.lua

Reported by https://hosted.weblate.org/user/leschek/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6431)

[fix] Add plural string for number of books

---

plugins/statistics.koplugin/main.lua

Reported by @leschek
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6437)

[fix] Statistics: allow for proper translation of plural

---

frontend/apps/reader/modules/readerrolling.lua

Closes: #6434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6436)

recalculate footer progress bar correctly on `UpdatePos`

---

frontend/dispatcher.lua
plugins/profiles.koplugin/main.lua

there is no need to pass the caller rather just the table where the setting is located
passing the setting alone is not enough as sometimes it is nil an the you do not get a reference to its location
I realy overthought this the first time, i still have to get used to that in lua passing a table will refer to the original location, I an too used to C :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6435)

simplify Dispatcher

---

frontend/ui/network/manager.lua
frontend/ui/network/networklistener.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6438)

Minor cleanups after #6424

---

frontend/apps/reader/modules/readerhighlight.lua

Reported by @lescheck on Weblate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6452)

Update tesseract data files URL

---

frontend/dispatcher.lua

See https://github.com/koreader/koreader/pull/6428#issuecomment-667687997
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6462)

[chore] Allow translating "Font Size" in Dispatcher

---

frontend/device/android/device.lua
frontend/device/devicelistener.lua
frontend/device/generic/device.lua
frontend/ui/widget/frontlightwidget.lua

Reverts #5307 (not needed after #6426)
Fixes #6459
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6477)

bump luajit-launcher and remove frontlightwidget leftovers

---

plugins/calibre.koplugin/wireless.lua

Fixes #6485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6486)

calibre wireless: initialize inbox dir

---

plugins/kosync.koplugin/KOSyncClient.lua

I found that KOSync doesn't work with #6424 and since it was pretty simple I fixed it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6489)

Kosync network callback

---

frontend/dispatcher.lua

Fixes: #6516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6519)

Dispatcher: fix events with static argument

---

platform/kobo/enable-wifi.sh
platform/kobo/koreader.sh
platform/kobo/nickel.sh

Fix #6500 
(I'm back! :)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6522)

[Kobo] Unbreak Wi-Fi on FW >= 4.23

---

platform/cervantes/koreader.sh

Fixes #6537
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6550)

[cervantes]: check OTA updates on restart

---

frontend/dbg.lua
frontend/device/kobo/device.lua
frontend/ui/elements/mass_storage.lua
frontend/ui/uimanager.lua
platform/kobo/enable-wifi.sh
platform/kobo/koreader.sh
platform/kobo/nickel.sh
platform/kobo/obtain-ip.sh

All on our lonesome, for everybody, no custom setups required.
With pretty pictures, Wi-Fi support, ample logging and no lazy unmounts.
Requires a matching PR in base to bundle the tool, which I'll possibly do tonight if my brain doesn't give up before that ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6552)

[Kobo] Support USBMS exports

---

frontend/ui/elements/font-test-sample-default.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6571)

Fix typo in font test sample

---

frontend/device/devicelistener.lua
frontend/device/generic/device.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6568)

android: fix frontlight dialog gesture

---

frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/mass_storage.lua
frontend/ui/uimanager.lua
platform/kobo/koreader.sh

(... at least in theory ;p)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6566)

Allow i18n in KoboUSBMS

---

frontend/ui/elements/common_settings_menu_table.lua

not necessary after #6568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6578)

remove frontlightDialog leftover

---

frontend/ui/elements/common_info_menu_table.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua
frontend/version.lua
platform/kobo/koreader.sh

* Add some debugging in the startup script to aid in figuring out #6582 
* Bump KoboUSBMS for a minor tweak ensuring the final screen will never be optimized out by the EPDC
* Move some items around in the Hamburger menu to keep it single page (c.f., discussions in #6566)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6590)

More KoboUSBMS related tweaks & cleanups

---

frontend/device/android/powerd.lua

Has to be done, so that the frontlight toggle also works when started with frontlightSwitch==off.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6586)

turn on frontlight switch on Tolino.

---

frontend/device/android/device.lua
frontend/device/devicelistener.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6584)

update statusline after native light dialog

---

frontend/device/android/device.lua

tested on Epos2 and phone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6583)

resolve ANR on hold and native light dialog

---

frontend/ui/widget/filechooser.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6601)

Fix a few typos

---

plugins/terminal.koplugin/main.lua

With this changes you can enter multiple lines with commands and after viewing the output you can re-invoke the terminal with a button
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6599)

Terminal: support multiple lines and make it re-invokeable

---

frontend/device/pocketbook/device.lua

Needs https://github.com/koreader/koreader-base/pull/1168 and #6558
RFC #6545
This one is slightly stripped down compared to the gist.
Out of the box, it behaves exactly as native pocketbook apps should, ie aggressive standby, but no freezing at operations in progress.
Config UI will be done via koplugin that will also do adaptive standby. This is because the API is now device independent (albeit PB is the only implemented user).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6559)

Pocketbook new poll frontend

---

frontend/device/pocketbook/device.lua

This one slipped through tests somehow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6604)

Pocketbook frontend: Fix up missing require.

---

platform/kobo/koreader.sh

We know onboard is safe in these cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6603)

Detect early KoboUSBMS returns, and just restart KOReader

---

frontend/device/generic/device.lua
frontend/document/documentregistry.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/file_ext_assoc.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua

API and UI for external file associations, #6597
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6615)

Add API to set OS level file associations

---

platform/pocketbook/koreader.app

(ci script verified locally now)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6621)

Pocketbook: shfmt launcher script

---

frontend/device/pocketbook/device.lua

Turns out there's an IPC command for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6625)

Pocketbook: Add reboot option.

---

frontend/dispatcher.lua
plugins/terminal.koplugin/main.lua

As the title says...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6626)

Add gesture for invoking terminal emulator

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerfooter.lua

Optionally display number of bookmarks in footer. If no bookmarks defined, don't show this item
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6629)

Add bookmark count as footer item

---

platform/kobo/koreader.sh

It's not particularly pretty, but still better than shipping a 16MB font twice ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6639)

Update KoboUSBMS for CJK support

---

frontend/apps/cloudstorage/ftp.lua

Fixes #6636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6640)

ftp: guard against nil file

---

plugins/batterystat.koplugin/main.lua

Closes <https://github.com/koreader/koreader/issues/6057>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6646)

[Plugin] BatteryStat: consumed → charged for charging

---

frontend/ui/widget/opdsbrowser.lua

Re #6649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6653)

More verbose debug logging around OPDS caching

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/filemanager/filemanagercollection.lua
frontend/apps/filemanager/filemanagermenu.lua
frontend/apps/filemanager/filemanagershortcuts.lua
frontend/apps/reader/modules/readerdictionary.lua
frontend/apps/reader/readerui.lua
frontend/device/android/device.lua
frontend/device/kobo/powerd.lua
frontend/document/credocument.lua
frontend/readcollection.lua
frontend/readhistory.lua
frontend/ui/elements/menu_keyboard_layout.lua
frontend/ui/network/wpa_supplicant.lua
frontend/ui/translator.lua
frontend/ui/widget/keyboardlayoutdialog.lua
frontend/ui/widget/menu.lua
frontend/ui/widget/virtualkeyboard.lua
plugins/calibre.koplugin/wireless.lua
plugins/coverbrowser.koplugin/bookinfomanager.lua
plugins/coverbrowser.koplugin/covermenu.lua
plugins/evernote.koplugin/main.lua
plugins/gestures.koplugin/main.lua
plugins/profiles.koplugin/main.lua
plugins/statistics.koplugin/main.lua
plugins/terminal.koplugin/main.lua

Procrastination is fun! :D.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6657)

Minor util & ffi/util cleanups

---

frontend/device/pocketbook/powerd.lua

Account for InkView 5.x having different API for on/off states.
Fixes #6655
Needs https://github.com/koreader/koreader-base/pull/1185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6663)

Pocketbook: Fix frontlight handling.

---

plugins/autostandby.koplugin/main.lua

Got instantiated multiple times, when our state is meant to be global.
Fixes #6647
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6666)

Autostandby: Fix wrong assumptions about instance liveness.

---

frontend/device/pocketbook/device.lua

Hopefully, fix #6000
Depends on https://github.com/koreader/koreader-base/pull/1188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6669)

[PB] Fix WAIT_FOR_UPDATE_COMPLETE ioctl

---

frontend/ui/language.lua

Cf. <https://www.mobileread.com/forums/showthread.php?p=4036709#post4036709>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6689)

[fix] Czech is now cs, not cs_CZ

---

frontend/apps/reader/modules/readerfooter.lua

Cf. <https://www.mobileread.com/forums/showpost.php?p=4037153&postcount=8>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6692)

[i18n] Add missing bookmark count translation

---

platform/pocketbook/koreader.app

Much like on other platforms w/ an FBInk port ;).
Depends on https://github.com/koreader/koreader-base/pull/1192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6686)

[PB] Crash screen & OTA feedback

---

platform/kobo/koreader.sh
platform/kobo/nickel.sh

(When we can ^^).
Also bring in a few minor base updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6705)

Don't grab input devices on Kobo

---

Makefile

Forgot to ship the spinning_zsync helper script...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6722)

Unbreak OTAs on PB

---

frontend/document/tilecacheitem.lua
frontend/ui/widget/imagewidget.lua
plugins/coverbrowser.koplugin/bookinfomanager.lua

fixups for base bumped to https://github.com/koreader/koreader-base/pull/1201
otherwise tilecache breaks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6714)

blitbuffer: fixups for base

---

doc/Building_targets.md

And stop mentioning blatantly broken/outdated stuff.
Fix #6724
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6727)

[Dev docs] Steer people more strongly towards koxtoolchain

---

frontend/device/pocketbook/device.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6734)

Pocketbook: Fix silly rotation bug on PB740

---

frontend/ui/widget/filechooser.lua

* JIT wonkyness regressions since the BB tweaks (https://github.com/koreader/koreader-base/pull/1205)
* Better snapshot performance (https://github.com/koreader/koreader-base/pull/1206)
* Panel zoom memleak (https://github.com/koreader/koreader-base/pull/1207)
* strcoll shenanigans moved ffi/util (re #6751)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6753)

Bump base to bring in a few fixes & cleanups

---

frontend/apps/reader/modules/readerfooter.lua

Make the wonky "hide me if I'm off" behavior consistent and user-configurable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6754)

ReaderFooter: Make the wonky "hide me if I'm off" behavior consistent and user-configurable.

---

frontend/ui/data/keyboardlayouts/pl_keyboard.lua
frontend/ui/widget/virtualkeyboard.lua

Hi! I realized my second dream and I've added Polish keyboard layout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6762)

[UX] Add Polish keyboard layout.

---

README.md

Because @ezdiy has one (or more?) and is doing a great work with it.
I also have one (Touch HD3) which I don't use and I don't plan to use, so it's available for any contributor that wants to tinker with the platform. Thanks to @Cellaris for providing the device :smile:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6767)

Remove PB hardware requests

---

plugins/autostandby.koplugin/_meta.lua
plugins/autostandby.koplugin/main.lua
plugins/autosuspend.koplugin/_meta.lua
plugins/autosuspend.koplugin/main.lua
plugins/autoturn.koplugin/_meta.lua
plugins/autoturn.koplugin/main.lua

Also bump base
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6770)

Actually set sorting hints in plugins

---

frontend/device/generic/device.lua
frontend/device/remarkable/device.lua
frontend/ui/uimanager.lua
plugins/autosuspend.koplugin/main.lua

* Enable AutoSuspend (#6769)
* Better power events handling (#6676)
* Enable HW inversion, because I don't see why it wouldn't work ;p.
Many thanks to the actual testers and their feedback in the respective issues :).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6772)

A few reMarkable QoL fixes

---

frontend/device/kindle/device.lua
platform/pocketbook/koreader.app
spec/unit/readerview_spec.lua

* Fix #6780
* Tweak the PB crash screen so as not to comment on unsupported behavior ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6781)

A couple of hotfixes for 2020.10.1

---

frontend/device/android/device.lua

Fixes #6771
Fixes #6704
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6788)

bump LuaJIT, fix android native orientation logic

---

frontend/apps/reader/modules/readerfont.lua
frontend/ui/widget/bookstatuswidget.lua
plugins/coverbrowser.koplugin/bookinfomanager.lua
plugins/coverbrowser.koplugin/xutil.lua
plugins/statistics.koplugin/main.lua
plugins/statistics.koplugin/readerprogress.lua
spec/unit/readerfooter_spec.lua

This is essentially the continuation/culmination of both #6759 & #6761, many thanks to all those involved in the discussions and code :).
* Update the data collection format & handler to make it much less tortuous
* Update the pagecount & resync the stats on document layout changes
* Update the database schema to allow doing most queries against a SQL view that rescales the collected data to be accurate regardless of document layout (thanks to @marek-g for the SQL magic ;)).
* Add a "reset stats for current book" entry in the list of reset options, one that won't horribly break stats in said book ;).
* Fixed a couple of resource (SQL connection) leaks (in ReaderStatistics:getCurrentBookStats & ReaderStatistics:getCurrentBookStats).
* Flush stats to the DB on periodical metadata saves.
* …

ReaderStatistics: Data collection improvements

---

plugins/statistics.koplugin/main.lua

+ make CI happy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6796)

Bump base for sqlite.

---

plugins/statistics.koplugin/main.lua

Fixes the "current book" stats page.
(Regression in #6796)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6799)

Don't shadow gettext

---

platform/kobo/nickel.sh

~~There's still a stupid popup being shown, but at least it works.~~
Regression since #6522
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6800)

Ensure the SD card is actually detected in Nickel on exit.

---

plugins/statistics.koplugin/main.lua

* Don't stomp on an existing backup
* Try to handle inconsistent DBs better
Re: #6778
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6804)

Address some DB migration concerns

---

frontend/fontlist.lua
frontend/util.lua

Fixes https://github.com/koreader/koreader/issues/6819 (probably)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6820)

fontlist: Skip fonts with missing family_name

---

Makefile
platform/pocketbook/system_koreader.app

And make the system one a "symlink"
Fixes https://github.com/koreader/koreader/issues/6808
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6814)

Pocketbook: Use a single launcher

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/util.lua

Still thinking about #6768, I was wondering wether such changes could be approved (IMO in the same vein as `registerToMainMenu()`).
For example, this would allow to implement changes like f2194c1201575c940b30e1117fc195c4d50266f7 without modifying internal files, as follows:
```lua
local Device = require("device")
local EventListener = require("ui/widget/eventlistener")
local QRMessage = require("ui/widget/qrmessage")
local UIManager = require("ui/uimanager")
local _ = require("gettext")
local QRHighlight = EventListener:new{
name = "qrhighlight",
is_doc_only = true,
}
function QRHighlight:init()
self.ui.highlight:addToHighlightDialog("qrhighlight_QR", function(_reader_highlight_instance)
return {
text = _("QR"),
enabled = Device:hasClipboard(),
callback = function() …
```

Methods to modify highlight menu.

---

doc/config.ld
plugins/qrclipboard.koplugin/main.lua

Cf. <https://github.com/koreader/koreader/pull/6844#issuecomment-723672448>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6861)

[fix] Minor doc touchups re. QR encode

---

frontend/dump.lua
frontend/luasettings.lua

All is in the title.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6868)

Order keys in settings.reader.lua

---

plugins/coverimage.koplugin/main.lua

Forgotten period in text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6871)

Typo in Text

---

Makefile

- adaptative icons
- minify + shrink
- remove unused assets to save a few KBs
- install apk by clicking on notification after download (doesn't apply to F-Droid)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6870)

Android bundle

---

frontend/device/android/device.lua
frontend/device/thirdparty.lua

Fix for https://www.mobileread.com/forums/showpost.php?p=4058592&postcount=1
- User overrides marked as `false` were not checked
- Actions without app were skipped.
It seems that I forgot to check app picker settings :P
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6887)

android: fix dict overrides

---

plugins/coverimage.koplugin/main.lua

This should fix https://github.com/koreader/koreader/issues/6876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6884)

Scale cover image and add a background where necessary to better fit the screen

---

frontend/device/remarkable/device.lua
plugins/coverimage.koplugin/main.lua

Please see https://github.com/koreader/koreader/issues/6899 and https://github.com/koreader/koreader/issues/6899#issuecomment-732664106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6906)

Enable Cover-Image on Remarkable and PocketBook

---

frontend/apps/reader/modules/readerzooming.lua

@jperon Did my review comment about this get lost? :-/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6927)

[chore, i18n] Remove extra quotation marks

---

plugins/SSH.koplugin/_meta.lua
plugins/SSH.koplugin/main.lua
plugins/autoturn.koplugin/main.lua
plugins/docsettingtweak.koplugin/_meta.lua
plugins/docsettingtweak.koplugin/main.lua
plugins/gestures.koplugin/_meta.lua
plugins/hello.koplugin/_meta.lua
plugins/hello.koplugin/main.lua
plugins/profiles.koplugin/_meta.lua

*Especially* in the hello world plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6949)

[chore] Change single quotes to double quotes

---

frontend/document/picdocument.lua

As said in #6929
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6931)

JPG/PNG: MuPDF as default provider

---

frontend/apps/reader/modules/readerdictionary.lua
frontend/device/android/device.lua
frontend/device/generic/device.lua
frontend/util.lua
platform/android/llapp_main.lua

Requires https://github.com/koreader/android-luajit-launcher/pull/270
Requires https://github.com/koreader/koreader-base/pull/1255
Fixes https://github.com/koreader/koreader/issues/6613
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6959)

move unpackArchive to Device, use native version on android

---

.github/workflows/build.yml
datastorage.lua
platform/mac/do_mac_bundle.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6955)

[CI] Mac OS app

---

Makefile
kodev

Requires https://github.com/koreader/koreader-base/pull/1239
Closes #6782
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6909)

add target: debian-arm64

---

plugins/coverimage.koplugin/main.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6985)

[chore, plugins] CoverImage: move newline outside translated string

---

frontend/ui/opdsparser.lua
frontend/ui/widget/opdsbrowser.lua

By basically fixing *all* of them with a Lua pattern, instead of discovering new ones every few weeks ;).
Fix #6993
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6994)

Workaround luxl's issue with self-closing tags once and for all

---

frontend/ui/opdsparser.lua

Deal with hr/br in a single gsub call
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6995)

Quick optimization to #6994

---

frontend/ui/downloadmgr.lua
plugins/calibre.koplugin/search.lua
plugins/calibre.koplugin/wireless.lua

Force primary partition on Android file chooser
Scan external volumes on Android
Fixes #6943
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6996)

Calibre plugin fixes

---

frontend/device/remarkable/device.lua
platform/remarkable/koreader.sh

Cf. <https://github.com/koreader/koreader/pull/6992>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7009)

Minor formatting fixes

---

frontend/ui/widget/confirmbox.lua
frontend/ui/widget/infomessage.lua
frontend/ui/widget/multiconfirmbox.lua

This gives a more uniform look than having some boxes rectangular and some
with radiused corners
----
I probably missed some...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/6997)

Radius corners of more boxes

---

frontend/apps/filemanager/filemanager.lua

Fix #7005
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7006)

FileManager: Make reinit slightly less hackish

---

frontend/apps/reader/modules/readerdictionary.lua

Fixes <https://github.com/koreader/koreader/issues/3030>.
Cross-ref to <https://github.com/koreader/koreader/pull/6998>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7012)

[UX] Wait 0.5s before showing "searching for" dialog

---

platform/mac/do_mac_bundle.sh

(And support non-standard brew prefixes, just in case)
Depends on https://github.com/koreader/koreader-base/pull/1260
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7013)

macOS: Comment the brew shenanigans

---

platform/mac/do_mac_bundle.sh

Button was green in #7013. It was a lie :(.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7014)

macOS: Linting in do_mac_bundle

---

frontend/ui/widget/opdsbrowser.lua

Cf. <https://github.com/koreader/koreader/issues/7007>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7031)

Revert ManyBooks and Flibusta to HTTP

---

frontend/ui/widget/opdsbrowser.lua

Fix #7030
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7034)

OPDSBrowser: Update the title during navigation

---

platform/kobo/nickel.sh
reader.lua

Depends on https://github.com/koreader/koreader-base/pull/1263
TL;DR: because Android is the worst.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7023)

Rejig CBB toggling on startup to avoid an extra jit.flush

---

plugins/coverbrowser.koplugin/bookinfomanager.lua

Avoid opening two connections in //, by feeding the current connection
to saveSetting, like we were already doing for loadSettings...
It somehow worked just fine on Kobo/Emu, but blew up in fun and
interesting ways on Kindle, probably because of the Fuse proxy.
It was still pretty dumb nonetheless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7039)

BookInfo: Saner database migration

---

frontend/device/remarkable/device.lua

Most of this is scheduled with delays for reasons, so this was a stupid idea, my bad ;).
Fix #7033
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7043)

rM: Unbreak PowerEvents

---

frontend/apps/filemanager/filemanagermenu.lua
frontend/device/android/device.lua

And see how much stuff breaks \o/
Depends on https://github.com/koreader/android-luajit-launcher/pull/278 (to hopefully break less/more stuff :D).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7024)

Android: Don't mark the platform as should_restrict_JIT

---

frontend/ui/widget/opdsbrowser.lua

Fixes <https://github.com/koreader/koreader/issues/7007>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7032)

OPDS: Inform and warn about downgrade attack

---

frontend/util.lua

Cf. <https://www.mobileread.com/forums/showthread.php?p=4072308#post4072308>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7027)

htmlToPlainText(): More newlines on HTML paragraphs

---

frontend/cache.lua
frontend/device/android/device.lua
frontend/ui/rendertext.lua
frontend/ui/widget/container/inputcontainer.lua
frontend/ui/widget/container/widgetcontainer.lua

Depends on https://github.com/koreader/android-luajit-launcher/pull/281
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7059)

More Android trickery

---

plugins/coverbrowser.koplugin/bookinfomanager.lua
plugins/statistics.koplugin/main.lua

xref https://www.mobileread.com/forums/showpost.php?p=4073920&postcount=17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7063)

Simplify db migration toasts

---

plugins/calibre.koplugin/wireless.lua

Fixes #7064
The underlying issue wasn't reported, but at least we don't crash here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7067)

calibre: do not attempt to stop the socket if nil

---

frontend/apps/reader/modules/readerbookmark.lua

Fixes #7060.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7062)

Fix typo in "remove bookmark?"

---

frontend/ui/widget/touchmenu.lua

Fixes: #6940
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7074)

UI: Clicking menu icon returns to top of menu

---

frontend/apps/reader/modules/readerfooter.lua
frontend/device/kindle/device.lua
frontend/ui/network/networklistener.lua
frontend/ui/screensaver.lua

Stuff mentioned on Gitter over the last few days,, or that I encountered along the way ;).
(Rebase me, history is sane).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7113)

A batch of random fixes

---

frontend/pluginloader.lua
plugins/goodreads.koplugin/_meta.lua

And deprecate goodreads
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7101)

Add deprecation messages to plugins

---

frontend/dispatcher.lua

This allows the ConfigDialog to update properly
@poire-z 
Please see if this helps :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7116)

Dispatcher: correctly set document.configurable

---

frontend/apps/reader/modules/readercoptlistener.lua
frontend/apps/reader/modules/readerfooter.lua

Use the same wording, where possible (good for translations).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7130)

Align wording of AltStatusBar menu to the bottom one.

---

frontend/ui/uimanager.lua
reader.lua

Re #7096, Fix #7125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7133)

Remember the final rotation during Reboot/PowerOff/AutoSuspend, too

---

frontend/apps/reader/modules/readerfooter.lua
frontend/device/cervantes/device.lua
frontend/device/cervantes/powerd.lua
frontend/device/generic/powerd.lua
frontend/device/kindle/device.lua
frontend/device/kindle/powerd.lua
frontend/device/kobo/device.lua
frontend/device/kobo/powerd.lua
frontend/device/remarkable/powerd.lua
frontend/device/sony-prstux/powerd.lua
frontend/ui/network/networklistener.lua
frontend/ui/wikipedia.lua
frontend/util.lua
frontend/version.lua
plugins/systemstat.koplugin/main.lua
plugins/timesync.koplugin/main.lua
spec/unit/device_spec.lua

My eyes, they bleed.
May inadvertently help w/ #7045 (or make it worse, depending on how broken the kernel is ;p).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7149)

Cleanup eye-gouging madness around io.read calls

---

frontend/apps/cloudstorage/dropbox.lua
frontend/ui/data/css_tweaks.lua
frontend/ui/elements/screen_android.lua
frontend/util.lua
plugins/calibre.koplugin/wireless.lua
plugins/coverbrowser.koplugin/listmenu.lua
plugins/statistics.koplugin/main.lua
spec/unit/util_spec.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7154)

Address assorted Weblate comments

---

frontend/document/djvudocument.lua
frontend/document/documentregistry.lua
frontend/ui/widget/opdsbrowser.lua
plugins/wallabag.koplugin/main.lua

Fixes #5478.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7155)

[feat] Support mimetypes in DocumentRegistry:hasProvider()

---

plugins/coverimage.koplugin/main.lua

Eat this, github.
This continues the work from #7214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7221)

Better image fit (continued)

---

frontend/device/remarkable/device.lua
platform/remarkable/disable-wifi.sh
platform/remarkable/enable-wifi.sh

pinging @snelg and @gbyl for testing, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7216)

Remarkable1 wifi

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/ui/data/creoptions.lua
frontend/ui/widget/configdialog.lua
frontend/ui/widget/textviewer.lua

Fix #7230 & #7231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7232)

A couple of minor UI fixes

---

frontend/ui/data/keyboardlayouts/fa_keyboard.lua
frontend/ui/data/keyboardlayouts/keypopup/fa_popup.lua

Cf. <https://github.com/koreader/koreader/pulls#issuecomment-774345230>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7253)

[chore] Fix a few Persian keyboard luacheck issues

---

frontend/apps/reader/modules/readerhighlight.lua

Since #6851: some checks can't be done at init(), and have to be done at onShowHighlightMenu() time.
Closes #7248.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7250)

Highlight dialog: fix 'Follow Link' button not shown

---

frontend/ui/widget/menu.lua

Fix #7251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7254)

 Menu: Properly unhighlight menu items with a callback that doesn't do anything

---

plugins/opds.koplugin/opdsbrowser.lua

https://knihi.com/readers.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7263)

Add OPDS server from knihi.com (belarusian)

---

frontend/util.lua

Cf. <https://github.com/koreader/koreader/issues/7286#issuecomment-778855817>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7292)

[chore] Fix up util.stringStartsWith/stringEndsWith LDoc comments

---

frontend/apps/filemanager/filemanagermenu.lua
frontend/ui/elements/filemanager_menu_order.lua

Fixes #7290.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7291)

[fix] Remove OPDS menu entry from FilemanagerMenu

---

.github/workflows/build.yml
doc/Building.md

Fix #7307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7313)

Unbreak macOS build

---

frontend/apps/reader/modules/readerdogear.lua

Draw it below the CRe top status bar rather than over it.
It is ugly on the screenshot of first post of #7311. Should look better this way:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7312)

Bookmarks dogear: fix position with CRe top status bar

---

plugins/coverbrowser.koplugin/listmenu.lua

Should trigger when per-page <= 6/7, avoids authors and titles to become too big.
Discussed in #7278, a so-called "discussion" that this can't close. Trying it: Closes #7278.
Screenshots before/after in #7278 (good luck finding them in that useless piece of shitcussion).
(Changes the max for file info on the right from 16 to 18 as requested in there - we'll see if that feels too big.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7324)

CoverBrowser: list mode: limit font size of components

---

frontend/ui/widget/touchmenu.lua

Re #7262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7325)

TouchMenu: Workaround an EPDC race in the hold handler w/ flash_ui

---

frontend/apps/cloudstorage/cloudstorage.lua
frontend/apps/filemanager/filemanager.lua
frontend/apps/filemanager/filemanagermenu.lua
frontend/apps/reader/modules/readerwikipedia.lua
frontend/ui/cloudmgr.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/quickstart.lua
frontend/ui/screensaver.lua
frontend/ui/widget/pathchooser.lua
frontend/ui/widget/screenshoter.lua
plugins/calibre.koplugin/main.lua
plugins/movetoarchive.koplugin/main.lua
plugins/newsdownloader.koplugin/main.lua
plugins/send2ebook.koplugin/main.lua

Closes <https://github.com/koreader/koreader/issues/7157>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7328)

Standardize directory/folder to folder

---

frontend/device/kindle/device.lua

Otherwise, ScreenSaver handling doesn't work, duh'.
I have no idea how I managed to get that working the last time I tested
it :?.
Possibly I tested the final code on a K4 and not a K3?
Fix #7333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7336)

Legacy Kindle: Actually handle (system) power events

---

frontend/apps/reader/modules/readerlink.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7310)

show external link as QR code

---

frontend/apps/reader/modules/readercoptlistener.lua
frontend/apps/reader/modules/readerfooter.lua
frontend/ui/elements/screensaver_menu.lua
frontend/ui/widget/screensaverwidget.lua

Fix #7327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7334)

ScreenSaver: Delay footer/header repaint if screensaver_delay is enabled

---

plugins/opds.koplugin/opdsbrowser.lua

Remember, it's life +70 in US & EU, life +50 in Canada.
(It's actually slightly more complex than that, and some periods of
time/countries may use a far longer term. IANAL).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7351)

Get rid of OPDS libraries with content of dubious legal status.

---

frontend/apps/filemanager/filemanagerbookinfo.lua
frontend/apps/reader/modules/readertoc.lua
frontend/ui/widget/filechooser.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7363)

Fix nativation typo to navigation 

---

frontend/apps/filemanager/filemanagermenu.lua

Cf. <https://www.mobileread.com/forums/showthread.php?p=4098071#post4098071>.
----------
I'm not quite sure, thoughts?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7365)

Add explanation for shorten home folder

---

frontend/ui/widget/pathchooser.lua
plugins/opds.koplugin/opdsbrowser.lua

Cf. https://github.com/koreader/koreader/issues/7350#issuecomment-789672442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7386)

A few more directory to folder

---

plugins/opds.koplugin/opdsbrowser.lua

Cf. https://github.com/koreader/koreader/pull/7386#issuecomment-791555451
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7387)

Even more directory to folder

---

frontend/device/android/device.lua

https://play.google.com/store/apps/details?id=gaurav.lookuppro and its free version.
From https://www.mobileread.com/forums/showpost.php?p=4097548&postcount=8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7359)

Add a couple of modern android dicts

---

plugins/opds.koplugin/opdsbrowser.lua
spec/unit/opds_spec.lua

Regression since #7380 
(Also bump base for https://github.com/koreader/koreader-base/pull/1321 ;p).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7393)

OPDSBrowser: Unbreak test

---

frontend/device/kobo/device.lua
frontend/device/sony-prstux/device.lua
frontend/ui/network/manager.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7395)

Hold "Wi-Fi" menu to show network selection instead of auto-connecting

---

plugins/keepalive.koplugin/main.lua

Currently the "checked" mark does not work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7416)

Use PluginShare to share the keepalive state

---

doc/Building.md

To ensure it gets installed.
Cf. <https://github.com/koreader/koreader/issues/7409#issuecomment-800267291>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7421)

Add Lua 5.1 to sample Debubuntu apt-get command

---

frontend/document/documentregistry.lua
frontend/document/pdfdocument.lua

Regression since #7411
Fix #7456
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7457)

PdfDocument: Unbreak highlights

---

frontend/ui/data/koptoptions.lua

Cf. https://github.com/koreader/koreader/issues/7461#issuecomment-809582341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7462)

Improve fit to … help text

---

frontend/apps/reader/modules/readerfooter.lua

Fix #7464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7466)

ReaderFooter: Workaround a bad interaction with ReaderHighlight related to hold handlers

---

plugins/statistics.koplugin/main.lua

Regression since #7371
Fix #7470
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7471)

Statistics: Properly initialize default settings.

---

frontend/ui/elements/screensaver_menu.lua
frontend/ui/screensaver.lua

Awesome typo from #7371 ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7479)

ScreenSaver: Fix default settings

---

spec/unit/opds_spec.lua

See https://github.com/koreader/koreader/issues/7439
Not tested yet, have to figure out how to run tests first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7489)

Update tests in opds_spec for Gutenberg http -> https

---

frontend/apps/filemanager/filemanagerfilesearcher.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7493)

Add a period

---

frontend/apps/filemanager/filemanagerfilesearcher.lua
frontend/apps/reader/modules/readerdictionary.lua
frontend/apps/reader/modules/readersearch.lua
frontend/apps/reader/modules/readerwikipedia.lua
frontend/ui/widget/dictquicklookup.lua

Do not show "No results" notification when nothing entered to search for.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7501)

Search dialogs: correct response when nothing entered

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerview.lua

Re #6572 & #7497
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7505)

Two unrelated UX tweaks

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/filemanager/filemanagercollection.lua
frontend/apps/filemanager/filemanagerhistory.lua
frontend/apps/filemanager/filemanagermenu.lua
frontend/apps/filemanager/filemanagershortcuts.lua
frontend/apps/reader/modules/readerbookmark.lua
frontend/cache.lua
frontend/fontlist.lua
plugins/opds.koplugin/opdsbrowser.lua
reader.lua

* Move the fontlist cache out of Cache's territory, as discussed in #7510 
* Fix #7520 
* Fix #7518 
* Fix #7482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7524)

Bag'o fixes ;p

---

plugins/calibre.koplugin/wireless.lua

Pretty much exactly what @pazos suggested in https://github.com/koreader/koreader/issues/6399#issuecomment-725622329
Also submitting a corresponding tiny patch to @harmtemolder 's Calibre plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7492)

Calibre - send files back to calibre for sync

---

frontend/apps/reader/modules/readertoc.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7557)

fix for #7553: missing comma

---

frontend/apps/filemanager/filemanager.lua

c.f. https://github.com/koreader/koreader/issues/7477
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7559)

Filemanager: long-press the "+" button to refresh displaying content

---

frontend/apps/filemanager/filemanager.lua

fixes https://github.com/koreader/koreader/issues/7477
and complements https://github.com/koreader/koreader/pull/7559
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7564)

filemanager: add home button refresh

---

frontend/device/android/device.lua
frontend/device/generic/device.lua
frontend/device/pocketbook/device.lua
frontend/device/remarkable/device.lua
plugins/coverimage.koplugin/main.lua

Caching mechanism for CoverImage.
Suggestions are welcome.
This can solve some issues from https://github.com/koreader/koreader/issues/7506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7510)

Add a caching mechanism for CoverImage

---

frontend/apps/filemanager/filemanagermenu.lua

fixes: #7577
see prior art in #3935 #3933
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7580)

do not exit when opening unsupported file by last for FM

---

frontend/apps/reader/modules/readerconfig.lua
frontend/apps/reader/modules/readerpaging.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/page_turns.lua
frontend/ui/elements/reader_menu_order.lua

https://github.com/koreader/koreader/issues/6741 (second request) and https://github.com/koreader/koreader/issues/6071
Thanks to @NiLuJe for providing guidance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7572)

UI: Page Turns Menu

---

plugins/coverimage.koplugin/main.lua

For @hius07' sanity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7584)

[chore] Directory to folder

---

platform/kobo/koreader.sh
platform/pocketbook/koreader.app
platform/remarkable/koreader.sh

"Fix" #7581
Thanks to @tastytea for the tests ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7585)

PocketBook: Workaround platform shenanigans when aplying an OTA

---

frontend/apps/cloudstorage/ftp.lua
frontend/apps/cloudstorage/ftpapi.lua

Fixes #6390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7597)

CloudStorage (FTP): Do not buffer entire download in memory

---

plugins/coverimage.koplugin/main.lua

Sorry, one translatable missed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7603)

Missed translatable

---

frontend/apps/filemanager/filemanager.lua

Discussion and screenshots: https://github.com/koreader/koreader/issues/7554
Wordings;
Distinguish ffiles and folders;
Deny blank input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7582)

Filemanager: enhance file operations dialogs

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/reader/readerui.lua
frontend/pluginloader.lua

(instantiated, actually).
Re #7598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7607)

PluginLoader: Allow querying whether a specific plugin is loaded

---

frontend/ui/data/creoptions.lua
reader.lua
spec/unit/filemanager_spec.lua
spec/unit/opds_spec.lua

Fix #7617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7620)

Startup: Instantiate FileManagerHistory properly

---

plugins/coverimage.koplugin/main.lua

This is just a minor improvement in the menu display if the cachsize is turned off.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7611)

Better strings

---

frontend/apps/reader/modules/readerfont.lua

Fixes #7502
Let me know if instead of commenting out I should just remove the lines
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7589)

Remove notification popups when font face and size are changed

---

Makefile

Requires https://github.com/koreader/android-luajit-launcher/pull/305
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7649)

android: keep bundled version in a dedicated text file

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/reader/readerui.lua
frontend/ui/widget/filechooser.lua
plugins/opds.koplugin/opdscatalog.lua
reader.lua

Make it clearer that we actually store it in a *module/class* member, not an *instance* member.
Also, warn if there's a close/open mismatch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7658)

FileManager/ReaderUI: Clarify the current instance accessor

---

frontend/apps/reader/modules/readerfont.lua

Remove unused code as the event handlers belonging to that were remeved long ago (https://github.com/koreader/koreader/commit/30898a3cd8476b6a3ecae59eb7b0841a542e36fb)
See also https://github.com/koreader/koreader/pull/7623#issuecomment-836822042
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7665)

Remove dead code

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/reader/modules/readerview.lua
frontend/apps/reader/readerui.lua
frontend/device/generic/device.lua
frontend/ui/geometry.lua
frontend/ui/widget/configdialog.lua
spec/unit/device_spec.lua

We've managed to trip a few of those on dimen fields post-init but
pre-paintTo in a few weird corner-cases, a point at which dimen is often
nil.
ConfigDialog: Deal with that very thing in update()
Fix #7656
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7664)

Geom: nil guard a few rect methods

---

frontend/dispatcher.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7676)

[doc] Fix random typo

---

frontend/dbg.lua

Cf. <https://github.com/koreader/koreader/pull/7664#discussion_r631858784>.
---
@NiLuJe I didn't realize it had slipped under the radar back when I went on a doc writing spree, but I suppose I focused on things like util which are more directly relevant to new contributors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7677)

[doc] Documentation stub for Dbg module

---

frontend/device/generic/device.lua
frontend/ui/widget/configdialog.lua

* Unbreak restart-after-an-OTA
* Fix #7681 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7683)

Fix a couple of regressions

---

frontend/apps/cloudstorage/cloudstorage.lua
frontend/apps/cloudstorage/ftpapi.lua

References <https://github.com/koreader/koreader/issues/7688>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7694)

CloudStorage: log error

---

frontend/device/android/device.lua
frontend/ui/otamanager.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7695)

android: warn before downgrading APK

---

frontend/apps/reader/modules/readerhighlight.lua

Fix #7698
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7700)

ReaderHighlight: nil guard a few self.hold_pos accesses

---

plugins/coverimage.koplugin/main.lua

Round size of cached files up to multiples of blocksize.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7705)

[CoverImage] Use blksize for size of cached files

---

frontend/ui/widget/inputtext.lua

Continue of https://github.com/koreader/koreader/pull/7507, now for hold.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7687)

Inputtext: don't allow the cursor to move within a hint (hold)

---

frontend/apps/reader/modules/readermenu.lua
frontend/dispatcher.lua

This is the successor of "Fix crash with "open last document" gesture and no lastfile"  #7691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7716)

Crash with gestures

---

frontend/ui/uimanager.lua
frontend/ui/widget/datewidget.lua
frontend/ui/widget/dictquicklookup.lua
frontend/ui/widget/doublespinwidget.lua
frontend/ui/widget/frontlightwidget.lua
frontend/ui/widget/imageviewer.lua
frontend/ui/widget/infomessage.lua
frontend/ui/widget/keyboardlayoutdialog.lua
frontend/ui/widget/linkbox.lua
frontend/ui/widget/naturallightwidget.lua
frontend/ui/widget/notification.lua
frontend/ui/widget/openwithdialog.lua
frontend/ui/widget/qrmessage.lua
frontend/ui/widget/screensaverwidget.lua
frontend/ui/widget/skimtowidget.lua
frontend/ui/widget/spinwidget.lua
frontend/ui/widget/textviewer.lua
frontend/ui/widget/timewidget.lua
frontend/ui/widget/trapwidget.lua
frontend/ui/widget/virtualkeyboard.lua

That seems like a rather terrible idea to begin with, and one that may actually have fatal consequences at that.
Re #7738
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7744)

Events: Never stop propagating CloseWidget

---

frontend/apps/reader/modules/readerfont.lua
frontend/apps/reader/modules/readerview.lua

Also remove a double space pointed out by @NiLuJe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7773)

[lang] Improve "set to" consistency

---

frontend/apps/reader/modules/readertypeset.lua
frontend/device/pocketbook/device.lua
frontend/ui/widget/virtualkeyboard.lua
platform/pocketbook/koreader.app

* VirtualKeyboardPopup stuff mentioned in #7696
* A bunch of PB stuff (#7732, #7747)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7754)

A bunch of fixes

---

plugins/opds.koplugin/opdsparser.lua

Now that we can actually use it, thanks to #7767 ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7768)

OPDSParser: Attempt to preserve data from content tags *without* breaking luxl

---

frontend/ui/widget/inputdialog.lua
frontend/ui/widget/inputtext.lua
frontend/ui/widget/virtualkeyboard.lua

Discussion in https://github.com/koreader/koreader/issues/7100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7751)

VirtualKeyboard: hide the keyboard with the hold on 'arrow down'

---

frontend/apps/reader/modules/readerlink.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua

The inital location is useful to go back to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7685)

ReaderLink: add location to stack on opening book

---

plugins/SSH.koplugin/main.lua

Menu standardized to checkbox, an action added to dispatcher, infomessages added/extended.
--
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7765)

SSH server: redesign menu; add to dispatcher

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readertypography.lua
frontend/apps/reader/modules/readeruserhyph.lua
frontend/apps/reader/readerui.lua
frontend/document/credocument.lua

This is the successor of #7746.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7787)

Add custom hyphenation rules (second try)

---

frontend/ui/data/css_tweaks.lua
frontend/ui/widget/menu.lua

Now that I've finished reviewing the French translation, fix a few minor things I noticed along the way ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7786)

A couple of translation tweaks

---

spec/unit/version_spec.lua

Cf. https://github.com/koreader/koreader/issues/7805#issuecomment-855337115.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7809)

[chore, spec] Version: test 8-character hash just in case

---

frontend/util.lua

Fix #7818
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7829)

util.findFiles: Don't die on broken symlinks

---

frontend/apps/reader/modules/readercoptlistener.lua
frontend/apps/reader/modules/readerkoptlistener.lua
frontend/dispatcher.lua
frontend/ui/data/koptoptions.lua
frontend/ui/widget/configdialog.lua
frontend/ui/widget/touchmenu.lua

The parts of #7671 that are ready for merge.
I will add proper Kopt dispatcher support (the rest of #7671) when i have time.
Cleanup from #7626 
Dispatcher: indentation
TouchMenu: open to items page when going up a level
Kopt/Creoptions: change to using an event to update configurable. Abstract implimentation out of ConfigDialog
Please rebase not squash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7827)

Dispatcher fixes

---

platform/kobo/disable-wifi.sh
platform/kobo/enable-wifi.sh
platform/kobo/koreader.sh
platform/kobo/nickel.sh
plugins/statistics.koplugin/main.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7843)

Kobo: Handle various new stuff from FW 4.28+

---

frontend/document/koptinterface.lua
frontend/util.lua

#7837 & #7850
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7852)

A couple of quick fixes

---

frontend/document/doccache.lua
frontend/ui/widget/dictquicklookup.lua
platform/kindle/koreader.sh

Like, really not a lot, but, oh, well.
Re: #7853
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7858)

Another bunch of quick tweaks/fixes

---

frontend/ui/widget/inputtext.lua

Misprint from https://github.com/koreader/koreader/commit/4973134fb64f9ffd377eb1453d4bbc837e53136c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7880)

InputText correct misprint

---

plugins/opds.koplugin/opdsparser.lua

Fix #7899
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7900)

OPDS: Also handle self-closing dc: tags

---

frontend/apps/cloudstorage/cloudstorage.lua
frontend/ui/widget/menu.lua
plugins/opds.koplugin/opdsbrowser.lua

When we are deep inside the OPDS catalog, we need to press return arrow many times to get to the first page.
Propose to hold the return arrow to get this.
Requires a small addition to the Menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7845)

OPDS catalog, Cloud storage: return from the deep

---

frontend/apps/reader/modules/readerfooter.lua

Rebasement of https://github.com/koreader/koreader/pull/7835
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7903)

ReaderFooter settings menu: keep upper menu page

---

frontend/apps/reader/modules/readerdevicestatus.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7907)

Tweak clunky wording from #7857

---

frontend/apps/reader/modules/readerdevicestatus.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7910)

[minor] Fix ellipsis

---

frontend/apps/reader/modules/readerback.lua
frontend/apps/reader/modules/readerpaging.lua

code copied from ReaderBack
https://github.com/koreader/koreader/blob/c0386e5dd02014794e4715528b6e8ae82f287aba/frontend/apps/reader/modules/readerback.lua#L34-L43
Fixes: #7922
not sure if this is the right way to fix it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7923)

make sure ReaderLink gets a deep copy of location

---

frontend/apps/reader/modules/readerfont.lua

Fixes small issue noticed at https://github.com/koreader/koreader/discussions/7898#discussioncomment-962282
(Trying edits via GitHub web UI).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7934)

Font contrast: fix value in notification

---

frontend/ui/screensaver.lua

Fix #7938, exposed by #7929
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7941)

Screensaver: Fix an old w/h typo

---

frontend/apps/reader/modules/readersearch.lua
frontend/document/credocument.lua

This PR fix #7883  
Do not show checkboxes on pdf and mupdf documents, don't crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7947)

Fix checkboxes only shown on crengine; local retval

---

frontend/ui/widget/inputtext.lua
frontend/ui/widget/textboxwidget.lua

Now available in one-line inputs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7976)

InputText: up/down arrows move cursor to start/end of line

---

frontend/apps/reader/modules/readersearch.lua

Move indicator with search-dialog. (thanks to @poire-z )
Remove unused local vars. (thanks to @hius07 )
Code deduplication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7973)

Search: movable indicator, code dedup, unused vars

---

frontend/apps/filemanager/filemanagerfilesearcher.lua
frontend/apps/filemanager/filemanagermenu.lua
frontend/apps/reader/modules/readeruserhyph.lua
frontend/document/credocument.lua
frontend/util.lua

This could be a solution to #7950
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7956)

Case sensitive file search in filemanager

---

frontend/ui/widget/inputdialog.lua
frontend/ui/widget/inputtext.lua

Design thanks to @zwim.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7966)

Text editor: add case sensitive search

---

frontend/ui/data/onetime_migration.lua

Fixes https://github.com/koreader/koreader/issues/7979
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7980)

Fix date in onetime_migration

---

frontend/ui/widget/inputtext.lua

Continue and thanks to https://github.com/koreader/koreader/pull/7966#issuecomment-880831477
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7981)

Text editor: enable UTF-8 search

---

frontend/util.lua

Fixes: #7984
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7987)

secondsToHClock(): always floor seconds for consistency

---

plugins/send2ebook.koplugin/_meta.lua

See https://github.com/koreader/koreader/issues/7955#issuecomment-877625098
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7967)

Flag send2ebook as deprecated

---

frontend/apps/filemanager/filemanagermenu.lua
frontend/device/input.lua
frontend/device/kobo/device.lua
frontend/device/kobo/powerd.lua
platform/kobo/disable-wifi.sh
platform/kobo/enable-wifi.sh
platform/kobo/koreader.sh
platform/kobo/nickel.sh

Requires https://github.com/koreader/koreader-base/pull/1386
Fix #7890 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7986)

Kobo Elipsa support

---

doc/Events.md
frontend/dispatcher.lua
plugins/gestures.koplugin/main.lua
plugins/profiles.koplugin/main.lua

This fixes inheritance issues when changing documents.
prevents issues like #7716 & #7752
based upon work in #7671
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7999)

Dispatcher: use UIManager:sendEvent instead of the current instance

---

frontend/apps/filemanager/filemanagerhistory.lua

<kbd>![History](https://user-images.githubusercontent.com/62179190/126769924-d4203dfa-e354-4c6d-9e8a-d44f25a25959.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8016)

History: confirmation before cleaning

---

frontend/ui/elements/menu_activate.lua

3 states, 2 checkboxes
<kbd>![MenuActivate](https://user-images.githubusercontent.com/62179190/126770167-32588559-b847-4317-9df0-fc7c7f026722.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8017)

Activate menu: standardize to 2 checkboxes

---

plugins/evernote.koplugin/note.tpl

As suggested by @Frenzie: fixes https://www.mobileread.com/forums/showthread.php?t=340891
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8040)

add doctype to template

---

frontend/ui/widget/keyvaluepage.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8059)

[fix, lang] KeyValuePage: make "go to page" string translateable

---

frontend/ui/widget/sortwidget.lua

similar to #8059
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8061)

[fix, lang] sortwidget: make "go to page" string translateable

---

frontend/apps/reader/modules/readerstatus.lua

Go to the directory of the deleted file, instead of the folder you happend to switch into the reader from as this may have changed (via changing books from history etc)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8042)

ReaderStatus: end book action: delete file: go to current directory in FM

---

platform/kobo/enable-wifi.sh

Don't pass empty parameters to insmod, it apparently doesn't like it...
Fix #8075
Regression since a91ba05e349a1f6fe9ae8e77bace6d86dcbf13b6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8077)

Unbreak Wi-Fi on < Mk.8

---

frontend/apps/filemanager/filemanagerfilesearcher.lua

Required by https://github.com/koreader/koreader/pull/8056.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8073)

Filemanagerfilesearcher: allow call with a search string

---

plugins/coverimage.koplugin/main.lua

This should solve https://github.com/koreader/koreader/issues/8046.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8054)

[CoverImage] Add Grayscale BMP in 8 bit

---

README.md

I looked at the readme for this project over a year ago and it didn't say anything about improved performance, so I didn't bother to try it out. I don't really care about any of the features currently advertised.
I have learned that on my Kobo Aura HD, KOReader is _much much faster_ than the built in reading software. I wish I would have been using it this whole time! (see https://www.mobileread.com/forums/showthread.php?p=4147051&posted=1#post4147051 for my test videos if you're interested)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8090)

advertise the fact that it is FAST

---

frontend/apps/reader/modules/readerfooter.lua

See https://github.com/koreader/koreader/issues/7549#issuecomment-899090164. Closes #7549
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8093)

Footer: add "Include current page in pages left" setting

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8110)

Readme: add link to user guide

---

frontend/ui/widget/checkbutton.lua
frontend/ui/widget/inputtext.lua

Unused.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8108)

Checkbutton cleanup

---

plugins/opds.koplugin/opdsbrowser.lua

Fixes <https://github.com/koreader/koreader/issues/7995>.
--
This probably breaks some assumption, needs more thought.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8115)

[plugin] Change OPDS filetype algorithm to extension first, mimetype second

---

frontend/apps/cloudstorage/cloudstorage.lua
frontend/apps/cloudstorage/dropboxapi.lua
frontend/apps/reader/modules/readerwikipedia.lua
frontend/ui/cloudmgr.lua
frontend/ui/widget/filechooser.lua
frontend/ui/widget/pathchooser.lua
plugins/coverimage.koplugin/main.lua
plugins/opds.koplugin/opdsbrowser.lua
plugins/texteditor.koplugin/main.lua

Closes https://github.com/koreader/koreader/issues/8105.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8128)

Standardize select/choose to choose

---

frontend/ui/widget/virtualkeyboard.lua

Re: #8089
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8143)

VirtualKeyBoard: Switch to schedule-less visual feedback for flash_keyboard

---

frontend/ui/widget/frontlightwidget.lua

re: https://github.com/koreader/koreader/issues/8070#issuecomment-902162990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8144)

FrontLightWidget: Fix "Auto" max_width

---

frontend/pluginloader.lua

Fixes <https://github.com/koreader/koreader/issues/8152>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8153)

[plugin] Add GoodReads to obsolete plugins

---

doc/config.ld

Cf. https://github.com/koreader/koreader/pull/7983#issuecomment-908981240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8158)

Fix docs, evernote → exporter

---

plugins/calibre.koplugin/extensions.lua
plugins/calibre.koplugin/main.lua
plugins/calibre.koplugin/wireless.lua

Also include sensible defaults (epub as 1st option)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8146)

calibre: gui to choose default extension

---

frontend/apps/reader/modules/readerzooming.lua
frontend/document/document.lua
frontend/ui/geometry.lua
spec/unit/readerlink_spec.lua
spec/unit/readerview_spec.lua

* Requires https://github.com/koreader/koreader-base/pull/1407
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8170)

Document: Round dimensions properly in getPageDimensions

---

frontend/apps/reader/modules/readerhighlight.lua

Show translatable title of the style.
https://www.mobileread.com/forums/showthread.php?p=4151396#post4151396
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8174)

Readerhighlight: notification on changing style via gesture

---

README.md

Remove evernote & zsync mentions
also removing `online` as `over-the-air` is self-explanatory :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8177)

Readme: Tame down expectations

---

metadata/en-US/full_description.txt

Same as  #8177.
--
@pazos I didn't think of it until after I pressed merge. :-)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8178)

F-Droid description: tame expectations

---

frontend/apps/reader/modules/readersearch.lua
frontend/apps/reader/modules/readerstyletweak.lua
frontend/ui/elements/common_settings_menu_table.lua
plugins/gestures.koplugin/main.lua

Closes https://github.com/koreader/koreader/issues/8184.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8185)

Standardize: long-press/hold to long-press

---

frontend/document/doccache.lua
plugins/statistics.koplugin/main.lua

* Further tweak #8198
* Fix #8201
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8207)

A few minor tweaks

---

plugins/opds.koplugin/opdsbrowser.lua

Resolves this issue: https://github.com/koreader/koreader/issues/3023
Also added a bunch of comments along the way.
See line 533 and beyond for the fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8210)

Fix OPDS plugin bug wherein Arxiv PDF document acquisition URLs are not given a callback to download.

---

frontend/dispatcher.lua

Same as "Taps and gestures"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8215)

Dispatcher: adjust "screen and lights" to style guide

---

frontend/apps/reader/modules/readersearch.lua
frontend/ui/data/css_tweaks.lua

Closes https://github.com/koreader/koreader/issues/8203.
Fixes https://www.mobileread.com/forums/showthread.php?p=4154129#post4154129
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8217)

Help text fixes

---

plugins/newsdownloader.koplugin/epubdownloadbackend.lua
plugins/newsdownloader.koplugin/feed_view.lua

Fixes https://github.com/koreader/koreader/pull/8214#issuecomment-918856569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8220)

Fix undeclared variable error

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/reader/readerui.lua
frontend/pluginloader.lua

Closes https://github.com/koreader/koreader/issues/8228.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8230)

crash.log: write plugin regular information only in debug mode

---

frontend/ui/widget/progresswidget.lua

Closes https://github.com/koreader/koreader/issues/8191.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8195)

Progresswidget: invert read chapter marks

---

frontend/ui/widget/screenshoter.lua

Close https://github.com/koreader/koreader/issues/8224.
<kbd>![1](https://user-images.githubusercontent.com/62179190/133882583-37797689-8e9e-45a1-b3fb-169232032fc4.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8227)

Screenshoter: allow to set default folder from menu

---

frontend/document/credocument.lua

https://github.com/koreader/koreader/issues/8221#issuecomment-921528508
https://github.com/koreader/koreader/issues/8221#issuecomment-921535313
Closes https://github.com/koreader/koreader/issues/8221.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8232)

Fix segfault on exit after opening fb2.zip

---

plugins/autowarmth.koplugin/main.lua

Hopefully the last modifications.
Make the displayed information more beautiful and compact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8264)

Autowarmth: Make Information in easy mode more beautiful

---

plugins/newsdownloader.koplugin/main.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8267)

[chore] NewsDownloader: remove stray space

---

plugins/newsdownloader.koplugin/main.lua

Follow-up to <https://github.com/koreader/koreader/pull/8267>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8268)

[chore] NewsDownloader: various minor string fixes

---

plugins/statistics.koplugin/main.lua

closes #8266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8273)

Allow for always counting page as read, regardless of time spent

---

frontend/ui/widget/virtualkeyboard.lua

Closes https://github.com/koreader/koreader/issues/8260.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8276)

Virtualkeyboard: grey umlaut mode key

---

plugins/autowarmth.koplugin/main.lua

This should fix https://github.com/koreader/koreader/issues/8293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8295)

[Autowarmth] Fix bug when leaving/entering FM/reader

---

frontend/ui/widget/textboxwidget.lua

re: https://github.com/koreader/koreader/pull/8275#issuecomment-933744596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8298)

TextBoxWidget: Unbreak Wikipedia (bis)

---

.circleci/config.yml

See https://github.com/koreader/virdevenv/pull/69 for details
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8305)

[CI] Fix certificate issue with quick 0.1.8

---

frontend/apps/reader/modules/readergoto.lua

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8395)

ReaderGoto: go to %

---

plugins/autowarmth.koplugin/suntime.lua

This PR will fix https://www.mobileread.com/forums/showthread.php?t=342905
Also fixes a few comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8434)

[Autowarmth plugin] Fix sanity check for longitude

---

frontend/document/koptinterface.lua

Previously getTextFromBoxes would just pass the first and last three
bytes of the current and previous words when trying to detect CJK
characters (which shouldn't have spaces inserted).
However, this handling was not correct because CJK characters can be
longer than 3 bytes, and internally BaseUtil.utf8charcode doesn't ensure
that it was only given a single utf8 character (it blindly does the bit
operations on whatever length code you give it).
As a result, before this patch selections in PDF documents would have
lots of spaces stripped because getTextFromBoxes would think that almost
all characters were CJK characters.
Fixes: 6f1b70e5eb71 ("util.utf8: improve CJK character detection")
Fixes #8433 
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
--- …

kopt: correctly handle CJK character detection for space insertion

---

frontend/ui/widget/listview.lua

little fix for a little typo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8444)

Fix typo in ListView doc

---

frontend/apps/reader/modules/readersearch.lua

Minor optimization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8450)

readersearch: do not show regexp checkbutton in pdf

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/reader/modules/readerback.lua
frontend/ui/elements/common_settings_menu_table.lua

* Optimize the navigation and document menu code.
* Switch to colons in the navigation menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8442)

Navigation menu: Colons

---

frontend/apps/reader/modules/readerdictionary.lua

Fuzzy searching doesn't work with CJK text because sdcv doesn't handle
CJK text particularly well when fuzzy searching. With Japanese, fuzzy
searching results in large numbers of useless results because sdcv
decides to strip off the wrong part of the word when fuzzy searching.
For a specific example -- 喋られる is "fuzzy searched" by removing the
喋 kanji and searching for られる with some other fuzzy factors, which
results in hundreds of results. However, none of these results are 喋る
(the correct result) because the first step removed the only part of the
word being searched that is relevant. With the Japanese plugin, KOReader
can correctly auto-select and lookup any gramatically correct Japanese
word, meaning that fuzzy searching is not only unnecessary but also
detremental (for any failed …

reader: dictionary: disable fuzzy searching for CJK words

---

frontend/apps/reader/modules/readerdictionary.lua
frontend/ui/elements/common_exit_menu_table.lua
frontend/ui/elements/common_info_menu_table.lua

Introduced in #8459 , https://github.com/koreader/koreader/pull/8459#issuecomment-974867448
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8461)

[chore] Fix a few luacheck errors

---

frontend/apps/reader/modules/readerfooter.lua

Follow-up to <https://github.com/koreader/koreader/pull/8424>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8465)

[chore] Fix "Compact items" capitalization

---

frontend/ui/elements/common_settings_menu_table.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8466)

[chore] Change "filebrowser" to "file browser"

---

platform/kindle/koreader.sh

We don't ship it anymore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8471)

Kindle: remove zsync plugin iptables rules

---

plugins/gestures.koplugin/main.lua

~~Code borrowed from ReaderFooter~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8474)

multiswipe menu: keep the same parent page for going up from submenu

---

frontend/ui/geometry.lua
frontend/ui/widget/confirmbox.lua
frontend/ui/widget/datetimewidget.lua
frontend/ui/widget/imagewidget.lua
frontend/ui/widget/inputdialog.lua
frontend/ui/widget/multiinputdialog.lua

This PR is a work in progress.
Here I will add documentation for dialog widgets step by step.
In one or two weeks, it should be ready. 
I would appreciate your feedback on the individual modules. A simple "go on" would be enough ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8425)

Add documentation for dialog widgets

---

frontend/ui/widget/doublespinwidget.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8506)

[chore, CI] Remove empty whitespace

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readertypeset.lua

Cf. <https://github.com/koreader/koreader/pull/8489#issuecomment-985319434>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8510)

[i18n] Add context to CSS style vs highlight style

---

plugins/autowarmth.koplugin/main.lua
plugins/autowarmth.koplugin/suntime.lua

An update: Use `datetimewidget` and optimize speed (30%) and accuracy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8502)

[autowarmth, plugin] use date time widget, optimize

---

plugins/autowarmth.koplugin/suntime.lua

fix "todo" comment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8513)

[autowarmth, plugin] fix CI

---

plugins/autowarmth.koplugin/suntime.lua

Fixed CI warning about unused variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8518)

[autowarmth, plugin] CI Fix unused variable

---

frontend/ui/otamanager.lua

In response to the comment by @ilyats on Weblate:
> Text appears in code twice, as menu item and as dialog button label. Ideally, translations should be different.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8519)

[i18n] Add context to "Update"

---

frontend/apps/reader/modules/readerrolling.lua
frontend/apps/reader/readerui.lua
frontend/device/android/device.lua
frontend/document/credocument.lua

This PR fixes ANRs when applying style tweaks on long books (during rendering).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8501)

Fix some ANRs on applying style tweaks on a long book.

---

frontend/ui/trapper.lua

Discovered while extending Koreader in interesing ways.
Almost finished with a plugin to control my Tuya smartbulbs :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8539)

Trapper: fix doc

---

frontend/apps/reader/modules/readerhighlight.lua

Closes https://github.com/koreader/koreader/issues/8533.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8541)

ReaderHighlight: don't highlight text when long-press disabled

---

frontend/ui/widget/textboxwidget.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8559)

TextBoxWidget: add option to set bgcolor

---

plugins/coverimage.koplugin/main.lua

SizeSpinner: "Set" is disabled if the value has not changed, so no need to check this in the callback function.
Corrected typo.
Optimized code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8565)

[Coverimage, plugin] Clean up, typo

---

frontend/ui/widget/textviewer.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8588)

[chore, CI] Remove unused logger require

---

plugins/batterystat.koplugin/main.lua

Closes https://github.com/koreader/koreader/issues/8581.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8582)

[fix] batterystat: change per hour

---

frontend/ui/data/css_tweaks.lua

See <https://www.mobileread.com/forums/showthread.php?p=4183244#post4183244> for discussion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8587)

Style tweaks: add in-page classic classname Polish footnotes

---

.ci/install.sh
platform/appimage/AppRun
platform/common/spinning_zsync
platform/ubuntu-touch/koreader.sh

Cf. <https://github.com/koreader/virdevenv/pull/71#discussion_r777025218>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8605)

[CI] Minor updates for ShellCheck 0.8.0

---

plugins/docsettingtweak.koplugin/main.lua

In the same way as https://github.com/koreader/koreader/commit/a31d9446849b3864ecf425127e49dbe6b5a8a9a8. Closes https://github.com/koreader/koreader/issues/8596.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8599)

DocSettingTweak: Disable on non-Touch devices

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerhighlight.lua

Changes (requested in various FRs):
**-in bookmark list**
(1) easy access to actions (not with a long-press on an item)
(2) easy access to bookmark categories
(3) easy access to bookmarks of the current page
**-in a book**
(4) easy note viewing
(5) do not save highlight if "Add note" is cancelled
Bookmark list now has a left button that helps with 1-3. Tap on it to:
-switch to a category
-select bookmarks
-search bookmarks
-jump to a page in Bookmark list corresponding to the book current page
Long-press on the left button to toggle the select mode.
Selected bookmarks can be
-removed
-reset note, that means removing auto-text (page number / timestamp)
(Auto-text is easily added **for all bookmarks** with checking the option `Add page number / timestamp to bookmark`, but it cannot be …

Bookmarks/Highlights: left button, show note in book

---

frontend/apps/reader/modules/readerhighlight.lua

Leftover after https://github.com/koreader/koreader/pull/8600.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8609)

readerhighlight leftover fix

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8615)

[chore, CI] Remove an environment variable intended for shellcheck 0.4.5

---

plugins/opds.koplugin/opdsbrowser.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8606)

Add Standard Ebooks feed to opdsbrowser.lua

---

.ci/after_success.sh
.ci/after_success_docs_translation.sh
.circleci/config.yml

<del>Still needs some script changes.</del>
References <https://github.com/koreader/koreader/pull/8607>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8614)

[CI] Fix CircleCI context issue by separating out docs & translations

---

frontend/apps/cloudstorage/cloudstorage.lua
frontend/apps/reader/modules/readerbookmark.lua
frontend/ui/widget/menu.lua
frontend/ui/widget/titlebar.lua
plugins/coverbrowser.koplugin/covermenu.lua

Standard TitleBar with left/close buttons.
Landscape
Filemanager and PathChooser to compare.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8639)

Menu widget: insert TitileBar

---

frontend/apps/filemanager/filemanager.lua
frontend/ui/widget/filechooser.lua
frontend/ui/widget/pathchooser.lua
plugins/coverbrowser.koplugin/covermenu.lua

Closes https://github.com/koreader/koreader/issues/8631.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8646)

PathChooser: add left Home button

---

plugins/opds.koplugin/opdsbrowser.lua

Standardize title with left plus/home button.
Plus - add new opds catalog
Home - return to the list of catalogs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8660)

OPDS catalog: add title left button

---

frontend/document/document.lua

Reset to one running core.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8579)

Reset to one core

---

frontend/ui/widget/datetimewidget.lua
frontend/ui/widget/doublespinwidget.lua
frontend/ui/widget/radiobuttonwidget.lua
frontend/ui/widget/spinwidget.lua
frontend/ui/widget/titlebar.lua

TitleBar: add info_text
SpinWidget, DoubleSpinWidget, DateTimeWidget, RadioButtonWidget: insert TitleBar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8683)

More widgets: insert TitleBar

---

plugins/autosuspend.koplugin/main.lua

This should fix 
https://github.com/koreader/koreader/pull/8480#issuecomment-1015055771
and
https://github.com/koreader/koreader/pull/8480#issuecomment-1015093492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8684)

Autosuspend: fix disable

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/document/credocument.lua

Thanks https://github.com/koreader/koreader/pull/8616#issuecomment-1015443117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8690)

Bookmarks: fix compare invalid xpointers

---

plugins/batterystat.koplugin/main.lua

Thanks @hius07
I was dividing self.time in a previous iteration and made a copy paste typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8694)

Battery Stat: for real this time

---

frontend/ui/widget/inputdialog.lua
frontend/ui/widget/inputtext.lua
frontend/ui/widget/logindialog.lua
frontend/ui/widget/multiinputdialog.lua
frontend/ui/widget/openwithdialog.lua

InputDialog, MultiInputDialog, OpenWithDialog, LoginDialog
(1)
(2)
(3)
(4) Before - After
(5)
(6)
(7)
(8)
(9)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8695)

InputDialog: insert TitleBar

---

frontend/apps/reader/modules/readerhighlight.lua

While creating a bookmark, take datetime and chapter name from corresponding highlight.
Remove not used commented ancient Kindle clippings code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8699)

Bookmarks: do not duplicate datetime request on creation

---

frontend/apps/cloudstorage/cloudstorage.lua

Fixes #6465.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8705)

[lang] Add missing plurals to Dropbox download messages

---

frontend/device/generic/powerd.lua
frontend/ui/uimanager.lua

This should address @poire-z's comments ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8711)

PowerD: Follow up to #8672

---

plugins/terminal.koplugin/main.lua
plugins/terminal.koplugin/terminputtext.lua

Locally make doc works with this, maybe CI will also work?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8742)

Terminal emulator: satisfy CI doc

---

plugins/terminal.koplugin/main.lua
plugins/terminal.koplugin/terminputtext.lua

Some minor fixes for terminal emulator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8756)

Teminal emulator: fix translatable, fix potential crash

---

plugins/terminal.koplugin/main.lua

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8759)

[plugin] Update capitalization style "Terminal Emulator" → "Terminal emulator"

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/ui/elements/page_overlap.lua
frontend/ui/elements/screen_rotation_menu_table.lua
frontend/ui/widget/radiomark.lua
frontend/ui/widget/touchmenu.lua

Screenshots in https://github.com/koreader/koreader/issues/8754.
Available in:
-File manager - Settings - Screen - Rotation
-Reader - Settings - Taps and gestures - Long-press on text
-Reader - Typeset - Highlight style
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8757)

Touchmenu radiobutton

---

frontend/ui/widget/multiinputdialog.lua

Fix ugly full screen flashing on show.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8760)

MultiInputDialog: do not refresh full screen on show

---

frontend/device/kobo/device.lua

c.f., https://github.com/baskerville/plato/issues/220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8794)

Kobo: Use the right input protocol on the Nia

---

frontend/readhistory.lua

Reborn https://github.com/koreader/koreader/pull/8784. Closes https://github.com/koreader/koreader/issues/8779.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8813)

Readhistory: force reload

---

frontend/ui/elements/common_settings_menu_table.lua

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8812)

'End of document action' menu: radiomark

---

plugins/newsdownloader.koplugin/feed_source.lua

Fixes #8799
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8822)

Add support for RDF feeds

---

plugins/terminal.koplugin/main.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8829)

[plugin] Terminal: fix @translators comments

---

plugins/terminal.koplugin/main.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8830)

[plugin] Terminal: move stray newlines outside of translated string

---

plugins/terminal.koplugin/main.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8831)

[plugin] Terminal: remove stray space at end of string

---

frontend/ui/widget/frontlightwidget.lua
frontend/ui/widget/naturallightwidget.lua

Regression since https://github.com/koreader/koreader/pull/8769.
Fixes https://github.com/koreader/koreader/pull/8769#issuecomment-1047342888.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8834)

Frontlight/Naturallight widgets: revert movable

---

frontend/ui/widget/radiobuttontable.lua

Fixes #8841
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8847)

RadioButtonTable: CheckButton does not have onFocus

---

plugins/terminal.koplugin/main.lua

This should fix a regression introduced with #8845 with reopening a running shell.
Adds more checks and more verbose logging messages on failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8848)

Terminal: regression with #8845

---

frontend/device/pocketbook/device.lua

Thanks to @uatel.
Fixes #8850.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8851)

Add Pocketbook 740-3

---

frontend/apps/reader/modules/readerpaging.lua

Cf. <https://www.mobileread.com/forums/showthread.php?p=4200567>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8836)

ReaderPaging: allow for page diff greater than 1 in onScrollPageRel

---

frontend/apps/filemanager/filemanagerhistory.lua
frontend/readhistory.lua
plugins/coverbrowser.koplugin/covermenu.lua

Closes https://github.com/koreader/koreader/issues/3406. Closes https://github.com/koreader/koreader/issues/4849. Closes https://github.com/koreader/koreader/issues/7435. Closes https://github.com/koreader/koreader/issues/8811.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8820)

History: filter by book status
