koreader/koreader

frontend/apps/reader/modules/readersearch.lua

InputContainer's onInput trickery for hold_input & tap_input.
Also, don't flag the buttons from that InputDialog as vsync,
because that was stupid ;).
Fix #7357
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7360)

ReaderSearch: Switch to a real InputDialog, instead of piggybacking on

---

frontend/ui/network/manager.lua
frontend/ui/widget/networksetting.lua

Namely, if Wi-Fi is enabled, but the connection is down.
Fix #7358
(Note that we have a Kobo-specific workaround to tear-down Wi-Fi in these cases, that was probably subtly inhibited in most cases by #6424 ^^).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7368)

WiFi: Handle inconsistent states a tad better.

---

frontend/apps/reader/modules/readerdogear.lua
resources/icons/mdlight/dogear.alpha.svg

Also, update the actual ReaderDogEar variant of the icon to use a semi-transparent fill for the bottom-left corner.
Fix #7364
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7369)

ReaderDogEar: Enforce a minimum size, too

---

frontend/ui/widget/menu.lua

Remove an unwanted truncation.
This *should* be a float ;).
c.f., https://github.com/koreader/koreader/pull/7335#discussion_r586548610
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7378)

Another minor fixup post #7335

---

frontend/apps/reader/modules/readerfooter.lua
spec/unit/readerfooter_spec.lua

Should fix #7390
In theory. In practice, CenterContainer is much better at utilizing the available width, whereas LeftContainer & RightContainer attempt to move text around to... weird effects, so we don't let 'em.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7391)

ReaderFooter: Fix some interactions between margins and text width

---

frontend/apps/filemanager/filemanager.lua
frontend/dispatcher.lua
frontend/ui/data/creoptions.lua
frontend/ui/data/koptoptions.lua

Fix #7388
Related fixes:
* Unbreak the Rotation submenu entries since #7306
* Actually update the touchzones properly when the FM is rotated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7389)

Dispatcher: nil guard against access to a document instance

---

plugins/opds.koplugin/opdsbrowser.lua

Some OPDS servers do not provide authors for all items. In this case, fall back to the item name only.
Resolves crash in #6418, option for downloading by Content-Disposition should still be considered.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7384)

OPDS: Do not include author in download filename if nil or empty

---

frontend/apps/filemanager/filemanagerfilesearcher.lua

Fixes: #7361
Space is overloaded to show all results. Is this the desired behavior?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7362)

FileSearcher: Do not crash on space, show unsupported files if enabled.

---

plugins/evernote.koplugin/JoplinClient.lua

The Joplin API endpoints for fetching notes or notebooks are paginated now
Resolves #7148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7162)

Account for result pagination when fetching notes or notebooks from Joplin API

---

frontend/device/kobo/powerd.lua
frontend/ui/screensaver.lua
frontend/ui/widget/keyvaluepage.lua
frontend/ui/widget/menu.lua

* Clock shenanigans on Kobo (fix #7092, pending https://github.com/koreader/koreader-base/pull/1322).
* Menu/KeyValuePage: Make sure the buttons are hidden when no items are shown (fix #7394).
* Screensaver: Use the ReaderUI instance when we can. Because re-opening the document you're currently reading just to get its cover felt fairly stupid...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7396)

A couple of fixes & enhancements

---

frontend/apps/reader/modules/readertypeset.lua
frontend/ui/screensaver.lua
plugins/kosync.koplugin/main.lua

We don't have real ternary operators in Lua, if the second argument
evaluates to false, it doesn't work.
Invert the test to avoid this pitfall.
(c.f., http://lua-users.org/wiki/TernaryOperator).
Fix #7402, regression since #7371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7403)

Screensaver: Unbreak screensaver_stretch_images

---

frontend/device/kobo/device.lua
frontend/device/wakeupmgr.lua
plugins/autosuspend.koplugin/main.lua

* Unify logging with AutoSuspend (e.g., keep ourselves to showing the delay in seconds, not the raw timestamp, as that's way harder to interpret, and the RTC module and/or logger will do that for us when the time comes).
* Speaking of, minor revamp of RTC related logging to make it more human-readable.
* On Kobo, if we hit the unexpected wakeup limit, re-engage AutoSuspend's *suspend* check, so that the device has a chance to poweroff instead of being kept awake.
Depends on https://github.com/koreader/koreader-base/pull/1323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7400)

WakeupMgr: Minor usage tweak

---

frontend/device/pocketbook/device.lua

It's apparently still necessary on a number of devices.
Fix #7072 (Regression since #6684).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7404)

Re-implement the PB fb fixup insanity

---

frontend/ui/widget/skimtowidget.lua

More logical buttons allocation, increasing from left to right.
https://github.com/koreader/koreader/wiki/Skim-document
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7408)

SkimToWidget: swap '1' and '10' buttons

---

frontend/apps/reader/modules/readertoc.lua

Fix for https://github.com/koreader/koreader/issues/7428#issuecomment-802959731 , although I can't reproduce it, and this part being run and this crash happening should have been prevented by the enabled_func not allowing it to be run...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7434)

TOC settings: fix possible crash

---

frontend/apps/filemanager/filemanagermenu.lua
frontend/device/kobo/device.lua

And enable it by default on the Libra (which already happened in base previously, since https://github.com/koreader/koreader-base/pull/1329).
This is hidden away inside the dev menu, because duh'.
Requires https://github.com/koreader/koreader-base/pull/1334
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7431)

Kobo: Allow toggling the WAIT_FOR_UPDATE_COMPLETE hack

---

frontend/apps/cloudstorage/webdavapi.lua
plugins/opds.koplugin/opdsbrowser.lua

It appears that passing `username` and `password` to `http.request()` doesn't work.
http://w3.impa.br/~diego/software/luasocket/http.html#request indicates that the way to set this is with a URL like `http://user:pass@url.com/foo`. This does actually work if you set this URL in the WebDAV settings.
This patch uses the (old) alternative method of direct authentication, so as not to have to mess about with splitting the protocol, adding the `user:password@` and recombining.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7425)

Unbreak HTTP authentication

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/document/document.lua
frontend/document/pdfdocument.lua

This changes the PDF annotation contents each time the corresponding bookmark text is edited. When the annotations are written to the PDF file, the annotation contents are saved as well into the PDF.
In my initial tests it works - I can see the bookmark texts in the PDF viewer Okular. However, there are still some rough edges (partly due to my inexperience with the code base and with Lua):
- To touch as little existing code as possible, I duplicated some code. Once verified that everything works, some refactoring should be done.
- More error checking/reporting should be added.
- Tests should be added for the feature.
Depends on some [low-level additions to koreader-base](https://github.com/koreader/koreader-base/pull/1327).
--- …

Update PDF annotations when changing bookmark text

---

frontend/apps/reader/modules/readertoc.lua

Don't assume self.ticks is usable, but get them updated with :getTocTicks(), even after a :resetToc().
Closes #7442.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7443)

TOC settings: fix ticks disappearing

---

frontend/device/kindle/device.lua
frontend/device/kobo/device.lua

* Also, move MXCFB cap checks to Device.
* Requires https://github.com/koreader/koreader-base/pull/1339
Fix #7433 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7446)

Initial KOA3 support

---

plugins/opds.koplugin/opdsbrowser.lua

Previously, it was updated with *acquisitions*, too, which was weird.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7451)

OPDSBrowser: Only update the title on plain navigation

---

frontend/pluginloader.lua

It looks like a problem introduced by https://github.com/koreader/koreader/commit/dee72a431c1ef4d59569ffc80b876e2e91765bbf#diff-b3b0e0e90ea7b43a9d97a1c7572acef3f1dc7d1d2f75fe634345a1b841c624fa. Or did I misunderstand it?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7447)

PluginLoader should update lookup_path_list if data_dir is not ".".

---

frontend/document/credocument.lua

Includes (among others):
- LVImg: Tweak JPEG decoding some more https://github.com/koreader/crengine/pull/427
- toStringV2(): fix (again) when target node is a boxing node https://github.com/koreader/crengine/pull/428
- LVFontCache::find(): give more weight to first fonts in list
- Page splitting: more accurate rendering progress
- getRenderedWidths(): fix nowrap around image/inlineBoxes
- Tables rendering: tweak column widths algorithm
- CSS: parse/handle "currentcolor", default for border-color
- CSS: add units 'ch' (just like 'ex')
- SVG images: proper alpha blending
- MathML: add parsing and rendering support files https://github.com/koreader/crengine/pull/429
- MathML: plug MathML code into crengine core
- MathML: <epub:switch/case/default>: accept MathML
- (Upstream) Make …

bump crengine: add support for MathML

---

frontend/ui/data/css_tweaks.lua

`.voetnoten` is standard in DBNL ebooks.
A good test book can be found at <https://www.dbnl.org/tekst/veld028jnot01_01/>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7467)

Add DBNL footnotes styletweak

---

frontend/apps/filemanager/filemanager.lua

For parent folder (..):
disabled `Copy`, `Cut`, `Delete`, `Rename`.
enabled `Paste`, `Set as HOME folder`.
Added `/` to the dialog title for folders (same as in the files list) to distinguish folders and files (in addition to different sets of the bottom buttons).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7475)

File manager: disable forbidden or dangerous actions for parent folder

---

frontend/device/gesturedetector.lua
frontend/device/input.lua
frontend/device/kobo/device.lua
frontend/ui/uimanager.lua

* Actually load librt properly on old Linux systems (fix #7472)
* Made sure SDL & Android honored timeouts properly in some edgy (or not so edgy, in SDL's case) cases (c.f., https://github.com/koreader/koreader-base/pull/1343).
* Try harder not to consume a timer callback when the timerfd backend is in use and `select` timed out *not* because of a timerfd expiring. This would take some particularly heinous timing to reproduce (e.g., a timerfd set, but a task deadline expiring *before* it). May or may not help with #7473.
* Decode `BTN_` KEY codes in verbose debug logs.
* Fix MultiTouch on the H2O (GestureDetector was hard-coding the two slots as 0 & 1, but the H2O kernel is a special snowflake that doesn't use slot 0, instead switching to slot 1 & 2).
--- …

Input: Followup tweaks to #7415

---

plugins/texteditor.koplugin/main.lua

Allows to hide keyboard on start to see more text.
Default is to show keyboard.
Some wordings unification.
`Open file` goes down, closer to the list of opened files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7460)

Text editor: option to show/hide keyboard on start

---

frontend/apps/reader/modules/readersearch.lua

When nothing found now we have the `search_dialog` (arrows) displayed and need to observe the screen whether there are any search results highlighted.
I propose to show the infomessage for 2 sec.
After that we can continue search in the opposite direction with the `search_dialog` if needed.
`vsync` removed to avoid the `search_dialog` buttons showing up over the infomessage and it seems to cause no problems anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7436)

Fulltext search: show notification when nothing found

---

frontend/apps/filemanager/filemanagerfilesearcher.lua
frontend/apps/filemanager/filemanagermenu.lua
frontend/apps/reader/modules/readerdictionary.lua
frontend/apps/reader/modules/readerwikipedia.lua
frontend/ui/widget/dictquicklookup.lua
plugins/calibre.koplugin/main.lua
plugins/calibre.koplugin/search.lua
plugins/opds.koplugin/opdsbrowser.lua

There is `File search` in the Gesture manager already.
There is `Fulltext search` in the readermenu.
Some help text added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7398)

Standardize search/find to search

---

frontend/apps/reader/modules/readerfont.lua
frontend/apps/reader/modules/readertoc.lua
frontend/ui/data/css_tweaks.lua
frontend/ui/widget/notification.lua
frontend/ui/widget/touchmenu.lua

Generic feature added to TouchMenu: an optional callback 'open_on_menu_item_id_func()' set on an items table can tell which menu item should be shown when opening a menu.
TouchMenu: allows jumping to first or last page with long-press on the chevrons.
Proposals and discussion at at https://github.com/koreader/koreader/issues/3620#issuecomment-801421408 and https://github.com/koreader/koreader/issues/3620#issuecomment-801516104.
I haven't added it for the other menu suggested there (Languages, Dispatcher actions...) because these are less bothering _to me_ :) Tell me if I should.
I also included something that I proposed previously (can't find where) - because I've been happy having it in my own patch: showing the current font name in the `Font>` menu name itself: …

Font menu: open on page with currently selected font, and other tweaks

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/reader/readerui.lua
frontend/device/input.lua
frontend/device/kobo/device.lua
frontend/pluginloader.lua
frontend/ui/hook_container.lua
frontend/ui/uimanager.lua
plugins/autostandby.koplugin/main.lua
plugins/autosuspend.koplugin/main.lua
plugins/autoturn.koplugin/main.lua
spec/unit/device_spec.lua

Requires https://github.com/koreader/koreader-base/pull/1344 & https://github.com/koreader/koreader-base/pull/1346 (fix #7485)
Assorted input fixes:
* Actually handle errors in the "there's a callback timer" input polling loop.
* Don't break timerfd when the clock probe was inconclusive.
Not directly related, but noticed because of duplicate onInputEvent handlers:
* HookContainer: Fix deregistration to actually deregister properly. "Regression" extant since its inception in #2933 (!).
* Made sure the three plugins (basically the trio of AutoThingies ;p) that were using HookContainer actually unschedule their task on teardown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koread …

Input: Process input events in batches

---

frontend/ui/elements/screensaver_menu.lua
frontend/ui/screensaver.lua

By which I mean, explicitly initialize default settings, making everything seven hundred billion percent less weird.
Also, split the background option between image and (solo) message, because the defaults for those are different, and trying to twist the one into the other was leading to pure madness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7496)

ScreenSaver: Get rid of automagic settings

---

frontend/apps/reader/modules/readerview.lua

Adds a new hidden setting to address https://github.com/koreader/koreader/issues/7476
The setting takes values from 0 (brightest) to 1 (darkest). For example, to lighten the highlight, users can manually add the line below to their `settings.reader.lua`
```
"highlight_lighten_factor" = 0.1
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7497)

hidden setting: highlight lighten factor

---

frontend/ui/widget/inputtext.lua

Before: you can tap a hint and cursor jumps to that position. Not nice, as we haven't started to input yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7507)

Inputtext: don't allow the cursor to move within a hint

---

platform/remarkable/koreader.sh

Fixes https://github.com/koreader/koreader/issues/7508
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7509)

remarkable FW 2.6: Set absolute path for 'sync'

---

frontend/ui/widget/container/inputcontainer.lua
frontend/ui/widget/keyvaluepage.lua
frontend/ui/widget/menu.lua

Continue to implement default behaviour in input dialogs: do not accept empty input field.
Folow up to https://github.com/koreader/koreader/pull/7501.
InputContainer will not allow blank input by deafult.
If needed to allow, set `allow_blank_input = true` before calling.
Affects page selector in the KeyValuePage widget.
Does not affect Wikipedia languages settings (https://github.com/koreader/koreader/pull/7501#discussion_r606771433).
Menu.lua: do not allow blank input in page selector.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7516)

Input dialogs: do not allow blank input cont'd

---

frontend/ui/widget/dictquicklookup.lua

Discussed in https://github.com/koreader/koreader/issues/7511.
Allow continue search in Dict, Wiki or Translate.
New window will stack over the window with the previous lookup results (same as with the long press in the article).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7523)

Dict/Wiki lookup results window: improve the 'pencil' button

---

frontend/device/remarkable/device.lua

Note from @NiLuJe 's PR https://github.com/koreader/koreader/pull/7415#issuecomment-807855785
"reMarkable: Stopped enforcing synthetic timestamps on input events, as it should no longer be necessary."
It's definitely still necessary, at least on rm2
The basic problem is that *stylus* input is synced with the realtime clock, but *touch* input is not.
After KOReader starts, if the very first input is from the stylus, then the log says
```
GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
```
But if the very first input is from my finger, then the log says
```
GestureDetector:probeClockSource: Touch event clock source detection was inconclusive
```
So if the stylus is the very first input, then all subsequent finger inputs are always misinterpreted as long …

Fix for PR #7415 breaking reMarkable touch input

---

frontend/device/gesturedetector.lua
frontend/device/input.lua
frontend/device/kobo/device.lua
frontend/device/sony-prstux/device.lua
frontend/ui/timeval.lua
spec/unit/device_spec.lua
spec/unit/input_spec.lua

* TimeVal: Log the results of the COARSE probes in debug logs
* GestureDetector: Print details of failed clock probes in debug logs
* GestureDetector: Skip the BOOTTIME probe when CLOCK_BOOTTIME is unsupported.
* Input: Decode ABS_DISTANCE events in debug logs
* Get rid of duplicated <linux/input.h> constants, use the FFI module everywhere (re #7536)
* Kobo: Get rid of the `touch_alyssum_protocol` quirk. Replace it by setting `main_finger_slot` to `1`, like on the H2O.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7542)

Input: Minor cleanups

---

frontend/apps/reader/modules/readertypography.lua
frontend/cache.lua
frontend/ui/data/onetime_migration.lua
frontend/ui/data/settings_migration.lua
frontend/ui/screensaver.lua
frontend/version.lua
plugins/opds.koplugin/opdsbrowser.lua
plugins/statistics.koplugin/main.lua
reader.lua

There have been a couple of these this month, and keeping stuff that should only ever run once piling up in their respective module was getting ugly, especially when it's usually simple stuff (settings, files).
So, move everything to a dedicated module, run by reader.lua on startup, and that will actually only do things once, when necessary.
~~(Draft because on top of #7528; starts after 7305f8f)~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7531)

Centralize one time migration code after updates

---

frontend/persist.lua
frontend/ui/data/onetime_migration.lua
plugins/calibre.koplugin/search.lua
spec/unit/persist_spec.lua

And swap the Calibre metadata cache to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7543)

Persist: Add the new native LuaJIT serializer to the list of supported codecs

---

frontend/persist.lua
frontend/ui/data/onetime_migration.lua
frontend/ui/message/streammessagequeue.lua
plugins/calibre.koplugin/search.lua
plugins/calibre.koplugin/wireless.lua

* Wireless: Optimize memory usage in StreamMessageQueue (use an array of string ropes, that we only concatenate once). Allowed to relax the throttling, making transfers that much faster.
* Persist: Add a "zstd" codec, that uses the "luajit" codec, but compressed via zstd. Since both of those are very fast, it pretty much trounces everything in terms of speed and size ;).
* Persist: Implemented a "writes_to_file" framework, much like the existing "reads_from_file" one. And use it in the zstd codec to avoid useless temporary string interning.
* Metadata: Switch to the zstd codec.
Requires https://github.com/koreader/koreader-base/pull/1355
--- …

Calibre: More QoL tweaks

---

frontend/ui/widget/button.lua

Allow to keep the icon centered after `setIcon`.
`setIcon` isn't used anywhere at the moment (going to be).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7546)

Button setIcon: keep button width

---

frontend/apps/reader/modules/readertoc.lua
frontend/ui/elements/reader_menu_order.lua

Sometimes ToC entries are too short and it is hard to trace page numbers.
---
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7551)

ToC: option to show/hide entries separator

---

frontend/ui/widget/numberpickerwidget.lua

(1) It is convenient to see the boundaries of the input value instead of the current value (which is seen in the SpinWidget).
Before
After
(2) Is line 143 correct? Can it be removed (the input box is closed with 148)?
https://github.com/koreader/koreader/blob/bbe197bd4b8a1e44520a1a659d91ca1fa8e162c6/frontend/ui/widget/numberpickerwidget.lua#L142-L149
(3) Since (1), as we see the hint with the boundaries before input, do we need the detailed error infomessages?
https://github.com/koreader/koreader/blob/bbe197bd4b8a1e44520a1a659d91ca1fa8e162c6/frontend/ui/widget/numberpickerwidget.lua#L151
https://github.com/koreader/koreader/blob/bbe197bd4b8a1e44520a1a659d91ca1fa8e162c6/frontend/ui/widget/numberpickerwidget.lua#L156
--- …

Numberpicker: show hint with boundaries instead of the current value

---

frontend/apps/reader/modules/readerdictionary.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/apps/reader/modules/readertoc.lua
frontend/apps/reader/modules/readerview.lua
frontend/device/android/device.lua
frontend/device/gesturedetector.lua
frontend/device/input.lua
frontend/device/sdl/device.lua
frontend/ui/gesturerange.lua
frontend/ui/timeval.lua
frontend/ui/uimanager.lua
frontend/ui/widget/dictquicklookup.lua
frontend/ui/widget/footnotewidget.lua
frontend/ui/widget/frontlightwidget.lua
frontend/ui/widget/infomessage.lua
frontend/ui/widget/menu.lua
frontend/ui/widget/notification.lua
frontend/ui/widget/sortwidget.lua
frontend/ui/widget/touchmenu.lua
plugins/autosuspend.koplugin/main.lua
plugins/autoturn.koplugin/main.lua
plugins/backgroundrunner.koplugin/main.lua
plugins/calibre.koplugin/search.lua

* Input: Don't create a new TimeVal object for input frame timestamps, just promote our existing table by assigning it the `TimeVal` metatable.
* TimeVal: Export (const) `zero` & `huge` TimeVal objects, because they're common enough in our codebase. (NOTE: not actually const, that's a Lua 5.4 feature ;p).
* GestureDetector: Explain the behavior of the `last_tevs` & `first_tevs` tables, and why one needs a new object and not the other.
* Speaking of, simplify the copy method for `first_tevs`, because it doesn't to create a new TimeVal object, we can just reference the original, it's unique and re-assigned for each frame.
* Menu: Don't share the `dimen` object across instances. Because we can have a few different instances of it at one time. This fixes, probably among other things, the …

A bunch of fixes

---

frontend/device/remarkable/device.lua

"we did move rM to the same power event handler [as] Kobo, so it should already be doing a white flash before [ScreenSaver]" https://github.com/koreader/koreader/issues/7519#issuecomment-819649806
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7563)

remarkable: remove extra refresh before poweroff

---

frontend/ui/elements/screensaver_menu.lua
frontend/ui/screensaver.lua

UI to enable/disable the Screensaver fallback message as discussed here https://github.com/koreader/koreader/issues/7519#issuecomment-821851836
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7566)

screensaver: add reboot/poweroff message toggle

---

frontend/ui/data/css_tweaks.lua

A small addition to the beautiful set of style tweaks.
Before: footnote numbers follow the style of the text element, e.g. epigraph+author makes them italic+bold.
After: footnote numbers are normal throughout the text of the book.
---
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7567)

Style tweaks: add links italic font style

---

frontend/apps/reader/modules/readertoc.lua

No need to reinvent the wheel.
Fix #7568, regression since #7553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7569)

ReaderToc: Unbreak ToC depth detection

---

frontend/device/android/device.lua
frontend/device/generic/device.lua
frontend/device/pocketbook/device.lua
frontend/device/remarkable/device.lua
frontend/device/sdl/device.lua
frontend/document/canvascontext.lua
frontend/fontlist.lua
frontend/ui/elements/font_settings.lua
platform/remarkable/koreader.sh

Add system + user paths to the ReMarkable (it has "normal" linux paths)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7535)

add hasSystemFonts device property

---

frontend/ui/network/manager.lua
frontend/ui/widget/networksetting.lua

Fully tearing down Wi-Fi was a bit optimistic, as the AP list can
technically still be up, so the user might want to try again and/or
connect to another AP.
Fix #5912, regression since #4616.
The reasoning behind #4616 doesn't really apply anymore anyway, as the
Wi-Fi prompt now handles this inconsistent state properly (#7368).
The whole codepath should be *extremely* rare anyway (and/or require
super-broken network conditions).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7570)

NetworkManager: Just warn if the gateway is unreachable after a successful authentication.

---

frontend/apps/filemanager/filemanager.lua

Tweak the goHome handler directly, instead of only the Home button.
Also, limit it to when it's actually needed, as changeToPath already
does it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7571)

FileManager: Tweak #7564

---

plugins/coverimage.koplugin/main.lua

Fix template, so that translations can be used (`color` is an internal string with the values "black", "white" and "gray").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7591)

fix template

---

frontend/device/kindle/powerd.lua
platform/cervantes/koreader.sh
platform/kindle/koreader.sh
platform/kobo/koreader.sh
platform/pocketbook/koreader.app
platform/remarkable/koreader.sh
spec/unit/device_spec.lua

Instead of forking it on every checkpoint.
Won't change much in the grand scheme of things, but FIFOs are fun.
~~(Draft because on top of #7585).~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7588)

OTA: Handle tar checkpointing visual feedback w/ an FBInk daemon

---

frontend/apps/reader/modules/readerfooter.lua

Ignore `Hide empty items` if not `Show all at once`.
c.f. https://github.com/koreader/koreader/issues/7488#issuecomment-826340576
Small tuning of the settings:
- `Hide empty items` is disabled if not `Show all at once`
- `Hide empty items` located next to `Show all at once` for better visibility
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7602)

Status bar: do not hide alone empty indicators

---

frontend/dispatcher.lua

Closes https://github.com/koreader/koreader/issues/7488.
As discussed, the action is the same as tapping the footer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7606)

Dispatcher: add "Toggle status bar" action

---

plugins/gestures.koplugin/main.lua

There are 11 `Gesture manager` submenu items, that creates the second page with `Spread and pinch` alone.
Propose to move `Short diagonal swipe` into `One-finger swipe` (it is the one-finger swipe actually) and get a nice one-page menu.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7609)

Gestures menu optimization

---

frontend/apps/reader/modules/readerfont.lua
frontend/dispatcher.lua
frontend/document/credocument.lua
frontend/ui/data/creoptions.lua
frontend/ui/data/optionsutil.lua
frontend/ui/widget/configdialog.lua

Includes:
- MathML: a few minor fixes https://github.com/koreader/crengine/pull/435
- (Upstream) lvtext: fix possible index out of range
- Fonts: RegisterExternalFont() should take a documentId
- Fonts: fix: letter-spacing should not be applied on diacritic
- (Upstream) Fonts: more granular synthetic weights
- Fonts: synthesized weights: tweak some comments
- Fonts: keep hinting with synthetic weight
- Fonts: fix synthesized weight inconsitencies
- Fonts: fix getFontFileNameAndFaceIndex()
- Fonts: adds LVFontMan::RegularizeRegisteredFontsWeights()
- Fonts: handle synth_weight tweaks in glyph/glyphinfo slots
- (Upstream) Fonts: fix some compiler warnings
- Fix hyphenation on Armenian and Georgian text https://github.com/koreader/crengine/pull/436 Closes #7539.
I decided to not care about …

bump crengine: more granular font weights

---

plugins/autosuspend.koplugin/main.lua

Kindles are not flagged canPowerOff, although that's technically not
entirely warranted, but sorta makes sense.
The Plugin already handles that sanely, and will only expose/honor the
suspend timer.
(That wasn't the case before #7400, which possibly explains the omission).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7612)

Kindle: Enable AutoSuspend plugin

---

frontend/apps/reader/modules/readercoptlistener.lua
frontend/device/android/device.lua

Update the time on header and footer, when device resumes. Otherwise if you put the device to sleep and resume it the next day, an old time is displayed until the autorefresh happens.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7630)

[Android] Refresh header and footer on Resume, unschedule refresh

---

frontend/apps/filemanager/filemanager.lua
frontend/dispatcher.lua
plugins/gestures.koplugin/defaults.lua
plugins/gestures.koplugin/main.lua

Holding the "Plus" button is reserved for content refresh in https://github.com/koreader/koreader/pull/7559.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7592)

File manager: make "Refresh content" action customizable

---

frontend/apps/cloudstorage/dropboxapi.lua

This fixes the issue I created in #7600. As I said, I've never done anything in Lua before but this is a small change and it has worked on my system. I added a new function in the DropboxAPI to pull additional folder lists until all are pulled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7621)

DropboxAPI fix to get all files with pagination

---

frontend/dispatcher.lua

In the bottom menu you can select fractional font sizes (e.g. 17.5). 
Now you can change the font size to the same values as in the bottom menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7626)

[dispatcher] Make font sizes consistent with bottom menu numberpicker

---

plugins/texteditor.koplugin/main.lua

Some enhancements to the Text editor:
- correct name for Dispatcher
- show font size value in the menu
- new `Clean text editor history` in the Settings
- consistent ConfirmBox buttons `Cancel` - `Action`
- the last (I hope) directory -> folder
--
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7635)

Text editor: new 'Clean text editor history' etc.

---

frontend/apps/reader/modules/readerwikipedia.lua

Self explained.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7637)

Wikipedia: disable 'Clean history' when the history is empty

---

frontend/apps/reader/modules/readerdictionary.lua

Self explained.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7636)

Dictionary: disable 'Clean history' when the history is empty

---

frontend/apps/reader/modules/readerpagemap.lua
frontend/apps/reader/modules/readertoc.lua
frontend/ui/elements/reader_menu_order.lua
frontend/ui/widget/menu.lua

A dotted line joining the ToC entry text to the page number may make it easier to use.
This replaces the menu item separator from #7551. See https://github.com/koreader/koreader/pull/7551#issuecomment-835384193
Also fix baseline aligment, which could be a bit off.
Should this be enabled by default (currently is) to advertize it, or not ?
(I think most people really don't care about page numbers, so no line would keep them appart and you would not be distracted.)
<kbd>![image](https://user-images.githubusercontent.com/24273478/118017232-a911af80-b356-11eb-8968-605f43dcdb57.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/118017304-be86d980-b356-11eb-82ec-161cddec6759.png)</kbd>
--- …

ReaderToc: option to show a dotted line

---

plugins/wallabag.koplugin/main.lua

Fixes <https://github.com/koreader/koreader/issues/7650>.
@mredaelli @matejdro Could you please verify this works around the issue for you?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7668)

[plugin] Wallabag: different timeouts for API calls vs file downloads

---

plugins/coverimage.koplugin/main.lua

I was still thinking about 341d6ac660e590a129ae3e8681167aa1dae0075a I suppose.
Hat tip to @yparitcher.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7678)

Fix stupid typo

---

frontend/device.lua

To avoid a few log lines on all platforms:
```
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7682)

move SDL check to the end of Device's probe function

---

frontend/ui/widget/container/inputcontainer.lua
frontend/ui/widget/inputdialog.lua
frontend/ui/widget/inputtext.lua

Allows to jump to a line by its number in the file.
Shows the target line at top of the screen, cursor positioning at the beginning.
By now available in the Text editor and in the Book-specific style tweak.
Current line number is shown in the hint.
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7673)

InputDialog: add 'Go to line' button

---

frontend/apps/filemanager/filemanagermenu.lua
frontend/device/pocketbook/device.lua

Apparently, it's even more broken on some devices/FW combos.
Fix #7663
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7684)

PB: Unconditionally disable HW rotation on B288 SoC

---

frontend/ui/widget/inputdialog.lua
frontend/ui/widget/inputtext.lua

Searches for a string in the edited text.
Available in the Text editor and other input dialogs with the navigation bar enabled.
<kbd>Find first</kbd> searches from the beginning of the text.
<kbd>Find next</kbd> searches from the next to cursor position, used for continious search.
By now, the Search input window is closed after the search. You need to press the `Find` button again for continious search, the search string is kept in the input.
Is it better to keep the dialog open for the comfortable continious search? And close it with the `Cancel` only?
Case insensitive. Cursor jumps to the beginning of the found string.
Notifications are shown for better results visibility.
Unfortunately, violated our standartization to "search", couldn't invent better short wordings.
--
--
---
This …

InputDialog: add search

---

frontend/apps/reader/modules/readerrolling.lua
frontend/document/credocument.lua

If the top status bar is enabled and the document has already been rendered, then the progress indicator is shown just below the status line.
On book opening or if there is no top status bar, no changes.
see #7666. Closes #7666
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7667)

Tune pogress indicator

---

frontend/apps/reader/modules/readerfont.lua

Whith the new font size step of 0.5 the gesture for increasing or decreasing font size would change the size by only half of the given value. 
This fix would also be in #7623. But I expect it is better to apply this sooner as #7623 will come :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7689)

Fix changeFontSize whith the new granulary gestures

---

frontend/apps/reader/modules/readerconfig.lua
frontend/apps/reader/modules/readerfooter.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readermenu.lua
frontend/apps/reader/modules/readerpaging.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/apps/reader/modules/readerscrolling.lua
frontend/apps/reader/modules/readerview.lua
frontend/apps/reader/readerui.lua
frontend/device/devicelistener.lua
frontend/device/gesturedetector.lua
frontend/device/sdl/device.lua
frontend/ui/elements/reader_menu_order.lua
frontend/ui/uimanager.lua
frontend/ui/widget/dictquicklookup.lua
frontend/ui/widget/textwidget.lua
plugins/gestures.koplugin/main.lua

Add a new reader module: `ReaderScrolling`, that exposes some `Scrolling>` options to the menu (which are to be used by and implemented in `ReaderPaging` and `ReaderRolling` themselves) and implement some inertial scrolling logic used by both of them.
Default to `Classic scrolling` which is the expected behaviour on phones and tablets. Closes #7413.
The old CreDocument buggy behaviour is available as `Turbo scrolling` for both Paging and Rolling documents.
Added a `On release scrolling` option that might be useful on eInk to avoid dynamic pan/scrolling (I had that in my own patch, and was just happy having pan/scroll work like that, so may be others will like it too - it's the one stop solution to not having conflicts with swipe and multiswipe when you just happen to use scroll mode with …

Fix scrolling, add inertial scroll on non-eInk devices

---

defaults.lua
plugins/gestures.koplugin/main.lua
spec/unit/defaults_spec.lua

Make 'em match backward & forward.
Now that we have working overrides and the gesture manager, trying to fit them in a weird superset of the top corner tapzones in a vain attempt to avoid bad interactions doesn't make much sense anymore, and just makes the Gesture Manager UI confusing.
Also make sure the corner zones override the L/R ones for double taps, like it's the case with other gestures.
Fix #7710
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7711)

Double tap: Update default tap zones

---

frontend/ui/widget/inputdialog.lua

It should be "Not found." as in "Find next".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7714)

[lang] Fix minor inconsistency

---

frontend/apps/reader/modules/readerhighlight.lua

See #7713. Closes #7713.
<kbd>![image](https://user-images.githubusercontent.com/24273478/119050563-55403f80-b9c2-11eb-8f65-0a9c5de4a181.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/119050707-7f91fd00-b9c2-11eb-9776-4974a18b441e.png)</kbd>
(Just realising with these screenshots these buttons ended up looking the same in LTR and RTL - although doing different things :)
Also fix long-long-press on single word (to bring the highlight dialog instead of doing a lookup) which was broken since a few weeks. See https://github.com/koreader/koreader/issues/7722#issuecomment-845365207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7725)

ReaderHighlight: clearer symbols on selection start/end buttons

---

frontend/apps/reader/readerui.lua
frontend/document/credocument.lua
frontend/document/document.lua
frontend/document/documentregistry.lua
frontend/document/pdfdocument.lua
frontend/document/picdocument.lua
plugins/statistics.koplugin/main.lua

There was a nasty interaction whereas CReDocument would assume *all* :close calls were "final". That isn't actually the case, as DocumentRegistry will keep a cache of currently open documents with refcounting.
Tweak Document:close & DocumentRegistry to make the refcounting state more explicit, allowing CreDocument (& PdfDocument) to only do "final" stuff on actually final :close calls (i.e., closing the last ref, a.k.a., tearing down the actual instance).
Regression since #7702, c.f., https://github.com/koreader/koreader/pull/7702#issuecomment-845042727
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7723)

CReDocument: Don't break it when a cached ref is closed

---

frontend/ui/widget/inputtext.lua

Add some clipboard management to the Text editor and other text input boxes.
Screenshots here: https://github.com/koreader/koreader/issues/7715
Closes #7715.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7719)

InputText: add clipboard dialog

---

frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/screen_notification_menu_table.lua

Otherwise it's flagged as orphaned ;).
(Also tweak indenting of said settings to be more in line with how we
usually do these).
Overlooked in #7718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7734)

Notifications: Sort the settings appropriately in the FM

---

frontend/ui/widget/inputtext.lua
frontend/ui/widget/virtualkeyboard.lua

Holding `left arrow` will move cursor to the beginning of the line.
Holding `right arrow` will move cursor to the end of the line.
Available in all input boxes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7730)

VirtualKeyboard: move cursor with holding left/right arrows

---

frontend/ui/elements/screen_notification_menu_table.lua

This is the PR for the menu entry selection like discussed in #7743.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7736)

Notification menu entries: Drop "No notifications" as discussed in #7734

---

.github/ISSUE_TEMPLATE/bug_report.md
frontend/ui/elements/common_info_menu_table.lua

Requires https://github.com/koreader/android-luajit-launcher/pull/309
How the new message looks:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7709)

Bug report changes

---

frontend/apps/reader/modules/readercropping.lua
frontend/apps/reader/modules/readerzooming.lua

Expand #7728 to also catch SetZoomMode (mostly for Dispatcher's sake, but other things also send it).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7735)

ReaderZooming: Unconditionally update the configurables on SetZoomMode

---

platform/cervantes/koreader.sh

I have made the minimal modifications to enable the bomb crash screen on Cervantes while preserving as much of the current behavior as possible, but the current behavior is inconsistent: it leaves the restart loop for return values between 1 and 84 but treats any return value greater than 87 as a request to restart koreader.
I decided to maintain the spirit of the original script and only restart koreader for the special return values (85, 86 and 87), and exit for any other return value, showing the crash screen if the return value is not zero.
If it is deemed better that koreader.sh loops forever restarting koreader until the return value is zero I can change the code.
--- …

Enable bomb crash screen on Cervantes

---

frontend/apps/reader/modules/readerdictionary.lua

By showing a warning, instead of not passing any -u flag to sdcv and letting it query *all* dictionaries if FS order, which is mildly confusing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7737)

ReaderDictionary: Handle all dictionaries being disabled better.

---

frontend/apps/reader/modules/readerfont.lua
frontend/apps/reader/modules/readertypeset.lua
frontend/apps/reader/modules/readerview.lua

On Notifications when `getOptionText` returns not a value, use colon in message.
Reworded some notifications with "on" "off".
See https://github.com/koreader/koreader/pull/7718#discussion_r638670551
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7759)

Notification sentences

---

frontend/device/thirdparty.lua

They add noise to early logs, just to print defaults
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7760)

don't log thirdparty app list if they're platform defaults

---

frontend/device/android/device.lua

* save settings before installing a new APK & after resume (fixes #7724)
* move Resume/Suspend events to Resume/Pause callbacks (might help with https://www.mobileread.com/forums/showthread.php?t=339597)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7753)

android: minor fixes

---

plugins/opds.koplugin/opdsbrowser.lua

In accordance with
https://specs.opds.io/opds-1.2.html#513-summary-and-content
the `content` OPDS catalog entry is shown with this new button.
Useful before download.
Screenshots from flibusta.
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7767)

OPDS catalog: add book info button

---

frontend/apps/reader/modules/readerhighlight.lua

Pressing <kbd>Copy</kbd> in the popup highlight menu:
- copies the selection to the clipboard
- closes the popup menu
- clears the selection
- shows notification
Pressing <kbd>Copy</kbd> in the `…` HighlightDialog menu does not clear the highlighting.
Closes https://github.com/koreader/koreader/issues/7772
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7776)

ReaderHighlight: close popup menu on 'Copy'

---

frontend/ui/widget/keyvaluepage.lua

Allows to show an item's value with the same font size as the KVP table itself (which is based on the `Info lists items per page` setting).
Currently affects Book information (Book Description etc. will be shown with the same font size as the Book information table) and Reading statistics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7782)

KeyValuePage: propagate items font size to the child TextViewer

---

frontend/apps/reader/modules/readerkoptlistener.lua
frontend/apps/reader/modules/readerzooming.lua
frontend/ui/data/onetime_migration.lua

Namely, in case the user had a global legacy `zoom_mode` set.
Nothing can actually set this as a global anymore, but we were still honoring it... because we still use it for *local* DocSettings...(because everything is terrible and the internal API relies mostly on zoom_mode instead of the genus/type combos).
So, add some more public conversion methods, and get rid of the global.
Fix #7778
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7780)

ReaderZooming: Deal with some more zoom_mode shenanigans

---

plugins/opds.koplugin/opdsbrowser.lua

The library list font size is set in the `Item font size` setting.
This allows to show the book information with the same adjustable font size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7783)

OPDS browser: adjust book information font size

---

frontend/apps/filemanager/filemanagerbookinfo.lua
plugins/coverbrowser.koplugin/covermenu.lua

We can call the "Book description" window in three ways and all three windows have different titles.
**1. Via "Book information" KVP window.**
https://github.com/koreader/koreader/blob/0b58abada58ad21761ef3c8d6a8e9ecd68e54652/frontend/apps/filemanager/filemanagerbookinfo.lua#L204
--
The title is just a key name in the KVP table. The similar titles (`Key_name:`) are shown for other "Book information" fields.
**2. With a gesture in the reader.**
https://github.com/koreader/koreader/blob/0b58abada58ad21761ef3c8d6a8e9ecd68e54652/frontend/apps/filemanager/filemanagerbookinfo.lua#L272
**3. With a popup menu in the file browser detailed view mode.**
https://github.com/koreader/koreader/blob/0b58abada58ad21761ef3c8d6a8e9ecd68e54652/plugins/coverbrowser.koplugin/covermenu.lua#L348
It shows the …

'Book description' inconsistency fix

---

frontend/apps/reader/modules/readertoc.lua
frontend/ui/widget/menu.lua

Currently the ToC is shown with **three** font sizes:
- entry names
- page numbers
- entry names in popups
I propose to use one and only font size as set in the `ToC entry font size` setting.
Let persons with poor eyes increase interface elements if they need to.
Before
After
--
**ToC with dots**
Additionally, may I propose @poire-z to enhance nice dots https://github.com/koreader/koreader/pull/7669 in accordance with the typography rules recommendations:
I mean a large padding:
https://github.com/koreader/koreader/blob/0b58abada58ad21761ef3c8d6a8e9ecd68e54652/frontend/ui/widget/menu.lua#L273
and aligned right margin of the dots:
https://github.com/koreader/koreader/blob/0b58abada58ad21761ef3c8d6a8e9ecd68e54652/frontend/ui/widget/menu.lua#L290
The width of dots for the current entry to be …

ToC: harmonize font sizes

---

platform/debian/do_debian_package.sh

fakeroot was missing from the Docker image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7804)

[fix] Debian package: ensure failure is caught

---

frontend/ui/widget/numberpickerwidget.lua

Set date: number of days in direct input was 31 for all months.
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7803)

NumberPicker: correct max day in input dialog

---

Makefile
frontend/device/android/device.lua
frontend/ui/elements/common_info_menu_table.lua
kodev
platform/android/llapp_main.lua

Requires https://github.com/koreader/android-luajit-launcher/pull/276
- Bumps the target Sdk to Android 11 (API30)
- `kodev-log` uses `pidcat` if available
- Add a crash handler
The crash handler is raised on errors, like in other platforms, but the UI differs a bit:
-  App isn't restarted. The user needs to launch it again from the app launcher.
- Shows the entire log in a scrollable view
- Provides a share/send button
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7813)

Bump android backend

---

frontend/apps/reader/modules/readerfooter.lua
frontend/apps/reader/modules/readertoc.lua

Instead of baking in a hyphen, so as to avoid signed zeroes, or confusion with page progress if page maps are enabled.
Also, made compact items RTL friendly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7807)

[RFC] ReaderFooter: Make pages_left_book use an actual prefix icon

---

plugins/opds.koplugin/main.lua

OPDS catalog can be invoked from reader with gesture.
Then on closing OPDS catalog, KOReader crashes.
Let's jump to the download folder instead.
Closes https://github.com/koreader/koreader/issues/7784.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7825)

OPDS catalog invoked from reader: fix crash KOReader on close

---

frontend/apps/cloudstorage/dropboxapi.lua
frontend/apps/cloudstorage/webdavapi.lua

Re #7354
(Except w/ FTP, because LuaSocket's FTP module is a special snowflake, and the whole protocol is just plain terrible).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7834)

CloudStorage: Log download failures

---

frontend/ui/widget/menu.lua
frontend/ui/widget/touchmenu.lua
platform/kindle/koreader.sh
plugins/statistics.koplugin/main.lua

* #7867 (Attempting to store `nil` in a TEXT sql field leads to badness).
* Another "touch handler called before paint" race in TouchMenu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7868)

Another couple of fixes

---

frontend/device/android/device.lua

Requires https://github.com/koreader/android-luajit-launcher/pull/320
Also the luajit-launcher bump adds support for Likebook P78 and sanitizes clipboard text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7872)

workaround for Onyx Poke2 nonsense

---

frontend/apps/reader/modules/readerfooter.lua

Use the (smaller) "‹" or "›" symbols in pages_left_book, to match pages_left, in compact_items
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7828)

Use smaller symbols for pages_left_book in compact_items

---

frontend/ui/translator.lua

We have no Translation history, so at least the latest input to be saved for some use.
p.3 in https://github.com/koreader/koreader/issues/7851
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7855)

Translator: copy translation input to the clipboard

---

plugins/kosync.koplugin/main.lua

Add option to change checksum method in KOSync.
Binary = Default, currently in use by KOReader. Matches by using MD5 of 10x1024 byte chunks of the file itself.
Filename = Does an MD5 hash over the filename (foo.epub). Much less restrictive, but more likely to sync files especially if there are non-content changes made to an ePub, that do affect the resulting binary such as image scaling.
Because resulting document ID is the same MD5 digest, there are no KOSync server changes required. When a user switches between the two methods, they are effectively different documents to the server.
Tested using ePub's, and verified that if there is a collision of filenames with a different book, KOReader handles it in a sane way and sends the user back to the start of the file.
--- …

Add option to change checksum method in KOSync to be Binary or Filename based

---

frontend/apps/reader/modules/readerpaging.lua

Cf. <https://www.mobileread.com/forums/showthread.php?t=339912>.
I'll have to check why this doesn't work in continuous. Cf. https://github.com/koreader/koreader/issues/3932#issuecomment-395354006
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7820)

ReaderPaging: show page overlap menu in reflow

---

frontend/apps/reader/modules/readerfooter.lua
frontend/ui/data/onetime_migration.lua

Follow up and closes (?) https://github.com/koreader/koreader/pull/7242
Hides the battery status if battery level is higher than threshold.
Default threshold 100% (do not hide).
Requires one time migration to put `battery_hide_threshold` to the footer settings.
What date should be set at the migration module?
https://github.com/koreader/koreader/blob/12ebffc669a14a7775bd688548d7b962668d7414/frontend/ui/data/onetime_migration.lua#L221-L222
--
--
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7876)

Status bar: hide battery if level higher than threshold

---

frontend/ui/widget/inputdialog.lua
frontend/ui/widget/inputtext.lua
frontend/ui/widget/virtualkeyboard.lua

This set of updates summarizes the discussion from https://github.com/koreader/koreader/issues/7861 and includes;
1) **New way to hide the VirtualKeyboard**
Based on https://github.com/koreader/koreader/issues/7861#issuecomment-868804312, implemented via InputDialog.
To hide the keyboard tap any point of the screen outside the inputbox and above the keyboard.
To show the keyboard tap the inputbox.
Hacky "holding the arrow-down key" is not needed anymore.
2) **InputDialog windows are movable and transparentable by default**
Based on https://github.com/koreader/koreader/issues/7861#issuecomment-867218545.
3) **Redesign of the Clipboard dialog**
Actually we do not need a (duplicating) keyboard in the Clipboard dialog.
Clipboard dialog now is a TextViewer, all buttons and functionality …

InputDialog, InputText: a bunch of updates

---

frontend/apps/filemanager/filemanager.lua

Checks for existing destination file/folder for Rename operation and asks to overwrite.
The code for rename is unchanged, just wrapped into function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7833)

FileManager: add overwrite check for Rename

---

frontend/apps/reader/modules/readerdevicestatus.lua
frontend/ui/widget/menu.lua

`Menu: fix item sizes when switching display modes` Closes #7904.
`Device status: fix crash in debug mode` Fixes https://github.com/koreader/koreader/pull/7857#issuecomment-870558901
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7905)

Menu: fix item sizes when switching display modes

---

frontend/ui/widget/inputdialog.lua

New property to allow/deny hiding the keyboard with the tap outside of the dialog.
Useful in Text editor `Find` and `Go` dialogs (and maybe somewhere else, where hiding the keyboard is undesirable).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7908)

InputDialog: manage hiding the keyboard

---

frontend/ui/widget/keyboardlayoutdialog.lua

We've been locked in landscape.
Now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7911)

KeyboardLayoutDialog movable

---

frontend/document/credocument.lua

I've encountered an issue when Calibre Content Server's OPDS feed produced ``text/fb2-xml`` mimetype. Don't know if it is actually Calibre to blame, but thought this simple fix will save some poor souls' time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7932)

Add another mimetype alias for FB2 files for OPDS

---

frontend/apps/reader/modules/readercoptlistener.lua
frontend/apps/reader/modules/readerfooter.lua
frontend/ui/screensaver.lua
frontend/ui/widget/screensaverwidget.lua

* Simplify & cleanup weird useless duplicate refreshes, and move the OutOfScreenSaver event to the right place.
Fix #7643
* Also fix a bogus refresh on Resume if the CRe header is not actually enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7929)

ScreenSaver: Saner close behavior

---

frontend/apps/reader/modules/readersearch.lua
frontend/document/credocument.lua
frontend/ui/elements/reader_menu_order.lua
frontend/ui/widget/inputdialog.lua

For use with https://github.com/koreader/koreader-base/pull/1378
Adds a menu for regular expression searches and stores the last search string in full text as well as in regex search.
This should fix https://github.com/koreader/koreader/issues/7862
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7883)

Regex search menu

---

frontend/ui/widget/checkbutton.lua

Fix issue noticed at https://github.com/koreader/koreader/pull/7947#issuecomment-876693624 : _Long-press on (hold for help) makes and leaves the input dialog translucent._
Same bits of code as used in Button.lua.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7948)

CheckButton: fix hold when in a movable container

---

frontend/apps/reader/modules/readersearch.lua

;-)
Assuming you want it to show up as `'\'`, anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7952)

Fix wrong escape

---

frontend/apps/reader/modules/readerzooming.lua
resources/icons/mdlight/direction.LRBT.svg
resources/icons/mdlight/direction.RLBT.svg

Re #7964 & #7962
Low hanging fruits (i.e., make sure the configurables are kept up to date, and rename inverted icons).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7968)

ReaderZooming tweaks

---

frontend/device/sdl/device.lua

bump base: fix doc for ffi/utf8proc https://github.com/koreader/koreader-base/pull/1385 https://github.com/koreader/koreader/pull/7956#issuecomment-880626432
SDL keyboard input: should go to top level widget only
Avoid the typed input to be added to all InputText present on the stack: only the top one should handle it.
https://github.com/koreader/koreader/pull/7981#issuecomment-880896489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7982)

SDL keyboard input: should go to top level widget only

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/filemanager/filemanagerfilesearcher.lua
frontend/apps/filemanager/filemanagermenu.lua
frontend/ui/data/onetime_migration.lua
frontend/ui/widget/filechooser.lua

When using file search in filemanager, the found files are shown in the sorting order selected in filemanager.
BTW: The naming of natural/numeric sorting is inconsistent. In filemanager you can select "Sort by filename (natural sorting)", but in the menu before "Sort by: numeric" is shown. Shouldn't this be changed to "natural" as well? (and the `collate` setting migrated too)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7978)

FileSearcher honor filemanagers sorting order

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerview.lua
frontend/document/document.lua
frontend/document/koptinterface.lua
frontend/document/pdfdocument.lua
frontend/document/tilecacheitem.lua

`PDF text selection: fix/tweak spacing between words/boxes`
We may get multiple boxes when selecting texts, one for each word, and we have to add spaces between the extracted words ourselves. Previously, we were only adding a space if the last char of previous word was ASCII, so missing spaces after accents or greek words.
Try to do better by measuring the distances between boxes and comparing to box heights, with a few heuristics.
`PDF written highlights: fix boxes, trash cached tiles`
TileCacheItem: add created_ts property.
Document: manage a tile_cache_validity_ts and ignore older cached tiles.
This timestamps is updated when highlights are written as annotations in, or deleted from, the PDF, so we can get the most current rendered bitmap from MuPDF and avoid highlight ghosts on old …

PDF text selection & highlights: various fixes

---

frontend/device/input.lua
frontend/device/kobo/device.lua

Some devices have wonky input streams, so, don't rock the boat too much ;).
(e.g., I never get ABS_MT_PRESSURE events set to 0 on the Forma, which is essentially what makes the whole `snow_protocol` insanity necessary... We could possibly rely on the BTN_TOUCH events, but they're not in the same stream, so matching 'em to a slot would be tricky.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8004)

Minor input tweak after #7986

---

frontend/apps/reader/modules/readerview.lua

Small followup to e3bac94d.
Should avoid the confusing https://github.com/koreader/koreader/pull/7988#issuecomment-883977694 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8002)

PDF written highlights: trash cached tiles on close

---

frontend/ui/data/onetime_migration.lua

Do a reset of the duration format to use Classic, which is better for existing users of KOReader.
If existing users don't change their duration format for the footer it defaulted to "modern" so users were getting migrated to using "modern" setting which can look... pretty different. :)
Users can of course change the setting, but probably better to do a one time switch of everyone back to Classic to make sure everyone is using the intended default. If people do want to switch back to Modern, they can do so in the Time and Date settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8008)

Reset everyone's duration time to classic

---

frontend/apps/filemanager/filemanagermenu.lua
frontend/ui/widget/filechooser.lua
plugins/coverbrowser.koplugin/main.lua

Reordering of the file browser Settings menu and a couple of new features.
Main menu. No changes.
<kbd>![01](https://user-images.githubusercontent.com/62179190/126475633-998d813c-7109-4980-8484-596cc427cb6c.png)</kbd>
`Display mode` submenu. No settings here, moved to `Settings` submenu.
<kbd>![02](https://user-images.githubusercontent.com/62179190/126475637-96b63f93-64c1-4b96-a940-0fdc77e5845a.png)</kbd>
`Settings` submenu. **Main changes here.**
<kbd>![03](https://user-images.githubusercontent.com/62179190/126475639-50eb58e7-86b7-492b-8ef4-4aa459917f41.png)</kbd>
New item `Hide folders count`.
I do not need to know the quantity of elements in subfolders, prevent extra scanning and wearing of the device memory.
Default: unchecked (show count). If checked, looks like: …

File browser: Settings submenu reordering

---

frontend/ui/otamanager.lua

Grammatical conventions suggest we should use `check for updates` over `check for update`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8027)

Check for updates

---

frontend/apps/reader/modules/readertoc.lua

Reported by @ichnilatis-gr, see https://www.mobileread.com/forums/showthread.php?p=4140493#post4140493 and following.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8028)

[lang] Add a couple of plurals

---

frontend/device/gesturedetector.lua
frontend/device/input.lua

The kernel currently reports an ungodly amount of bogus 0-pressure *finger down* events, making the previously dumb logic highly annoying.
I can deal with missed pen taps (somewhat, it's still annoying). But missed *finger* taps are highly aggravating.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8021)

Input: Only ignore hovering *pen* events on the Elipsa

---

doc/Hacking.md
frontend/device/kobo/ntx_io.lua
platform/kobo/disable-wifi.sh
platform/kobo/enable-wifi.sh
platform/kobo/koreader.sh
platform/kobo/nickel.sh

* Kill NanoClock on startup (xref: https://www.mobileread.com/forums/showpost.php?p=4144385&postcount=72)
* Fix Wi-Fi toggle on the Elipsa (xref: https://www.mobileread.com/forums/showpost.php?p=4140835&postcount=3317)
* Set the Wi-Fi regulatory domain properly on the Elipsa, to avoid mishaps on the 5G band.
* Also, minor doc updates re: logger.dbg and evalution of function arguments in Lua.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8057)

A bunch of tweaks & fixes

---

frontend/apps/reader/modules/readerdevicestatus.lua

Some guys take care of the battery longlife and try to avoid overcharging:
https://www.mobileread.com/forums/showthread.php?p=4142290#post4142290
Battery level alert will show up when:
(1) the device is not charging and battery level becomes lower than low_threshold (default 20%), or
(2) the device is charging and battery level becomes higher than high_threshold (default 100% i.e. no alert).
<kbd>![1](https://user-images.githubusercontent.com/62179190/127649846-b0acc84f-4636-41ef-8bcd-6b47ee6e585a.png)</kbd>
<kbd>![2](https://user-images.githubusercontent.com/62179190/127649853-4d1c411b-79de-4197-969c-76da13c5f844.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreade …

ReaderDeviceStatus: add high battery level alert

---

frontend/apps/filemanager/filemanagerfilesearcher.lua
frontend/apps/reader/modules/readersearch.lua
frontend/ui/widget/checkbutton.lua
frontend/ui/widget/frontlightwidget.lua
frontend/ui/widget/inputdialog.lua
frontend/ui/widget/inputtext.lua

Some checkbutton long text (in translation) may be truncated.
<kbd>![1](https://user-images.githubusercontent.com/62179190/129183219-9f680334-8702-4886-aab3-23f03dbc8c09.png)</kbd>
Let's show the full text on hold (if no action assigned).
<kbd>![2](https://user-images.githubusercontent.com/62179190/129183257-db6a610d-6dd6-487a-b8d9-f8f6a896760b.png)</kbd>
As addition, fixing long text in Readersearch.
Before
<kbd>![3](https://user-images.githubusercontent.com/62179190/129183359-5b0eb11c-4654-45f2-ae12-87cea5060f4d.png)</kbd>
After
<kbd>![4](https://user-images.githubusercontent.com/62179190/129183374-d68cbbb1-41a2-45ba-9385-0ec684f4a602.png)</kbd>
--- …

Checkbutton: now multiline

---

frontend/ui/widget/confirmbox.lua
frontend/ui/widget/imageviewer.lua
frontend/ui/widget/screenshoter.lua

Some development of the screenshoter.
<kbd>![1](https://user-images.githubusercontent.com/62179190/128508894-466e2e67-ea03-4de2-95b1-1c0e5ea2f19e.png)</kbd>
We can preview the screenshot and delete it immediately if we don't like it.
Requires a small addition to the ConfirmBox to keep it open after previewing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8050)

Screenshoter menu development

---

frontend/apps/reader/modules/readergoto.lua
frontend/ui/widget/menu.lua

Two rows of the buttons. Closes https://github.com/koreader/koreader/issues/8051.
<kbd>![1](https://user-images.githubusercontent.com/62179190/128622972-7c8546c4-8983-440b-991a-c9cd178d7b4f.png)</kbd>
--
As addition, fix of 
https://github.com/koreader/koreader/blob/ba6fef4d7ba217ca558072f090849000e72ba142/frontend/ui/widget/menu.lua#L833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8056)

Menu widget: avoid truncation in "Go to letter" dialog

---

frontend/ui/widget/button.lua
frontend/ui/widget/textboxwidget.lua

If the button text would be truncated, try to avoid it by reducing the font size, and even switching to a 2-lines TextBoxWidget.
TextBoxWidget: fix possible glyphs truncations when a small line_height is used. Also avoid some bad result from getFontSizeToFitHeight(), possible due to some rounding errors.
Screenshots in https://github.com/koreader/koreader/pull/8056#issuecomment-898897244
This implements the 4th screenshot:
Might be a little ugly, but should rarely be seen in English, but may make the experience better with other languages - and with high-DPI settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8078)

Button: reduce font size to avoid truncation

---

frontend/ui/quickstart.lua

"../resources/..." was not working on some devices like Android. Build the correct relative path on all devices.
Fix https://github.com/koreader/koreader/pull/7985#issuecomment-884042869
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8072)

Quick start guide: fix links to images

---

plugins/profiles.koplugin/main.lua

Add the possibility to autostart profiles when KOReader is started with filemanager or lastfile.
Discussed in https://github.com/koreader/koreader/issues/8020
If more profiles are selected, they are started in alphabetically order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8049)

Autostart Profiles

---

frontend/ui/widget/checkbutton.lua
frontend/ui/widget/checkmark.lua
frontend/ui/widget/openwithdialog.lua
frontend/ui/widget/textboxwidget.lua

Continue of https://github.com/koreader/koreader/pull/8066.
(1) Accurate vertical alignment of Checkbutton parts (checkmark and button text): https://github.com/koreader/koreader/pull/8078#issuecomment-898942459
(2) `max_width` must be provided to Checkbutton by the caller, so no additional checks of width are needed in flashing part of the code.
(3) More accurate `max_width` in Open with... dialog (visible if flash_ui enabled).
Good alignment
<kbd>![1](https://user-images.githubusercontent.com/62179190/129551958-a180b449-0454-41f4-936b-a2800eb0c8c7.png)</kbd>
With bigger font size (for testing)
<kbd>![2](https://user-images.githubusercontent.com/62179190/129552018-9754e01f-5fa6-44a2-86f2-8a3ee72f9158.png)</kbd>
--- …

Checkbutton: accurate vertical alignment

---

frontend/apps/reader/modules/readerdevicestatus.lua

If an alert is on the screen waiting for a user's interaction - close it before showing the new one.
Separate battery and memory alerts.
Closes https://github.com/koreader/koreader/issues/8081.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8086)

ReaderDeviceStatus: show only one alert

---

frontend/ui/widget/inputtext.lua
frontend/ui/widget/textviewer.lua

(1) Before: when holding the input box in input dialogs for calling the Clipboard, hold release was passed to movable container and input dialog moved a little bit. Fixed.
(2) Before: empty clipboard title was **Clipboard (empty)**. Made consistent with input text hints.
(3) Now text color can be passed to the Text viewer.
<kbd>![1](https://user-images.githubusercontent.com/62179190/129720210-bc4d34df-1d27-4850-8c0e-4a657f752e5b.png)</kbd>
<kbd>![2](https://user-images.githubusercontent.com/62179190/129720219-b263f46b-5abb-4ca8-9660-afca61781128.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8091)

InputText: accurate handle hold, Clipboard empty hint

---

frontend/ui/data/css_tweaks.lua
frontend/ui/widget/button.lua
frontend/ui/widget/dictquicklookup.lua

`Footnote popups/in-page: support type/role=endnote` closes #8033
`Dict: avoid list items bullet/digit truncation with HTML dicts` closes #7946
`Button: avoid cut words when switching to multilines` See https://github.com/koreader/koreader/pull/8078#issuecomment-899242126
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8092)

Various fixes: footnotes, HTML dictionary, Button

---

frontend/apps/reader/modules/readertypography.lua
frontend/ui/translator.lua

When enabled, if the book has some supported language tag in its metadata, use it as the source language. Otherwise,
fallback to the current settings (auto-detect or selected source language).
See https://github.com/koreader/koreader/issues/8063#issuecomment-899440719.
Closes #8063 (not exactly the solution requested, but simple and good enough).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8094)

Translator: add "Translate from book language" option

---

frontend/apps/filemanager/filemanagerfilesearcher.lua

Currently we see filenames only.
<kbd>![1](https://user-images.githubusercontent.com/62179190/129892488-78d664db-0a52-4b43-b9e5-6a8cb14c7d32.png)</kbd>
Added hold action to show the full path. `Go to` on a file will open the folder with a focused file.
<kbd>![2](https://user-images.githubusercontent.com/62179190/129892648-3c6c8d2f-01e2-494d-b65c-56f7823dc210.png)</kbd>
<kbd>![3](https://user-images.githubusercontent.com/62179190/129892653-c601338e-8de3-45ca-9ab4-eb80f6f99c13.png)</kbd>
Minor optimization of the checkbutton code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8100)

File search: add hold in search results

---

frontend/device/android/powerd.lua

`warmth` is in `0-100` range, we need to scale it to `0-fl_warmth_max` range. 
closes #8070
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8104)

Fix warmth settings on some android devices

---

plugins/opds.koplugin/opdsbrowser.lua

It can happen… somewhere, while clicking around http://arxiv.maplepop.com/catalog a bit. (The magical crash/bug finder from <https://github.com/koreader/koreader/issues/3023>.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8111)

[plugin] OPDS: prevent crash if link.type is nil

---

frontend/util.lua
plugins/coverbrowser.koplugin/listmenu.lua
plugins/readtimer.koplugin/main.lua

Re: #8106 
* Cleanup util.secondsFrom*Clock stuff (simpler maths, tail calls, meaningful printf tokens).
* Use util.secondsToClockDuration in ReadTimer instead of reinventing the wheel three different ways.
* Reschedule unexpired timers properly on resume (as best as we can, given the unreliable nature of REALTIME).
* Make clock timers tick on the dot, instead of at the same second as when being set.
* Speaking of clock timers, leave the math to os.date & os.time, don't reinvent the wheel yet again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8107)

ReadTimer: More QoL tweaks

---

frontend/apps/filemanager/filemanager.lua
frontend/ui/widget/menu.lua

A minor design fix: margins of the folder name in the header made consistent with other elements.
Before
<kbd>![1](https://user-images.githubusercontent.com/62179190/130013507-9a85818b-953a-45ed-b680-5313f7c031b5.png)</kbd>
<kbd>![2](https://user-images.githubusercontent.com/62179190/130013512-99e238f9-ee86-4702-a0a4-bdea3d17d88c.png)</kbd>
After
<kbd>![3](https://user-images.githubusercontent.com/62179190/130013520-71482062-d99b-4ec3-82f9-a198fa4ae371.png)</kbd>
<kbd>![4](https://user-images.githubusercontent.com/62179190/130013526-e4d9d0e7-f5eb-453a-9065-ba2083c5695c.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8103)

File browser, Path chooser: fix margin of the long folder name in the header

---

frontend/ui/data/dictionaries.lua

Current link causes “could not save file to” error and just redirects to https://dicionario-aberto.net 's main page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8118)

 Fix link for Portuguese dictionary “Dicionário Aberto”

---

frontend/apps/cloudstorage/webdavapi.lua

Some servers serve <D:resourcetype></D:resourcetype> rather
than <D:resourcetype/>. So handle this case when deciding
if an item is not a collection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8121)

WebDAV: Handle non-self-closing tag for empty collection

---

platform/kindle/koreader.sh

https://github.com/koreader/koreader/pull/6233#issuecomment-903300554
Tested on my Voyage with KOL 1.1, very nice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8122)

Kindle: don't kill kb service on start

---

frontend/ui/data/creoptions.lua

I guess `full` was in one of the old iterations. Might affect translations though
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8141)

change "full" to "best" (kerning info)

---

frontend/ui/elements/menu_keyboard_layout.lua
frontend/ui/widget/keyboardlayoutdialog.lua
frontend/ui/widget/virtualkeyboard.lua

Legend:
KLM - main menu item `Keyboard layout` (with checkboxes)
KLD - KeyboardLayoutDialog (with radiobuttons)
Changes:
(1) KLM: limit the number of enabled layouts to 4.
Because of lack of space in the "globe" popup.
<kbd>![1](https://user-images.githubusercontent.com/62179190/131209388-2da69062-0b2a-4e70-bb49-d5a7e3dbf260.png)</kbd>
(2) KLM: long-press the layout to set it as "default".
Every new keyboard will be opened with "default" layout (except hide/show keyboard with a tap outside of input box).
Checkbox `Remember last layout`, default state: checked.
<kbd>![2](https://user-images.githubusercontent.com/62179190/131209394-029fbbeb-a36d-4f34-b103-3f98fcdfbf5c.png)</kbd>
(3) "Globe" button: tap remains enabled after selecting a layout via KLD.
If selected layout is enabled, a tap …

Virtual keyboard: default layout, compact mode

---

frontend/apps/reader/modules/readerpaging.lua
frontend/dispatcher.lua
frontend/ui/data/koptoptions.lua
frontend/ui/widget/configdialog.lua
frontend/ui/widget/toggleswitch.lua
plugins/batterystat.koplugin/main.lua
plugins/statistics.koplugin/main.lua
plugins/systemstat.koplugin/main.lua

Dispatcher: add Battery & System statistics
ConfigDialog: remove uneeded support for muliple events -Fixes reflow support for dispatcher
Dispatcher: update configurable before event (like configdialog)
Dispatcher: initial Kopt support
Statistics: move dispatcher items to plugin
---
Mostly done by #7827
this adds Dispatcher support for kopt options.
@zwim you should be able to add notification support in the kopt handler
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/7671)

 Koptoptions: add to dispatcher

---

frontend/ui/data/onetime_migration.lua
frontend/ui/elements/menu_keyboard_layout.lua
frontend/ui/widget/keyboardlayoutdialog.lua
frontend/ui/widget/virtualkeyboard.lua

Store list of layouts in settings file as array of enabled layouts only (up to 4 elements).
Optimize code.
Allows sorting of the abbreviations in the globe popup:
just check layouts in the desired order (the first checked will be northeast).
Requires onetime migration to clean up the settings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8159)

Keyboard layouts: optimize, sorting

---

frontend/device/kobo/device.lua
platform/kobo/disable-wifi.sh
platform/kobo/enable-wifi.sh
platform/kobo/koreader.sh
platform/kobo/nickel.sh

* Neater fbdepth usage on sunxi
* Make sure we only ever match *loaded* modules when we check lsmod
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8169)

Minor script tweaks

---

frontend/apps/reader/modules/readerfooter.lua
frontend/device/android/powerd.lua
frontend/device/cervantes/powerd.lua
frontend/device/devicelistener.lua
frontend/device/kobo/powerd.lua
frontend/device/pocketbook/powerd.lua
frontend/device/sdl/powerd.lua

This PR adds the possibility to add a frontlight warmth indicator to the bottom status bar.
Tested on Android (mobile and Tolino) and with the emulator.
Not tested on Kobos, Cervantes, Pocketbook. Could/wants someone to check these please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8060)

Add warmth to status line

---

frontend/apps/reader/modules/readerbookmark.lua

When matching a highlight to a bookmark *really* fails.
(Noticed in the log from #8175)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8176)

ReaderBookmark:renameBookmark: Better nil guard

---

frontend/apps/reader/modules/readermenu.lua
frontend/apps/reader/modules/readerpaging.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/apps/reader/modules/readerview.lua
frontend/ui/elements/page_overlap.lua

Add a default option for Page overlap enabled/disabled for new books (long-press as usual).
Closes https://github.com/koreader/koreader/issues/7757.
<kbd>![1](https://user-images.githubusercontent.com/62179190/132100043-5e5b4a9d-70af-4a25-b80f-60d94d94a149.png)</kbd>
Page overlap menu is a separate module.
Cleaned readerpaging, readerrolling, readerview of duplicated code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8180)

Page overlap menu

---

frontend/apps/reader/modules/readerdevicestatus.lua

Correct read settings.
Standardize showing values in menu (a colon).
SpinWidget and DoubleSpinWidget default widths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8194)

Readerdevicestatus: optimize code

---

frontend/ui/data/css_tweaks.lua

Add a few ruby style tweaks, put them in their submenu
See the long discussions we had with @davidvelosa in #8063, starting from https://github.com/koreader/koreader/issues/8063#issuecomment-899899625
I settled on only these, gave simpler titles, kept the technical details in the description:
Rewording/correction suggestions welcome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8189)

Style tweaks: add a few ruby specific tweaks

---

frontend/cache.lua
frontend/document/doccache.lua

This slightly strange use-case was broken since #7624 
Fix #8181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8198)

DocCache: Allow disabling it (again)

---

frontend/apps/reader/modules/readersearch.lua
frontend/ui/widget/button.lua
frontend/ui/widget/buttontable.lua

Reducing icon size in button in https://github.com/koreader/koreader/pull/8190 has affected other modules.
Restoring default icon size, reducing icon in Readersearch only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8206)

Icon in button: correct size

---

frontend/ui/network/wpa_supplicant.lua
frontend/ui/widget/networksetting.lua

Add support for AP without encryption
Note :
- open network have empty password (that how wpa_supplicant.lua recognize it)
- we still use the "set/edit password" widget so we can add/forgive the network
- we exclude WEP encrytion only now
#2784
It’s a bit hacky but work great on my H2O
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8196)

Add unencrypted wifi support

---

frontend/dispatcher.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua
plugins/SSH.koplugin/main.lua
plugins/bookshortcuts.koplugin/_meta.lua
plugins/bookshortcuts.koplugin/main.lua
plugins/calibre.koplugin/main.lua
plugins/gestures.koplugin/main.lua
plugins/hello.koplugin/main.lua
plugins/kosync.koplugin/main.lua
plugins/statistics.koplugin/main.lua
plugins/terminal.koplugin/main.lua
plugins/texteditor.koplugin/main.lua
plugins/wallabag.koplugin/main.lua

`Dispatcher: Revamp sections and item order`
` Dispatcher:removeAction()
Gestures: use sub_item_table_func to allow the menu to refresh on change`
`book shortcuts plugin`
---
Adds a plugin to allow adding a gesture to open a specific book.
Motivation: I use my kindle for daily study and am constantly switching between the same few books. I personally added a few custom ones already in one of my other [personal plugins](https://github.com/yparitcher/chitas.koplugin/blob/863a8ad0c549af878e830fe790eefb990f5efb85/main.lua#L36-L38), but they are getting hard to manage. This allows adding them easily on device.
Please let me know if this interests anyone, if it is ok for core or should be in contrib.
--- …

book shortcuts plugin

---

frontend/apps/reader/modules/readertypography.lua
frontend/ui/elements/refresh_menu_table.lua
frontend/ui/widget/configdialog.lua
frontend/ui/widget/datewidget.lua
frontend/ui/widget/doublespinwidget.lua
frontend/ui/widget/numberpickerwidget.lua
frontend/ui/widget/timewidget.lua

Changes to DoubleSpinWidget, TimeWidget, DateWidget.
(1) In landscape mode widgets have the same width as in portrait mode.
(2) Default width is 0.6 of the screen width in the portrait mode.
(3) Close button `x` removed from the title bar.
(4) Fixed a bug of long title in DoubleSpinWidget (https://github.com/koreader/koreader/issues/8192#issuecomment-917560853).
<kbd>![1](https://user-images.githubusercontent.com/62179190/133115746-a5a9f86c-fc33-4c1c-ab55-54d6f50e7125.png)</kbd>
<kbd>![2](https://user-images.githubusercontent.com/62179190/133115759-27f3d2c4-ce62-4f92-89cf-b9d5ef8060ed.png)</kbd>
<kbd>![3](https://user-images.githubusercontent.com/62179190/133115770-c6dcfbbf-cb0e-4722-a39a-07a485d1f5fb.png)</kbd>
<kbd>![4](https://user-images.githubusercontent.com/62179190/133115773-d6d5688 …

DoubleSpinWidget: keep size in rotation

---

plugins/newsdownloader.koplugin/feed_config.lua
plugins/newsdownloader.koplugin/feed_view.lua
plugins/newsdownloader.koplugin/main.lua

This PR includes the following changes:
- Changed the scope of a bunch of variables in `main.lua`
- Replaced `processRSS` and `processAtom` with `processFeed`.
- Fixed XML/Atom feeds not being downloaded because of a missing description
- Moved settings for downloading images to settings menu
- Changed some of the menu labels
- Added more verbose error messages during the downloads process
- Added a user flow with option to "Go to downloads" after feeds are downloaded
I've tried to follow the code styles for this project. Inevitably, I've probably introduced some of my own style biases.  
Please discuss!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8145)

Fixes and changes to newsdownloader.koplugin

---

plugins/newsdownloader.koplugin/feed_view.lua
plugins/newsdownloader.koplugin/main.lua

As per: https://github.com/koreader/koreader/pull/8145#issuecomment-918493892
Also: removed an unused function (`processAtom`).
Also: fixed punctuation and casing in comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8214)

Newsdownloader: Fix warnings from luacheck

---

frontend/apps/cloudstorage/dropbox.lua
frontend/apps/cloudstorage/ftp.lua
frontend/apps/cloudstorage/webdav.lua
frontend/apps/filemanager/filemanagerfilesearcher.lua
frontend/apps/filemanager/filemanagersetdefaults.lua
frontend/apps/reader/modules/readersearch.lua
frontend/ui/widget/inputdialog.lua
frontend/ui/widget/multiinputdialog.lua
plugins/calibre.koplugin/search.lua
plugins/opds.koplugin/opdsbrowser.lua
plugins/perceptionexpander.koplugin/main.lua
plugins/terminal.koplugin/main.lua
plugins/wallabag.koplugin/main.lua

(1) InputDialog: default width set to 0.8 of the screen width in portrait mode, keep in rotation.
<kbd>![1](https://user-images.githubusercontent.com/62179190/133770683-2d379374-740a-4d99-a5a2-6906c68b0184.png)</kbd>
<kbd>![2](https://user-images.githubusercontent.com/62179190/133770693-f4132a66-2641-419a-aed3-f85ae8218424.png)</kbd>
(2) MultiInputDialog: default width is set by InputDialog, some modules (filemanagersetdefaults, readersearch) require wider dialogs, keep in rotation.
Fixed an issue: cut of a high dialog in landscape mode.
Before
<kbd>![3](https://user-images.githubusercontent.com/62179190/133770704-fe63334c-fcbf-477a-8a0e-b94ac7116a16.png)</kbd>
After
<kbd>![4](https://user-images.githubusercontent.com/62179190/133770716-83bf4dd7-03dc-47e0-b601-ccbd2d3fd9d3.png)</kbd>
(3) …

Input dialogs: keep size in rotation

---

frontend/device/generic/device.lua
frontend/device/kobo/device.lua
frontend/document/djvudocument.lua
frontend/document/document.lua
frontend/document/koptinterface.lua
frontend/document/pdfdocument.lua
frontend/ui/widget/textboxwidget.lua
platform/kobo/koreader.sh
plugins/coverbrowser.koplugin/bookinfomanager.lua

* TextBoxWidget stuff for #8241
* Runtime selection of online CPU core count on Kobo (Elipsa) to allow spending most of our time with only a single core online.
(The 2 core switch is actually probably mostly overkill still, but, oh, well ;)).
* BookInfoManager: Avoid undefined behavior in `collectSubprocesses` .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8250)

A couple of fixes & tweaks

---

frontend/ui/widget/buttondialog.lua
frontend/ui/widget/buttondialogtitle.lua
frontend/ui/widget/buttontable.lua
frontend/ui/widget/confirmbox.lua
frontend/ui/widget/inputtext.lua
frontend/ui/widget/keyboardlayoutdialog.lua
frontend/ui/widget/multiconfirmbox.lua
frontend/ui/widget/notification.lua
frontend/ui/widget/skimtowidget.lua
frontend/ui/widget/virtualkeyboard.lua

The final round of setting the width of widgets in rotation (with https://github.com/koreader/koreader/pull/8212, https://github.com/koreader/koreader/pull/8223, https://github.com/koreader/koreader/pull/8226)
(1) ButtonTable, ButtonDialog, ButtonDialogTitle, ConfirmBox, MultiConfirmBox, SkimToWidget - keep size in rotation.
Before
<kbd>![1](https://user-images.githubusercontent.com/62179190/134162390-5006078d-5f04-463e-add3-9ea884d36bc4.png)</kbd>
<kbd>![2](https://user-images.githubusercontent.com/62179190/134162396-8e7608e9-64d6-45c8-8fff-d0bc17cddc4d.png)</kbd>
After
<kbd>![3](https://user-images.githubusercontent.com/62179190/134162398-97046ee8-4417-42f6-b2b5-bd6c0992a570.png)</kbd>
<kbd>![4](https://user-images.githubusercontent.com/62179190/134162403-64c3da70-8379-4607-9896-d10993a5 …

Widgets: keep size in rotation

---

frontend/apps/filemanager/filemanagerfilesearcher.lua

Correct call to show file manager, do not start new instance if exists.
Otherwise there was a warn in the crash.log: 
https://github.com/koreader/koreader/blob/3a01ab78994af9d232b2cd584eec6d5ea8a05b76/frontend/apps/filemanager/filemanager.lua#L1204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8257)

File searcher: correct call the FM

---

frontend/device/kobo/device.lua

io.lines only closes the fd when the loop is exited sanely, not by a control flow keyword (i.e., no break or return allowed).
Regression since #8169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8261)

Kobo: Don't leak fds in isWifiOn

---

frontend/device/cervantes/powerd.lua
frontend/device/devicelistener.lua
frontend/device/kobo/nickel_conf.lua
frontend/device/kobo/powerd.lua
frontend/ui/data/onetime_migration.lua
frontend/ui/widget/frontlightwidget.lua

Remove autowarmth from `frontlightdialog` as well as on kobo and cervantes `powerd`. If someone wants an advanced warmth setting, the upcoming `From dusk till dawn` plugin can be used. (https://github.com/koreader/koreader/pull/8129#issuecomment-905658485)
~~Missing is a onetime migration to remove the saved settings from `settings.reader.lua`.~~
Because I don't own a kobo or a cervantes this is a draft PR, as it has to be tested on these devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8154)

[frontlight, kobo, cervantes] Remove auto_warmth

---

plugins/autowarmth.koplugin/main.lua

Correct wordings to twilight, where dusk and dawn are meant.
Make translation strings easier to manage in the formatted overview (no spaces at the end of a string; use string.rep instead).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8262)

Autowarmth text formatting

---

frontend/ui/widget/textboxwidget.lua

Turns out we can't release line_num_to_image early, so,
delay it until the final, full widget teardown.
(Regression since #8250, c.f.,
https://github.com/koreader/koreader/pull/8250#discussion_r716646211)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8275)

TextBoxWidget: Unbreak Wikipedia

---

frontend/ui/widget/container/centercontainer.lua
frontend/ui/widget/inputdialog.lua
frontend/ui/widget/keyboardlayoutdialog.lua
frontend/ui/widget/multiinputdialog.lua

New property `ignore_if_over` allows to move the content (if it is bigger than the container) within the container to align upper or left borders (not both at once, analogue to existing `ignore`). Applicable, for example, to show the title of high dialogs in landscape mode.
Before
<kbd>![1](https://user-images.githubusercontent.com/62179190/135088164-80b76b33-5dee-450f-96e6-818acdf2fda6.png)</kbd>
After
<kbd>![2](https://user-images.githubusercontent.com/62179190/135088171-b56c251f-a11a-4802-9fa0-9d220547b8b1.png)</kbd>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8277)

CenterContainer: manage bigger content

---

plugins/autowarmth.koplugin/main.lua

For example: If in the overview of the autwarmth settings there are umlauts (utf8), the table is not justified.
~~With https://github.com/koreader/koreader-base/pull/1414 the problem is solved.~~ Not needed anymore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8271)

Autowarmth: Use number of characters not number of bytes

---

frontend/dispatcher.lua
frontend/document/koptinterface.lua
frontend/ui/data/koptoptions.lua

Fixes: #8286
Can we decouple k2pdfopt usage from reflow (text_wrap)?
this option like many is only enabled when reflow is on as only then is k2pdfopt used to render the page: https://github.com/koreader/koreader/blob/2b87b1d8ed0b71e8830615106b6d8fba86e67182/frontend/document/koptinterface.lua#L334-L342
like what optimized page does (for some reason it is only used for dewatermark):
https://github.com/koreader/koreader/blob/2b87b1d8ed0b71e8830615106b6d8fba86e67182/frontend/document/koptinterface.lua#L384
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8287)

kopt: allow pdf auto straighten

---

frontend/apps/reader/modules/readerhighlight.lua

This PR fixes a crash in readerhighlight. 
This bug was probably introduced with https://github.com/koreader/koreader/commit/7a0e3d5e68e4d119cdd60060a01303380e497c74#diff-db51db4b48e0314c642050876de6cd601d148eaaa00d4511523f811531d63ccf
To hit the bug, add a Gesture for going to `next bookmark`. Add a few bookmarks. Go to the first page. Apply the gesture for going to `next bookmark`.
-> Then KOReader jumps to the right page (wanted) and shows a HighlightMenu (which is not wanted).
-> Tap on e.g. Hyphenate (if you have enabled it) or Translate 
-> Crash
```
10/31/21-10:12:58 DEBUG setDirty fast from widget nil w/ region 27 404 242 37 
./luajit: frontend/apps/reader/modules/readerhighlight.lua:1239: attempt to index local 'selected_text' (a nil value) …
```

Fix crash in readerhighlight

---

plugins/autowarmth.koplugin/main.lua
plugins/autowarmth.koplugin/suntime.lua

Improvements in this PR
* Documentation update for ephemeris calculation;
* Calculate true noon and true midnight directly (important for special dates on positions, where we have only a sunset or sunrise);
* Fixed problems with high latitudes (over the polar circle, e.g. Hammerfest NO);
* Fixed some minor mistakes; 
* Improved accuracy (error less than half a minute on latitudes < 50°);
One minor problem has to be fixed (but not now, as I am to busy the next weeks):
* Accuracy for latitudes >65° are not so good for a about 14 days per year (around summer begin or when the midnight sun starts or ends)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8397)

[Autowarmth plugin] Optimisations; Documentation

---

frontend/apps/reader/modules/readerfooter.lua
frontend/device/generic/device.lua
frontend/ui/network/manager.lua
frontend/ui/network/wpa_supplicant.lua
frontend/ui/widget/progresswidget.lua
platform/kobo/koreader.sh

* Slightly more readable crash screen on the Sage, because the screen is too fast and GL16 too fugly otherwise.
* Workaround (maybe) a weird flash race in the sleep screen, where the secod flash may not cover the full screen region based on what was on screen *prior* to the white flash (??!!).
* NetworkManager: handle the case of a global preffered AP being sorted earlier than a KO preferred AP screwing everything up, because we attempted to associate to our own AP while wpa_supplicant was in the process of associating to its own AP.
(Fairly edge-casey, exposed by the fact that I have two different APs for the GHz and 2GHz band, the system's preferred AP is the 5G one, and KO's is the 2G one because I migrated my setting from a device with no 5G support, and I'm far enough away that the …

More Kobo Mk.8 tweaks

---

frontend/ui/data/dictionaries.lua

The previous version of JMdict comes from 2009 and doesn't appear to
work at all when trying to do basic lookups (likely due to some kind of
encoding problem). In addition, the license information and sourcing was
not really in line with the requirements specified by the JMdict
license. This version is far more up-to-date and also includes synonym-based
deinflection (though because KOReader has a Japanese plugin now, this is
technically not necessary).
Since there didn't exist a nicely-maintained place to download these
dictionaries (because StarDict is not widely used for Japanese
dictionaries), I've set up a personal GitHub repository where I've
hosted them. Note that we're intentionally not pinning the commit hash
because GitHub only recommends we use gh-pages for CDN purposes, and one …

dictionaries: switch to far more up-to-date JM(ne)dict

---

frontend/apps/reader/modules/readerhighlight.lua

It's possible for the user to have selected nothing, and trying to
operate on the nil highlight can cause confusion or crashes. This
restores the behaviour before commit 7a0e3d5e68e4 ("readerhighlight:
remove selected_word and use selected_text everywhere"), which missed
this case.
Fixes: 7a0e3d5e68e4 ("readerhighlight: remove selected_word and use selected_text everywhere")
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
/cc @hius07
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8399)

readerhighlight: ignore cases where no text is selected

---

plugins/coverimage.koplugin/main.lua

This PR changes the menu entries to colons and unlocks cache sizespinners, when cover image is not activated.
Honor recommendation of using a default value as in https://github.com/koreader/koreader/pull/7371#issuecomment-788157906
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8430)

[Coverimage, plugin] Colons in menus; unlock sizespinner 

---

frontend/apps/reader/modules/readerdictionary.lua

Another PR for consistency: Use colons in menus in readerdictionary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8431)

[readerdictionary] Colons in menus

---

frontend/docsettings.lua

Witnessed on Android with books on the external SD card.
See https://github.com/koreader/koreader/issues/8420#issuecomment-970249466. Closes #8420.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8448)

DocSettings: fix settings not saved when book on read-only FS

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerhighlight.lua

Allows to highlight bigger areas by selecting starting and ending fragments.
Issues to close: https://github.com/koreader/koreader/issues/7726, https://github.com/koreader/koreader/issues/7748
How to use: highlight starting fragment
Press `Extend highlighting`
Highlight ending fragment (it was a long-press on "Features")
The ending fragment can precede, follow, intersect or include the starting fragment.
Now works for cre documents only.
If this UX and coding approach is accepted, I shall look into pdf.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8432)

readerhighlight: extend highlighting

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerpaging.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/apps/reader/modules/readerview.lua
frontend/ui/elements/page_turns.lua

(1) inverse_reading_order moved to readerview
(2) setting forward and backward tap zones moved to readerview
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8445)

Readerpaging, readerrolling: remove duplicated code

---

frontend/apps/reader/modules/readercoptlistener.lua

Hopefully the last commit for colons in the menu.
Additionally, honor default values in `readSettings`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8436)

AltStatusBar: Consistent colons in menu

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerview.lua
frontend/apps/reader/readerui.lua

Bookmark/highlight formats in crengine and mupdf are incompatible.
This backups bookmarks and highlights when opening the document with an incompatible engine.
Fix crash when opening a document with highlights with different engine.
Closes https://github.com/koreader/koreader/issues/8451.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8455)

Backup bookmarks/highlights in incompatible engines

---

frontend/readhistory.lua
plugins/bookshortcuts.koplugin/main.lua

Allow setting a folder (not just a file) as a book shortcut with 2 options:
1. open FM: opens the FM in that folder
2. Last file: opens the most recently read book (via ReadHistory) in that folder. (this is what I use it for. A gesture to go back to the book i am in middle of by category (folder))
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8449)

[BookShortcuts] folder support

---

frontend/apps/reader/modules/readerfooter.lua

Introduced in https://github.com/koreader/koreader/pull/8419
Unfortunately it's not just useless, but it causes some edge case issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8464)

[bug] Don't translate empty strings

---

frontend/ui/network/networklistener.lua

I have a kindle & have restricted it via iptables to the local network so it will never be online. (There is no easy way to just allow traffic from koreader) 
This PR allows the wifi toggle (gesture) to turn off wifi when only connected to the local network as opposed to just re-turning on the wifi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8468)

toggle wifi when connected even if offline

---

frontend/apps/reader/modules/readerview.lua
frontend/ui/elements/page_turns.lua

Allows to choose a configuration of page turns tap zones.
`Default`: settings taken from defaults.lua/defaults.persistent.lua
`Left/Right`: full screen divided with a vertical border
`Top/Bottom`: full screen divided with a horizontal border (forward zone is at the bottom)
Customizable position of the border.
Other tap zones (menus, corners) unchanged.
`Invert page turn taps and swipes` doesn't swap `Top/bottom` zones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8475)

Customize page turns tap zones

---

frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/menu_keyboard_layout.lua
frontend/ui/widget/keyboardlayoutdialog.lua
frontend/ui/widget/virtualkeyboard.lua
frontend/util.lua
plugins/autosuspend.koplugin/main.lua
plugins/autoturn.koplugin/main.lua
spec/unit/util_spec.lua

This will be the second last maintenance for the menu for a while. Regards to the `Device menu`.
* Don't close menu, when selecting a screenshot folder.
* Set default size of keyboard only in `virtualkeyboard.lua` and not additionally in `menu_keyboard.lua` (maintainability).
* Use the proposed handling of default values or `readSettings` in `virtualkeyboard.lua`.
* Show selected keyboard(s) layout `Keyboard layout: Deutsch, English`.
* The autosuspend plugin is also situated in the device-menu.
* As a bycatch switch from `Autoturn (1 s)` to `Autoturn: 1 s`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8435)

DeviceMenu: Colons and more information

---

frontend/apps/reader/modules/readerview.lua

Fix for the backup of highlights/bookmarks (introduced in https://github.com/koreader/koreader/pull/8455).
Fixes opening book with old highlights, when (after deleting the last highlight on a page) empty table of highlights for this page was not deleted.
Thanks https://github.com/koreader/koreader/pull/8473#issuecomment-977818299
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8479)

Highlights backup fix

---

frontend/apps/filemanager/filemanagermenu.lua
frontend/device/android/device.lua

Now users can test light drivers too. See https://github.com/koreader/android-luajit-launcher/pull/339#issuecomment-977822717
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8483)

android: bump test activity

---

frontend/ui/data/css_tweaks.lua

Includes:
- bump crengine: adds CSS "-cr-only-if: txt-document" https://github.com/koreader/koreader-base/pull/1435
- Update button-listen for reMarkable firmware update https://github.com/koreader/koreader-base/pull/1428 . Closes #8242.
Style tweaks: have "Justify most/all text" work on txt documents. Closes #8456. Closes #8216.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8487)

bump crengine and button-listen.c for reMarkable

---

frontend/ui/widget/spinwidget.lua
plugins/gestures.koplugin/main.lua

`Default value` moved up, showing the default value.
`Extra` button moved up.
`Default` is upper.
This is a mockup of configdialog just to discuss is it worth to show the default value there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8485)

SpinWidget buttons move

---

platform/cervantes/obtain-ip.sh

This changes Cervantes' obtain-ip.sh so that it sends the hostname with the DHCP request.
This is useful because in some networks the DHCP server creates DNS records with the provided hostname, so you can use "ssh $HOSTNAME" instead of "ssh $IP_ADDRESS".
I don't know what hostname -s returns on an unmodified Cervantes, as I have long ago changed the hostname on mine. If anyone has a device with the original hostname and can run hostname -s on it so we can know if it's something reasonable it would be nice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8481)

Make the DHCP request include the device hostname on Cervantes.

---

plugins/gestures.koplugin/main.lua

Default value is shown in the SpinWidget default button, no need to show it in the info-text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8488)

Gesture intervals spinwidgets - do not show default value in info-text

---

frontend/ui/widget/configdialog.lua

The bug occurred for config settings with SpinWidget and DoubleSpinWidget.
For `Set as default` button the prefix was added to the setting name on every press of the button, producing names like `["copt_copt_copt_copt_font_size"] = 22`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8498)

ConfigDialog: fix set as default with spinwidgets

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/dispatcher.lua
frontend/ui/elements/reader_menu_order.lua
frontend/ui/widget/doublespinwidget.lua

Filtering bookmarks seems to work rather well (https://github.com/koreader/koreader/issues/8496), so it's time to rename it to Bookmarks search.
Also:
-accessible from the main menu and with a gesture
-case sensitive search
Closes https://github.com/koreader/koreader/issues/8496.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8504)

Bookmarks search

---

frontend/gettext.lua

Everything in string.gsub() is replaced, not only the matching group. By using two groups, we can correctly return the full matched string when none of the special conditions apply.
Fixes <https://github.com/koreader/koreader/issues/8486>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8511)

[fix] gettext: don't replace backslash characters

---

datastorage.lua

I tried using koreader on my PC using linux, and found it crashes because there is no `$HOME/.config` in my system, instead I use `$XDG_CONFIG_HOME`. I guess this should work, can't test it since im not able to build the project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8507)

[fix] Use XDG_CONFIG_HOME on Linux

---

frontend/docsettings.lua

When trying to open/delete a supported document with empty name (eg `.txt`) got an error
`./luajit: frontend/docsettings.lua:118: attempt to concatenate a nil value`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8517)

docsettings: fix open/delete file with empty name

---

frontend/ui/elements/font_settings.lua

As with the config, koreader wasnt loading my fonts, because they are in `$XDG_DATA_HOME`.
Already tested this fix and it works perfectly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8521)

[fix] koreader not using XDG_DATA_HOME to search for fonts

---

frontend/apps/filemanager/filemanagerfilesearcher.lua
frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readersearch.lua
frontend/ui/elements/menu_keyboard_layout.lua
frontend/ui/widget/checkbutton.lua
frontend/ui/widget/inputdialog.lua
frontend/ui/widget/inputtext.lua
frontend/ui/widget/openwithdialog.lua

Enabled checkbutton always toggles on tap (unless tap_input), so removed toggling from the callback code.
Removed duplicate code from modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8522)

Checkbutton: separate toggle and callback

---

frontend/apps/reader/modules/readerdictionary.lua

So the presence of a dict_ext and results from it are transparent to callers.
(This fix the warning log when dict_ext is there.)
See https://github.com/koreader/koreader/pull/8312#issuecomment-984019075 and follow ups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8523)

ReaderDictionary: merge dict & dict_ext results

---

frontend/document/credocument.lua
plugins/opds.koplugin/opdsbrowser.lua

(1) New button to rename a book before downloading. Closes https://github.com/koreader/koreader/issues/8508.
(2) While testing I've noticed that the Flibusta OPDS dialog is broken (wide 1st button, redundant separator between type buttons).
The reason is that Flibusta gives 6 acquisitions, but 2, 3 and 4 are unsupported (missing 2nd button widens the first one, missing 3 and 4 produce the separator).
The code for building button table is rewritten to filter out unsupported formats. Flibusta looks okay.
(3) But what are the unsupported formats from Flibusta? They are just zipped html, rtf and txt. Let's add a provider (crengine) and make them supported.
Finally we can get all formats and are sure that any (future) unsupported format shall not break our dialog.
--- …

OPDS: rename a book before downloading

---

frontend/ui/widget/numberpickerwidget.lua
frontend/ui/widget/spinwidget.lua

Regression since https://github.com/koreader/koreader/pull/8495. SpinWidget with `value_table` didn't work.
To reproduce: bottom menu, fine tune Contrast.
Fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8529)

SpinWidget fix enable/disable OK button

---

frontend/apps/reader/modules/readercoptlistener.lua
frontend/apps/reader/modules/readerrolling.lua

Includes https://github.com/koreader/crengine/pull/461 : 
- setStatusFontSize/Face(): avoid spurious re-rendering.
- Hanging punctuation: include it in native highlighting.
- Hanging punctuation: tweak hanging ratios again.
cre.cpp: don't Render() in setViewDimen(), we'll do that in a more controlled fashion in frontend https://github.com/koreader/koreader-base/pull/1438
Also bump Freetype to 2.11.1 https://github.com/koreader/koreader-base/pull/1436
Also include ffi/utf8proc.count() https://github.com/koreader/koreader-base/pull/1414
Also: ReaderRolling/ReaderCoptListener: fix a few re-rendering issues:
- When switching screen rotation, have the re-rendering properly done only via :onUpdatePos() - see https://github.com/koreader/koreader/pull/8501#issuecomment-986948160
- When changing …

bump crengine: avoid re-renderings, hanging punctuation tweaks

---

frontend/ui/widget/textboxwidget.lua

Just do as in _measureWithXText(): convert to string when text is not (ie. a number).
Closes #8542.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8545)

TextBoxWidget: fix crash in legacy mode

---

frontend/document/tilecacheitem.lua

This somehow fell through the cracks for all these years ;).
Requires https://github.com/koreader/koreader-base/pull/1440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8547)

TileCache: Preserve BlitBuffer's inversion & rotation

---

frontend/apps/filemanager/filemanager.lua
frontend/dispatcher.lua
frontend/ui/widget/filechooser.lua
frontend/ui/widget/iconbutton.lua
frontend/ui/widget/menu.lua
plugins/coverbrowser.koplugin/covermenu.lua
plugins/coverbrowser.koplugin/listmenu.lua
plugins/coverbrowser.koplugin/mosaicmenu.lua

New button in the Plus menu.
In select mode:
-Plus icon is changing to indicate the select mode
-tap a file to select/deselect
-selected file is dimmed
-browsing in folders in usual way
-folders cannot be selected
-long-press on files and folders is disabled
After selection, tap a Check icon for actions.
If the approach is accepted, I shall continue with more actions and non-classic display modes.
Closes https://github.com/koreader/koreader/issues/8524.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8536)

File manager: group operations

---

frontend/dispatcher.lua
frontend/ui/widget/spinwidget.lua

Regression after https://github.com/koreader/koreader/pull/8495: in assigning an action for a gesture OK button in SpinWidget was disabled for current value of a setting (until changing the value). Fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8558)

SpinWidget in Dispatcher fix

---

frontend/apps/filemanager/filemanager.lua
frontend/ui/widget/filechooser.lua

Long-press was not disabled in non-classic display modes, caused errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8567)

File browser select mode fix (disable long-press)

---

frontend/apps/reader/modules/readerhighlight.lua

Rolling is not ready at the moment of init yet. Regression after https://github.com/koreader/koreader/pull/8541.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8573)

ReaderHighlight: unlock "View HTML"

---

frontend/readhistory.lua

Fix: cannot open a book from History immediately after moving or renaming the file in the file browser.
Closes https://github.com/koreader/koreader/issues/8574.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8575)

Filemanager/History: fix book move/rename

---

frontend/ui/widget/button.lua
frontend/ui/widget/iconbutton.lua
frontend/ui/widget/menu.lua

New extra (left) button in the title of the Menu widget.
For consistency with the close (right) button, both are IconButtons, with widened tap zones.
Can be used to call actions applicable to all items of the list (bookmarks search, add cloud storage etc).
The icon of the extra button can be changed by the caller.
More screenshots to see and compare the design.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8564)

Menu widget: add extra (left) title button

---

frontend/ui/widget/textviewer.lua

When TextViewer is showing up, it causes screen refresh of the rectangle from the upper left corner of the screen (0,0) till the lower right corner of the TextViewer window (the result of `combine`).
So when the TextViewer is not full-screen, left and upper parts of the screen are refreshed.
This unpleasent screen flashing can be seen, for exampe, when showing book description from the Book information page, or when calling the clipboard (long-press on the text input box).
Let's show the TextViewer in a usual way, as (almost) all other widgets do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8576)

TextViewer: fix refresh

---

frontend/apps/cloudstorage/cloudstorage.lua

Cloud storage redesign, including:
(1) show server type in the list of storages
(2) add new cloud storage with a "plus" button (requires https://github.com/koreader/koreader/pull/8564)
(3) when browsing in a storage, the "plus" button is changed to the "home" button, to return to the CloudStorage home screen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8569)

CloudStorage redesign

---

plugins/exporter.koplugin/note.tpl

Based on some feedback from #8548 and #8535
This also sets the charset to UTF-8 to support more characters.
@hius07 Feel free to pull this change into any ongoing work you have for HTML export if that is easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8551)

Handle newlines in HTML highlight export

---

plugins/exporter.koplugin/note.tpl

Changes in accordance with https://github.com/koreader/koreader/issues/8535:
-add `html` and `body` tags to support older embedded browsers
-bookmark note formatting: grey letters, indented, without title
(Massive changes are caused with the indentation along the tags).
Screenshots: original text with 2 highlights, the note to the 2nd highlight, exported html.
Closes https://github.com/koreader/koreader/issues/8535.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8592)

Exporter plugin: html template fix

---

frontend/apps/filemanager/filemanager.lua

In select mode there is no access to the Plus menu.
For easy navigation let's add `New folder` and `Folder shortcuts` buttons to the select popup menu.
Additionally: new checkbox `Enter folder after creation` in the folder creation dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8595)

Filemanager select mode: add folder buttons

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerlink.lua
frontend/apps/reader/modules/readermenu.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/page_turns.lua
frontend/ui/elements/reader_menu_order.lua

They were ending up orphaned as `NEW:` in the top menu first tab, as we don't add any `Taps and gestures>` menu where most of them usually end up:
Only small hack is that we probably need `Invert page turn buttons` from `Page turns>` on non-touch devices, so I moved that single item into the `Navigation>` sub menu that is still there on NT devices.
There are probably other menu items/features that should not be made available on NT devices like `Panel zoom`, `Highlight style` (we can't highlight - but we could show highlights made on another device...), `Translation settings>` (we can't translate anything if we can't select text I think)... but well, would need taking a longer tour of everything that I'm not ready to make :) So, just cleaning the ugly "NEW:".
Note: I only tested all this …

[Non-Touch] Don't add touch-related menu items

---

frontend/ui/widget/menu.lua

Resize of the Menu widget title bar elements (discussed in https://github.com/koreader/koreader/issues/8549):
(1) No padding above the title
(2) Smaller left and right buttons icons
(3) Extended left and right buttons tap zones
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8603)

Menu widget: title bar resize

---

frontend/device/sdl/device.lua
frontend/ui/elements/screensaver_menu.lua
frontend/ui/screensaver.lua
frontend/ui/widget/imagewidget.lua
frontend/ui/widget/spinwidget.lua

The `screensaver` has much more possibilities as the `coverimage.plugin`. The only thing I am missing, is to set a threshold for stretching the image: If the aspect ratios of the image (cover) and the screen don't differ too much then stretch, else scale the image (cover).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8570)

Screensaver: add method to set a threshold for stretching

---

frontend/apps/cloudstorage/cloudstorage.lua
frontend/apps/cloudstorage/dropbox.lua
frontend/apps/cloudstorage/dropboxapi.lua

New actions in Dropbox account on tap on the Plus left button:
(1) Upload file (up to 150 MB file size)
(2) Create folder
Additionally:
(3) show file size in the file list
(4) allow to enter empty folders (showing "No items", like in FM)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8610)

Dropbox: upload file, create folder

---

plugins/exporter.koplugin/main.lua

Ensure that we're actually connected before sending highlights, otherwise the plugin will just error. I missed this in my earlier testing, since I was mostly testing through the emulator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8604)

Exporter plugin: Connect to internet before sending highlights

---

frontend/ui/widget/filechooser.lua

(1) If files filtering is enabled, PathChooser shows full number of files in subfolders, instead of the number of filtered files.
Example: choose an image for screensaver. Only image files are filtered, but the total number of files in subfolders is displayed. 
Fixed.
(2) Number of folders and number of files in subfolders are displayed separately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8598)

FileChooser: fix and show number of files

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerlink.lua
frontend/apps/reader/modules/readerthumbnail.lua
frontend/apps/reader/modules/readertoc.lua
frontend/apps/reader/readerui.lua
frontend/dispatcher.lua
frontend/ui/elements/reader_menu_order.lua
frontend/ui/widget/bookmapwidget.lua
frontend/ui/widget/container/scrollablecontainer.lua
frontend/ui/widget/pagebrowserwidget.lua
frontend/ui/widget/titlebar.lua
plugins/statistics.koplugin/main.lua

Existing widgets building their own title bar with help of CloseButton should progressively be updated to use this, for clarity, consistency, and less code duplication.
It follows the look/sizes/positionnings of the recent Menu header redesign of #8549 and #8603, so we can have more title bars and close icons looking similar.
For now, it's only used by the new Book map and Page browser widgets. I tested this with DictQuickLookup and CalendarView, but I'll add these in a later PR.
(There is some occasional refresh glitches when tap on the Close button when flash_ui is enabled, that I have not fixed in this commit - I could avoid it with a allow_flash=false in IconButton, but I may let @NiLuJe have a look first - couldn't pinpoint what is really happening...)
- Book map: shows a map of …

Add Book map and Page browser

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/document/djvudocument.lua
frontend/document/koptinterface.lua
frontend/document/pdfdocument.lua

Bookmarks of one page will be sorted depending on their position in the text (now they are sorted in order of adding).
Page bookmark is the first (before highlights and notes).
If two highlights start at one position, the shorter one will be the first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8616)

Bookmarks: fix sort within one page

---

frontend/device/pocketbook/device.lua

When using the PB741 color the wifi is checked connected when there is
actually no connection yet. This is caused by a different connected state
being returned by the PB741 color.
More info found in #8617
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8621)

Fix #8617: WiFi network returns connected without connection for PB741 color

---

frontend/document/koptinterface.lua
frontend/ui/widget/textviewer.lua

Fix crash when trying to select text in djvu (reflow off).
```
./luajit: frontend/document/koptinterface.lua:671: attempt to perform arithmetic on local 'nr_word' (a nil value)
frontend/document/koptinterface.lua:671: in function 'getTextBoxes'
frontend/document/koptinterface.lua:1156: in function 'getTextFromPositions'
frontend/apps/reader/modules/readerhighlight.lua:1082: in function 'handler'
frontend/ui/widget/container/inputcontainer.lua:255: in function 'handleEvent'
frontend/ui/uimanager.lua:1119: in function 'sendEvent'
frontend/ui/uimanager.lua:53: in function '__default__'
frontend/ui/uimanager.lua:1603: in function 'handleInputEvent'
frontend/ui/uimanager.lua:1683: in function 'handleInput'
frontend/ui/uimanager.lua:1730: in function 'run'
./reader.lua:323: in …
```

Fix djvu crash

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/ui/widget/bookmapwidget.lua
frontend/ui/widget/dictquicklookup.lua
frontend/ui/widget/iconbutton.lua
frontend/ui/widget/keyvaluepage.lua
frontend/ui/widget/pagebrowserwidget.lua
frontend/ui/widget/titlebar.lua
plugins/statistics.koplugin/calendarview.lua
resources/icons/mdlight/close.svg

Discussions and screenshots about this in #8625 and #8627.
- Fix hold callback name
- Add options to handle long titles (truncated by default): "title_multines" and "title_shrink_font_to_fit" (allowing setTitle() with them makes the code a bit more complex).
- Add options to set bottom line color and horizontal padding.
- Use an added title.close.svg (based on exit.svg, tweaked to have similar size and baseline as other icons) for close button.
IconButton:
- handle hold/hold_release similar to Button.
- new option allow_flash to allow disabling flashing
Also tweak ReaderHighlight:onHoldRelease() to avoid doing its stuff when onHold() is clearing highlight (previous CheckButton was closing/clearing on hold release, new TitleBar close button does that on hold).
--- …

TitleBar: new options, dedicated close button

---

frontend/ui/widget/textviewer.lua

New TitleBar widget used. Very nice.
In the last screenshot we can compare new close button with old close button in KVP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8625)

TextViewer: insert TitleBar

---

frontend/ui/widget/sortwidget.lua
frontend/ui/widget/textviewer.lua
resources/icons/mdlight/appbar.menu.svg
resources/icons/mdlight/check.svg

Before (lines are dark-gray)
After (lines are black, default, hardcoded in the TitleBar)
If we want to reduce the top padding (the content is not vertically centered)
Title bars
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8627)

SortWidget: insert TitleBar

---

plugins/coverbrowser.koplugin/listmenu.lua

Caused by #8598
Trips this dbg guard.
https://github.com/koreader/koreader/blob/ec280f874f0cfce660bdb4d396589939503d3c8b/frontend/ui/widget/textwidget.lua#L178-L182
There is probably a better way to fix this.
Stack trace:
```
./luajit: frontend/ui/widget/textwidget.lua:180: Wrong text type (expected string)
[C]: in function 'assert'
frontend/ui/widget/textwidget.lua:180: in function 'pre_guard'
frontend/dbg.lua:64: in function 'updateSize'
frontend/ui/widget/textwidget.lua:300: in function 'getWidth'
plugins/coverbrowser.koplugin/listmenu.lua:236: in function 'update'
plugins/coverbrowser.koplugin/listmenu.lua:178: in function 'init'
frontend/ui/widget/widget.lua:48: in function 'new'
plugins/coverbrowser.koplugin/listmenu.lua:1000: in function '_updateItemsBuildUI' …
```

filechooser: istr needs a string

---

plugins/wallabag.koplugin/main.lua

This will allow koreader users to choose to add tags in the review field (separated by comas), and then send them to wallbag.
It adds and option for that (a checkbox) in the wallabag plugin options.
It could be useful to directly tag articles on koreader to find them easily later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8637)

Wallabag : adds an option to send the review as tags on wallabag

---

frontend/apps/reader/modules/readerbookmark.lua

Revert some bits from 55532b13 (#8639 , commit https://github.com/koreader/koreader/pull/8639/commits/89327a22e8fadceb215c2a0f8e3fc5e239fbd9af), as the otherwise uneeded CenterContainer is used by unit tests.
See https://github.com/koreader/koreader/pull/8639#pullrequestreview-848337420
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8645)

ReaderBookmark: fix issue with unit tests

---

platform/common/spinning_zsync

`# shellcheck disable=SC2039,SC3040` is only if you want it to pass multiple versions, but I figure there's not much reason to keep the old exception for <=0.7.1 in there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8618)

[CI] Minor shellcheck cleanup

---

frontend/device/pocketbook/device.lua

Apparently, inkview.NetConnect() doesn’t enable the Wi-Fi on its own,
this results in a failure if the device has been put into the sleep or
standby mode, when the Wi-Fi hardware is powered down.
This fixes the bug #4747.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8546)

Pocketbook: switch the Wi-Fi on before attempting to connect (#4747)

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/ui/translator.lua

May be used to save translation as a note to the highlighted text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8669)

Translator: add copy to clipboard

---

frontend/apps/filemanager/filemanager.lua
frontend/device/android/device.lua
frontend/device/sdl/device.lua

regression from #8648
FileManager.instance.banner was removed and replaced with TitleBar
Discovered by dragging the emulator by mistake :)
also 
`FM select mode: let the icon survive through reinit not only rotation`
This commit was not tested for every type of reinit but it should work
@hius07
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8678)

SDL & Android: Do not set FM banner on resize

---

plugins/batterystat.koplugin/main.lua

regression from #8491
papered over in #8582
Fixes #8644 #8687
Root cause was util.secondsToClockDuration (called by duration) takes seconds and we were giving it hours as `Change per hour` needs hours
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8688)

Battery Stat: Fix remaining & per hour numbers

---

frontend/apps/reader/modules/readerdictionary.lua
frontend/apps/reader/modules/readerwikipedia.lua
frontend/ui/widget/dictquicklookup.lua
frontend/ui/widget/htmlboxwidget.lua
frontend/ui/widget/textboxwidget.lua
plugins/coverbrowser.koplugin/bookinfomanager.lua
plugins/coverbrowser.koplugin/listmenu.lua

`CoverBrowser: use translations for error messages`
Closes #8594.
`Fix hold duration in text/html box widgets`
Fix very-long-press in DictQuickLookup that should allow doing the query to the other domain (dict <> wiki) instead of the current one.
Similar to 7dea979.
`Wikipedia: rework wiki languages internal handling`
Fix various issues with stacked Wikipedia lookup results, and follow up lookups when invoked from Wikipedia lookup history (where going to a search for language LL would not use language LL when hitting "Full wikipedia").
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8677)

Wikipedia: rework wiki languages internal handling

---

frontend/device/generic/device.lua
frontend/device/generic/powerd.lua
frontend/device/kobo/device.lua
frontend/device/kobo/powerd.lua
frontend/document/canvascontext.lua
frontend/document/document.lua
frontend/document/koptinterface.lua
frontend/ui/data/onetime_migration.lua
frontend/ui/uimanager.lua
frontend/ui/widget/touchmenu.lua
platform/kobo/koreader.sh

* Initial support for the Sage PowerCover (i.e., display its status in the TouchMenu footer).
I left the footer & co alone, because I don't really care about seeing that much detail in those other contexts.
* Fix the update progress bar on sunxi. I had noticed that is was hella broken on the Elipsa & Sage with the latest FW (while I could have sworn it originally worked on the Elipsa...).
* Above fix led me to a simpler workaround for similar issues with the crash screen.
* Set the CPU governor on *all* cores if possible (that's a NOP in practice, because we don't change the governor on SMP devices).
* Accurately refresh the charging LED state on startup & resume, accounting for the PowerCover (i.e., charging == charging the *cover*).
* Stash `enableCPUCores` in `CanvasContext`, to avoid …

A few Kobo/sunxi tweaks & fixes

---

plugins/exporter.koplugin/clip.lua

for platforms where history dir don't match installation path.
Fixes https://github.com/koreader/koreader/issues/8675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8685)

exporter plugin: fix history dir

---

frontend/ui/widget/pathchooser.lua

`pathchooser.lua` does not support non-touch device to choose file or folder due to those device cannot generate long press event.
Non-touch device can select file in list, it is good enough to choose file without long press to confirm.
`pathchooser.lua` changes the label of current directory `.` to `Long-press to choose a folder`. It is user friendly, while for non-device, it is a very good place to let user tell the system I want the current folder to be chosen without extra long press.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8696)

Support non-touch device to choose file or folder

---

frontend/ui/data/css_tweaks.lua
frontend/ui/wikipedia.lua

Includes https://github.com/koreader/crengine/pull/462 :
- LVHashTable::resize(): behave as ::init()
Fix floating point crash in #8583
- FB2 series: extract series number as string, not int
Closes #8666
- Non-linear fragments: more generic handling
Closes #8623
- CSS: list-style-position: correct alignment for "outside"
- List items: fix marker not drawn with position:inside and no content
- (Upstream) Ordered list markers: add a decimal point suffix
- List item markers: more pleasant rendering
Closes #8668
- renderListItemMarker(): cleanup, minor optimizations
Also: `Wikipedia: tweak EPUB css and footnote styletweaks
`
EPUB: have pages with footnotes marked as non-linear so they can be hidden with "Hide non-linear flows".
In-page footnotes: keep the footnote number near the left margin …

bump crengine: non-linear fragments and list item tweaks

---

frontend/device/android/device.lua

Its custom intent was borked on last update and doesn't work anymore.
Fixes https://github.com/koreader/koreader/issues/8718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8721)

Colordict: use generic send intent.

---

frontend/apps/filemanager/filemanagershortcuts.lua
frontend/ui/data/keyboardlayouts/ja_keyboard.lua
frontend/ui/widget/inputtext.lua
frontend/ui/widget/keyboardlayoutdialog.lua
frontend/ui/widget/openwithdialog.lua
plugins/opds.koplugin/opdsbrowser.lua

Minor UX fixes and standardization
(1) OpenWithDialog: movable; checkbuttons added via standard `addWidget`
(2) KeyboardLayoutDialog: insert TitleBar
(3) Clipboard: disable Paste button on empty clipboard
(4) OPDS book info: multiline title (book author and title)
(5) Folder shortcuts: standard "plus" button to add a shortcut
(6) ja_keyboard Keitai tap interval: no default value in description (shown in default spinwidget button)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8720)

Various UX fixes

---

frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/font_ui_fallbacks.lua
frontend/ui/elements/reader_menu_order.lua
frontend/ui/font.lua

Add a submenu allowing users to add Noto Sans fonts to be used as UI fallback fonts.
Lots of them are alrady there on Android (I get 8 pages of fonts on my old Android phone), but can be downloaded (manually) and side-loaded by the user on other devices.
Addresses issue at https://github.com/koreader/koreader/discussions/8655 with the solution from https://github.com/koreader/koreader/discussions/8655#discussioncomment-2016822.
I've put the submenu under `Device>` for lack of a better idea, but afterall, it's about other fonts available on the device :)
Re/good-wording suggestions welcome :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8722)

UI font fallbacks: allow using more "Noto Sans xyz"

---

frontend/apps/reader/modules/readerconfig.lua
frontend/ui/widget/button.lua
frontend/ui/widget/buttonprogresswidget.lua
frontend/ui/widget/buttontable.lua
frontend/ui/widget/configdialog.lua
frontend/ui/widget/container/framecontainer.lua
frontend/ui/widget/doublespinwidget.lua
frontend/ui/widget/focusmanager.lua
frontend/ui/widget/iconbutton.lua
frontend/ui/widget/numberpickerwidget.lua
frontend/ui/widget/radiobuttontable.lua
frontend/ui/widget/skimtowidget.lua
frontend/ui/widget/spinwidget.lua
frontend/ui/widget/toggleswitch.lua
frontend/ui/widget/touchmenu.lua
frontend/ui/widget/virtualkeyboard.lua
tools/wbuilder.lua

There are many difficulties for non-touch to use reader configuration panel.
* Cannot select specified value, only cycle toggle one by one: `toggleswitch` and `ButtonProgressWidget`
* Cannot select `⋮` button: `toggleswitch` and `ButtonProgressWidget`
* Dialog opened by `⋮`  cannot focus button in dialog content.
`FocusManager` is a based on `InputContainer`. It maintains a 2D table layout which contains focus-able widgets. `FocusManager` handles `left`, `up`, `right`, `down` press events. On those keys pressed, it send `unfocus` event to current focused widget and `focus` event to next widget.
Widget updates its style on receiving  `unfocus`and `focus`event.
A container widget(like dialog), extend `FocusManager`, add focus-able widget to `layout` field on `init`. Then the container has …

Improve reader config dialog for Non-Touch devices

---

frontend/ui/widget/bookmapwidget.lua
frontend/ui/widget/bookstatuswidget.lua
frontend/ui/widget/imageviewer.lua
frontend/ui/widget/keyvaluepage.lua
frontend/ui/widget/menu.lua
plugins/statistics.koplugin/calendarview.lua
plugins/statistics.koplugin/readerprogress.lua

For consistency with BookMap and PageBrowser widgets where swipe south (the usual gesture to quick close) can't be used for closing and we had to use any multiswipe instead, allow any multiswipe to close these other fullscreen widgets too:
Menu (ToC, Bookmarks), KeyValuePage, ImageViewer, BookStatusWidget, ReaderProgress, CalendarView.
See https://github.com/koreader/koreader/pull/8613#issuecomment-1019557277 item **C**.
(Didn't do SortWidget - rarely used and can't be associated to a gesture - and FootnoteWidget - non fullscreen.)
See https://github.com/koreader/koreader/pull/8613#issuecomment-1019583186
Added this line to the info text:
--- …

Allow any multiswipe to close some fullscreen widgets

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerview.lua
frontend/document/pdfdocument.lua

(1) New `strikeout` highlight style.
Requires https://github.com/koreader/koreader-base/pull/1450.
(2) Fix changing highlight style in pdf documents with enabled `save_document`.
Fix ugly combination of mupdf and KOReader highlights. Closes https://github.com/koreader/koreader/issues/8663.
Before
After
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8725)

Highlight: strikeout style, fix pdf highlight

---

plugins/wallabag.koplugin/main.lua

In this PR https://github.com/koreader/koreader/pull/8637
It worked on my sev environnement, but when updating my device, there
were synchronization errors.
Apparently sometimes documents do not have a summary.
To avoid an error during the synchronisation this change adds checks
when getting tags for the document.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8733)

wallabag : fixes synchronization when "send review as tags" is checked

---

frontend/device/pocketbook/device.lua

Needs following PR too: https://github.com/koreader/koreader-base/pull/1451
Fixes: https://github.com/koreader/koreader/issues/7406
Fixes: https://github.com/koreader/koreader/issues/8187
Needs testing for: https://github.com/koreader/koreader/issues/6479
I've been emailing about color support for the pocketbooks directly with Pocketbook. The awesome folks of pocketbook replied with the implementation of rendering with the native inkview library. I've tested this with my Pocketbook 741 and the results are very promising.
This is their answer:
> Support for PB741 (InkPad Color)
> https://github.com/koreader/koreader/issues/7406 
>
> There are two types of color screens used by PocketBook: Kaleido and Kaleido plus. These two types have slightly different color filter patterns. Thus we need …

PocketBook: Handle rendering of interface and books directly with inkview

---

frontend/ui/widget/focusmanager.lua

Fix https://github.com/koreader/koreader/pull/8712#issuecomment-1023134610
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8737)

FocusManager: only trigger selected widged in focused style with DPad support device

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/ui/widget/textboxwidget.lua

(1) New button <kbd>Go to bookmark</kbd> in Bookmark details dialog.
(2) New button <kbd>Latest bookmark</kbd> in the popup menu.
(3) Empty input box for new note, new button <kbd>Paste</kbd> to paste highlighted text (auto-text). Closes https://github.com/koreader/koreader/issues/8736.
(4) Allow duplicated bookmarks to avoid orphaned highlights.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8738)

Bookmarks: Go to bookmark, Latest bookmark, empty note

---

frontend/device/pocketbook/device.lua

Added the [PocketBook Basic Lux 3](https://goodereader.com/blog/electronic-readers/__trashed-4) and amended PB606's comment name to PocketBook Basic 4,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8740)

Add PocketBook Basic Lux 3 (PB617)

---

plugins/terminal.koplugin/terminputtext.lua

This fixes a crash in terminal emulator on exit of elinks.
see: https://github.com/koreader/koreader/pull/8636#issuecomment-1024956177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8749)

[fix, plugin] Terminal emulator: Fix elinks -> 'q' crash

---

frontend/device/pocketbook/device.lua

This change drops the #koreader signature check. This check prevents KOReader from modifying associations if something else has changed the file without putting a verbatim `#koreader` string back. While this prevents KOReader from interfering with another application or the system trying to own the file, it also leads to hard to diagnose issues, when the user can inadvertently change associations without realising they’re doing so, and being unable to return back.
One way this can happen if the user temporarily uninstalls KOReader, powers the device back on again, and then installs it back. The system will drop unknown applications from the associations file and remove the signature as well.
Fixes: #8728
See also: http://www.mobileread.mobi/forums/showthread.php?t=339558
---
This change …

PocketBook: make canAssociateFileExtensions always return true

---

frontend/apps/reader/modules/readerrolling.lua
frontend/ui/widget/keyvaluepage.lua
plugins/statistics.koplugin/calendarview.lua
plugins/statistics.koplugin/main.lua

Please review by looking at each individual commmits - as some of them are just chores repeating the same changes.
`ReaderStatistics: remove id_book parameter to insertDB()`
As it should always just work on the current book.
Also remove uneeded getCalendarView().
`ReaderStatistics: fix current page stats on close/suspend`
Fixes current page statistics (duration) ignored when document closed, or when suspending and resuming.
On suspend/resume, update the page start ts by the time spent sleeping, so its duration will be the time spent on it not sleeping.
This fixes in a more generic approach the issue noticed at https://github.com/koreader/koreader/pull/6778#issuecomment-982779673 , which became more noticable now that we have Book map.
I made `onReadingPaused()` and `onReadingResumed()` …

Reading statistics: various fixes and tweaks

---

frontend/apps/reader/modules/readercoptlistener.lua
frontend/apps/reader/modules/readerrolling.lua

As a proud new owner of a KOBO Sage + power cover, I realized, that the alternate status bar is showing `[ + ]` (=charging), when the device is connected to the power cover. 
This PR shows fixes the problem `[ + ]` is only shown, when the device or the device+cover combo is plugged in a power source and not when the device is charging from the cover.
A minor drawback remains: When pulling the device out of the cover, or putting it in the cover, the alternate status bar is updated either on a page change or after a minute (and not immediately).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8741)

[AltStatusBar] Don't show [+] in status line when loading from power cover

---

frontend/apps/reader/modules/readerfooter.lua
frontend/device/generic/powerd.lua
frontend/ui/uimanager.lua
frontend/ui/widget/touchmenu.lua

* Fix the battery capacity pulls during early boot issue mentioned in #8711 
* Handle the PowerCover in ReaderFooter's battery gauge widget (re #8741)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8752)

Even more PowerD & PowerCover shenanigans

---

frontend/ui/widget/radiomark.lua

A small down shifting of the radio mark to eliminate visual effect of round mark being upper than the text.
Before
After
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8771)

RadioMark: down shift

---

frontend/ui/widget/pagebrowserwidget.lua

Instead of using the depth configured in Book map, start with max depth, and allow decreasing (and reseting when at 0) with long-press on the (i) top left icon.
See https://github.com/koreader/koreader/pull/8613#issuecomment-1025716574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8772)

PageBrowser: allow changing nb of chapter levels shown

---

frontend/ui/widget/frontlightwidget.lua
frontend/ui/widget/naturallightwidget.lua

Removed the last old close button.
Both widgets are now movable, so removed jumping down/up of the Frontlight dialog when opening Naturallight configuration.
Before
After
I have no device with warmlight, so made it blindly, looking at the picture in https://github.com/koreader/koreader/pull/3744#issuecomment-372471223.
Need testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8769)

Frontlight/Naturallight widgets: insert TitleBar, movable

---

frontend/ui/widget/checkbutton.lua
frontend/ui/widget/radiobuttontable.lua

CheckButton now can have CheckMark or RadioMark.
RadioButton widget is not used anymore and can be deleted.
(Minor visual change: previous radiobuttons were shorter than checkbuttons by 2 points. Now they are equal.
Hard to observe, only with flash_ui enabled).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8774)

CheckButton: insert RadioMark

---

frontend/apps/filemanager/filemanagershortcuts.lua
frontend/ui/widget/pathchooser.lua

For easy navigation, Folder shortcuts can be called via long-press on the Home (left) button in the PathChooser title bar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8787)

Pathchooser: add folder shortcuts

---

frontend/apps/filemanager/filemanagerutil.lua
frontend/apps/reader/modules/readertypeset.lua
frontend/apps/reader/modules/readerview.lua

(1) Fix default `block_rendering_mode` in readertypeset, see https://github.com/koreader/koreader/pull/8412#issuecomment-1029531114.
(2) Keep `bookmarks_sorted_20220106`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8792)

Doc settings reset: fixes

---

plugins/bookshortcuts.koplugin/main.lua

Fixes:
(1)
`02/09/22-16:06:51 WARN  FileManager instance mismatch! Tried to spin up a new instance, while we still have an existing one: table: 0x42d62bb8
`
(2)
`02/09/22-16:06:51 ERROR failed to call event handler onBookShortcut frontend/apps/reader/readerui.lua:545: bad argument #1 to 'attributes' (string expected, got nil)
`
(3) `Directory` to `Folder`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8795)

BookShortcuts plugin: fix folders handling

---

frontend/apps/cloudstorage/cloudstorage.lua
frontend/ui/widget/buttondialogtitle.lua
plugins/opds.koplugin/opdsbrowser.lua

(1) ButtonDialogTitle: new method `setTitle()`
(2) OPDSbrowser
-use `setTitle()` instead of open/close ButtonDialogTitle (no visual changes to the download dialog)
-reduce logger.info output to avoid flooding crash.log
(3) CloudStorage
-enhance download dialog (similar to OPDS), much optimized code of `downloadFile`
-fix a bug: cannot create new folder or upload files to the root of the Dropbox storage
OPDS
Cloud storage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8809)

Cloud storage: enhance download dialog, fix Dropbox uploading

---

frontend/device/pocketbook/device.lua

With the inkview library inverting the screen seems possible but needs some 
discussion with the developers of Pocketbook. For now disable HWInvert so 
this feature is not broken while we figure out how to change the invert with inkview.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8803)

Fix invert for pocketbooks by disabling hardware invert

---

frontend/apps/filemanager/filemanager.lua
plugins/gestures.koplugin/main.lua

(1) Long-press on the FM title Home button now can be assigned to any action
(2) For those who does not have Text editor and wants to look into some small file
https://www.mobileread.com/forums/showthread.php?t=345189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8821)

File manager: free long-press on Home button; open file with TextViewer

---

plugins/kosync.koplugin/KOSyncClient.lua

Currently the progress sent to the server can be either a string or an int (depending on whetther the document has pages).
The following are both payload sent from koreader to the server.
```
{"percentage":0.005,"device":"device_name","device_id":"B78EA04ACC3A453DBA220D720C0BE102","document":"348e34463a44ba68659fc6fe814a6778","progress":3}
```
where document `348e34463a44ba68659fc6fe814a6778` is a pdf file.
```
{"percentage":1,"device":"device_name","device_id":"B78EA04ACC3A453DBA220D720C0BE102","document":"4eb484b229696cb39cd8fe5495aa1bbe","progress":"\/body\/DocFragment[30]\/body\/p\/img.0"}
```
where document `4eb484b229696cb39cd8fe5495aa1bbe` is an epub file.
This may add extra work to the backend server. A few commits were added to my personal fork of …

kosync: send progress as a string to the server

---

frontend/apps/reader/modules/readerpagemap.lua
frontend/apps/reader/modules/readertoc.lua
frontend/ui/bidi.lua
frontend/ui/elements/page_turns.lua
frontend/ui/widget/bookmapwidget.lua
frontend/ui/widget/checkmark.lua
frontend/ui/widget/container/framecontainer.lua
frontend/ui/widget/container/leftcontainer.lua
frontend/ui/widget/container/rightcontainer.lua
frontend/ui/widget/container/scrollablecontainer.lua
frontend/ui/widget/horizontalgroup.lua
frontend/ui/widget/horizontalscrollbar.lua
frontend/ui/widget/menu.lua
frontend/ui/widget/overlapgroup.lua
frontend/ui/widget/pagebrowserwidget.lua
frontend/ui/widget/progresswidget.lua
frontend/ui/widget/verticalgroup.lua

This PR allows changing the TOC BookMap PageBrowser & ~~SkimTo~~ UI direction based on the tap direction of the book even if it is not the same as the general UI.
This can be useful when for example reading an english book with a RTL hebrew UI
see previous discussion in https://github.com/koreader/koreader/issues/5359#issuecomment-568810654 https://github.com/koreader/koreader/pull/8613#issuecomment-1006717032
`_mirroredUI inherit from widgetcontainer`
This allows `_mirroredUI` to be set on init not require.
The first 3 commits are ready the last one needs some work.
The Toc works great with this (It is also easy to gate with one entry/exit point) however bookmap does not work, some of the elements are off and i could not figure out why. @poire-z Do you have any clue why? Also is there a …

BD: allow inverting for Document UI elements (TOC)

---

frontend/ui/elements/font_ui_fallbacks.lua

Fixes #8810.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8849)

[fix, i18n] Add gettext() to info text about UI fallback fonts

---

frontend/apps/reader/modules/readertoc.lua

Fixes RTL issue noticed at https://github.com/koreader/koreader/pull/8876#issue-1161280868
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8879)

TOC: use bidi_wrap_func

---

setupkoenv.lua

TLDR 
allow ffi.load from rocks libs
I have plugins that us a C library via the FFI. to make it easily accessible i packaged it in a rock https://luarocks.org/modules/yparitcher/libzmanim but luajit FFI does not follow `package.cpath` rather it only looks in the native linker paths (LD_LIBRARY_PATH).
This PR allow the FFI to load libraries made available in a rock, it should not affect anything else
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8878)

setupkoenv: ffi.load: search rocks

---

frontend/apps/reader/modules/readertoc.lua
frontend/apps/reader/modules/readerview.lua
frontend/ui/bidi.lua
frontend/ui/widget/bookmapwidget.lua
frontend/ui/widget/pagebrowserwidget.lua

Follow up to #8673 / 42dd5aad. Handle settings only in `ReaderView:shouldInvertBiDiLayoutMirroring()`. See https://github.com/koreader/koreader/pull/8673#issuecomment-1046349246.
I haven't changed them, but currently, the settings are named:
```
["inverse_reading_order"] = true
["invert_ui_layout_mirroring"] = true
```
I find the 2nd one a bit too generic, while it depends on the first one.
Should we change the 2nd one to read `inverse_reading_order_also_ui_layout` ?
https://github.com/koreader/koreader/pull/8673/commits/4e45227250da427636db3498b0eabf7dfd9a28c4#r789583906
@yparitcher : in TOC, chapters titles are still rendered LTR:
while in Book map and Page browser, they look better:
--- …

Bidi: keep invert() generic, handle settings in ReaderView

---

plugins/calibre.koplugin/search.lua

Sometimes Calibre metadata file does not have series_index for whatever reasons. Tapping series name will not open a list of books which are part of the series. Upon inspection it turns out that code execution never goes past line 274, just hanging there when trying to do string.format. This code change allows those books to still be listed but without series index information while avoiding the hang,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8870)

Calibre plugin - Fixed hang when book has series but series index is nil

---

frontend/apps/filemanager/filemanagerfilesearcher.lua
frontend/apps/filemanager/filemanagershortcuts.lua
frontend/apps/reader/readerui.lua

(1) Correct show folders
(2) `Include subfolders` checkbutton (default true)
(3) Show file size in search results
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8807)

File searcher: fix show folders, include subfolders checkbutton

---

frontend/ui/widget/menu.lua

Avoid showing "Page 0 of 0" in non-classic dispaly modes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8838)

Menu widget: fix "No items"

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerview.lua
frontend/ui/elements/reader_menu_order.lua
frontend/ui/widget/focusmanager.lua
frontend/ui/widget/openwithdialog.lua
frontend/ui/widget/radiobuttonwidget.lua
frontend/ui/widget/sortwidget.lua

Relate to #4329, #6562
In my opinion, highlight is the last major gap left for non-touch devices after PR #8712 and #8859 merged.
Enable text selection in non-touch devices can unlock highlight module features. Dictionary lookup, one of highlight module feature, is very useful for me to read technical book offline.
The essential problem is: how to select a range text?
Similar to #4329:
1. Start text selection mode. An indicator to let user move to the start position.
2. Confirm start position.
3. Move indicator to the end position (optional, if only single word wanted)
4. Confirm end position.
For touch devices, step 1 and step 2 are activated by a `hold` event. Step 3 accusers as user moving figure activated by `pan_hold` events. Step 4 is activated by a `hold_release` event.
So the …

non-touch device highlight support

---

frontend/apps/reader/modules/readertoc.lua

Introduced by #8859.
Non touch support is implemented before commit d8087b37e3e7c5e21fc3f3320bd3d435b26c4b56, which adds `index` parameter to `callback` function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8892)

fix exception on expand TOC on non-touch device: table index is nil

---

frontend/apps/reader/modules/readerfooter.lua
frontend/device/android/device.lua
frontend/device/android/powerd.lua
frontend/device/cervantes/powerd.lua
frontend/device/generic/powerd.lua
frontend/device/kindle/device.lua
frontend/device/kindle/powerd.lua
frontend/device/kobo/powerd.lua
frontend/device/pocketbook/powerd.lua
frontend/device/sdl/powerd.lua
frontend/device/sysfs_light.lua
frontend/ui/widget/bookstatuswidget.lua
frontend/ui/widget/button.lua
frontend/ui/widget/buttonprogresswidget.lua
frontend/ui/widget/configdialog.lua
frontend/ui/widget/container/widgetcontainer.lua
frontend/ui/widget/dictquicklookup.lua
frontend/ui/widget/frontlightwidget.lua
frontend/ui/widget/inputtext.lua
frontend/ui/widget/naturallightwidget.lua
frontend/ui/widget/textboxwidget.lua
frontend/ui/widget/textwidget.lua
frontend/ui/widget/titlebar.lua
plugins/coverbrowser.koplugin/listmenu.lua
plugins/coverbrowser.koplugin/mosaicmenu.lua
reader.lua

Requires https://github.com/koreader/koreader-base/pull/1457
(Oh, hello there, "mystery" device ;p).
----
* Rejig frontlight warmth API to more closely match the existing API, and, hopefully, clarify some of its quirks, and reduce boilerplate and duplicate code in platform implementations.
* Tweak Kindle:setDateTime to prefer using the platform's custom script, as in interacts better with the stock UI. And make the fallbacks handle old busybox versions better.
* Add Kindle PW5 support ;).
* Add warmth support to the Kindle platform.
* Random TextBoxWidget cleanups: make sure we immediately free destroyed instances.
* FrontLightWidget: Refactor to make it slightly less obnoxious to grok and update; i.e., separate layout from update, and properly separate brightness from warmth handling. …

Initial Kindle PW5 support

---

frontend/device/kobo/powerd.lua

I am doing some prework on a batterycare.koplugin, which will allow to keep the charge of the internal battery as well as the charge of the power cover in sane regions (aka no over charge, no deep charge).
This PR minimizes the unsuccessful detection of the power cover, which is good for all Sages with a power cover.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8894)

Kobo, Sage: better power cover detection

---

plugins/calibre.koplugin/main.lua

`Manual` could mean several things, most notably some kind of documentation and something you do by hand.
The added context is partially to aid translators and partially to preclude potential collisions in the future.
Cf. <https://github.com/koreader/koreader-translations/pull/138>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8909)

[i18n] Add context for calibre configuration type

---

frontend/apps/reader/modules/readeruserhyph.lua

This should fix https://github.com/koreader/koreader/issues/8843
The problem was, that some user dictionary entries were not utf8-normalized.
With this PR, old dicts get normalized on load and if there is a problem with loading the dicts are get sorted again.
This sorting might help, if someone generates his dicts per hand too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8863)

UserHyph: Scrub and sort user dict

---

.gitignore
plugins/calibre.koplugin/search.lua

When browsing tags and series there was no way to go "back" from tag/series results. Figured we can enable return button navigation by pushing entry to paths property of Menu widget.
When return button is enabled it is overlapping with rounded border previously present on browse widget so I made it borderless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8869)

Calibre plugin - Series/Tag browser updated to show back button.

---

plugins/opds.koplugin/opdsbrowser.lua

This PR adds support for the unofficial page streaming extension for OPDS. See: https://anansi-project.github.io/docs/opds-pse/specs/v1.0. This is useful for streaming comics from a remote server.
Addresses #7500.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8919)

Add OPDS PSE 1.0 support

---

frontend/device/generic/device.lua
frontend/device/kindle/device.lua

Most NTX boards require elaborate trickery (see fbdepth) to actually
send a vput ioctl without the driver screwing with the rotation behind
your back.
This was causing spurious hardware rotations on exit on most Kobo
devices, something which might have gone mostly unnoticed, as current
Nickel versions will sanitize it on startup.
A simple repro was instead to start an USBMS session, as that exits
KOReader and restarts it without going through fbdepth again ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8931)

Only toggle nightmode via the grayscale fb info flag on Kindle

---

plugins/wallabag.koplugin/main.lua

Fixes #8930.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8933)

[fix, plugin] Wallabag: avoid crash when setDownloadDirectory doesn't have a touchmenu_instance

---

frontend/ui/widget/frontlightwidget.lua

Fix #8913
Unlike previous iterations of the widget (I think?), this leaves the full granularity accessible via the +/- buttons.
In case that's unwanted, the first commit honored the scaling for those ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8935)

FrontLightWidget: Unbreak warmth on full-granularity devices

---

frontend/device/remarkable/device.lua
frontend/device/remarkable/event_map.lua

When running KOReader with a launcher, having the power button trigger the Power event conflicts with the launcher's built-in screensaver (see https://github.com/koreader/koreader/issues/8891).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8900)

Don't use KOReader suspend/screensaver/autosuspend when launched from Oxide

---

frontend/ui/widget/buttonprogresswidget.lua

We don't need one in FrontLightWidget ;).
Fix https://github.com/koreader/koreader/issues/8913#issuecomment-1074915143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8940)

ButtonProgressWidget: Make hold_callback optional

---

frontend/device/generic/device.lua
frontend/device/kindle/device.lua
frontend/ui/screensaver.lua
frontend/ui/widget/screensaverwidget.lua

* Handle said rotation shenanigans inside ScreenSaver & ScreenSaverWidget, which allows a more targeted approach; and prevents said rotation from affecting other widgets. (Also, gets rid of duplicated code).
* Handle the corner-case or exiting early from a "keep on screen for n sec" screensaver better, by unscheduling the extra refresh, since an early tap took care of that already.
Fix #8762 
Fix #8842 
(And possibly other, similar older issues?).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8943)

ScreenSaver: Minor refactor to avoid code duplication and weird rotation shenanigans

---

frontend/apps/reader/modules/readerview.lua
frontend/ui/uimanager.lua

Also, the save_settings calculation has to be educated to honor the times in standby.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8961)

Readerview: Fix save_settings calculation with standby

---

frontend/device/generic/powerd.lua

This corrects the waiting time in `getCapacity` for the times in standby.
Without this - if standby is enabled - the capacity display in the menu and status bar would get updated way too slow.
On devices without standby this PR is mainly a noop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8958)

Kobo powerd: fix frequency in battery's getCapacity with enabled standby

---

frontend/apps/reader/modules/readerfooter.lua

If a device (Sage) has an aux battery and the sum of the internal end external capacity exceed the hide battery threshold, the capacity is not shown in the status bar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8959)

Status bar: fix battery display (threshold with aux battery)

---

frontend/device/kobo/device.lua
frontend/ui/uimanager.lua
plugins/autosuspend.koplugin/main.lua

This fixes the issue mentioned in https://www.mobileread.com/forums/showthread.php?t=345985, which you can easily reproduce by having autostandby disabled, long-pressing on a book to refresh its metadata, and opening it after the thumbnail has been refreshed.
It would cash a few seconds after, once the metadata processes get reaped.
This also cleans up a few minor things, and one not so minor thing: don't actually suspend if the timeout is unset ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8970)

AutoSuspend: Avoid unbalanced prevent/allow Suspend calls

---

frontend/device/generic/powerd.lua
frontend/ui/uimanager.lua

Without this PR the battery capacity is updated at worst one minute after resume. Which might be annoying, if you have charged the device during suspend.
BTW, now getElapsedTimeSinceBoot does more what it's name promises ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8983)

getElapsedTimeSinceBoot: Honor times in suspend, too

---

frontend/apps/reader/modules/readerrolling.lua
frontend/ui/uimanager.lua
frontend/ui/widget/doublespinwidget.lua
frontend/ui/widget/spinwidget.lua

Instead of UIManager possibly staled _now, which could have no effect after a long ReaderRolling re-rendering.
Also lower the delay after such ReaderRolling re-renderings, so we can change settings quicker when comparing renderings.
See https://github.com/koreader/koreader/pull/8501#issuecomment-1086628431 and followups.
Since eda8379e8c #8495, on Apply, the widget is fully rebuild, and was repositionned at its initial position (centered) and fully opaque.
See https://github.com/koreader/koreader/pull/8490#issuecomment-1094276472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8993)

SpinWidgets and discardEvents() fixes

---

frontend/device/kobo/device.lua
plugins/autosuspend.koplugin/main.lua

Specifically, don't forcibly unschedule/schedule on every input event, instead, let the scheduled task figure out if the deadline came to pass or not ;).
c.f., https://github.com/koreader/koreader/pull/8970#issuecomment-1092775830
Besides getting rid of some overhead, this allows proper scheduling after a task that would have blocked for longer than the standby timeout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8985)

AutoSuspend: Handle standby scheduling in the same manner as suspend/shutdown

---

frontend/device/generic/device.lua
frontend/device/input.lua
frontend/device/kobo/device.lua
frontend/ui/uimanager.lua

Might help avoiding evdev queue overflow on misbehaving covers (#8964).
At the very least shaves a fair bit of stupid from debug logs ;o).
Requires https://github.com/koreader/koreader-base/pull/1478
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8987)

Kobo: Disable key repeat during suspend

---

frontend/ui/widget/imageviewer.lua

Makes ImageViewer more ergonomic on devices with hardware keys.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8927)

Use hw keys for page turning when ImageViewer.image is a table

---

plugins/wallabag.koplugin/main.lua

Fixes <https://github.com/koreader/koreader/issues/8949>. Not tested yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8950)

[plugin] Wallabag: abort synchronisation on request error

---

frontend/apps/reader/modules/readerfooter.lua

Not quite sure if I did this right @NiLuJe (esp. `setDirty` is not familiar to me)
Without this PR I get in the log on each footer update (every minute):
```
04/14/22-14:50:01 DEBUG refresh on physical rectangle 0 0 540 31
04/14/22-14:50:01 DEBUG Explicit widgetRepaint: table: 0x7f02dcf46fd8 @ ( 0 , 0 )
04/14/22-14:50:01 DEBUG setDirty via a func from widget table: 0x7f02dcf46fd8
frontend/ui/uimanager.lua:880: in function 'post_guard'
frontend/dbg.lua:68: in function 'setDirty'
frontend/apps/reader/modules/readerfooter.lua:2217: in function 'updateFooterText'
frontend/apps/reader/modules/readerfooter.lua:2114: in function 'updateFooterPage'
frontend/apps/reader/modules/readerfooter.lua:2098: in function 'onUpdateFooter'
frontend/apps/reader/modules/readerfooter.lua:782: in function …
```

readerfooter: make setDirty happy, reduce log

---

frontend/ui/elements/menu_keyboard_layout.lua

In the device menu -> Keyboard -> Keyboard layout show "Keyboard layouts: %1" if no keyboard is selected.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9008)

Fix menu entry, when no keyboard is activated

---

plugins/wallabag.koplugin/main.lua

This change adds an "Automatic tags" setting in the Wallabag plugin. Any articles saved with the plugin will be tagged with this comma-separated list.
For example, this can be set to "koreader,inbox" to tag saved articles with "koreader", indicating their origin, and "inbox", indicating that I may want to evaluate the article before saving it to my device for reading.
This can be combined with the "Ignore tags" setting (e.g. ignoring the "inbox" tag) if the user wants to evaluate articles on their PC first before downloading them to their reader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9017)

Wallabag: Add setting for automatically tagging new articles

---

frontend/device/kobo/device.lua
frontend/ui/uimanager.lua
plugins/autosuspend.koplugin/main.lua

c.f., https://github.com/koreader/koreader/pull/9001#issuecomment-1100726585
RFC to @zwim ;).
----
* Make sure AutoStandby cohabitates nicely with AutoSuspend (regression since #8985), specifically:
* Disable standby during suspend.
* Ensure that leaving standby restores the scheduled suspend properly, with the appropriate remaining amount of time based on the last user input.
* Handle devices with an auxiliary battery better when scheduling suspend (assume it's only charging when the aux battery is charging, not the ereader's).
* Tweak debug logging to be able to remote debug corner-cases more easily without requiring code changes.
* Fix erroneous behavior when awoken from standby by something that doesn't trigger an InputEvent Event (e.g., rtc alarm, gyro, or random bullshit).
---
This …

AutoSuspend: Alternate take on the suspend delay extension regression

---

plugins/exporter.koplugin/clip.lua

This is a lightweight solution (in terms of coding) for the exporter's highlight ordering problem reported in #8982
It just uses bookmarks to sort highlights.
Since #8996 might go unmerged, I propose this as an intermediate solution. 😄
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9021)

Exporter highlight sort

---

doc/Building.md

The build deps listed in the README are not sufficient to build
KOReader. Inserting the full list of dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9034)

Build deps for Fedora

---

frontend/ui/network/networklistener.lua

Rationale from: https://github.com/koreader/koreader/pull/9064#issuecomment-1116485065
>While we are dealing with WiFi, a slight hijack, on my kindle when the WiFi is on but not connected the ToggleWiFi gesture tries to connect so i have no way of turning it off. For eample I use the gesture to turn it on, then leave the range I can't use it to turn off. I think the more direct approach would be to toggle On -> Off states so if i am disconnected and want to reconnect i can always go Off then On, but I am able to turn it off.
>TLDR: the tooglewifi gesture should check for iswififup not isconnected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9067)

Network: ToggleWiFi: check `isWifiOn` instead of `isConnected`

---

frontend/apps/reader/modules/readerrolling.lua
frontend/apps/reader/modules/readerview.lua
frontend/device/generic/device.lua
frontend/device/kindle/device.lua
frontend/ui/elements/page_turns.lua

enable page turn animations on supported platforms (PW5/MTK)
This creates a swipe animation when turning pages in the reader.
(for some reason, I happened to read a few pages in the stock reader and decided i like the effect ;)
Requires: https://github.com/koreader/koreader-base/pull/1477
To Do:
- PDF
- ~~Landscape (we dont rotate the FB so this must be adjusted)~~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8974)

PW5: Page turn animations

---

frontend/apps/filemanager/filemanager.lua
frontend/ui/widget/filechooser.lua
frontend/ui/widget/focusmanager.lua
frontend/ui/widget/inputtext.lua
frontend/ui/widget/menu.lua
frontend/ui/widget/titlebar.lua
plugins/coverbrowser.koplugin/covermenu.lua
plugins/coverbrowser.koplugin/mosaicmenu.lua

Fix #9027 
There are 22 `TitleBar:new` in source code. Only few of them have buttons other than just right `close` button (`PageBrowserWidget` has TitleBar with buttons while it is disabled for non-touch device.):
* File Manager
* History
* Folder Shortcuts
* Favorites
* Cloud Storage
All these pages are based on `Menu` widget. `Menu` widget replaces `FocusManager` move focus right key listener as menu item `Hold` event listener. It also turn off move focus left key listener on `hasFewKey()` device. It is hard to support horizontal focus movement between `TitleBar` buttons in `Menu` widget.
After several failure solutions, making `TitleBar` buttons layout in vertical is a simple and safe solution so far.
**frontend/ui/widget/titlebar.lua**
Show left and right on non-touch devices
Methods …

TitleBar left and right buttons navigation on non-touch devices

---

frontend/device/kobo/powerd.lua
frontend/dispatcher.lua
frontend/ui/network/manager.lua
frontend/ui/network/networklistener.lua

There's possibly a weird behavioral quirk on Kobo depending on whether there are system-level saved networks or not, c.f., #8667,
so this ensures that the worst-case scenario gets a hint that something is indeed actually happening ;).
Heavily based on @zwim's implementation in #8667, just took a more defensive approach to refresh races to avoid glitches on mxcfb ;).
(First commit is a random comment cleanup I missed in #9036 ;)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9064)

NetworkManager: Make sure we show an IM at the *start* of a Wi-Fi toggle action

---

frontend/apps/reader/modules/readerpagemap.lua
frontend/document/credocument.lua

Includes:
- https://github.com/koreader/crengine/pull/477
- lvtext: tweak object flags implementation
- lvtext: rename LTEXT_WORD_IS_OBJECT to LTEXT_WORD_IS_IMAGE
- lvtext: add LTEXT_OBJECT_IS_EMBEDDED_BLOCK
- Text: support for inline margin/border/padding.
Closes #8156.
- https://github.com/koreader/crengine/pull/478
- PageMap: allow building synthetic pages numbers
cre: add synthetic page map functions. These are not yet used, it will need some thinking to address #9020 (if we really want to) - but the functions are there so we can experiment.
Also:
`ReaderPageMap: fix page labels in 2-columns mode`
Page labels on the right page could have some bad y position (they were never above the last page label on the left page).
--- …

bump crengine: support for inline margin/border/padding

---

doc/config.ld

The file was moved in <https://github.com/koreader/koreader/pull/8944> but not changed in the docs config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9075)

Fix docs after Exporter plugin refactor

---

frontend/ui/otamanager.lua

After tapping "Check for update" some time nothing seems to happen. No big deal, but a little bit annoying.
This PR adds an IM with just an hourglass, so that the user knows, something is started.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9083)

OTAManager: Check for update -> immediately show hourglass

---

frontend/apps/reader/modules/readerfooter.lua
frontend/ui/widget/frontlightwidget.lua

c.f, https://www.mobileread.com/forums/showpost.php?p=4220159&postcount=7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9084)

ReaderFooter: Refresh the footer on frontlight state changes issued by the frontlight widget

---

frontend/apps/reader/modules/readerdevicestatus.lua

Shift the first scheduling of the checkers to a full minute (rounded down to the previous minute), the consecutive schedule are multiples of minutes. This is to reduce wakeups from standby.
Fix the missing unschedule of the checkers, when the checker intervals are changed from the menu (to avoid multiple scheduled checkers).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9032)

Power-savings in readerdevicestatus: Schedule on full minute and fix multiple scheduling.

---

frontend/device/input.lua

Regression since #9036
Fix #9095
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9098)

PocketBook: Don't break synthetic power input events on suspend

---

frontend/apps/filemanager/filemanagershortcuts.lua

Closes https://github.com/koreader/koreader/issues/9105.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9107)

FilemanagerShortcuts: fix crash on adding the first shortcut

---

frontend/device/remarkable/device.lua

The change from `timeval` to `time` completely broke reMarkable.
`frontend/device/remarkable/device.lua` was using `TimeVal:now()` to manually overwrite event `time` values, as noted in the code comments.
`Input:handleTouchEv` is expecting those event `time` values to be timevals, not integer times.
So as soon as the user touches the screen,
```
./luajit: frontend/ui/time.lua:130: attempt to index local 'tv' (a number value)
frontend/ui/time.lua:130: in function 'timeval'
frontend/device/input.lua:714: in function 'handleTouchEv'
frontend/device/input.lua:1240: in function 'waitEvent'
frontend/ui/uimanager.lua:1698: in function 'handleInput'
frontend/ui/uimanager.lua:1754: in function 'run'
./reader.lua:324: in main chunk
[C]: at 0x000140f1
!!!!
Uh oh, something went …
```

Fix reMarkable crash bug v2022.05: event overwrite with new time module

---

plugins/statistics.koplugin/readerprogress.lua

As `readerstatistics` uses some short strings like `Total` and forms some compound information with this, translations will get difficult (at least for German). -> I have learned this week: `Never be clever. ;-)` -> So this PR will be more than clever, it will be smart ;))
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9113)

[plugin, statistics] simplify ReaderProgress for better translations

---

frontend/apps/reader/modules/readerdictionary.lua
frontend/device/wakeupmgr.lua
frontend/ui/uimanager.lua
frontend/ui/widget/confirmbox.lua
frontend/ui/widget/infomessage.lua
plugins/autosuspend.koplugin/main.lua

Long story short: the LeaveStandby event is sent via `tickAfterNext`, so if we tear down the plugin right after calling it (in this case, that means that the very input event that wakes the device up from suspend is one that kills ReaderUI or FileManager), what's in UIManager's task queue isn't the actual function, but the anonymous nextTick wrapper constructed by `tickAfterNext` (c.f., 
https://github.com/koreader/koreader/issues/9112#issuecomment-1133999385).
Tweak `UIManager:tickAfterNext` to return a reference to said wrapper, so that we can store it and unschedule that one, too, in `AutoSuspend:onCloseWidget`.
Fix #9112 (many thanks to [@boredhominid](https://github.com/boredhominid) for his help in finding a repro for this ;)).
Re: #8638, as the extra debugging facilities (i.e., …

AutoSuspend: Don't send LeaveStandby events from a zombie plugin instance

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/ui/widget/datetimewidget.lua

Follow up to #9070.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9145)

DateTimeWidget: don't make ":" and "/" translatable

---

plugins/vocabbuilder.koplugin/db.lua

Fix the bug that when reviewing backwards, changes made earlier could be reset by loading more from database.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9161)

vocabulary builder bug fix: resetting changes when reviewing backwards

---

plugins/exporter.koplugin/base.lua
plugins/exporter.koplugin/main.lua
plugins/exporter.koplugin/target/html.lua
plugins/exporter.koplugin/target/json.lua
plugins/exporter.koplugin/target/markdown.lua
plugins/exporter.koplugin/target/text.lua

This PR enables users to share exported highlights on Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9153)

Highlights share

---

frontend/ui/data/creoptions.lua
frontend/ui/data/optionsutil.lua
frontend/ui/widget/configdialog.lua

A follow up to #9046 to add some units to the bottom menu.
Don't worry, after this PR regarding units there will only be one follow up with the font size. (But it's a little bigger. It will allow to switch the text scaling from `pt` (aka dpt) to `KOScale™`)
For that  future PR, I have to fiddle out what the `name_text_true_values` option does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9126)

SpinWidget, DoubleSpinWidget: add units to bottom menu

---

plugins/exporter.koplugin/main.lua

This PR implements verbose info messages for highlight exports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9166)

Info messages with status

---

plugins/vocabbuilder.koplugin/db.lua
plugins/vocabbuilder.koplugin/main.lua

This PR fixes the bug #9162 caused by unsafe db operation and adds an edit mode for quick deletion of words requested at https://github.com/koreader/koreader/pull/9132#issuecomment-1144757498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9168)

vocabulary builder bugfix and quick word deletion

---

frontend/apps/reader/modules/readerfont.lua
frontend/apps/reader/modules/readertypography.lua
frontend/document/credocument.lua
frontend/ui/data/creoptions.lua
frontend/ui/data/css_tweaks.lua
frontend/ui/widget/configdialog.lua

Includes https://github.com/koreader/crengine/pull/482 :
- initTableRendMethods(): fix possible crash
- ldomXPointer::getRect(): skip inline pads
- Ruby: keep any last text wrapped in internal table elements
- Font: fix HarfBuzz localized glyphs with CJK punctuation
- lvtext: store kerning mode as a Formatter property
- CJK: improved typography by tweaking punctuations
Closes #6078.
- CJK: allow scaling CJK glyphs' widths
- CSS/lvrend: adds "-cr-hint: cjk-tailored"
- CJK: expand last line as previous justified line
Closes #8929.
- CJK: add 1/4 em of spacing between CJK and western words
Closes #6162 (and hopefully my journey into CJK :).
Add this style tweak:
(A bit sad to get 6 items in this style tweak menu - I usually try to target at max 5 items - but couldn't think of any other …

bump crengine: improved typography for Chinese and Japanese

---

frontend/apps/reader/modules/readercoptlistener.lua
frontend/apps/reader/modules/readerfooter.lua
frontend/ui/uimanager.lua
plugins/autosuspend.koplugin/main.lua

Even in corner cases where we're woken up *without* user input (e.g., rtc alarm).
Fix #9157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9173)

AutoSuspend: Make sure we send a LeaveStandby event ASAP

---

plugins/terminal.koplugin/main.lua

This fixes https://github.com/koreader/koreader/issues/9108#issuecomment-1132243061
Tapping on clear screen during a running program like top, let's KOReader crash.
Some programs use ansi-sequences to implement a TUI. When messing with the input buffer, there would need to adjust at least some saved char positions (and maybe more). So I decided to implement the `clear screen` just as a shurtcut to send the shell command `clear`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9119)

[Terminal] fix crash on clear screen

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerview.lua
frontend/document/credocument.lua
frontend/ui/data/creoptions.lua
frontend/ui/data/optionsutil.lua

Includes https://github.com/koreader/crengine/pull/484 : 
- lvtext: fix `m_kerning_mode` type
- XML: let '`gb2312`' (Chinese) encoding be known
- Add `ldomXPointer::getChar()`
- `LVDocView::getNodeByPoint()`: tweak for text selection
- Fonts: allow fetching the list of embedded fonts
cre.cpp https://github.com/koreader/koreader-base/pull/1490 : 
- `getTextFromPositions()`: use `getNodeByPoint(forTextSelection=true)` to allow panning in margins and get the nearest text instead of nothing.
Closes #9169.
- add `extendXPointersToSentenceSegment()` to allow extending some xpointer range to include punctuations at start or end (with for now a quite rudimentary implementation).
- add `getEmbeddedFontList()` to allow fetching the list of embedded fonts in the current EPUB book.
Also includes …

bump crengine: text selection and embedded fonts tweaks

---

frontend/apps/reader/modules/readerfooter.lua

Enabled Fi-Wi-Status in the footer.
Turn Wi-Fi on in the menu, the footer gets updated (shows the Icon).
Turn Wi-Fi off in the menu, the footer doesn't get updated. You see the correct unchecked menu entry and the old obsolete Wi-Fi icon in the footer. This inconsistency has confused me quite some time.
With this PR, the footer shows the current status, when toggling Wi-Fi from the menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9185)

Footer: update on network disconnect

---

plugins/autofrontlight.koplugin/main.lua

On a Kindle Oasis 2 and 3 the plugin would be disabled due to not
checking for "KindleOasis2" and "KindleOasis3" respectively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9202)

Auto frontlight plugin: Newer Oasis models are also supported

---

frontend/apps/reader/modules/readerdictionary.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua
plugins/vocabbuilder.koplugin/_meta.lua
plugins/vocabbuilder.koplugin/db.lua
plugins/vocabbuilder.koplugin/main.lua
resources/icons/empty.svg

This PR adds a copy button and word context(off by default) to the three-dot menu of word entries. cf #9180 
Also some db refactoring and minor UI improvements: 
- a dedicated book title table in order to shrink db size by storing references to title names instead of repeated actual strings,
- alignment of different forms of the "more" button and possible clipped words in translations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9195)

vocabbuilder.koplugin: adding copy button and word context

---

frontend/ui/renderimage.lua
frontend/ui/screensaver.lua
frontend/ui/widget/imagewidget.lua
plugins/opds.koplugin/opdsbrowser.lua
spec/unit/imagewidget_spec.lua

* RenderImage: Always pcall C/FFI stuff, and always return nil on error
* OPDSBrowser: Handle renderImageData failure in streamPages
* ImageWidget: Always return a bb, even on decoding failures (in which case, a checkerboard pattern is returned).
* ScreenSaver: Make sure the choose image/folder/document settings report what the code *actually* does (especially on empty settings).
This is all a bunch of cleanup spurred by #5469 ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9206)

Unify RenderImage API & usage

---

.circleci/config.yml

Overlooked in <https://github.com/koreader/koreader/pull/9007>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9209)

[CI] Also use Ubuntu 20.04 Docker image for docs

---

plugins/exporter.koplugin/base.lua
plugins/exporter.koplugin/clip.lua
plugins/exporter.koplugin/target/json.lua

Fixes #6974
Fixes #8674
Along with them, I've noticed that if we get the title from meta, it can be in any language and some devices might not be able to create a file with all the Unicode letters. Therefore, I've added exportable_title parsed from filename and used that in export file generation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9220)

Better meta parsing for exporter

---

plugins/autodim.koplugin/main.lua

This is a maintenance PR.
With scheduling the next autodim_check on every tap, we can keep the device longer in standby mode. So we have more power savings.
The long story: The current version works like that:
Let's say I set the idle-time to 3 min and I need 2.5 min to read a page.
Start at 0 min (next scheduled check is at/in 3 min)
Read and tap to turn page after 2.5 min (next scheduled check is at 3 min - in 0.5 min)
At 3 min there is a scheduled_check (wakeup) -> reschedule check in 3 min.
Read and tap to turn page after 2.5 min (no wakeup)
Then after 1 min there is a wakeup -> reschedule.
---> So I get an additional wakeup on every second page.
This PR solves the problem: During normal reading I don't get _any_ wakeup during reading. (The only drawback is, that one function is …

AutoDim: reschedule on every tap

---

frontend/apps/reader/modules/readerlink.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/ui/widget/footnotewidget.lua

Noticed when jump to a footnote and quickly going back.
Also move footnote popup settings into a submenu.
See https://github.com/koreader/koreader/issues/9229#issuecomment-1160476900. Closes #9229.
Rewording suggestions welcome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9248)

Footnote popup: allow using book font as popup font

---

frontend/device/pocketbook/device.lua

This will keep the PocketBook wifi alive by telling to the PocketBook to keep it alive. This is the first time I used the scheduleIn function so feel free to nitpick.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9208)

Pocketbook: Keep wifi alive as long as wifi is enabled

---

plugins/autosuspend.koplugin/main.lua

I had the feeling that `autostandby` has Alzheimer. Sometimes my Sage forgot to standby. 
@NiLuJe : It's not the metal table, it's the time of the day. When reading at night I have more time and sometimes `autodim` or `autowarmth` knock in. If they knock in within the `wake_in >=3` is false, autostandby looses its scheduling. (Autodim is a real stress-test.)
On normal reading (with no autodim starting, during the day when warmth does not change) you can sometimes provoke the failure if you tap right before an automatic footer update (around second 57, 58).
This PR should fix the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9258)

AutoStandby: fix (re)scheduling

---

frontend/device/generic/powerd.lua
plugins/autowarmth.koplugin/main.lua

This should fix #9274.
I made for a dedicated PR for this, for testing (as I don't have a KA1).
The additional overhead of setting warmth twice in scheduling warmth changes will disappear in #9252 (where the whole scheduling gets optimized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9289)

AutoWarmth: force setWarmth after resume

---

.github/workflows/build.yml

Bump to Monterey, since current action produces a broken `crengine.dylib` anyway.
Keep the minimum target in Big Sur.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9279)

[CI] Downgrade macOS Github Action to macOS 10.15

---

frontend/device/input.lua
frontend/device/kindle/device.lua
frontend/device/kindle/mockrtc.lua
frontend/device/kindle/powerd.lua
frontend/device/wakeupmgr.lua
frontend/ui/uimanager.lua

To do
---
Tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9269)

Kindle input: wakeupFromSuspend & readyToSuspend

---

frontend/device/generic/device.lua
frontend/ui/data/creoptions.lua
frontend/ui/data/optionsutil.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua

Pictures say more than words:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9205)

BottomMenu: show real sizes for margins and font size

---

frontend/ui/widget/numberpickerwidget.lua

If the input of a numberpickerwidget starts with `=` evaluate that expression. Might be useful if you want to enter for example `=12+10` or `=12*1.2` (not so usefull, but for free `=math.sqrt(144)`).
If the input of a numberpickerwidget starts with `:` avoid the min-max checks: Useful for testing (or exagerate some value like the max autoturn time see #9051). This is only enabled if `verbose debug` is on. 
To be combined in `:=1+2`, math plus suppressed checks.
A possible use case (independend of testing purposes) could be to allow autoturn in 7 days (=60 x 24 x 7)
Here I exagerate the max value and calculate the value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/918 …

NumberPickerWidget: add method to avoid min-max checks and input math expressions.

---

frontend/apps/reader/modules/readerstyletweak.lua
frontend/ui/widget/touchmenu.lua

This is mostly needed because opening the menu with swipe is actually done by handling a pan south event, and so the final swipe event is another event, that is then handled by TouchMenu, which would straight away close itself.
Closes #9304.
Minor logic fix: allow global_conflicts_with to be not only a function, but also a string or a table, as documented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9308)

TouchMenu: don't allow swipe south to close menu

---

frontend/device/kindle/device.lua

~~`ui/time: fix for ldoc`~~
~~for some reason it does not bouild if there is a @module line~~
`kindle: track suspend time`
This is useful for the sysstat plugin not to have 00:00 for suspend time :)
Something similar should probably be done for the other `canSuspend` platforms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9307)

kindle: track suspend time

---

frontend/dispatcher.lua
frontend/ui/elements/screensaver_menu.lua
frontend/ui/screensaver.lua
frontend/ui/widget/infomessage.lua
frontend/ui/widget/screensaverwidget.lua

Rather some kind of "child lock" than real secure protection, which we can't ensure anyway.
See https://github.com/koreader/koreader/issues/5970#issuecomment-1172926681 and follow ups.
Related feature requests: #5970 #9270 #2255.
Tested on the emulator and my Kobo.
Somehow, by luck because I didn't need to look at all that, this works/happens
- on resume, frontlight becomes on when the "Waiting for gesture..." message is shown
- if we hit again the power button, the device goes naturally into suspend (even if I eat all events, this ones goes thru as it might be handled at a lower level :)
- if gesture forgotten, I can press 2 seconds and release on the power button and the KOReader powers off the device. We can just power on and get back to KOReader.
- not tested if autosuspend works if …

Screensaver: add option to require a gesture after resume

---

frontend/device/kobo/device.lua

Hadn't noticed that the new Libra 2 has it on a different bus than the
Sage/Elipsa.
(Harmless because we kept the Sage & Elipsa hardcoded).
c.f., https://www.mobileread.com/forums/showpost.php?p=4238067&postcount=869,
thanks to @baskerville for the poke ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9322)

Kobo: Autodetect the Elan input device on both i2c buses

---

frontend/device/pocketbook/device.lua

In some versions of the /ebrmain/config/extensions.cfg file there is a
comment #ebrcfg. This will not match the regex and crashes koreader as
the table is empty.
Add a check to ensure the table is not empty while reading extensions
from the default file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9327)

fix: Crash loading extensions from pocketbook

---

frontend/device/input.lua

It's used to communicate state changes from Android to Lua, we really really don't want to lose these ;).
Fix #9326
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9335)

Android: Leave the EV_MSC input handler alone.

---

frontend/apps/reader/modules/readerfont.lua
frontend/document/credocument.lua

Includes https://github.com/koreader/crengine/pull/486 : 
- Text: fix possible overflow with "`white-space: pre`"
- Fonts: `getFontFileNameAndFaceIndex()`: return family type
- Fonts: account for `_bias` in Font hash
- epub.css, fb2.css: remove hardcoded monospace font names
- Fonts: allow scaling monospace fonts
- Fonts: allow adjusting fallback font sizes to x-height
- HTML parser: trust xml encoding before html charset
Closes #9331. Closes #8306.
In our list of fonts, show a "M" indicator alongside monospace fonts, and allow long-press to select the one to be use for "font-family: monospace".
Add 2 options to Font settings, to scale monospace fonts by a percentage, and to adjust fallback fonts to their x-height.
The explanation for the monospace scaling is available via long-press:
I …

bump crengine: monospace and fallback fonts tweaks

---

frontend/ui/widget/inputtext.lua

When `input_type ==  "number"` convert the hint to "string" type.
Closes https://github.com/koreader/koreader/issues/9359.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9362)

InputText: fix 'number' hint

---

frontend/apps/cloudstorage/cloudstorage.lua
frontend/ui/screensaver.lua
frontend/ui/widget/pathchooser.lua
plugins/bookshortcuts.koplugin/main.lua
plugins/texteditor.koplugin/main.lua

Long-press the left TitleBar Home button:
Got standard New folder dialog:
Closes https://github.com/koreader/koreader/issues/9330.
Minor optimization of the PathChooser call parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9354)

PathChooser: add creating folder

---

plugins/autodim.koplugin/main.lua
plugins/autowarmth.koplugin/main.lua

I was experimenting with a solution to dim the frontlight smoothly on sun set/rise. 
Too long to explain: This does not work, as I don't want to find out how the intensity of devices maps to brightness felt by us humans. (maybe or next year, or the year after or in 2525).
So, this solution stupidly turns the frontlight _on_ (toggle)  between sunset and sunrise, and turns the frontlight _off_ (toggle) during daytime, **once** (per day). The user can override the selection of the plugin, but on the next day/night change AutoWarmth toggles again (if necessary).
This should also work with autosuspend (which I really, really love from the users view, but from the developers point :/)
Draft by now, as some more test will follow, so no need to review _as long this PR is in draft state_.
But as …

AutoWarmth: add option to toggle/set frontlight on day/night

---

plugins/autowarmth.koplugin/main.lua

See https://github.com/koreader/koreader/pull/9337#issuecomment-1198008045
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9382)

AutoWarmth: fix stupid typo

---

frontend/ui/data/optionsutil.lua

This should fix https://github.com/koreader/koreader/pull/9205#issuecomment-1200130686
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9392)

Bottom Menu: contrast has no units

---

frontend/ui/widget/bookmapwidget.lua
plugins/statistics.koplugin/main.lua

This helps jumping to page when ToC chapters are short and the bookmap page rows narrow.
Previously, we needed to tap exactly on the page slots (black in there) to see these pages in PageBrowser, which might be frustrating.
Now, we can tap in the yellow regions, and it would show the expected page.
(Not sure why I made tap so restrictive... I hope there wasn't a reason I can't find out now.)
Also fix crash when invoking BookMap and PageBrowser on a PicDocument (considered DocLess by Statistics).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9400)

BookMap: allow tap on ToC titles and outside page slots

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerview.lua

Mark notes with an additional indicator to distinguish them from highlights.
Indicators:
-underline, in black color (highlight underscore is grey)
-side vertical line (of 3 px width)
-side mark - a pencil sign
Side line/mark are located:
-for cre documents - floating position in a fixed distance from the edge of the text
-for pdf documents - fixed position in a fixed distance from the edge of the screen
For RTL (mirrored) layout side line/mark are located in the left margin.
Closes https://github.com/koreader/koreader/issues/9356.
Two-page mode
Mirrored layout
pdf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9395)

Highlight: add note marker

---

tools/update-metadata.lua

As discussed in https://github.com/koreader/koreader/issues/8225
The time to review the metadata itself is now, before it gets translated.
Then it is a matter of executing this script once to sync the english translation with in-file metadata.
Then wait a couple of months, execute again and be amazed by translation statistics :smile:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9090)

add tool to update fastlane metadata based on weblate translations

---

frontend/document/picdocument.lua
frontend/ui/renderimage.lua
frontend/ui/wikipedia.lua

Bump base, includes:
- thirdparty/luasec 1.2.0 https://github.com/koreader/koreader-base/pull/1509
- Bump NanoSVG: various small fixes
- Add thirdparty/libwebp and ffi/webp.lua wrapper https://github.com/koreader/koreader-base/pull/1511
- MuPDF: add support for webp images
- bump crengine: add support for webp images
- thirdparty/harfbuzz 5.1.0 https://github.com/koreader/koreader-base/pull/1510
RenderImage:renderImageData(): render webp images with ffi/webp.lua.
Closes #3016. Closes #9240.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9402)

CRe, MuPDF, PicDocument: add support for WebP images

---

frontend/document/canvascontext.lua

It is used by CoverBrowser, in a subprocess, when extracting metadata from PicDocuments, and crash on Android as calling android methods is only allowed from the main thread.
See https://github.com/koreader/koreader/pull/9402#issuecomment-1205049364
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9417)

CanvasContext.hasEinkScreen(): avoid crash on Android

---

frontend/device/kindle/device.lua
platform/kindle/extensions/koreader/menu.json
platform/kindle/koreader.sh

this reclaims a bunch of memory useful on low memory devices
based on https://github.com/mireq/KOReader-without-framework-support-for-Amazon-Kindle
https://github.com/koreader/koreader/issues/2663#issuecomment-1126975284
https://github.com/koreader/koreader/issues/796#issuecomment-634423039
The memory usage om my PW5 drops by ~ 100MB
Currently testing on my PW5, will see what happens in the next week or so.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9419)

kindle: allow stopping the framework on 5.X

---

frontend/device/generic/device.lua
frontend/device/gesturedetector.lua
frontend/device/input.lua
frontend/device/kindle/device.lua
frontend/device/kobo/device.lua
frontend/ui/screensaver.lua
spec/unit/focusmanager_spec.lua
spec/unit/input_spec.lua

* Avoid a double-free by clearing the right timerfd callback (fix #9376).
* Avoid getting semi-stuck in random hold states when triggering multi-slot holds.
* Random completely unrelated fix for #9285
* Various fixes for slightly erroneous MT handling on some drivers.
* And more generic MT handling fixes to ensure every slot gets processed, which prevents "missing" gestures, most notably contact lifts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9377)

Input: Fix a bunch of multi-slot corner cases

---

frontend/ui/data/dictionaries.lua

This adds inflections to the Czech-English dictionary. I have tested the dictionary, but not the download within KOReader, as mentioned in https://github.com/koreader/koreader/issues/9037 (because I haven't set up the dev environment yet). So it would be nice if someone could test it with this ebook, for example: [mistr_a_marketka.zip](https://github.com/koreader/koreader/files/9181609/mistr_a_marketka.zip)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9370)

Update Czech-English Dictonary with inflections

---

plugins/autowarmth.koplugin/main.lua
plugins/autowarmth.koplugin/suntime.lua

Fixes a quirk introduced with  #9252, which schedules not the actual warmth, but the next but one warmth when leaving suspend or standby.
Imperceptible to the user:
* Reduce calculations (save minimal power, esp. when wake from standby).
* Fixes stupid reschedules of `scheduleNextWarmthChanges` which may lead to 30.000(!) schedulings  if the reschedule time is below 1 second (as `os.date` only gives a second resolution). This might sometimes happen but very  seldom, but can be provoked wit a fixed schedule. This is not really noticeable to the user, no hang or something, but anyway it will get fixed with this PR....
_(For documentation: Set all times to 16:17:00; Solar noon to 16:17:10;  Sunset to 16:18:00; Civil dusk to 16:19:00; Nautical dusk to 16:20; Astronomical dusk to 18:18; Set …

[AutoWarmth] optimisations and fixes to progressive warmth setting

---

frontend/device/cervantes/device.lua
frontend/device/input.lua
frontend/device/kobo/device.lua
frontend/device/remarkable/device.lua

I'm not *entirely* sure why it broke, but it was a pretty crap workaround anyway, and @pazos already had a perfectly sane setup in place for Cervantes, so let's just repurpose that ;).
Fix #9464
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9465)

Input: Unbreak evdev handling on Kobo single-touch devices

---

plugins/newsdownloader.koplugin/main.lua

Fixes #9467
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9468)

NewsDownloader: Strip byte order mark from xml string before parsing

---

frontend/device/cervantes/device.lua
frontend/device/gesturedetector.lua
frontend/device/input.lua
frontend/device/kobo/device.lua
frontend/device/sdl/device.lua
spec/unit/device_spec.lua

This involves actually discriminating the Touch A/B from the Touch C in
the first place ;).
Get rid of the touchscreen probe thingy, as it *should* now be
unnecessary, and handle the actual Mk. 3 quirk, which is that the input
frame that reports a contact lift *already* does the coordinates
transform for us...
Unfortunately, our own transforms are not stateful, so this requires a
bit of an ugly hack, but, oh, well, it's a prehistoric device, so, you
get what you get ;).
While I'm there, fix the mirror transforms, which were all off-by-one
(600 pixels make for a [0, 599] range of coordinates, not [1, 600]).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9474)

Kobo: Attempt to fix input on Mk. 3 (i.e., Kobo Touch A/B).

---

Makefile

BTW, the kindle TC is stripped already, as it is 1.4 MB before and after
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9478)

make sure STL has proper permissions

---

frontend/device/kindle/device.lua

Fix #9482 (which, I, err, can't actually reproduce, the banner gets caught by the standard refresh on my device ^^).
Anyway, that was a fun investigation, many thanks to @yparitcher for playing along ;).
c.f., https://github.com/NiLuJe/koreader/commit/019f2b4a6f40435718765b877b1faec068907208 for more details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9491)

Kindle: Attempt to deal with sticky "waking up" hibernation banners

---

frontend/device/generic/device.lua
frontend/device/kobo/device.lua

Specifically, between checkUnexpectedWakeup & rescheduleSuspend, because we don't actually suspend *immediately*, we wait 15s, and if the unexpected wakeup guard fires *between* the two, shit goes wrong.
This was fairly easy to reproduce by plugging/unplugging a sleeping device (and a bit of "luck" with the timing); fix #9457.
Regression exposed by #9263, but the technical issue existed before that, and stems from an older refactor of checkUnexpectedWakeup that left some legacy and wonky behaviors in place ;). (Specifically, the counter set to 0 used to be meaningful at one point, but that was broken by design, so we switched to actually unscheduling the function, which is much saner. Unfortunately, the actual check for that older behavior was kept in place; and I tripped it with a poorly …

Kobo: Fix a few bad interactions between suspend & checkUnexpectedWakeup

---

plugins/autowarmth.koplugin/main.lua

This shall fix #9498. 
Add a menu entry in the "Warmth and night mode settings" menu
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9504)

AutoWarmth: add a choice to control warmth and/or night mode

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/readerui.lua
frontend/document/credocument.lua
frontend/document/pdfdocument.lua
frontend/ui/renderimage.lua
frontend/ui/widget/imageviewer.lua
frontend/ui/wikipedia.lua

As we do with web browsers.
(Dunno why I didn't think about it before, I was always closing and relaunching the emulator when hacking test HTML files to check cre tweaks :)
Add thirdparty/lunasvg, patched and extended https://github.com/koreader/koreader-base/pull/1514
Includes https://github.com/koreader/crengine/pull/489 : 
- SerialBuf: allow serializing longer strings
- Support `<img src="data:image/svg+xml,<svg...`, remove `;-cr-plain,`
- CSS: attribute selectors: accept `'` or `"` as the quote char
- Embedded fonts: fix ignored name when sharing same url
- LVImg: fix possible crash on GIF images
- Fonts: `DrawTextString()`: allow collecting glyphs as SVG paths
- Images parsing: cache native sizes
- SVG: enhanced SVG support with LunaSVG extended
- Add ldomNode::isImage(), handle …

bump crengine: better SVG support with extended LunaSVG

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/ui/translator.lua
frontend/ui/widget/inputdialog.lua
frontend/ui/widget/inputtext.lua
frontend/ui/widget/scrolltextwidget.lua
frontend/ui/widget/textboxwidget.lua
frontend/ui/widget/textviewer.lua
frontend/util.lua

Add default button to find a string in a text. Idea: https://github.com/koreader/koreader/pull/7966#issuecomment-1236184767.
When no additional buttons defined.
Standard search dialog.
Found string is marked with a cursor vertical line (like in TextEditor).
The notification shows the screen line number to help noticing the cursor.
With additional buttons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9507)

TextViewer: add Find

---

frontend/ui/data/dictionaries.lua

This adds a Russian-Russian dictionary that I created, extracted from Wiktionary.
The download/lua code is untested, so if someone would want to test it I have a random public domain Russian ebook:
[Гавриилиада_(Пушкин).zip](https://github.com/koreader/koreader/files/9568714/_.zip)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9517)

Add Russian Wiktionary dictionary

---

frontend/apps/filemanager/filemanagermenu.lua
frontend/fontlist.lua
frontend/ui/data/onetime_migration.lua

Since I never actually needed to look into that data ever until today, let's just get rid of the weird debug-specific behavior.
Instead, just add a dedicated "Developer options" entry that will dump it on demand (and it'll be sorted to boot, which makes it 500% more usable).
Plus, since yesterday's change, the cache format switch between debug or not miiiight actually be crashy, so re-trigger the migration  ;p.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9519)

FontList: Always use the binary cache format

---

frontend/version.lua

This PR change that `Version:getShortVersion` in `frontend/version.lua` handles the case of `rev` being empty, which happened for me in a "dirty" git environment (it seems like `kodev release android` does not include a `git-rev` file)
for now i have set `no version` to return instead of a empty string to indicate that it is missing, though i could also change it to `no git-rev file` or `dirty` depending on what is wanted
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9502)

fix(version.lua::getShortVersion): handle "rev" being empty

---

frontend/cache.lua
frontend/document/doccache.lua
frontend/ui/widget/imageviewer.lua
frontend/ui/widget/imagewidget.lua
frontend/util.lua

Computed with *magic* ;p
(Seriously, don't ask me to explain the maths :D).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9529)

ImageViewer: Clamp zoom factor to sane values

---

frontend/apps/reader/modules/readerdictionary.lua

Fixed in upstream sdcv, but we need to also do it in our parsing of .ifo and picking out dict name.
Also includes minor bump of base/sdcv https://github.com/koreader/koreader-base/pull/1518
See https://github.com/koreader/koreader/issues/9535#issuecomment-1252771204 .
Closes #9535. Closes #9455.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9536)

ReaderDict: fix use of dicts with ifo with DOS line endings

---

frontend/device/kobo/device.lua

Will need an actual tester to confirm FBInk gets the rotation right, as well as the touch input & frontlight situation.
Depends on https://github.com/koreader/koreader-base/pull/1521
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9545)

Kobo: Initial Clara 2E support

---

plugins/vocabbuilder.koplugin/db.lua
plugins/vocabbuilder.koplugin/main.lua

Adds button to undo last study operation (got it/forgot) in more (...) per fr #9527
Closes #9527.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9528)

vocabbuilder.koplugin: support undo word study

---

frontend/apps/reader/modules/readerfont.lua
frontend/apps/reader/modules/readerlink.lua
frontend/document/credocument.lua
frontend/ui/widget/touchmenu.lua

Allows having a toggable checkmark on menu items leading to a sub-menu.
Allow associating a font to each of the generic font-family names.
Bump crengine for https://github.com/koreader/crengine/pull/490 : 
- CSS parsing: accept (and ignore) namesspaces
- `isImage()`: more checks for `<object>` as it can have inner content
- `getFontFileNameAndFaceIndex()`: returns if font has math support
- `getFontFileNameAndFaceIndex()`: returns if font has emojis
- CSS/Fonts: add support for `font-family` to font name mapping
See discussion and early screenshots around in https://github.com/koreader/koreader/issues/7426#issuecomment-1258335839.
Changes since this proposal: made tap assign/unset a font for the current book only. It will need a long-press to get the association global and used on all …

ReaderFont: add "Font-family fonts" submenu

---

frontend/apps/filemanager/filemanager.lua
frontend/ui/widget/buttondialogtitle.lua
frontend/ui/widget/filechooser.lua
plugins/coverbrowser.koplugin/covermenu.lua
plugins/coverbrowser.koplugin/main.lua

Add usual way to start files selection: long-press the file and choose the <kbd>Select</kbd> button.
On pressing, the FM goes to the select mode and the file pressed is selected.
While in select mode, long-pressing on any file shows "Selection actions" pop-up menu (same as pressing the titlebar "Select" icon).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9571)

FileManager: add Select button to the file long-press menu

---

frontend/ui/elements/menu_keyboard_layout.lua

And do so only for the active layouts.
This prevents loading a potentially large amount of data without even having navigated to said menu (or having the layout enabled).
Noticed because the first TouchMenu open was hitching since the introduction of the ZH kb ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9584)

Keyboards/Menu: Lazy-load the layout-specific menu

---

.github/ISSUE_TEMPLATE/bug_report.md

Because it's literally 90% of my first replies :/.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9585)

GH: Extend the issue template to request verbose debug logs for non-crash issues.

---

frontend/dbg.lua
frontend/docsettings.lua
frontend/dump.lua
frontend/fontlist.lua
frontend/logger.lua
frontend/luadata.lua
frontend/luadefaults.lua
frontend/luasettings.lua
frontend/persist.lua
frontend/ui/trapper.lua
frontend/ui/widget/configdialog.lua
frontend/ui/wikipedia.lua
frontend/util.lua
reader.lua
spec/unit/persist_spec.lua

A.K.A. "Snakes, why did it have to be snakes?!".
* Persist: support serpent, and use by default over dump (as we assume consistency > readability in Persist).
* Logger/Dbg: Use serpent instead of dump to dump tables (it's slightly more compact, honors __tostring, and will tag tables with their ref, which can come in handy when debugging).
* Dbg: Don't duplicate Logger's log function, just use it directly.
* Fontlist/ConfigDialog: Use serpent for the debug dump.
* Call `os.setlocale(C, "numeric")` on startup instead of peppering it around dump calls. It's process-wide, so it didn't make much sense.
* Trapper: Use LuaJIT's serde facilities instead of dump. They're more reliable in the face of funky input, much faster, and in this case, the data never makes it to human eyes, so a …

Logger: Use serpent instead of dump

---

frontend/apps/filemanager/filemanagermenu.lua
frontend/device/kobo/device.lua

Because I'm kinda curious as to when exactly the PowerCover starts breaking all the things, and monitoring everything all the time is not practical...
(Also, re-enable the charging LED on the H2O).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9601)

Kobo: Add a debug option to turn the charging LED on PM entry failure

---

frontend/apps/reader/modules/readerdictionary.lua
frontend/apps/reader/modules/readerwikipedia.lua
frontend/ui/screensaver.lua
frontend/ui/widget/dictquicklookup.lua

* Fix a DictQuickLookup regression since #9586 that broke Wikipedia and a few DictQuickLookup features, like mass-closing.
* ScreenSaver: Never inhibit the power event messages, except when explicitly requested. (Having a custom message set would prevent them to shwo up).
* ScreenSaver: Make the overlay message behave better when attached to a top message (i.e., position it below instead of over).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9612)

A couple of fixes

---

frontend/docsettings.lua
frontend/luadata.lua
frontend/luadefaults.lua
frontend/luasettings.lua

The candidates array had a very very very high chance of being sparse, which effectively broke the logic.
It was *mostly* harmless since said logic is only here for a long and varied history of backwards compatibility ;).
c.f., https://github.com/koreader/koreader/pull/9603#issuecomment-1272201127
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9607)

DocSettings: Fix candidates sorting

---

frontend/ui/uimanager.lua
frontend/ui/widget/notification.lua

The ultimate goal is for toast widgets (i.e., Notification when flagged as such) to:
* Not stop event propagation
* Close themselves when the event was emitted by user input.
Instead of doing event filtering in UIManager, we simply overload the onGesture & onKey* handlers in Notification to do just that, and just make sure UIManager will *send* those events to toasts, but without affecting the usual semantics of top widget selection and event propagation (which is as simple as just calling handleEvent on them unchecked ;p).
Thanks to @poire-z for the brainstorming in https://github.com/koreader/koreader/issues/9594 ;).
This also happens to fix a bug in which we might have looped on the top widget twice, because of an array vs. hash mishap ;).
- - - …

UIManager: Fix handling of toast widgets in sendEvent

---

frontend/apps/reader/modules/readerstatus.lua

Saves current book status summary immediately on change in the "End of Book" dialog.
Closes https://github.com/koreader/koreader/issues/9616.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9619)

ReaderStatus: save status summary

---

frontend/ui/data/keyboardlayouts/th_keyboard.lua
frontend/ui/language.lua
frontend/ui/widget/virtualkeyboard.lua

This PR adds support for a Thai keyboard. Layout mostly copied from my phone, with difference in diacritics placements: phone has only one key for all of them, while here we have a couple more. Swipe in different directions needed for inputing them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9620)

Thai keyboard

---

frontend/dispatcher.lua

Discovered by @poire-z in https://github.com/koreader/koreader/pull/9531#issuecomment-1274839234
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9628)

Dispatcher: Fix subtle bug with modified items being added twice to the sort index

---

plugins/vocabbuilder.koplugin/db.lua
plugins/vocabbuilder.koplugin/main.lua

This PR adds support for reviewing words in reverse due time order in the vocabulary builder plugin. This will have the recently-worked-on words up front when there are a large number of words overdue, allowing for easier divide-and-conquer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9605)

vocabbuilder.koplugin: supports review in reverse order

---

frontend/ui/widget/buttondialogtitle.lua

Minor enhancement: if a ButtonDialogTitle is tall and exceeds the sreen height, align upper borders of the screen and the dialog, to see the dialog title.
Best applicable to new QuickMenus that may contain many actions/buttons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9631)

ButtonDialogTitle: align upper borders

---

frontend/device/kobo/device.lua
frontend/device/sysfs_light.lua
frontend/ui/uimanager.lua
frontend/ui/widget/frontlightwidget.lua

Also simplifies a few UIManager log messages (re: https://github.com/koreader/koreader-base/pull/1537)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9635)

Kobo: Always use open/write/close for sysfs writes

---

reader.lua

Sidenote for the crazy win32 people out there: it doesn't have a concept of line-buffering, so native win32 should use "no" here, but I'm *hoping* MinGW transparently handles this nonsense.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9636)

Oh, hey, Lua already has a setvbuf wrapper ;p

---

frontend/ui/uimanager.lua

* Remove a check made redundant by #9617
* Bump base (https://github.com/koreader/koreader-base/pull/1538)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9641)

UIManager: Minor code cleanup

---

frontend/ui/data/keyboardlayouts/zh_keyboard.lua

This PR makes zh_keyboard's number pad symbol mode instead of shift mode, so that numbers are shown when the keyboard is called expecting numeral input.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9654)

zh_keyboard: make number pad symbol mode

---

plugins/coverbrowser.koplugin/covermenu.lua

Broken since b0eb0ce0: the custom callbacks for the "Reset settings" & "Book information" buttons are not being called anymore because patching those is done to early (before instead of after creating the new modified dialog).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9647)

FileManager: fix button callback overrides

---

frontend/device/kobo/powerd.lua
frontend/ui/time.lua
frontend/ui/uimanager.lua
frontend/ui/widget/datetimewidget.lua
frontend/ui/widget/doublespinwidget.lua
frontend/ui/widget/frontlightwidget.lua
frontend/ui/widget/imageviewer.lua
frontend/ui/widget/infomessage.lua
frontend/ui/widget/inputtext.lua
frontend/ui/widget/notification.lua
frontend/ui/widget/qrmessage.lua
frontend/ui/widget/radiobuttonwidget.lua
frontend/ui/widget/screensaverwidget.lua
frontend/ui/widget/skimtowidget.lua
frontend/ui/widget/spinwidget.lua
frontend/ui/widget/textviewer.lua
frontend/ui/widget/trapwidget.lua
plugins/statistics.koplugin/readerprogress.lua

* Kobo: Unbreak frontlight toggle for some speciifc values (fix #9674, regression since #9609)
* ScreenSaver: Actually enable the `onAnyKeyPressed` handler (allowing one to close the ScreenSaver with page-turn buttons, for instance). [This is properly disabled when using the child lock pattern mode, because @poire-z rules ;)].
* Previous commit lead to a general cleanup of those handlers in the codebase, because it turns out it was *really* not the only dumb unused code c/p around ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9676)

A small round of fixes

---

frontend/ui/elements/font_ui_fallbacks.lua
frontend/ui/font.lua

This PR adds support for user-customizable bold fonts for fallback UI fonts, including default ones and user-added ones.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9621)

Customizable bold font for fallback UI font

---

plugins/profiles.koplugin/main.lua

New profiles are not registered in Dispatcher by default.
Requires a fix to Dispatcher to not kill profile `settings` field when selecting "Nothing" action.
@yparitcher
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9623)

Profiles: optional registration in Dispatcher

---

frontend/apps/reader/modules/readermenu.lua
frontend/ui/elements/reader_menu_order.lua

One of the most frequent questions asked by the new users is why my current settings are not applied to all books.
After they understand why, they must go through all the settings once more. This will help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9643)

Save current document settings as default settings

---

frontend/apps/reader/modules/readerdogear.lua
frontend/apps/reader/modules/readerfooter.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/apps/reader/modules/readerthumbnail.lua
frontend/apps/reader/modules/readertoc.lua
frontend/dispatcher.lua
plugins/statistics.koplugin/main.lua

When a gesture/profile was updating multiple cre settings, each setting handler would emit UpdatePos which each would force a re-rendering.
When this might be happening, postpone the rerendering until all are set.
Needs some bit of refactoring to the events at play: introduce "DocumentRerendered" event, and use it where we used "UpdatePos" or "UpdateToc" to mean exactly that.
Discussion and first experiments at https://github.com/koreader/koreader/issues/9594#issuecomment-1272475277
Not thoroughly tested, and it's a bit hard to guess what edgy mess this kind of event tweaking can cause (I just changed what I needed trying to keep the logic, there may be extra unnecessary calls that were already there around ReaderFooter and the non-linear flow stuff). (Also, the undocumented/unavailable …

Dispatcher: avoid multiple cre rerenderings when many settings changed

---

plugins/autodim.koplugin/main.lua

When AutoDim knocks in it sometimes happens, that a tap does not exit the trapper widget. So multiple taps (many of them) have to b done, before swallowing input events is done.
This PR fixes that, be explicitly closing the trapper widget (if there is one), before showing the other one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9675)

AutoDim: close trapper widget explicitly

---

spec/unit/uimanager_bench.lua
spec/unit/uimanager_spec.lua

argc was eliminated in https://github.com/koreader/koreader/pull/9624
Thanks to @hasezoey (https://github.com/koreader/koreader/pull/9680#issuecomment-1290440793)
Plus a minor change in the scheduling test, so that the _task_queue is not filled only from one end.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9684)

Test suite: get rid of argc in the _task_queue

---

frontend/dispatcher.lua

(1) Preserve profile name when selecting the "Nothing" action.
(2) Show number of actions instead of "Many".
TODO after https://github.com/koreader/koreader/pull/9651#discussion_r1000918149: fix checkbox of the "Nothing" action for profiles with name.
https://github.com/koreader/koreader/blob/724db8775561651abbf24650b95b2d03a07d961d/frontend/dispatcher.lua#L800-L802
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9682)

Dispatcher: preserve profile name, show actions count

---

spec/unit/uimanager_spec.lua

Fixes a test case, where the `_task_queue` was not sorted before calling `_checkTasks`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9694)

[spec] UIManager:_task_queue has to be sorted!

---

frontend/apps/cloudstorage/webdav.lua
frontend/apps/cloudstorage/webdavapi.lua

This PR fixes bugs in `webdavapi`:
- error when url ends with `/` and start folder starts with `/`
- error checking current folder when url encode has different letter case than server
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9688)

WebDAV: fix bugs when start folder starts with "/"

---

frontend/apps/reader/modules/readerkoptlistener.lua
frontend/apps/reader/modules/readerzooming.lua

Strings are taken from koptoptions.lua, so no new translations are needed.
Closes https://github.com/koreader/koreader/issues/9667.
Side bonus: simplify zoom mode validation, get rid of `arrayContains`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9707)

ReaderZooming: translate zoom mode in infomessage

---

frontend/ui/widget/keyvaluepage.lua

When creating a KeyValuePage with an empty table of kv_pairs, it will throw an error unless there's a check to prevent that.
`./luajit: frontend/ui/widget/keyvaluepage.lua:601: attempt to compare nil with number`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9705)

KeyValuePage: Don't compare potential nil with number

---

frontend/ui/widget/textviewer.lua

Similar to most fullscreen widgets (#8726), even if TextViewer is mostly not-fullscreen, but just nearly fullscreen :).
https://github.com/koreader/koreader/pull/8726#issuecomment-1294207467 :
> I got used to using multiswipes to close all these fullscreen widgets.
There's one place where this habit doesnt work: TextViewer. It's usually (always?) not fullscreen.
Any problem/inconsistency you would see if it would also multiswipe-close ?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9720)

TextViewer: allow close on any multiswipe

---

frontend/ui/widget/keyvaluepage.lua

Add left button.
Allow title centering (may be useful with the left button).
May looks like:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9713)

KeyValuePage: enhance TitleBar

---

frontend/dispatcher.lua

Should fix https://github.com/koreader/koreader/discussions/9719
Regression introduced in https://github.com/koreader/koreader/pull/9682 by my fault.
See the xgettext error message:
```
frontend/dispatcher.lua:573: warning: Empty msgid.  It is reserved by GNU gettext:
gettext("") returns the header entry with
meta information, not the empty string.
xgettext: warning: msgid '' is used without plural and with plural.
xgettext.c:1975: Here is the occurrence without plural.
frontend/dispatcher.lua:573: Here is the occurrence with plural.
Workaround: If the msgid is a sentence, change the wording of the sentence; otherwise, use contexts for disambiguation.
```
- - - …

Fix broken translation metadata

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/dispatcher.lua

(1) Add "Add note" default 'long-press on text' action
(2) Allow setting the default action with a gesture (will help a little bit to https://github.com/koreader/koreader/issues/9695).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9723)

ReaderHighlight: set default long-press action with a gesture

---

frontend/ui/uimanager.lua
spec/unit/readerfooter_spec.lua
spec/unit/taskqueue_bench.lua
spec/unit/uimanager_bench.lua
spec/unit/uimanager_spec.lua

In real life most scheduled tasks are in the near future. Tasks being long in the future are seldom rescheduled. 
In the current implementation if a near future task is scheduled it is inserted at the beginning of the task queue, and therefore most of the queue has to be shifted backwards. When such a task gets consumed, the whole queue is shifted forwards again. So there is a lot of shifting. The only benefit of this implementation is, that `_checkTasks` only needs to check `_task_queue[1]`.
This PR reverses the sorting order of the task_queue, so that tasks scheduled in the near future are at the end of the queue -> less shifting on insertion and consumption.
Additionally, there is a small benchmark `taskqueue_bench.lua` which tries to mimicry some real life usage with scheduling and …

[UIManager] Reverse order of _task_queue

---

plugins/autowarmth.koplugin/main.lua

If the user changes night mode _and_ AutoWarmth controls night mode too, give the user an InfoMessage about that fact.
Tested for night mode menu entry and for gestures.
This should close https://github.com/koreader/koreader/discussions/9712 and #9737
As always rewording of the message is welcome ;-)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9715)

AutoWarmth: add message on user change of night mode

---

frontend/dispatcher.lua

Tools and humans alike are confused by leaving it empty. It should be inoffensive to resolve the problem by having an unused singular. Doing anything else would make it so we couldn't have the correct plurals in Slovak, among others.
Follow-up to https://github.com/koreader/koreader/pull/9726
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9734)

Dispatcher: add unused singular to action plurals

---

plugins/newsdownloader.koplugin/main.lua

*I can't believe I opened a PR and it didn't include unrelated commits.*
Can't reproduce, but most likely this is a fix for #9690
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9697)

NewsDownloader: Keep nil reference from being passed to UIManager  

---

plugins/statistics.koplugin/calendarview.lua

This PR changes the color palette of statistics plugin's calendar view's book bars, aiming at an increased difference among bar colors while removing the striking pure black.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9739)

Statistics calendar view: adjust color palette to avoid pure black bars

---

frontend/apps/reader/modules/readerhighlight.lua

We cannot make multi-page highlighting in pdf yet, so need to check if starting and ending fragments are within one page.
In pdf continuous mode `current_page` is not accurate, let's use `hold_pos.page` of the ending fragment instead.
Closes https://github.com/koreader/koreader/issues/9729.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9769)

ReaderHighlight: fix ending fragment check in continuous mode

---

frontend/apps/reader/modules/readertoc.lua

Fix regression introduced by 48eb0231 #9651: on re-rerendering, the new pages count didn't reach the Statistics plugin.
So, if you change font size or margins, the stats for the page read since then were badly accounted, until a change of book or restart... I noticed that in Book map, strange nobody else did over the last 2.5 weeks.
(Stupid me... I explicitely put back the `return true` in :onUpdateToc - as nothing else should handle that event - and just use it as-is for onDocumentRerendered, which itself should propagate...)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9775)

Fix page stats messed up after rerendering

---

plugins/vocabbuilder.koplugin/db.lua

Use pcalls to protect each migration step.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9702)

Vocabbuilder.koplugin: make db migration allow starting from intermediate stage

---

frontend/apps/reader/modules/readerview.lua
frontend/ui/elements/page_turns.lua

Allows to set backward and forward tap zone widths separately (and have a gap between them).
Closes https://github.com/koreader/koreader/issues/9466.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9772)

Page turns: add backward tap zone width setting

---

plugins/vocabbuilder.koplugin/db.lua
plugins/vocabbuilder.koplugin/main.lua

This PR adds longer review intervals. See #9757.
(Not sure if `mo` and `yr` are the correct way to abbreviate month and year.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9764)

Vocabbuilder.koplugin: allow longer intervals

---

frontend/ui/widget/button.lua
frontend/ui/widget/sortwidget.lua
plugins/vocabbuilder.koplugin/db.lua
plugins/vocabbuilder.koplugin/main.lua

This PR adds the ability to re-assign which book a word belongs to and change name of an existing book. It can be used as a way to regroup words and hide/show them by book. cf. #9486
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9776)

vocabbuilder.koplugin: make a word's book title changeable

---

frontend/ui/widget/button.lua

Fix long text alignment (defect from https://github.com/koreader/koreader/pull/9526).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9778)

Button: fix long text alignment

---

frontend/ui/data/dictionaries.lua

This adds Vietnamese dictionaries to koreader
I got dictionaries files from <https://sourceforge.net/projects/ovdp/>, repacked to tar.gz and pushed them to <https://github.com/KhoiCanDev/ovdp-mirror>, files provided using github pages CDN
Built and tested manually on Linux (running emulator)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9783)

dictionaries: add Vietnamese dictionaries

---

frontend/apps/filemanager/filemanagerutil.lua

Correspond `filemanagerutil.abbreviate` with `util.splitFilePathName`.
Closes https://github.com/koreader/koreader/issues/9782.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9785)

Filemanagerutil: let abbreviate manage extra slash

---

frontend/apps/reader/modules/readermenu.lua
frontend/device/pocketbook/device.lua

* Handle HOME on PB (fix #9791)
* MENU in ReaderMenu should bypass the gesture filters (fix #9792)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9794)

A couple of button mapping fixes

---

frontend/apps/cloudstorage/syncservice.lua
frontend/ui/widget/keyvaluepage.lua
plugins/vocabbuilder.koplugin/main.lua

This fixes:
1. `keyvaluepage` key value too close when keys are short and values are long https://github.com/koreader/koreader/pull/9672#issuecomment-1314265246
2. `syncservice` not updating services after adding new ones
3. `vocabbuilder.main` not updating book title in the "more" dialogue when the book title is changed but not reassigned.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9790)

Fix a couple bugs: keyvaluepage, syncservice, vocabbuilder

---

frontend/device/pocketbook/device.lua

Needed for: https://github.com/koreader/koreader-base/pull/1484
Fixes: #8872
Adjust image colors for pocketbook color devices to supply brighter image colors. Make it a config option to we can adjust it to a sensible default for all devices later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9756)

Use inkview to adjust image colors to look more bright

---

plugins/exporter.koplugin/clip.lua

If a highlight cannot be associated with a bookmark, place it at the end of the exported list.
Closes https://github.com/koreader/koreader/issues/9801.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9802)

Exporter: fix orphan highlights

---

plugins/statistics.koplugin/main.lua

This pr fixes a bug in statistics plugin's sync sql command that uses left join instead of inner join, which adds unnecessary comparisons and might result in incorrect mapping between databases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9811)

Statistics sync: fix sql command

---

frontend/apps/reader/modules/readerstyletweak.lua
frontend/dispatcher.lua
frontend/ui/widget/touchmenu.lua
plugins/profiles.koplugin/main.lua

Style tweaks can be applied with a gesture or added to a profile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9816)

Reader style tweaks: register in Dispatcher manually

---

frontend/ui/screensaver.lua

Closes #9048. Shows battery status at suspend time. It would be nice to have the corresponding battery icon in there too, but here's a start. Would also be cool to somehow update the percentage on screen while suspended and charging (like Kobo does natively), but that sounds pretty complicated.
Be cool, it's my first time writing Lua. Hopefully the first of many PRs to come.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9810)

ScreenSaver: Battery percentage in screensaver message

---

plugins/batterystat.koplugin/main.lua

While the Battery Statistics plugin is ~great~, it doesn't actually show the current battery level, which obviously makes it hard to interpret some of its data.
Now that I know something about the gettext strings, I'd like some feedback on the best way to proceed here. I thought the title would be a good, prominent place to put the battery percentage. The original "Battery statistics" was a gettext string. I saw an example in the AutoWarmth plugin where a gettext string is used inside a `string.format` call, so that's what I used, but I'm open to suggestions.
https://github.com/koreader/koreader/blob/d6b67f42d8a6605fe7a919ea8e8807aa14548340/plugins/autowarmth.koplugin/main.lua#L1204-L1206
- - - …

BatteryStat: Show current battery percentage

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/ui/widget/confirmbox.lua

In the new select mode ConfirmBox actually there is no question, so the "notice-question" icon to be changed to the new select mode symbol.
(It can be just "notice-info" but it is not so interesting imho).
Old
Proposed
Option
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9830)

ReaderHighlight: new icon in select mode ConfirmBox

---

plugins/opds.koplugin/opdsbrowser.lua

Such catalogs are not cached.
Closes https://github.com/koreader/koreader/issues/6088.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9829)

OPDSbrowser: accept catalogs without header in response

---

plugins/statistics.koplugin/calendarview.lua
plugins/statistics.koplugin/main.lua

- Add vertical lines every 10mn
I tried using a lighter gray than the one used for horizontal lines, but the thin lines were nearly invisible on my GloHD.
I also needed to add a top and bottom lines, otherwise the vertical lines reaching outwards a line felt a bit odd.
- If today, show an arrow indicator at current time
- Add "Today's timeline" to menu
Any better position/ordering ? (I have a thought for non-touch people that may have some habbits navigating with keys to reach CalendarView - they may reach now Today's timeline - but dunno where else to put it, as it's somehow a child of Calendar view.
- Rename badly named self.hour_width, which is a height
Suggested around https://github.com/koreader/koreader/pull/9813#issuecomment-1321938944.
It feels there is a bit of abuse of …

Calendar view's day view: visual tweaks

---

plugins/statistics.koplugin/main.lua

Ensure any reading at 0h00 or 23h59 looks like it continues from previous or to next page if DB data seems to indicate so.
See https://github.com/koreader/koreader/pull/9832#issuecomment-1327968436.
Was a bit tedious :/ Tested with one sample case :\
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9834)

Calendar view's day view: tweak SQL data extraction

---

frontend/apps/filemanager/filemanagerhistory.lua

This remembers the currently status filter in the History viewer as a user setting, added with #8820 (and answers #3406 a little better).
Since we had to (and still do) grab statuses from every book by opening up the files, I abided by @poire-z's concerns ([here](https://github.com/koreader/koreader/pull/8820#discussion_r809967780)) to make sure no extra work is added when the filter is off ("all"). I do this by only scanning the files for their status if there is a filter selected, and this data is re-used when showing the filter-selection dialog. If there is no filter currently selected, the filter-selection dialog scans the files like it did before. This means that just like before, if you have no filter selected, opening the History viewer will not scan all your history files, which …

Remember history status filter, show filtered count in view

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/modules/readerthumbnail.lua
frontend/apps/reader/modules/readerview.lua
frontend/document/koptinterface.lua
frontend/document/pdfdocument.lua

Available via Select mode. (nothing new to show in screenshots)
Some technical details:
(1) pboxes are not saved in bookmarks anymore
(2) for highlights made in reflow mode `page` is stored in `position` now (but older bookmarks exist, so some check is needed in sorting)
(3) for multi-page pdf highlights new key `ext` is saved to the highlight structure, contains positions and pboxes of each page
(4) to draw a pdf page readerview now must scan all the pages of the document to find extended pages of multi-page highlights
(5) writing highlight to pdf annotation: fixed a bug with changing highlight style (the note was killed after that); the note is saved for each page of multi-page highlight (we can hover the mouse over any part of the highlighted text to see the note).
(6) note marker …

ReaderHighlight: pdf multi-page highlights

---

.github/workflows/build.yml

Doing a debug build using MACOSX_DEPLOYMENT_TARGET=12.00 produces a build that seems to work. The debug part isn't optimal but at least it builds and runs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9856)

[CI] Set macOS Github Action to macOS 12.00

---

frontend/apps/cloudstorage/webdavapi.lua

(sub)folders on some WebDAV servers are not listed in cloudstorage due to strict xml element matching of `<d:collection>`  elements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9847)

cloudstorage: Fix directory listing for some WebDAV servers

---

frontend/apps/filemanager/filemanagermenu.lua
frontend/device/devicelistener.lua
frontend/device/generic/device.lua
frontend/pluginloader.lua
frontend/ui/elements/common_exit_menu_table.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/font_settings.lua
frontend/ui/elements/font_ui_fallbacks.lua
frontend/ui/elements/menu_activate.lua
frontend/ui/elements/screen_disable_double_tap_table.lua
frontend/ui/elements/screen_dpi_menu_table.lua
frontend/ui/elements/waveform_level.lua
frontend/ui/language.lua
frontend/ui/network/manager.lua
frontend/ui/uimanager.lua

Maybe not the most important change, but esp. during development it might save some taps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9853)

Restart KOReader: add a ConfirmBox instead of a plain InfoMessage

---

frontend/ui/widget/touchmenu.lua

See <https://github.com/koreader/koreader/pull/9876#issuecomment-1340090208>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9884)

TouchMenu: menu search without patterns

---

frontend/apps/cloudstorage/syncservice.lua
plugins/statistics.koplugin/main.lua

This pr adds support for dropbox short-lived token for the cloudsync module. See #9861
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9862)

Cloudsync: dropbox token re-generation

---

plugins/statistics.koplugin/calendarview.lua
plugins/statistics.koplugin/main.lua
plugins/statistics.koplugin/readerprogress.lua

No need to pass the translations from main.lua to calendarview.lua.
Also use datetime translations in ReaderProgress.
Closes #9892.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9893)

Calendar view: properly use datetime module

---

frontend/device/kobo/device.lua

Fix for #9895 
Seems to be a similar/identical issue to #9590 , the Sage fix is based on that but using `automagic_sysfs` and the `/dev/input/by-path/` which seems to be preferred in the existing code.
If the issue was caused by a hardware change, I'm optimistic this fix won't affect older devices that don't need it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9896)

Fix non-working power button on Kobo Sage

---

frontend/ui/screensaver.lua

If there are hidden flows, this calculates the current page, total pages, percent, time left in chapter, and time left in the magic variables used in screensaver message only for the current flow. If there are no hidden flows, the behavior is the same as before.
Did some testing with no non-linear flows, hidden flows, non-hidden flows, hidden flows in the middle of a linear flow, didn't find any discrepancies (after the first 300 I found and fixed, that is).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9905)

Add linear flow wisdom to screensaver message magic variables

---

frontend/ui/screensaver.lua

At @NiLuJe's request, I tried to add a note to the screensaver message about the variables that will only apply to the current flow if any flows are hidden (see #9905). Not the prettiest thing, nor the clearest, but not a lot of room to work with here and we're already cramped.
plus more sensible order and an extra space between symbol and description
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9909)

Add note about flows to screensaver variables message

---

frontend/apps/reader/modules/readermenu.lua
frontend/ui/screensaver.lua

At the risk of juggling too many plates... This one belongs directly with excluding the cover; for any book where you want to exclude the cover, you likely want to exclude the text even more. ;)
* Make the "Exclude this book's cover from screensaver" into "Exclude this book's cover and text from screensaver"
* Disable the "disabled" screensaver type if this is checked and we're currently inside that book
* Disable "Book status" if this is checked, since it also includes the book cover
* Use random image as fallback for all screensaver types (it's the safest option from both a privacy and availability perspective) instead of "disable" (which can now be excluded with the above checkbox)
* Use `resources/koreader.png` as fallback if random image folder empty, as it's guaranteed (though if …

Exclude text when excluding cover, random image as fallback

---

plugins/statistics.koplugin/main.lua
plugins/statistics.koplugin/readerprogress.lua

I like the Reading Statistics plugin.
**Changes:**
- Reading Progress
- Rename "Reading Progress" title "Current" to more descriptive "Session" (parity w/ Current Statistics that calls this concept a "session")
- Change "Average / pages" to "Average / pages/day" and "Average / time" to "Average / time/day" since the old text is not intuitive to understand, and we have space, and fits pattern of "Total / time", etc.
- Use more widespread YYYY-MM-DD date format instead of "MM.DD"
- Current Statistics and per-book view
- If book has non-linear fragments, use same logic as the status bar uses to show current page and remaining time
- Add current page status spacing, "%d/%d" to "%d / %d" etc., to match status bar
- Show on a single page since they're guaranteed to be short anyway
- Make values …

ReadingStatistics: Cleanup and tweaks

---

frontend/apps/reader/modules/readerfooter.lua
frontend/ui/data/onetime_migration.lua

Seems like at some point in the past, we've expanded from the original Icon/Letter/Compact paradigm applying only to prefixes. These 3 options today apply to the entirety of the footer status bar items. Some non-prefix-related things today that depend on whether the "Compact" option is selected:
- separation spacing between status bar items
- the width of the whitespace within the actual items themselves
This change adds one more thing: when the modern time format is selected, and the Compact option is not selected, we display time left in chapter and time left in book as full hms format (8m23s) instead of 8m23'. Compact remains in the 8m23' format.
And since this option was already extended beyond the prefix level, I've rechristened it with the more fitting name "Item style":
- I've …

Change footer status bar type setting label from 'Prefix' to 'Item style'

---

plugins/statistics.koplugin/main.lua
plugins/vocabbuilder.koplugin/db.lua

I love the statistics cloud sync @weijiuqiao created for #9709.
One minor annoyance with the original version, though: *every* time you run the sync process, the sqlite autoincrement sequence increases by the total number of books in the database, even if literally nothing has changed in the statistics database.
When you do an insert using either `ON CONFLICT [...] DO NOTHING` or `INSERT OR IGNORE` to prevent duplicate rows, sqlite still increments the sequence counter for each of the duplicate rows that it did not insert.
The only way around that is to explicitly write the SQL statement so that it doesn't try to insert the duplicates in the first place.
- - - …

Do not increment db sequences unnecessarily during cloud sync

---

frontend/ui/message/streammessagequeue.lua
plugins/calibre.koplugin/wireless.lua

Also, get rid of the weird and clunky `failed_connect_callback` thingy, because it makes no sense?
Re #9908
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9914)

Calibre: Log errors on wireless connection failures

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/filemanager/filemanagermenu.lua
frontend/apps/reader/modules/readerfont.lua
frontend/apps/reader/modules/readermenu.lua
frontend/apps/reader/readerui.lua
frontend/dispatcher.lua
frontend/ui/widget/touchmenu.lua
plugins/gestures.koplugin/main.lua

Follow up to #9823 and #9876 , fix issues noticed at https://github.com/koreader/koreader/pull/9876#issuecomment-1340011033 and others:
- Cleanup search and animation codes, fix inconsistencies between animation/no-animation opening, and refreshes glitches on eInk.
- Show menu item on tap, with buttons to either open directly, or to walk there (removed earlier "Animation" checkbox, so the choice can be decided later).
- Move event handlers into ReaderMenu/FileManagerMenu.
- Avoid duplicated and confusing results from gestures and font-family submenus.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9926)

TouchMenu: tweak menu search

---

frontend/device/pocketbook/device.lua

Requires: https://github.com/koreader/koreader-base/pull/1562 and https://github.com/koreader/koreader-base/pull/1566
Issue: #9427
~~I feel I will need to ask for a lot of forgiveness now after writing this stuff. Most likely this implementation is completely in the wrong place and implemented completely in the wrong way but it actually works.~~
~~Because the lack of a proper event when the screen is rotated (I've looked, and looked, and looked even more but didn't find one). The only way I know ATM is polling the GSensor every second and just broadcasting an event for the screen change when there was a change found.~~
~~Most likely this is extremely inefficient so feel free to point me to a better way of doing this. But I was not able to find some more guiding implementation on the gyro …

Implement GSensor support for more moderm PocketBooks

---

frontend/ui/widget/container/centercontainer.lua
frontend/ui/widget/container/widgetcontainer.lua
frontend/ui/widget/iconbutton.lua
frontend/ui/widget/textwidget.lua

Noticed while testing #9941 in RTL mode.
Includes a few other trivial style fixes in separate commits.
I couldn't *quite* figure out what was responsible for inverting the padding values, though... (@poire-z? ;p).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9959)

IconButton: Fix highlights in RTL UI

---

frontend/ui/network/manager.lua
plugins/autowarmth.koplugin/main.lua

Minimal simplifications of `enabled_func` in two cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9966)

TouchMenu: simplify/remove enabled_func in use cases

---

plugins/coverimage.koplugin/main.lua

Make CoverImage unit usage consistent with the rest of KOReader.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9938)

[plugin, CoverImage] Use units in SpinWidget

---

frontend/device/generic/device.lua
frontend/device/kindle/device.lua
frontend/ui/screensaver.lua
frontend/ui/widget/screensaverlockwidget.lua
frontend/ui/widget/screensaverwidget.lua
reader.lua
spec/unit/device_spec.lua

Go through a dedicated sticky invisible widget instead of piggybacking on ScreenSaverWidget, so that we behave if there are other InputContainers in ScreenSaverWidget, or if there aren't any ScreenSaverWidget at all.
Fix #9911, fix #9955
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9964)

ScreenSaver: Refactor gesture lock to behave regardless of configuration

---

frontend/ui/widget/checkmark.lua

The x and y coordinates of SortItemWidget's checkmark widget were not updated, thus remained at their initial value 0. Consequently the [intersectWith check in SortItemWidget:onTap](https://github.com/koreader/koreader/blob/788ccac5613af02812ae210bb801e682836f1ca4/frontend/ui/widget/sortwidget.lua#L96) always evaluated to false, resulting in taps on checkmarks in the sort widget not being recognized.
I considered putting this directly in WidgetContainer so that intersectWith tests are also possible with other widgets than CheckMark that dervie from  WidgetContainer, but decided against it, because I found a [usage](https://github.com/koreader/koreader/blob/788ccac5613af02812ae210bb801e682836f1ca4/plugins/perceptionexpander.koplugin/main.lua#L73) of the ["offset" feature present in …

Fix on tap toggling of checkmark in sort widget

---

frontend/apps/reader/modules/readerdogear.lua
frontend/ui/widget/buttontable.lua
frontend/ui/widget/container/movablecontainer.lua
plugins/texteditor.koplugin/main.lua

Prevent any later hold_release event from being handled by MovableContainer as a moving touch+hold_release.
This issue was noticable when closing DictQuickLookup with long-press on close, resulting in the movable highlight actions ButtonTable moving to where the long-press happened.
Issue described at https://github.com/koreader/koreader/pull/9507#issuecomment-1328103992, and various alternative solutions proposed in next posts.
Regression since #9651, fix item 4 of #9979, https://github.com/koreader/koreader/issues/9979#issuecomment-1368258192.
Closes #9973 , by getting rid of the numbers :) and going with:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9985)

ButtonTable, ReaderDogear and TextEditor tweaks and fixes

---

frontend/ui/data/dictionaries.lua

The name of the dictionary is "Big explanatory dictionary of the modern Ukrainian language".
Regarding license please see https://uk.wikipedia.org/wiki/Український_тлумачний_словник (I am biased).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9982)

Dictionaries: add Ukrainian explanatory dictionary

---

frontend/apps/reader/modules/readerlink.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/ui/uimanager.lua

Abort earlier if the nearest link is too far, instead of computing stuff and creating an object we'll never actually use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9987)

ReaderLink: Minor logic simplification in onGoToPageLink

---

plugins/autowarmth.koplugin/main.lua

Change is only noticeable to translators.
See
https://github.com/koreader/koreader/discussions/9990
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9996)

[AutoWarmth] Simplify translations

---

frontend/device/kobo/device.lua

Regression since #9902, because I'd forgotten that the default Kobo block *does* set those...
Reported by @ptrm on Gitter, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9998)

Kobo: Unbreak automagic_sysfs on the Libra 2

---

frontend/apps/reader/readerui.lua

(1) Set initial status to "reading" on opening a book. Closes https://github.com/koreader/koreader/issues/9500.
(2) Save a book to history on success opening only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9993)

ReaderUI: fix status and history

---

frontend/ui/elements/common_exit_menu_table.lua

Unwillingly removed by #8459.
Closes #9999. (And this PR should be #10000 !!! :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10000)

Exit menu: restore long-press to exit directly

---

frontend/apps/reader/modules/readerfooter.lua
frontend/apps/reader/modules/readerview.lua
frontend/device/android/device.lua
frontend/device/generic/device.lua
frontend/device/kobo/device.lua

The translation was applied *before* platform-specific input hooks, which, well, broke it, because we always swap x/y on Kobo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10008)

Kobo: Unbreak input translation when a viewport is involved

---

frontend/device/kobo/device.lua

Fix #10020, Regression since #10008
(hasMultiTouch is set by `Generic.init`, but we use it before that; so just set it properly ourselves in our superclass, because we don't actually need to rely on Generic's autodetection).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10019)

Kobo: Unbreak a slew of devices

---

frontend/device/wakeupmgr.lua
frontend/ui/uimanager.lua

Apparently, toggling the rtc interrupt doesn't quite work on some boards?
Fix #10031
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10032)

WakeupMgr: Explicitly invalidate the current alarm in unsetWakeupAlarm

---

plugins/profiles.koplugin/main.lua

(1) Keep profile registration in a duplicate. Closes https://github.com/koreader/koreader/issues/9980.
(2) Fix profile menu update on register/unregister. Closes https://github.com/koreader/koreader/issues/10026.
(3) Update gestures and profiles after renaming a profile. Closes https://github.com/koreader/koreader/issues/10027.
(4) Update gestures and profiles after deleting a profile.
(5) Update gestures and profiles after unregistering a profile.
(6) Fix Profiles touchmenu stack update (unreported bug).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10033)

Profiles: fixes

---

frontend/device/kindle/device.lua
frontend/ui/network/manager.lua

isWifiOn for kindle currently returns if the interface is connected, change this to doing what is says isWifiOn the file is only present if the wireless interface is up.
isConnected pings the gateway, rely on the kernel for a more reliable check.
Whan connecting to my android phone's wifi hotspot to remote debug from my phone, the network is connected yet the phone(gateway) does not respond to pings leading koreader to shut down the connection thinking it is unsuccessful
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10059)

Kindle: NetworkMgr: isWifiOn isConnected

---

kodev

`grep: warning: stray \ before -`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10071)

kodev: fix grep warnings

---

platform/appimage/koreader.appdata.xml

To make it shown as a desktop application and listed on flathub.org, the app data must mark it as a desktop application: https://github.com/flathub/flathub/wiki/AppData-Guidelines#header
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10076)

fix not shown as a desktop application

---

frontend/ui/elements/common_settings_menu_table.lua

See:
https://github.com/koreader/koreader/pull/9946#issuecomment-1364588746
This is what it looks with consistent menu entries
A question for wording: I think `Save book metadata: only on close and suspend` should be long/informative enough.
1.) Why auto (this just eats space)?
2.) Do we have a manual save?
3.) Exit implies close, so on every exit the document would be closed anyway.
So I would prefer (not in this commit yet)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9995)

[Document] Consistent menu entries in auto-save menu

---

frontend/device/kobo/powerd.lua
plugins/autowarmth.koplugin/main.lua

Today I got a strange behavior with AutoWarmth.
Starting the device (Sage) and going from NickelMenu to KOReader (during twilight), the warmth of the display did not change, although the correct warmth was displayed in the status bar.
A few reboots and KOReader restarts and Nickel-KOReader rounds later I found, that the first call of `Powerd:setWarmth` did nothing as `Powerd:frontlightWarmth()` (a somewhat ambiguous name; getWarmth would be better) returned the same value, as `setWarmth` wanted to set. 
So the question is, why did `frontlightWarmth()` return that value? Why to h.... does `frontlightWarmth()` knew, what value AutoWarmth wanted to set.
The PR fixes this special quirk by forcing `setWarmth()` to use the current value. That should not do much harm, as it gets called only on …

Screen Warmth: Fix a bug with syncing screen warmth on start

---

frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua
frontend/userpatch.lua
plugins/patchmanagement.koplugin/_meta.lua
plugins/patchmanagement.koplugin/main.lua
plugins/texteditor.koplugin/main.lua

This PR allows to enable/disable user patches.
(Draft by now, as there are unwanted l10n and lajit-launcher commits in here. I will look into that on WE)
I really would like to have it under `Plugin management` as I feel that my(?) patches are similar to plugins.
Here you can see, which patches (level)  are installed.
And here a patch on a certain level
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9970)

PatchManager: a plugin to manage user patches

---

reader.lua

Stupid c/p typo exists since its inception in #6976
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10095)

Misc: Make --verbose do what it should be doing ;).

---

frontend/device/android/device.lua
frontend/device/cervantes/device.lua
frontend/device/generic/device.lua
frontend/device/kindle/device.lua
frontend/device/kobo/device.lua
frontend/device/pocketbook/device.lua
frontend/device/remarkable/device.lua
frontend/device/sdl/device.lua
frontend/device/sony-prstux/device.lua
frontend/ui/network/manager.lua
frontend/ui/network/networklistener.lua

Follow up to #10059.
Many of the devices use the same function to back both `iswifion()` and `isConnected()`. I think they represent different things, 1. is the radio on 2. are we connected to a network.
I fixed this for kindle, but asking for the other devices,
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10062)

network info is probably only available when connected

---

frontend/ui/network/manager.lua
frontend/ui/network/networklistener.lua

They expose a network sysfs entry so we can track usage
Works for me on kindle, but i stop the amazon framework
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10096)

network: Allow auto_wifi_off on kindle & remarkable

---

frontend/device/android/device.lua
frontend/device/generic/device.lua

Because a translation by (0, 0) is pretty dumb ;o).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10104)

Input: Don't set unnecessary input translations when viewports are involved

---

frontend/device/cervantes/device.lua
frontend/device/kindle/device.lua
frontend/device/kobo/device.lua
frontend/device/remarkable/device.lua
frontend/device/sony-prstux/device.lua
frontend/ui/network/manager.lua

Spent some time testing #10062 today, and there were a few shortcomings ;).
* `carrier` is set to 1 as soon as the device is *administratively* up (in practice, as soon as we run `ifconfig up`). This is perfectly fine for `isWifiOn`, but absolutely not for `isConnected`, because we are not, actually, connected to *anything*, no attempt at associating has even been made at that point. Besides being semantically wrong, in practice, this will horribly break the connectivity check, because it expects that `isConnected` means we can talk to at least the LAN.
* Delving into the Linux docs reveals that `operstate` looks like a better candidate, as it reflects *operational status*; for Wi-Fi, that means associated and successfully authenticated. That's... closer, but still not it, because we …

NetworkMgr: Refine isConnected check

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/filemanager/filemanagercollection.lua
frontend/apps/filemanager/filemanagerhistory.lua
frontend/apps/filemanager/filemanagerutil.lua
frontend/apps/reader/modules/readerstatus.lua
frontend/ui/elements/common_settings_menu_table.lua
plugins/coverbrowser.koplugin/covermenu.lua
plugins/coverbrowser.koplugin/main.lua
plugins/wallabag.koplugin/main.lua

Closes #8954.
Change is made to file manager, history, and collections alike. Most time-consuming part was understanding the inner workings of coverbrowser to allow compatibility with it.
Lots of code duplication due to historical reasons causes changes to look larger than they are, when it's mostly the same thing copied across the 3 view modules, and coverbrowser further trying to overwrite each separately. The special attention given to coverbrowser is simply because of the special cache it uses...
Ridealong tweaks:
- Remove the "Mark as reading/read" button from File Manager as it's superseded by this
- Add "Reset settings" button to Collections viewer to parallel File Manager and History, and to avoid having the ugly 2-button, 1-button, 2-button layout
- Rename "Sort" button in …

Add file dialog buttons to change book status

---

frontend/datetime.lua
frontend/ui/elements/common_settings_menu_table.lua
plugins/autodim.koplugin/main.lua
plugins/autosuspend.koplugin/main.lua
plugins/autoturn.koplugin/main.lua
plugins/batterystat.koplugin/main.lua
plugins/statistics.koplugin/main.lua
plugins/statistics.koplugin/readerprogress.lua
plugins/systemstat.koplugin/main.lua
spec/unit/datetime_spec.lua

The bare minimum changes to do this as talked about in that other PR. Mostly updating `datetime.secondsToClockDuration()` usages. Updated tests
The name of the hms option is up for debate. "Literal" is the stand-in
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9924)

Spin off hms as selectable time format

---

plugins/exporter.koplugin/template/md.lua

This change will make the ids generated from the headers for TOC more unique in editors and static site generators since it is improbable that one person can make 2 highlights on a page in a second's time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10065)

Added seconds in the markdown export

---

frontend/device/kobo/device.lua

It goes through init, unlike on other models.
Re: #10121
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10122)

Kobo: Mimic Nickel's poweroff behavior on sunxi

---

frontend/apps/reader/modules/readerflipping.lua
frontend/apps/reader/modules/readerrolling.lua
frontend/apps/reader/modules/readerstyletweak.lua
frontend/apps/reader/modules/readerthumbnail.lua
frontend/apps/reader/modules/readerview.lua
frontend/apps/reader/readerui.lua
frontend/document/credocument.lua
frontend/ui/elements/reader_menu_order.lua
frontend/ui/widget/imagewidget.lua
frontend/ui/widget/multiconfirmbox.lua
frontend/ui/widget/touchmenu.lua
plugins/statistics.koplugin/main.lua

Add comments and a new one with `-cr-hint: toc-level1` (that I've been using quite frequently lately for books with no or bad ToC, and had to go find the syntax in our style tweaks).
Also don't propagate tap/hold on disabled menu items.
(When top and bottom menu displayed at the same time, tap on a disabled top menu item could active some bottom toggle change.)
crengine would not create a cache for small documents, which could actually makes re-opening small files slower than big files!
Includes:
- https://github.com/koreader/crengine/pull/506
- Cache: minor simplifications 
- Cache: improve cache file reproducibility
- https://github.com/koreader/crengine/pull/507
- CHM: minor cleanup
- LVStream: minor cleanups
- LVStream: fix and improve `LVZipDecodeStream` implementation
- LVStream: …

ReaderRolling: quicker partial rerenderings with EPUBs

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/filemanager/filemanagercollection.lua
frontend/apps/filemanager/filemanagerhistory.lua
frontend/apps/filemanager/filemanagerutil.lua
frontend/apps/reader/modules/readerstatus.lua
plugins/coverbrowser.koplugin/covermenu.lua
spec/unit/filemanager_spec.lua

(1) Support of the new centralized sdr storage in file operations and other modules (continue of https://github.com/koreader/koreader/pull/10074).
(2) Added unified Delete file dialog (successor of the closed https://github.com/koreader/koreader/pull/10011). Closes https://github.com/koreader/koreader/issues/10001. Closes https://github.com/koreader/koreader/issues/9978.
(3) Added unified "Execute script" file dialog button.
(4) Correct access to DocSettings in `filemanagerutils`.
(5) Minor fixes caused with the new book status buttons in the file popup dialogs in FM, History and Collections (https://github.com/koreader/koreader/pull/9953). Checkmark added (https://github.com/koreader/koreader/pull/9953#issuecomment-1431155936).
(6) Closes https://github.com/koreader/koreader/issues/9952. …

DocSettings: add support of centralized sdr storage

---

frontend/device/generic/device.lua
frontend/device/sdl/device.lua

Some Pocketbook devices (e.g. Lux 4) lack iproute2 binaries, but have net-tools installed instead. Instead of running `ip r` multiple times, try running it and parsing its output directly, falling back to `route -n` if `ip` is not available.
Unfortunately, I can’t pinging itself because apparently on my device `ping` is not suid-root, but having added some debug print to this function I was able to determine that the parsing code works correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8739)

Try route from net-tools if ip from iproute2 is not available

---

frontend/apps/reader/modules/readerhighlight.lua
frontend/apps/reader/readerui.lua

(1) ConfirmBox when saving highlights to pdf now requires button press. Closes https://github.com/koreader/koreader/issues/9328.
(2) Fixed icon in the select mode ConfirmBox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10142)

ReaderHighlight: minor fixes

---

plugins/statistics.koplugin/main.lua

Fix some of my early blunders in using the `N_()` gettext function. Mini-PR from https://github.com/koreader/koreader/pull/9924#discussion_r1104298501 (@Frenzie).
There was also one line for generating this same `%1 (%2 pages)` text that confusingly uses different ordering in the SQL query output; switched the two SELECT arguments around to make it match the other 5 usages. Hope that's not a big deal. Works the same as before
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10146)

ReadingStats: Fix N_() usages, rearrange a SQL select

---

frontend/device/generic/device.lua
frontend/device/sdl/device.lua
frontend/ui/network/manager.lua
frontend/ui/network/networklistener.lua

i.e., we now query routes, interfaces, wireless extensions & ping ourselves, dropping the dependency on specific CLI tools altogether.
Depends on https://github.com/koreader/koreader-base/pull/1584
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10139)

Device: Handle network info data gathering ourselves

---

frontend/apps/reader/readerui.lua
frontend/ui/uimanager.lua

Also restore input if ReaderUI crashed.
Also avoid refresh_count management when "Full refresh rate" is set to "never".
See https://github.com/koreader/koreader/pull/10124#issuecomment-1435557091 and followup posts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10155)

Partial rerendering: really avoid flash on reload

---

frontend/datetime.lua
frontend/ui/elements/common_settings_menu_table.lua
spec/unit/datetime_spec.lua

Implements previous discussion at https://github.com/koreader/koreader/pull/9924#issuecomment-1435166341 by adding spaces between the days, hours, minutes, and seconds (@poire-z). When using the `compact` argument, the spaces will not be used.
In addition, noticed that the "removing leading zeros" contract of the `compact` argument is not met by the Letters format, and leading 0s don't look good anyway with this format (`1h 03m 27s` vs `1h 3m 27s`), so I removed these leading zeros entirely when using this format.
Previously: `1d03h38m`
Now: `1d 3h 38m` normally, `1d3h38m` when compact
Previously: `1d03h38m05s`
Now: `1d 3h 38m 5s` normally, `1d3h38m5s` when compact
Added unit tests, as well as unit tests for the existing `withDays` functionality. Also made the `d` letter for "days" into a …

Add spaces to Letters time format when non-compact, remove lead 0s

---

frontend/apps/reader/readerui.lua
frontend/datetime.lua
frontend/readhistory.lua
frontend/ui/widget/touchmenu.lua
plugins/systemstat.koplugin/main.lua

Updates book access time on closing the document.
Do not use sdr mtime to get the last access time. See https://github.com/koreader/koreader/pull/10149#issuecomment-1438824972
(Minor optimization of calling `secondsToDateTime`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10156)

History: update last book access time

---

plugins/coverbrowser.koplugin/mosaicmenu.lua

Regression introduced in #10140.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10164)

[fix] CoverBrowser: fix calling upvalue crash in MosaicMenu

---

frontend/apps/filemanager/filemanager.lua
frontend/apps/filemanager/filemanagermenu.lua
frontend/docsettings.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua
plugins/docsettingtweak.koplugin/main.lua
spec/unit/readerui_spec.lua

(1) Use `util.removePath` for "dir" sdr folders.
(2) Add menu help text (draft).
(3) Add <kbd>Move book metadata</kbd> button in Filemanager select mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10149)

DocSettings: fix and migration

---

frontend/device/input.lua
frontend/device/remarkable/device.lua

Fix #10012
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10168)

rM: Disable input shenanigans on mainline kernels

---

frontend/ui/elements/screen_notification_menu_table.lua
frontend/ui/widget/notification.lua
frontend/version.lua
reader.lua

This is the successor to #10160
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10178)

  Version log and (limited) notifications log

---

plugins/calibre.koplugin/search.lua

> unimiso
> 
> Looking at lua, %3 seems to be a path list. I think it would be better to put \n before %3.
The path list will start with \n already, but an extra newline won't hurt and this string is really weird (i.e., people will naturally put a space or a newline in front of it).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10172)

[i18n] Improve clarity for translators

---

frontend/apps/filemanager/filemanagermenu.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10174)

[i18n] FileManagerMenu: remove stray newline from metadata location translation

---

plugins/vocabbuilder.koplugin/main.lua

fixes #10194.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10195)

vocabbuilder.koplugin: fix reset word progress bug

---

plugins/coverbrowser.koplugin/main.lua

Not a frequently used feature but is helpful when testing and switching different modes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10188)

Coverbrowser: sync display modes

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/document/credocument.lua
frontend/ui/data/koptoptions.lua
frontend/ui/widget/pagebrowserwidget.lua

Allow for larger margins (which may exhibit other issues that were less noticable with small margins).
See https://github.com/koreader/koreader/issues/4255#issuecomment-1463907821 and next posts for possible caveats with larger margins.
Closes #4255. Closes #7233. Closes #7815.
Includes https://github.com/koreader/crengine/pull/513 :
- Update German hyphenation patterns
- CSS stylesheets cache: also clear it after initial load
- getSurroundingAddedHeight(): use interline_scale_factor
- LVDocView::getNodeByPoint(): tweak again for text selection
- LVDocView::getPageBookmark(): behave as getBookmark()
See https://github.com/koreader/koreader/issues/10193#issuecomment-1464453447.
Closes #10193.
- - - …

More KOpt page margins, bump crengine, toggle bookmarks in PageBrowser

---

frontend/apps/reader/modules/readerstyletweak.lua
frontend/ui/widget/bookmapwidget.lua
frontend/ui/widget/button.lua
frontend/ui/widget/buttondialog.lua
frontend/ui/widget/buttondialogtitle.lua
frontend/ui/widget/buttonprogresswidget.lua
frontend/ui/widget/buttontable.lua
frontend/ui/widget/configdialog.lua
frontend/ui/widget/container/movablecontainer.lua
frontend/ui/widget/frontlightwidget.lua
frontend/ui/widget/numberpickerwidget.lua
frontend/ui/widget/pagebrowserwidget.lua
frontend/ui/widget/skimtowidget.lua
plugins/vocabbuilder.koplugin/main.lua

Easier to review commit by commit.
Fixes some issues noticed at https://github.com/koreader/koreader/pull/9526#issuecomment-1464903837.
Implement ideas discussed at https://github.com/koreader/koreader/issues/10056#issuecomment-1458833625
All our widgets are considering their provided 'width' as the outer width, except Button which considered it as some 'inner width', to which padding/border/margin were added. Let's have them all consistent.
Some other widgets using Button had tweaks to account for that odd behaviour: fix and simplify them.
Also fix Button layout when text is left aligned.
Properly compute Button and separator widths, instead of using magic numbers (which lost their magic over the years :)
Ensure buttons and progress widgets are properly aligned on the sides.
Move the …

Button related tweaks, add menu to Book map and Page browser

---

frontend/apps/filemanager/filemanagerhistory.lua
frontend/apps/filemanager/filemanagerutil.lua
frontend/readhistory.lua

Forgot to disable Book cover and Book description buttons for deleted files:
Minor optimization:
-readhistory: do not store the same callback in each item
-filemanagerutil: the same book info buttons will be used in other modules
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10244)

History: fix book info buttons disable

---

frontend/readhistory.lua

Shame on me. Closes https://github.com/koreader/koreader/issues/10256.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10257)

History: fix clear missing

---

plugins/exporter.koplugin/clip.lua

Fixes #10259
The function `exportAllNotes` in the [main.lua](https://github.com/koreader/koreader/blob/master/plugins/exporter.koplugin/main.lua) file of the `exporter` plugin calls `parseHistory` of the [clip.lua](https://github.com/koreader/koreader/blob/master/plugins/exporter.koplugin/clip.lua) file, line 337.
This function tries to access the `history_dir` using `getHistoryDir` function from the [datastorage.lua](https://github.com/koreader/koreader/blob/master/datastorage.lua) module, which it fails to find.
In the `datastorage` module, you can find this snippet of code, starting at line 60:
```lua
local function initDataDir()
local sub_data_dirs = {
<some folders>
-- "history", -- legacy/obsolete sidecar files
<some other folders>
}
```
Since the folder is sometimes not present, …

Fix: Updated legacy directory, which crashed the program

---

frontend/apps/filemanager/filemanagerbookinfo.lua
frontend/apps/filemanager/filemanagerutil.lua

(1) Added current page lines and words number (based on https://github.com/koreader/koreader/issues/10231#issuecomment-1477138340)
(2) Do not show empty book props (former "N/A")
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10255)

BookInfo: add page information

---

frontend/ui/widget/doublespinwidget.lua
plugins/statistics.koplugin/calendarview.lua
plugins/statistics.koplugin/main.lua

Closes #10250.
Made two commits, one is on the calendar day view and the other the calendar weeks view. The latter is quite ugly because in the sql commands, the offset is inserted in multiple places.
I tried another way with the sqls though, something like:`select *** from (select start_time - offset as start_time, *** from page_stat) as page_stat ***` so the `start_time` is first modified then compared but somehow it doesn't work.
Still, I find it too confusing to just leave it if the two views are out of sync. Maybe there's a better way to do the sqls?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10254)

Statistics.koplugin: Calendar day with custom start time

---

frontend/ui/widget/filechooser.lua

Reported in https://github.com/koreader/koreader/pull/10275#issuecomment-1492955156.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10283)

FileChooser: fix crash on "unreadable content"

---

plugins/exporter.koplugin/base.lua
plugins/exporter.koplugin/clip.lua

Solves #10281
The current implementation of the naming system for single imports automatically uses a fallback to avoid illegal characters.
The fix implements a way to check if the title from the metadata does have illegal characters before using the original filename as a fallback.
I think this was the original intent, as signaled from the comment in the function (see in changes).
This allows for more consistency across the export plugin and uses the original filename only when metadata is missing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10282)

Fix: title from filename is now used only as fallback when exporting

---

frontend/apps/filemanager/filemanager.lua
plugins/gestures.koplugin/defaults.lua

(1) Home folder is marked with a "home" sign
(2) Android: do not show parts of `/storage/emulated/0`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10288)

Folder Menu: sign for Home folder

---

frontend/ui/widget/datetimewidget.lua
frontend/ui/widget/pagebrowserwidget.lua
plugins/statistics.koplugin/calendarview.lua
plugins/statistics.koplugin/main.lua

When using the new option "Daily timeline starts at", make the separator line between 23:00 and 00:00 thicker.
Also tweak time picker to pick minutes by units of 10, and remove max hour (06:00) limitation.
See https://github.com/koreader/koreader/pull/10254#issuecomment-1493073148.
Handle scroll by row or page a bit differently, so we dont constrain and readjust the focus page when reaching book start or end: when later scrolling in the other direction, we'll find exactly the view as it was (this means that we allow a single thumbnail in the view, but it's less confusing this way).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10289)

Calendar view and Page browser tweaks

---

.circleci/config.yml
kodev

run all the tests from the CI
CircleCI use kodev check
This should lead to less redundant scripts
The kodev part works fine, however since the docker relies on the CI scripts to set up the env, it doesn't work so nicely for CircleCi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8682)

Kodev check

---

frontend/ui/widget/filechooser.lua

Closes https://github.com/koreader/koreader/issues/10294.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10296)

FileChooser: fix show files in bold

---

frontend/apps/filemanager/filemanager.lua
frontend/ui/widget/filechooser.lua
plugins/gestures.koplugin/defaults.lua

Also fixes unreadable folder name in root (https://github.com/koreader/koreader/pull/10275#issuecomment-1493404186).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10298)

File browser: show Folder Menu on long-press on Home icon

---

frontend/apps/reader/modules/readercoptlistener.lua
frontend/apps/reader/modules/readerfooter.lua
frontend/ui/uimanager.lua
plugins/autodim.koplugin/main.lua
plugins/autosuspend.koplugin/main.lua
plugins/autoturn.koplugin/main.lua
plugins/autowarmth.koplugin/main.lua

Here I want to optimize the standby behavior, by minimizing the usage of the `onEnterStandby` and `onLeaveStandby` handlers.
The goal is to eliminate most of that handlers and optimize (speed) up the rest.
This can be achieved by just shifting the execution time of scheduled tasks by ` - Device.last_standby_time` (notice the sign, which means they should be executed earlier.) 
So it is not necessary to unschedule related tasks in `onEnterStandby` and reschedule them in `onLeaveStandby`.
The savings in the unschedule part might be smaller than the savings in the rescheduling part. (We will save a table delete and a binary insert in every case.)
As I won't eliminate the `onXXXStandby` events, everything will work as usual. The only difference is, that scheduled tasks will get executed …

Optimize standby event handling

---

frontend/apps/reader/modules/readercoptlistener.lua
frontend/apps/reader/modules/readerkoptlistener.lua
frontend/ui/data/creoptions.lua

Continue of https://github.com/koreader/koreader/pull/10295, discussed at https://github.com/koreader/koreader/pull/10295#issuecomment-1495648088 and further.
cre limits:
https://github.com/koreader/koreader/blob/34c2dab54b479b7f11f898976476bb647497afc4/frontend/apps/reader/modules/readerfont.lua#L263-L264
pdf limits:
https://github.com/koreader/koreader/blob/34c2dab54b479b7f11f898976476bb647497afc4/defaults.lua#L84
https://github.com/koreader/koreader/blob/34c2dab54b479b7f11f898976476bb647497afc4/frontend/ui/data/koptoptions.lua#L366-L369
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10307)

Reader: do not apply line spacing out of range

---

kodev

Currently,  `./kodev check` spits out a lot of warnings on `shfm`. `shfm` is a third-party file.
This PR adds a method to skip certain files from being shellchecked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10344)

Don't use shellcheck on thirdparty scripts

---

plugins/coverbrowser.koplugin/covermenu.lua
plugins/coverbrowser.koplugin/listmenu.lua
plugins/coverbrowser.koplugin/mosaicmenu.lua

Some values of the cache array can be `nil`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10346)

CoverBrowser: fix getting cached info

---

kodev

they are not our problem (we cant fix them here)
regression since #10344
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10362)

kodev check: enforce default submodule.recurse=false for shellcheck & shfmt on submodules

---

plugins/exporter.koplugin/clip.lua

Fixes #10279
The fix makes it so that `parseHistoryFile` uses the stored metadata from the history file to define title and author, instead of the `doc_file` (book) filename.
This makes the results coming form `export all books` and `export current book` the same.
The current solution still keeps the author and title from the filename as fallbacks, but could be removed or changed with some other default (for example, "(Missing author in book's metadata)"), if we want the users to have feedback on missing metadata and have them fix it.
This are the files post-fix (reference before fix in the issue), left is all-books and right is current book export.
The filename still uses the wrong title (grokking instead of Grokking Algorithms), not sure if I should fix it here or in another issue.
- - …

[RFC] Fix: use metadata for author and title when exporting all notes

---

plugins/exporter.koplugin/template/md.lua

Solves #10070 and maybe #10072
The previous version would crash due to author missing in the book's metadata.
```lua
-- line 38
local function prepareBookContent(book, formatting_options, highlight_formatting)
[..........]
content = content .. "##### " .. book.author:gsub("\n", ", ") .. "\n\n"
[.........]
```
Added a conditional that sets the book author to a default `(Author not found in book's metadata)`, so that the user can still have a feedback on missing metadata, while successfully exporting their notes.
The fix works both with export one file and export all files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10278)

Fix: exporting Markdown with missing authors doesn't crash anymore

---

frontend/apps/filemanager/filemanagermenu.lua

Regression from #10198.
Fixes #10368.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10369)

[fix] Reintroduce "Start with" default to prevent nil string on startup

---

frontend/apps/reader/readerui.lua
frontend/dispatcher.lua
frontend/ui/widget/bookmapwidget.lua
frontend/ui/widget/pagebrowserwidget.lua

Closes #10277.
Note: in dispatcher.lua, the action definitions (with separators) and the ordering are in 2 different lists, and their ordering is different, which makes it tedious to properly update and figuring out where to insert/update separators.
Add a top left menu item -/+ to show none, only on the first thumbnail of a row, or on all thumbnails.
Also make the page slot separator longer in the bottom ribbon before pages that start a thumbnails row.
Also show a little spike in the bottom ribbon below page slots that get their page number displayed, to ease figuring out the connection.
Discussed all along #10320. Closes #10320.
- - - …

PageBrowser: show page number alongside thumbnails

---

frontend/device/devicelistener.lua
frontend/device/generic/device.lua
frontend/device/generic/powerd.lua
frontend/device/kobo/device.lua
frontend/device/kobo/powerd.lua
frontend/ui/widget/notification.lua

On my Sage toggling Frontlight on gives a smooth brightness ramp; but toggling it off is a jump in brightness.
This PR fixes that behavioir:
*) Toggling FL on is not changed
*) Toggling FL of does a ramp (with an exponential decay, to make it smooth :) as the observer should like. Anyway not tested on other devices as a Sage). 
More infos are in the comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10305)

Fix frontlight toggle not ramping, but immediately turning off on Sage

---

frontend/apps/reader/modules/readerbookmark.lua
frontend/ui/widget/checkbutton.lua
frontend/ui/widget/confirmbox.lua
frontend/ui/widget/inputdialog.lua
frontend/ui/widget/openwithdialog.lua

In the same way as InputDialog does.
1 widget added
4 widgets added (line, span, 2 checkbuttons)
(Also minor code cleanup)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10364)

ConfirmBox: add widgets

---

frontend/device/kindle/device.lua
spec/unit/device_spec.lua

@NiLuJe as mentioned in the forum post
https://www.mobileread.com/forums/showpost.php?p=4310654&postcount=7
https://github.com/koreader/koreader/pull/9419
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10290)

kindle voyage no framework launch whispertouch button activation

---

frontend/ui/data/dictionaries.lua

Might have got the languages the wrong way around - to be clear, the words are Esperanto and the definitions are in English!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10297)

Add esperanto-english dictionary

---

frontend/device/kindle/device.lua
frontend/device/kindle/powerd.lua
frontend/device/kobo/device.lua
frontend/device/sysfs_light.lua
frontend/ui/elements/common_settings_menu_table.lua
frontend/ui/elements/filemanager_menu_order.lua
frontend/ui/elements/reader_menu_order.lua
frontend/util.lua
spec/unit/device_spec.lua

~~used on kindle but can be extended to other devices~~
Allow disabling the hall efect sensor via the sysfs knob, so the kindle system wont sleep & wake the device
for those of use that stay in koreader, are caseless and get spurious wakeups
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10363)

Kindle: toggle cover events

---

datastorage.lua

This situation might potentially occur in something like a Docker/Podman container or WSL.
Fixes #10380.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10382)

DataStorage: create parent config home if it doesn't exist yet

---

plugins/statistics.koplugin/readerprogress.lua

Closes #10386.
(Just fixing the noticed issue. ReaderProgress layout was and is just heavily bad, but as long as it's not visually noticable - or only in my small emulator - not getting more involved!)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10389)

Statistics: fix ReaderProgress bad layout in RTL UI

---

frontend/apps/reader/modules/readerlink.lua
frontend/dispatcher.lua

This is useful when i want to reference something a few pages away while keeping track of my current page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10387)

Dispatcher: add `addCurrentLocationToStack`

---

frontend/apps/reader/modules/readerview.lua
frontend/ui/elements/page_overlap.lua

Closes https://github.com/koreader/koreader/issues/10394.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10401)

Page overlap: add "Horizontal line" marker

---

plugins/exporter.koplugin/clip.lua

Also avoid double-reading the legacy history (`readhistory` takes care of it).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10407)

Exporter: correct access to doc settings

---

kodev

launch & unistall the correct version
do not rely on setup_env
When paired with wireless debugging, this makes android debugging not such a pain.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10418)

Android: improve kodev run

---

frontend/device/sdl/device.lua

Related to koreader/koreader-base#1610. Not sure if this is actually needed, but for consistency the render buffer's dimensions should be used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10428)

SDL: use render buffer size instead of window size

---

frontend/device/input.lua

It's mostly not used for actual input, but sideband stuff that we don't want to miss.
Fix #10427
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10430)

Input: Leave EV_SDL mostly alone in inhibitInput

---

frontend/ui/widget/naturallightwidget.lua

The backend code makes rather strong assumptions that it'll *always* get a number of of it ;).
Fix #10352
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10425)

NaturalLightWidget: Fallback to previous values instead of `nil` if InputText is empty

---

plugins/exporter.koplugin/main.lua
plugins/exporter.koplugin/target/memos.lua

Add an export method for memos, which originates from [flomo](https://flomoapp.com/) and now has an open-source self-deployment solution:[memos](https://github.com/usememos/memos)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10411)

Exporter: add memos export

---

frontend/apps/reader/modules/readerhighlight.lua

Fix translation for books without "language" in properties (it is "", Translator expects `nil`).
Regression after https://github.com/koreader/koreader/pull/10438.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10451)

ReaderHighlight: fix translation

---

plugins/exporter.koplugin/base.lua
plugins/exporter.koplugin/main.lua

Default is still `koreader/clipboard`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10448)

Exporter: choose folder
