koreader/koreader

- doc/Hacking.md
I couldn't find these for a while
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8901)
> Add location of logs to Hacking document

- frontend/apps/reader/modules/readerlink.lua
- frontend/apps/reader/modules/readerpaging.lua
Requires https://github.com/koreader/koreader-base/pull/1460
Does not support continuous scrolling yet, as ReaderPaging:_gotoPage() does
not seem to be accurate enough.
.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8907)
> Interpret position information from links

- frontend/dbg.lua
- frontend/device/sysfs_light.lua
- frontend/gettext.lua
- frontend/ui/wikipedia.lua
- platform/kindle/koreader.sh
- plugins/exporter.koplugin/clip.lua
- plugins/japanese.koplugin/deinflector.lua
- plugins/statistics.koplugin/main.lua
- plugins/terminal.koplugin/main.lua
Noticed a random leaky fd in one of the USBMS issues logs, decided to double-check the codebase ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8921)
> Minor Lua I/O cleanups

- frontend/readhistory.lua
- plugins/bookshortcuts.koplugin/main.lua
when opening last file for a directory allow searching the history in subfolders also.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8945)
> Book Shortcuts: allow recursively searching folders

- frontend/device/kobo/device.lua
https://github.com/koreader/koreader-base/pull/1472
https://github.com/koreader/koreader-base/pull/1473
https://github.com/koreader/android-luajit-launcher/pull/364
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8962)
> Bump base & android-luajit-launcher

- frontend/ui/widget/inputtext.lua
Fix #8967
Regression since #8859
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8968)
> Make sure InputText has a consistent API, regardless of hasDPad

- .ci/helper_luarocks.sh
Includes:
- https://github.com/koreader/crengine/pull/473 : 
- Fonts: fix hinting with synthesized weight inconsistencies
- Drawing: fix glyphs at top/bottom possibly truncated
- CSS vertical-align set on final blocks should not apply
- Text: correct glyph overlap at text node boundaries
- https://github.com/koreader/crengine/pull/474 : 
- Use #define for keyword color values
- lvdrawbuf: handle text and background colors with alpha
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8972)
> bump crengine: italic correction, alpha colors, fixes

- plugins/autosuspend.koplugin/_meta.lua
- plugins/systemstat.koplugin/main.lua
Easy the life of translators and fixes a stupid string typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8980)
> String and formatting issues

- plugins/terminal.koplugin/main.lua
So we actually have a chance of understanding why it fails to load ;).
(Also, properly require posix FFI stuff, in the unlikely event they aren't already in the main namespace).
Re #8986
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8994)
> Terminal: Make the prerequisites check verbose

- plugins/autosuspend.koplugin/main.lua
- plugins/terminal.koplugin/main.lua
Fix #8986
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/8998)
> Terminal: Make sure devpts is mounted on Kobo

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/ui/translator.lua
- frontend/ui/widget/textviewer.lua
Closes https://github.com/koreader/koreader/issues/9002.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9012)
> Translate: fix crash on save translation to note

- platform/kobo/koreader.sh
* Kill the new font & I18N daemons on startup
* Kill bluetooth radio & power & daemons on startup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9010)
> Kobo: Kill new FW 4.32 stuff on startup

- plugins/wallabag.koplugin/main.lua
Fix <https://github.com/koreader/koreader/issues/8936>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9018)
> [plugin] Wallabag: archive instead of deleting read articles by default

- frontend/device/kindle/device.lua
Work on 5.14.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9054)
> Add warm light controller for Kindle Oasis 3 #3

- frontend/apps/cloudstorage/webdavapi.lua
Closes https://github.com/koreader/koreader/issues/8805. Discussed in https://github.com/koreader/koreader/pull/8806.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9061)
> Cloudstorage WebDAV: fix leading slash for root folder

- frontend/device/generic/device.lua
Thanks to @hius07
(https://github.com/koreader/koreader/issues/7881#issuecomment-1028921755)
;).
Fix #7881
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9073)
> Kindle: Fix retrieveNetworkInfo on the K4

- doc/Unit_tests.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9078)
> [doc] Update busted version mentioned in docs

- frontend/gettext.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9080)
> [chore] Remove leftover debug print

- plugins/calibre.koplugin/metadata.lua
Follow up https://github.com/koreader/koreader/pull/8999
Fixes https://github.com/koreader/koreader/issues/9085
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9086)
> fix: attempt to call local start_time (number)

- frontend/apps/reader/modules/readerview.lua
- frontend/dispatcher.lua
- frontend/ui/elements/page_turns.lua
xref: https://www.mobileread.com/forums/showthread.php?p=4224443&postcount=1119
(not tested on device)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9123)
> Page turn animations: add to dispatcher

- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/device/input.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/confirmbox.lua
- frontend/ui/widget/infomessage.lua
Fixes #9043
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9065)
> merge `discardEvents` & `inhibitInput`

- plugins/exporter.koplugin/base.lua
Fixes #9127
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9130)
> Fix export file disappearance in some devices

- frontend/device/gesturedetector.lua
- frontend/device/input.lua
- frontend/ui/uimanager.lua
This should address the issues raised there post-merge ;).
Re #9065 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9139)
> Minor Input:inhibitInput followup to #9065

- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
As suggested in https://github.com/koreader/koreader/pull/9028#issuecomment-1143736619
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9158)
> AutoDim: move menu position

- plugins/exporter.koplugin/main.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9167)
> Fixes Infomessage error on remote

- plugins/exporter.koplugin/target/json.lua
This PR implements RapidJSON encoding and an optional pretty output for highlight export and share.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9165)
> Pretty JSON export

- plugins/autosuspend.koplugin/main.lua
Simplify autosuspend after #9055
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9146)
> [plugin, autosuspend] Clean up after #9055

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readersearch.lua
- frontend/device/kobo/nickel_conf.lua
- frontend/document/credocument.lua
- frontend/document/koptinterface.lua
- frontend/dump.lua
- frontend/gettext.lua
- frontend/ui/elements/screen_dpi_menu_table.lua
- frontend/ui/renderimage.lua
- plugins/kosync.koplugin/main.lua
- spec/unit/readerrolling_spec.lua
Re: https://github.com/koreader/koreader-base/pull/1487
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9174)
> Make luacheck >= 0.26 happy

- frontend/ui/screensaver.lua
- frontend/ui/uimanager.lua
- plugins/autosuspend.koplugin/main.lua
ScreenSaver: Possibly avoid crashes in folder mode on devices that might have been used on macOS.
UIManager: Simplify the mechanism added in #9173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9200)
> A couple of minor tweaks

- plugins/exporter.koplugin/target/joplin.lua
https://github.com/koreader/koreader/issues/9197#issuecomment-1153129147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9203)
> exporter: fix crash on joplin when token is invalid

- .ci/after_success_docs_translation.sh
With reference to https://github.com/koreader/koreader/pull/9193#issuecomment-1153128485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9204)
> [CI] Don't hide docs generation log

- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/screensaverwidget.lua
- plugins/autodim.koplugin/main.lua
Don't draw footer over bottom menu, screensaver, keyboard ...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9192)
> AutoDim: Don't update footer if not necessary

- plugins/autodim.koplugin/main.lua
If the front light is off, don't activate AutoDim (especially don't show TrapWidget to swallow the first tap).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9217)
> AutoDim: No dim if frontlight is off

- plugins/vocabbuilder.koplugin/main.lua
This pr resolves #9231. @Frenzie :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9233)
> vocabbuilder.koplugin: Remove space from translatable string

- plugins/exporter.koplugin/clip.lua
Fixes #9253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9255)
> Exporter getTitle Fix fix

- frontend/device/sdl/device.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9280)
> SDL: set WM_CLASS on Wayland/X11

- plugins/coverimage.koplugin/main.lua
This PR fixes #9299
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9301)
> CoverImage: fix translatable

- plugins/autodim.koplugin/main.lua
This should fix #9303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9315)
> AutoDim: fix timing problems with standby

- plugins/autowarmth.koplugin/main.lua
Show changes from menu immediately in footer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9325)
> AutoWarmth: show menu selection immediately in footer

- frontend/device/pocketbook/device.lua
This will start KOReader on (my) Pocketbook.
KOReader [crash.log](https://github.com/koreader/koreader/files/9173731/crash.log)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9365)
> Add PocketBook Era (PB700)

- frontend/ui/widget/sortwidget.lua
- plugins/vocabbuilder.koplugin/db.lua
- plugins/vocabbuilder.koplugin/main.lua
Always show more button instead of delete regardless of review count per #9383.
Adds book filtering per #9256 (from menu or by swiping up).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9393)
> vocabbuilder.koplugin: always show more button, add book filtering

- plugins/autowarmth.koplugin/main.lua
This fixes a potential crash in AutoWarmth (allthough I am not able to trigger it willingly).
Maybe this also fixes https://github.com/koreader/koreader/issues/9409#issuecomment-1205818414.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9411)
> [plugin] Fix crash in AutoWarmth

- frontend/device/input.lua
- frontend/device/kindle/device.lua
Minor stuff I forgot when reviewing #9377 ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9441)
> Input: Minor comment tweaks

- frontend/device/input.lua
Fixes #9439.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9443)
> [fix, SDL] Remove useless Device call from exit

- frontend/device/input.lua
Regression since #9377
Fix #9444
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9445)
> Input: Unbreak event handling on strict protocol B devices

- frontend/ui/data/onetime_migration.lua
- plugins/opds.koplugin/opdsbrowser.lua
The URLs for the Standard Ebooks OPDS feeds have changed. This PR updates them to the new URLs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9371)
> Update Standard Ebooks OPDS URLs to new URL

- .luacheckrc
- frontend/device/kobo/device.lua
Resurgence of #2128 since #9465 & friends.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9473)
> Kobo: Unbreak touch input on fresh setups on Trilogy

- Makefile
Depends on https://github.com/koreader/koreader-base/pull/1513
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9470)
> Ship the STL if need be

- frontend/device/input.lua
Followup to #9474
I was afraid that ABS_PRESSURE could be sent out of order, but that
appears to never be the case, so we can simplify the code a bit :}.
c.f., https://github.com/baskerville/plato/commit/8466f687efe7d950bb6a7e2ac71f2cda7a22c48f
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9481)
> Input: Minor simplification for the Mk. 3 input quirk

- frontend/ui/widget/textboxwidget.lua
Thanks https://github.com/koreader/koreader/pull/9507#issuecomment-1245987998.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9516)
> TextViewer: fix bug in TextBoxWidget after #9507

- frontend/device/android/device.lua
This PR adds button mapping for Tolinos
fixes #9175
closes #9503
~~requires https://github.com/koreader/android-luajit-launcher/pull/381~~
requires https://github.com/koreader/android-luajit-launcher/pull/383
This PR is the result of https://github.com/koreader/koreader/pull/9503#issuecomment-1242992368
Note: i did not change to original PR because that was with a different intend, also tried to add some warmth settings (but i could not get that to work and i dont know how to use JNI to implement it)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9509)
> feat(device/android/device): add custom mapping for tolino buttons

- plugins/autowarmth.koplugin/main.lua
Nit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9525)
> AutoWarmth: nit

- frontend/apps/cloudstorage/webdavapi.lua
- frontend/apps/reader/modules/readerdictionary.lua
- frontend/ui/otamanager.lua
- frontend/ui/translator.lua
- frontend/ui/wikipedia.lua
- plugins/exporter.koplugin/target/readwise.lua
- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
- plugins/newsdownloader.koplugin/internaldownloadbackend.lua
- plugins/newsdownloader.koplugin/luahttpdownloadbackend.lua
- plugins/opds.koplugin/opdsbrowser.lua
- plugins/wallabag.koplugin/main.lua
Should hopefully help avoid playing twenty questions as long as we get debug logs...
May include minor localized drive-by linting ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9523)
> Unify error logging on network errors

- frontend/ui/widget/button.lua
- frontend/ui/widget/buttondialogtitle.lua
- frontend/ui/widget/buttontable.lua
- plugins/profiles.koplugin/main.lua
Description and sreenshots in https://github.com/koreader/koreader/issues/8701#issuecomment-1249608740. Closes https://github.com/koreader/koreader/issues/8701.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9526)
> Profiles: add QuickMenu

- frontend/document/doccache.lua
Regression since #9529
Fix #9565
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9566)
> DocCache: Unbreak on !Linux platforms

- frontend/ui/widget/infomessage.lua
Small fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9577)
> Documentation: Fix doc of infomessage

- frontend/ui/data/keyboardlayouts/zh_ime.lua
- frontend/ui/widget/dictquicklookup.lua
- plugins/vocabbuilder.koplugin/db.lua
- plugins/vocabbuilder.koplugin/main.lua
This PR makes the following changes:
- allowing users to opt to add words manually to the vocabulary builder per #9486
- due time for review will be based on the streak count of GOT IT's than review count
- minor update of the zh_keyboard character deletion logic
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9582)
> vocabbuilder.koplugin: allow manually adding new words

- frontend/apps/reader/modules/readerdevicestatus.lua
- frontend/apps/reader/modules/readertypography.lua
- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/doublespinwidget.lua
- plugins/statistics.koplugin/main.lua
Thanks https://github.com/koreader/koreader/pull/9558#issuecomment-1264447739.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9580)
> ConfigDialog: fix bug in DoubleSpinWidget default values

- frontend/dispatcher.lua
Fixes: #9594
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9597)
> Dispatcher: QuickMenu: Fix footgun

- frontend/apps/cloudstorage/dropbox.lua
- frontend/apps/cloudstorage/ftp.lua
- frontend/apps/cloudstorage/webdav.lua
- frontend/apps/filemanager/filemanagersetdefaults.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/luadefaults.lua
- frontend/persist.lua
- frontend/ui/widget/multiinputdialog.lua
- plugins/opds.koplugin/opdsbrowser.lua
- plugins/perceptionexpander.koplugin/main.lua
- plugins/terminal.koplugin/aliases.lua
- plugins/wallabag.koplugin/main.lua
- spec/unit/inputtext_spec.lua
- spec/unit/persist_spec.lua
Stupid oversight is stupid ;o).
Also, simplify LuaDefaults defaults.lua shenanigans, this should match the old require("defaults") behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9598)
> Persist: Fix serialize for serpent

- frontend/util.lua
Since we've been playing with those the last few days, having a reference to a basic implementation for plain arrays doesn't sound entirely unhelpful ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9614)
> util: Add a set of binary searches implementation

- frontend/ui/uimanager.lua
- frontend/ui/widget/notification.lua
(HB & SDL2)
And fix an oversight in #9617 :s.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9618)
> Bump base (https://github.com/koreader/koreader-base/pull/1534)

- frontend/ui/uimanager.lua
- spec/unit/uimanager_bench.lua
- spec/unit/uimanager_spec.lua
This change speeds up the binary insert by 10%.
Some additional tests have to be done (for `tickAfterNext` and `nextTick`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9600)
> UIManager: Optimize binary insert

- .luacheckrc
- doc/Events.md
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readerthumbnail.lua
- frontend/dbg.lua
- frontend/device/pocketbook/device.lua
- frontend/logger.lua
- frontend/ui/data/keyboardlayouts/ja_keyboard.lua
- frontend/ui/event.lua
- frontend/ui/trapper.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/eventlistener.lua
- frontend/util.lua
- plugins/japanese.koplugin/deinflector.lua
- plugins/opds.koplugin/opdsbrowser.lua
* Iterate over varargs directly via select if possible
* Use table.pack otherwise (requires https://github.com/koreader/koreader-base/pull/1535).
* This allows us to simplify a few Logger calls, as logger now handles nil values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9624)
> Cleanup various varargs shenanigans

- plugins/exporter.koplugin/target/json.lua
- This allows interoperability between different readers who want to import highlights on different devices/file systems. All that is needed then to import highlights is to match the local books and their path based on the checksum.
- I needed this to import highlights on sioyek book reader from koreader, I use koreader on tablets and sioyek on my laptop.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9610)
> add md5 checksum of the file while exporting highlights

- spec/unit/uimanager_bench.lua
Follow up to #9600.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9629)
> UnitTests: Nits and misspellings 

- plugins/autostandby.koplugin/main.lua
String "Update" is not available for translation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9655)
> Change of string "Update" to be translatable

- frontend/ui/data/keyboardlayouts/zh_keyboard.lua
This is a follow up to #9589.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9633)
> zh_keyboard: fix misspelling

- frontend/ui/widget/configdialog.lua
Closes https://github.com/koreader/koreader/issues/9661.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9662)
> ConfigDialog: fix bug with default values

- frontend/ui/widget/configdialog.lua
Closes https://github.com/koreader/koreader/issues/9665.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9666)
> ConfigDialog: fix bug with default values 2

- frontend/ui/widget/textviewer.lua
See https://github.com/koreader/koreader/pull/9507#issuecomment-1285106670
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9668)
> TextViewer: correct keyboard layout after long-press on Find

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/document/credocument.lua
- frontend/document/djvudocument.lua
- frontend/document/koptinterface.lua
- frontend/document/pdfdocument.lua
- plugins/vocabbuilder.koplugin/main.lua
This PR adds support for extracting context of looked-up words from some pdf files for the vocabulary builder plugin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9622)
> vocabbuilder.koplugin: support extracting context from pdfs

- plugins/vocabbuilder.koplugin/db.lua
- plugins/vocabbuilder.koplugin/main.lua
This PR makes it possible to open the plugin by taps or gestures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9634)
> vocabbuilder.koplugin: support adding to tap gesture menu

- frontend/ui/data/keyboardlayouts/keypopup/sk_popup.lua
- frontend/ui/data/keyboardlayouts/sk_keyboard.lua
- frontend/ui/widget/virtualkeyboard.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9656)
> Add Slovak virtual keyboard

- frontend/ui/widget/buttondialog.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9505)
> Add documentation to ButtonDialog

- plugins/exporter.koplugin/base.lua
- plugins/exporter.koplugin/target/html.lua
- plugins/exporter.koplugin/target/json.lua
- plugins/exporter.koplugin/target/markdown.lua
- plugins/exporter.koplugin/target/text.lua
Untested.
Pinging @uroybd: https://github.com/koreader/koreader/pull/9153#issuecomment-1143857139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9194)
> exporter.koplugin: send the right mimetype when sharing text.

- plugins/opds.koplugin/opdsbrowser.lua
This is a new PR from https://github.com/koreader/koreader/pull/9664, I messed up and didnt put the changes on a new branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9681)
> Re-Do: New Feature, Stream from Page

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/device/devicelistener.lua
- frontend/device/wakeupmgr.lua
- frontend/ui/uimanager.lua
This PR implements two different things:
1. commit: Optimize UIManager by
- hiding some `logger.dbg` behind `dbg.is_on`. This saves evaluation of the `logger.dbg` arguments, (Power)
- minor refactoring of some logic, (Readability) and
- despaghettify some code (Readability).
2. commit: Replace some wrapper functions with aliases (but only if the wrapped method can not be overloaded). This is for minimi powersavings.
The PR should 
* simplify and improve the readability of the code
* improve power saving (when debugging is off).
Dunno if this PR is desired. If not, pleas close.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9657)
> Random optimizations

- plugins/opds.koplugin/main.lua
- plugins/opds.koplugin/opdsbrowser.lua
- plugins/opds.koplugin/opdsparser.lua
- spec/unit/opds_spec.lua
Refactoring:
-removed duplicated code
-removed passing of username/password through all the modules
-logical order of the methods
-some optimizing and drying
-comments
New features:
-subcatalog link can be saved to the list of servers (eg: direct link to the catalog of books by an author)
-more book information can be fetched and shown (<kbd>Book information</kbd>)
-fixed access to the Standard library (by @KGKopli, closes https://github.com/koreader/koreader/issues/9372)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9703)
> OPDSbrowser refactoring

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerrolling.lua
regression in #9691 https://github.com/koreader/koreader/commit/b523c2e8b9354825c1b0d09a89946dff9c2d105d
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9710)
> ges_events must be a table

- defaults.lua
- frontend/ui/widget/bookmapwidget.lua
- frontend/ui/widget/bookstatuswidget.lua
- frontend/ui/widget/progresswidget.lua
- plugins/statistics.koplugin/calendarview.lua
- plugins/statistics.koplugin/readerprogress.lua
Depends on https://github.com/koreader/koreader-base/pull/1548
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9716)
> Cleanup: Track color constant name change

- plugins/opds.koplugin/opdsbrowser.lua
Fix https://github.com/koreader/koreader/pull/9703#issuecomment-1296425411.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9718)
> OPDSbrowser: fix uninitialized calibre

- plugins/calibre.koplugin/metadata.lua
Fixes #9722
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9725)
> calibre metadata: prevent duplicates

- frontend/apps/cloudstorage/webdavapi.lua
- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readerback.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerconfig.lua
- frontend/apps/reader/modules/readerfont.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerlink.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerpanning.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readerrotation.lua
- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/apps/reader/modules/readerzooming.lua
- frontend/apps/reader/readerui.lua
- frontend/device/input.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/container/inputcontainer.lua
- frontend/ui/widget/focusmanager.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/touchmenu.lua
- plugins/externalkeyboard.koplugin/event_map_keyboard.lua
- plugins/externalkeyboard.koplugin/find-keyboard.lua
- plugins/externalkeyboard.koplugin/main.lua
Mostly centered around ExternalKeyboard ;).
Namely, navigation now works as expected in the FM & Reader.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9717)
> Another round of tweaks

- plugins/autowarmth.koplugin/main.lua
This shall fix #9721 as well as a bug on sanitizing fixed scheduler times entering (namely to check true midnight time is after astronomic dawn).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9730)
> AutoWarmth: Fix frontlight flash after resume and weird true midnight settings

- frontend/ui/widget/radiobuttontable.lua
- frontend/ui/widget/radiobuttonwidget.lua
Document the widget
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9733)
> [doc] RadioButtonWidget

- frontend/device/devicelistener.lua
- plugins/autowarmth.koplugin/main.lua
This should fix #9728.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9735)
> AutoWarmth: fix frontlight toggle during day

- plugins/exporter.koplugin/main.lua
Fixes #9740
thanks to @hius07 for the hint!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9753)
> exporter: prevent exporting documents when they're not open

- frontend/device/devicelistener.lua
This should fix #9741.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9759)
> Fix regression (introduced in #9657)

- plugins/autowarmth.koplugin/main.lua
On cloudy autumn-evenings the light might be too dark to read without frontlight.
This PR adds an offset to the toggling time, so that the fl might be toggled some time before sunset or after sunrise.
Wordings are welcomed.
Draft by now, as this will need some more testing. (Easy-mode, expert-mode, user fl toggle, sleep and resume ...)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9755)
> AutoWarmth: add a time offset for toggling frontlight on/off

- frontend/apps/cloudstorage/cloudstorage.lua
- frontend/apps/cloudstorage/dropbox.lua
Will help to https://www.mobileread.com/forums/showpost.php?p=4274650&postcount=9.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9821)
> CloudStorage: add DropBox starting folder

- plugins/calibre.koplugin/search.lua
Fixes https://github.com/koreader/koreader/issues/9836
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9837)
> calibre: fix attempt to index path_entry

- frontend/apps/filemanager/filemanagermenu.lua
Reported in <https://www.mobileread.com/forums/showthread.php?p=4276962#post4276962>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9841)
> [i18n] Fix 'Choose new folder to set as home?' can't be translated

- frontend/dispatcher.lua
Closes #9838
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9842)
> Dispatcher: only suspend if Device:canSuspend

- plugins/coverimage.koplugin/main.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9839)
> unified call method

- plugins/autowarmth.koplugin/main.lua
Simplify the schedulings, optimize a bit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9788)
> [plugins] AutoWarmth optimize schedulings

- .github/workflows/build.yml
Reverts koreader/koreader#9856
See #9863. It doesn't seem to actually work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9864)
> Revert "[CI] Set macOS Github Action to macOS 12.00"

- plugins/readtimer.koplugin/main.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9844)
> when readtimer interval end, you can Again.

- frontend/apps/filemanager/filemanagermenu.lua
- plugins/opds.koplugin/opdsbrowser.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9878)
> [i18n] Add a couple of explanatory comments for translators

- plugins/vocabbuilder.koplugin/db.lua
- plugins/vocabbuilder.koplugin/main.lua
This PR adds the ability to search words from the vocab builder plugin.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9881)
> Vocabbuilder.koplugin: add search ability

- plugins/externalkeyboard.koplugin/main.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9890)
> [i18n] Remove stray newline from ExternalKeyboard string

- frontend/apps/reader/modules/readerstatus.lua
- frontend/dispatcher.lua
Action in Dispatcher.
Closes https://www.mobileread.com/forums/showthread.php?t=350683.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9916)
> Reader: open next file in folder

- platform/appimage/koreader.appdata.xml
- license: use SPDX license identifier: https://spdx.org/licenses/
- content rating: add OARS content rating: https://hughsie.github.io/oars/generate.html (required by flathub: https://github.com/flathub/flathub/wiki/AppData-Guidelines#oars-information)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9929)
> make appdata standard compliant

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
- plugins/statistics.koplugin/main.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9928)
> Statistics: show correct number of notes in a book

- frontend/device/generic/device.lua
See <https://www.mobileread.com/forums/showthread.php?p=4282773#post4282773>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9933)
> [i18n] Make gateway strings translateable

- platform/appimage/koreader.appdata.xml
Changed according to
- https://github.com/flathub/flathub/pull/3724#discussion_r1051620485
- https://github.com/flathub/flathub/pull/3724#discussion_r1052666720
- https://github.com/flathub/flathub/pull/3724#discussion_r1052667447
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9940)
> better compliance with appstream data standard

- frontend/apps/reader/modules/readerfooter.lua
- plugins/systemstat.koplugin/main.lua
This should fix #9942
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9945)
> Make translateable: SystemStat, custom footer

- frontend/ui/widget/keyvaluepage.lua
Fixes #9972.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9974)
> KVPage: fix crash from empty page due to item deletion

- frontend/apps/reader/modules/readerconfig.lua
This should solve item 2 in #9979
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9983)
> [footer] Fix footer auto refresh and bottom menu 

- frontend/readhistory.lua
Removed unused and duplicates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/9991)
> ReadHistory: further minor refactoring

- frontend/ui/language.lua
Cf. <https://github.com/koreader/koreader/discussions/10016>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10017)
> [i18n] Enable Farsi

- frontend/device/kobo/device.lua
Just some mistakes I noticed in the comments...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10038)
> Minor comments update and cosmetic

- plugins/profiles.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/8590.
Closes https://github.com/koreader/koreader/issues/10015.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10036)
> Profiles: create profile with current document settings

- frontend/ui/otamanager.lua
Re: https://github.com/koreader/koreader/pull/4539#issuecomment-1411707712
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10068)
> OTAManager: Pick the right binaries on Kindles running on the Bellatrix platform

- frontend/dispatcher.lua
Applicable for `Set font` and `Set highlight action` actions.
Closes https://github.com/koreader/koreader/issues/10077.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10080)
> Dispatcher: fix dynamically built menu

- platform/appimage/koreader.appdata.xml
- add developer name (can be shown on flathub.org)
- set `Translate` link to the Weblate page rather than the ambiguous `README.md`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10094)
> improve appstream metadata

- frontend/ui/screensaver.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10105)
> Screensaver: correct access to doc settings

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10004)
> Update supported format list with missing items

- plugins/externalkeyboard.koplugin/_meta.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10081)
> ExternalKeyboard: make metadata capitalization abide by styleguide

- frontend/util.lua
The previous iteration, besides failing to handle leaf-only input, was relying on splitFilePathName, which just doesn't do what's required to incrementally build the directory tree the right way around ;).
This should more closely match mkdir -p, i.e., it will *fail* if any part (or all of it) of the path exists but is *not* a directory.
Re #10074
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10111)
> util: Rewrite makePath

- frontend/ui/widget/filechooser.lua
Fixed: when sorting by type, the files of the same type are now sorted by name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10091)
> filechooser: optimize some sorting functions

- frontend/apps/reader/modules/readerbookmark.lua
Closes https://github.com/koreader/koreader/issues/10108.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10109)
> ReaderBookmark: fix comparing positions

- plugins/calibre.koplugin/main.lua
- plugins/calibre.koplugin/metadata.lua
- plugins/calibre.koplugin/search.lua
c.f., https://www.mobileread.com/forums/showthread.php?t=352142
This adds dedicated "browse by" buttons for authors & tags, and adds series & tags to the search settings for the meta "Search books" button.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10113)
> Calibre: Allow authors/title metadata browse/searches

- plugins/coverbrowser.koplugin/listmenu.lua
Self-explained
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10119)
> ListMenu: correct access to doc settings

- plugins/autowarmth.koplugin/main.lua
- plugins/autowarmth.koplugin/suntime.lua
This PR fixes a bug with daylight saving time _on the day_ of the summer-time-change and bumps `suntime.lua` to the current version).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10125)
> [AutoWarmth] Recalculate timezone

- frontend/device/kindle/device.lua
regression since #8856
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10131)
> fix broken escaping

- frontend/util.lua
Will attempt to prune empty directories from the given path, going as far back up as possible.
Re: #10074
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10129)
> util: Add removePath

- frontend/device/generic/device.lua
- frontend/ui/data/dictionaries.lua
Followups to #8739 & a "fix" for #10134 (I don't recall how we're supposed to handle HTTP -> HTTPS redirects the "right" way).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10135)
> A bunch of trivial tweaks

- plugins/coverbrowser.koplugin/covermenu.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
Self-explainable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10140)
> MosaicMenu: correct access to doc settings

- plugins/wallabag.koplugin/main.lua
Self-explainable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10147)
> Wallabag: fix doc settings

- frontend/device/generic/device.lua
Don't blow up if we fall back to exec'ing ping
Fix https://github.com/koreader/koreader/pull/10139#issuecomment-1437678458
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10151)
> Hotfix followup to #10139

- plugins/movetoarchive.koplugin/main.lua
Self-explainable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10152)
> MoveToArchive: fix DocSettings

- plugins/exporter.koplugin/main.lua
Fixes #9231.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10159)
> [i18n, plugin] Exporter: fix some incorrect uses of translation

- frontend/apps/reader/modules/readerpagemap.lua
- frontend/apps/reader/modules/readerstatus.lua
- frontend/ui/elements/common_settings_menu_table.lua
- plugins/autofrontlight.koplugin/main.lua
- plugins/keepalive.koplugin/main.lua
Minor fixes to menu and dialogs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10165)
> UX: a set of minor fixes

- frontend/apps/reader/modules/readerfooter.lua
Noticed that something was wonky during my train ride ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10167)
> ReaderFooter: Don't reset session marker on standby

- frontend/ui/widget/button.lua
Just display its ref.
Re: https://github.com/koreader/koreader/pull/7166#issuecomment-1445177124
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10171)
> Button: don't dump the widget in a debug print

- frontend/ui/widget/filechooser.lua
(1) Fix sorting folders when `collate` is "type", "size", "percentage": folders are sorted by name now.
(2) Fix getting next file in folder when `collate` is "mixed files and folders": returned `nil` when next item was a folder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10176)
> FileChooser: fixes

- frontend/ui/widget/bookstatuswidget.lua
In accordance with the new file dialog status buttons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10179)
> BookStatusWidget: relocate status toggle buttons

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- plugins/coverbrowser.koplugin/covermenu.lua
Add <kbd>Book cover</kbd> and <kbd>Book description</kbd> buttons (that existed in non-classic modes).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10185)
> Classic display mode: add popup file dialog buttons

- frontend/apps/reader/modules/readerflipping.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/dispatcher.lua
- resources/icons/mdlight/bookmark.svg
(1) Change indicator to "bookmark" icon without dogear.
(2) Add toggling with a gesture.
Discussed in https://github.com/koreader/koreader/issues/10192. Closes https://github.com/koreader/koreader/issues/10192.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10196)
> Bookmark flipping mode fix

- frontend/apps/reader/modules/readerstyletweak.lua
Fixes https://github.com/koreader/koreader/issues/10243#issuecomment-1483909915.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10247)
> Style tweaks: update profiles on unregistering in Dispatcher

- frontend/apps/reader/modules/readerzooming.lua
- frontend/dispatcher.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10269)
> Dispatcher: use translated labels for Zoom Mode actions

- frontend/dispatcher.lua
Closes https://github.com/koreader/koreader/issues/10270.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10271)
> Dispatcher: translate QuickMenu title

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagerutil.lua
- frontend/readcollection.lua
- frontend/ui/widget/buttontable.lua
To go up to parent folders.
Home folder abbreviated
Home folder abbreviated and locked
Long folder name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10275)
> File browser: add Folder Menu

- plugins/statistics.koplugin/main.lua
Added the sync book statistics action to dispatcher, along with InfoMessage shown during sync.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10285)
> Sync book statistics: add to dispatcher

- frontend/apps/reader/modules/readerbookmark.lua
Closes https://github.com/koreader/koreader/issues/10284.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10287)
> ReaderBookmark: do not write pdf annotation for page bookmarks

- plugins/coverbrowser.koplugin/covermenu.lua
- plugins/coverbrowser.koplugin/listmenu.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10276)
> ListMenu: show mark for books with highlights

- frontend/apps/reader/modules/readercoptlistener.lua
- frontend/apps/reader/modules/readerkoptlistener.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/document/pdfdocument.lua
- frontend/ui/data/creoptions.lua
Closes https://github.com/koreader/koreader/issues/10286.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10295)
> Reader: do not apply font size out of range

- plugins/SSH.koplugin/main.lua
See #9812.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10300)
> SSH.koplugin: fix cant stop SSH server bug when pid file's stale

- plugins/statistics.koplugin/calendarview.lua
- plugins/statistics.koplugin/main.lua
Continuing https://github.com/koreader/koreader/pull/10254#issuecomment-1494697269
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10299)
> Statistic.koplugin: fix today's timeline showing next day when within custom offset

- frontend/apps/filemanager/filemanagerutil.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerthumbnail.lua
For Page browser.
Also minor cleaning of ReaderBookmark.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10303)
> ReaderThumbnails: update cached page thumbnail on bookmark note change

- frontend/apps/filemanager/filemanagerbookinfo.lua
Closes https://github.com/koreader/koreader/issues/10314.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10315)
> BookInfo: fix crash on show cover

- doc/Events.md
- frontend/dbg.lua
- frontend/ui/trapper.lua
- frontend/ui/uimanager.lua
- frontend/ui/widget/eventlistener.lua
c.f., https://github.com/koreader/koreader-base/pull/1603 for more details.
Re: #9624
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10350)
> Deal with table.pack corner-cases properly

- frontend/ui/widget/keyvaluepage.lua
Corner(or edge?) case: https://github.com/koreader/koreader/pull/9672#issuecomment-1494867499
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10326)
> keyvaluepage: fix corner-case alignment bug

- frontend/ui/data/koptoptions.lua
Regression from https://github.com/koreader/koreader/pull/10208.
Closes https://github.com/koreader/koreader/issues/10373.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10376)
> koptoptions: fix default margin

- frontend/ui/widget/filechooser.lua
Regression after https://github.com/koreader/koreader/pull/10329.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10393)
> FileChooser: fix percent sorting

- plugins/exporter.koplugin/target/my_clippings.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10400)
> [plugin] Exporter: avoid passing newlines to translators

- frontend/apps/reader/modules/readerlink.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10399)
> ReaderLink: fix capitalization typo in "Go Forward"

- kodev
Was helpful when testing https://github.com/koreader/android-luajit-launcher/pull/415 ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10431)
> kodev: Catch TAG_SURFACE in the debug logcat filter

- frontend/ui/data/onetime_migration.lua
That could lead to an attempt to load an old fontlist cache in an incompatible format...
Re: #9771
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10429)
> OTM: Attempt to deal with wonky config states

- plugins/exporter.koplugin/main.lua
Fix ldoc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10464)
> Exporter: comment

- plugins/exporter.koplugin/main.lua
Follow-up to <https://github.com/koreader/koreader/pull/10464>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10465)
> [doc, plugin] Exporter: manually specify module name

- frontend/apps/filemanager/filemanagercollection.lua
Closes https://github.com/koreader/koreader/issues/10470.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10472)
> FileManagerCollection: fix Crash on "Execute shell script"

- frontend/util.lua
See https://github.com/koreader/koreader/issues/10485#issuecomment-1563875642 for details.
Fixes #10485.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10490)
> Work around LD_PRELOAD error on reMarkable 2 devices

- plugins/statistics.koplugin/main.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10498)
> Sync the `last_open` field in Reading Statistics

- frontend/ui/widget/bookmapwidget.lua
See https://github.com/koreader/koreader/pull/10530#discussion_r1217635869.
@Frenzie: please have a look at the new strings appearing in weblate, that I didn't miss/mess anything else :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10544)
> BookMap: fix help text wording

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
Fetching drawers from the highlights turned out to be rather fast, so I think this can be implemented.
Closes https://github.com/koreader/koreader/issues/10189. Closes https://github.com/koreader/koreader/issues/10543. @benasocj @atrate
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10549)
> Bookmarks: filter by highlight style

- frontend/apps/filemanager/filemanagerbookinfo.lua
- plugins/coverimage.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/10546.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10553)
> CoverImage: custom cover support

- plugins/autowarmth.koplugin/main.lua
This should fix #10491.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10556)
> [AutoWarmth] Fix nightmode issue on non natural light devices

- frontend/ui/widget/imageviewer.lua
- plugins/opds.koplugin/opdsbrowser.lua
(1) New "Book cover" button in the download dialog.
(2) Detect book that can be borrowed only (Internet Archive).
There is no support for borrowing, just showing a disabled button.
(3) Fixed some libraries, all of them work except Gallica.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10555)
> OPDS: view book cover

- frontend/device/kindle/device.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10569)
> kindle: fix require error trace

- frontend/persist.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10568)
> persist: fix possible leak on error

- frontend/ui/widget/htmlboxwidget.lua
thanks @poire-z 
Closes: #10565
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10574)
> HtmlboxWidget: pairs->ipairs

- frontend/document/credocument.lua
Used by Flibusta.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10575)
> OPDS: epub alternative mimetype

- frontend/apps/reader/modules/readerpaging.lua
- frontend/apps/reader/modules/readerview.lua
Closes https://github.com/koreader/koreader/issues/10573.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10576)
> Overlap: fix detecting reflow mode

- frontend/device/pocketbook/device.lua
Cf. #10579.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10582)
> PocketBook: add alternative definition for PB840

- frontend/readhistory.lua
Further to https://github.com/koreader/koreader/pull/10594, fix updating the mandatory.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10601)
> History: update short date/time correctly

- .luarc.json
Because doing it globally is a PITA
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10611)
> Add a config file for the Lua LSP

- plugins/statistics.koplugin/main.lua
References <https://github.com/koreader/koreader/discussions/10479>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10621)
> [i18n,plugin]Statistics: differentiate different types of 'reset'

- plugins/archiveviewer.koplugin/main.lua
More generic template: https://github.com/koreader/koreader/pull/10584#issuecomment-1614408339.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10625)
> Archive viewer: correct parsing unzip output

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/readerui.lua
- frontend/ui/screensaver.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/touchmenu.lua
- spec/unit/device_spec.lua
- spec/unit/readerui_spec.lua
(1) Remove `_getRunningInstance()`
(2) Remove double-call of `document:getProps()`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10634)
> ReaderUI: minor optimization

- frontend/dispatcher.lua
Fixes: #10631
Lightly tested
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10636)
> QuickMenu: anchor to gesture position

- frontend/ui/data/onetime_migration.lua
- frontend/ui/widget/imageviewer.lua
- plugins/opds.koplugin/opdsbrowser.lua
- plugins/opds.koplugin/opdspse.lua
(1) No more special calibre entry, local catalogs to be added in usual way. Instead of https://github.com/koreader/koreader/pull/10623.
(2) Fix OPDSPSE hack of ImageViewer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10657)
> OPDS fixes

- frontend/apps/cloudstorage/cloudstorage.lua
- frontend/apps/cloudstorage/dropboxapi.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10666)
> DropBox: unify error messages

- frontend/ui/network/manager.lua
See https://github.com/koreader/koreader/pull/10669/files#r1263385527
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10696)
> NetworkManager: increase clarity for chatty framework user-facing explanation

- frontend/device/sdl/device.lua
- kodev
- platform/appimage/AppRun
- platform/cervantes/koreader.sh
- platform/debian/koreader.sh
- platform/kindle/koreader.sh
- platform/kobo/disable-wifi.sh
- platform/kobo/enable-wifi.sh
- platform/kobo/koreader.sh
- platform/kobo/nickel.sh
- platform/kobo/obtain-ip.sh
- platform/kobo/release-ip.sh
- platform/mac/do_mac_bundle.sh
- platform/pocketbook/koreader.app
- platform/remarkable/koreader.sh
- platform/ubuntu-touch/koreader.sh
- setupkoenv.lua
Companion PR to https://github.com/koreader/koreader-base/pull/1638
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10705)
> Build: Get rid of LD_LIBRARY_PATH

- frontend/apps/reader/modules/readerview.lua
Some items are inapplicable to cre documents.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10710)
> ReaderView: do not read/save inapplicable doc_settings items

- frontend/device/kobo/device.lua
Regression since #10728, Fix #10757
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10758)
> Kobo: Unbreak Aura One support

- frontend/ui/data/onetime_migration.lua
Followup to #10749
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10775)
> Statistics: Close the DB handle in the vacuum OTM block

- plugins/exporter.koplugin/target/readwise.lua
- plugins/exporter.koplugin/template/note.tpl
Resolves #10755. Thanks @hius07
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10788)
> Exporter: Replace author newlines with commas in HTML, Readwise

- frontend/dispatcher.lua
- plugins/profiles.koplugin/main.lua
Didn't work for non-English languages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10778)
> Profiles: fix New profile with current pdf document settings

- frontend/apps/filemanager/filemanager.lua
(1) Abbreviate filepath in the selected files list.
(2) If Home folder is locked, and we are changing the Home folder to the current folder, lock it.
(3) `pasteHere` to the current folder by default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10821)
> Filemanager: minor tweaks

- frontend/device/kobo/device.lua
Apparently, that doesn't quite work...
Re: #10719
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10841)
> Kobo: Disable HW inversion on MTK

- frontend/apps/filemanager/filemanagerutil.lua
- plugins/calibre.koplugin/search.lua
We're getting old, remembering whether you've actually read stuff is hard ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10842)
> Calibre: Add reading status to the metadata search popups

- frontend/device/generic/device.lua
Was getting mildly miffed by false-positives with the charging LED on plug/unplug ;o).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10855)
> Device: Try harder to properly setup the charging LED on plug/unplug

- frontend/apps/reader/modules/readertypeset.lua
- frontend/apps/reader/readerui.lua
- plugins/profiles.koplugin/main.lua
Main discussion in https://github.com/koreader/koreader/pull/10763.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10801)
> copt deduplicate: smooth_scaling, nightmode_images

- frontend/docsettings.lua
Made a few private functions actually private ;).
Also bumps base & android for minor third-party updates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10868)
> DocSettings: Minor cleanup following #10861

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagerutil.lua
- frontend/apps/reader/modules/readerfooter.lua
- plugins/coverbrowser.koplugin/covermenu.lua
Thanks to https://github.com/koreader/koreader/pull/10861#issuecomment-1702954994.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10869)
> Custom metadata: event

- frontend/apps/reader/modules/readercoptlistener.lua
- frontend/apps/reader/modules/readertypeset.lua
- frontend/apps/reader/modules/readerview.lua
- frontend/ui/data/creoptions.lua
- plugins/profiles.koplugin/main.lua
Main discussion in https://github.com/koreader/koreader/pull/10763.
The last round for ReaderTypeset.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10880)
> copt deduplicate: render_dpi, margins, rotation_mode

- frontend/apps/reader/modules/readerdogear.lua
- frontend/apps/reader/modules/readerfont.lua
- frontend/apps/reader/modules/readerpagemap.lua
- frontend/apps/reader/modules/readerthumbnail.lua
- frontend/ui/data/settings_migration.lua
Main discussion in: https://github.com/koreader/koreader/pull/10763.
The last round for cre options.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10885)
> copt deduplicate: font settings

- frontend/apps/reader/modules/readercropping.lua
- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/imageviewer.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/multiconfirmbox.lua
Leftovers after https://github.com/koreader/koreader/commit/b81a407690fe3ec1942e1fb69e2481dc1b751b0a#diff-f4336cced5920f9a372bf51d7145f80fba8243ad0a88cfaa046ba4824f08423d.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10926)
> ButtonTable: remove unused

- frontend/ui/elements/screensaver_menu.lua
With radio buttons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10931)
> Screensaver menu: prettify

- frontend/device/pocketbook/device.lua
Update device.lua, to add PB-Verse_(PB629) and PB-Verse Pro_(PB634)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10938)
> Update device.lua, to add PB-Verse_(PB629) and PB-Verse Pro_(PB634)

- frontend/device/sdl/device.lua
Fix #10927
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10929)
> sdl: ensure dialogs are displayed after window change events

- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagerutil.lua
Closes https://github.com/koreader/koreader/issues/10933.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10946)
> Status: setting status of current book in History and Collections

- frontend/ui/elements/screen_rotation_menu_table.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/10954)
> Screen rotation menu: deduplicate

- plugins/vocabbuilder.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/11006.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11008)
> Vocabbuilder: fix docless title

- frontend/docsettings.lua
- frontend/luadefaults.lua
- frontend/luasettings.lua
- frontend/readhistory.lua
- frontend/util.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11012)
> writeToFile: centralize

- README.md
See https://github.com/koreader/koreader.github.io/pull/21
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11000)
> README: update user guide link

- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/dispatcher.lua
Intentionally disabled in https://github.com/koreader/koreader/pull/10994.
Closes https://github.com/koreader/koreader/issues/11005.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11028)
> Reader: re-enable File search, Folder shortcuts

- plugins/exporter.koplugin/target/flomo.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11031)
> [lang] Exporter: add translator's note about Flomo

- plugins/exporter.koplugin/target/memos.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11032)
> [lang] Exporter: minor stylistic changes to Memos capitalization and dialog titles

- frontend/apps/cloudstorage/webdav.lua
Closes https://github.com/koreader/koreader/issues/11025.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11026)
> WebDAV: do not allow trailing slash in start folder name

- frontend/device/kindle/device.lua
Maybe. Assuming Bellatrix3 boards are extremely similar to their Bellatrix brethren...
Fix #11045
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11047)
> Kindle: Initial Scribe support

- frontend/device/kindle/device.lua
- frontend/device/kobo/device.lua
Need to poke elsewhere for its Input device
Fix #11048
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11049)
> Kindle: Handle the PW5 SE properly

- frontend/device/kindle/device.lua
That sort of stuff may ultimately be more fleshed out and end up in an `input_utils` to avoid code duplication with the ExternalKeyboard plugin.
Alas, time is in short supply ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11064)
> Kindle: The KT5 requires the same input delving shenanigans as the PW5

- plugins/exporter.koplugin/main.lua
- plugins/exporter.koplugin/target/xmnote.lua
Highlight export now supports [XMNote](https://www.coolapk.com/apk/com.merpyzf.xmnote), which is an app for managing book highlights.
Screenshot:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11087)
> Exporter: add XMNote export

- frontend/ui/data/dictionaries.lua
This PR will add English to Persian dictionary to the list of available dictionaries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11160)
> English to Persian dictionary

- frontend/apps/filemanager/filemanagershortcuts.lua
Closes https://github.com/koreader/koreader/issues/11166.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11167)
> Folder shortcuts: fix menu

- plugins/gestures.koplugin/main.lua
Fixes https://github.com/koreader/koreader/issues/11161#issuecomment-1827692855.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11175)
> Profiles: fix update actions in gestures

- frontend/apps/filemanager/filemanagerhistory.lua
Closes https://github.com/koreader/koreader/issues/11183.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11188)
> History: fix non standard status

- frontend/device/gesturedetector.lua
Apparently, #11198 wasn't defensive enough...
Make those visible warnings, so we can see how much they actually happen in the wild...
Fix #11209 & Fix #10950 (via https://github.com/koreader/koreader-base/pull/1712)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11211)
> GestureDetector: Be even *more* defensive with initial_tev records (and fix MT on PB)

- frontend/device/sdl/device.lua
SDL supports multitouch since https://github.com/koreader/koreader-base/pull/1599
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11212)
> AppImage: remove hasMultitouch = no

- plugins/terminal.koplugin/terminputtext.lua
Closes #11229
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11230)
> Terminal Emulator: Fix former_buffer crash

- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/filemanager/filemanagerutil.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readerwikipedia.lua
- frontend/document/document.lua
- frontend/ui/screensaver.lua
- frontend/ui/widget/buttondialog.lua
- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/imageviewer.lua
- frontend/ui/widget/screenshoter.lua
- plugins/exporter.koplugin/main.lua
- plugins/statistics.koplugin/main.lua
(1) Closes https://github.com/koreader/koreader/issues/11193.
(2) Unify and deduplicate "Choose folder" dialog in different modules.
(3) Fixes https://github.com/koreader/koreader/issues/11228.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11227)
> Screenshot: set as book custom cover

- platform/debian/koreader.desktop
Fixes #11118.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11249)
> Debian package: add X-Purism-FormFactor to koreader.desktop

- frontend/device/kindle/device.lua
- plugins/autofrontlight.koplugin/main.lua
- spec/unit/autofrontlight_spec.lua
Add the Scribe to the list while we're there
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11255)
> Kindle: Add a hasLightSensor devcap, and use it in the AutoFrontlight plugin

- plugins/exporter.koplugin/base.lua
Closes #9988
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11259)
> Android - Exporter Plugin - FIX Share as text crash (2.0)

- frontend/apps/filemanager/filemanagerbookinfo.lua
When showing from the "Book information" page, the description should be shown with "book_info" text type, while other fields use "general" text type of TextViewer.
Noticed in https://github.com/koreader/koreader/pull/11210#issuecomment-1862328359.
Closes https://github.com/koreader/koreader/issues/10692.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11260)
> Book info: proper text type of description

- plugins/statistics.koplugin/main.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11279)
> fix continued mode, goto statistics page crashed

- frontend/apps/filemanager/filemanagerhistory.lua
Closes https://github.com/koreader/koreader/issues/11281.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11282)
> History: fix untranslated strings

- frontend/device/kindle/device.lua
Closes #11286 
Overrides #11290 (needed a branch update)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11292)
> Add HW dither on Kindle Scribe

- frontend/device/kindle/device.lua
Closes #11269
Thank you @NiLuJe !
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11277)
> Kindle Oasis 1,2,3, Scribe: fix startup orientation

- plugins/coverbrowser.koplugin/bookinfomanager.lua
Closes https://github.com/koreader/koreader/issues/11355.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11356)
> CoverBrowser: fix cover cache check

- plugins/coverbrowser.koplugin/bookinfomanager.lua
Related issue https://github.com/koreader/koreader/issues/11375.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11380)
> CoverBrowser: fix cover cache check #2

- frontend/apps/reader/modules/readersearch.lua
- frontend/dispatcher.lua
- frontend/ui/elements/reader_menu_order.lua
I do not like the idea of saving last search results to the storage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11388)
> Fulltext search: action to show last findall results

- plugins/texteditor.koplugin/main.lua
File size was changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11396)
> Text editor: refresh path on saving file

- datastorage.lua
- frontend/docsettings.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11439)
> DocSettings: check legacy history location only once

- frontend/apps/filemanager/filemanager.lua
- frontend/document/documentregistry.lua
- frontend/ui/widget/filechooser.lua
- plugins/coverbrowser.koplugin/covermenu.lua
Use item info provided by FileChooser.
Also fix showing PathChooser with invalid path (thanks @zwim for reporting).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11452)
> FileManager: less lfs calls

- frontend/apps/reader/modules/readerpaging.lua
Issue: https://github.com/koreader/koreader/issues/11405
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11408)
> Fix offset issue on next page in pan zoom

- plugins/vocabbuilder.koplugin/main.lua
Added support
1. Select only this book
2. Select all books
3. Select all books on this page
4. Deselect all books on this page 
when filtering.
Ref. #11471
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11475)
> VocabBuilder.koplugin: support batch operations in book filtering

- README.md
Closes #11384.
(Unless someone knows an alternative.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11385)
> Remove bountysource from README

- frontend/apps/reader/modules/readerlink.lua
Fixes #11567.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11569)
> [fix] ReaderLink: fix copy link

- frontend/apps/reader/modules/readerview.lua
- frontend/ui/widget/filechooser.lua
fixes #11581
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11586)
> Underline thickness increased

- frontend/apps/reader/modules/readerhighlight.lua
~~strikeout~~ Strike through
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11619)
> [ReaderHighlight] ~~strikeout~~ → Strike through

- frontend/ui/widget/filechooser.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11615)
> [minor] FileChooser: use en-dash instead of dash for UI

- frontend/apps/reader/modules/readerstyletweak.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11616)
> [minor] ReaderStyletweak: fix typo

- frontend/apps/filemanager/filemanagermenu.lua
Closes https://github.com/koreader/koreader/issues/11625.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11626)
> File manager: fix classic mode item font size

- frontend/document/credocument.lua
- frontend/document/document.lua
- plugins/coverbrowser.koplugin/bookinfomanager.lua
Depends on https://github.com/koreader/koreader-base/pull/1758
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11628)
> feat: add identifiers to document

- frontend/document/credocument.lua
Bump base:
- Update LuaJIT to 20240310 https://github.com/koreader/koreader-base/pull/1765
- harfbuzz: fix ccache 4.9.1 errors https://github.com/koreader/koreader-base/pull/1760
- ci: drop unnecessary macOS build dependency
- CRE: avoid assert failure in sub-processes https://github.com/koreader/koreader-base/pull/1766
Bump luajit-launcher:
- Update LuaJIT to 20240310 https://github.com/koreader/android-luajit-launcher/pull/476
Frontend:
- CreDocument: prevent assert failure in sub-processes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11658)
> bump base, luajit-launcher, avoid assert failure in sub-processes

- doc/Building.md
Not necessary anymore. Closes #11633.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11661)
> doc: remove ragel from the build requirements

- Makefile
https://github.com/AppImage/AppImageKit/releases/tag/13
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11665)
> [AppImage] AppImageTool 13 (#5275)

- frontend/ui/widget/virtualkeyboard.lua
Discussed in https://github.com/koreader/koreader/issues/11668.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11699)
> Keyboard: detect tap if swipes are disabled

- frontend/ui/widget/sortwidget.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11705)
> SortWidget: sort alphabetically

- .circleci/config.yml
base:
- https://github.com/koreader/koreader-base/pull/1774
- https://github.com/koreader/koreader-base/pull/1772
- https://github.com/koreader/koreader-base/pull/1771
- https://github.com/koreader/koreader-base/pull/1770
- https://github.com/koreader/koreader-base/pull/1769
- ci: drop travis configuration (unused)
- ci: cleanup unnecessary code in `common` script
- ci: drop `emulator_install` script
- ci: bump (most) docker images (switch to Ubuntu 20.04)
luajit-launcher:
- https://github.com/koreader/android-luajit-launcher/pull/445
- https://github.com/koreader/android-luajit-launcher/pull/469
- https://github.com/koreader/android-luajit-launcher/pull/478
- https://github.com/koreader/android-luajit-launcher/pull/479
- - - …
> bump base, docker images, and luajit-launcher

- frontend/apps/reader/modules/readerlink.lua
- frontend/apps/reader/modules/readersearch.lua
- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/apps/reader/modules/readertoc.lua
- plugins/httpinspector.koplugin/main.lua
- plugins/statistics.koplugin/main.lua
I felt the need for that when working on https://github.com/koreader/koreader-base/pull/1766.
Argued at https://github.com/koreader/koreader/pull/11533#issuecomment-2041526924 and follow ups.
When on a page before the first ToC item (the first chapter), that first chapter title may be shown in the footer instead of a more correct blank title.
This bug might still have had other small effect elsewhere.
Closes #11674.
As currently we only handle ReadingPaused/Resumed on suspend and resume, no page change should happen while paused, so there is no current issue to fix. But let's get ready for other use cases (which may be brought in by user patches, ie. pausing while the SkimWidget is displayed, and obviously triggers page changes).
See …
> Various minor tweaks and fixes (ToC, Search, HttpInspector)

- frontend/device/gesturedetector.lua
- frontend/ui/trapper.lua
- frontend/ui/widget/imagewidget.lua
- plugins/kosync.koplugin/main.lua
remove repetitive words
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11785)
> chore: remove repetitive words

- spec/unit/commonrequire.lua
- spec/unit/readerbookmark_spec.lua
- spec/unit/readerhighlight_spec.lua
- spec/unit/readerlink_spec.lua
Cf. discussion in #11775.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11784)
> fix frontend tests

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
Fix Bookmark list with reverse sorting.
Fix pdf "tap on highlight" detection.
Fix pdf multi-page highlight note marker.
Closes https://github.com/koreader/koreader/issues/11762.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11788)
> Annotations: fixes 2

- platform/pocketbook/koreader.app
I believe this fixes #11760
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11764)
> Check if /usr/bin symlink is present to fix instance reuse issue on older Pocketbooks

- .ci/after_success.sh
- .ci/build.sh
- .ci/test.sh
- .circleci/config.yml
- .github/workflows/build.yml
Pendent of https://github.com/koreader/koreader-base/pull/1783.
Example CI runs:
- miss on both caches: [CircleCI](https://app.circleci.com/pipelines/github/benoit-pierre/koreader/208/workflows/9edc833b-50ad-4fab-bc62-d2b3beaf69d8/jobs/181) / [macOS](https://github.com/benoit-pierre/koreader/actions/runs/9069053825/job/24917755160)
- primary hit on ccache: [macOS](https://github.com/benoit-pierre/koreader/actions/runs/9069534031/job/24919290445)
- primary hit: [CircleCI](https://app.circleci.com/pipelines/github/benoit-pierre/koreader/209/workflows/5e213985-6a97-4a8d-9a51-83c26edeebea/jobs/183) / [macOS](https://github.com/benoit-pierre/koreader/actions/runs/9069534031/job/24920092051)
- - - …
> CI improvements

- doc/Building_targets.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11818)
> doc: fix android NDK / SDK instructions

- platform/appimage/koreader.appdata.xml
Because it is actually pulled from here :p
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11819)
> appimage: keep metadata in sync with flathub

- frontend/ui/widget/dictquicklookup.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11811)
> fix #11810: only set FocusManager layout if hasDPod

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/menu.lua
Mostly internal optimization, but also some UI changes:
(1) Good bookmark list header showing filtering status
(2) Bookmark details with arrows for next/previous bookmark jump
(3) Bookmark details window is not closed after editing note/text, to review the changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11825)
> Annotations: Bookmark list improvement

- frontend/ui/widget/multiinputdialog.lua
Closes https://github.com/koreader/koreader/issues/11812.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11832)
> MultiInputDialog: fix keyboard height changed

- make/appimage.mk
- make/linux.mk
I'm sorry. I promise to never use `nano` again to do quick edits :/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11849)
> fix after #11833

- platform/appimage/koreader.desktop
- platform/linux/koreader.desktop
Also added them in the appimage, since apps like Gear Lever can be used to integrate it into a proper desktop application.
Change the comment to a simple "ebook reader"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11847)
> Desktop: add all supported mimetypes.

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/readerui.lua
- frontend/ui/network/networklistener.lua
Discussed at https://github.com/koreader/koreader/pull/11749#issuecomment-2119098139 and further.
@Commodore64user
This should help you with #11749
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11858)
> NetworkListener: Fix FM integration & properly gate behind hasWifiToggle

- make/linux.mk
- platform/linux/do_debian_package.sh
- platform/linux/instructions.txt
With instructions for package maintainers and **non-instructions** for end users.
The Libc version detection is a bit flaky but works across GLIBC2 versions. I'm open to remove it if it is too hacky.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11859)
> add README.md to linux package

- frontend/ui/widget/menu.lua
- frontend/ui/widget/touchmenu.lua
discussed #11834
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11872)
> Global long press on K4, 'ScreenKB' + 'Press'

- frontend/ui/widget/focusmanager.lua
- frontend/ui/widget/menu.lua
discussed https://github.com/koreader/koreader/issues/11834
then merged #11872, then reverted #11881
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11884)
> Global long press on K4, 'ScreenKB' + 'Press' (this time for real)

- frontend/ui/widget/inputtext.lua
- frontend/ui/widget/virtualkeyboard.lua
Closes https://github.com/koreader/koreader/issues/11831.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11843)
> VirtualKeyboard: delete word on backspace swipe west

- frontend/ui/widget/screenshoter.lua
Related to https://github.com/koreader/koreader/issues/11887.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11888)
> Enable Alt+Shift+G for screenshots on all devices with a keyboard

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/ui/widget/filechooser.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
- resources/icons/mdlight/star.white.svg
Discussed in and closes https://github.com/koreader/koreader/issues/11846.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11868)
> Collections: add collection mark to books

- frontend/ui/widget/menu.lua
addresses concerns found in #11884
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11890)
> long press on Right key limited to hasFewKeys (this time is personal)

- frontend/apps/reader/modules/readerhighlight.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11898)
> remove very long press from NT settings

- frontend/apps/reader/modules/readerbookmark.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11902)
> [i18n] ReaderBookmark: don't bother translators with a space

- frontend/apps/reader/modules/readerfooter.lua
Show the whole book progress percentage even when the chapter progress bar is enabled.
(Also deduplicated building of the settings menu items.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11885)
> Status bar: fix book progress

- frontend/apps/reader/modules/readerlink.lua
See https://github.com/koreader/koreader/pull/11900/files/316c6a0624a504e1ef8645dfbcfb068a73384d3b#r1615314584
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11905)
> ReaderLink: change (hasScreenKB or hasSymKey) add to notification stack shortcut to Press instead of Down

- plugins/coverbrowser.koplugin/mosaicmenu.lua
this PR [and #11884] closes #11834
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11906)
> CoverBrowser: update MosaicMenu FocusManager grid view to 2D

- frontend/apps/reader/modules/readerbookmark.lua
discussed https://github.com/koreader/koreader/issues/11834#issuecomment-2132411929 onwards.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11907)
> [ReaderBookmark] "bookmark current page" removed from NT kindles

- .circleci/config.yml
- .github/workflows/build.yml
- Makefile
- kodev
- make/android.mk
- make/appimage.mk
- make/cervantes.mk
- make/kindle.mk
- make/kobo.mk
- make/linux.mk
- make/macos.mk
- make/pocketbook.mk
- make/remarkable.mk
- make/sony-prstux.mk
- make/ubuntu-touch.mk
- setupkoenv.lua
- spec/unit/commonrequire.lua
- spec/unit/dbg_spec.lua
- tools/benchmark.lua
- tools/kobo_touch_probe.lua
- tools/wbuilder.lua
- https://github.com/koreader/koreader-base/pull/1750
- https://github.com/koreader/koreader-base/pull/1793
- https://github.com/koreader/koreader-base/pull/1794
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11923)
> bump base + new build system tweaks

- frontend/apps/reader/modules/readerlink.lua
as seen here https://github.com/koreader/koreader/pull/11900#discussion_r1615474301.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11925)
> ReaderLink: make AddCurrentLocationToStack show notification

- frontend/fontlist.lua
Closes https://github.com/koreader/koreader/issues/11927.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11932)
> FontList: skip Kindle blacklisted fonts

- frontend/ui/elements/menu_keyboard_layout.lua
sorry, this should have been in the previous PR. I just hadn't noticed ;)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11944)
> Keyboard menu, swipe setting removed from NT

- plugins/autowarmth.koplugin/main.lua
This fixes the request in #11274.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11946)
> [plugin AutoWarmth] Add more gesture for activation of autowarmth

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/ui/widget/menu.lua
Max lines: 3
Max lines: 1
Closes https://github.com/koreader/koreader/issues/10163. Closes https://github.com/koreader/koreader/issues/11719.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11918)
> Annotation list: flexible item heights

- frontend/apps/filemanager/filemanager.lua
- frontend/dispatcher.lua
- plugins/coverbrowser.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/11007.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11921)
> Dispatcher: add File browser actions 'Set display mode', 'Sort By'

- frontend/document/pdfdocument.lua
- spec/unit/koptinterface_spec.lua
Depend on https://github.com/koreader/koreader-base/pull/1805.
Closes:
- #5422 
- #9927
- #10879
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11940)
> mupdf: update to 1.24.2

- frontend/ui/widget/dictquicklookup.lua
- frontend/ui/widget/sortwidget.lua
addressing concerns found #11933
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11949)
> [SortWidget, DictQuickLookup] Renaming functions

- frontend/ui/widget/menu.lua
As seen here https://github.com/koreader/koreader/pull/11918#issuecomment-2137290809
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11966)
> add menu-key-event to 'Menu widget'

- frontend/device/generic/device.lua
fixing issue described here https://github.com/koreader/koreader/pull/11963#issuecomment-2147876605.
thanks @poire-z
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11982)
> fixing button mapping shenanigans

- frontend/apps/reader/modules/readerfooter.lua
- frontend/apps/reader/modules/readertoc.lua
- frontend/ui/elements/screensaver_menu.lua
see #11978
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11981)
> Minor wording corrections

- frontend/apps/reader/modules/readerthumbnail.lua
fixing bug reported here https://github.com/koreader/koreader/pull/11916#issuecomment-2151903891
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11987)
> [ReaderThumbnail] Change base class to support key events

- frontend/apps/cloudstorage/webdav.lua
- frontend/apps/cloudstorage/webdavapi.lua
Fixes #11985
It now shows InfoMessage `Could not upload file (network error)` if upload `code` is nil.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12000)
> Cloud error fix

- plugins/statistics.koplugin/main.lua
Closes #11201 
Thank you very much @hius07 !
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11991)
> Statistics Plugin: Skip adding never opened marked as finished books

- frontend/ui/otamanager.lua
- kodev
- make/kindlehf.mk
CC: https://github.com/koreader/koreader-base/pull/1814
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11986)
> Add support for kindles after fw 5.16.3

- .github/workflows/build.yml
- platform/mac/do_mac_bundle.sh
Untested, someone with access to a real machine will have to test the bundle.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11945)
> ci/macos: add arm64 job

- frontend/apps/reader/modules/readerlink.lua
This allows plugins to handle relative and otherwise schemeless URLs.
Also: clear registered schemes on each init(), to parallel the situation with external link buttons, and add documentation.
(Sorry for making 3 PRs where one would have done... this should really be the last on this now.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12019)
> Readerlink: allow registering empty scheme

- doc/Building.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/11961)
> doc: update building documentation

- frontend/apps/reader/modules/readerbookmark.lua
Closes https://github.com/koreader/koreader/issues/12052.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12053)
> ReaderBookmark: fix sort by date

- frontend/ui/widget/menu.lua
Shortcuts to improve navigation when using Menu Widget.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12065)
> [Menu Widget] shortcuts for easier navigation on NT kindle

- frontend/version.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12074)
> Version: Fix documentation of version number

- frontend/apps/cloudstorage/webdav.lua
- frontend/apps/cloudstorage/webdavapi.lua
- frontend/apps/reader/modules/readergoto.lua
- frontend/apps/reader/modules/readerpaging.lua
- frontend/device/android/device.lua
- frontend/device/kindle/device.lua
- frontend/device/kindle/powerd.lua
- frontend/device/sdl/device.lua
- frontend/ui/data/keyboardlayouts/ar_keyboard.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/filemanager_menu_order.lua
- frontend/ui/elements/reader_menu_order.lua
- frontend/ui/network/manager.lua
- frontend/ui/network/networklistener.lua
- frontend/ui/translator.lua
- frontend/ui/widget/filechooser.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/networksetting.lua
- frontend/ui/widget/screenshoter.lua
- frontend/ui/widget/skimtowidget.lua
- frontend/util.lua
- frontend/version.lua
https://github.com/koreader/koreader/issues/12040, this is not final, i still need to add https://github.com/notmarek/openlipclua to the base, and i have no idea how to go about it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12056)
> Kindle: Add wifi selector

- frontend/apps/filemanager/filemanager.lua
Closes https://github.com/koreader/koreader/issues/12094.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12095)
> Filemanager: fix OpenWith without config

- plugins/exporter.koplugin/target/my_clippings.lua
This should take care of #10745 regarding my_clippings; I'm not sure if it's the last one remaining and the issue can be closed.
The result is the same and I've followed the instructions given by @pazos; hopefully the OOM risk is no more.
Thanks for tagging me in #12106 (probably needs to solve conflicts with this fix)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12107)
> Export: solved my_clippings OOM

- frontend/apps/reader/modules/readermenu.lua
- frontend/apps/reader/modules/readerstatus.lua
- frontend/apps/reader/readerui.lua
Closes https://github.com/koreader/koreader/issues/12125.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12129)
> Reader: always exit to book folder

- plugins/exporter.koplugin/target/markdown.lua
- plugins/exporter.koplugin/target/text.lua
- plugins/exporter.koplugin/template/md.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12126)
> exporter: fix OOM

- tools/update-metadata.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12157)
> [minor] Fix lowercase typo in "Google Translate"

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12166)
> ci/circle: bump docker image

- spec/unit/opds_spec.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12185)
> tests/opds: fix no longer valid feedbooks.com URLs

- .github/workflows/build.yml
- doc/Building.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12187)
> bump base (updated build system) & fix macOS CI

- frontend/apps/reader/modules/readercoptlistener.lua
- frontend/apps/reader/modules/readerfooter.lua
- frontend/ui/widget/datetimewidget.lua
- plugins/readtimer.koplugin/main.lua
This closes #11950
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12002)
> AltStatusBar/Footer: add the read timer value

- frontend/apps/reader/modules/readerannotation.lua
- frontend/apps/reader/modules/readerpagemap.lua
- plugins/exporter.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/12209.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12214)
> Annotations: pageno honors reference pages and hidden flows

- frontend/ui/widget/toggleswitch.lua
Closes https://github.com/koreader/koreader/issues/12206.
Maybe quick and dirty, but making ToggleSwitch totally independent of ConfigDialog would require much work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12215)
> ToggleSwitch: fix long-press

- frontend/apps/reader/modules/readerannotation.lua
Closes https://github.com/koreader/koreader/issues/12230.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12231)
> ReaderAnnotation: fix doesMatch func

- doc/Building.md
It usually gets pulled when installing git.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12240)
> doc: explicitly mention perl dependency

- .ci/build.sh
- .ci/test.sh
- .circleci/config.yml
- .github/workflows/build.yml
- Makefile
- make/android.mk
- make/appimage.mk
- make/cervantes.mk
- make/kindle.mk
- make/kobo.mk
- make/pocketbook.mk
- make/remarkable.mk
- make/sony-prstux.mk
- make/ubuntu-touch.mk
Cf. https://github.com/koreader/koreader-base/pull/1858.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12242)
> miscellaneous build system changes

- frontend/ui/network/manager.lua
Fixes #12244.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12260)
> [fix] NetworkMgr: apply HTTP proxy setting on startup

- frontend/apps/reader/modules/readerannotation.lua
Closes https://github.com/koreader/koreader/issues/12269.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12270)
> ReaderAnnotation: fix doesMatch func 2

- frontend/apps/reader/readerui.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12290)
> ReaderUI: add `seamless` argument to switchDocument

- frontend/ui/size.lua
- plugins/coverbrowser.koplugin/mosaicmenu.lua
closes #12132
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12189)
> [CoverBrowser.MosaicMenu] Increase the thickness of the mosaic’s focus underline

- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/multiinputdialog.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12289)
> InputDialog and MultiInputDialog: improve enter and edit callback handling, and implement addWidget

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/reader/modules/readerdictionary.lua
- frontend/apps/reader/modules/readersearch.lua
- frontend/apps/reader/modules/readerwikipedia.lua
- frontend/ui/elements/common_settings_menu_table.lua
- frontend/ui/elements/menu_keyboard_layout.lua
- frontend/ui/widget/configdialog.lua
- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/inputtext.lua
- frontend/ui/widget/multiinputdialog.lua
- frontend/ui/widget/textboxwidget.lua
* Adds option to hide virtual keyboard on devices that have a physical keyboard and K4. closes #11374
* Adds some shortcuts for search in both file manager and reader. closes #10499
<kbd>Alt</kbd> + <kbd>D</kbd>: dictionary search
<kbd>Alt</kbd> + <kbd>W</kbd>: wikipedia search
<kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd>: text search [clear field] (reader only)
<kbd>Alt</kbd> + <kbd>S</kbd>: text search [populated with last search] (reader only)
<kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd>: file search (clear field)
<kbd>Alt</kbd> + <kbd>F</kbd>: file search (with last search)
<kbd>Shift</kbd> + <kbd>Del</kbd>: delete whole word (kindle only, when on an input field)
<kbd>Sym</kbd> + <kbd>Alphabet keys</kbd>: different characters and numbers (kindle only)
* Removes `Backspace …
> Show/Hide Virtual keyboard and more keyboard shortcuts

- frontend/ui/data/onetime_migration.lua
Steps need to happen in chronological order, (mostly) always.
Fix https://github.com/koreader/koreader/issues/12326
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12337)
> OTM: Unbreak #11999 

- doc/Building_targets.md
Closes #12344.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12345)
> [doc] Build: update Android instructions to openjdk-17-jdk

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/reader/modules/readerannotation.lua
- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhandmade.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readersearch.lua
(1) Fix updating page numbers when partial rendering enabled.
(2) Add support of pdf custom hidden flows.
(3) Add updating page numbers when custom hidden flows changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12324)
> Annotations: fix page numbers

- frontend/ui/rendertext.lua
- frontend/ui/widget/imagewidget.lua
Completely pointless commits because I got triggered by a missing pipe in a log ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12354)
> Nit: Make some cache keys prettier

- frontend/dispatcher.lua
In consistency with the menu:
https://github.com/koreader/koreader/blob/a51bd7a7fd1376ca972171994a6f6a7eec7a6464/frontend/ui/elements/common_exit_menu_table.lua#L33-L38
https://github.com/koreader/koreader/blob/a51bd7a7fd1376ca972171994a6f6a7eec7a6464/frontend/ui/elements/common_settings_menu_table.lua#L277-L285
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12356)
> Dispatcher: minor wording fixes

- frontend/ui/message/filemessagequeue.lua
- frontend/ui/message/messagequeue.lua
- frontend/ui/message/streammessagequeue.lua
- frontend/ui/message/streammessagequeueserver.lua
Tested:
- calibre wireless connection with the emulator and Android ARM / ARM64
- HTTP inspector (patched to use `streammessagequeueserver`) with the emulator
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12350)
> czmq & libzmq: update to 4.2.1 & 4.3.5 respectively

- .ci/after_success.sh
Don't try to re-build (particularly base, since some things where removed before saving the build cache).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12367)
> ci: fix test / coverage

- doc/Building_targets.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12368)
> doc: update Android build instructions

- frontend/apps/reader/modules/readerstatus.lua
- frontend/apps/reader/readerui.lua
- frontend/ui/screensaver.lua
- frontend/ui/widget/bookstatuswidget.lua
- tools/wbuilder.lua
Mostly remove unused code, minor fixes.
(Maybe we can consider removing Book status at all)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12343)
> ReaderStatus, Book status widget: cleanup

- .github/workflows/build.yml
Same as https://github.com/koreader/koreader-base/pull/1909.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12382)
> ci/macos: fix homebrew packages install

- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/inputtext.lua
* minor corrections to issues raised by @poire-z here #12162
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12372)
> Minor corrections

- frontend/apps/reader/modules/readerfooter.lua
- frontend/dispatcher.lua
- frontend/ui/widget/touchmenu.lua
- plugins/gestures.koplugin/main.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12378)
> Touch menu: always go up to correct parent page

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/ui/widget/bookmapwidget.lua
- frontend/ui/widget/pagebrowserwidget.lua
Fixes #12389
Fixes #12387
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12390)
> Closing Bookmark details dialog with X should also refresh list entry

- kodev
- make/emulator.mk
Automatically use rlwrap if available.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12408)
> kodev: improve `kodev prompt`

- frontend/apps/reader/modules/readerfooter.lua
- plugins/readtimer.koplugin/main.lua
One from ReadTimer, for sure; and one that maaaaybe could be tripped via BookMetadataChanged ;).
Fix #12323
(rebase me)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12422)
> Fix a couple of potentially spurious footer refreshes

- frontend/apps/reader/modules/readerhighlight.lua
Noticed while triaging #12478 ;)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12479)
> ReaderHighlight: Fix an old typo in the OCR help string

- frontend/dispatcher.lua
* Adds events to dispatcher for selecting next/previous link in the current page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12474)
> [Dispatcher] new events for selecting links

- plugins/vocabbuilder.koplugin/db.lua
- plugins/vocabbuilder.koplugin/main.lua
This pr retains the highlighted word in the vocab context when the word stem is being searched manually.
This does not fix #11754 but makes things a bit better.
Closes #12465.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12469)
> VocabBuilder.koplugin: Better handling word context

- frontend/device/kindle/device.lua
- frontend/device/kindle/powerd.lua
Fix #11744
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12521)
> Kindle: Restore hall effect sensor state on startup

- frontend/device/pocketbook/device.lua
Another regression from #12486.
Cf. https://github.com/koreader/koreader/issues/12554#issuecomment-2374718772.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12555)
> input: fix pocketbook init

- frontend/device/kindle/device.lua
- frontend/device/kobo/device.lua
- frontend/ui/message/filemessagequeue.lua
- frontend/ui/message/messagequeue.lua
- frontend/ui/message/streammessagequeue.lua
- frontend/ui/message/streammessagequeueserver.lua
- platform/android/llapp_main.lua
- plugins/externalkeyboard.koplugin/main.lua
- setupkoenv.lua
To load our native libraries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12545)
> use new `ffi.loadlib` helper

- plugins/exporter.koplugin/base.lua
- plugins/exporter.koplugin/main.lua
(1) Add a setting to export current book highlights to the book folder.
(2) Register exporting actions in Dispatcher. Closes https://github.com/koreader/koreader/issues/12452.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12569)
> Exporter: export to book folder, register to Dispatcher

- make/appimage.mk
Depend on https://github.com/koreader/koreader-base/pull/1946.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12575)
> sdl: use our compiled version for the AppImage

- plugins/exporter.koplugin/main.lua
Fixes #12591.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12592)
> [plugin] Exporter: fix typo

- frontend/dispatcher.lua
Closes https://github.com/koreader/koreader/issues/12057.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12580)
> Dispatcher: values' range consistent with bottom menu

- frontend/util.lua
- plugins/docsettingtweak.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/12559.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12606)
> DocSettingsTweak: apply to books with status

- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagershortcuts.lua
- frontend/ui/widget/menu.lua
Based on https://github.com/koreader/koreader/pull/7524#discussion_r610854294.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12573)
> Menu widget: rotation handler

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/document/credocument.lua
Follows the "Highlight" dialog position settings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12599)
> ReaderHighlight: adjustable "Edit highlight" dialog position

- plugins/terminal.koplugin/main.lua
Revival of #12384 now that https://github.com/koreader/android-luajit-launcher/pull/524 is in ;).
(Rebase me)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12631)
> Terminal: Minor cleanups

- frontend/ui/widget/inputdialog.lua
- frontend/ui/widget/inputtext.lua
Dioscussed in https://github.com/koreader/koreader/issues/12618. Closes https://github.com/koreader/koreader/issues/12618.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12632)
> Text editor: show current line number

- frontend/ui/widget/inputtext.lua
Regression in https://github.com/koreader/koreader/pull/12632.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12652)
> InputText: fix Terminal plugin input

- frontend/apps/reader/modules/readerhighlight.lua
Closes https://github.com/koreader/koreader/issues/12653.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12654)
> ReaderHighlight: fix color for extended highlight in pdf

- frontend/device/kindle/device.lua
Fixes #12662
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12663)
> Kindle Scribe: fix elseif for orientation code

- plugins/autofrontlight.koplugin/_meta.lua
My suggestion to fix #12567
Deprecate now, remove soon :)
Might be moved to contrib if current users find it useful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12619)
> And deprecation to autofrontlight

- plugins/exporter.koplugin/_meta.lua
Make sure we don't keep unsupported code on our tree.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12620)
> Add deprecation for unmaintained targets

- plugins/patchmanagement.koplugin/main.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12668)
> PatchManagement: prettify menu

- doc/Building.md
C.f., https://github.com/koreader/koreader/issues/12678
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12680)
> Update Building.md - meson install from backports

- plugins/terminal.koplugin/main.lua
Do not log on every book opening/closing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12682)
> Terminal: less logging

- frontend/ui/widget/menu.lua
- plugins/coverbrowser.koplugin/main.lua
(1) Fix drawing focus in Mosaic mode.
(2) CoverBrowser: keep focus and show focused item when switching display modes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12688)
> Focus: fixes

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/ui/widget/filechooser.lua
- frontend/util.lua
- plugins/profiles.koplugin/main.lua
(1) on showing folder
(2) on book opening: if book is in collections
(3) on book closing - same conditions as for opening
On showing folder
On book opening
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12691)
> Profiles: more auto-exec triggers 2

- plugins/calibre.koplugin/main.lua
After #12714 
Sorry :/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12715)
> calibre: remove json chooser UI leftover

- plugins/wallabag.koplugin/main.lua
Before this change, on hold articles were deleted if `Remotely delete finished articles` was enabled. To make this configurable new option `Remotely delete on hold articles` has been added.
Fixes #12698.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12722)
> Separate option to delete ‘on hold’ articles from wallabag

- frontend/apps/reader/modules/readerhighlight.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12731)
> [minor] ReaderHighlight: normalize spelling of PDF

- frontend/apps/reader/modules/readerhighlight.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12732)
> [minor] ReaderHighlight: normalize more spelling of PDF

- frontend/device/android/device.lua
Includes:
https://github.com/koreader/android-luajit-launcher/pull/526
https://github.com/koreader/android-luajit-launcher/pull/527
https://github.com/koreader/android-luajit-launcher/pull/528
https://github.com/koreader/android-luajit-launcher/pull/529
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12734)
> bump android-luajit-launcher

- frontend/ui/widget/screenshoter.lua
Check for existance and create if absent.
Closes https://github.com/koreader/koreader/issues/12742.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12750)
> Screenshoter: fix screenshot folder

- frontend/document/koptinterface.lua
Factorized from lower layers' implementations (djvu & mupdf).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12729)
> factorize reflow code

- doc/Building.md
Ninja is not optional.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12762)
> doc: minor tweak to building requirements

- frontend/ui/network/wpa_supplicant.lua
Apparently, I missed this code path in #11089 and I only noticed it now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12782)
> Decode wpa_supplicant SSID when already connected

- .github/workflows/build.yml
Note: depend on #12655.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12784)
> ci/macos: enable tests

- plugins/patchmanagement.koplugin/_meta.lua
Fixes #12841.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12849)
> [plugin] Patch management: fix disabling plugin

- frontend/apps/filemanager/filemanagerbookinfo.lua
Closes https://github.com/koreader/koreader/issues/12851.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12852)
> FileManagerBookInfo: fix logic in getCoverImage()

- plugins/profiles.koplugin/main.lua
* minor addition to Profile plugin to update profile actions assigned to hotkeys
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12642)
> [Profiles] search and update profile actions assigned to hotkeys

- frontend/apps/filemanager/filemanagercollection.lua
- frontend/readcollection.lua
- frontend/util.lua
Kind of "flat" library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12892)
> Collections: add books from a folder

- frontend/document/koptinterface.lua
Closes #12916. Closes #12475.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12917)
> VocabBuilder.koplugin: support pdf context extraction for multi-word phrase

- plugins/newsdownloader.koplugin/main.lua
Fixes #12953.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12958)
> [plugin] NewsDownloader: support single-entry feeds

- plugins/newsdownloader.koplugin/main.lua
Fixes https://github.com/koreader/koreader/issues/3172.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12959)
> [plugin] NewsDownloader: fix Atom download_full_article=false not working

- plugins/exporter.koplugin/target/nextcloud.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12970)
> [lang] Exporter → Nextcloud: use proper arrow

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
Fixes #12967.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12969)
> [plugin] NewsDownloader: download images without extension

- plugins/coverbrowser.koplugin/listmenu.lua
Reported by @milotype
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12968)
> [plugin, i18n] CoverBrowser: add missing plural

- plugins/newsdownloader.koplugin/main.lua
Fixes #8611.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12980)
> [plugin] NewsDownloader: add primitive support for relative URLs

- frontend/device/kindle/device.lua
Most of this is guess work and needs testing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12990)
> [device] Add the new kindle line-up

- plugins/readtimer.koplugin/main.lua
Fixes #12984.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/12985)
> [plugin] ReadTimer: interpret more than two minutes in the past as a time tomorrow

- plugins/exporter.koplugin/target/nextcloud.lua
Fixes #12821.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13005)
> Export plugin: support multiple authors in Nextcloud export

- frontend/device/kindle/device.lua
This should be the last of the 2024 line-up and yes the device is identical to last gen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13051)
> [device] add Kindle Scribe 2 support

- plugins/wallabag.koplugin/main.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13062)
> [i18n, plugins] Wallabag: use ngettext for plural

- plugins/newsdownloader.koplugin/main.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13071)
> [minor, plugin] NewsDownloader: fix a string that's concatenated without space or newline

- plugins/coverbrowser.koplugin/main.lua
- plugins/statistics.koplugin/main.lua
I thought I had them all in <https://github.com/koreader/koreader/pull/13055> but I seem to have missed a few.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13074)
> [minor] Normalize more requires

- frontend/ui/trapper.lua
- frontend/ui/wikipedia.lua
- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
On Wikipedia articles with for example 30 images this reduces the download time from ~12 seconds to ~8 seconds (depending on image size and connection speed), which is fairly significant.
---
For context, I was looking into doing something like https://www.lua.org/pil/9.4.html to speed up image downloads when I noticed that a lot of the time spent came from the 100 ms spent waiting in between downloading every image.
I'm inclined to think it's fine if not better as currently in this PR, but regular non-waiting InfoMessages could be interspersed along these lines if desired:
```diff
diff --git a/frontend/ui/wikipedia.lua b/frontend/ui/wikipedia.lua
index 36cdcecfa..208e6ab17 100644
--- a/frontend/ui/wikipedia.lua
+++ b/frontend/ui/wikipedia.lua
@@ -1502,12 +1502,16 @@ abbr.abbr {
local …
```
> EPUB: limit image download display updates to once per second

- frontend/util.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13096)
> [minor] Remove accidental self from util.calcFreeMem()

- frontend/ui/trapper.lua
Overlooked in #13073.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13095)
> [doc] Update Trapper:info() documentation

- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerhistory.lua
- frontend/apps/filemanager/filemanagerutil.lua
- frontend/ui/widget/booklist.lua
- frontend/ui/widget/filechooser.lua
- plugins/calibre.koplugin/search.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13099)
> Collections: filter by book status

- Makefile
Cf. https://github.com/koreader/koreader-base/pull/2022.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13151)
> always compile with debug information

- frontend/ui/widget/sortwidget.lua
just a few QoL changes to the `SortWidget` class for non-touch users
* Renamed `moveItem` to `onMoveItem` and updated all references to this method. 
* Renamed `goToPage` to `onGoToPage` and updated all references to this method. 
* Introduced a new method `registerKeyEvents` to handle the registration of key events.
* Moved the key event registration logic from `init` to the new `registerKeyEvents` method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13154)
> [SortWidget] NT: add new keyEvents to widget

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
- plugins/newsdownloader.koplugin/main.lua
Closes #13061.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13171)
> NewsDownloader: add a cache to reduce wasted bandwidth

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
It's been implemented in LuaSocket http.request() in the meantime.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13179)
> [chore] NewsDownloader: remove custom redirect handling

- frontend/device/gesturedetector.lua
- spec/unit/gesturedetector_spec.lua
That somehow slipped through the cracks when those fields were added...
Fix #13090
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13101)
> GestureDetector: Translate start & end gesture positions when rotated

- plugins/newsdownloader.koplugin/main.lua
Missing in #13171.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13181)
> NewsDownloader: a couple of cache improvements

- plugins/newsdownloader.koplugin/feed_view.lua
- plugins/newsdownloader.koplugin/main.lua
Dead code, redundant comments, indentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13182)
> NewsDownloader: some random cleanup

- frontend/device/kindle/powerd.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13196)
See #13176
> Kindle: demote Warn to Info

- frontend/apps/filemanager/filemanagercollection.lua
- frontend/document/credocument.lua
Rather slow, average about 1.5 s per book on Kindle Voyage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13139)
> Collections: search in book content

- frontend/dispatcher.lua
Closes https://github.com/koreader/koreader/issues/13226.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13227)
> Dispatcher: fix remove actions

- frontend/socketutil.lua
- frontend/ui/widget/inputtext.lua
- plugins/opds.koplugin/opdsbrowser.lua
May be useful for calibre and other self-hosted servers.
Closes https://github.com/koreader/koreader/issues/13007.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13230)
> OPDS: raw server filenames for download

- frontend/device/pocketbook/device.lua
See https://www.mobileread.com/forums/showthread.php?p=4488302#post4488302
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13238)
> Fix typo in PocketBook init

- frontend/apps/reader/modules/readerstyletweak.lua
- frontend/dispatcher.lua
Closes https://github.com/koreader/koreader/issues/13010.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13242)
> Style tweaks: add 'Set on/off' action to Dispatcher

- frontend/ui/widget/htmlboxwidget.lua
In same cases MuPDF returns a visually single line of text as multiple lines. Merge such lines to ensure that getSelectedText works properly.
See: https://github.com/koreader/koreader/pull/13232#issuecomment-2658171531
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13276)
> HtmlBoxWidget: fix incorrect selection

- plugins/terminal.koplugin/terminputtext.lua
Closes #13272.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13273)
> [plugin] Terminal: improve LDoc module definition for terminputtext.lua

- plugins/coverbrowser.koplugin/bookinfomanager.lua
Same as in ReaderUI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13290)
> CoverBrowser BookInfoManager: handle zip

- frontend/ui/elements/timeout_android.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13332)
> [minor] Fix "Screen timeout" capitalization

- frontend/ui/data/koptoptions.lua
Fixes https://github.com/koreader/koreader/pull/12871#issuecomment-2692252499.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13350)
> KoptOptions: fix rtl

- frontend/ui/message/simpletcpserver.lua
- plugins/httpinspector.koplugin/main.lua
Fixes #13303.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13339)
> [plugin] HTTPInspector: return InputEvent on every call

- frontend/apps/filemanager/filemanagerutil.lua
- plugins/bookshortcuts.koplugin/main.lua
Executes scripts by a gesture/profile.
Use case https://github.com/koreader/koreader/discussions/13367.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13393)
> Book shortcuts: scripts support

- plugins/profiles.koplugin/main.lua
To turn the light on in the night only:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13399)
> Profiles: auto-exec time interval

- frontend/apps/reader/modules/readerhighlight.lua
- frontend/apps/reader/modules/readerrolling.lua
- frontend/apps/reader/modules/readertypeset.lua
- frontend/apps/reader/readerui.lua
- frontend/document/credocument.lua
To help chinese and cyrillic users who read a lot of txt files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13392)
> Expose txt_preformatted to UI

- frontend/apps/reader/modules/readerstatus.lua
Sorry, missed  in https://github.com/koreader/koreader/pull/13424.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13431)
> Open previous file in last book folder 2

- frontend/apps/filemanager/filemanager.lua
- frontend/apps/filemanager/filemanagerbookinfo.lua
- frontend/apps/filemanager/filemanagercollection.lua
- frontend/apps/filemanager/filemanagerfilesearcher.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/ui/widget/booklist.lua
- frontend/ui/widget/filechooser.lua
- frontend/ui/widget/menu.lua
- frontend/ui/widget/pathchooser.lua
- plugins/coverbrowser.koplugin/main.lua
- plugins/opds.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/3864. Closes https://github.com/koreader/koreader/issues/7875. Closes https://github.com/koreader/koreader/issues/10957.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13437)
> File browser: sort by metadata

- .ci/after_success_docs_translation.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13468)
> [CI] git fetch first in after_success_docs_translation.sh

- frontend/apps/filemanager/filemanagerfilesearcher.lua
Recent bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13465)
> File searcher: fix menu appearance

- plugins/vocabbuilder.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/13490.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13495)
> VocabBuilder: fix SortWidget method name

- frontend/ui/data/onetime_migration.lua
After https://github.com/koreader/koreader/pull/12932.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13499)
> One time migration: fix last migration date

- doc/Porting.md
Fixed a few hyperlinks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13504)
> Update some links in Porting.md

- platform/linux/do_debian_package.sh
Fixes https://github.com/koreader/koreader/issues/13509
It also changes slightly other metadata and removes my name from the file :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13512)
> avoid debian fonts

- plugins/calibre.koplugin/main.lua
Fixes https://github.com/koreader/koreader/issues/13478
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13513)
> calibre: add timeout to connection message

- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readermenu.lua
- plugins/hotkeys.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/13507.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13511)
> Key press handlers to show upper menu

- plugins/calibre.koplugin/search.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13484)
> [plugin] calibre: fix a nil concatenation typo

- plugins/exporter.koplugin/main.lua
Closes #13526
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13531)
> fix thirdparty exporters

- plugins/opds.koplugin/opdsbrowser.lua
To handle non-standard relations.
Closes https://github.com/koreader/koreader/issues/13520.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13535)
> OPDSBrowser: analyze acquisition mimetype

- frontend/ui/network/manager.lua
Closes #12839.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13562)
> NetworkManager: check if proxy URL can be parsed

- plugins/texteditor.koplugin/main.lua
Closes https://github.com/koreader/koreader/issues/13268.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13624)
> Text editor: fix notebook file mess

- frontend/apps/reader/modules/readerpaging.lua
Closes: #13570
Closes: #12869
Closes: #11989
Supersedes: #13560
@jonnyl2 
The crash is fixed by the second commit (reproduced and tested), the nil check is enough, please confirm.
The issues in #13570 are fixed by the second commit, i reproduced and tested with the first issue there, but it should fix the second also, please confirm
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13607)
> Fix Location Stack Issues

- frontend/apps/filemanager/filemanagercollection.lua
- frontend/readcollection.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13628)
> Collections: select books

- plugins/coverimage.koplugin/main.lua
New option to disable image rotation in cover image plugin.
Fix #12308
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13604)
> [CoverImage] Add rotate image option

- frontend/apps/reader/modules/readerfooter.lua
Closes https://github.com/koreader/koreader/issues/13696.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13702)
> Status bar: dynamic filler

- .github/workflows/build.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13725)
> ci/macos: minor tweaks

- frontend/apps/reader/modules/readerbookmark.lua
- frontend/apps/reader/modules/readerhighlight.lua
Closes #13713
|Before|After|
|---|---|
|![rh_before](https://github.com/user-attachments/assets/cfaab122-cc3d-49d3-aa63-bdba4c0f906a)|![rh_after](https://github.com/user-attachments/assets/ef0167f3-3722-48bc-ac81-08f1402c8e39)|
|![bd_before](https://github.com/user-attachments/assets/478ad7f5-8e00-4b7c-9515-269b7daa05f6)|![bd_after](https://github.com/user-attachments/assets/116a83c9-7adc-40f9-98ae-0f9d8735f051)|
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13735)
> ReaderHighlight, ReaderBookmark: Highlight button labels, Bookmark details button order

- frontend/apps/reader/modules/readerfooter.lua
Fixes appearance with different combinations of settings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13739)
> Status bar: dynamic filler and presets fixes

- plugins/opds.koplugin/opdsbrowser.lua
Avoid delay of the message when downloading starts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13742)
> OPDSBrowser: fix "Downloading…" message

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13767)
> ci: bump docker images

- doc/Building.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13775)
> cmake: bump minimum required version to 3.17.5

- frontend/apps/reader/modules/readerannotation.lua
- frontend/apps/reader/modules/readerbookmark.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13751)
> Annotations export/import: merge (keep existing annotations)

- plugins/newsdownloader.koplugin/main.lua
Regression in #13407.
Reported in <https://github.com/koreader/koreader/discussions/13752#discussioncomment-13166619>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13799)
> [plugin] NewsDownloader: fix RSS feeds

- plugins/calibre.koplugin/wireless.lua
Regression from #13704.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13805)
> calibre: fix setting inbox from menu

- plugins/opds.koplugin/opdsbrowser.lua
Bulk downloads currently don't work for feeds that need auth because the current `downloadFile` method gets credentials from the root catalog, which isn't set in the downloadList view. Fixing by storing credentials alongside the URL and title when an item is saved for download so that we can use them later when the download actually happens.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13851)
> Fixing OPDS bulk download auth

- platform/mac/do_mac_bundle.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13861)
> macos: no need to bundle tar anymore

- make/android.mk
Cf. https://github.com/koreader/koreader-base/pull/2088.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13796)
> libarchive based android luajit launcher

- plugins/profiles.koplugin/main.lua
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13873)
> Profiles auto-exec "On showing folder": add "path is (not) equal" conditions

- frontend/apps/filemanager/filemanagercollection.lua
Closes https://github.com/koreader/koreader/issues/13843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13898)
> Collections: fix manual sorting

- plugins/vocabbuilder.koplugin/main.lua
Partially completes #13261.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13876)
> VocabBuilder plugin: show copy button on duplication when adding

- plugins/newsdownloader.koplugin/main.lua
Accidentally changed in #13806.
Closes #13933.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13945)
> [plugin] NewsDownloader: fix getEmptyFeed() call

- spec/unit/newsdownloader_spec.lua
Cf. https://github.com/koreader/koreader/pull/13953#issuecomment-2972614736.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13954)
> tests: fix newsdownloader tests isolation

- doc/Building.md
- doc/Unit_tests.md
- kodev
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13953)
> update building & testing docs + kodev tweak

- plugins/calibre.koplugin/metadata.lua
- plugins/calibre.koplugin/wireless.lua
Fixes #12922. This PR only fixes calibre metadata search functionality in koreeader
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13920)
> [Calibre] React to SEND_BOOK_METADATA opcode

- frontend/readcollection.lua
(1) Connected folders:
-if a user has entered file types to be added to a collection, do not call `hasProvider`;
-parse file types string (that can contain several comma separated types) out of the `lfs.dir` loop.
(2) Adding a book to several collections: call `lfs.attributes` only once.
Interesting collection connecting/sorting speed measurement in
https://www.mobileread.com/forums/showthread.php?p=4517852#post4517852
and the following comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/13958)
> ReadCollection: minor speedup

- Makefile
- frontend/ui/otamanager.lua
- tools/mkrelease.sh
**Increase re-use:**
- use the latest stable release tag date for all files modification time (which does change `Version:getBuildDate()` for nightlies)
- tweak tar command tar to ignore read-errors (so missing files don't result in a failure to create the installation archive): no point in trashing the archive, especially considering the fact that if the OTA update was canceled, a subsequent attempt would re-use that (potentially incomplete) archive
**Comparison:**
Default:
| re-used / fetched  | v2025.04-67        | v2025.04-68        | v2025.04-72        | v2025.04-74        |
|:-                  |                  -:|                  -:|                  -:|                  -:|
| v2025.04           |   66.5 % / 25.5 MB |   66.3 % / 25.5 MB |   65.1 % / 25.5 MB |   64.2 % / 25.6 MB …
> improve ota updates

- doc/Building.md
Reverts koreader/koreader#14030
See https://github.com/koreader/koreader/issues/14029#issuecomment-3043795821
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14033)
> Revert "doc: fix macOS build instructions"

- frontend/ui/widget/touchmenu.lua
Closes https://github.com/koreader/koreader/issues/14039.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14040)
> TouchMenu: fix

- plugins/terminal.koplugin/main.lua
- plugins/terminal.koplugin/terminputtext.lua
Fixes #14049.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14059)
> [plugin] Terminal Emulator: implement delWord for terminal

- frontend/apps/filemanager/filemanagercollection.lua
- frontend/document/document.lua
- frontend/document/koptinterface.lua
- frontend/ui/widget/bookmapwidget.lua
- frontend/ui/widget/inputdialog.lua
Correct a bunch of typos in comments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14079)
> Typos (harmless)

- plugins/autowarmth.koplugin/main.lua
Fix quirk mentioned in https://github.com/koreader/koreader/discussions/14103#discussioncomment-13920615
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14104)
> [Autowarmth] Fix nightmode only in non Expert-Mode

- frontend/device/android/device.lua
There you go @carlosaya.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14156)
> Add Go Color 7 II to devices that follow gravity

- make/remarkable.mk
made an oopsie that caused it to not compile properly
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14175)
> fix/remarkable: indentation

- plugins/vocabbuilder.koplugin/main.lua
This closes #14123;
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14127)
> VocabBuilder.koplugin: supports removing word in-place after addition

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14178)
> ci: bump docker image

- frontend/apps/cloudstorage/cloudstorage.lua
- frontend/apps/filemanager/filemanagermenu.lua
- frontend/apps/reader/modules/readermenu.lua
- frontend/dispatcher.lua
Closes https://github.com/koreader/koreader/issues/14168. Closes https://github.com/koreader/koreader/issues/14176.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14189)
> CloudStorage: add action in Dispatcher

- plugins/opds.koplugin/opdsbrowser.lua
This PR fixes a bug where books downloaded via OPDS could be saved without a file extension, making them un-openable until manually renamed.
This typically occurs when the "Use server filenames" option is enabled, and the OPDS server provides an incomplete filename. The root cause is that the filename retrieval logic was too trusting of the server's response in two cases:
1.  The `content-disposition` header provides a filename that is missing the file extension.
2.  The fallback logic, which parses the filename from the URL, fails when the download link is a dynamic endpoint (e.g., `/download?id=123`) instead of a direct link to a file (e.g., `/book.cbz`).
The new logic checks the retrieved filename. If it's missing an extension, it appends the correct `filetype` that KOReader expects …
> Fix(OPDS): Ensure downloaded files have a file extension

- plugins/exporter.koplugin/base.lua
- plugins/exporter.koplugin/clip.lua
- plugins/exporter.koplugin/main.lua
- spec/unit/exporter_plugin_main_spec.lua
Customizable export filename. Closes https://github.com/koreader/koreader/issues/12587. Closes https://github.com/koreader/koreader/issues/14110.
Other minor fixes and optimizations. Closes https://github.com/koreader/koreader/issues/13705.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14212)
> Export highlights: customizable export filename

- frontend/apps/reader/modules/readerfooter.lua
Closes #14231.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14232)
> ReaderFooter: skip dynamic filler in items cycling

- frontend/device/remarkable/device.lua
Yep, new device is now out and here's PR to support it! (Though I don't have one so had to rely on other owners for informations)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14284)
> feat/remarkable: Initial reMarkable Paper Pro Move support

- frontend/ui/uimanager.lua
- plugins/readtimer.koplugin/main.lua
- Closes #14275
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14280)
> ReadTimer: use previous scheduled instance

- frontend/ui/data/dictionaries.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14302)
> feat: add reader.dict monolingual dictionaries

- frontend/apps/reader/modules/readerpaging.lua
* Follow-up to #14267. 
* Closes #14323.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14324)
> ReaderPaging: fix page turn by keys

- frontend/apps/filemanager/filemanagerbookinfo.lua
Add a "pages left in chapter" option to custom text
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14327)
> Add "pages left in chapter" option to custom footer text

- frontend/ui/widget/progressbardialog.lua
Otherwise nothing is shown on my Kindle (kindlepw2).
Close #14179.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14182)
> ProgressbarDialog: fix progress bar fill color

- frontend/ui/data/keyboardlayouts/keypopup/sr_popup.lua
- frontend/ui/data/keyboardlayouts/sr_keyboard.lua
- frontend/ui/widget/virtualkeyboard.lua
This adds Serbian cyrillic keyboard layout.
It is based on very good English layout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14338)
> Add Serbian keyboard layout

- .github/workflows/build.yml
Reduce differences with base.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14340)
> ci/macos: tweaks

- make/appimage.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14351)
> appimage: support aarch64

- frontend/pluginloader.lua
- plugins/SSH.koplugin/main.lua
Closes #14316.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14318)
> PluginLoader: call stop method on plugin when disabling

- frontend/document/djvudocument.lua
- frontend/document/koptinterface.lua
- tools/bench/djvu_getpagetextboxes_bench.lua
Closes <https://github.com/koreader/koreader/issues/2943>.
(rebase me)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14350)
> DjVu: flatten nested text layer

- plugins/SSH.koplugin/main.lua
https://github.com/jospalau/koreader/commit/d71d1348441102418d9dbecaa043dc1b4256a39d#commitcomment-166700608
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14370)
> SSH: fix typo, 'show' not 'Show'

- make/android.mk
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14366)
> Android: auto-grant MANAGE_EXTERNAL_STORAGE for faster dev testing

- plugins/newsdownloader.koplugin/epubdownloadbackend.lua
- plugins/newsdownloader.koplugin/feed_config.lua
- plugins/newsdownloader.koplugin/feed_view.lua
- plugins/newsdownloader.koplugin/main.lua
Block CSS elements like share widgets or "More like this" sections. Enabled with the "Enable filter" button. Reuses some logic from the filtering function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14383)
> [News] Block CSS elements

- frontend/ui/screensaver.lua
Closes #14398.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader/14402)
> Sleep screen: fix image in landscape mode
